// db/seed_advice_aries.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Aries ascendant native with:
//   Ascendant: Aries
//   Natal placements (sidereal Lahiri):
//     Sun=5th (Leo, own)  Moon=4th (Cancer, own)  Mercury=6th (Virgo, own+exalted)
//     Venus=12th (Pisces, exalted)  Mars=1st (Aries, own — Ruchaka Yoga)
//     Jupiter=9th (Sagittarius, own)  Saturn=10th (Capricorn, own — Sasa Yoga)
//     Rahu=5th (Leo, conjunct Sun)  Ketu=11th (Aquarius)
//
// All 530 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose advice-specific interpretations, then run:
//
//   node db/seed_advice_aries.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./advice');

const ASCENDANT = 'Aries';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mars ruler of the 1st House in the 1st House', description: 'Lead today. Make the first move; do not wait for permission. Whatever has been pending a decision — sign it, ship it, send it. Skip meetings that exist only to confirm what you already know. Pace and directness are your edge; consensus-building is a tax.' },
  { name: 'Venus ruler of the 2nd House in the 12th House', description: 'Speak quietly today. The voice and the wallet do their work in private channels — write the letter rather than make the call, defer the public conversation about money, attend to the foreign correspondence. Pleasure is permitted in moderation; pleasure-spending is not.' },
  { name: 'Mercury ruler of the 3rd House in the 6th House', description: 'Send the precise message. Today rewards documentation over conversation, and clarity over warmth. The difficult email you have been drafting in your head — write it, edit twice, send. Younger colleagues will execute sharply if instructions are crisp.' },
  { name: 'Moon ruler of the 4th House in the 4th House', description: 'Stay close to home today. Cancel the away-meeting if you can; the kitchen-table version of any decision is the truer one. Call mother. Tend to the dwelling. Real-estate paperwork lands well today.' },
  { name: 'Sun ruler of the 5th House in the 5th House', description: 'Be visibly creative today. Take the stage you have been declining; pitch the thing; perform the role you trained for. Mentees and protégés respond. Avoid the trap of confusing audience-pleasing with creative substance — make what you would make if no one was watching.' },
  { name: 'Mercury ruler of the 6th House in the 6th House', description: 'Confront the conflict today. The grievance you have been holding, the debt you have been postponing, the audit you have been deferring — close it now. The mind is in supreme command of detail; deploy it surgically. Soften the tone, not the precision.' },
  { name: 'Venus ruler of the 7th House in the 12th House', description: 'Tend to the partnership in private today. Quiet acts — a note, a touch, an unscheduled return home — outweigh public displays. Foreign or distant partners want a check-in. The shadow: avoid public commentary on private partnership matters.' },
  { name: 'Mars ruler of the 8th House in the 1st House', description: 'Move through the body today. Workout, fast, fight class, surgical-style cleaning of a closet, sweat. Old emotional residue clears physically. The mind alone cannot reach what the body has been holding.' },
  { name: 'Jupiter ruler of the 9th House in the 9th House', description: 'Honor the principle today. Where there is a choice between expedience and ethics, choose ethics — even at cost. The mentor or senior figure who corrected you long ago was right; the lesson surfaces today as a chance to apply it. Foreign or higher-learning conversations land well.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Build for the long arc today. Decisions made today should answer to the version of you ten years from now, not the one with this quarter\'s metrics. Slow, structural moves favored. Skip the impulse purchase, the impulse pivot, the impulse promise.' },
  { name: 'Saturn ruler of the 11th House in the 10th House', description: 'Cultivate the senior network today. The elder colleague, the formal alliance, the structured friendship — these compound. Send the formal greeting; accept the structured invitation; defer the casual social ask if it conflicts.' },
  { name: 'Jupiter ruler of the 12th House in the 9th House', description: 'Spend on principle today, not on pleasure. Charitable expenditure, books, retreats, foreign travel — all favored. Ordinary indulgent spending will feel hollow tomorrow. Sleep slightly more.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (6)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 5th (Dispositor)', description: 'Take the stage today. The bold creative move, the public declaration, the visible mentor act. Verify each ambitious leap against a quieter inner standard — but do not skip the leap.' },
  { name: 'Moon in 4th (Dispositor)', description: 'Anchor in home today. Cook, call mother, tend the dwelling, host privately. Decisions made at the kitchen table outlast the ones made in the boardroom.' },
  { name: 'Mercury in 6th (Dispositor)', description: 'Adjudicate today. The peer conflict, the family-system grievance, the debt that has been wandering — close one of them with documentation. Soften the tone; do not soften the precision.' },
  { name: 'Jupiter in 9th (Dispositor)', description: 'Choose the principle today. The ethical move pays back over years, the expedient one costs you in months. Foreign or higher-learning gestures land well.' },
  { name: 'Mars in 1st (Dispositor)', description: 'Lead from the front today. The cold call, the founder declaration, the bold ask. The energy is yours to spend.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'Honor the long arc today. Slow, structural, irreversible moves favored over fast ones. Defer the impulsive decision twenty-four hours.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual visibility window. Lead with the persona; take on a public mantle; make the bold declaration about who you are this year.' },
  { name: 'Sun Transits the 2nd House', description: 'Speak about money openly. Negotiate compensation, settle family-finance, record the talk. Throat-care matters.' },
  { name: 'Sun Transits the 3rd House', description: 'Push the courageous communication. The deferred message, the bold proposal, the sibling conversation — all favored.' },
  { name: 'Sun Transits the 4th House', description: 'Anchor in home and mother for the month. Real-estate decisions, family-business inflection, work-from-home phase favored.' },
  { name: 'Sun Transits the 5th House', description: 'Annual peak creative-visibility. Launch, declare, propose, perform. Take the stage.' },
  { name: 'Sun Transits the 6th House', description: 'Best window of the year for confronting conflict. The audit, the difficult HR talk, the regulatory filing, the debt-recovery — all close cleanly.' },
  { name: 'Sun Transits the 7th House', description: 'Annual peak partnership-visibility. Sign the contract, make the public alliance, address the spouse-or-counterparty directly.' },
  { name: 'Sun Transits the 8th House', description: 'Surgical decisions. Restructurings, succession, regulatory navigation, deep transformations land.' },
  { name: 'Sun Transits the 9th House', description: 'Honor the principle. Take the international call, write the publishing piece, accept the senior blessing or test.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility. Take the chief role, demand the title, lead the competitive pitch.' },
  { name: 'Sun Transits the 11th House', description: 'Receive recognition with detachment. Bonus, board, network news lands — feel it without grasping.' },
  { name: 'Sun Transits the 12th House', description: 'Behind-the-scenes month. White papers, foreign correspondence, retreats, confidential mandates favored.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional charge on persona. Lead warmly today; reach out with extra warmth.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional warmth around money and voice. Speak when warm, defer when overcooked.' },
  { name: 'Moon Transits the 3rd House', description: 'Send the warm message. Soften peer-and-sibling communications.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-emotional peak. Cook, call mother, work from home if possible.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creativity. Channel into a project; avoid impulsive speculation.' },
  { name: 'Moon Transits the 6th House', description: 'Empathetic conflict-resolution. Soften the technical tone.' },
  { name: 'Moon Transits the 7th House', description: 'Read the partner\'s mood before pushing terms.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight; defer non-urgent decisions two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward principle, foreign, mentor. Capture the big-vision; defer execution.' },
  { name: 'Moon Transits the 10th House', description: 'Public-reputation sensitivity. Opening line, posture, dress matter more today.' },
  { name: 'Moon Transits the 11th House', description: 'Reach out to the network with measured warmth.' },
  { name: 'Moon Transits the 12th House', description: 'Sleep more. Quiet, behind-scenes, foreign-correspondence days.' },
  { name: 'Mercury Transits the 1st House', description: 'Refresh the personal narrative. CV, bio, founder-story; bold intro letters.' },
  { name: 'Mercury Transits the 2nd House', description: 'Patient communication around money and voice. Excellent for paperwork, salary cases.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak writing/effort/peer-leadership window of any quarter. Ship documents, send proposals.' },
  { name: 'Mercury Transits the 4th House', description: 'Family/home/real-estate paperwork. Lease drafts, mother-letters.' },
  { name: 'Mercury Transits the 5th House', description: 'Bold creative communication. Verify before sending — the volume runs hot.' },
  { name: 'Mercury Transits the 6th House', description: 'Peak surgical-mind window. Audit reports, regulatory filings, technical specs.' },
  { name: 'Mercury Transits the 7th House', description: 'Diplomatic contract negotiation in writing.' },
  { name: 'Mercury Transits the 8th House', description: 'Investigative depth-writing. Forensic reports, due diligence, deep talks.' },
  { name: 'Mercury Transits the 9th House', description: 'Visionary writing window. Foreign correspondence, philosophical drafts.' },
  { name: 'Mercury Transits the 10th House', description: 'Disciplined career-communication. Press releases, formal status memos.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp-but-detached network communication. Structured outreach.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential and devotional correspondence. Watch leaks.' },
  { name: 'Venus Transits the 1st House', description: 'Personal warmth peaks. Charm-driven asks favored.' },
  { name: 'Venus Transits the 2nd House', description: 'Soft window for money and voice. Indulge mindfully.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful peer/sibling communication.' },
  { name: 'Venus Transits the 4th House', description: 'Beautiful home/mother/real-estate window. Sign the lease, host the gathering.' },
  { name: 'Venus Transits the 5th House', description: 'Peak creative-aesthetic visibility. Take the spotlight.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic service excellence. Difficult colleagues become receptive.' },
  { name: 'Venus Transits the 7th House', description: 'Peak partnership-warmth. Sign the JV, formalize the long-pending alliance.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic intimacy and shared-resources negotiation.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful foreign engagement and ethical advisory.' },
  { name: 'Venus Transits the 10th House', description: 'Softens public face. Brand-driven public moves.' },
  { name: 'Venus Transits the 11th House', description: 'Graceful but cool gains and networks. Bonus events favored.' },
  { name: 'Venus Transits the 12th House', description: 'Annual peak foreign-luxury-devotional window. Hidden patrons surface.' },
  { name: 'Mars Transits the 1st House', description: 'Powerful self-action window. Launch the founder move; sign the bold paper.' },
  { name: 'Mars Transits the 2nd House', description: 'Watch sharp speech. Data-back any aggressive money-asks.' },
  { name: 'Mars Transits the 3rd House', description: 'Fierce effort/communication. Ship under deadline; defend the document.' },
  { name: 'Mars Transits the 4th House', description: 'Heated home disputes resolve. Decisive real-estate action favored; soften family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Hot creative-speculative drive. Verify before leaping.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable conflict-combat. Win the workplace dispute.' },
  { name: 'Mars Transits the 7th House', description: 'Friction in partnerships. Defer contract-close seven to ten days.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical action in transformation chamber. Restructure decisively.' },
  { name: 'Mars Transits the 9th House', description: 'Bold dharma-action. Foreign-engagement push favored.' },
  { name: 'Mars Transits the 10th House', description: 'One of the strongest career-action windows of any two-year cycle.' },
  { name: 'Mars Transits the 11th House', description: 'Assertive network/gain push. Win the bonus negotiation.' },
  { name: 'Mars Transits the 12th House', description: 'Heated foreign/luxury/hidden zone. Sleep loss possible.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual self-expansion. Take the role-elevation; declare the bigger ambition.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom on money/voice/family-finance. Long-term resource decisions blessed.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on writing/peers. Major publications; peer deepenings.' },
  { name: 'Jupiter Transits the 4th House', description: 'Peak home/family/real-estate expansion year.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major creative-launch year. Take the visible authority.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom into service/conflict. Health-watch — control portions.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom into partnership. Anchor JV; marriage-grade commitment.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into transformation. Inheritance/severance favorably resolves.' },
  { name: 'Jupiter Transits the 9th House', description: 'Among the most blessed years of any twelve-year cycle.' },
  { name: 'Jupiter Transits the 10th House', description: 'Peak career-zenith year. Take the chief role; accept the prestige offer.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom on detached gains. Bonus and equity compound.' },
  { name: 'Jupiter Transits the 12th House', description: 'Peak foreign/luxury/devotional year. Foreign sabbatical favored.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on body/identity. Slow down; build for permanence.' },
  { name: 'Saturn Transits the 2nd House', description: 'Discipline on income/voice. Slow but real wage growth.' },
  { name: 'Saturn Transits the 3rd House', description: 'Discipline on writing/peers/effort. Long-form authorship builds.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy home/mother weight. Real-estate decisions feel structural.' },
  { name: 'Saturn Transits the 5th House', description: 'Creative authority tested. Mentee-relationships restructure.' },
  { name: 'Saturn Transits the 6th House', description: 'Best multi-year window for service-mastery.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnerships.' },
  { name: 'Saturn Transits the 8th House', description: 'Major life restructuring window. Hold steady.' },
  { name: 'Saturn Transits the 9th House', description: 'Discipline on dharma/foreign/teacher domain.' },
  { name: 'Saturn Transits the 10th House', description: 'The 2.5-year window that seeds the next 30-year career chapter.' },
  { name: 'Saturn Transits the 11th House', description: 'Disciplined gains/networks. The network purges what is no longer dharmic.' },
  { name: 'Saturn Transits the 12th House', description: 'Discipline on foreign/luxury/devotional. Sabbaticals turn structural.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive self-reinvention. Verify each leap.' },
  { name: 'Rahu Transits the 2nd House', description: 'Obsessive ambition around money/voice. Beware get-rich-quick schemes.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive communication push. Verify before publishing.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home/mother/relocation. Foreign-relocation pull strong.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month peak ambition window. Verify integrity.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat a powerful enemy or chronic issue.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive partnership chapter. Verify carefully.' },
  { name: 'Rahu Transits the 8th House', description: 'Obsessive transformation chapter. Stay grounded.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign-fortune obsession. Vet the dharma channel.' },
  { name: 'Rahu Transits the 10th House', description: 'Obsessive career-elevation push. Vet legitimacy.' },
  { name: 'Rahu Transits the 11th House', description: 'Obsessive gains/networks chapter. Stay clean.' },
  { name: 'Rahu Transits the 12th House', description: 'Obsessive foreign/luxury/devotional chapter. Verify each path.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping. Sit; do not over-rebuild.' },
  { name: 'Ketu Transits the 2nd House', description: 'Detachment from money/voice. Don\'t panic-renegotiate.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from peers/writing. Solo deep-work favored.' },
  { name: 'Ketu Transits the 4th House', description: 'Home/mother detachment. Sell-property impulses.' },
  { name: 'Ketu Transits the 5th House', description: 'Creative-authority eclipse. Old ambition feels hollow.' },
  { name: 'Ketu Transits the 6th House', description: 'Service detachment. Old conflicts dissolve without victory.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership detachment. Old JVs unwind.' },
  { name: 'Ketu Transits the 8th House', description: 'Transformation acceleration. Old chapters end abruptly.' },
  { name: 'Ketu Transits the 9th House', description: 'Dharma detachment. Old gurus feel finished.' },
  { name: 'Ketu Transits the 10th House', description: 'Career eclipse. Old roles feel hollow.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month deep purification of network/gains motivations.' },
  { name: 'Ketu Transits the 12th House', description: 'Foreign/luxury/devotional dissolution.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates. Lead with persona today.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish the public-face.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the stage.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Lock in declarations.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Career-visibility window. Demand the title; lead the pitch.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-visibility day.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional warmth on persona. Reach out warmly.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public reputation.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional-career day.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-communication. Refresh the personal narrative.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak self-communication day.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp career-communication. Press releases, status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Personal warmth peaks. Charm-asks favored.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens public face. Aesthetic public moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-career day.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold body-anchored self-action.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold career action. Launch flagship moves.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak career-action day.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the role-elevation.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the chief role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body/identity. Simplify.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public work tested for staying power.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak career-discipline day.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion. Watch obsession.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Window begins.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic career-visibility expansion.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Window begins.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. The old persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit with the dissolution.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. Don\'t over-defend a fading role.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Window begins.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. The role dissolves quietly.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning. Old hierarchies collapse; rebuild authority.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year reckoning begins. Position for the long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak transformation day. Hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The transformation chapter completes.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the foreign and devotional channel. Stay flexible.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Window closes. Integrate; release what didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 5th house', description: 'Birthday-window ego activation. Best for the bold creative move.' },
  { name: 'Sun aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Sun in 5th house : Exact', description: 'Peak day. Launch, declare, take the platform.' },
  { name: 'Sun aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Moon in 4th house', description: 'Visibility through home/mother. Real-estate moves favored.' },
  { name: 'Sun aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Moon in 4th house : Exact', description: 'Peak day. Sign the lease; host mother.' },
  { name: 'Sun aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mercury in 6th house', description: 'Solar fire on conflict-resolution. Settle the case.' },
  { name: 'Sun aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mercury in 6th house : Exact', description: 'Peak day. Run the elimination.' },
  { name: 'Sun aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Venus in 12th house', description: 'Solar light on foreign/devotional zone. Take the foreign call; visit the retreat.' },
  { name: 'Sun aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Sun aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mars in 1st house', description: 'Solar fire on warrior identity. Bold founder declarations.' },
  { name: 'Sun aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mars in 1st house : Exact', description: 'Peak day. Lead the charge.' },
  { name: 'Sun aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Jupiter in 9th house', description: 'Solar light on principle. Honor the dharma.' },
  { name: 'Sun aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Jupiter in 9th house : Exact', description: 'Peak day. Sign the foreign deal.' },
  { name: 'Sun aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on career-mastery. Accept the chief role.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Rahu in 5th house', description: 'Ambition-amplified ego. Verify integrity twice.' },
  { name: 'Sun aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Rahu in 5th house : Exact', description: 'Peak day. Take the bold leap with verification.' },
  { name: 'Sun aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Ketu in 11th house', description: 'Solar light on detached-gains. Receive without grasping.' },
  { name: 'Sun aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Sun aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Sun in 5th house', description: 'Emotional charge on creative authority. Make the heart-led move.' },
  { name: 'Moon aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Moon in 4th house', description: 'Monthly home-emotional peak. Cook; call mother.' },
  { name: 'Moon aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mercury in 6th house', description: 'Empathetic conflict-resolution. Soft tones win today.' },
  { name: 'Moon aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Venus in 12th house', description: 'Emotional warmth on retreat/foreign. Soft, soothing day.' },
  { name: 'Moon aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mars in 1st house', description: 'Emotional charge on body. Lead from heart and gut together.' },
  { name: 'Moon aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Jupiter in 9th house', description: 'Emotional pull toward principle/foreign/mentor.' },
  { name: 'Moon aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on reputation. Read the room before pushing terms.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Rahu in 5th house', description: 'Emotional charge on ambition. Watch obsessive-craving.' },
  { name: 'Moon aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Ketu in 11th house', description: 'Emotional detachment from network. Don\'t over-rebuild.' },
  { name: 'Moon aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Moon aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Sun in 5th house', description: 'Sharp creative-communication. Pitch decks favored.' },
  { name: 'Mercury aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Moon in 4th house', description: 'Emotionally tuned home/family writing.' },
  { name: 'Mercury aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mercury in 6th house', description: 'Peak surgical-mind window of any quarter. Audit, file, ship the spec.' },
  { name: 'Mercury aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mercury in 6th house : Exact', description: 'Peak day. Ship the masterpiece document.' },
  { name: 'Mercury aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Venus in 12th house', description: 'Graceful foreign/devotional writing.' },
  { name: 'Mercury aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mars in 1st house', description: 'Punchy, bold self-communication.' },
  { name: 'Mercury aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Jupiter in 9th house', description: 'Visionary writing window.' },
  { name: 'Mercury aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Disciplined career-communication.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Rahu in 5th house', description: 'Bold, viral creative communication. Verify before sending.' },
  { name: 'Mercury aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Ketu in 11th house', description: 'Sharp-detached network communication.' },
  { name: 'Mercury aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Mercury aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Sun in 5th house', description: 'Graceful creative-authority. Aesthetic launches favored.' },
  { name: 'Venus aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Moon in 4th house', description: 'Beautiful home/mother window.' },
  { name: 'Venus aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mercury in 6th house', description: 'Diplomatic service excellence.' },
  { name: 'Venus aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Venus in 12th house', description: 'Peak foreign/luxury/devotional window.' },
  { name: 'Venus aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mars in 1st house', description: 'Warmth on persona. Charm-driven asks.' },
  { name: 'Venus aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Jupiter in 9th house', description: 'Graceful foreign/dharma window.' },
  { name: 'Venus aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Softens public face.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Rahu in 5th house', description: 'Glamour-amplified creative window. Verify substance.' },
  { name: 'Venus aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Ketu in 11th house', description: 'Graceful but cool gains/networks.' },
  { name: 'Venus aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Sun in 5th house', description: 'Fiery creative push. Verify ambition does not inflate.' },
  { name: 'Mars aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Moon in 4th house', description: 'Heated home/family push. Decisive real-estate moves.' },
  { name: 'Mars aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mercury in 6th house', description: 'Fiery surgical-mind push. Win the conflict.' },
  { name: 'Mars aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Venus in 12th house', description: 'Heated foreign/luxury zone. Behind-scenes power-plays.' },
  { name: 'Mars aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mars in 1st house', description: 'Peak self-action window of any two-year cycle.' },
  { name: 'Mars aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Jupiter in 9th house', description: 'Fiery dharma push.' },
  { name: 'Mars aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Fiery career-mastery push.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Rahu in 5th house', description: 'Fiery ambition with shadow. Verify twice.' },
  { name: 'Mars aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Ketu in 11th house', description: 'Heated network push with detachment.' },
  { name: 'Mars aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Mars aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Sun in 5th house', description: 'Wisdom on creative-authority. Major launch favored.' },
  { name: 'Jupiter aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Moon in 4th house', description: 'Wisdom on home/mother. Real-estate expansion.' },
  { name: 'Jupiter aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mercury in 6th house', description: 'Wisdom on conflict/service. Difficult clients become teachers.' },
  { name: 'Jupiter aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Venus in 12th house', description: 'Peak foreign/luxury/devotional expansion.' },
  { name: 'Jupiter aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mars in 1st house', description: 'Wisdom on warrior identity. Take the larger role.' },
  { name: 'Jupiter aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Jupiter in 9th house', description: 'Peak dharma window of any twelve-year cycle.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on career-mastery.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Rahu in 5th house', description: 'Wisdom on ambition. Fame anchors in dharma.' },
  { name: 'Jupiter aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Ketu in 11th house', description: 'Wisdom on detached gains. Honor without grasping.' },
  { name: 'Jupiter aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Jupiter aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Sun in 5th house', description: 'Structural test of creative-authority. Speculation tightens.' },
  { name: 'Saturn aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Moon in 4th house', description: 'Heaviness on home/mother.' },
  { name: 'Saturn aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mercury in 6th house', description: 'Favorable for service-mastery.' },
  { name: 'Saturn aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Venus in 12th house', description: 'Multi-year discipline on foreign/devotional.' },
  { name: 'Saturn aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mars in 1st house', description: 'Heavy structural test of warrior-identity.' },
  { name: 'Saturn aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Jupiter in 9th house', description: 'Discipline on dharma/foreign domain.' },
  { name: 'Saturn aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Peak career-restructure window of any thirty-year cycle.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Rahu in 5th house', description: 'Discipline on ambition. Fame-bubbles deflate.' },
  { name: 'Saturn aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Ketu in 11th house', description: 'Disciplined gains. Network purifies.' },
  { name: 'Saturn aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Saturn aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Sun in 5th house', description: 'Peak ambition window of any eighteen-year cycle.' },
  { name: 'Rahu aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Sun in 5th house : Exact', description: 'Peak day. Verify integrity.' },
  { name: 'Rahu aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Moon in 4th house', description: 'Obsessive home/mother chapter.' },
  { name: 'Rahu aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mercury in 6th house', description: 'Favorable. Defeat a powerful enemy.' },
  { name: 'Rahu aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Venus in 12th house', description: 'Obsessive foreign/luxury pull.' },
  { name: 'Rahu aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mars in 1st house', description: 'Obsessive founder-identity push.' },
  { name: 'Rahu aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Jupiter in 9th house', description: 'Foreign-fortune obsession.' },
  { name: 'Rahu aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Obsessive career-elevation push.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Rahu in 5th house', description: 'Eighteen-year apex of ambition cycle. Anchor in dharma.' },
  { name: 'Rahu aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Ketu in 11th house', description: 'Generational reckoning of network/gains vs. ambition.' },
  { name: 'Rahu aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Rahu aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Sun in 5th house', description: 'Creative-authority eclipse. Old ambition feels hollow.' },
  { name: 'Ketu aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Sun in 5th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Moon in 4th house', description: 'Home/mother detachment.' },
  { name: 'Ketu aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Moon in 4th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mercury in 6th house', description: 'Service detachment. Old conflicts dissolve quietly.' },
  { name: 'Ketu aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mercury in 6th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Venus in 12th house', description: 'Foreign/luxury/devotional dissolution.' },
  { name: 'Ketu aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Venus in 12th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mars in 1st house', description: 'Founder-identity stripping.' },
  { name: 'Ketu aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mars in 1st house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Jupiter in 9th house', description: 'Dharma detachment. Old gurus feel finished.' },
  { name: 'Ketu aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Jupiter in 9th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Career eclipse. Old roles feel hollow.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Rahu in 5th house', description: 'Generational ambition vs. detachment reckoning.' },
  { name: 'Ketu aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Rahu in 5th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Ketu in 11th house', description: 'Eighteen-year apex of detachment cycle.' },
  { name: 'Ketu aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Ketu in 11th house : Exact', description: 'Peak day.' },
  { name: 'Ketu aspect Ketu in 11th house : Ends', description: 'Window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
