// db/seed_career_virgo.js
//
// Per-ascendant fill-in seed for the **career** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga)
//     Venus=7th (Pisces, exalted — Malavya Yoga)
//     Mars=8th (Aries, own — 8L-in-8 Vipareet)
//     Jupiter=4th (Sagittarius, own — Hamsa Yoga)
//     Saturn=5th (Capricorn, own)
//     Rahu=3rd (Scorpio)  Ketu=9th (Taurus)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose career-specific interpretations, then run:
//
//   node db/seed_career_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./career');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'The mind is the brand. Analyst, editor, researcher, surgeon, engineer, accountant, code-craftsman, technical writer, classifier, taxonomist, fact-checker, critic — circuits where surgical precision *is* the deliverable. The work prizes detail, discrimination, methodical execution. You compound through small, exact deliveries that compound into a reputation for irreplaceable accuracy. The shadow: perfectionism that stalls the ship-decision; the analytic mind sometimes audits the work past the point a launch was ready.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'Income arrives through partnership. Spouse, principal client, JV co-founder, anchor counterparty, agent, manager, broker — these are the people who route money to your accounts. Industries: deal-led advisory, client services, marriage-broking, agent-rep work, partnership consulting, beauty-and-luxury distribution, art dealing, hospitality joint-ventures, mediation. Your earnings move when you sit across the table from someone, not when you sit alone with a spreadsheet. The shadow: financial dependency on partner-mood — diversify the channel before the relationship has the leverage.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'Courage routes through crisis. Surgical interventions, restructuring fights, audit warfare, due-diligence demolitions, investigative journalism, forensic accounting, crisis-management, succession battles. Your most decisive communication arrives in the high-stakes moment when the stakes are existential — that is your terrain. Industries: surgery, military intelligence, corporate-restructuring, occult research with edge, security consulting, investigative work. The shadow: addiction to the crisis cycle — when life is calm, you may unconsciously detonate something to feel sharp again.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'Hamsa Yoga on the home throne. The home itself is a wisdom-engine: the property, the family business, the work-from-home founder seat, the school-from-home, the ashram-style office. Real-estate compound. Educational institutions tied to the home. Hospitality with a teaching edge. Mother and matriarchal teachers. The most stable career chapters root in property and in lineage — the building that you own, the school that bears your name, the family business whose dharma you steward. The shadow: idealization of the home that quietly becomes refusal to leave it when the dharma calls you abroad.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Disciplined creative-intellect. Long-thesis research, multi-year writing projects, slow-build courses, structured speculation, methodical investment, classical-music or classical-art mastery, doctoral programs, deep-craft mentorship of mentees. Saturn-in-own-sign in 5H produces work that takes a decade to mature and then lasts a century. The shadow: the work-pleasure may run cold; remember to play sometimes, not just labor.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'Adversary-management compounds inside the creative engine. The lawsuit becomes a book; the audit becomes a thesis; the chronic enemy becomes the case-study. Vipareet potential — turn obstacles into intellectual product. Industries: legal-academic crossover, regulatory writing, forensic-creative work, investigative scholarship. The shadow: cultivating enemies for material — let some fights stay un-fictionalized.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Spouse, principal client, anchor partner all arrive through the home, the family network, the matriarchal channel, the educational lineage. Marriage often introduced via family connections or in a teacher-student context. Industries: family-real-estate JVs, school-leadership partnerships, hospitality co-ownership with spouse, founder-with-spouse home-based ventures. The shadow: the partner inherits the family expectations — clarify which dharma is yours and which is the family\'s before merging the books.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'Vipareet Raja Yoga: 8L in own sign in 8H. The crises that flatten others are the platform you rise from. Inheritance fights, succession battles, equity-event combat, restructuring chaos — these are not punishments but career propulsion. Surgeons, crisis consultants, corporate-restructuring principals, forensic auditors, occult researchers thrive here. The shadow: when there is no crisis you may manufacture one — direct the surgical instinct outward at real adversaries, not at your own peace.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'Dharma routes through the partner. Your principal teacher, your guru-equivalent, your most-influential mentor, often comes via the spouse or via a co-founder relationship. Foreign clientele and cross-cultural partnerships compound. Industries: international JV, cross-cultural-design, dharma-led advisory work with a co-principal, religious-organization partnerships, ethical-investment platforms with a spouse. The shadow: you may follow the partner\'s dharma instead of writing your own — receive the influence, but author your own scripture.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'Bhadra peak — career and self are the same engine. The boss is you; the brand is you; the analyst-craftsman in the room is you. Industries: founder-as-craftsman, consulting principal, surgical specialty, master-editor, lead-engineer, principal-investigator, chief-of-staff in technical organizations, technical-author with public following. Promotions track your name, not the org chart. The shadow: the absence of a boss can mean the absence of an authority to push back on bad calls — install peer-review into your own structure.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Wide-network gains route through emotional warmth. Mother-figures, female mentors, woman-led friend-circles, public sentiment, mass-audience affection — these are the channels that pay. Industries: community-platform founder, women-in-X networks, mass-market consumer brands with emotional resonance, cooperative platforms with a mothering ethos, public-sentiment-led media, retail-and-hospitality at scale. Bonus pools, equity true-ups, board invitations arrive through the warm-hearted relationship-stack you have built. The shadow: emotional weather steering financial decisions — separate the warmth from the contract.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'Atmakaraka-style 12L in 12H — kingly authority routed through retreat, foreign work, behind-the-scenes mandates, monastic dignity. Industries: ashram leadership, foreign-mission roles, defense intelligence, hospital chief-of-staff, archive curator, pharmaceutical R&D, off-balance-sheet structuring, monastery management, retreat-center founder. Public visibility is not the path; sovereign authority builds in quiet chambers and the world later acknowledges what was already true. The shadow: father-figure projection onto distant authorities — release the wish for the throne to be acknowledged in the marketplace.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, retreat-led authority lands. Best windows for behind-the-scenes mandates, foreign assignments, hospital/ashram/defense chapters, archival research leadership, off-balance-sheet structuring. The crown sits quietly in the back room. The shadow: the ego wanting visibility — the dharma wants invisibility.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, emotional-network gains compound. Best for community-platform pacts, mother-figure mentorship calls, women-led-friend-circle moves, mass-audience-warmth campaigns, cooperative-platform alliances. The shadow: emotional swings entering the gain calculation — sleep on the warm offer.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, sharp self-craftsmanship lands. Best for founder-as-craftsman declarations, technical-authorship publications, consulting-principal pitches, surgical-deliverable shipping, analyst-with-public-name moves. The shadow: over-edit lock — at some point the deliverable must ship even with imperfections.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, the home-as-wisdom-engine activates. Real-estate acquisitions, family-business expansions, school-leadership inflections, mother-line career moves, work-from-home founder leverage. The shadow: idealization that delays the decision — Hamsa wisdom must marry with timely action.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, surgical transformation lands. Best for restructuring leadership, succession battles, equity-event combat, crisis-management mandates, forensic interventions. The Vipareet engine pays through chaos. The shadow: stirring crises to feel useful — let calm chapters be calm.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, disciplined creative-intellect compounds. Best for multi-year thesis publication, classical-craft mastery announcements, structured-speculation rounds, methodical-investment maturity, doctoral defenses, mentor-of-mentees role formalization. The shadow: the work has gone cold — schedule a play day before the next major deliverable.' },
  { name: 'Venus in 7th (Dispositor)', description: 'Malavya throne. When this engine fires, partner-led grace lands. Best for spouse-led JV closures, principal-client deal signing, marriage inflections, foreign-partner alliances, dharma-co-founder pacts. The shadow: deferring authorship to the partner — receive the grace, but sign the contract in your own hand.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak self-articulation window. Mind sharp, body radiant, public-craftsman declarations land. Best four-week window for founder-as-analyst debut, technical-authorship publication, principal-consultant launch.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on income, voice, family-finance. Best for negotiating fees, recording the technical talk, publishing the pricing model, locking the family-money decision.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on writing, pitch, peers, short-burst sales. Push the campaign sequence, ship the technical post, lead the team-storming sprint. Younger colleagues respond directly.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on Hamsa home-throne. Real-estate decisions, family-business inflections, mother-line career conversations, work-from-home founder moves. Father-figures press their mark — honor without surrendering authorship.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on disciplined creative-intellect. Best window for multi-year thesis defense, course-platform launch, structured-speculation announcement, mentor-of-mentees role debut.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on adversary-management. Best for the audit you have been postponing, the regulatory filing, the hard HR conversation, the lawsuit. Adversaries weaken under direct illumination.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on Malavya partnership engine. Anchor-deal visibility, JV declarations, spouse-led public moves, principal-client elevation. Sign the partnership, take the deal public.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in the Vipareet transformation chamber (own-sign Mars terrain). Career decisions take surgical edge — restructuring, equity-event navigation, succession force-plays, forensic interventions land cleanly.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma, foreign work, teaching, mentor channels. Ketu zone activated — release one teacher-attachment to receive the next. Foreign certifications, judicial proceedings favored.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility. Best for technical-authority declarations, lead-craftsman elevations, public-mantle-of-precision moves. The room reads you as the senior-track analyst.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on emotional-gain network. Bonus-pool conversations, equity true-ups, women-led-network introductions land. Mother-figure mentors notice you publicly.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return on its own throne. Peak retreat-authority month — behind-the-scenes mandates, foreign-mission directives, archive-curation, pharmaceutical/research leadership, monastic-style chief-of-staff roles. Sovereignty in quiet chambers.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional-charge window on persona. Channel into a craftsman-warmth move — the technical post that carries feeling, the founder note that lands warmly.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on income and voice. Read the room before pricing; soft-spoken negotiations land.' },
  { name: 'Moon Transits the 3rd House', description: 'Two-day window of warm communication. The brave-and-warm sales call, the candid technical post, the empathetic team-message.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly Hamsa home-throne emotional peak. Mother-channel call, real-estate read-out, family-business pulse-check. Cook a real meal at home; the reset compounds.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative-intellect. The mind feels poetic; capture the warm draft before the analytic spine returns.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict-management. The adversary may push triggers; respond from documentation, not reaction.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on Malavya partnership. Read the spouse / principal-client temperature before the meeting; warm tone wins the day.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on the transformation zone. Defer high-risk decisions two days; old fears surface for processing.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma-detachment, foreign work, teacher-release. Old guru-loyalty may quietly dissolve this month.' },
  { name: 'Moon Transits the 10th House', description: 'Monthly career-pulse peak. Public reception is warm; senior-network read-outs favor you. Take the warm-toned client meeting.' },
  { name: 'Moon Transits the 11th House', description: 'Moon on its own gain-throne. Peak monthly emotional-network warmth. Reach out to the long-arc female mentor, the mother-figure ally, the cooperative-platform principal.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; foreign and behind-the-scenes pull. Best for retreat planning, confidential drafting, dream-led strategy.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury\'s own-sign-exalted return. Peak monthly self-articulation. Refresh the bio, the technical CV, the founder-craftsman pitch deck. Send the introduction emails.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Renegotiate fees, write the family-finance plan, record the technical talk, pin the pricing model.' },
  { name: 'Mercury Transits the 3rd House', description: 'Sharp short-burst communication window. Peak for content production, sales sequences, sibling-channel deals, technical journalism.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp Hamsa home-throne articulation. Real-estate paperwork, family-business memos, mother-channel correspondence, school-leadership documentation.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative-intellect articulation. Ship the multi-year thesis chapter, the long-form course module, the structured-speculation memo.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp adversary-management. Audit memos, litigation briefs, HR documentation — surgical-precision wins.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, JV memos, contract negotiations, spouse-channel correspondence land cleanly.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-chamber articulation. Succession plans, restructuring memos, equity-event paperwork, due-diligence reports.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-and-foreign articulation. Publish the paper, file the foreign certification, draft the teaching curriculum.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp career-public articulation. Press releases, all-hands updates, technical-authority memos. Issue the formal status note.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Community-platform updates, women-led-network newsletters, mass-audience writing.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp behind-the-scenes articulation. Confidential memos, foreign correspondence, retreat-strategy drafts, archival writing.' },
  { name: 'Venus Transits the 1st House', description: 'Beauty on the analyst-craftsman engine. Refine the technical aesthetic, the founder image, the pitch-deck typography. Charm-led precision wins.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on income and voice. Pricing rises, voice-projects favored, family-finance softens.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on communication. Tone the message, soften the pitch, let charm carry the technical pitch further.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on Hamsa home-throne. Property diplomacy, family-business charm, mother-channel warmth. Aesthetic upgrades to the workspace.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on creative-intellect. Polished course design, elegant thesis defense, refined classical-craft presentation.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on adversary-management. Mediated settlements, charm-led HR, brand-reputation diplomacy. Resolve through warmth, not weight.' },
  { name: 'Venus Transits the 7th House', description: 'Venus on its Malavya throne. Peak partnership-aesthetic month. Anchor-deal warmth, spouse softens, principal-client elevates. Sign the JV with grace.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in the transformation chamber. Equity-event diplomacy, restructuring with elegance, succession with grace. The hard conversation lands softly.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on dharma and foreign work. International stages, teaching with grace, ethics-led design, cross-cultural diplomacy.' },
  { name: 'Venus Transits the 10th House', description: 'Peak public-aesthetic visibility. Brand campaigns, design-led PR, beauty-driven status moves. Senior network reads you as the elegant analyst.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on the wide-network engine. Cooperative-platform diplomacy, women-led-network warmth, board-aesthetic moves.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on the behind-the-scenes engine. Confidential design work, retreat aesthetics, foreign-luxury back channel.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on the body-mind. Bold founder-craftsman moves, athletic performance, direct-action declarations. Watch impulsivity; pair speed with discipline.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on income and voice. Aggressive negotiation, bold price-setting, contested family-finance. Argue from documentation.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on communication. Bold sales sequences, contested technical journalism, fierce pitch-mode. Push the campaign now.' },
  { name: 'Mars Transits the 4th House', description: 'Mars on Hamsa home-throne. Property disputes, family-business friction, real-estate aggression. Don\'t fight family in heat — wait two days.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on creative-intellect. Bold creative shipping, contested speculative bets, fierce mentor-mode. The thesis ships; the bet gets placed.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on adversary-management — Mars\'s strong terrain. The fight is winnable. Press the audit, push the lawsuit, fire the difficult subordinate.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on Malavya partnership. Bold deal-making, contested JV moves, force-clarified spouse and principal-client conversations.' },
  { name: 'Mars Transits the 8th House', description: 'Mars on its own Vipareet throne (own-sign Aries 8H). Peak transformation-action year. Surgical succession force-plays, equity-event combat, restructuring leadership. Crises convert to platform.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on dharma and detachment. Bold teaching declarations, foreign-credential pushes, judicial filings. Act on principle.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on the career-throne. Bold public moves, competitive pitches, demand-the-title windows. Storming the senior-track. Watch heat with the boss.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on the gain-network engine. Bold mother-figure-network moves, contested cooperative-platform pushes, board-level combat with women-led principals.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential combat. Behind-the-scenes warrior, foreign-mandate aggression, off-balance-sheet pushes. Watch hidden enemies.' },
  { name: 'Jupiter Transits the 1st House', description: 'Major year for self-expansion. Founder-craftsman elevation, technical-authorship breakthrough, public-mantle assumption. Discipline diet — Jupiter expands the body too.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Major year for income and voice expansion. Fee-jumps, family-money inflows, voice-project breakthrough.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Major year for communication-expansion. Publishing, technical broadcasting, sales-leadership, sibling-channel growth.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter on its own Hamsa throne. Peak home-throne expansion year. Real-estate acquisition, family-business growth, mother-line career inflection, school-leadership offers. The home itself expands.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for creative-intellect expansion. Course-platform breakthrough, multi-year-thesis publication, mentor-of-mentees role formalized.' },
  { name: 'Jupiter Transits the 6th House', description: 'Major year for adversary-victory. Long lawsuits resolve favorably; chronic adversaries fade; HR transformation lands.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major year for Malavya partnership expansion. Spouse, principal-client, JV principal arrive. Anchor-deal closure year. Marriage if unmarried; renewal if married.' },
  { name: 'Jupiter Transits the 8th House', description: 'Major year for Vipareet transformation gains. Inheritance, severance, equity-event windfall. The crises this year are doorways.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major year for dharma-expansion (despite Ketu in 9th — Jupiter sanctifies). Foreign credentials, teaching-platform breakthrough, judicial endorsements, guru-blessing chapters.' },
  { name: 'Jupiter Transits the 10th House', description: 'Major year for public-career expansion. Chief-of-something offers, prestige roles, board appointments, formal-recognition windfalls.' },
  { name: 'Jupiter Transits the 11th House', description: 'Major year for emotional-network gain. Bonus-pool windfall, equity true-up, mother-figure mentor inflection, women-led-network elevation.' },
  { name: 'Jupiter Transits the 12th House', description: 'Major year for behind-the-scenes expansion. Foreign work, retreats, confidential mandates, off-balance-sheet wisdom-driven gains. Pilgrimage chapter.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on body and identity. Health discipline mandatory; vanity commitments fall away. What survives is permanent.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on income, voice, family-finance. Fee stagnation possible; structure savings rituals.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on communication. Long-arc content systems compound; sibling-channel structures formalize.' },
  { name: 'Saturn Transits the 4th House', description: 'Multi-year discipline on Hamsa home-throne. Real-estate restructuring, family-business reckoning, mother\'s health-and-career as long-arc concern.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn on its own throne in 5H. Peak structural-creative chapter of the multi-decade cycle. The 10-year thesis lands, the cohort-compounding course matures, the slow speculative bet pays.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain (own sign in 6H). Multi-year peak adversary-management. Long lawsuits, regulatory mastery, structural HR. Patience-and-paperwork wins.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of Malavya partnership. Spouse-and-client commitments scrutinized; weak deals end; strong ones formalize for 30 years.' },
  { name: 'Saturn Transits the 8th House', description: 'Multi-year reckoning in the Vipareet transformation chamber. Inheritance disputes, equity-event delays. Patience pays — the structural windfall is on a slow timeline.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year dharma-discipline on Ketu zone. Long credential paths, judicial processes, teaching-institution leadership. The slow climb to elder-teacher status.' },
  { name: 'Saturn Transits the 10th House', description: 'Multi-year structural-career chapter. Slow recognition, foundation-laying for legacy authority. Chief-of-something crystallizes by the cycle end.' },
  { name: 'Saturn Transits the 11th House', description: 'Multi-year discipline on emotional-network gains. Cooperative platforms formalize; women-led-network deepens; board roles consolidate.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on behind-the-scenes work. Long retreat-chapter, foreign-confidential mandates, off-balance-sheet structuring. Quiet authority builds.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive identity-reinvention. New persona, new ambitions, new public projection. Verify each move; the obsession can run hot.' },
  { name: 'Rahu Transits the 2nd House', description: 'Eighteen-month obsession on income and voice. Sudden family-money chaos; verify get-rich schemes; voice-projects with chaotic upside.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on its strong terrain (3H — own placement). Eighteen-month obsessive communication chapter. Viral content, controversial journalism, sibling-channel intensities. Verify integrity.' },
  { name: 'Rahu Transits the 4th House', description: 'Eighteen-month home-throne obsession. Foreign-property pull, family-business reinvention, real-estate fevers. Verify each title.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month obsessive creative chapter. Speculation, viral courses, controversial public-stage moves. Verify ethical bedrock.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Eighteen-month obsessive adversary-defeat chapter. Long-running enemies fall; chronic conflicts resolve unconventionally.' },
  { name: 'Rahu Transits the 7th House', description: 'Eighteen-month obsessive partnership chapter. Foreign spouse, controversial JV, sudden anchor-client. Verify counterparty integrity.' },
  { name: 'Rahu Transits the 8th House', description: 'Eighteen-month obsessive Vipareet chapter. Inheritance chaos, equity-event windfalls, occult-research breakthroughs, foreign opaque dealings. Verify everything.' },
  { name: 'Rahu Transits the 9th House', description: 'Eighteen-month foreign-dharma obsession on the Ketu zone. International guru-pull, controversial teaching-platforms, foreign-credential push.' },
  { name: 'Rahu Transits the 10th House', description: 'Eighteen-month career-reinvention obsession. Sudden promotions, unconventional industries, foreign-career pull. Verify each pivot.' },
  { name: 'Rahu Transits the 11th House', description: 'Eighteen-month obsessive wide-network chapter. Sudden viral-network gains, controversial cooperative-platforms. Verify integrity.' },
  { name: 'Rahu Transits the 12th House', description: 'Eighteen-month foreign-confidential obsession. Hidden mandates, foreign-occult chapters, off-balance-sheet intensities.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping window. Old persona feels empty; ambitions detach. Sit; do not over-correct.' },
  { name: 'Ketu Transits the 2nd House', description: 'Eighteen-month detachment from income, voice, family-money. Old earning paths feel hollow; cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Eighteen-month communication-detachment. Old content-loops feel finished; sibling-channel quiets.' },
  { name: 'Ketu Transits the 4th House', description: 'Eighteen-month home-throne detachment. Old real-estate plans feel weightless; family-business attachment dissolves.' },
  { name: 'Ketu Transits the 5th House', description: 'Eighteen-month creative-detachment. Old performance-loops feel finished; speculative cravings fall away.' },
  { name: 'Ketu Transits the 6th House', description: 'Eighteen-month adversary-detachment. Long enemies fade without intervention; chronic conflicts dissolve quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Eighteen-month partnership-detachment. Old deal feels finished; spouse / principal-client dynamic loosens.' },
  { name: 'Ketu Transits the 8th House', description: 'Eighteen-month transformation-acceleration. Old crises evaporate; deep occult-research detachment.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on its own natal placement (9H). Peak dharma-detachment chapter of the cycle. Old guru-loyalties dissolve completely; principle-without-attachment ripens. The teacher within wakes.' },
  { name: 'Ketu Transits the 10th House', description: 'Eighteen-month career-eclipse. Old role feels weightless; the title that was the destination feels like a costume.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month wide-network detachment. Old friend-circles drift; bonus-pool feels detached.' },
  { name: 'Ketu Transits the 12th House', description: 'Eighteen-month behind-the-scenes detachment. Old retreats, foreign-confidential mandates close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through the analyst-craftsman persona. Best for technical-authority declarations, founder-as-craftsman debut.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish technical materials; prepare the leadership pitch.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the stage, declare the role, accept the public mantle.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Convert visibility into a binding title.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Peak career-visibility window. Launch flagship initiatives; demand title-elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens. Plan the upward move; brief the boss.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-visibility day. Take the elevation, lead the pitch, accept the prestige role.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-visibility window closes. Lock in title or compensation moves.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona; warm public reception possible.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens. Prepare to be felt, not just seen.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Public mood favors you; warm presentations land.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes. Lock in connections.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public reputation; warm career news possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional career window opens. Senior-network warmth rises.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional career day. Take the warm-toned client meeting, the empathetic team-talk.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional career window closes. Move warm leads into formal commitments.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury on its Bhadra throne. Peak self-articulation. Refresh CV, bio, founder-craftsman story.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Bhadra-mind-on-self window opens. Refresh personal-brand documentation.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak Bhadra day. Send the bold technical intro letter, publish the personal-craftsman post.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Bhadra-self window closes. Lock in personal-brand commitments.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp career-communication. Press releases, all-hands updates, status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-communication window opens. Prepare the public message.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak career-communication day. Publish, present, send the formal update.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-communication window closes. Convert messaging into commitment.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Beauty on the analyst-craftsman engine. The room responds to your refined precision.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Venus-self window opens. Plan the warm outreach.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. Make the warm ask; charm wins where pure precision would not.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Venus-self window closes. Convert warmth into binding agreements.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens the public face. Brand campaigns, design-led PR, beauty-driven status moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-career window opens. Plan the brand refresh.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-career day. Launch the campaign, present the redesign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-career window closes. Lock in design commitments.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold body-anchored self-action; founder declarations; warrior moves.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens. Prepare the bold move; train the body.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Take the founder action, sign the bold paper, lead the charge.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes. Channel residual energy into discipline.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold, decisive career action. Launch flagship initiatives; demand title-bumps; lead competitive pitches.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens. Prepare the bold play.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak career-action day. Launch, demand, lead.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action window closes. Convert moves into permanent positions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the role-elevation; declare the larger ambition.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens. Plan public-mantle assumption.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the elevation; declare the ambition.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes. Lock in title and public commitment.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the chief role, the prestige offer, the board appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion window opens. Brief the senior network.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day. Accept the chief-of-something role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion window closes. Convert offers into binding commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity. Slow down, simplify, build for permanence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens. Eliminate vanity commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. The reckoning is acute. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Heavy structural pressure on career. Slow recognition; foundation-laying for legacy authority.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline window opens. Structure work for years.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak career-discipline day. The promotion delayed, the foundation laid, the permanent role crystallizes.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-discipline window closes. Convert effort into title and compensation.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion; foreign or unconventional self emerges. Watch obsession.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window begins. Sudden ambition surfaces.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak reinvention day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes. Decide which experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic visibility expansion. Sudden promotions, unconventional opportunities, foreign career pull.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Career-reinvention window begins. Vet unconventional offers carefully.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak career-reinvention day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Career-reinvention window closes. Lock in legitimate pivots; release illusory ones.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. The old persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens. The pull to step away rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak stripping day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes. Move forward leaner.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. Promotions stall; recognition feels hollow.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse window begins. Don\'t over-defend a role wanting to end.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak career-eclipse day. The role dissolves quietly. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse window closes. Move forward to the cleaner platform.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting the disciplined-creative engine. Saturn-on-own-throne in 5H meets Pluto reset — the multi-year thesis dies and rebuilds, the slow-built course platform restructures, the long speculative bet transforms. You emerge with rebuilt creative-intellectual authority.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on the creative-discipline engine. Old creative frameworks dismantle.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day. The old thesis breaks; the new one is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Structural-transformation chapter completes. You emerge with rebuilt creative-intellectual authority.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting Malavya partnership engine. Unexpected partner pivots, abrupt JV reinventions, surprise spouse-and-client shifts.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden partnership disruption window opens. Expect pivots in spouse, principal-client, or anchor JV.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak partnership disruption day. The deal lands or shatters; the relational pivot is forced.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Partnership disruption window closes. Integrate the changes; release experiments that didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar light on its own retreat-throne. Best window for behind-the-scenes mandates, foreign assignments, archival-research leadership, monastic chief-of-staff roles.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Annual retreat-throne window opens. Plan the year\'s confidential mandate.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Peak retreat-throne day. Take the foreign assignment, the archival role, the monastic-style leadership seat.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Retreat-throne window closes. Lock in confidential or foreign commitments.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar fire on emotional-network gain engine. Mother-figure mentors, women-led-network, mass-audience warmth visibility.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Emotional-network window opens. Brief the warm-network principals.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Peak day. Take the women-led-network call, accept the mother-figure mentorship inflection.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Emotional-network window closes. Lock in network commitments.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar fire on Bhadra craftsman-throne. Founder-as-analyst declarations, technical-authorship publications, public-craftsman moves.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Bhadra-fire window opens. Plan the technical-authorship launch.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Peak Bhadra-solar day. Publish the technical work, declare the craftsman role, launch the analyst platform.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Bhadra-fire window closes. Lock in personal-craftsman commitments.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar fire on Malavya partnership. Anchor-deal visibility, JV declarations, spouse-and-principal-client elevation.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Malavya-fire window opens. Brief the spouse / principal-client.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Peak Malavya day. Sign the JV, take the deal public, accept the partner-led elevation.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Malavya-fire window closes. Lock in contractual commitments.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar fire on Vipareet engine. Surgical succession moves, equity-event combat, restructuring leadership land cleanly.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Vipareet-fire window opens. Prepare the transformation move.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Peak Vipareet-solar day. Take the surgical succession action, force the equity-event resolution, lead the restructuring.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Vipareet-fire window closes. Convert crisis-moves into structural authority.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar fire on Hamsa home-throne. Real-estate visibility, family-business public moves, school-leadership declarations.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Hamsa-fire window opens. Prepare the home-throne move.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Peak Hamsa-solar day. Acquire the property, expand the family business, accept the school-leadership role.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Hamsa-fire window closes. Lock in home-throne commitments.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar fire on disciplined-creative engine. Multi-year-thesis defenses, course-platform launches, structured-speculation announcements peak.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Creative-discipline-fire window opens.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Peak day. Defend the thesis, launch the course platform, announce the structured speculation.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Creative-discipline-fire window closes.' },
  { name: 'Sun aspect Rahu in 3rd house', description: 'Solar fire on communication-chaos zone. Viral-content visibility, controversial-journalism moves — verify integrity before publishing.' },
  { name: 'Sun aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-fire window opens. Vet the viral-content draft.' },
  { name: 'Sun aspect Rahu in 3rd house : Exact', description: 'Peak day. Take the bold communication move with full ethical-bedrock check.' },
  { name: 'Sun aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-fire window closes. Lock legitimate moves; release illusions.' },
  { name: 'Sun aspect Ketu in 9th house', description: 'Solar light on dharma-detachment zone. Old guru-attachments dissolve in public; the principle without the personality emerges.' },
  { name: 'Sun aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-fire window opens.' },
  { name: 'Sun aspect Ketu in 9th house : Exact', description: 'Peak day. Release the teacher-attachment that has been hollow; the inner guru is enough.' },
  { name: 'Sun aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-fire window closes.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on the retreat-throne. Quiet authority and inwardness rise; pause before public moves.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Retreat-emotion window opens.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Peak day. Take the confidential meeting, write the private memo, host the retreat-style call.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Retreat-emotion window closes.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon\'s own-sign return on the gain-throne. Peak emotional-network warmth day. Reach out to mother-figure mentors, women-led-network principals.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Gain-emotion window opens.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Peak day. Take the warm community-platform call; accept the women-led-network elevation.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Gain-emotion window closes.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional warmth on the Bhadra craftsman-throne. The technical writing carries feeling; the analytic deliverable lands warmly.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Bhadra-emotion window opens.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Peak day. Write the warm technical post, lead the empathetic analyst meeting.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Bhadra-emotion window closes.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on Malavya partnership. Read the spouse / principal-client temperature; soften the deal-tone.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Malavya-emotion window opens.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Peak day. Lead with warmth in the JV meeting; let charm carry the deal.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Malavya-emotion window closes.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on Vipareet zone. Old transformation-fears surface; defer the restructuring move two days.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Vipareet-emotion window opens.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Peak day. Sit with the transformation-anxiety; do not act in heat.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Vipareet-emotion window closes.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional warmth on Hamsa home-throne. Mother-channel calls, real-estate read-outs, family-business pulse-checks.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Hamsa-emotion window opens.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Peak day. Cook a real meal, host the family-business call, sign the warm property paper.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Hamsa-emotion window closes.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional weight on creative-discipline. The multi-year thesis feels heavy; the course-build feels endless. Honor the long arc.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Creative-discipline-emotion window opens.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Peak day. Honor the slow craft; the heaviness is the foundation, not the failure.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Creative-discipline-emotion window closes.' },
  { name: 'Moon aspect Rahu in 3rd house', description: 'Emotional swing on communication-chaos zone. Viral content cravings rise; verify before publishing in heat.' },
  { name: 'Moon aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-emotion window opens.' },
  { name: 'Moon aspect Rahu in 3rd house : Exact', description: 'Peak day. Defer the viral-content move two days; the emotion is too loud for clean choice.' },
  { name: 'Moon aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-emotion window closes.' },
  { name: 'Moon aspect Ketu in 9th house', description: 'Emotional detachment from teacher / dharma. Old guru-loyalty feels weightless; the principle remains, the personality fades.' },
  { name: 'Moon aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-emotion window opens.' },
  { name: 'Moon aspect Ketu in 9th house : Exact', description: 'Peak day. Sit with the teacher-attachment dissolving; do not panic-replace the guru.' },
  { name: 'Moon aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-emotion window closes.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Sharp articulation of the retreat-throne. Confidential memos, foreign correspondence, archival-research write-ups.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Retreat-articulation window opens.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Peak day. Send the confidential memo, file the foreign assignment paper, write the archival report.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Retreat-articulation window closes.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Sharp articulation on emotional-network. Community-platform updates, mother-figure-mentorship correspondence, women-led-network newsletters.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Network-articulation window opens.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Peak day. Send the community update, write the warm mentor-channel letter, publish the women-led-network piece.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Network-articulation window closes.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury\'s Bhadra return on its own throne. Peak self-articulation day of the year. The mind is at its sharpest annual setting.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Bhadra peak window opens. Plan the masterpiece deliverable.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Peak Bhadra day. Ship the technical work, publish the analytic deliverable, launch the analyst platform.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Bhadra peak window closes. Lock in the year\'s craftsman commitments.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Sharp Malavya partnership articulation. Term sheets, JV memos, contract drafts, spouse-channel correspondence.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Partnership-articulation window opens.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Peak day. Send the term sheet, publish the JV memo, sign the contract draft.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Partnership-articulation window closes.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Sharp Vipareet articulation. Succession plans, restructuring memos, equity-event paperwork, due-diligence reports.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Vipareet-articulation window opens.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Peak day. Document the opaque deal precisely; the paperwork is the protection.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Vipareet-articulation window closes.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Sharp Hamsa home-throne articulation. Real-estate paperwork, family-business memos, school-leadership documentation.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Hamsa-articulation window opens.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Peak day. File the property paper, send the family-business memo, publish the school-leadership announcement.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Hamsa-articulation window closes.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Sharp creative-discipline articulation. Multi-year-thesis chapters, course-module memos, structured-speculation reports.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Creative-discipline-articulation window opens.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Peak day. Ship the thesis chapter, publish the course module, file the structured-speculation report.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Creative-discipline-articulation window closes.' },
  { name: 'Mercury aspect Rahu in 3rd house', description: 'Sharp communication-chaos articulation. Viral-content drafts, controversial-journalism pieces — verify integrity.' },
  { name: 'Mercury aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-articulation window opens.' },
  { name: 'Mercury aspect Rahu in 3rd house : Exact', description: 'Peak day. Polish the viral-content draft — but verify ethical bedrock before publishing.' },
  { name: 'Mercury aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-articulation window closes.' },
  { name: 'Mercury aspect Ketu in 9th house', description: 'Sharp dharma-detachment articulation. Audit teacher-attachments; write the closure letter to the old guru-channel.' },
  { name: 'Mercury aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-articulation window opens.' },
  { name: 'Mercury aspect Ketu in 9th house : Exact', description: 'Peak day. Write the formal closure to the old teacher-channel; the principle is intact without the lineage.' },
  { name: 'Mercury aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-articulation window closes.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Beauty on the retreat-throne. Confidential design work, foreign-luxury back channel, archival aesthetics.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Retreat-beauty window opens.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Peak day. Soften the confidential meeting, design the elegant retreat space, host the private warm dinner.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Retreat-beauty window closes.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Beauty on emotional-network. Cooperative-platform diplomacy, women-led-network warmth, board-aesthetic moves.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Network-beauty window opens.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Peak day. Take the warm women-led-network call, polish the board presentation, host the cooperative-platform gala.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Network-beauty window closes.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Beauty on Bhadra craftsman-throne. Refine the technical aesthetic, the founder image, the typography of the deliverable.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Bhadra-beauty window opens.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Peak day. Polish the technical writing, redesign the analyst-deliverable, present the craftsman work with elegance.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Bhadra-beauty window closes.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus on its Malavya throne. Peak partnership-grace day. The deal closes warmly; the spouse softens; the principal client elevates.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Malavya peak window opens. Plan the elegant partnership move.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Peak Malavya day. Sign the warm JV, accept the spouse-led elevation, host the principal-client banquet.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Malavya peak window closes. Lock in partnership commitments.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Beauty in the Vipareet chamber. Equity-event diplomacy, restructuring-with-aesthetic, succession-with-grace.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Vipareet-beauty window opens.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Peak day. Take the elegant succession meeting, host the warm restructuring conversation, soften the surgical move.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Vipareet-beauty window closes.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Beauty on Hamsa home-throne. Property diplomacy, family-business charm, mother-channel warmth, school-leadership elegance.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Hamsa-beauty window opens.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Peak day. Soften the property negotiation, host the elegant family meeting, redesign the workspace.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Hamsa-beauty window closes.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Beauty on creative-discipline. Polished course design, elegant thesis defense, refined classical-craft presentation.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Creative-discipline-beauty window opens.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Peak day. Polish the course visuals, present the thesis with elegance, refine the classical-craft deliverable.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Creative-discipline-beauty window closes.' },
  { name: 'Venus aspect Rahu in 3rd house', description: 'Beauty on communication-chaos zone. Polished viral content, elegant controversial journalism — verify integrity under the gloss.' },
  { name: 'Venus aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-beauty window opens.' },
  { name: 'Venus aspect Rahu in 3rd house : Exact', description: 'Peak day. Polish the viral-content draft, verify the ethical bedrock.' },
  { name: 'Venus aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-beauty window closes.' },
  { name: 'Venus aspect Ketu in 9th house', description: 'Beauty on dharma-detachment. Old teacher-aesthetic feels weightless; the principle remains beautiful even without the lineage.' },
  { name: 'Venus aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-beauty window opens.' },
  { name: 'Venus aspect Ketu in 9th house : Exact', description: 'Peak day. Release the old teacher-aesthetic that has been hollow.' },
  { name: 'Venus aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-beauty window closes.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Mars on the retreat-throne. Behind-the-scenes warrior moves, foreign-mandate aggression, off-balance-sheet pushes.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Retreat-fire window opens.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Peak day. Take the confidential force-play, push the foreign-mandate aggression.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Retreat-fire window closes.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Mars on the gain-network engine. Bold mother-figure-network moves, contested cooperative-platform pushes, board-level combat with women-led principals.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Gain-fire window opens.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Peak day. Push the network move, contest the cooperative-platform decision, lead the board fight.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Gain-fire window closes.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Mars on the Bhadra craftsman-throne. Bold founder-craftsman moves, fierce technical-authorship pushes, contested public-craftsman declarations.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Bhadra-fire window opens.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Peak day. Take the bold technical-authorship move, fight the brand-attack, ship the contested deliverable.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Bhadra-fire window closes.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Mars on Malavya partnership. Bold deal-making, contested JV moves, force-clarified spouse and principal-client conversations.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Malavya-fire window opens.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Peak day. Sign the JV, divorce the dead deal, demand the partnership terms.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Malavya-fire window closes.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars on its own Vipareet throne. Peak transformation-fire day of the year. Surgical succession action, equity-event combat, restructuring leadership at full force.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Vipareet peak window opens. Prepare the surgical move.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Peak Vipareet day. Force the succession resolution, lead the restructuring, take the equity-event surgical move.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Vipareet peak window closes. Convert crisis-moves into permanent structural authority.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Mars on Hamsa home-throne. Property disputes, family-business friction, real-estate aggression. Don\'t fight family in heat.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Hamsa-fire window opens.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Peak day. Defer the family-confrontation two days; the heat distorts.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Hamsa-fire window closes.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Mars on creative-discipline. Bold creative shipping, contested speculative bets, fierce mentor-mode.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Creative-fire window opens.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Peak day. Ship the bold thesis, place the contested bet, lead the fierce mentorship.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Creative-fire window closes.' },
  { name: 'Mars aspect Rahu in 3rd house', description: 'Mars on communication-chaos zone. Bold viral-content pushes, contested journalism, fierce sales sequences.' },
  { name: 'Mars aspect Rahu in 3rd house : Starts', description: 'Communication-fire window opens.' },
  { name: 'Mars aspect Rahu in 3rd house : Exact', description: 'Peak day. Push the contested piece, lead the bold sales storm — verify integrity twice.' },
  { name: 'Mars aspect Rahu in 3rd house : Ends', description: 'Communication-fire window closes.' },
  { name: 'Mars aspect Ketu in 9th house', description: 'Mars on dharma-detachment. Forceful release of old teacher-attachments; fierce closure of dead lineage commitments.' },
  { name: 'Mars aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-fire window opens.' },
  { name: 'Mars aspect Ketu in 9th house : Exact', description: 'Peak day. Forcefully close the dead teacher-channel; do not negotiate the closure.' },
  { name: 'Mars aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-fire window closes.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom on the retreat-throne. Confidential mandate gains, foreign assignment elevation, archival-research royalty.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Retreat-expansion window opens.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Peak day. Accept the confidential mandate elevation, take the foreign assignment, formalize the archival-research seat.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Retreat-expansion window closes.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on emotional-network gain. Bonus-pool windfalls, equity true-ups, mother-figure-mentor inflections, women-led-network elevations.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Gain-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Peak day. Take the bonus, accept the equity true-up, formalize the mother-figure-mentor relationship.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Gain-expansion window closes.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom on Bhadra craftsman-throne. Founder-craftsman elevation, technical-authorship breakthrough, public-craftsman expansion.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Bhadra-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Peak day. Accept the founder-craftsman elevation, launch the technical-authorship platform, take the public-craftsman role.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Bhadra-expansion window closes.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on Malavya partnership. Anchor-deal expansion, JV elevation, marriage-and-equity-partner inflection.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Malavya-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Peak day. Sign the elevated JV, accept the marriage-or-merger inflection, take the principal-client expansion.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Malavya-expansion window closes.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on Vipareet engine. Inheritance windfalls, equity-event gains, succession-led elevation. Jupiter sanctifies the transformation.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Vipareet-expansion window opens.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Peak day. Take the inheritance, accept the succession-led elevation, formalize the equity-event windfall.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Vipareet-expansion window closes.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter on its own Hamsa throne. Peak home-throne expansion day of the cycle. Real-estate windfall, family-business inflection, school-leadership offer, mother-line career elevation.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Hamsa peak window opens. Plan the home-throne move.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Peak Hamsa day. Acquire the property, expand the family business, accept the school-leadership role.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Hamsa peak window closes. Lock in home-throne commitments.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on creative-discipline. Course-platform breakthrough, multi-year-thesis publication, mentor-of-mentees role formalized.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Creative-discipline-expansion window opens.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Peak day. Launch the course platform, defend the thesis, formalize the mentorship.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Creative-discipline-expansion window closes.' },
  { name: 'Jupiter aspect Rahu in 3rd house', description: 'Wisdom on communication-chaos zone. Viral-content elevation, controversial-journalism breakthroughs — Jupiter sanctifies the bold message.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-expansion window opens.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Exact', description: 'Peak day. Take the bold viral-content move, accept the controversial-journalism platform.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-expansion window closes.' },
  { name: 'Jupiter aspect Ketu in 9th house', description: 'Wisdom on dharma-detachment. The released teacher-attachment becomes its own teaching; Jupiter sanctifies the principle without the lineage.' },
  { name: 'Jupiter aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-expansion window opens.' },
  { name: 'Jupiter aspect Ketu in 9th house : Exact', description: 'Peak day. Convert the released guru-attachment into your own teaching artifact.' },
  { name: 'Jupiter aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-expansion window closes.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Structural pressure on the retreat-throne. Long confidential mandates, slow foreign assignments, archival-research as long-arc commitment.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Retreat-discipline window opens.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Peak day. Take the slow foreign assignment, formalize the long-arc archival role, sign the multi-year confidential mandate.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Retreat-discipline window closes.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Structural pressure on emotional-network. Cooperative platforms formalize; women-led-network deepens; board roles consolidate.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Network-discipline window opens.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Peak day. Sign the cooperative-platform charter, formalize the women-led-network membership, accept the board seat.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Network-discipline window closes.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Structural pressure on Bhadra craftsman-throne. Slow founder-craftsman evolution; vanity-skills fall away; the durable craft sets in.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Bhadra-discipline window opens.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Peak day. Eliminate vanity-skills; lock in the durable craftsman structure.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Bhadra-discipline window closes.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Structural pressure on Malavya partnership. Spouse-and-client commitments scrutinized; weak deals end; strong ones formalize for 30 years.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Malavya-discipline window opens.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Peak day. Divorce the weak deal, formalize the strong JV, lock in the long marriage structure.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Malavya-discipline window closes.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Structural pressure on Vipareet engine. Inheritance disputes, equity-event delays, succession restructuring. Patience pays.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Vipareet-discipline window opens.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Peak day. Hold the line on the slow restructuring; the windfall arrives on a slow timeline.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Vipareet-discipline window closes.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Structural pressure on Hamsa home-throne. Real-estate restructuring, family-business reckoning, mother-line career as long-arc commitment.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Hamsa-discipline window opens.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Peak day. Take the slow real-estate decision, restructure the family business, formalize the mother-line commitment.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Hamsa-discipline window closes.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn on its own throne. Peak structural-creative day of the multi-decade cycle. The 10-year thesis lands, the cohort-compounding course matures, the slow speculative bet pays.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn-creative peak window opens. Decades of slow work converge.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Peak day. Defend the long thesis, formalize the creative platform, lock in the structured-speculation maturity.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn-creative peak window closes. Lock in long-horizon creative commitments.' },
  { name: 'Saturn aspect Rahu in 3rd house', description: 'Structural pressure on communication-chaos zone. Long-arc viral-content discipline; chaotic journalism formalizes into an institutional voice.' },
  { name: 'Saturn aspect Rahu in 3rd house : Starts', description: 'Communication-discipline window opens.' },
  { name: 'Saturn aspect Rahu in 3rd house : Exact', description: 'Peak day. Lock in the multi-year content schedule; convert chaotic voice into institutional structure.' },
  { name: 'Saturn aspect Rahu in 3rd house : Ends', description: 'Communication-discipline window closes.' },
  { name: 'Saturn aspect Ketu in 9th house', description: 'Structural pressure on dharma-detachment. The teacher-release is formally documented; the lineage closure is structural.' },
  { name: 'Saturn aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-discipline window opens.' },
  { name: 'Saturn aspect Ketu in 9th house : Exact', description: 'Peak day. Sign the formal closure of the dead teacher-channel.' },
  { name: 'Saturn aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-discipline window closes.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Chaotic expansion on the retreat-throne. Foreign-mandate fevers, confidential-deal obsessions, off-balance-sheet intensities.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Retreat-chaos window opens.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Peak day. Vet the foreign mandate twice; the confidential opportunity may be real or smoke.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Retreat-chaos window closes.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Chaotic expansion on emotional-network. Sudden viral-network gains, controversial cooperative-platform pulls.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Network-chaos window opens.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Peak day. Take the viral-network move — verify ethical bedrock.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Network-chaos window closes.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Chaotic expansion on Bhadra craftsman-throne. Viral founder-craftsman moments, sudden technical-authorship pivots, controversial public-face shifts.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Bhadra-chaos window opens.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Peak day. Take the bold pivot — verify the technical bedrock under the gloss.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Bhadra-chaos window closes.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Chaotic expansion on Malavya partnership. Foreign spouse, controversial JV, sudden anchor-client. Verify counterparty integrity.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Malavya-chaos window opens.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Peak day. Vet the controversial JV thoroughly; the deal can be real or it can be smoke.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Malavya-chaos window closes.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Chaotic expansion on Vipareet engine. Sudden equity-event windfalls, occult-research breakthroughs, foreign opaque dealings. Verify everything.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Vipareet-chaos window opens. Vet each opaque opportunity.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Peak day. Take the equity-event move with full documentation; the chaos is structural.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Vipareet-chaos window closes. Lock legitimate moves; release illusions.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Chaotic expansion on Hamsa home-throne. Foreign-property pull, family-business reinvention, real-estate fevers. Verify titles.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Hamsa-chaos window opens.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Peak day. Vet the foreign-property paperwork before signing.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Hamsa-chaos window closes.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Chaotic expansion on creative-discipline engine. Speculative-fevers, viral-course pulls, controversial public-stage moves.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Creative-chaos window opens.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Peak day. Take the speculative-creative move with full ethical-bedrock check.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Creative-chaos window closes.' },
  { name: 'Rahu aspect Rahu in 3rd house', description: 'Rahu return on its own placement (3H). Peak communication-chaos day. Viral content opportunity at maximum amplitude — and at maximum risk. Verify ethical bedrock.' },
  { name: 'Rahu aspect Rahu in 3rd house : Starts', description: 'Rahu-return communication window opens. Vet the bold message.' },
  { name: 'Rahu aspect Rahu in 3rd house : Exact', description: 'Peak Rahu-return day. Push the viral message — but the chaos is structural; verify integrity.' },
  { name: 'Rahu aspect Rahu in 3rd house : Ends', description: 'Rahu-return window closes. Lock legitimate channels; release illusions.' },
  { name: 'Rahu aspect Ketu in 9th house', description: 'Rahu-Ketu axis return on the dharma-detachment zone. Peak teacher-attachment turbulence; lineage-stress at maximum.' },
  { name: 'Rahu aspect Ketu in 9th house : Starts', description: 'Axis-chaos window opens.' },
  { name: 'Rahu aspect Ketu in 9th house : Exact', description: 'Peak day. Defer dharma decisions; the axis is too loud for clean choice.' },
  { name: 'Rahu aspect Ketu in 9th house : Ends', description: 'Axis-chaos window closes.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on the retreat-throne. Old confidential mandates feel weightless; foreign-assignment cravings dissolve.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Retreat-detachment window opens.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Peak day. Sit with the confidential-mandate feeling weightless; do not panic-replace.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Retreat-detachment window closes.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on emotional-network. Old friend-circles drift; bonus-pool feels detached.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Network-detachment window opens.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Peak day. Release the old friend-circle that has grown hollow.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Network-detachment window closes.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on Bhadra craftsman-throne. Old founder-craftsman persona feels hollow; the analytic mastery quiets.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Bhadra-detachment window opens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Peak day. Sit with the craft feeling weightless; do not over-perform to compensate.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Bhadra-detachment window closes.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on Malavya partnership. Old deal feels finished; spouse / principal-client dynamic loosens.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Malavya-detachment window opens.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Peak day. Sit with the deal feeling weightless; do not panic-renegotiate.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Malavya-detachment window closes.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on Vipareet engine. Old crises evaporate; deep transformation-detachment.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Vipareet-detachment window opens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Peak day. Release the old crisis-loop; the field is clearing for the next surgical chapter.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Vipareet-detachment window closes.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on Hamsa home-throne. Old real-estate plans feel weightless; family-business attachment dissolves.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Hamsa-detachment window opens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Peak day. Sit with the home-throne feeling weightless; do not panic-sell or panic-leave.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Hamsa-detachment window closes.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on creative-discipline. Old performance-loops feel finished; speculative cravings fall away.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Creative-detachment window opens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Peak day. Release the dead creative-loop; the field clears for a new iteration.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Creative-detachment window closes.' },
  { name: 'Ketu aspect Rahu in 3rd house', description: 'Ketu-Rahu axis stress on communication. Old viral-content loops feel finished; the chaos quiets unconventionally.' },
  { name: 'Ketu aspect Rahu in 3rd house : Starts', description: 'Communication-axis-detachment window opens.' },
  { name: 'Ketu aspect Rahu in 3rd house : Exact', description: 'Peak day. Sit with the content-channel quieting; do not force a replacement.' },
  { name: 'Ketu aspect Rahu in 3rd house : Ends', description: 'Communication-axis-detachment window closes.' },
  { name: 'Ketu aspect Ketu in 9th house', description: 'Ketu return on its own placement (9H). Peak dharma-detachment day. Old teacher-attachments dissolve completely; the inner guru surfaces fully. Profound spiritual release.' },
  { name: 'Ketu aspect Ketu in 9th house : Starts', description: 'Ketu-return dharma window opens.' },
  { name: 'Ketu aspect Ketu in 9th house : Exact', description: 'Peak Ketu-return day. The lineage-attachment evaporates; the principle without personality crystallizes.' },
  { name: 'Ketu aspect Ketu in 9th house : Ends', description: 'Ketu-return dharma window closes. Move forward with the inner teacher integrated.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} career] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
