// db/seed_food_aries.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to a
// representative Aries ascendant native with:
//   Ascendant: Aries
//   Natal placements (sidereal Lahiri):
//     Sun=5th (Leo, own)  Moon=4th (Cancer, own)  Mercury=6th (Virgo, own+exalted)
//     Venus=12th (Pisces, exalted)  Mars=1st (Aries, own — Ruchaka Yoga)
//     Jupiter=9th (Sagittarius, own)  Saturn=10th (Capricorn, own — Sasa Yoga)
//     Rahu=5th (Leo, conjunct Sun)  Ketu=11th (Aquarius)
//
// All 530 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose food-specific interpretations, then run:
//
//   node db/seed_food_aries.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./food');

const ASCENDANT = 'Aries';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mars ruler of the 1st House in the 1st House', description: 'Your constitution runs hot. Strong digestive fire, sharp appetite, fast metabolism in youth — and a tendency to acidity, inflammation, skin and blood heat as the years stack up. The diet that suits you is cooling, sweet-leaning, lightly bitter and astringent: ghee, milk, sweet fruits, leafy greens, coconut, coriander, fennel, cucumber, melon, basmati rice. Avoid excess chili, vinegar, fermented foods, alcohol, red meat at night, and skipped meals. Eat before the hunger turns into temper.' },
  { name: 'Venus ruler of the 2nd House in the 12th House', description: 'Income from food, voice, and family-finance routes through foreign and devotional channels — but the same pattern shows up in eating. Foreign cuisine fascinates you; flavors from far away nourish more than the local default. Sweet drinks, retreat meals, temple food, hospital diets, hotel dining all soothe the system. The shadow: liquid pleasures (cocktails, sweet desserts, late-night indulgence) compound silently — pin them to a deliberate ritual.' },
  { name: 'Mercury ruler of the 3rd House in the 6th House', description: 'A sensitive, precision-tuned gut. Stress goes straight to digestion; deadlines flip the bowel; over-caffeination misfires. The clean, simple, well-prepared meal beats the elaborate one every time. Whole grains, lightly cooked vegetables, herbal teas, regular timing. The shadow: over-thinking the diet into another job — choose a small set of clean staples and rotate.' },
  { name: 'Moon ruler of the 4th House in the 4th House', description: 'Emotion and food are deeply intertwined. The kitchen and dining table at home feed you more than restaurant meals; food made by the people you love registers as actual nourishment. Comfort-food cravings rise sharply under stress — guard against night-time emotional eating. Cook at home most days; let the act of cooking itself be the medicine, not just the result.' },
  { name: 'Sun ruler of the 5th House in the 5th House', description: 'Performance metabolism: when you have a stage, your appetite is sharp and the body burns clean. When the spotlight is off, the same fire turns inward and you skip meals or under-fuel. Heart and bones need attention; warm cooked food, good fats, golden milk, ghee, dates, almonds. Avoid heart-stressors (excess salt, processed meat, deep-fried). The Rahu undertow: bingeing on novelty foods or status-restaurants — slow down, taste actually.' },
  { name: 'Mercury ruler of the 6th House in the 6th House', description: 'You hold sovereign command over your daily eating — when you decide to eat clean, you can do it for months without slipping. That same precision can turn into anxious over-controlling. Pace it: 80% disciplined, 20% relaxed. Easy on antacids; instead address the upstream: less spicy, less late-night eating, more cooling herbs (mint, coriander, fennel).' },
  { name: 'Venus ruler of the 7th House in the 12th House', description: 'Romantic and partnership life often happens through shared meals — restaurants abroad, retreat dining, late-night room service, hotel breakfasts. The partner\'s food preferences shift yours over time. The shadow: indulgent shared eating that quietly thickens the body and the budget. Schedule a weekly clean-eating reset day.' },
  { name: 'Mars ruler of the 8th House in the 1st House', description: 'Sudden food reactions — allergies, intolerances, abrupt sensitivities — can appear out of nowhere. The body rapidly absorbs and rapidly rejects. Surgical-style eating works: identify the precise trigger, eliminate fully, reintroduce slowly. Fasting suits you in disciplined doses; reckless fasting (skipping meals from busy-ness) inflames the system.' },
  { name: 'Jupiter ruler of the 9th House in the 9th House', description: 'Generous appetite. You can eat large portions of rich, traditional food and feel blessed by it — but the body remembers. Weight gain is gradual and structural rather than rapid. Best foods: warm whole grains, ghee in moderation, traditional dal-rice-vegetable meals, ceremonial sattvic food. Best practices: eat the largest meal at midday; lighter dinner; no late food.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'The body wants the same things at the same times every day. Irregular meals tax the system disproportionately. Build a fixed eating schedule and the metabolism compounds. Joints, bones, knees need warm, oily, well-spiced food in middle age. Avoid raw cold salads as the primary diet; favor soups, stews, well-cooked vegetables. Bone broth, sesame, ghee — long-game nourishment.' },
  { name: 'Saturn ruler of the 11th House in the 10th House', description: 'Gains and friend-circle eating route through formal, structured, work-anchored meals. The corporate dinner, the conference banquet, the senior-network lunch — these are where eating-as-network happens for you. The shadow: too many work meals erode the home-cooking ritual that actually feeds you. Cap external dining; reserve at least 5 home meals per week.' },
  { name: 'Jupiter ruler of the 12th House in the 9th House', description: 'Pilgrimages, retreats, foreign trips, ashrams — these places restore digestion better than any clinic. When the body feels heavy, plan the trip; the change of food, water, and rhythm resets the system. The shadow: pleasure-eating on travel that undoes the reset; arrive disciplined.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (6)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 5th (Dispositor)', description: 'When this engine fires, the diet wants performance-fuel — clean grains, good fats, sharp protein at midday, light dinner. Warm cooked food beats raw food. Show off less; eat consistently. The Rahu shadow: novelty-restaurant chasing — pick three cooling, nourishing places and rotate.' },
  { name: 'Moon in 4th (Dispositor)', description: 'When this engine fires, the home kitchen is the answer to most digestive complaints. Mother\'s recipes, traditional family dishes, the dining table you grew up with — all medicinal. Eat what your body grew up on; the system recognizes it.' },
  { name: 'Mercury in 6th (Dispositor)', description: 'When this engine fires, run a clean-eating audit. Eliminate the obvious irritants for ten days: alcohol, fermented foods, refined sugar, heavy red meat, late-night eating. Reintroduce one at a time and notice. The body tells you precisely; your mind reads the signal sharply.' },
  { name: 'Jupiter in 9th (Dispositor)', description: 'When this engine fires, traditional sattvic food restores balance. Ghee, basmati, lightly spiced dal, warm milk, dates, almonds. Eat at family or community gatherings. Beware over-eating in celebration mode — the appetite expands easily here.' },
  { name: 'Mars in 1st (Dispositor)', description: 'When this engine fires, the body burns hot. Cool the system: cucumber, mint, coconut, watermelon, fennel water, coriander. Avoid red meat, alcohol, chili, vinegar, deep-fried. Walk after meals; do not stack sharp workouts on top of heavy meals.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, regularity is the medicine. Same meals at same times for two weeks; the system stabilizes. Warm cooked food; minimal raw; steady protein; oils and warming spices for the joints (ginger, turmeric, sesame).' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Solar fire on the body. Heat rises; appetite peaks but digestion runs hot. Cooling foods favored — coconut water, cucumber, mint, melon, milk. Avoid extra spice and alcohol for the month.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on speech, voice, and what enters the mouth. Vocal-care matters; honey, ghee, soothing teas. Avoid acid foods (citrus, tomato) if voice is in use.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on the diet. Bold dietary changes possible. Push the new eating protocol; the willpower is up.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home kitchen. Cook at home; the hearth is medicinal this month. Mother\'s recipes restore.' },
  { name: 'Sun Transits the 5th House', description: 'Solar return-style on creative-performance metabolism. Heart-care foods favored: warm milk, dates, almonds, ghee. Avoid late-night party-eating.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on the digestive engine. Best window of the year for a clean-eating reset, an elimination diet, a parasite cleanse, a gut audit.' },
  { name: 'Sun Transits the 7th House', description: 'Solar light on shared meals. Partner-related eating dynamics surface. Avoid alcohol-heavy social meals.' },
  { name: 'Sun Transits the 8th House', description: 'Solar fire in the transformation chamber of the body. Sharp digestive resets; possible flare of old triggers — handle softly.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on philosophical eating. Sattvic diet calls; pilgrimage food, ashram fare, traditional fast.' },
  { name: 'Sun Transits the 10th House', description: 'Solar fire on structural-eating habits. Reset the daily schedule; lock in fixed meal times.' },
  { name: 'Sun Transits the 11th House', description: 'Solar light on group-eating dynamics. Friend-network meals favored, but watch detachment afterward.' },
  { name: 'Sun Transits the 12th House', description: 'Solar light on retreat-eating. Foreign cuisine, hospital diets, hotel meals dominate. Hidden patterns surface.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of body-emotion fusion. Eat with extra warmth and self-care; the body is sensitive.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on speech and intake. Comfort-food cravings rise; choose something warm and nourishing.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on small bursts of eating. Snacking risk. Pre-prep clean snacks.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-kitchen peak. Cook at home; mother\'s food restores; the dining table is medicinal.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on performance-metabolism. Avoid emotional eating before a presentation.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on digestive sensitivity. Eat clean; reduce triggers.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on shared meals. Read the partner\'s food-mood before suggesting cuisine.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on the transformation-eating zone. Avoid heavy meals; defer rich food two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward sattvic, ceremonial, foreign food. Travel-eating favored.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on the eating schedule. Don\'t skip meals from busy-ness today; build in the structure.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth toward group-eating with detachment undertone. Attend the dinner, but don\'t over-indulge.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional charge on retreat and foreign-cuisine. Soup, broth, soft foods.' },
  { name: 'Mercury Transits the 1st House', description: 'Bold, punchy dietary self-talk. Refresh the eating plan, write the food journal.' },
  { name: 'Mercury Transits the 2nd House', description: 'Patient communication around food, voice, family-finance. Plan meals carefully.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak food-writing/research window. Read the new diet book, audit food labels, send the dietitian inquiry.' },
  { name: 'Mercury Transits the 4th House', description: 'Emotionally tuned home-cooking. Plan the family meals, write the grocery list with care.' },
  { name: 'Mercury Transits the 5th House', description: 'Bold creative cooking. Try new recipes; food-content creation favored.' },
  { name: 'Mercury Transits the 6th House', description: 'Peak food-precision window of any quarter. Audit the diet, identify triggers, run an elimination, get the bloodwork.' },
  { name: 'Mercury Transits the 7th House', description: 'Diplomatic communication around shared meals. Negotiate cuisine choices with the partner.' },
  { name: 'Mercury Transits the 8th House', description: 'Investigative food research. Allergy testing, deep-dive into food sensitivities.' },
  { name: 'Mercury Transits the 9th House', description: 'Visionary food philosophy. Sattvic, Ayurvedic, traditional eating systems study.' },
  { name: 'Mercury Transits the 10th House', description: 'Disciplined eating-schedule communication. Lock in the meal plan.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp-but-detached communication on group meals. Logistics for dinner parties.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential food-writing. Foreign-cuisine research, retreat-diet planning.' },
  { name: 'Venus Transits the 1st House', description: 'Personal warmth around food. Pleasure-eating window; indulge mindfully.' },
  { name: 'Venus Transits the 2nd House', description: 'Sweet, indulgent food window. Throat-care matters; honey, ghee, soothing teas.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful food-related communication. Recipe sharing, food-content creation.' },
  { name: 'Venus Transits the 4th House', description: 'Beautiful home-kitchen window. Cook the elaborate meal, host the warm gathering.' },
  { name: 'Venus Transits the 5th House', description: 'Peak romantic-and-creative eating. Date-nights, beautiful presentations, indulgent desserts.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic food-discipline. Soft elimination diets work; the body cooperates.' },
  { name: 'Venus Transits the 7th House', description: 'Peak shared-meals warmth window. Partner-meal-rituals, romantic dinners.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic intimacy with the body. Sensual eating; gentle digestive reset.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful traditional-food window. Ceremonial meals, foreign-cuisine warmth.' },
  { name: 'Venus Transits the 10th House', description: 'Softens public-eating. Brand-friendly food choices; well-photographed meals.' },
  { name: 'Venus Transits the 11th House', description: 'Graceful but cool group-eating. Pleasant dinner parties; emotional restraint.' },
  { name: 'Venus Transits the 12th House', description: 'Annual peak window for foreign cuisine, hotel dining, retreat food, bedroom-snacks.' },
  { name: 'Mars Transits the 1st House', description: 'Body fire peaks. Pitta-spike risk: skin breakouts, acidity, inflammation. Cooling foods mandatory — coconut water, cucumber, mint, fennel.' },
  { name: 'Mars Transits the 2nd House', description: 'Sharp speech and possible heat in mouth/teeth/throat. Cool the system; soothing teas; avoid extra spice.' },
  { name: 'Mars Transits the 3rd House', description: 'Bold dietary changes. Push through the protocol you have been postponing.' },
  { name: 'Mars Transits the 4th House', description: 'Heated home-kitchen. Sharp arguments around food; soften family dynamics.' },
  { name: 'Mars Transits the 5th House', description: 'Hot performance-metabolism. Burn fuel cleanly; avoid stimulants and heavy late meals.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable for digestive combat. Excellent for an elimination diet, parasite cleanse, intense gut reset.' },
  { name: 'Mars Transits the 7th House', description: 'Friction in shared meals. Avoid food-fights; defer cuisine-arguments.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical-style fasting works; sudden eliminations land cleanly.' },
  { name: 'Mars Transits the 9th House', description: 'Bold sattvic discipline. Take on the traditional fast or pilgrimage-diet.' },
  { name: 'Mars Transits the 10th House', description: 'Strong scheduling-discipline window. Lock in the rigorous meal-plan.' },
  { name: 'Mars Transits the 11th House', description: 'Assertive group-eating push. Lead a friend-cleanse or group-fast with detachment.' },
  { name: 'Mars Transits the 12th House', description: 'Heated foreign-cuisine and bedroom-snacking. Watch alcohol; sleep loss possible.' },
  { name: 'Jupiter Transits the 1st House', description: 'Body expands. Weight-gain risk; appetite expands; portion control matters all year.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom on speech, voice, family-finance, food. Throat care; sweet flavors expand.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on dietary research. Major food-philosophy education.' },
  { name: 'Jupiter Transits the 4th House', description: 'Peak home-kitchen expansion year. New equipment, larger pantry, family cooking traditions deepen.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major celebratory-eating year. Weddings, festivals, banquets. Watch portion expansion.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom into digestive zone — but Jupiter in 6H tends toward weight gain. Control portions; favor warm light food.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom into shared meals. Marriage feasts; partner-nutrition deepens.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into transformation eating. Inheritance feasts; deep dietary therapy.' },
  { name: 'Jupiter Transits the 9th House', description: 'Among the most blessed sattvic-eating windows. Pilgrimage food; ceremonial diet; major Ayurvedic practice.' },
  { name: 'Jupiter Transits the 10th House', description: 'Peak structural-diet expansion year. Lock in long-term eating discipline; the year compounds.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom on group-eating. Friend-cleanse leadership; community-meal traditions.' },
  { name: 'Jupiter Transits the 12th House', description: 'Peak foreign-cuisine expansion year. International travel-eating; retreat fare.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on the body. Joints, bones, slow weight gain. Discipline diet now or pay later.' },
  { name: 'Saturn Transits the 2nd House', description: 'Discipline on speech, voice, food. Slow, structural dental and throat care.' },
  { name: 'Saturn Transits the 3rd House', description: 'Discipline on small-effort eating. Build food-prep routines that last decades.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy home-kitchen weight; mother\'s health-and-food becomes a structural concern.' },
  { name: 'Saturn Transits the 5th House', description: 'Performance-metabolism discipline. Heart-care, bone-density work; long-arc fitness foundation.' },
  { name: 'Saturn Transits the 6th House', description: 'Favorable for long-term gut-mastery. The multi-year diet that compounds.' },
  { name: 'Saturn Transits the 7th House', description: 'Structural-test of shared meals. Long-arc partner-nutrition habits.' },
  { name: 'Saturn Transits the 8th House', description: 'Major dietary restructuring window. Old food-habits end; new structural patterns set.' },
  { name: 'Saturn Transits the 9th House', description: 'Discipline on sattvic/traditional eating. Slow ceremonial-fast practice.' },
  { name: 'Saturn Transits the 10th House', description: 'The 2.5-year window that seeds the next 30-year eating-pattern. Lock in the structure.' },
  { name: 'Saturn Transits the 11th House', description: 'Disciplined group-eating; the social-eating network purges what is unhealthy.' },
  { name: 'Saturn Transits the 12th House', description: 'Discipline on foreign and retreat-eating. Long-distance dietary patterns formalize.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive body-reinvention. New diet, new body-image, new persona. Verify each protocol.' },
  { name: 'Rahu Transits the 2nd House', description: 'Obsessive eating around voice, family-finance. Beware get-thin-quick schemes.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive food-research. Diet-fad-chasing; verify integrity.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home-cooking chapter. New cuisines, foreign recipes, family-tradition reinvention.' },
  { name: 'Rahu Transits the 5th House', description: 'Obsessive performance-eating. Intense dieting; speculation around food businesses.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat a long-running food sensitivity, win against a chronic gut issue.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive partner-eating. Foreign cuisine pull; controversial joint-diet experiments.' },
  { name: 'Rahu Transits the 8th House', description: 'Obsessive transformational diet. Sudden allergy-discoveries; deep food-medicine research.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign-fortune food obsession. International cuisine, controversial guru-of-the-diet.' },
  { name: 'Rahu Transits the 10th House', description: 'Obsessive structural-diet push. Sudden meal-plan changes; verify legitimacy.' },
  { name: 'Rahu Transits the 11th House', description: 'Obsessive group-eating chapter. Trend-diet pressure; stay clean.' },
  { name: 'Rahu Transits the 12th House', description: 'Obsessive foreign-cuisine pull. Hidden food-issues surface; pleasure-eating obsession.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month body-stripping window. Old eating-identity feels empty. Sit; do not over-protocol.' },
  { name: 'Ketu Transits the 2nd House', description: 'Detachment from food, voice, family-finance dynamics. The cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from food-research and small-burst eating. Solo simple meals favored.' },
  { name: 'Ketu Transits the 4th House', description: 'Home-kitchen detachment. Less attachment to family-recipes; simplification.' },
  { name: 'Ketu Transits the 5th House', description: 'Performance-metabolism eclipse. Old fame-diet feels hollow; fasting easier.' },
  { name: 'Ketu Transits the 6th House', description: 'Service-eating detachment. Old chronic gut-issues dissolve without intervention.' },
  { name: 'Ketu Transits the 7th House', description: 'Partner-eating detachment. Joint food-rituals dissolve.' },
  { name: 'Ketu Transits the 8th House', description: 'Transformation-eating acceleration. Old food-allergies fade; new ones may surface briefly.' },
  { name: 'Ketu Transits the 9th House', description: 'Sattvic-eating detachment. Old guru-diets feel finished; principle-without-attachment ripens.' },
  { name: 'Ketu Transits the 10th House', description: 'Structural-diet eclipse. Old meal-schedule feels weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month deep purification of group-eating motivations.' },
  { name: 'Ketu Transits the 12th House', description: 'Foreign-cuisine and retreat-diet dissolution. Pleasure-eating evaporates.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar fire on the body. Cool the system; eat warm but not heating food.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Heating window opens. Stock cooling foods.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak heat day. Coconut water, cucumber, mint, melon.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Heating window closes. Resume normal balance.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar fire on eating-schedule. Lock in the structure; eat at fixed times.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Schedule-discipline window opens. Plan meal-times.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak schedule-day. Maintain the rhythm strictly.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on body. Eat with extra warmth and self-care.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotion-on-body window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Comfort-food cravings rise; choose something nourishing.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on schedule. Don\'t skip meals from busy-ness.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak day. Honor the meal-time even if work pulls.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp body-communication. Refresh the eating-plan.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Send the dietitian inquiry; write the food journal.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp schedule-communication. Lock in the meal-plan formally.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Publish the meal schedule to the household.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Personal warmth around food. Pleasure-eating window; indulge mindfully.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Indulge with intention.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens public-eating. Brand-friendly food choices.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak day. Photograph the beautiful meal.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Body fire peaks. Cooling foods mandatory.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Coconut water, cucumber, mint.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold scheduling-discipline. Lock in rigorous meal-plan.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak day. Execute the plan strictly.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Body expands. Weight-gain risk; portion control matters.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Larger appetite — control portions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Wisdom on eating-schedule. Lock in the long-term plan.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the long-term diet decision.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on the body. Joints, bones, slow weight gain risk.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Discipline the diet — bones, joints need warm oily food.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Discipline on eating-schedule. Lock in the rigorous meal-plan.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day. The schedule sets in.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic body-experimentation. Diet-fad pull strong; verify each protocol.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the unconventional dietary move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic schedule-disruption. Sudden meal-plan changes.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Body-stripping. Old eating-identity feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit with the dissolution; fasting easier.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Schedule eclipse. Old meal-pattern feels weightless.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Old schedule dissolves quietly.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting the long-term eating engine. Multi-year body-platform transformation; old metabolic patterns rebuild.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year metabolic reckoning begins. Old eating-frameworks dismantle.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak transformation day. The old eating-system breaks; a new one forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The metabolic-transformation chapter completes.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the foreign-pleasure eating channel. Unexpected dietary shifts; new cuisine fascinations; abrupt allergy emergence.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruption window opens. Expect surprise food-sensitivities.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. New food-trigger surfaces; the back-channel pivots.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption window closes. Integrate; release what didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 5th house', description: 'Birthday-window heart-fire activation. Heart-care foods: warm milk, dates, almonds, ghee.' },
  { name: 'Sun aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Sun in 5th house : Exact', description: 'Peak day. Honor the heart with warm nourishing food.' },
  { name: 'Sun aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Moon in 4th house', description: 'Solar light on home-cooking. Mother\'s recipes restore.' },
  { name: 'Sun aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Moon in 4th house : Exact', description: 'Peak day. Cook at home; eat with mother.' },
  { name: 'Sun aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mercury in 6th house', description: 'Solar fire on digestive engine. Best window for clean-eating reset.' },
  { name: 'Sun aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mercury in 6th house : Exact', description: 'Peak day. Run the elimination diet.' },
  { name: 'Sun aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Venus in 12th house', description: 'Solar light on foreign-pleasure eating. Foreign cuisine, retreat food.' },
  { name: 'Sun aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Venus in 12th house : Exact', description: 'Peak day. Visit the foreign restaurant; the retreat fare.' },
  { name: 'Sun aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mars in 1st house', description: 'Solar fire amplifies body-heat. Cooling foods mandatory.' },
  { name: 'Sun aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mars in 1st house : Exact', description: 'Peak heat day. Coconut water, mint, fennel.' },
  { name: 'Sun aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Jupiter in 9th house', description: 'Solar light on sattvic eating. Traditional ceremonial fare.' },
  { name: 'Sun aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Jupiter in 9th house : Exact', description: 'Peak day. Sattvic dal-rice-vegetable lunch.' },
  { name: 'Sun aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on structural-eating. Lock in fixed meal times.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak day. Schedule discipline.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Rahu in 5th house', description: 'Ambition-amplified performance-metabolism. Beware fad-diet chasing.' },
  { name: 'Sun aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Rahu in 5th house : Exact', description: 'Peak day. Verify the trendy protocol.' },
  { name: 'Sun aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Ketu in 11th house', description: 'Solar light on detached group-eating. Friend-meal news lands; eat with detachment.' },
  { name: 'Sun aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Ketu in 11th house : Exact', description: 'Peak day. Group meal lands quietly.' },
  { name: 'Sun aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Sun in 5th house', description: 'Emotional charge on heart-fire. Warm comfort meals.' },
  { name: 'Moon aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Sun in 5th house : Exact', description: 'Peak day. Heart-warming food: warm milk, dates.' },
  { name: 'Moon aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Moon in 4th house', description: 'Monthly home-kitchen peak.' },
  { name: 'Moon aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Moon in 4th house : Exact', description: 'Peak day. Eat with mother; cook traditional.' },
  { name: 'Moon aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mercury in 6th house', description: 'Empathetic digestive intelligence. Eat clean and simple.' },
  { name: 'Moon aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mercury in 6th house : Exact', description: 'Peak day. Light, easy meals.' },
  { name: 'Moon aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Venus in 12th house', description: 'Emotional warmth on retreat/foreign cuisine.' },
  { name: 'Moon aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Venus in 12th house : Exact', description: 'Peak day. Soft, soothing, foreign-tinged meals.' },
  { name: 'Moon aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mars in 1st house', description: 'Emotional charge on body-fire. Cool the system; eat warm but not heating.' },
  { name: 'Moon aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mars in 1st house : Exact', description: 'Peak day. Coconut, mint, fennel; warm not hot.' },
  { name: 'Moon aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Jupiter in 9th house', description: 'Emotional pull toward sattvic, ceremonial food.' },
  { name: 'Moon aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Jupiter in 9th house : Exact', description: 'Peak day. Traditional dal-rice; ghee.' },
  { name: 'Moon aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on schedule. Hold the meal-time even under stress.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day. Don\'t skip meals.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Rahu in 5th house', description: 'Emotional charge on performance-eating. Watch ambition-binge.' },
  { name: 'Moon aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Rahu in 5th house : Exact', description: 'Peak day. Stress-eating risk; pre-prep clean snacks.' },
  { name: 'Moon aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Ketu in 11th house', description: 'Emotional detachment from group-eating.' },
  { name: 'Moon aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Ketu in 11th house : Exact', description: 'Peak day. Friend-meals feel cool; eat lightly.' },
  { name: 'Moon aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Sun in 5th house', description: 'Sharp performance-eating communication. Coaching on heart-fitness diet.' },
  { name: 'Mercury aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Sun in 5th house : Exact', description: 'Peak day. Send the heart-fitness food plan.' },
  { name: 'Mercury aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Moon in 4th house', description: 'Emotionally-tuned home-cooking writing. Plan family menus.' },
  { name: 'Mercury aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Moon in 4th house : Exact', description: 'Peak day. Write the grocery list with care.' },
  { name: 'Mercury aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mercury in 6th house', description: 'Peak food-precision window of any quarter.' },
  { name: 'Mercury aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mercury in 6th house : Exact', description: 'Peak day. Audit the diet, identify triggers.' },
  { name: 'Mercury aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Venus in 12th house', description: 'Graceful foreign-cuisine and retreat-diet writing.' },
  { name: 'Mercury aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Venus in 12th house : Exact', description: 'Peak day. Plan the retreat menu.' },
  { name: 'Mercury aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mars in 1st house', description: 'Punchy body-discipline writing. Refresh the eating plan.' },
  { name: 'Mercury aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mars in 1st house : Exact', description: 'Peak day. Send the bold dietary refresh.' },
  { name: 'Mercury aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Jupiter in 9th house', description: 'Visionary food-philosophy writing. Sattvic, Ayurvedic study.' },
  { name: 'Mercury aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Jupiter in 9th house : Exact', description: 'Peak day. Read the traditional text.' },
  { name: 'Mercury aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Disciplined eating-schedule writing. Lock in the formal plan.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day. Publish the meal schedule to the household.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Rahu in 5th house', description: 'Bold dietary fad-research. Verify before adopting.' },
  { name: 'Mercury aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Rahu in 5th house : Exact', description: 'Peak day. Trendy diet-pitch lands — verify.' },
  { name: 'Mercury aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Ketu in 11th house', description: 'Sharp detached group-eating logistics. Cold dinner-party planning.' },
  { name: 'Mercury aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Ketu in 11th house : Exact', description: 'Peak day. Logistics close cleanly.' },
  { name: 'Mercury aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Sun in 5th house', description: 'Graceful performance-eating. Aesthetic plating, beautiful presentations.' },
  { name: 'Venus aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Sun in 5th house : Exact', description: 'Peak day. Cook the beautiful dish.' },
  { name: 'Venus aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Moon in 4th house', description: 'Beautiful home-cooking. Cook the elaborate family meal.' },
  { name: 'Venus aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Moon in 4th house : Exact', description: 'Peak day. Host the warm gathering.' },
  { name: 'Venus aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mercury in 6th house', description: 'Diplomatic dietary discipline. Soft eliminations work.' },
  { name: 'Venus aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mercury in 6th house : Exact', description: 'Peak day. Soft cleanse with sweet bitter herbs.' },
  { name: 'Venus aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Venus in 12th house', description: 'Peak foreign-cuisine, retreat-food, indulgent-dessert window.' },
  { name: 'Venus aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Venus in 12th house : Exact', description: 'Peak day. Visit the foreign restaurant or retreat kitchen.' },
  { name: 'Venus aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mars in 1st house', description: 'Charm-body window. Pleasure-eating with self-compassion.' },
  { name: 'Venus aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mars in 1st house : Exact', description: 'Peak day. Indulge mindfully.' },
  { name: 'Venus aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Jupiter in 9th house', description: 'Graceful sattvic eating. Ceremonial, traditional, foreign-temple food.' },
  { name: 'Venus aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Jupiter in 9th house : Exact', description: 'Peak day. Ceremonial sattvic meal.' },
  { name: 'Venus aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Softens public-eating. Brand-friendly photographable meals.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day. Photograph the meal.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Rahu in 5th house', description: 'Glamour-amplified eating. Trendy restaurants, fame-chef obsession.' },
  { name: 'Venus aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Rahu in 5th house : Exact', description: 'Peak day. Take the spotlight meal — anchor in dharma.' },
  { name: 'Venus aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Ketu in 11th house', description: 'Graceful but cool group-meals. Pleasant but restrained.' },
  { name: 'Venus aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Ketu in 11th house : Exact', description: 'Peak day. Friend-dinner is pleasant; emotionally muted.' },
  { name: 'Venus aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Sun in 5th house', description: 'Fiery performance-metabolism. Burn fuel cleanly; avoid heavy late meals.' },
  { name: 'Mars aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Sun in 5th house : Exact', description: 'Peak day. Light dinners; protein at midday.' },
  { name: 'Mars aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Moon in 4th house', description: 'Heated home-kitchen tension. Soften family food-arguments.' },
  { name: 'Mars aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Moon in 4th house : Exact', description: 'Peak day. Cook with calm; defer disputes.' },
  { name: 'Mars aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mercury in 6th house', description: 'Favorable for digestive combat. Excellent elimination diet day.' },
  { name: 'Mars aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mercury in 6th house : Exact', description: 'Peak day. Run the strict elimination.' },
  { name: 'Mars aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Venus in 12th house', description: 'Heated foreign-cuisine and bedroom-snacking. Watch alcohol.' },
  { name: 'Mars aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Venus in 12th house : Exact', description: 'Peak day. Foreign or hidden food-issues surface.' },
  { name: 'Mars aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mars in 1st house', description: 'Peak body-fire window of any two-year cycle. Cooling foods mandatory.' },
  { name: 'Mars aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mars in 1st house : Exact', description: 'Peak heat day. Coconut, cucumber, fennel, mint.' },
  { name: 'Mars aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Jupiter in 9th house', description: 'Bold sattvic discipline. Take on the traditional fast.' },
  { name: 'Mars aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Jupiter in 9th house : Exact', description: 'Peak day. Begin the disciplined fast.' },
  { name: 'Mars aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Strong scheduling-discipline. Lock in the rigorous meal-plan.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day. Execute the plan strictly.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Rahu in 5th house', description: 'Fiery ambition-eating. Beware extreme fad-diets; verify twice.' },
  { name: 'Mars aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Rahu in 5th house : Exact', description: 'Peak day. Resist the trendy extreme.' },
  { name: 'Mars aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Ketu in 11th house', description: 'Assertive group-cleanse with detachment.' },
  { name: 'Mars aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Ketu in 11th house : Exact', description: 'Peak day. Lead the friend-cleanse.' },
  { name: 'Mars aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Sun in 5th house', description: 'Wisdom on heart-fitness diet. Major celebratory meals; portion-control matters.' },
  { name: 'Jupiter aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Sun in 5th house : Exact', description: 'Peak day. Celebratory feast — but cap portions.' },
  { name: 'Jupiter aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Moon in 4th house', description: 'Wisdom on home-cooking. Family-tradition deepens.' },
  { name: 'Jupiter aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Moon in 4th house : Exact', description: 'Peak day. Cook the traditional family meal.' },
  { name: 'Jupiter aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mercury in 6th house', description: 'Wisdom on digestive engine. Major Ayurvedic study; gut-mastery deepens.' },
  { name: 'Jupiter aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mercury in 6th house : Exact', description: 'Peak day. The Ayurvedic protocol locks in.' },
  { name: 'Jupiter aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Venus in 12th house', description: 'Peak foreign-cuisine and retreat-food expansion.' },
  { name: 'Jupiter aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Venus in 12th house : Exact', description: 'Peak day. Visit the foreign retreat or temple kitchen.' },
  { name: 'Jupiter aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mars in 1st house', description: 'Wisdom on body-fire. Larger appetite — control portions.' },
  { name: 'Jupiter aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mars in 1st house : Exact', description: 'Peak day. Generous appetite; eat full but stop in time.' },
  { name: 'Jupiter aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Jupiter in 9th house', description: 'Peak sattvic-eating window of any twelve-year cycle. Pilgrimage-food, ceremonial-fast ideal.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Exact', description: 'Peak day. Take the pilgrimage food; lead the sattvic meal.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on long-term schedule. Lock in the multi-decade eating-pattern.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day. The structural diet locks in.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Rahu in 5th house', description: 'Wisdom on performance-eating ambition. Diet-fad gets a guru.' },
  { name: 'Jupiter aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Rahu in 5th house : Exact', description: 'Peak day. Principled performance-diet crystallizes.' },
  { name: 'Jupiter aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Ketu in 11th house', description: 'Wisdom on detached group-eating. Major friend-cleanse with equanimity.' },
  { name: 'Jupiter aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Ketu in 11th house : Exact', description: 'Peak day. Group-meal lands; honor without clinging.' },
  { name: 'Jupiter aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Sun in 5th house', description: 'Structural test of performance-metabolism. Heart-care, bone-density work.' },
  { name: 'Saturn aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Sun in 5th house : Exact', description: 'Peak day. Heart-and-bone food: ghee, sesame, almonds.' },
  { name: 'Saturn aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Moon in 4th house', description: 'Heaviness on home-kitchen. Mother\'s health-and-food becomes structural concern.' },
  { name: 'Saturn aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Moon in 4th house : Exact', description: 'Peak day. Mother needs nutritional care.' },
  { name: 'Saturn aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mercury in 6th house', description: 'Favorable for long-term gut-mastery. Multi-year diet that compounds.' },
  { name: 'Saturn aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mercury in 6th house : Exact', description: 'Peak day. The structural Ayurvedic diet sets in.' },
  { name: 'Saturn aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Venus in 12th house', description: 'Multi-year discipline on foreign cuisine, retreat-food, pleasure-eating.' },
  { name: 'Saturn aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Venus in 12th house : Exact', description: 'Peak day. Foreign-eating habits formalize.' },
  { name: 'Saturn aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mars in 1st house', description: 'Heavy structural test of body-fire. Joints, bones, slow weight-gain risk.' },
  { name: 'Saturn aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mars in 1st house : Exact', description: 'Peak day. Warm, oily, sesame-rich food for joints.' },
  { name: 'Saturn aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Jupiter in 9th house', description: 'Discipline on sattvic/traditional eating. Slow ceremonial-fast practice.' },
  { name: 'Saturn aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Jupiter in 9th house : Exact', description: 'Peak day. The traditional fast lands.' },
  { name: 'Saturn aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Peak schedule-restructure window of any thirty-year cycle.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak day. Accept the multi-decade meal-pattern.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Rahu in 5th house', description: 'Discipline on performance-ambition eating. Speculative diets deflate.' },
  { name: 'Saturn aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Rahu in 5th house : Exact', description: 'Peak day. Fad-diet bubble pops.' },
  { name: 'Saturn aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Ketu in 11th house', description: 'Disciplined group-eating purification.' },
  { name: 'Saturn aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Ketu in 11th house : Exact', description: 'Peak day. The unhealthy group-eating pattern falls away.' },
  { name: 'Saturn aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Sun in 5th house', description: 'Peak performance-eating ambition window of any eighteen-year cycle. Verify dharma.' },
  { name: 'Rahu aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Sun in 5th house : Exact', description: 'Peak day. The fad-leap presents — verify.' },
  { name: 'Rahu aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Moon in 4th house', description: 'Obsessive home-cooking reinvention. Foreign-recipe pull.' },
  { name: 'Rahu aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Moon in 4th house : Exact', description: 'Peak day. Foreign-cuisine pull peaks.' },
  { name: 'Rahu aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mercury in 6th house', description: 'Favorable. Defeat a chronic gut-issue, win against long-running food sensitivity.' },
  { name: 'Rahu aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mercury in 6th house : Exact', description: 'Peak day. Major sensitivity yields.' },
  { name: 'Rahu aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Venus in 12th house', description: 'Obsessive foreign-cuisine and retreat-food pull.' },
  { name: 'Rahu aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Venus in 12th house : Exact', description: 'Peak day. Foreign-cuisine pull peaks.' },
  { name: 'Rahu aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mars in 1st house', description: 'Obsessive body-reinvention. New diet, new body-image.' },
  { name: 'Rahu aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mars in 1st house : Exact', description: 'Peak day. Body-reinvention leap presents — verify.' },
  { name: 'Rahu aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Jupiter in 9th house', description: 'Foreign-fortune food obsession. International cuisine.' },
  { name: 'Rahu aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Jupiter in 9th house : Exact', description: 'Peak day. Foreign-food leap presents.' },
  { name: 'Rahu aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Obsessive schedule-disruption. Sudden meal-plan changes.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day. Bold dietary-leap presents — verify.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Rahu in 5th house', description: 'Eighteen-year apex of performance-eating cycle.' },
  { name: 'Rahu aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Rahu in 5th house : Exact', description: 'Peak day. The fad-cycle peaks.' },
  { name: 'Rahu aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Ketu in 11th house', description: 'Generational reckoning of group-eating dynamics.' },
  { name: 'Rahu aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Ketu in 11th house : Exact', description: 'Peak day. Diet-defining group event lands.' },
  { name: 'Rahu aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Sun in 5th house', description: 'Performance-eating eclipse. Old fame-diet feels hollow.' },
  { name: 'Ketu aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Sun in 5th house : Exact', description: 'Peak day. Old protocol dissolves.' },
  { name: 'Ketu aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Moon in 4th house', description: 'Home-kitchen detachment. Less attachment to family-recipes.' },
  { name: 'Ketu aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Moon in 4th house : Exact', description: 'Peak day. Simplification impulse peaks.' },
  { name: 'Ketu aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mercury in 6th house', description: 'Service-eating detachment. Old gut-issues dissolve.' },
  { name: 'Ketu aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mercury in 6th house : Exact', description: 'Peak day. Old chronic issue fades.' },
  { name: 'Ketu aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Venus in 12th house', description: 'Foreign-cuisine and retreat-food dissolution.' },
  { name: 'Ketu aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Venus in 12th house : Exact', description: 'Peak day. Old foreign-cuisine attachment closes.' },
  { name: 'Ketu aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mars in 1st house', description: 'Body-stripping. Old eating-identity dissolves.' },
  { name: 'Ketu aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mars in 1st house : Exact', description: 'Peak day. Fasting easier; old protocol dissolves.' },
  { name: 'Ketu aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Jupiter in 9th house', description: 'Sattvic-eating detachment. Old guru-diets feel finished.' },
  { name: 'Ketu aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Jupiter in 9th house : Exact', description: 'Peak day. Old principle-diet dissolves.' },
  { name: 'Ketu aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Schedule eclipse. Old meal-pattern feels weightless.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day. Old structure dissolves.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Rahu in 5th house', description: 'Generational fad-vs-discipline reckoning.' },
  { name: 'Ketu aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Rahu in 5th house : Exact', description: 'Peak day. Old fad-cycle ends.' },
  { name: 'Ketu aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Ketu in 11th house', description: 'Eighteen-year apex of group-eating detachment.' },
  { name: 'Ketu aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Ketu in 11th house : Exact', description: 'Peak day. Old group-eating pattern dissolves.' },
  { name: 'Ketu aspect Ketu in 11th house : Ends', description: 'Window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
