// db/seed_food_cancer.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to a
// representative Cancer ascendant native with:
//   Ascendant: Cancer (Kapha-Pitta-leaning, water-cardinal, Moon-ruled)
//   Natal: Sun=3rd Moon=2nd Mercury=3rd Venus=4th(own) Mars=7th(exalted)
//          Jupiter=6th(own) Saturn=8th(own) Rahu=9th Ketu=3rd

const db = require('./food');

const ASCENDANT = 'Cancer';

const events = [
  // RULERS (12)
  { name: 'Moon ruler of the 1st House in the 2nd House', description: 'Eating IS your nervous-system regulation. When mood drops, food is your first medicine — make sure it\'s the right medicine. You overeat when emotional, undereat when overworked. Family meals are sacred infrastructure for your wellbeing. Best diet: warm, cooked, lightly spiced family-style food shared at a real table.' },
  { name: 'Sun ruler of the 2nd House in the 3rd House', description: 'The body responds well to structured eating windows, measured portions, the same 6 trustworthy meals on rotation. Skip the diet-trend; commit to the steady protocol. Sun in Virgo with Mercury and Ketu = a Virgo-style cluster around food: ingredients matter; provenance matters; the digestive log helps.' },
  { name: 'Mercury ruler of the 3rd House in the 3rd House', description: 'Peak digestive intelligence. You can read your gut\'s signals more accurately than most charts. Trust the body\'s yes/no on food more than any external nutrition rule. Best for: keeping a food journal, learning the systematic effects of each food on you. The Virgo precision in food digestion is your superpower if you train it.' },
  { name: 'Venus ruler of the 4th House in the 4th House', description: 'Mother\'s recipes are not nostalgia but actual medicine for your constitution. The home kitchen IS your wellness center. Beautify the dining space; eat at a real table; protect the lunch hour. Hospitality work, family-style restaurants, mother\'s-recipe products thrive as side income.' },
  { name: 'Mars ruler of the 5th House in the 7th House', description: 'Eat with disciplined people; the partner\'s plate shapes yours. Best for: structured meal-prep with partner, scheduled couples-cooking, restaurant outings as a discipline.' },
  { name: 'Jupiter ruler of the 6th House in the 6th House', description: 'Hamsa-style health. The digestive system is naturally robust. You can eat what would destroy lesser stomachs IF you stay on principle. Best for: traditional dharmic diet, fasting on principle (not vanity), turmeric-ginger-cumin foundation. Ayurvedic-trained chefs find you instinctively.' },
  { name: 'Saturn ruler of the 7th House in the 8th House', description: 'Food during life transitions matters more — illness recovery, childbirth, surgery, deep grief. The structured fast (Saturn-style), the disciplined elimination diet, the long-term protocol all serve you well. Joint food decisions with partner mature slowly.' },
  { name: 'Saturn ruler of the 8th House in the 8th House', description: 'Vipareet on the longevity/transformation axis. Slow-build food habits compound massively over decades. The same measured diet at age 30 looks austere; at age 70 it has saved your life. Best for: longevity-protocol food, structured intermittent eating, Ayurvedic seasonal protocols. Avoid: extreme one-week trend diets.' },
  { name: 'Jupiter ruler of the 9th House in the 6th House', description: 'Father-figure mentors and gurus often share their food wisdom; absorb it. Foreign cuisines work IF dharma-aligned (vegetarian-leaning, traditional, mindfully sourced). Long pilgrimages reset your gut better than any cleanse.' },
  { name: 'Mars ruler of the 10th House in the 7th House', description: 'Business meals matter; the structured restaurant lunch with the right partner shapes career. Eat to be sharp for the deal; eat with discipline; the partner sees how you eat and forms judgments accordingly. Avoid combative eating habits at deal tables.' },
  { name: 'Venus ruler of the 11th House in the 4th House', description: 'Best food side-incomes: home-bakery, family recipe books, hospitality, design of dining experiences. Friend-network gains through hosting; the table is the social/financial integrator.' },
  { name: 'Mercury ruler of the 12th House in the 3rd House', description: 'The shadow: night-eating that drains you the next day. Best for: structured travel-food protocol, foreign-cuisine integration done methodically. Watch confidential indulgences; sleep-eating costs you.' },

  // DISPOSITORS (5)
  { name: 'Mercury in 3rd (Dispositor)', description: 'The digestive intelligence is the engine that drives both authority over food and ability to detach from cravings. Best for: tracking what works, eliminating what doesn\'t, building the Virgo-precise protocol. The shadow: orthorexia — Virgo Mercury can become rigid about food rules. Stay structured but not punitive.' },
  { name: 'Sun in 3rd (Dispositor)', description: 'Methodical authority on food wired to emotional eating engine. Best for: structured meal authorship; the Virgo-precise protocol that becomes your standard. The shadow: ego-around-food (the fancy diet, the curated photo, the food as identity). Eat for body, not for status.' },
  { name: 'Venus in 4th (Dispositor)', description: 'Home-cooking is the harmony engine itself. The kitchen is the relationship; the table is the family; mother\'s recipes are the foundation. Female mentors arrive with food wisdom. Hospitality, family-recipe businesses, beautiful-table-design work all favored.' },
  { name: 'Saturn in 8th (Dispositor)', description: 'Structural food discipline anchors everything. The 25-year fasting practice; the lifelong elimination of one ingredient that didn\'t serve you; the slow long-term protocol. The shadow: rigidity that punishes the body during life events that demand flexibility (pregnancy, illness, social ritual).' },
  { name: 'Jupiter in 6th (Dispositor)', description: 'Service-with-wisdom anchors the foreign-cuisine obsession. Foreign foods are blessed when they\'re dharmically sourced (traditional, sattvic-leaning, mindful). The Italian grandmother\'s recipe, the Ayurvedic kitchari, the Japanese ichiju-sansai — all work for you because of their tradition, not their novelty.' },

  // TRANSITS (108)
  { name: 'Sun Transits the 1st House', description: 'Body sensitive to heat, sun exposure, hot foods. Cool down the food slightly; favor coconut water, cucumber, mint. Watch sun-related skin/eye reactions during this month.' },
  { name: 'Sun Transits the 2nd House', description: 'Heated speech and family-table dynamics. Watch the throat, mouth, dental health. Best for: addressing family-meal-pattern issues directly. Cool drinks at meals; reduce strongly-heating spices for 30 days.' },
  { name: 'Sun Transits the 3rd House', description: 'Annual peak for digestive precision. Best window of the year to tighten the food protocol; track every meal; identify the silent-saboteur food. Mid-day meal becomes the strongest meal.' },
  { name: 'Sun Transits the 4th House', description: 'Peak home-kitchen visibility. Update the kitchen, the dining space, the cookware. Mother\'s wisdom on food surfaces; absorb it.' },
  { name: 'Sun Transits the 5th House', description: 'Sun in 5H Scorpio energizes creative cooking, mentee-eating, romance-meal dynamics. Best for: cooking with depth and intention; the date-night meal that matters.' },
  { name: 'Sun Transits the 6th House', description: 'Service-and-care peak in food. Show up for partner\'s/family\'s health-eating needs. Best window to address the chronic gut issue, food sensitivity, lingering imbalance.' },
  { name: 'Sun Transits the 7th House', description: 'Partnership-meal visibility. Business meals matter; structured restaurant outings shape the year. Watch ego-friction at the table.' },
  { name: 'Sun Transits the 8th House', description: 'Transformation-eating zone. Best for: structured fasts, elimination protocols, deep gut cleanses, surgery-recovery food regimens.' },
  { name: 'Sun Transits the 9th House', description: 'Foreign cuisine spotlight. Best for: integrating one foreign tradition into your protocol (Ayurvedic, Mediterranean, Japanese, etc.) with dharmic intent.' },
  { name: 'Sun Transits the 10th House', description: 'Public-meal visibility. Networking dinners, business-lunches, the meals where the work gets done. Eat for sharpness; show up well.' },
  { name: 'Sun Transits the 11th House', description: 'Friend-network meal spotlight. Best for: hosting the senior peer dinner, joining the food-club, deepening eating-related friendships.' },
  { name: 'Sun Transits the 12th House', description: 'Private/foreign/late-night eating dynamics. Plan the retreat-with-clean-food; watch confidential indulgences; address late-night snacking.' },
  { name: 'Moon Transits the 1st House', description: 'Peak emotional-eating sensitivity. Eat warm cooked food today; emotional triggers around eating spike.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on speech, family-table, voice. Family meal lands warmly OR triggers depending on dynamics.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on Virgo-precise eating. The body knows what it wants; listen.' },
  { name: 'Moon Transits the 4th House', description: 'Peak home-kitchen days. Cook the slow meal; eat at the real table.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional intensity in pleasure-eating. Channel into a beautiful planned meal; avoid emotional snacking.' },
  { name: 'Moon Transits the 6th House', description: 'Service-care food days. Cook for someone who needs it; the act heals you both.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge at shared-meal table. Read partner\'s mood before suggesting the dinner topic.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight in shared-resource food zone. Eat lightly; defer hard food-related decisions.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward foreign cuisine, gurus\' diets. Try the new tradition mindfully.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on public-meal performance. Sensitive to how you appear at the deal table.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth at friend-table. Host the gathering; share the meal.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional energy drains. Eat lightly; sleep more; avoid late-night eating.' },
  { name: 'Mercury Transits the 1st House', description: 'Emotionally attuned attention to body-state. Best for: starting the food journal, the body-scan practice, the hydration log.' },
  { name: 'Mercury Transits the 2nd House', description: 'Passionate vocal/family-table communication around food. Best for: family-recipe documentation, the food-related conversation with mother.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak digestive-tracking window. Refine the protocol; identify the silent saboteur food; map the gut signals.' },
  { name: 'Mercury Transits the 4th House', description: 'Diplomatic kitchen-communication. Best for: family-recipe writing, mother-cookbook, design-thinking the dining ritual.' },
  { name: 'Mercury Transits the 5th House', description: 'Investigative pleasure-food. Due-diligence on a new restaurant; analytical date-night eating.' },
  { name: 'Mercury Transits the 6th House', description: 'Peak service-food window. SOPs, meal-plans, scheduled-eating protocols, supplement regimens.' },
  { name: 'Mercury Transits the 7th House', description: 'Disciplined business-meal communication. Best for: structuring the deal-dinner protocol with partner.' },
  { name: 'Mercury Transits the 8th House', description: 'Investigative depth-research on food. Best for: gut-microbiome work, food-sensitivity testing, longevity-protocol research.' },
  { name: 'Mercury Transits the 9th House', description: 'Debilitated, but Rahu amplifies. Best for: studying foreign food traditions; worst for: precise food-language negotiation.' },
  { name: 'Mercury Transits the 10th House', description: 'Punchy public-meal communication. Restaurant reviews, food-content posting, public-meal etiquette.' },
  { name: 'Mercury Transits the 11th House', description: 'Patient food-friend network communication. Plan the food-club; coordinate the group dinner.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential food research, foreign-cuisine deep-dive, late-night reading on diet. Watch midnight food-scrolling.' },
  { name: 'Venus Transits the 1st House', description: 'Exalted-style eating-charm. Best for: the beautiful presentation, the date-meal, hospitality-style eating.' },
  { name: 'Venus Transits the 2nd House', description: 'Luxurious vocal/family-table window. Indulge mindfully; family-meal harmonizes.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful eating with peers/siblings. Beautiful precision in food.' },
  { name: 'Venus Transits the 4th House', description: 'Annual peak for home-table beauty. Beautify the kitchen, sign cooking-school, deepen with mother around food.' },
  { name: 'Venus Transits the 5th House', description: 'Peak romance-meal/pleasure-eating window. Date nights, indulgent gourmet experiences.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic service-food. Best for: HR-style food-coordination, conflict-resolution-over-meal, healing-food prep.' },
  { name: 'Venus Transits the 7th House', description: 'Peak shared-meal warmth. The marriage-formalizing dinner; the contract-celebration meal.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic transformation-eating. Recovery meals, comfort food during loss, gentle reintroduction after fasting.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful foreign-cuisine engagement. Travel-meal favored; cross-cultural cooking exchange.' },
  { name: 'Venus Transits the 10th House', description: 'Softer public-meal image. Beautiful business-lunch presentation.' },
  { name: 'Venus Transits the 11th House', description: 'Friend-network meal warmth peaks. Hosting; group dinners; female-friend cooking exchanges.' },
  { name: 'Venus Transits the 12th House', description: 'Quiet pleasure-eating; foreign luxury food; hidden indulgences. Watch over-spending on travel-cuisine.' },
  { name: 'Mars Transits the 1st House', description: 'Energy up but body fragile. Reduce strongly-heating foods; favor cooling, soothing, slow-cooked dishes.' },
  { name: 'Mars Transits the 2nd House', description: 'Heated speech/family-table flares. Watch the throat, mouth, dental issues. Avoid hot-spicy food at family dinners.' },
  { name: 'Mars Transits the 3rd House', description: 'Fierce digestive-action window. Best for: the cleanse-execution; worst for: rushed eating, eating while angry.' },
  { name: 'Mars Transits the 4th House', description: 'Debilitated Mars meets exalted Venus in home zone. Kitchen disputes flare; decisive cookware-or-recipe action favored.' },
  { name: 'Mars Transits the 5th House', description: 'Drive in pleasure-cooking, romance-meals, mentee-feeding. Best for: aggressive recipe development, decisive entertaining.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable digestive combat. Win the long-pending gut issue; defeat the chronic food-sensitivity problem.' },
  { name: 'Mars Transits the 7th House', description: 'Peak structured shared-meal action. Major partnership-meal protocols, business-meal discipline.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical dietary action. Cleanses, eliminations, structured fasts, recovery-meal protocols.' },
  { name: 'Mars Transits the 9th House', description: 'Assertive foreign-cuisine moves. Take the principled stand on dietary philosophy.' },
  { name: 'Mars Transits the 10th House', description: 'Bold public-meal assertion. Eat to be sharp at the high-stakes lunch.' },
  { name: 'Mars Transits the 11th House', description: 'Heated friend-table dynamics. Aggressive event planning; food-related peer-rivalry.' },
  { name: 'Mars Transits the 12th House', description: 'Hidden frictions at the late-night fridge. Avoid late-night impulsive eating.' },
  { name: 'Jupiter Transits the 1st House', description: 'Once-in-12-years personal expansion includes weight gain (manage it). Body wants comfort food; discipline matters. Best for: long-term health-protocol commitment, certified-Ayurvedic study.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Vocal/family-table expansion. Family wealth grows through food (recipe-business, hospitality side-income). Watch over-eating at family meals.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Flagship year for digestive-precision. Major dietary-protocol crystallizes; food-tracking becomes high-precision.' },
  { name: 'Jupiter Transits the 4th House', description: 'Exalted-style home-kitchen expansion. Major kitchen upgrade; mother-recipe documentation; family-meal foundation deepens.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major creative-cooking year. Recipe development, cookbook writing, mentee-cooking-coaching all flourish.' },
  { name: 'Jupiter Transits the 6th House', description: 'Service-with-wisdom food year. Health-care-via-food deepens; chronic gut issues heal; regimens crystallize.' },
  { name: 'Jupiter Transits the 7th House', description: 'Debilitated Jupiter, but Mars cushions. Major partnership-meal commitment moves. Choose carefully; over-indulgence at the deal-table costs.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into transformation-eating. Inheritance-meals, recovery-food regimens, deep cleanses.' },
  { name: 'Jupiter Transits the 9th House', description: 'Own-sign Jupiter on the dharma-food node. Major year for foreign tradition integration (Ayurveda, Med, Japanese), pilgrimage food, dharmic eating.' },
  { name: 'Jupiter Transits the 10th House', description: 'Public-meal expansion. Speaking on food, being seen at major-restaurant dinners, food-content recognition.' },
  { name: 'Jupiter Transits the 11th House', description: 'Friend-network food expansion. Major food-club growth; group cooking events; gainful food-collaborations.' },
  { name: 'Jupiter Transits the 12th House', description: 'Private/foreign/sabbatical food dimension grows. Travel-eating, retreat-cleansing, behind-scenes food-research.' },
  { name: 'Saturn Transits the 1st House', description: 'Sade Sati 2nd leg. Body under structural test. Slow down eating; simplify the diet; protein/sleep/hydration discipline matters.' },
  { name: 'Saturn Transits the 2nd House', description: 'Sade Sati 3rd leg. Family-table reckoning; speech-around-food discipline. Address the family eating pattern that\'s never worked.' },
  { name: 'Saturn Transits the 3rd House', description: 'Heavy digestive-protocol chapter. The years-long elimination diet; the structural food-system commitment.' },
  { name: 'Saturn Transits the 4th House', description: 'Home-kitchen under structural test. Buy quality cookware; hold patiently; support mother\'s evolving food needs.' },
  { name: 'Saturn Transits the 5th House', description: 'Pleasure-eating demands seriousness. The casual indulgence chapter ends; structured pleasure begins.' },
  { name: 'Saturn Transits the 6th House', description: 'Favorable. Long gut-issues resolve through patience; chronic food-sensitivity heals slowly.' },
  { name: 'Saturn Transits the 7th House', description: 'Heavy shared-meal chapter. The marriage-eating-pattern under structural review.' },
  { name: 'Saturn Transits the 8th House', description: 'Once-in-29-years deep transformation in shared-resources/digestive-system. Half-life food reckoning.' },
  { name: 'Saturn Transits the 9th House', description: 'Dharma-food under structural pressure. The cross-cultural eating tradition demands compliance and patience.' },
  { name: 'Saturn Transits the 10th House', description: 'Public-meal chapter under heavy review. The way you eat in public earns slow respect.' },
  { name: 'Saturn Transits the 11th House', description: 'Food-friend-network discipline. The food-club shrinks to the real ones.' },
  { name: 'Saturn Transits the 12th House', description: 'Sade Sati 1st leg. Withdrawal in eating habits; foreign-food-detachment phase begins.' },
  { name: 'Rahu Transits the 1st House', description: 'Once-in-18-years body-shock. New dietary obsession forms; foreign-cuisine self emerges. Watch trend-diet derailments.' },
  { name: 'Rahu Transits the 2nd House', description: 'Chaotic family-table/voice/speech around food. Speculative diet-protocol moves; family-eating-pattern reshuffles.' },
  { name: 'Rahu Transits the 3rd House', description: 'Explosive digestive-experimentation. Viral diet trends pull at you; track results.' },
  { name: 'Rahu Transits the 4th House', description: 'Chaotic home-kitchen dynamics. Sudden kitchen-upgrades, foreign-appliance acquisitions, mother-recipe shifts.' },
  { name: 'Rahu Transits the 5th House', description: 'Speculative-pleasure-eating. Unconventional gourmet experiments, controversial creative cooking.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat chronic gut-rivals; expand into unconventional health-eating domains.' },
  { name: 'Rahu Transits the 7th House', description: 'Chaotic shared-meal dynamics. Foreign-partner eating habits, surprise restaurant rituals. Vet rigorously.' },
  { name: 'Rahu Transits the 8th House', description: 'Sudden transformation-eating events. Surprise food-allergy discoveries, abrupt elimination protocols.' },
  { name: 'Rahu Transits the 9th House', description: 'Once-in-18-years foreign-cuisine peak. Cross-cultural food obsession intensifies.' },
  { name: 'Rahu Transits the 10th House', description: 'Meteoric public-meal shifts. Sudden food-content virality, abrupt change in food-related public role.' },
  { name: 'Rahu Transits the 11th House', description: 'Chaotic food-network expansion. Unusual food-club affiliations, foreign-chef ties.' },
  { name: 'Rahu Transits the 12th House', description: 'Foreign-food relocation, hidden-eating dynamics, sleep-disrupting cravings. Watch obsessive late-night food-research.' },
  { name: 'Ketu Transits the 1st House', description: 'Body-identity stripping. Old dietary identity feels empty; appetite drops; old food rituals fade.' },
  { name: 'Ketu Transits the 2nd House', description: 'Emotional detachment from family-table/speech around food. The family eating pattern recalibrates.' },
  { name: 'Ketu Transits the 3rd House', description: 'Old digestive habits dissolve; new precision required. Reset the protocol.' },
  { name: 'Ketu Transits the 4th House', description: 'Detachment from home-kitchen indulgence. Selling old cookware, downsizing pantry, mother-style independence in food.' },
  { name: 'Ketu Transits the 5th House', description: 'Pleasure-eating feels hollow. Use for non-monetary food-study, recipe-research without indulgence.' },
  { name: 'Ketu Transits the 6th House', description: 'Chronic food-enemies disengage; long gut-issues close; service-eating ends.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership-meal eclipse. Long restaurant-rituals quietly end; spouse-eating dynamic recalibrates.' },
  { name: 'Ketu Transits the 8th House', description: 'Deep transformation-detachment in shared eating. Honor what wants to end.' },
  { name: 'Ketu Transits the 9th House', description: 'Eclipse on dharma-food node. Long-cherished foreign-tradition recalibrates.' },
  { name: 'Ketu Transits the 10th House', description: 'Public-meal visibility flickers. Food-as-social-currency dissolves.' },
  { name: 'Ketu Transits the 11th House', description: 'Food-network burn-through. Transactional eating-friendships fade.' },
  { name: 'Ketu Transits the 12th House', description: 'Quiet foreign-food/isolation chapter. Late-night eating dissolves; spiritual-eating dimension deepens.' },

  // ANGLE ASPECTS (72)
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Cool down food slightly; manage hydration.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Pre-load hydration; watch sun-food balance.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Eat lighter, cooler; favor coconut water, cucumber, mint.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Resume normal protocol.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Show up sharp at the deal-dinner.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Plan the high-stakes business meal.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Eat to be sharp.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Public-meal window fades.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Listen to the gut\'s signals carefully.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Eat warm cooked food.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'The gut speaks loudly today; honor its requests.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Body-emotion window fades.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Mood at the table is read by the room.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Public-emotion-meal window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Show up regulated at the meal.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Public-emotion-meal closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury sharpens body-articulation. Best for: starting the food journal, the body-tracking practice.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Body-articulation window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Track the meal effects in detail.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Body-articulation closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on public-meal zenith. Restaurant reviews, food-content posts, public-meal etiquette.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Public-food-comm window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Post the review; share the recipe.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Public-food-comm closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Peak hospitality-eating charm.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Body-charm window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Beautiful presentation; gracious eating.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Body-charm fades.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Diplomatic, beautiful business-meal visibility.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Public-meal-warmth window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Host the elegant business dinner.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Public-meal-warmth closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Energy up but body fragile. Avoid hot-spicy, fast-eating.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Body-action window opens with debilitated edge.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Cool the food; slow the eating.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Body-action fades.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Competitive eating moves. Watch combative table-tone.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Public-meal-action window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Bold business-meal action.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Public-meal-action cools.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Once-in-12-years digestive-expansion. Manage weight; the body wants comfort.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Body-expansion window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Long-term health-protocol commitment.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Body-expansion closes. Lock in the structure.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Expansive food-recognition.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Public-food-expansion window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Take the food-content elevation.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Public-food-expansion closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Structural test. Slow down eating; simplify; protein-sleep-hydration discipline.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Body-discipline window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Hold the disciplined protocol.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Body-discipline closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public-eating tested for staying power.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Public-eating-discipline window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Disciplined business-meal earns slow respect.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Public-eating-Saturn closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic dietary identity expansion. New trend-diet pulls; vet carefully.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Rahu-body window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Try the new protocol but with discipline.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu-body closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic food-visibility expansion.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Rahu-MC window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'The viral food-moment; verify before leveraging.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu-MC closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Appetite drops; old food identity feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Ketu-body window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Eat lightly; observe the dissolving cravings.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Ketu-body closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse on food-as-status.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Public-eating-eclipse window opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'The food-influencer role dissolves.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Public-eating-eclipse closes.' },

  // OUTER SPECIALS (8)
  { name: 'Pluto conjunct Saturn', description: 'Generational reckoning on Saturn (Aquarius 8H). Joint-eating habits, deep digestive structures, longevity protocols all transform fundamentally. Old comfort-food identity dies.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural-food reckoning begins. Old eating-pattern dismantles.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Old protocol breaks; new is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Food-transformation chapter completes. New foundation emerges.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption on Venus (Libra 4H). Unexpected kitchen-shifts, surprise allergies, abrupt change in dining preferences.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Expect kitchen surprises.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Sudden allergy-discovery, kitchen-equipment failure, unexpected ingredient love.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Uranus-Venus shock closes. Integrate.' },

  // ASPECTS (324)
  // — Jupiter aspects natal —
  { name: 'Jupiter aspect Sun in 3rd house', description: 'Expansive Virgo-precise eating. Best for: starting the dharmic-protocol, expanding the trusted food rotation.' },
  { name: 'Jupiter aspect Sun in 3rd house : Starts', description: 'Plan the protocol expansion.' },
  { name: 'Jupiter aspect Sun in 3rd house : Exact', description: 'Peak day for authoritative food protocol. Commit to the regimen.' },
  { name: 'Jupiter aspect Sun in 3rd house : Ends', description: 'Lock in the protocol.' },
  { name: 'Jupiter aspect Moon in 2nd house', description: 'Vocal/family-table expansion. Watch portion sizes; family meals expand both warmth and waistline.' },
  { name: 'Jupiter aspect Moon in 2nd house : Starts', description: 'Plan generously, eat moderately.' },
  { name: 'Jupiter aspect Moon in 2nd house : Exact', description: 'Host the family meal; watch the portions.' },
  { name: 'Jupiter aspect Moon in 2nd house : Ends', description: 'Family-table window closes.' },
  { name: 'Jupiter aspect Mercury in 3rd house', description: 'Peak digestive-precision wisdom. Refine the protocol; integrate one new ingredient mindfully.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Starts', description: 'Digestive-wisdom window opens.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Exact', description: 'The food-protocol crystallizes.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Ends', description: 'Digestive-wisdom closes.' },
  { name: 'Jupiter aspect Venus in 4th house', description: 'Peak home-kitchen expansion. Major cookware upgrade; mother-recipe integration; family-meal foundation deepens.' },
  { name: 'Jupiter aspect Venus in 4th house : Starts', description: 'Home-kitchen-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 4th house : Exact', description: 'Buy the quality cookware; document the family recipe.' },
  { name: 'Jupiter aspect Venus in 4th house : Ends', description: 'Home-kitchen-expansion closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Expansive shared-meal commitment. Restaurant-membership formalization, partner-meal-protocol.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Shared-meal-expansion window opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Sign the shared-meal commitment.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Shared-meal-expansion closes.' },
  { name: 'Jupiter aspect Jupiter in 6th house', description: 'Service-with-wisdom food year. Health-via-food deepens; chronic gut issues heal.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Starts', description: 'Service-food window opens.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Exact', description: 'The chronic gut-issue heals.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Ends', description: 'Service-food closes.' },
  { name: 'Jupiter aspect Saturn in 8th house', description: 'Wisdom into transformation-eating. Recovery protocols, structured cleanses favored.' },
  { name: 'Jupiter aspect Saturn in 8th house : Starts', description: 'Transformation-food window opens.' },
  { name: 'Jupiter aspect Saturn in 8th house : Exact', description: 'Begin the structured cleanse.' },
  { name: 'Jupiter aspect Saturn in 8th house : Ends', description: 'Transformation-food closes.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Own-sign Jupiter on dharma-food node. Peak window for foreign-tradition integration.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Foreign-food-wisdom window opens.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Integrate the dharmic foreign tradition.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Foreign-food-wisdom closes.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on detached-eating. Solo mindful meals flourish; group-eating chatter feels hollow.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Solo-mindful-eating window opens.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'The contemplative meal lands.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Solo-mindful-eating closes.' },

  // — Ketu aspects natal —
  { name: 'Ketu aspect Sun in 3rd house', description: 'Food-authority feels hollow; ego-around-food drops. Eat for body, not status.' },
  { name: 'Ketu aspect Sun in 3rd house : Starts', description: 'Food-ego eclipse begins.' },
  { name: 'Ketu aspect Sun in 3rd house : Exact', description: 'The fancy-diet identity drops.' },
  { name: 'Ketu aspect Sun in 3rd house : Ends', description: 'Food-ego eclipse closes.' },
  { name: 'Ketu aspect Moon in 2nd house', description: 'Emotional detachment from family-table. Family-meal pattern recalibrates.' },
  { name: 'Ketu aspect Moon in 2nd house : Starts', description: 'Family-table detachment begins.' },
  { name: 'Ketu aspect Moon in 2nd house : Exact', description: 'Family meal feels distant.' },
  { name: 'Ketu aspect Moon in 2nd house : Ends', description: 'Family-table detachment fades.' },
  { name: 'Ketu aspect Mercury in 3rd house', description: 'Paradoxical detached-precision in eating. Solo intuitive eating favored over tracked.' },
  { name: 'Ketu aspect Mercury in 3rd house : Starts', description: 'Detached-eating window opens.' },
  { name: 'Ketu aspect Mercury in 3rd house : Exact', description: 'Set the food journal aside; eat by feel.' },
  { name: 'Ketu aspect Mercury in 3rd house : Ends', description: 'Detached-eating closes.' },
  { name: 'Ketu aspect Venus in 4th house', description: 'Detachment from home-kitchen indulgence. Pantry-purge favored; declutter cookware.' },
  { name: 'Ketu aspect Venus in 4th house : Starts', description: 'Kitchen-detachment begins.' },
  { name: 'Ketu aspect Venus in 4th house : Exact', description: 'Donate the unused kitchen tools.' },
  { name: 'Ketu aspect Venus in 4th house : Ends', description: 'Kitchen-detachment fades.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Partnership-meal eclipse. Long restaurant-rituals end.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Partnership-meal eclipse begins.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Long shared-meal pattern dissolves.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Partnership-meal eclipse closes.' },
  { name: 'Ketu aspect Jupiter in 6th house', description: 'Service-eating detachment. Long supplement protocols end; strict regimens loosen.' },
  { name: 'Ketu aspect Jupiter in 6th house : Starts', description: 'Service-eating detachment begins.' },
  { name: 'Ketu aspect Jupiter in 6th house : Exact', description: 'The chronic regimen ends.' },
  { name: 'Ketu aspect Jupiter in 6th house : Ends', description: 'Service-eating detachment closes.' },
  { name: 'Ketu aspect Saturn in 8th house', description: 'Deep digestive transformation. Food sensitivities clarify; long-buried gut truths surface.' },
  { name: 'Ketu aspect Saturn in 8th house : Starts', description: 'Transformation-detachment begins.' },
  { name: 'Ketu aspect Saturn in 8th house : Exact', description: 'Buried food-truth surfaces.' },
  { name: 'Ketu aspect Saturn in 8th house : Ends', description: 'Transformation-detachment closes.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Axis activation in food. Foreign-cuisine direction recalibrates.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Nodal-axis food window begins.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Peak axis day. Foreign-food path shifts.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Nodal-axis food closes.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Once-in-18-years food-detachment-on-detachment. Old eating habits dissolve.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Ketu-return food window opens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'New food arc opens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu-return food closes.' },

  // — Mars aspects natal —
  { name: 'Mars aspect Sun in 3rd house', description: 'Fierce digestive drive. Best for: aggressive cleanse-execution. Worst for: rushed eating, eating-while-angry.' },
  { name: 'Mars aspect Sun in 3rd house : Starts', description: 'Mars-Sun food window opens.' },
  { name: 'Mars aspect Sun in 3rd house : Exact', description: 'Eat slowly; defer fights.' },
  { name: 'Mars aspect Sun in 3rd house : Ends', description: 'Mars-Sun food closes.' },
  { name: 'Mars aspect Moon in 2nd house', description: 'Heated speech/family-table flares. Watch the throat, mouth, dental issues.' },
  { name: 'Mars aspect Moon in 2nd house : Starts', description: 'Voice/family heat rising.' },
  { name: 'Mars aspect Moon in 2nd house : Exact', description: 'Cool drinks; less spice.' },
  { name: 'Mars aspect Moon in 2nd house : Ends', description: 'Voice/family heat fades.' },
  { name: 'Mars aspect Mercury in 3rd house', description: 'Sharp execution mind in food. Best for: hard cleanses, rapid protocol-implementation.' },
  { name: 'Mars aspect Mercury in 3rd house : Starts', description: 'Sharp-mind food window opens.' },
  { name: 'Mars aspect Mercury in 3rd house : Exact', description: 'Execute the protocol with precision.' },
  { name: 'Mars aspect Mercury in 3rd house : Ends', description: 'Sharp-mind food closes.' },
  { name: 'Mars aspect Venus in 4th house', description: 'Heated home-kitchen dynamics. Decisive cookware purchase; family-meal-rule clash.' },
  { name: 'Mars aspect Venus in 4th house : Starts', description: 'Kitchen-heat window opens.' },
  { name: 'Mars aspect Venus in 4th house : Exact', description: 'The kitchen-action moment.' },
  { name: 'Mars aspect Venus in 4th house : Ends', description: 'Kitchen-heat closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Peak structured-shared-meal action. Major restaurant-protocol commitment.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Mars-return shared-meal window opens.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Sign the structured-meal commitment.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Mars-return shared-meal closes.' },
  { name: 'Mars aspect Jupiter in 6th house', description: 'Fierce digestive combat. Win the long-pending gut-issue.' },
  { name: 'Mars aspect Jupiter in 6th house : Starts', description: 'Service-combat food window opens.' },
  { name: 'Mars aspect Jupiter in 6th house : Exact', description: 'Win the gut-rivalry.' },
  { name: 'Mars aspect Jupiter in 6th house : Ends', description: 'Service-combat food closes.' },
  { name: 'Mars aspect Saturn in 8th house', description: 'Surgical dietary action. Cleanses, eliminations, structured fasts.' },
  { name: 'Mars aspect Saturn in 8th house : Starts', description: 'Surgical-food window opens.' },
  { name: 'Mars aspect Saturn in 8th house : Exact', description: 'Take the cleanse-decision.' },
  { name: 'Mars aspect Saturn in 8th house : Ends', description: 'Surgical-food closes.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Assertive foreign-cuisine moves. Take the principled stand on dietary philosophy.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Foreign-food-combat window opens.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Push the dharmic dietary position.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Foreign-food-combat closes.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Sharp solo dietary execution; group-eating misfires. Solo intuitive cleansing.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Solo-action food window opens.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Solo cleanse lands.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Solo-action food closes.' },

  // — Mercury aspects natal —
  { name: 'Mercury aspect Sun in 3rd house', description: 'Annual return-style activation of editorial-food-mind. Best for: refining the protocol.' },
  { name: 'Mercury aspect Sun in 3rd house : Starts', description: 'Editorial-food window opens.' },
  { name: 'Mercury aspect Sun in 3rd house : Exact', description: 'Refine the food protocol.' },
  { name: 'Mercury aspect Sun in 3rd house : Ends', description: 'Editorial-food closes.' },
  { name: 'Mercury aspect Moon in 2nd house', description: 'Articulate emotional speech around food/family. Recipe-documentation; mother-cookbook.' },
  { name: 'Mercury aspect Moon in 2nd house : Starts', description: 'Voice-food articulation opens.' },
  { name: 'Mercury aspect Moon in 2nd house : Exact', description: 'Document the family recipes warmly.' },
  { name: 'Mercury aspect Moon in 2nd house : Ends', description: 'Voice-food articulation closes.' },
  { name: 'Mercury aspect Mercury in 3rd house', description: 'Annual peak for digestive-tracking. Refine the protocol.' },
  { name: 'Mercury aspect Mercury in 3rd house : Starts', description: 'Mercury return food window opens.' },
  { name: 'Mercury aspect Mercury in 3rd house : Exact', description: 'Track meals in detail.' },
  { name: 'Mercury aspect Mercury in 3rd house : Ends', description: 'Mercury return food closes.' },
  { name: 'Mercury aspect Venus in 4th house', description: 'Diplomatic kitchen-communication. Family-recipe writing; mother-cookbook.' },
  { name: 'Mercury aspect Venus in 4th house : Starts', description: 'Kitchen-communication window opens.' },
  { name: 'Mercury aspect Venus in 4th house : Exact', description: 'Document the family kitchen.' },
  { name: 'Mercury aspect Venus in 4th house : Ends', description: 'Kitchen-communication closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Precise business-meal protocol drafting.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Business-meal protocol window opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Draft the deal-dinner SOP.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Business-meal protocol closes.' },
  { name: 'Mercury aspect Jupiter in 6th house', description: 'Service-and-wisdom food communication. Meal-plans, supplement-regimens, scheduled-eating SOPs.' },
  { name: 'Mercury aspect Jupiter in 6th house : Starts', description: 'Service-food-comm window opens.' },
  { name: 'Mercury aspect Jupiter in 6th house : Exact', description: 'The meal-plan crystallizes.' },
  { name: 'Mercury aspect Jupiter in 6th house : Ends', description: 'Service-food-comm closes.' },
  { name: 'Mercury aspect Saturn in 8th house', description: 'Investigative depth-research on food. Gut-microbiome work, food-sensitivity testing.' },
  { name: 'Mercury aspect Saturn in 8th house : Starts', description: 'Depth-food-research window opens.' },
  { name: 'Mercury aspect Saturn in 8th house : Exact', description: 'The forensic dietary insight lands.' },
  { name: 'Mercury aspect Saturn in 8th house : Ends', description: 'Depth-food-research closes.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Debilitated, but Rahu amplifies. Best for: foreign-cuisine study.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Foreign-food-vision window opens.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Study the foreign tradition.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Foreign-food-vision closes.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Paradoxical detached-precision. Solo intuitive eating favored over tracked.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Detached-precision food window opens.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Drop the journal; eat by feel.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Detached-precision food closes.' },

  // — Moon aspects natal —
  { name: 'Moon aspect Sun in 3rd house', description: 'Feelings drive the day\'s eating. Best for: warm-toned communal meal.' },
  { name: 'Moon aspect Sun in 3rd house : Starts', description: 'Feelings-on-food window opens.' },
  { name: 'Moon aspect Sun in 3rd house : Exact', description: 'Warm meal lands.' },
  { name: 'Moon aspect Sun in 3rd house : Ends', description: 'Feelings-on-food closes.' },
  { name: 'Moon aspect Moon in 2nd house', description: 'Annual emotional-vocal-family-table peak. Speak warmly; family meal flows.' },
  { name: 'Moon aspect Moon in 2nd house : Starts', description: 'Family-table emotional opens.' },
  { name: 'Moon aspect Moon in 2nd house : Exact', description: 'Family meal heart-warming.' },
  { name: 'Moon aspect Moon in 2nd house : Ends', description: 'Family-table emotional closes.' },
  { name: 'Moon aspect Mercury in 3rd house', description: 'Warm-toned eating with peers/siblings. The shared meal feels easy.' },
  { name: 'Moon aspect Mercury in 3rd house : Starts', description: 'Warm-eating window opens.' },
  { name: 'Moon aspect Mercury in 3rd house : Exact', description: 'Have the meal-conversation that needs to land soft.' },
  { name: 'Moon aspect Mercury in 3rd house : Ends', description: 'Warm-eating closes.' },
  { name: 'Moon aspect Venus in 4th house', description: 'Peak home-kitchen emotional zone. Cook the slow meal at the real table.' },
  { name: 'Moon aspect Venus in 4th house : Starts', description: 'Home-kitchen emotional opens.' },
  { name: 'Moon aspect Venus in 4th house : Exact', description: 'Host the family at home.' },
  { name: 'Moon aspect Venus in 4th house : Ends', description: 'Home-kitchen emotional closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge at shared-meal table. Read partner before suggesting topics.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Shared-meal emotion window opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Soften the dinner conversation.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Shared-meal emotion closes.' },
  { name: 'Moon aspect Jupiter in 6th house', description: 'Service-care food days. Cook for someone who needs it.' },
  { name: 'Moon aspect Jupiter in 6th house : Starts', description: 'Service-care food opens.' },
  { name: 'Moon aspect Jupiter in 6th house : Exact', description: 'Healing meal for someone you love.' },
  { name: 'Moon aspect Jupiter in 6th house : Ends', description: 'Service-care food closes.' },
  { name: 'Moon aspect Saturn in 8th house', description: 'Emotional weight at the shared table. Eat lightly; defer hard food-decisions.' },
  { name: 'Moon aspect Saturn in 8th house : Starts', description: 'Shared-zone emotion food opens.' },
  { name: 'Moon aspect Saturn in 8th house : Exact', description: 'Light food; less talk.' },
  { name: 'Moon aspect Saturn in 8th house : Ends', description: 'Shared-zone emotion food closes.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional pull toward foreign cuisine, gurus\' diets.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Foreign-food emotion opens.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Try the new tradition mindfully.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Foreign-food emotion closes.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Emotional detachment in eating cluster. Solo mindful meal favored.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Solo-eating emotion opens.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'The solo meal satisfies.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Solo-eating emotion closes.' },

  // — Saturn aspects natal —
  { name: 'Saturn aspect Sun in 3rd house', description: 'Structural test of food-authority. Long-form protocol; demanding regimen.' },
  { name: 'Saturn aspect Sun in 3rd house : Starts', description: 'Food-discipline window opens.' },
  { name: 'Saturn aspect Sun in 3rd house : Exact', description: 'Hold the disciplined regimen.' },
  { name: 'Saturn aspect Sun in 3rd house : Ends', description: 'Food-discipline closes.' },
  { name: 'Saturn aspect Moon in 2nd house', description: 'Voice/family-table structural test. Speak less at meals; eat slower.' },
  { name: 'Saturn aspect Moon in 2nd house : Starts', description: 'Voice/family discipline food opens.' },
  { name: 'Saturn aspect Moon in 2nd house : Exact', description: 'Reckoning at the family table.' },
  { name: 'Saturn aspect Moon in 2nd house : Ends', description: 'Voice/family discipline food closes.' },
  { name: 'Saturn aspect Mercury in 3rd house', description: 'Long-form digestive-protocol chapter. Years-long elimination diet.' },
  { name: 'Saturn aspect Mercury in 3rd house : Starts', description: 'Structural-food window opens.' },
  { name: 'Saturn aspect Mercury in 3rd house : Exact', description: 'The protocol crystallizes for years.' },
  { name: 'Saturn aspect Mercury in 3rd house : Ends', description: 'Structural-food closes.' },
  { name: 'Saturn aspect Venus in 4th house', description: 'Home-kitchen structural test. Quality cookware; mother\'s evolving needs.' },
  { name: 'Saturn aspect Venus in 4th house : Starts', description: 'Home-kitchen-discipline opens.' },
  { name: 'Saturn aspect Venus in 4th house : Exact', description: 'Home-kitchen reckoning.' },
  { name: 'Saturn aspect Venus in 4th house : Ends', description: 'Home-kitchen-discipline closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Heavy shared-meal chapter. Marriage-eating-pattern under structural review.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Shared-meal discipline opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Reckoning of which shared meals are real.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Shared-meal discipline closes.' },
  { name: 'Saturn aspect Jupiter in 6th house', description: 'Favorable. Long gut-issues resolve through patience.' },
  { name: 'Saturn aspect Jupiter in 6th house : Starts', description: 'Service-food discipline opens.' },
  { name: 'Saturn aspect Jupiter in 6th house : Exact', description: 'Years-old gut-battle resolves.' },
  { name: 'Saturn aspect Jupiter in 6th house : Ends', description: 'Service-food discipline closes.' },
  { name: 'Saturn aspect Saturn in 8th house', description: 'Once-in-29-years half-life food-reckoning.' },
  { name: 'Saturn aspect Saturn in 8th house : Starts', description: 'Saturn return food window opens.' },
  { name: 'Saturn aspect Saturn in 8th house : Exact', description: 'Half-life food protocol.' },
  { name: 'Saturn aspect Saturn in 8th house : Ends', description: 'Saturn return food closes.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Pressure on foreign-food node.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Foreign-food discipline opens.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Dharma-food path reckoning.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Foreign-food discipline closes.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Discipline-on-detachment in cluster. Solo deep-work food protocol compounds.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Solo-food discipline opens.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Solo food-opus apex.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Solo-food discipline closes.' },

  // — Sun aspects natal —
  { name: 'Sun aspect Sun in 3rd house', description: 'Annual peak for authoritative food-protocol. Refine the regimen.' },
  { name: 'Sun aspect Sun in 3rd house : Starts', description: 'Solar-return food window opens.' },
  { name: 'Sun aspect Sun in 3rd house : Exact', description: 'Crystallize the year\'s food protocol.' },
  { name: 'Sun aspect Sun in 3rd house : Ends', description: 'Solar-return food closes.' },
  { name: 'Sun aspect Moon in 2nd house', description: 'Authoritative voice/family-table window. Lead the family-meal pattern.' },
  { name: 'Sun aspect Moon in 2nd house : Starts', description: 'Family-table authority opens.' },
  { name: 'Sun aspect Moon in 2nd house : Exact', description: 'Lead at the family table.' },
  { name: 'Sun aspect Moon in 2nd house : Ends', description: 'Family-table authority closes.' },
  { name: 'Sun aspect Mercury in 3rd house', description: 'Annual visibility on digestive-mind. Take authorship of the food-platform.' },
  { name: 'Sun aspect Mercury in 3rd house : Starts', description: 'Food-authority window opens.' },
  { name: 'Sun aspect Mercury in 3rd house : Exact', description: 'Take authorship of the food protocol.' },
  { name: 'Sun aspect Mercury in 3rd house : Ends', description: 'Food-authority closes.' },
  { name: 'Sun aspect Venus in 4th house', description: 'Annual visibility through home/family-kitchen channels. Family-business-of-food leadership.' },
  { name: 'Sun aspect Venus in 4th house : Starts', description: 'Home-kitchen authority opens.' },
  { name: 'Sun aspect Venus in 4th house : Exact', description: 'Lead the family kitchen.' },
  { name: 'Sun aspect Venus in 4th house : Ends', description: 'Home-kitchen authority closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Annual peak for partnership-led meal authority.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Shared-meal authority opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Sign the major shared-meal commitment.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Shared-meal authority closes.' },
  { name: 'Sun aspect Jupiter in 6th house', description: 'Service-food authority peak. Step into healer-via-food role.' },
  { name: 'Sun aspect Jupiter in 6th house : Starts', description: 'Service-food authority opens.' },
  { name: 'Sun aspect Jupiter in 6th house : Exact', description: 'Lead the healing-meal.' },
  { name: 'Sun aspect Jupiter in 6th house : Ends', description: 'Service-food authority closes.' },
  { name: 'Sun aspect Saturn in 8th house', description: 'Authoritative leadership through transformation-eating.' },
  { name: 'Sun aspect Saturn in 8th house : Starts', description: 'Transformation-food leadership opens.' },
  { name: 'Sun aspect Saturn in 8th house : Exact', description: 'Lead the cleanse/recovery protocol.' },
  { name: 'Sun aspect Saturn in 8th house : Ends', description: 'Transformation-food leadership closes.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Visibility through foreign-cuisine integration.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Foreign-food authority opens.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Take the international food stage.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Foreign-food authority closes.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Paradoxical authority-on-detachment. Solo dharmic eating shines.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Solo-food authority opens.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Solo dharmic eating lands.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Solo-food authority closes.' },

  // — Venus aspects natal —
  { name: 'Venus aspect Sun in 3rd house', description: 'Graceful authoritative food-communication. Charm with the well-presented dish.' },
  { name: 'Venus aspect Sun in 3rd house : Starts', description: 'Graceful-food window opens.' },
  { name: 'Venus aspect Sun in 3rd house : Exact', description: 'Charm with substance at the table.' },
  { name: 'Venus aspect Sun in 3rd house : Ends', description: 'Graceful-food closes.' },
  { name: 'Venus aspect Moon in 2nd house', description: 'Luxurious income/voice/family-table.' },
  { name: 'Venus aspect Moon in 2nd house : Starts', description: 'Family-table luxury opens.' },
  { name: 'Venus aspect Moon in 2nd house : Exact', description: 'Host the elegant family meal.' },
  { name: 'Venus aspect Moon in 2nd house : Ends', description: 'Family-table luxury closes.' },
  { name: 'Venus aspect Mercury in 3rd house', description: 'Graceful technical food-comm. Beautiful precision; cookbook-quality output.' },
  { name: 'Venus aspect Mercury in 3rd house : Starts', description: 'Graceful-food-mind window opens.' },
  { name: 'Venus aspect Mercury in 3rd house : Exact', description: 'The beautiful food-presentation lands.' },
  { name: 'Venus aspect Mercury in 3rd house : Ends', description: 'Graceful-food-mind closes.' },
  { name: 'Venus aspect Venus in 4th house', description: 'Annual peak for home-as-table. Beautify kitchen; host gatherings.' },
  { name: 'Venus aspect Venus in 4th house : Starts', description: 'Venus return food opens.' },
  { name: 'Venus aspect Venus in 4th house : Exact', description: 'Sign the cooking-class; deepen with mother in food.' },
  { name: 'Venus aspect Venus in 4th house : Ends', description: 'Venus return food closes.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Partnership-meal warmth + rigor. Sign the deal at the elegant restaurant.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Shared-meal warmth opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'The elegant business meal.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Shared-meal warmth closes.' },
  { name: 'Venus aspect Jupiter in 6th house', description: 'Diplomatic service-food. Healing meals, conflict-resolution-over-meal.' },
  { name: 'Venus aspect Jupiter in 6th house : Starts', description: 'Service-food diplomacy opens.' },
  { name: 'Venus aspect Jupiter in 6th house : Exact', description: 'The conflict resolves over the meal.' },
  { name: 'Venus aspect Jupiter in 6th house : Ends', description: 'Service-food diplomacy closes.' },
  { name: 'Venus aspect Saturn in 8th house', description: 'Diplomatic transformation-eating. Recovery-meal rituals, gentle reintroduction.' },
  { name: 'Venus aspect Saturn in 8th house : Starts', description: 'Transformation-food diplomacy opens.' },
  { name: 'Venus aspect Saturn in 8th house : Exact', description: 'Gentle recovery food.' },
  { name: 'Venus aspect Saturn in 8th house : Ends', description: 'Transformation-food diplomacy closes.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Graceful foreign-cuisine engagement.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Foreign-food diplomacy opens.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Travel-meal lands.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Foreign-food diplomacy closes.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Graceful detachment in eating-cluster. Solo aesthetic meal flourishes.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Solo-aesthetic meal opens.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'The contemplative beautiful meal.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Solo-aesthetic meal closes.' },

  // — Rahu aspects natal —
  { name: 'Rahu aspect Sun in 3rd house', description: 'Chaotic food-authority. Viral diet-trends, sudden food-content moments. Watch over-claiming.' },
  { name: 'Rahu aspect Sun in 3rd house : Starts', description: 'Chaotic food-authority opens.' },
  { name: 'Rahu aspect Sun in 3rd house : Exact', description: 'Viral food-moment with discipline.' },
  { name: 'Rahu aspect Sun in 3rd house : Ends', description: 'Chaotic food-authority closes.' },
  { name: 'Rahu aspect Moon in 2nd house', description: 'Chaotic family-table. Speculative diet-protocols at family level.' },
  { name: 'Rahu aspect Moon in 2nd house : Starts', description: 'Chaotic family-table opens.' },
  { name: 'Rahu aspect Moon in 2nd house : Exact', description: 'Family-meal pattern shifts.' },
  { name: 'Rahu aspect Moon in 2nd house : Ends', description: 'Chaotic family-table closes.' },
  { name: 'Rahu aspect Mercury in 3rd house', description: 'Explosive digestive-experimentation. Foreign-cuisine peer collaborations.' },
  { name: 'Rahu aspect Mercury in 3rd house : Starts', description: 'Breakthrough-food-mind opens.' },
  { name: 'Rahu aspect Mercury in 3rd house : Exact', description: 'The boundary-breaking food-protocol.' },
  { name: 'Rahu aspect Mercury in 3rd house : Ends', description: 'Breakthrough-food-mind closes.' },
  { name: 'Rahu aspect Venus in 4th house', description: 'Chaotic kitchen dynamics. Sudden equipment shifts, foreign-appliance acquisitions.' },
  { name: 'Rahu aspect Venus in 4th house : Starts', description: 'Kitchen-chaos opens.' },
  { name: 'Rahu aspect Venus in 4th house : Exact', description: 'Move with discipline through kitchen-shift.' },
  { name: 'Rahu aspect Venus in 4th house : Ends', description: 'Kitchen-chaos closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic shared-meal dynamics.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Chaotic shared-meal opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Verify before signing shared-meal commitments.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Chaotic shared-meal closes.' },
  { name: 'Rahu aspect Jupiter in 6th house', description: 'Favorable. Defeat chronic gut-rivals; expand into unconventional health-eating.' },
  { name: 'Rahu aspect Jupiter in 6th house : Starts', description: 'Unconventional health-eating opens.' },
  { name: 'Rahu aspect Jupiter in 6th house : Exact', description: 'Win the unconventional gut-battle.' },
  { name: 'Rahu aspect Jupiter in 6th house : Ends', description: 'Unconventional health-eating closes.' },
  { name: 'Rahu aspect Saturn in 8th house', description: 'Sudden transformation-food events. Surprise allergy-discoveries, abrupt protocols.' },
  { name: 'Rahu aspect Saturn in 8th house : Starts', description: 'Sudden food-transformation opens.' },
  { name: 'Rahu aspect Saturn in 8th house : Exact', description: 'The food-event lands. Vipareet wisdom.' },
  { name: 'Rahu aspect Saturn in 8th house : Ends', description: 'Sudden food-transformation closes.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Once-in-18-years foreign-cuisine peak. Cross-cultural food obsession.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return foreign-food opens.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'New foreign-food obsession arrives.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return foreign-food closes.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Axis activation in food. Foreign-tradition pulls against solo-detachment.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Nodal-axis food opens.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Clearer food-direction.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal-axis food closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
