// db/seed_advice_cancer.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Cancer ascendant native with:
//   Ascendant: Cancer
//   Natal: Sun=3rd Moon=2nd Mercury=3rd Venus=4th(own) Mars=7th(exalted)
//          Jupiter=6th(own) Saturn=8th(own) Rahu=9th Ketu=3rd

const db = require('./advice');

const ASCENDANT = 'Cancer';

const events = [
  // RULERS (12)
  { name: 'Moon ruler of the 1st House in the 2nd House', description: 'Your nervous system is regulated by warm food and warm words. When in doubt today, call mother or eat lunch with a friend rather than push through alone.' },
  { name: 'Sun ruler of the 2nd House in the 3rd House', description: 'Today the income or family-finance answer is hidden in writing carefully. Don\'t pitch verbally; draft the one-pager. Effort and precise sequence is your wage today.' },
  { name: 'Mercury ruler of the 3rd House in the 3rd House', description: 'Trust your analytical mind on the small decisions today. Send the email; ship the document; close the loop with the peer. Procrastination on small communications costs more than usual.' },
  { name: 'Venus ruler of the 4th House in the 4th House', description: 'Home is medicine today. Tidy the workspace; cook the slow meal; call mother. The day\'s problems often dissolve in a clean kitchen.' },
  { name: 'Mars ruler of the 5th House in the 7th House', description: 'Today your creative output is best made with the partner in mind. Pitch with rigor; think structurally about the date-night or the joint project.' },
  { name: 'Jupiter ruler of the 6th House in the 6th House', description: 'Serve the harder task with principle today. The boring admin, the difficult client, the long-deferred health appointment — all yield outsized rewards when you show up generously.' },
  { name: 'Saturn ruler of the 7th House in the 8th House', description: 'The relationship is being structurally tested under the surface today. Don\'t force; observe. Joint-finance, in-law, and deep-trust matters surface slowly. Be patient.' },
  { name: 'Saturn ruler of the 8th House in the 8th House', description: 'Hidden things are working in your favor today. The forensic insight, the quiet research, the long-deferred audit — all produce more than visible action.' },
  { name: 'Jupiter ruler of the 9th House in the 6th House', description: 'Meaning today comes through service. Listen to your father-figure mentor; show up for the hard problem with principle; the universe blesses the unglamorous fix.' },
  { name: 'Mars ruler of the 10th House in the 7th House', description: 'The career move and the relationship move are linked today. Sign contracts with rigor. The partner in the room shapes today\'s outcome.' },
  { name: 'Venus ruler of the 11th House in the 4th House', description: 'Gains today arrive through home, family, and female-mentor channels. Reach out to the senior woman in your network; the family table opens doors.' },
  { name: 'Mercury ruler of the 12th House in the 3rd House', description: 'Write the confidential note, the foreign correspondence, the quiet message today. What is spoken carelessly costs you; what is written privately compounds.' },

  // DISPOSITORS (5)
  { name: 'Mercury in 3rd (Dispositor)', description: 'The precise written word is your power today. Don\'t weaponize the analysis; deploy it. Use precision to close, not to wound.' },
  { name: 'Sun in 3rd (Dispositor)', description: 'Lead through methodical effort today, not through ego. The mentor or boss respects what you ship, not what you say.' },
  { name: 'Venus in 4th (Dispositor)', description: 'Harmony is your asset today. Mediate the dispute, beautify the workspace, deepen with mother. The diplomat in you serves today.' },
  { name: 'Saturn in 8th (Dispositor)', description: 'The slow structural work is protected today. The forensic deep-dive, the audit, the regulatory work all favored. Patience compounds.' },
  { name: 'Jupiter in 6th (Dispositor)', description: 'Serve the hard problem with high principle today. The wise helper in you is awake; let it work.' },

  // TRANSITS (108)
  { name: 'Sun Transits the 1st House', description: 'An authoritative window for self, body, public face. Today: lead, claim authorship, stand visible.' },
  { name: 'Sun Transits the 2nd House', description: 'An authoritative window for money, voice, family-finance. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 3rd House', description: 'An authoritative window for effort, peers, courage, writing. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 4th House', description: 'An authoritative window for home, mother, real-estate, comfort. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 5th House', description: 'An authoritative window for creativity, romance, children, calculated risk. Today: lead, claim authorship, stand visible.' },
  { name: 'Sun Transits the 6th House', description: 'An authoritative window for service, daily work, conflicts, health. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 7th House', description: 'An authoritative window for partnerships, contracts, the other person. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 8th House', description: 'An authoritative window for transformation, in-laws, joint resources. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 9th House', description: 'An authoritative window for higher learning, foreign matters, mentors. Today: lead, claim authorship, stand visible. Themes already strong in your life around this area get amplified now.' },
  { name: 'Sun Transits the 10th House', description: 'An authoritative window for reputation, career, public face. Today: lead, claim authorship, stand visible.' },
  { name: 'Sun Transits the 11th House', description: 'An authoritative window for gains, network, fulfilled desires. Today: lead, claim authorship, stand visible.' },
  { name: 'Sun Transits the 12th House', description: 'An authoritative window for private work, foreign matters, rest. Today: lead, claim authorship, stand visible.' },
  { name: 'Moon Transits the 1st House', description: 'An emotional window for self, body, public face. Today: tend feelings, read the room, nurture.' },
  { name: 'Moon Transits the 2nd House', description: 'An emotional window for money, voice, family-finance. Today: tend feelings, read the room, nurture.' },
  { name: 'Moon Transits the 3rd House', description: 'An emotional window for effort, peers, courage, writing. Today: tend feelings, read the room, nurture. Themes already strong in your life around this area get amplified now.' },
  { name: 'Moon Transits the 4th House', description: 'An emotional window for home, mother, real-estate, comfort. Today: tend feelings, read the room, nurture. Themes already strong in your life around this area get amplified now.' },
  { name: 'Moon Transits the 5th House', description: 'An emotional window for creativity, romance, children, calculated risk. Today: tend feelings, read the room, nurture.' },
  { name: 'Moon Transits the 6th House', description: 'An emotional window for service, daily work, conflicts, health. Today: tend feelings, read the room, nurture. Themes already strong in your life around this area get amplified now.' },
  { name: 'Moon Transits the 7th House', description: 'An emotional window for partnerships, contracts, the other person. Today: tend feelings, read the room, nurture. Themes already strong in your life around this area get amplified now.' },
  { name: 'Moon Transits the 8th House', description: 'An emotional window for transformation, in-laws, joint resources. Today: tend feelings, read the room, nurture. Themes already strong in your life around this area get amplified now.' },
  { name: 'Moon Transits the 9th House', description: 'An emotional window for higher learning, foreign matters, mentors. Today: tend feelings, read the room, nurture. Themes already strong in your life around this area get amplified now.' },
  { name: 'Moon Transits the 10th House', description: 'An emotional window for reputation, career, public face. Today: tend feelings, read the room, nurture.' },
  { name: 'Moon Transits the 11th House', description: 'An emotional window for gains, network, fulfilled desires. Today: tend feelings, read the room, nurture.' },
  { name: 'Moon Transits the 12th House', description: 'An emotional window for private work, foreign matters, rest. Today: tend feelings, read the room, nurture.' },
  { name: 'Mercury Transits the 1st House', description: 'A communicative window for self, body, public face. Today: write, articulate, exchange, plan.' },
  { name: 'Mercury Transits the 2nd House', description: 'A communicative window for money, voice, family-finance. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 3rd House', description: 'A communicative window for effort, peers, courage, writing. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 4th House', description: 'A communicative window for home, mother, real-estate, comfort. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 5th House', description: 'A communicative window for creativity, romance, children, calculated risk. Today: write, articulate, exchange, plan.' },
  { name: 'Mercury Transits the 6th House', description: 'A communicative window for service, daily work, conflicts, health. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 7th House', description: 'A communicative window for partnerships, contracts, the other person. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 8th House', description: 'A communicative window for transformation, in-laws, joint resources. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 9th House', description: 'A communicative window for higher learning, foreign matters, mentors. Today: write, articulate, exchange, plan. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mercury Transits the 10th House', description: 'A communicative window for reputation, career, public face. Today: write, articulate, exchange, plan.' },
  { name: 'Mercury Transits the 11th House', description: 'A communicative window for gains, network, fulfilled desires. Today: write, articulate, exchange, plan.' },
  { name: 'Mercury Transits the 12th House', description: 'A communicative window for private work, foreign matters, rest. Today: write, articulate, exchange, plan.' },
  { name: 'Venus Transits the 1st House', description: 'A harmonious window for self, body, public face. Today: beautify, mediate, attract, soften.' },
  { name: 'Venus Transits the 2nd House', description: 'A harmonious window for money, voice, family-finance. Today: beautify, mediate, attract, soften. Themes already strong in your life around this area get amplified now.' },
  { name: 'Venus Transits the 3rd House', description: 'A harmonious window for effort, peers, courage, writing. Today: beautify, mediate, attract, soften. Themes already strong in your life around this area get amplified now.' },
  { name: 'Venus Transits the 4th House', description: 'A harmonious window for home, mother, real-estate, comfort. Today: beautify, mediate, attract, soften.' },
  { name: 'Venus Transits the 5th House', description: 'A harmonious window for creativity, romance, children, calculated risk. Today: beautify, mediate, attract, soften.' },
  { name: 'Venus Transits the 6th House', description: 'A harmonious window for service, daily work, conflicts, health. Today: beautify, mediate, attract, soften. Themes already strong in your life around this area get amplified now.' },
  { name: 'Venus Transits the 7th House', description: 'A harmonious window for partnerships, contracts, the other person. Today: beautify, mediate, attract, soften. Themes already strong in your life around this area get amplified now.' },
  { name: 'Venus Transits the 8th House', description: 'A harmonious window for transformation, in-laws, joint resources. Today: beautify, mediate, attract, soften. Themes already strong in your life around this area get amplified now.' },
  { name: 'Venus Transits the 9th House', description: 'A harmonious window for higher learning, foreign matters, mentors. Today: beautify, mediate, attract, soften. Themes already strong in your life around this area get amplified now.' },
  { name: 'Venus Transits the 10th House', description: 'A harmonious window for reputation, career, public face. Today: beautify, mediate, attract, soften.' },
  { name: 'Venus Transits the 11th House', description: 'A harmonious window for gains, network, fulfilled desires. Today: beautify, mediate, attract, soften.' },
  { name: 'Venus Transits the 12th House', description: 'A harmonious window for private work, foreign matters, rest. Today: beautify, mediate, attract, soften.' },
  { name: 'Mars Transits the 1st House', description: 'A forceful window for self, body, public face. Today: push hard, defend, ship, contest.' },
  { name: 'Mars Transits the 2nd House', description: 'A forceful window for money, voice, family-finance. Today: push hard, defend, ship, contest. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mars Transits the 3rd House', description: 'A forceful window for effort, peers, courage, writing. Today: push hard, defend, ship, contest. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mars Transits the 4th House', description: 'A forceful window for home, mother, real-estate, comfort. Today: push hard, defend, ship, contest. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mars Transits the 5th House', description: 'A forceful window for creativity, romance, children, calculated risk. Today: push hard, defend, ship, contest.' },
  { name: 'Mars Transits the 6th House', description: 'A forceful window for service, daily work, conflicts, health. Today: push hard, defend, ship, contest. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mars Transits the 7th House', description: 'A forceful window for partnerships, contracts, the other person. Today: push hard, defend, ship, contest.' },
  { name: 'Mars Transits the 8th House', description: 'A forceful window for transformation, in-laws, joint resources. Today: push hard, defend, ship, contest. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mars Transits the 9th House', description: 'A forceful window for higher learning, foreign matters, mentors. Today: push hard, defend, ship, contest. Themes already strong in your life around this area get amplified now.' },
  { name: 'Mars Transits the 10th House', description: 'A forceful window for reputation, career, public face. Today: push hard, defend, ship, contest.' },
  { name: 'Mars Transits the 11th House', description: 'A forceful window for gains, network, fulfilled desires. Today: push hard, defend, ship, contest.' },
  { name: 'Mars Transits the 12th House', description: 'A forceful window for private work, foreign matters, rest. Today: push hard, defend, ship, contest.' },
  { name: 'Jupiter Transits the 1st House', description: 'An expansive window for self, body, public face. Today: grow, teach, mentor, take the long view.' },
  { name: 'Jupiter Transits the 2nd House', description: 'An expansive window for money, voice, family-finance. Today: grow, teach, mentor, take the long view. Themes already strong in your life around this area get amplified now.' },
  { name: 'Jupiter Transits the 3rd House', description: 'An expansive window for effort, peers, courage, writing. Today: grow, teach, mentor, take the long view. Themes already strong in your life around this area get amplified now.' },
  { name: 'Jupiter Transits the 4th House', description: 'An expansive window for home, mother, real-estate, comfort. Today: grow, teach, mentor, take the long view. Themes already strong in your life around this area get amplified now.' },
  { name: 'Jupiter Transits the 5th House', description: 'An expansive window for creativity, romance, children, calculated risk. Today: grow, teach, mentor, take the long view.' },
  { name: 'Jupiter Transits the 6th House', description: 'An expansive window for service, daily work, conflicts, health. Today: grow, teach, mentor, take the long view.' },
  { name: 'Jupiter Transits the 7th House', description: 'An expansive window for partnerships, contracts, the other person. Today: grow, teach, mentor, take the long view. Themes already strong in your life around this area get amplified now.' },
  { name: 'Jupiter Transits the 8th House', description: 'An expansive window for transformation, in-laws, joint resources. Today: grow, teach, mentor, take the long view. Themes already strong in your life around this area get amplified now.' },
  { name: 'Jupiter Transits the 9th House', description: 'An expansive window for higher learning, foreign matters, mentors. Today: grow, teach, mentor, take the long view. Themes already strong in your life around this area get amplified now.' },
  { name: 'Jupiter Transits the 10th House', description: 'An expansive window for reputation, career, public face. Today: grow, teach, mentor, take the long view.' },
  { name: 'Jupiter Transits the 11th House', description: 'An expansive window for gains, network, fulfilled desires. Today: grow, teach, mentor, take the long view.' },
  { name: 'Jupiter Transits the 12th House', description: 'An expansive window for private work, foreign matters, rest. Today: grow, teach, mentor, take the long view.' },
  { name: 'Saturn Transits the 1st House', description: 'A disciplined window for self, body, public face. Today: commit long-term, structure, slow down.' },
  { name: 'Saturn Transits the 2nd House', description: 'A disciplined window for money, voice, family-finance. Today: commit long-term, structure, slow down. Themes already strong in your life around this area get amplified now.' },
  { name: 'Saturn Transits the 3rd House', description: 'A disciplined window for effort, peers, courage, writing. Today: commit long-term, structure, slow down. Themes already strong in your life around this area get amplified now.' },
  { name: 'Saturn Transits the 4th House', description: 'A disciplined window for home, mother, real-estate, comfort. Today: commit long-term, structure, slow down. Themes already strong in your life around this area get amplified now.' },
  { name: 'Saturn Transits the 5th House', description: 'A disciplined window for creativity, romance, children, calculated risk. Today: commit long-term, structure, slow down.' },
  { name: 'Saturn Transits the 6th House', description: 'A disciplined window for service, daily work, conflicts, health. Today: commit long-term, structure, slow down. Themes already strong in your life around this area get amplified now.' },
  { name: 'Saturn Transits the 7th House', description: 'A disciplined window for partnerships, contracts, the other person. Today: commit long-term, structure, slow down. Themes already strong in your life around this area get amplified now.' },
  { name: 'Saturn Transits the 8th House', description: 'A disciplined window for transformation, in-laws, joint resources. Today: commit long-term, structure, slow down.' },
  { name: 'Saturn Transits the 9th House', description: 'A disciplined window for higher learning, foreign matters, mentors. Today: commit long-term, structure, slow down. Themes already strong in your life around this area get amplified now.' },
  { name: 'Saturn Transits the 10th House', description: 'A disciplined window for reputation, career, public face. Today: commit long-term, structure, slow down.' },
  { name: 'Saturn Transits the 11th House', description: 'A disciplined window for gains, network, fulfilled desires. Today: commit long-term, structure, slow down.' },
  { name: 'Saturn Transits the 12th House', description: 'A disciplined window for private work, foreign matters, rest. Today: commit long-term, structure, slow down.' },
  { name: 'Rahu Transits the 1st House', description: 'An unconventional window for self, body, public face. Today: experiment, chase the new, take the surprise call.' },
  { name: 'Rahu Transits the 2nd House', description: 'An unconventional window for money, voice, family-finance. Today: experiment, chase the new, take the surprise call. Themes already strong in your life around this area get amplified now.' },
  { name: 'Rahu Transits the 3rd House', description: 'An unconventional window for effort, peers, courage, writing. Today: experiment, chase the new, take the surprise call. Themes already strong in your life around this area get amplified now.' },
  { name: 'Rahu Transits the 4th House', description: 'An unconventional window for home, mother, real-estate, comfort. Today: experiment, chase the new, take the surprise call. Themes already strong in your life around this area get amplified now.' },
  { name: 'Rahu Transits the 5th House', description: 'An unconventional window for creativity, romance, children, calculated risk. Today: experiment, chase the new, take the surprise call.' },
  { name: 'Rahu Transits the 6th House', description: 'An unconventional window for service, daily work, conflicts, health. Today: experiment, chase the new, take the surprise call. Themes already strong in your life around this area get amplified now.' },
  { name: 'Rahu Transits the 7th House', description: 'An unconventional window for partnerships, contracts, the other person. Today: experiment, chase the new, take the surprise call. Themes already strong in your life around this area get amplified now.' },
  { name: 'Rahu Transits the 8th House', description: 'An unconventional window for transformation, in-laws, joint resources. Today: experiment, chase the new, take the surprise call. Themes already strong in your life around this area get amplified now.' },
  { name: 'Rahu Transits the 9th House', description: 'An unconventional window for higher learning, foreign matters, mentors. Today: experiment, chase the new, take the surprise call.' },
  { name: 'Rahu Transits the 10th House', description: 'An unconventional window for reputation, career, public face. Today: experiment, chase the new, take the surprise call.' },
  { name: 'Rahu Transits the 11th House', description: 'An unconventional window for gains, network, fulfilled desires. Today: experiment, chase the new, take the surprise call.' },
  { name: 'Rahu Transits the 12th House', description: 'An unconventional window for private work, foreign matters, rest. Today: experiment, chase the new, take the surprise call.' },
  { name: 'Ketu Transits the 1st House', description: 'A detaching window for self, body, public face. Today: release, simplify, pull back, observe.' },
  { name: 'Ketu Transits the 2nd House', description: 'A detaching window for money, voice, family-finance. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 3rd House', description: 'A detaching window for effort, peers, courage, writing. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 4th House', description: 'A detaching window for home, mother, real-estate, comfort. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 5th House', description: 'A detaching window for creativity, romance, children, calculated risk. Today: release, simplify, pull back, observe.' },
  { name: 'Ketu Transits the 6th House', description: 'A detaching window for service, daily work, conflicts, health. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 7th House', description: 'A detaching window for partnerships, contracts, the other person. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 8th House', description: 'A detaching window for transformation, in-laws, joint resources. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 9th House', description: 'A detaching window for higher learning, foreign matters, mentors. Today: release, simplify, pull back, observe. Themes already strong in your life around this area get amplified now.' },
  { name: 'Ketu Transits the 10th House', description: 'A detaching window for reputation, career, public face. Today: release, simplify, pull back, observe.' },
  { name: 'Ketu Transits the 11th House', description: 'A detaching window for gains, network, fulfilled desires. Today: release, simplify, pull back, observe.' },
  { name: 'Ketu Transits the 12th House', description: 'A detaching window for private work, foreign matters, rest. Today: release, simplify, pull back, observe.' },

  // ANGLE ASPECTS (72)
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'An authoritative window touching self, body, public face.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'An authoritative window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible on self, body, public face.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'The authoritative window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'An authoritative window touching reputation, status, public moves.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'An authoritative window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible on reputation, status, public moves.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'The authoritative window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'An emotional window touching self, body, public face.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'An emotional window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture on self, body, public face.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'The emotional window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'An emotional window touching reputation, status, public moves.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'An emotional window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture on reputation, status, public moves.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'The emotional window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'A communicative window touching self, body, public face.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'A communicative window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan on self, body, public face.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'The communicative window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'A communicative window touching reputation, status, public moves.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'A communicative window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan on reputation, status, public moves.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'The communicative window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'A harmonious window touching self, body, public face.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'A harmonious window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften on self, body, public face.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'The harmonious window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'A harmonious window touching reputation, status, public moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'A harmonious window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften on reputation, status, public moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'The harmonious window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'A forceful window touching self, body, public face.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'A forceful window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest on self, body, public face.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'The forceful window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'A forceful window touching reputation, status, public moves.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'A forceful window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest on reputation, status, public moves.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'The forceful window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'An expansive window touching self, body, public face.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'An expansive window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view on self, body, public face.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'The expansive window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'An expansive window touching reputation, status, public moves.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'An expansive window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view on reputation, status, public moves.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'The expansive window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'A disciplined window touching self, body, public face.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'A disciplined window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down on self, body, public face.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'The disciplined window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'A disciplined window touching reputation, status, public moves.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'A disciplined window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down on reputation, status, public moves.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'The disciplined window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'An unconventional window touching self, body, public face.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'An unconventional window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call on self, body, public face.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'The unconventional window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'An unconventional window touching reputation, status, public moves.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'An unconventional window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call on reputation, status, public moves.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'The unconventional window on reputation, status, public moves is closing. Lock in what was started.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'A detaching window touching self, body, public face.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'A detaching window opens on self, body, public face. Prepare relevant moves.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe on self, body, public face.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'The detaching window on self, body, public face is closing. Lock in what was started.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'A detaching window touching reputation, status, public moves.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'A detaching window opens on reputation, status, public moves. Prepare relevant moves.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe on reputation, status, public moves.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'The detaching window on reputation, status, public moves is closing. Lock in what was started.' },

  // OUTER SPECIALS (8)
  { name: 'Pluto conjunct Saturn', description: 'A multi-year structural reckoning. Old hierarchies collapse; you hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'A multi-year structural reckoning is beginning. Position for the long work.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Today is the peak. A multi-year structural reckoning. Old hierarchies collapse; you hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'A multi-year structural reckoning is completing. Integrate what changed.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruptions today. Move with discipline through unexpected shifts.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden disruptions today is beginning. Position for the long work.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Today is the peak. Sudden disruptions today. Move with discipline through unexpected shifts.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Sudden disruptions today is completing. Integrate what changed.' },

  // ASPECTS (324)
  // — Jupiter aspects natal —
  { name: 'Jupiter aspect Sun in 3rd house', description: 'An expansive window touching effort, peers, courage, writing.' },
  { name: 'Jupiter aspect Sun in 3rd house : Starts', description: 'An expansive window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the effort, peers, courage, writing area.' },
  { name: 'Jupiter aspect Sun in 3rd house : Ends', description: 'An expansive window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Moon in 2nd house', description: 'An expansive window touching money, voice, family-finance.' },
  { name: 'Jupiter aspect Moon in 2nd house : Starts', description: 'An expansive window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the money, voice, family-finance area.' },
  { name: 'Jupiter aspect Moon in 2nd house : Ends', description: 'An expansive window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Mercury in 3rd house', description: 'An expansive window touching effort, peers, courage, writing.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Starts', description: 'An expansive window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the effort, peers, courage, writing area.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Ends', description: 'An expansive window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Venus in 4th house', description: 'An expansive window touching home, mother, real-estate, comfort.' },
  { name: 'Jupiter aspect Venus in 4th house : Starts', description: 'An expansive window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Venus in 4th house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the home, mother, real-estate, comfort area.' },
  { name: 'Jupiter aspect Venus in 4th house : Ends', description: 'An expansive window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'An expansive window touching partnerships, contracts, the other person.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'An expansive window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the partnerships, contracts, the other person area.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'An expansive window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Jupiter in 6th house', description: 'An annual peak in service, daily work, conflicts, health.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Starts', description: 'An annual peak in service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Exact', description: 'Today is the peak day for annual reset of service, daily work, conflicts, health. Grow, teach, mentor, take the long view.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Ends', description: 'An annual peak in service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Saturn in 8th house', description: 'An expansive window touching transformation, in-laws, joint resources.' },
  { name: 'Jupiter aspect Saturn in 8th house : Starts', description: 'An expansive window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the transformation, in-laws, joint resources area.' },
  { name: 'Jupiter aspect Saturn in 8th house : Ends', description: 'An expansive window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'An expansive window touching higher learning, foreign matters, mentors.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'An expansive window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the higher learning, foreign matters, mentors area.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'An expansive window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'An expansive window touching effort, peers, courage, writing.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'An expansive window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Grow, teach, mentor, take the long view in the effort, peers, courage, writing area.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'An expansive window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Ketu aspects natal —
  { name: 'Ketu aspect Sun in 3rd house', description: 'A detaching window touching effort, peers, courage, writing.' },
  { name: 'Ketu aspect Sun in 3rd house : Starts', description: 'A detaching window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the effort, peers, courage, writing area.' },
  { name: 'Ketu aspect Sun in 3rd house : Ends', description: 'A detaching window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Ketu aspect Moon in 2nd house', description: 'A detaching window touching money, voice, family-finance.' },
  { name: 'Ketu aspect Moon in 2nd house : Starts', description: 'A detaching window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the money, voice, family-finance area.' },
  { name: 'Ketu aspect Moon in 2nd house : Ends', description: 'A detaching window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Ketu aspect Mercury in 3rd house', description: 'A detaching window touching effort, peers, courage, writing.' },
  { name: 'Ketu aspect Mercury in 3rd house : Starts', description: 'A detaching window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the effort, peers, courage, writing area.' },
  { name: 'Ketu aspect Mercury in 3rd house : Ends', description: 'A detaching window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Ketu aspect Venus in 4th house', description: 'A detaching window touching home, mother, real-estate, comfort.' },
  { name: 'Ketu aspect Venus in 4th house : Starts', description: 'A detaching window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Venus in 4th house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the home, mother, real-estate, comfort area.' },
  { name: 'Ketu aspect Venus in 4th house : Ends', description: 'A detaching window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'A detaching window touching partnerships, contracts, the other person.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'A detaching window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the partnerships, contracts, the other person area.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'A detaching window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Ketu aspect Jupiter in 6th house', description: 'A detaching window touching service, daily work, conflicts, health.' },
  { name: 'Ketu aspect Jupiter in 6th house : Starts', description: 'A detaching window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the service, daily work, conflicts, health area.' },
  { name: 'Ketu aspect Jupiter in 6th house : Ends', description: 'A detaching window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Ketu aspect Saturn in 8th house', description: 'A detaching window touching transformation, in-laws, joint resources.' },
  { name: 'Ketu aspect Saturn in 8th house : Starts', description: 'A detaching window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the transformation, in-laws, joint resources area.' },
  { name: 'Ketu aspect Saturn in 8th house : Ends', description: 'A detaching window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'A detaching window touching higher learning, foreign matters, mentors.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'A detaching window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Release, simplify, pull back, observe in the higher learning, foreign matters, mentors area.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'A detaching window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'An annual peak in effort, peers, courage, writing.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'An annual peak in effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Today is the peak day for annual reset of effort, peers, courage, writing. Release, simplify, pull back, observe.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'An annual peak in effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Mars aspects natal —
  { name: 'Mars aspect Sun in 3rd house', description: 'A forceful window touching effort, peers, courage, writing.' },
  { name: 'Mars aspect Sun in 3rd house : Starts', description: 'A forceful window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the effort, peers, courage, writing area.' },
  { name: 'Mars aspect Sun in 3rd house : Ends', description: 'A forceful window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Mars aspect Moon in 2nd house', description: 'A forceful window touching money, voice, family-finance.' },
  { name: 'Mars aspect Moon in 2nd house : Starts', description: 'A forceful window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the money, voice, family-finance area.' },
  { name: 'Mars aspect Moon in 2nd house : Ends', description: 'A forceful window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Mars aspect Mercury in 3rd house', description: 'A forceful window touching effort, peers, courage, writing.' },
  { name: 'Mars aspect Mercury in 3rd house : Starts', description: 'A forceful window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the effort, peers, courage, writing area.' },
  { name: 'Mars aspect Mercury in 3rd house : Ends', description: 'A forceful window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Mars aspect Venus in 4th house', description: 'A forceful window touching home, mother, real-estate, comfort.' },
  { name: 'Mars aspect Venus in 4th house : Starts', description: 'A forceful window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Venus in 4th house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the home, mother, real-estate, comfort area.' },
  { name: 'Mars aspect Venus in 4th house : Ends', description: 'A forceful window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Mars aspect Mars in 7th house', description: 'An annual peak in partnerships, contracts, the other person.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'An annual peak in partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Today is the peak day for annual reset of partnerships, contracts, the other person. Push hard, defend, ship, contest.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'An annual peak in partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Mars aspect Jupiter in 6th house', description: 'A forceful window touching service, daily work, conflicts, health.' },
  { name: 'Mars aspect Jupiter in 6th house : Starts', description: 'A forceful window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the service, daily work, conflicts, health area.' },
  { name: 'Mars aspect Jupiter in 6th house : Ends', description: 'A forceful window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Mars aspect Saturn in 8th house', description: 'A forceful window touching transformation, in-laws, joint resources.' },
  { name: 'Mars aspect Saturn in 8th house : Starts', description: 'A forceful window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the transformation, in-laws, joint resources area.' },
  { name: 'Mars aspect Saturn in 8th house : Ends', description: 'A forceful window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'A forceful window touching higher learning, foreign matters, mentors.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'A forceful window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the higher learning, foreign matters, mentors area.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'A forceful window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'A forceful window touching effort, peers, courage, writing.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'A forceful window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Push hard, defend, ship, contest in the effort, peers, courage, writing area.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'A forceful window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Mercury aspects natal —
  { name: 'Mercury aspect Sun in 3rd house', description: 'A communicative window touching effort, peers, courage, writing.' },
  { name: 'Mercury aspect Sun in 3rd house : Starts', description: 'A communicative window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the effort, peers, courage, writing area.' },
  { name: 'Mercury aspect Sun in 3rd house : Ends', description: 'A communicative window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Mercury aspect Moon in 2nd house', description: 'A communicative window touching money, voice, family-finance.' },
  { name: 'Mercury aspect Moon in 2nd house : Starts', description: 'A communicative window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the money, voice, family-finance area.' },
  { name: 'Mercury aspect Moon in 2nd house : Ends', description: 'A communicative window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Mercury aspect Mercury in 3rd house', description: 'An annual peak in effort, peers, courage, writing.' },
  { name: 'Mercury aspect Mercury in 3rd house : Starts', description: 'An annual peak in effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Mercury in 3rd house : Exact', description: 'Today is the peak day for annual reset of effort, peers, courage, writing. Write, articulate, exchange, plan.' },
  { name: 'Mercury aspect Mercury in 3rd house : Ends', description: 'An annual peak in effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Mercury aspect Venus in 4th house', description: 'A communicative window touching home, mother, real-estate, comfort.' },
  { name: 'Mercury aspect Venus in 4th house : Starts', description: 'A communicative window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Venus in 4th house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the home, mother, real-estate, comfort area.' },
  { name: 'Mercury aspect Venus in 4th house : Ends', description: 'A communicative window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'A communicative window touching partnerships, contracts, the other person.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'A communicative window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the partnerships, contracts, the other person area.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'A communicative window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Mercury aspect Jupiter in 6th house', description: 'A communicative window touching service, daily work, conflicts, health.' },
  { name: 'Mercury aspect Jupiter in 6th house : Starts', description: 'A communicative window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the service, daily work, conflicts, health area.' },
  { name: 'Mercury aspect Jupiter in 6th house : Ends', description: 'A communicative window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Mercury aspect Saturn in 8th house', description: 'A communicative window touching transformation, in-laws, joint resources.' },
  { name: 'Mercury aspect Saturn in 8th house : Starts', description: 'A communicative window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the transformation, in-laws, joint resources area.' },
  { name: 'Mercury aspect Saturn in 8th house : Ends', description: 'A communicative window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'A communicative window touching higher learning, foreign matters, mentors.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'A communicative window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the higher learning, foreign matters, mentors area.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'A communicative window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'A communicative window touching effort, peers, courage, writing.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'A communicative window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Write, articulate, exchange, plan in the effort, peers, courage, writing area.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'A communicative window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Moon aspects natal —
  { name: 'Moon aspect Sun in 3rd house', description: 'An emotional window touching effort, peers, courage, writing.' },
  { name: 'Moon aspect Sun in 3rd house : Starts', description: 'An emotional window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the effort, peers, courage, writing area.' },
  { name: 'Moon aspect Sun in 3rd house : Ends', description: 'An emotional window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Moon aspect Moon in 2nd house', description: 'An annual peak in money, voice, family-finance.' },
  { name: 'Moon aspect Moon in 2nd house : Starts', description: 'An annual peak in money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Moon in 2nd house : Exact', description: 'Today is the peak day for annual reset of money, voice, family-finance. Tend feelings, read the room, nurture.' },
  { name: 'Moon aspect Moon in 2nd house : Ends', description: 'An annual peak in money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Moon aspect Mercury in 3rd house', description: 'An emotional window touching effort, peers, courage, writing.' },
  { name: 'Moon aspect Mercury in 3rd house : Starts', description: 'An emotional window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the effort, peers, courage, writing area.' },
  { name: 'Moon aspect Mercury in 3rd house : Ends', description: 'An emotional window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Moon aspect Venus in 4th house', description: 'An emotional window touching home, mother, real-estate, comfort.' },
  { name: 'Moon aspect Venus in 4th house : Starts', description: 'An emotional window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Venus in 4th house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the home, mother, real-estate, comfort area.' },
  { name: 'Moon aspect Venus in 4th house : Ends', description: 'An emotional window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Moon aspect Mars in 7th house', description: 'An emotional window touching partnerships, contracts, the other person.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'An emotional window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the partnerships, contracts, the other person area.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'An emotional window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Moon aspect Jupiter in 6th house', description: 'An emotional window touching service, daily work, conflicts, health.' },
  { name: 'Moon aspect Jupiter in 6th house : Starts', description: 'An emotional window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the service, daily work, conflicts, health area.' },
  { name: 'Moon aspect Jupiter in 6th house : Ends', description: 'An emotional window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Moon aspect Saturn in 8th house', description: 'An emotional window touching transformation, in-laws, joint resources.' },
  { name: 'Moon aspect Saturn in 8th house : Starts', description: 'An emotional window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the transformation, in-laws, joint resources area.' },
  { name: 'Moon aspect Saturn in 8th house : Ends', description: 'An emotional window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'An emotional window touching higher learning, foreign matters, mentors.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'An emotional window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the higher learning, foreign matters, mentors area.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'An emotional window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'An emotional window touching effort, peers, courage, writing.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'An emotional window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Tend feelings, read the room, nurture in the effort, peers, courage, writing area.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'An emotional window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Saturn aspects natal —
  { name: 'Saturn aspect Sun in 3rd house', description: 'A disciplined window touching effort, peers, courage, writing.' },
  { name: 'Saturn aspect Sun in 3rd house : Starts', description: 'A disciplined window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the effort, peers, courage, writing area.' },
  { name: 'Saturn aspect Sun in 3rd house : Ends', description: 'A disciplined window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Saturn aspect Moon in 2nd house', description: 'A disciplined window touching money, voice, family-finance.' },
  { name: 'Saturn aspect Moon in 2nd house : Starts', description: 'A disciplined window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the money, voice, family-finance area.' },
  { name: 'Saturn aspect Moon in 2nd house : Ends', description: 'A disciplined window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Saturn aspect Mercury in 3rd house', description: 'A disciplined window touching effort, peers, courage, writing.' },
  { name: 'Saturn aspect Mercury in 3rd house : Starts', description: 'A disciplined window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the effort, peers, courage, writing area.' },
  { name: 'Saturn aspect Mercury in 3rd house : Ends', description: 'A disciplined window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Saturn aspect Venus in 4th house', description: 'A disciplined window touching home, mother, real-estate, comfort.' },
  { name: 'Saturn aspect Venus in 4th house : Starts', description: 'A disciplined window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Venus in 4th house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the home, mother, real-estate, comfort area.' },
  { name: 'Saturn aspect Venus in 4th house : Ends', description: 'A disciplined window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'A disciplined window touching partnerships, contracts, the other person.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'A disciplined window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the partnerships, contracts, the other person area.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'A disciplined window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Saturn aspect Jupiter in 6th house', description: 'A disciplined window touching service, daily work, conflicts, health.' },
  { name: 'Saturn aspect Jupiter in 6th house : Starts', description: 'A disciplined window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the service, daily work, conflicts, health area.' },
  { name: 'Saturn aspect Jupiter in 6th house : Ends', description: 'A disciplined window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Saturn aspect Saturn in 8th house', description: 'An annual peak in transformation, in-laws, joint resources.' },
  { name: 'Saturn aspect Saturn in 8th house : Starts', description: 'An annual peak in transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Saturn in 8th house : Exact', description: 'Today is the peak day for annual reset of transformation, in-laws, joint resources. Commit long-term, structure, slow down.' },
  { name: 'Saturn aspect Saturn in 8th house : Ends', description: 'An annual peak in transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'A disciplined window touching higher learning, foreign matters, mentors.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'A disciplined window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the higher learning, foreign matters, mentors area.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'A disciplined window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'A disciplined window touching effort, peers, courage, writing.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'A disciplined window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Commit long-term, structure, slow down in the effort, peers, courage, writing area.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'A disciplined window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Sun aspects natal —
  { name: 'Sun aspect Sun in 3rd house', description: 'An annual peak in effort, peers, courage, writing.' },
  { name: 'Sun aspect Sun in 3rd house : Starts', description: 'An annual peak in effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Sun in 3rd house : Exact', description: 'Today is the peak day for annual reset of effort, peers, courage, writing. Lead, claim authorship, stand visible.' },
  { name: 'Sun aspect Sun in 3rd house : Ends', description: 'An annual peak in effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Sun aspect Moon in 2nd house', description: 'An authoritative window touching money, voice, family-finance.' },
  { name: 'Sun aspect Moon in 2nd house : Starts', description: 'An authoritative window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the money, voice, family-finance area.' },
  { name: 'Sun aspect Moon in 2nd house : Ends', description: 'An authoritative window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Sun aspect Mercury in 3rd house', description: 'An authoritative window touching effort, peers, courage, writing.' },
  { name: 'Sun aspect Mercury in 3rd house : Starts', description: 'An authoritative window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the effort, peers, courage, writing area.' },
  { name: 'Sun aspect Mercury in 3rd house : Ends', description: 'An authoritative window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Sun aspect Venus in 4th house', description: 'An authoritative window touching home, mother, real-estate, comfort.' },
  { name: 'Sun aspect Venus in 4th house : Starts', description: 'An authoritative window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Venus in 4th house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the home, mother, real-estate, comfort area.' },
  { name: 'Sun aspect Venus in 4th house : Ends', description: 'An authoritative window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Sun aspect Mars in 7th house', description: 'An authoritative window touching partnerships, contracts, the other person.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'An authoritative window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the partnerships, contracts, the other person area.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'An authoritative window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Sun aspect Jupiter in 6th house', description: 'An authoritative window touching service, daily work, conflicts, health.' },
  { name: 'Sun aspect Jupiter in 6th house : Starts', description: 'An authoritative window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the service, daily work, conflicts, health area.' },
  { name: 'Sun aspect Jupiter in 6th house : Ends', description: 'An authoritative window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Sun aspect Saturn in 8th house', description: 'An authoritative window touching transformation, in-laws, joint resources.' },
  { name: 'Sun aspect Saturn in 8th house : Starts', description: 'An authoritative window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the transformation, in-laws, joint resources area.' },
  { name: 'Sun aspect Saturn in 8th house : Ends', description: 'An authoritative window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'An authoritative window touching higher learning, foreign matters, mentors.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'An authoritative window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the higher learning, foreign matters, mentors area.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'An authoritative window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'An authoritative window touching effort, peers, courage, writing.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'An authoritative window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Lead, claim authorship, stand visible in the effort, peers, courage, writing area.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'An authoritative window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Venus aspects natal —
  { name: 'Venus aspect Sun in 3rd house', description: 'A harmonious window touching effort, peers, courage, writing.' },
  { name: 'Venus aspect Sun in 3rd house : Starts', description: 'A harmonious window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the effort, peers, courage, writing area.' },
  { name: 'Venus aspect Sun in 3rd house : Ends', description: 'A harmonious window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Venus aspect Moon in 2nd house', description: 'A harmonious window touching money, voice, family-finance.' },
  { name: 'Venus aspect Moon in 2nd house : Starts', description: 'A harmonious window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the money, voice, family-finance area.' },
  { name: 'Venus aspect Moon in 2nd house : Ends', description: 'A harmonious window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Venus aspect Mercury in 3rd house', description: 'A harmonious window touching effort, peers, courage, writing.' },
  { name: 'Venus aspect Mercury in 3rd house : Starts', description: 'A harmonious window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the effort, peers, courage, writing area.' },
  { name: 'Venus aspect Mercury in 3rd house : Ends', description: 'A harmonious window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Venus aspect Venus in 4th house', description: 'An annual peak in home, mother, real-estate, comfort.' },
  { name: 'Venus aspect Venus in 4th house : Starts', description: 'An annual peak in home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Venus in 4th house : Exact', description: 'Today is the peak day for annual reset of home, mother, real-estate, comfort. Beautify, mediate, attract, soften.' },
  { name: 'Venus aspect Venus in 4th house : Ends', description: 'An annual peak in home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Venus aspect Mars in 7th house', description: 'A harmonious window touching partnerships, contracts, the other person.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'A harmonious window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the partnerships, contracts, the other person area.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'A harmonious window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Venus aspect Jupiter in 6th house', description: 'A harmonious window touching service, daily work, conflicts, health.' },
  { name: 'Venus aspect Jupiter in 6th house : Starts', description: 'A harmonious window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the service, daily work, conflicts, health area.' },
  { name: 'Venus aspect Jupiter in 6th house : Ends', description: 'A harmonious window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Venus aspect Saturn in 8th house', description: 'A harmonious window touching transformation, in-laws, joint resources.' },
  { name: 'Venus aspect Saturn in 8th house : Starts', description: 'A harmonious window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the transformation, in-laws, joint resources area.' },
  { name: 'Venus aspect Saturn in 8th house : Ends', description: 'A harmonious window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'A harmonious window touching higher learning, foreign matters, mentors.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'A harmonious window touching higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the higher learning, foreign matters, mentors area.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'A harmonious window touching higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'A harmonious window touching effort, peers, courage, writing.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'A harmonious window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Beautify, mediate, attract, soften in the effort, peers, courage, writing area.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'A harmonious window touching effort, peers, courage, writing is closing. Lock in commitments.' },

  // — Rahu aspects natal —
  { name: 'Rahu aspect Sun in 3rd house', description: 'An unconventional window touching effort, peers, courage, writing.' },
  { name: 'Rahu aspect Sun in 3rd house : Starts', description: 'An unconventional window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Sun in 3rd house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the effort, peers, courage, writing area.' },
  { name: 'Rahu aspect Sun in 3rd house : Ends', description: 'An unconventional window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Rahu aspect Moon in 2nd house', description: 'An unconventional window touching money, voice, family-finance.' },
  { name: 'Rahu aspect Moon in 2nd house : Starts', description: 'An unconventional window touching money, voice, family-finance is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Moon in 2nd house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the money, voice, family-finance area.' },
  { name: 'Rahu aspect Moon in 2nd house : Ends', description: 'An unconventional window touching money, voice, family-finance is closing. Lock in commitments.' },
  { name: 'Rahu aspect Mercury in 3rd house', description: 'An unconventional window touching effort, peers, courage, writing.' },
  { name: 'Rahu aspect Mercury in 3rd house : Starts', description: 'An unconventional window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Mercury in 3rd house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the effort, peers, courage, writing area.' },
  { name: 'Rahu aspect Mercury in 3rd house : Ends', description: 'An unconventional window touching effort, peers, courage, writing is closing. Lock in commitments.' },
  { name: 'Rahu aspect Venus in 4th house', description: 'An unconventional window touching home, mother, real-estate, comfort.' },
  { name: 'Rahu aspect Venus in 4th house : Starts', description: 'An unconventional window touching home, mother, real-estate, comfort is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Venus in 4th house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the home, mother, real-estate, comfort area.' },
  { name: 'Rahu aspect Venus in 4th house : Ends', description: 'An unconventional window touching home, mother, real-estate, comfort is closing. Lock in commitments.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'An unconventional window touching partnerships, contracts, the other person.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'An unconventional window touching partnerships, contracts, the other person is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the partnerships, contracts, the other person area.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'An unconventional window touching partnerships, contracts, the other person is closing. Lock in commitments.' },
  { name: 'Rahu aspect Jupiter in 6th house', description: 'An unconventional window touching service, daily work, conflicts, health.' },
  { name: 'Rahu aspect Jupiter in 6th house : Starts', description: 'An unconventional window touching service, daily work, conflicts, health is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Jupiter in 6th house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the service, daily work, conflicts, health area.' },
  { name: 'Rahu aspect Jupiter in 6th house : Ends', description: 'An unconventional window touching service, daily work, conflicts, health is closing. Lock in commitments.' },
  { name: 'Rahu aspect Saturn in 8th house', description: 'An unconventional window touching transformation, in-laws, joint resources.' },
  { name: 'Rahu aspect Saturn in 8th house : Starts', description: 'An unconventional window touching transformation, in-laws, joint resources is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Saturn in 8th house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the transformation, in-laws, joint resources area.' },
  { name: 'Rahu aspect Saturn in 8th house : Ends', description: 'An unconventional window touching transformation, in-laws, joint resources is closing. Lock in commitments.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'An annual peak in higher learning, foreign matters, mentors.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'An annual peak in higher learning, foreign matters, mentors is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Today is the peak day for annual reset of higher learning, foreign matters, mentors. Experiment, chase the new, take the surprise call.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'An annual peak in higher learning, foreign matters, mentors is closing. Lock in commitments.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'An unconventional window touching effort, peers, courage, writing.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'An unconventional window touching effort, peers, courage, writing is approaching. Prepare relevant moves.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Today is the peak day. Experiment, chase the new, take the surprise call in the effort, peers, courage, writing area.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'An unconventional window touching effort, peers, courage, writing is closing. Lock in commitments.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
