// db/seed_advice_cancer.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Cancer ascendant native with:
//   Ascendant: Cancer
//   Natal: Sun=3rd Moon=2nd Mercury=3rd Venus=4th(own) Mars=7th(exalted)
//          Jupiter=6th(own) Saturn=8th(own) Rahu=9th Ketu=3rd

const db = require('./advice');

const ASCENDANT = 'Cancer';

const events = [
  // RULERS (12)
  { name: 'Moon ruler of the 1st House in the 2nd House', description: 'Your Lagna lord Moon in 2H Leo means today: protect the voice, watch the family-money conversation, eat at a real table. Your nervous system is regulated by warm food and warm words. When in doubt today, call mother or eat lunch with a friend rather than push through alone.' },
  { name: 'Sun ruler of the 2nd House in the 3rd House', description: 'Your 2nd lord Sun in 3H means today: the income/family-finance answer is hidden in writing carefully. Don\'t pitch verbally; draft the one-pager. Effort + precise sequence is your wage today.' },
  { name: 'Mercury ruler of the 3rd House in the 3rd House', description: 'Your 3rd lord Mercury in own-sign 3H means today: trust your analytical mind on the small decisions. Send the email; ship the document; close the loop with the peer. Procrastination on small comms costs more than usual today.' },
  { name: 'Venus ruler of the 4th House in the 4th House', description: 'Your 4th lord Venus in own-sign 4H means today: home is medicine. Tidy the workspace; cook the slow meal; call mother. The day\'s problems often dissolve in a clean kitchen.' },
  { name: 'Mars ruler of the 5th House in the 7th House', description: 'Your 5th lord Mars in 7H exalted means today: your creative output is best made with the partner-in-mind. Pitch with rigor; think structurally about the date-night or the joint project.' },
  { name: 'Jupiter ruler of the 6th House in the 6th House', description: 'Your 6th lord Jupiter in own-sign 6H means today: serve the harder task with principle. The boring admin, the difficult client, the long-deferred health appointment — all yield outsized rewards when you show up dharmically today.' },
  { name: 'Saturn ruler of the 7th House in the 8th House', description: 'Your 7th lord Saturn in own-sign 8H means today: the relationship is being structurally tested under the surface. Don\'t force; observe. Joint-finance, in-law, deep-trust matters surface slowly. Be patient.' },
  { name: 'Saturn ruler of the 8th House in the 8th House', description: 'Your 8th lord Saturn in own-sign 8H means today: hidden things are working in your favor. The forensic insight, the quiet research, the long-deferred audit — all produce more than visible action.' },
  { name: 'Jupiter ruler of the 9th House in the 6th House', description: 'Your 9th lord Jupiter in own-sign 6H means today: dharma comes through service. Listen to your father-figure mentor; show up for the hard problem with principle; the universe blesses the unglamorous fix.' },
  { name: 'Mars ruler of the 10th House in the 7th House', description: 'Your 10th lord Mars in 7H exalted means today: the career move and the relationship move are linked. Sign the contract with rigor. The partner-in-the-room shapes today\'s outcome.' },
  { name: 'Venus ruler of the 11th House in the 4th House', description: 'Your 11th lord Venus in own-sign 4H means today: gains arrive through home/family/female-mentor channels. Reach out to the senior woman in your network; the family table opens doors.' },
  { name: 'Mercury ruler of the 12th House in the 3rd House', description: 'Your 12th lord Mercury in own-sign 3H means today: write the confidential note, the foreign correspondence, the quiet message. What\'s spoken carelessly costs you; what\'s written privately compounds.' },

  // DISPOSITORS (5)
  { name: 'Mercury in 3rd (Dispositor)', description: 'Your dispositor Mercury (3H Virgo, own sign) means today: the precise written word is your power. Don\'t weaponize the analysis; deploy it. Use the Virgo precision to close, not to wound.' },
  { name: 'Sun in 3rd (Dispositor)', description: 'Your dispositor Sun (3H Virgo) means today: lead through methodical effort, not through ego. Father-figure mentor or boss respects what you ship, not what you say.' },
  { name: 'Venus in 4th (Dispositor)', description: 'Your dispositor Venus (4H Libra, own sign) means today: harmony is your asset. Mediate the dispute, beautify the workspace, deepen with mother. The diplomat-aesthete in you serves today.' },
  { name: 'Saturn in 8th (Dispositor)', description: 'Your dispositor Saturn (8H Aquarius, own sign) means today: the slow structural work is protected. The forensic deep-dive, the audit, the regulatory work all favored. Patience compounds.' },
  { name: 'Jupiter in 6th (Dispositor)', description: 'Your dispositor Jupiter (6H Sagittarius, own sign) means today: serve the hard problem with high principle. The Hamsa in you is awake; let it work.' },

  // TRANSITS (108)
  { name: 'Sun Transits the 1st House', description: 'Sun debilitated in Cancer Lagna — push through awkward visibility today. Don\'t hide just because the spotlight feels uncomfortable. Show up modestly but consistently.' },
  { name: 'Sun Transits the 2nd House', description: 'Sun in 2H on Moon — speak warmly today; address family-finance; the throat needs cool drinks and gentle care.' },
  { name: 'Sun Transits the 3rd House', description: 'Sun in 3H on cluster — best day to ship the document, write the analysis, take the courage assignment.' },
  { name: 'Sun Transits the 4th House', description: 'Sun in 4H on Venus — best day for mother-call, real-estate decision, home-as-office work.' },
  { name: 'Sun Transits the 5th House', description: 'Sun in 5H — best day to pitch the creative idea, take the calculated risk, mentor the protégé.' },
  { name: 'Sun Transits the 6th House', description: 'Sun in 6H on Jupiter — best day for the unglamorous fix; the difficult client; the boring admin that compounds.' },
  { name: 'Sun Transits the 7th House', description: 'Sun in 7H on exalted Mars — best day to sign the contract, formalize the partnership, demand the rigorous terms.' },
  { name: 'Sun Transits the 8th House', description: 'Sun in 8H on Saturn — best day for the surgical decision, the restructuring, the deep-research insight.' },
  { name: 'Sun Transits the 9th House', description: 'Sun in 9H on Rahu — best day for the international call, the certification effort, the principled stand.' },
  { name: 'Sun Transits the 10th House', description: 'Sun in 10H — best day to demand the title, lead the public initiative, refresh your career materials.' },
  { name: 'Sun Transits the 11th House', description: 'Sun in 11H — best day to accept the senior invitation, formalize the alliance, ask for the gain.' },
  { name: 'Sun Transits the 12th House', description: 'Sun in 12H — best day for behind-scenes work, the long-form draft, the quiet retreat.' },
  { name: 'Moon Transits the 1st House', description: 'Moon in own-sign Cancer Lagna — high empathy day. Lead with warmth; the room reads you generously.' },
  { name: 'Moon Transits the 2nd House', description: 'Moon return on 2H Moon — speak from the heart; family-finance feels close.' },
  { name: 'Moon Transits the 3rd House', description: 'Moon in 3H on cluster — send the warm note; have the empathic peer-conversation.' },
  { name: 'Moon Transits the 4th House', description: 'Moon in 4H on Venus — peak home day. Cook; nest; mother-call.' },
  { name: 'Moon Transits the 5th House', description: 'Moon in 5H — emotional creative depth. Channel into focused output, not impulsive moves.' },
  { name: 'Moon Transits the 6th House', description: 'Moon in 6H on Jupiter — show up for someone who needs care; service heals you.' },
  { name: 'Moon Transits the 7th House', description: 'Moon in 7H on exalted Mars — read the partner\'s mood before pushing terms.' },
  { name: 'Moon Transits the 8th House', description: 'Moon in 8H on Saturn — emotional weight in shared-zone. Defer hard decisions; sleep more.' },
  { name: 'Moon Transits the 9th House', description: 'Moon in 9H on Rahu — capture the big-vision dream; commit later.' },
  { name: 'Moon Transits the 10th House', description: 'Moon in 10H — the room reads you. Show up regulated; protect the public face.' },
  { name: 'Moon Transits the 11th House', description: 'Moon in 11H — reach out to the senior friend; accept the warm invitation.' },
  { name: 'Moon Transits the 12th House', description: 'Moon in 12H — quiet day; behind-scenes work; sleep early.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury in Cancer Lagna — write the personal-state update; refresh your CV warmly.' },
  { name: 'Mercury Transits the 2nd House', description: 'Mercury in 2H on Moon — make the warm-toned salary case; record the heart-led talk.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury return on cluster — peak ship day. Send the document; close the loop; the mind is sharp.' },
  { name: 'Mercury Transits the 4th House', description: 'Mercury in 4H on Venus — handle real-estate paperwork; family-business calls; mother-letter.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury in 5H — write the creative brief, the mentee email, the pitch deck.' },
  { name: 'Mercury Transits the 6th House', description: 'Mercury in 6H on Jupiter — write SOPs, regulatory filings, conflict-resolution emails.' },
  { name: 'Mercury Transits the 7th House', description: 'Mercury in 7H on exalted Mars — draft contract terms; send the precise legal note.' },
  { name: 'Mercury Transits the 8th House', description: 'Mercury in 8H on Saturn — depth-research day; the forensic insight lands.' },
  { name: 'Mercury Transits the 9th House', description: 'Mercury in 9H on Rahu — write visionary; defer precise contract language.' },
  { name: 'Mercury Transits the 10th House', description: 'Mercury in 10H — bold career-comm; press release; LinkedIn-style update.' },
  { name: 'Mercury Transits the 11th House', description: 'Mercury in 11H — patient outreach to senior allies; deal-driven introductions.' },
  { name: 'Mercury Transits the 12th House', description: 'Mercury in 12H own-sign — confidential writing; foreign correspondence; watch leaks.' },
  { name: 'Venus Transits the 1st House', description: 'Venus in Cancer Lagna — peak charisma day. Take the client meeting; ask for the favor.' },
  { name: 'Venus Transits the 2nd House', description: 'Venus in 2H on Moon — luxurious salary diplomacy; family-finance harmony.' },
  { name: 'Venus Transits the 3rd House', description: 'Venus in 3H on cluster — graceful peer-comm; the difficult email turns diplomatic.' },
  { name: 'Venus Transits the 4th House', description: 'Venus return on 4H Venus — beautify; host; deepen with mother. Annual home-peak.' },
  { name: 'Venus Transits the 5th House', description: 'Venus in 5H — date night; creative pleasure; advisory income flows.' },
  { name: 'Venus Transits the 6th House', description: 'Venus in 6H on Jupiter — diplomatic service; HR work; conflict-resolution lands.' },
  { name: 'Venus Transits the 7th House', description: 'Venus in 7H on exalted Mars — sign the partnership; close the long-pending client.' },
  { name: 'Venus Transits the 8th House', description: 'Venus in 8H on Saturn — diplomatic shared-finance; gentle inheritance conversation.' },
  { name: 'Venus Transits the 9th House', description: 'Venus in 9H on Rahu — graceful international engagement; cross-cultural diplomacy.' },
  { name: 'Venus Transits the 10th House', description: 'Venus in 10H — softer public face; brand campaign; design-driven launch.' },
  { name: 'Venus Transits the 11th House', description: 'Venus in 11H own-sign — peak gain/network day. Hosting; female-mentor connection.' },
  { name: 'Venus Transits the 12th House', description: 'Venus in 12H — quiet pleasure; foreign luxury; watch over-spending on travel.' },
  { name: 'Mars Transits the 1st House', description: 'Mars debilitated in Cancer — energy up but emotionally fragile. Push with discipline; avoid impulsive declarations.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars in 2H on Moon — heated speech; data over emotion in salary asks; throat care.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars in 3H on cluster — fierce execution. Ship hard; defend the document.' },
  { name: 'Mars Transits the 4th House', description: 'Mars in 4H on Venus — decisive home action; watch family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Mars in own-sign 5H — push the stalled creative project; defend authority over mentees.' },
  { name: 'Mars Transits the 6th House', description: 'Mars in 6H on Jupiter — favorable. Win the workplace dispute; settle long debts.' },
  { name: 'Mars Transits the 7th House', description: 'Mars-return on exalted Mars — peak partnership-action day. Sign deals; demand rigor; watch domineering tone.' },
  { name: 'Mars Transits the 8th House', description: 'Mars in 8H on Saturn — surgical action in restructuring zone. Lead through the chaos.' },
  { name: 'Mars Transits the 9th House', description: 'Mars in 9H on Rahu — assertive foreign moves; principled stand-taking.' },
  { name: 'Mars Transits the 10th House', description: 'Mars in own-sign 10H — bold career assertion. Demand the promotion; lead the visible battle.' },
  { name: 'Mars Transits the 11th House', description: 'Mars in 11H — aggressive bonus negotiation; equity disputes resolved through patient pressure.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in 12H — hidden frictions stir; avoid open warfare; fight from shadows or not at all.' },
  { name: 'Jupiter Transits the 1st House', description: 'Exalted Jupiter on Cancer Lagna — once-in-12-years personal expansion. Plan the long-term project.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Jupiter in 2H on Moon — vocal/income/family-finance expansion; ask for raises now.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Jupiter in 3H on cluster — flagship effort/writing year.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter in 4H on Venus — exalted home expansion; buy property; deepen mother-bond.' },
  { name: 'Jupiter Transits the 5th House', description: 'Jupiter in 5H — major creative/advisory/mentee growth year.' },
  { name: 'Jupiter Transits the 6th House', description: 'Jupiter return in own-sign 6H — service-with-wisdom peak; difficult clients become teachers.' },
  { name: 'Jupiter Transits the 7th House', description: 'Jupiter in 7H on exalted Mars — major partnership year; choose carefully (debilitated Jupiter).' },
  { name: 'Jupiter Transits the 8th House', description: 'Jupiter in 8H on Saturn — wisdom into transformation; inheritance/severance favored.' },
  { name: 'Jupiter Transits the 9th House', description: 'Jupiter in own-sign 9H on Rahu — major dharma/foreign year.' },
  { name: 'Jupiter Transits the 10th House', description: 'Jupiter in 10H — career visibility expansion; aim deliberately upward.' },
  { name: 'Jupiter Transits the 11th House', description: 'Jupiter in 11H — gains/network/long-held desires expand; ask for raises.' },
  { name: 'Jupiter Transits the 12th House', description: 'Jupiter in 12H — foreign/sabbatical/hidden-asset domain grows; retreats produce outsized resets.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn in Cancer Lagna — Sade Sati 2nd leg. Slow down; build for permanence; health discipline matters.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn in 2H on Moon — Sade Sati 3rd leg. Income/voice/family-finance discipline. Speak less, write more.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn in 3H on cluster — heavy effort/writing chapter. The years-in-the-making courage move.' },
  { name: 'Saturn Transits the 4th House', description: 'Saturn in 4H on Venus — home/family-foundation under structural test.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn in 5H — creativity/speculation demand seriousness.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn in 6H on Jupiter — favorable. Long workplace battles won through patience.' },
  { name: 'Saturn Transits the 7th House', description: 'Saturn in own-sign 7H on exalted Mars — heavy partnership chapter; what survives lasts decades.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn return in own-sign 8H — once-in-29-years deep transformation reckoning.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn in 9H on Rahu — dharma/foreign chapter under structural pressure.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn in 10H — heavy career visibility chapter; recognition delayed but permanent.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn in 11H — gains discipline; network shrinks to the real ones.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn in 12H — Sade Sati 1st leg. Structural patience required.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu in Cancer Lagna — once-in-18-years identity-shock. New persona experiment; vet derailments.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu in 2H on Moon — chaotic income/voice/family-finance; don\'t leverage on sudden wealth.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu in 3H on cluster — explosive writing/effort; viral content; watch over-claiming.' },
  { name: 'Rahu Transits the 4th House', description: 'Rahu in 4H on Venus — chaotic home/mother dynamics; foreign-property pulls.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu in 5H — speculative obsession; discipline the gambling impulse.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu in 6H on Jupiter — favorable. Defeat enemies; expand foreign service domains.' },
  { name: 'Rahu Transits the 7th House', description: 'Rahu in 7H on exalted Mars — chaotic partnerships; vet counterparties rigorously.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu in 8H on Saturn — sudden inheritance/severance/regulatory shocks. Vipareet activation.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu return on Rahu — foreign-spiritual obsession peaks; cross-border career chapter activates.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu in 10H — meteoric career shifts; sudden promotion or pivot; don\'t over-leverage.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu in 11H — unconventional gains; foreign-money streams; watch unsustainable income illusions.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu in 12H — foreign relocation; hidden-asset reshuffles; sleep-disrupting visions.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu in Cancer Lagna — identity stripping. Old career-self feels empty; don\'t leap impulsively.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu in 2H on Moon — emotional detachment from income/voice/family. Purifying.' },
  { name: 'Ketu Transits the 3rd House', description: 'Ketu return on 3H Ketu — old peer/effort patterns dissolve; solo work intensifies.' },
  { name: 'Ketu Transits the 4th House', description: 'Ketu in 4H on Venus — detachment from home/mother/real-estate; selling property favored.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu in 5H — creative output feels hollow; pursue non-monetary study.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu in 6H on Jupiter — chronic enemies disengage; long debts close; service obligations end.' },
  { name: 'Ketu Transits the 7th House', description: 'Ketu in 7H on exalted Mars — partnership eclipse; long contracts quietly end; don\'t cling.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu in 8H on Saturn — deep karmic transformation; honor what wants to end.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu in 9H on Rahu — eclipse on dharma node; mentors drift; real dharma surfaces underneath.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu in 10H — visibility flickers; promotions stall; let what wants to leave, leave.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu in 11H — network thins; transactional friends fade; the real ones remain.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu in own-position 12H — quiet foreign/isolation chapter; sleep/dreams clarify.' },

  // ANGLE ASPECTS (72)
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar visibility on Cancer persona — show up; take the spotlight despite discomfort.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Solar-self window opens. Prepare to be seen.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak solar-on-self day. Take the meeting; ask for the title.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Solar window fades. Lock in commitments.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar fire on career zenith — public recognition window.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens. Refresh public materials.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-spotlight day. Show up at your best.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-spotlight fades. Convert leads.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Moon on own-sign Lagna — peak empathic-self day.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Empathic window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak empathic-self day. Lead with warmth.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Empathic window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Lunar charge on career zenith — mood regulates visibility.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Public-emotion window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak Moon-MC day. Show up regulated.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Public-emotion window fades.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury sharpens self-articulation. Best for: interviews, personal statements.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Articulation window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak articulation day. Take the interview.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Articulation closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on career zenith — written authority on display.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-comm window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak career-comm day. Present the deck.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-comm closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Venus warms persona — peak professional charm.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Charisma window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charisma day. Take the client meeting.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charisma window fades.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Venus on career zenith — diplomatic public visibility.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Public-warmth window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak Venus-MC day. Launch the brand campaign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Public-warmth closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Mars debilitated on Cancer Lagna — push with discipline; avoid impulsive declarations.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action window opens with debilitated edge.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak Mars-self day. Bold ask; calm tone.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action window fades.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Mars on career zenith — competitive battles; watch combative tone.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak Mars-MC day. Defend authority.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action cools.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Exalted Jupiter on Cancer Lagna — once-in-12-years self-expansion.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion begins. Plan the major personal project.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak Jupiter-self day. Mentors notice.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion closes. Lock in title elevations.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Jupiter on career zenith — board-level mentor blessings.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day. Take the elevation.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Saturn on Cancer Lagna — body/identity under structural test.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self test begins.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak Saturn-self day. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Saturn on career zenith — slow public recognition.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak Saturn-MC day. Foundation laid.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-Saturn closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Rahu on Cancer Lagna — chaotic identity expansion.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Rahu-self window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak Rahu-self day. Take unconventional move with discipline.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu-self closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Rahu on career zenith — sudden promotions; unconventional offers.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Rahu-MC window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak Rahu-MC day. Verify before leveraging.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu-MC closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Ketu on Cancer Lagna — identity stripping; don\'t leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Ketu-self window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak Ketu-self day. Sit with dissonance.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Ketu-self closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Ketu on career zenith — visibility eclipse.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak career-Ketu day. Don\'t cling to dissolving role.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse closes.' },

  // OUTER SPECIALS (8)
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning on Saturn (Aquarius 8H). Old hierarchies collapse; vipareet activation.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural transformation day. Hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Transformation chapter completes.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption on Venus (Libra 4H). Unexpected home/mother shifts; surprise offers.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Venus-disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption closes. Integrate.' },

  // ASPECTS (324)
  // — Jupiter aspects natal —
  { name: 'Jupiter aspect Sun in 3rd house', description: 'Jupiter on 3H Sun — broad authority through writing; ship the document.' },
  { name: 'Jupiter aspect Sun in 3rd house : Starts', description: 'Window opens for flagship written work.' },
  { name: 'Jupiter aspect Sun in 3rd house : Exact', description: 'Peak day for authoritative communication. Publish; present.' },
  { name: 'Jupiter aspect Sun in 3rd house : Ends', description: 'Window closes. Lock in commitments.' },
  { name: 'Jupiter aspect Moon in 2nd house', description: 'Jupiter on 2H Moon — vocal/family-finance expansion. Speak; people listen.' },
  { name: 'Jupiter aspect Moon in 2nd house : Starts', description: 'Voice-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 2nd house : Exact', description: 'Peak vocal-income day. Record the talk; ask for the raise.' },
  { name: 'Jupiter aspect Moon in 2nd house : Ends', description: 'Voice-expansion closes.' },
  { name: 'Jupiter aspect Mercury in 3rd house', description: 'Jupiter on 3H Mercury (own sign) — peak technical/written wisdom.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Starts', description: 'Mind-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Exact', description: 'Peak technical-mind day. Ship the masterpiece document.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Ends', description: 'Mind-expansion closes.' },
  { name: 'Jupiter aspect Venus in 4th house', description: 'Jupiter on 4H Venus (own sign) — peak home expansion.' },
  { name: 'Jupiter aspect Venus in 4th house : Starts', description: 'Home-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 4th house : Exact', description: 'Peak home day. Sign the lease; deepen with mother.' },
  { name: 'Jupiter aspect Venus in 4th house : Ends', description: 'Home-expansion closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Jupiter on 7H exalted Mars — major partnership window.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Partnership-expansion opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak partnership day. Sign the contract.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Partnership-expansion closes.' },
  { name: 'Jupiter aspect Jupiter in 6th house', description: 'Jupiter return on 6H Jupiter — service-with-wisdom peak.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Starts', description: 'Service window opens.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Exact', description: 'Peak service day. Hard problem yields.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Ends', description: 'Service window closes.' },
  { name: 'Jupiter aspect Saturn in 8th house', description: 'Jupiter on 8H Saturn — wisdom into transformation. Inheritance/severance favored.' },
  { name: 'Jupiter aspect Saturn in 8th house : Starts', description: 'Transformation-wisdom window opens.' },
  { name: 'Jupiter aspect Saturn in 8th house : Exact', description: 'Peak transformation-blessing day.' },
  { name: 'Jupiter aspect Saturn in 8th house : Ends', description: 'Transformation-wisdom closes.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Jupiter on 9H Rahu — own-sign Jupiter on dharma node. Peak foreign/dharma window.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Foreign-dharma window opens.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Peak foreign-dharma day.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Foreign-dharma closes.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Jupiter on 3H Ketu — wisdom on detached-comm. Solo deep work flourishes.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Solo-wisdom opens.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Peak solo-wisdom day.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Solo-wisdom closes.' },

  // — Ketu aspects natal —
  { name: 'Ketu aspect Sun in 3rd house', description: 'Ketu on 3H Sun — authority feels hollow; ego drops out of work.' },
  { name: 'Ketu aspect Sun in 3rd house : Starts', description: 'Authority-eclipse begins.' },
  { name: 'Ketu aspect Sun in 3rd house : Exact', description: 'Peak Ketu-Sun day. Dharmic message lands.' },
  { name: 'Ketu aspect Sun in 3rd house : Ends', description: 'Authority-eclipse fades.' },
  { name: 'Ketu aspect Moon in 2nd house', description: 'Ketu on 2H Moon — voice/income detachment. Purifying.' },
  { name: 'Ketu aspect Moon in 2nd house : Starts', description: 'Voice-detachment begins.' },
  { name: 'Ketu aspect Moon in 2nd house : Exact', description: 'Peak Ketu-Moon day. Sit with dissonance.' },
  { name: 'Ketu aspect Moon in 2nd house : Ends', description: 'Voice-detachment fades.' },
  { name: 'Ketu aspect Mercury in 3rd house', description: 'Ketu on 3H Mercury (own sign) — solo precision; collaborative misfires.' },
  { name: 'Ketu aspect Mercury in 3rd house : Starts', description: 'Detached-mind window opens.' },
  { name: 'Ketu aspect Mercury in 3rd house : Exact', description: 'Peak Ketu-Mercury day. Solo breakthrough.' },
  { name: 'Ketu aspect Mercury in 3rd house : Ends', description: 'Detached-mind closes.' },
  { name: 'Ketu aspect Venus in 4th house', description: 'Ketu on 4H Venus — home-detachment; downsizing favored.' },
  { name: 'Ketu aspect Venus in 4th house : Starts', description: 'Home-detachment begins.' },
  { name: 'Ketu aspect Venus in 4th house : Exact', description: 'Peak home-Ketu day.' },
  { name: 'Ketu aspect Venus in 4th house : Ends', description: 'Home-detachment fades.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Ketu on 7H exalted Mars — partnership eclipse.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Partnership-eclipse begins.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Peak Ketu-Mars day. Honor what closes.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Partnership-eclipse closes.' },
  { name: 'Ketu aspect Jupiter in 6th house', description: 'Ketu on 6H Jupiter — service-detachment; chronic enemies disengage.' },
  { name: 'Ketu aspect Jupiter in 6th house : Starts', description: 'Service-detachment begins.' },
  { name: 'Ketu aspect Jupiter in 6th house : Exact', description: 'Peak service-Ketu day.' },
  { name: 'Ketu aspect Jupiter in 6th house : Ends', description: 'Service-detachment closes.' },
  { name: 'Ketu aspect Saturn in 8th house', description: 'Ketu on 8H Saturn — transformation-detachment; don\'t resist.' },
  { name: 'Ketu aspect Saturn in 8th house : Starts', description: 'Transformation-detachment begins.' },
  { name: 'Ketu aspect Saturn in 8th house : Exact', description: 'Peak Ketu-Saturn day. Buried truth surfaces.' },
  { name: 'Ketu aspect Saturn in 8th house : Ends', description: 'Transformation-detachment closes.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Ketu opposes Rahu — axis activation in dharma.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Nodal-axis window begins.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Peak axis day.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Nodal-axis closes.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Ketu return — once-in-18-years cluster reset.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Ketu-return opens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Peak Ketu-return day. Mark threshold.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu-return closes.' },

  // — Mars aspects natal —
  { name: 'Mars aspect Sun in 3rd house', description: 'Mars on 3H Sun — fierce ship-write-defend day.' },
  { name: 'Mars aspect Sun in 3rd house : Starts', description: 'Mars-Sun cluster window opens.' },
  { name: 'Mars aspect Sun in 3rd house : Exact', description: 'Peak Mars-Sun day. Ship hard; watch temper.' },
  { name: 'Mars aspect Sun in 3rd house : Ends', description: 'Mars-Sun cluster closes.' },
  { name: 'Mars aspect Moon in 2nd house', description: 'Mars on 2H Moon — heated speech; throat care.' },
  { name: 'Mars aspect Moon in 2nd house : Starts', description: 'Voice-heat rising.' },
  { name: 'Mars aspect Moon in 2nd house : Exact', description: 'Peak Mars-Moon day. Calm fire on family-money.' },
  { name: 'Mars aspect Moon in 2nd house : Ends', description: 'Voice-heat fades.' },
  { name: 'Mars aspect Mercury in 3rd house', description: 'Mars on 3H Mercury — sharp execution mind.' },
  { name: 'Mars aspect Mercury in 3rd house : Starts', description: 'Sharp-mind window opens.' },
  { name: 'Mars aspect Mercury in 3rd house : Exact', description: 'Peak Mars-Mercury day. Send precise cutting note.' },
  { name: 'Mars aspect Mercury in 3rd house : Ends', description: 'Sharp-mind closes.' },
  { name: 'Mars aspect Venus in 4th house', description: 'Mars on 4H Venus — heated home dynamics.' },
  { name: 'Mars aspect Venus in 4th house : Starts', description: 'Home-heat opens.' },
  { name: 'Mars aspect Venus in 4th house : Exact', description: 'Peak Mars-Venus day. Decisive home action.' },
  { name: 'Mars aspect Venus in 4th house : Ends', description: 'Home-heat closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Mars-return on yogakaraka — peak partnership-action.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Mars-return opens.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Peak partnership-action day. Sign deals.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Mars-return closes.' },
  { name: 'Mars aspect Jupiter in 6th house', description: 'Mars on 6H Jupiter — fierce service-combat.' },
  { name: 'Mars aspect Jupiter in 6th house : Starts', description: 'Service-combat opens.' },
  { name: 'Mars aspect Jupiter in 6th house : Exact', description: 'Peak Mars-Jupiter day. Win the rivalry.' },
  { name: 'Mars aspect Jupiter in 6th house : Ends', description: 'Service-combat closes.' },
  { name: 'Mars aspect Saturn in 8th house', description: 'Mars on 8H Saturn — surgical action in transformation.' },
  { name: 'Mars aspect Saturn in 8th house : Starts', description: 'Transformation-action opens.' },
  { name: 'Mars aspect Saturn in 8th house : Exact', description: 'Peak Mars-Saturn day. Lead through chaos.' },
  { name: 'Mars aspect Saturn in 8th house : Ends', description: 'Transformation-action closes.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Mars on 9H Rahu — assertive foreign moves.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Foreign-combat opens.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Peak Mars-Rahu day. Push principled position.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Foreign-combat closes.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Mars on 3H Ketu — sharp solo execution.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Solo-action opens.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Peak Mars-Ketu day. Solo breakthrough.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Solo-action closes.' },

  // — Mercury aspects natal —
  { name: 'Mercury aspect Sun in 3rd house', description: 'Mercury on 3H Sun — return-style activation. Best for: presentation; technical-leadership pitch.' },
  { name: 'Mercury aspect Sun in 3rd house : Starts', description: 'Editorial-authority opens.' },
  { name: 'Mercury aspect Sun in 3rd house : Exact', description: 'Peak Mercury-Sun day. Ship the document.' },
  { name: 'Mercury aspect Sun in 3rd house : Ends', description: 'Editorial-authority closes.' },
  { name: 'Mercury aspect Moon in 2nd house', description: 'Mercury on 2H Moon — articulate emotional speech.' },
  { name: 'Mercury aspect Moon in 2nd house : Starts', description: 'Voice-articulation opens.' },
  { name: 'Mercury aspect Moon in 2nd house : Exact', description: 'Peak Mercury-Moon day. Speak from the heart with precision.' },
  { name: 'Mercury aspect Moon in 2nd house : Ends', description: 'Voice-articulation closes.' },
  { name: 'Mercury aspect Mercury in 3rd house', description: 'Mercury return on cluster — annual peak technical day.' },
  { name: 'Mercury aspect Mercury in 3rd house : Starts', description: 'Mercury return opens.' },
  { name: 'Mercury aspect Mercury in 3rd house : Exact', description: 'Peak technical-mind day.' },
  { name: 'Mercury aspect Mercury in 3rd house : Ends', description: 'Mercury return closes.' },
  { name: 'Mercury aspect Venus in 4th house', description: 'Mercury on 4H Venus — diplomatic family/home comm.' },
  { name: 'Mercury aspect Venus in 4th house : Starts', description: 'Home-comm opens.' },
  { name: 'Mercury aspect Venus in 4th house : Exact', description: 'Peak Mercury-Venus day. Send the diplomatic note.' },
  { name: 'Mercury aspect Venus in 4th house : Ends', description: 'Home-comm closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Mercury on 7H Mars — precise contractual comm.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Contract-comm opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Peak Mercury-Mars day. Send term sheet.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Contract-comm closes.' },
  { name: 'Mercury aspect Jupiter in 6th house', description: 'Mercury on 6H Jupiter — service-and-wisdom comm.' },
  { name: 'Mercury aspect Jupiter in 6th house : Starts', description: 'Service-comm opens.' },
  { name: 'Mercury aspect Jupiter in 6th house : Exact', description: 'Peak Mercury-Jupiter day. Resolve chronic dispute.' },
  { name: 'Mercury aspect Jupiter in 6th house : Ends', description: 'Service-comm closes.' },
  { name: 'Mercury aspect Saturn in 8th house', description: 'Mercury on 8H Saturn — investigative depth-writing.' },
  { name: 'Mercury aspect Saturn in 8th house : Starts', description: 'Depth-writing opens.' },
  { name: 'Mercury aspect Saturn in 8th house : Exact', description: 'Peak depth-mind day. Forensic insight lands.' },
  { name: 'Mercury aspect Saturn in 8th house : Ends', description: 'Depth-writing closes.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Mercury on 9H Rahu — debilitated; foreign-vision study favored.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Foreign-vision opens.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Peak Mercury-Rahu day.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Foreign-vision closes.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Mercury on 3H Ketu — paradoxical detached precision.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Detached-precision opens.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Peak Mercury-Ketu day. Solo clarity.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Detached-precision closes.' },

  // — Moon aspects natal —
  { name: 'Moon aspect Sun in 3rd house', description: 'Moon on 3H Sun — feelings drive day. Warm-toned communication lands.' },
  { name: 'Moon aspect Sun in 3rd house : Starts', description: 'Feelings-on-authority opens.' },
  { name: 'Moon aspect Sun in 3rd house : Exact', description: 'Peak Moon-Sun day. Send emotionally honest memo.' },
  { name: 'Moon aspect Sun in 3rd house : Ends', description: 'Feelings-on-authority closes.' },
  { name: 'Moon aspect Moon in 2nd house', description: 'Moon return on 2H Moon — annual emotional voice peak.' },
  { name: 'Moon aspect Moon in 2nd house : Starts', description: 'Voice emotional opens.' },
  { name: 'Moon aspect Moon in 2nd house : Exact', description: 'Peak Moon return day. Speak warmly.' },
  { name: 'Moon aspect Moon in 2nd house : Ends', description: 'Voice emotional closes.' },
  { name: 'Moon aspect Mercury in 3rd house', description: 'Moon on 3H Mercury — warm-toned writing.' },
  { name: 'Moon aspect Mercury in 3rd house : Starts', description: 'Warm-tone opens.' },
  { name: 'Moon aspect Mercury in 3rd house : Exact', description: 'Peak Moon-Mercury day. Tone over content.' },
  { name: 'Moon aspect Mercury in 3rd house : Ends', description: 'Warm-tone closes.' },
  { name: 'Moon aspect Venus in 4th house', description: 'Moon on 4H Venus — peak home day. Cook; nest; mother.' },
  { name: 'Moon aspect Venus in 4th house : Starts', description: 'Home-emotional opens.' },
  { name: 'Moon aspect Venus in 4th house : Exact', description: 'Peak Moon-Venus day. Host gathering.' },
  { name: 'Moon aspect Venus in 4th house : Ends', description: 'Home-emotional closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Moon on 7H Mars — emotional charge in partnership.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Partnership-emotion opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Peak Moon-Mars day. Soften contract conversation.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Partnership-emotion closes.' },
  { name: 'Moon aspect Jupiter in 6th house', description: 'Moon on 6H Jupiter — service-empathy day.' },
  { name: 'Moon aspect Jupiter in 6th house : Starts', description: 'Service-empathy opens.' },
  { name: 'Moon aspect Jupiter in 6th house : Exact', description: 'Peak Moon-Jupiter day. Resolve conflict warmly.' },
  { name: 'Moon aspect Jupiter in 6th house : Ends', description: 'Service-empathy closes.' },
  { name: 'Moon aspect Saturn in 8th house', description: 'Moon on 8H Saturn — emotional weight; defer big decisions.' },
  { name: 'Moon aspect Saturn in 8th house : Starts', description: 'Transformation-emotion opens.' },
  { name: 'Moon aspect Saturn in 8th house : Exact', description: 'Peak Moon-Saturn day. Sleep more.' },
  { name: 'Moon aspect Saturn in 8th house : Ends', description: 'Transformation-emotion closes.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Moon on 9H Rahu — emotional pull foreign/dharma.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Foreign-vision-emotion opens.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Peak Moon-Rahu day. Capture dream; commit later.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Foreign-vision-emotion closes.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Moon on 3H Ketu — solo-emotion. Solo writing flourishes.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Solo-emotion opens.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Peak Moon-Ketu day. Solo deep-work.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Solo-emotion closes.' },

  // — Saturn aspects natal —
  { name: 'Saturn aspect Sun in 3rd house', description: 'Saturn on 3H Sun — structural test of authority. Slow recognition.' },
  { name: 'Saturn aspect Sun in 3rd house : Starts', description: 'Authority-discipline opens.' },
  { name: 'Saturn aspect Sun in 3rd house : Exact', description: 'Peak Saturn-Sun day. Ship disciplined output.' },
  { name: 'Saturn aspect Sun in 3rd house : Ends', description: 'Authority-discipline closes.' },
  { name: 'Saturn aspect Moon in 2nd house', description: 'Saturn on 2H Moon — voice/income discipline.' },
  { name: 'Saturn aspect Moon in 2nd house : Starts', description: 'Voice-discipline opens.' },
  { name: 'Saturn aspect Moon in 2nd house : Exact', description: 'Peak Saturn-Moon day. Patience compounds.' },
  { name: 'Saturn aspect Moon in 2nd house : Ends', description: 'Voice-discipline closes.' },
  { name: 'Saturn aspect Mercury in 3rd house', description: 'Saturn on 3H Mercury (own sign) — long-form chapter.' },
  { name: 'Saturn aspect Mercury in 3rd house : Starts', description: 'Structural-comm opens.' },
  { name: 'Saturn aspect Mercury in 3rd house : Exact', description: 'Peak Saturn-Mercury day. Ship long-form work.' },
  { name: 'Saturn aspect Mercury in 3rd house : Ends', description: 'Structural-comm closes.' },
  { name: 'Saturn aspect Venus in 4th house', description: 'Saturn on 4H Venus — home test. Buy carefully.' },
  { name: 'Saturn aspect Venus in 4th house : Starts', description: 'Home-discipline opens.' },
  { name: 'Saturn aspect Venus in 4th house : Exact', description: 'Peak Saturn-Venus day. Home reckoning.' },
  { name: 'Saturn aspect Venus in 4th house : Ends', description: 'Home-discipline closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Saturn on 7H exalted Mars — heavy partnership chapter.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Partnership-discipline opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Peak Saturn-Mars day. Reckoning of which deals are real.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Partnership-discipline closes.' },
  { name: 'Saturn aspect Jupiter in 6th house', description: 'Saturn on 6H Jupiter — favorable. Long battles won through patience.' },
  { name: 'Saturn aspect Jupiter in 6th house : Starts', description: 'Service-discipline opens.' },
  { name: 'Saturn aspect Jupiter in 6th house : Exact', description: 'Peak Saturn-Jupiter day.' },
  { name: 'Saturn aspect Jupiter in 6th house : Ends', description: 'Service-discipline closes.' },
  { name: 'Saturn aspect Saturn in 8th house', description: 'Saturn return — once-in-29-years deep transformation.' },
  { name: 'Saturn aspect Saturn in 8th house : Starts', description: 'Saturn return opens.' },
  { name: 'Saturn aspect Saturn in 8th house : Exact', description: 'Peak Saturn return day. Half-life reckoning.' },
  { name: 'Saturn aspect Saturn in 8th house : Ends', description: 'Saturn return closes.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Saturn on 9H Rahu — pressure on dharma node.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Foreign-discipline opens.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Peak Saturn-Rahu day. Dharma path reckoning.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Foreign-discipline closes.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Saturn on 3H Ketu — solo deep work compounds.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Solo-discipline opens.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Peak Saturn-Ketu day. Solo opus apex.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Solo-discipline closes.' },

  // — Sun aspects natal —
  { name: 'Sun aspect Sun in 3rd house', description: 'Solar return on 3H Sun — annual peak. Pitch the document.' },
  { name: 'Sun aspect Sun in 3rd house : Starts', description: 'Solar return opens.' },
  { name: 'Sun aspect Sun in 3rd house : Exact', description: 'Peak solar-return day. Ship; claim authorship.' },
  { name: 'Sun aspect Sun in 3rd house : Ends', description: 'Solar return closes.' },
  { name: 'Sun aspect Moon in 2nd house', description: 'Sun on 2H Moon — authoritative voice/family-finance window.' },
  { name: 'Sun aspect Moon in 2nd house : Starts', description: 'Voice-authority opens.' },
  { name: 'Sun aspect Moon in 2nd house : Exact', description: 'Peak Sun-Moon day. Speak with full authority.' },
  { name: 'Sun aspect Moon in 2nd house : Ends', description: 'Voice-authority closes.' },
  { name: 'Sun aspect Mercury in 3rd house', description: 'Sun on 3H Mercury — annual visibility on technical mind.' },
  { name: 'Sun aspect Mercury in 3rd house : Starts', description: 'Technical-authority opens.' },
  { name: 'Sun aspect Mercury in 3rd house : Exact', description: 'Peak Sun-Mercury day. Take authorship.' },
  { name: 'Sun aspect Mercury in 3rd house : Ends', description: 'Technical-authority closes.' },
  { name: 'Sun aspect Venus in 4th house', description: 'Sun on 4H Venus — annual visibility through home channels.' },
  { name: 'Sun aspect Venus in 4th house : Starts', description: 'Home-authority opens.' },
  { name: 'Sun aspect Venus in 4th house : Exact', description: 'Peak Sun-Venus day. Step into family-business leadership.' },
  { name: 'Sun aspect Venus in 4th house : Ends', description: 'Home-authority closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Sun on 7H exalted Mars — annual peak partnership-authority.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Partnership-authority opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Peak Sun-Mars day. Sign anchor contract.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Partnership-authority closes.' },
  { name: 'Sun aspect Jupiter in 6th house', description: 'Sun on 6H Jupiter — service-authority peak.' },
  { name: 'Sun aspect Jupiter in 6th house : Starts', description: 'Service-authority opens.' },
  { name: 'Sun aspect Jupiter in 6th house : Exact', description: 'Peak Sun-Jupiter day. Take expert lead.' },
  { name: 'Sun aspect Jupiter in 6th house : Ends', description: 'Service-authority closes.' },
  { name: 'Sun aspect Saturn in 8th house', description: 'Sun on 8H Saturn — authoritative leadership through transformation.' },
  { name: 'Sun aspect Saturn in 8th house : Starts', description: 'Transformation-leadership opens.' },
  { name: 'Sun aspect Saturn in 8th house : Exact', description: 'Peak Sun-Saturn day. Lead through chaos.' },
  { name: 'Sun aspect Saturn in 8th house : Ends', description: 'Transformation-leadership closes.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Sun on 9H Rahu — visibility through foreign/dharma channels.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Foreign-authority opens.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Peak Sun-Rahu day. Take international stage.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Foreign-authority closes.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Sun on 3H Ketu — paradoxical authority-on-detachment.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Solo-authority opens.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Peak Sun-Ketu day. Solo authority lands.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Solo-authority closes.' },

  // — Venus aspects natal —
  { name: 'Venus aspect Sun in 3rd house', description: 'Venus on 3H Sun — graceful authoritative comm. Charm with substance.' },
  { name: 'Venus aspect Sun in 3rd house : Starts', description: 'Graceful-authority opens.' },
  { name: 'Venus aspect Sun in 3rd house : Exact', description: 'Peak Venus-Sun day.' },
  { name: 'Venus aspect Sun in 3rd house : Ends', description: 'Graceful-authority closes.' },
  { name: 'Venus aspect Moon in 2nd house', description: 'Venus on 2H Moon — luxurious income/voice window.' },
  { name: 'Venus aspect Moon in 2nd house : Starts', description: 'Income-luxury opens.' },
  { name: 'Venus aspect Moon in 2nd house : Exact', description: 'Peak Venus-Moon day. Negotiate generously.' },
  { name: 'Venus aspect Moon in 2nd house : Ends', description: 'Income-luxury closes.' },
  { name: 'Venus aspect Mercury in 3rd house', description: 'Venus on 3H Mercury — graceful technical comm.' },
  { name: 'Venus aspect Mercury in 3rd house : Starts', description: 'Graceful-mind opens.' },
  { name: 'Venus aspect Mercury in 3rd house : Exact', description: 'Peak Venus-Mercury day. Beautiful precision lands.' },
  { name: 'Venus aspect Mercury in 3rd house : Ends', description: 'Graceful-mind closes.' },
  { name: 'Venus aspect Venus in 4th house', description: 'Venus return — annual home-foundation peak.' },
  { name: 'Venus aspect Venus in 4th house : Starts', description: 'Venus return opens.' },
  { name: 'Venus aspect Venus in 4th house : Exact', description: 'Peak Venus return day.' },
  { name: 'Venus aspect Venus in 4th house : Ends', description: 'Venus return closes.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Venus on 7H exalted Mars — partnership warmth + rigor.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Partnership-warmth opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Peak Venus-Mars day. Sign with both warmth and rigor.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Partnership-warmth closes.' },
  { name: 'Venus aspect Jupiter in 6th house', description: 'Venus on 6H Jupiter — diplomatic service excellence.' },
  { name: 'Venus aspect Jupiter in 6th house : Starts', description: 'Service-diplomacy opens.' },
  { name: 'Venus aspect Jupiter in 6th house : Exact', description: 'Peak Venus-Jupiter day. Resolve with grace.' },
  { name: 'Venus aspect Jupiter in 6th house : Ends', description: 'Service-diplomacy closes.' },
  { name: 'Venus aspect Saturn in 8th house', description: 'Venus on 8H Saturn — diplomatic transformation.' },
  { name: 'Venus aspect Saturn in 8th house : Starts', description: 'Transformation-diplomacy opens.' },
  { name: 'Venus aspect Saturn in 8th house : Exact', description: 'Peak Venus-Saturn day. Negotiate with diplomacy.' },
  { name: 'Venus aspect Saturn in 8th house : Ends', description: 'Transformation-diplomacy closes.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Venus on 9H Rahu — graceful foreign engagement.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Foreign-diplomacy opens.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Peak Venus-Rahu day. Sign cross-border deal.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Foreign-diplomacy closes.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Venus on 3H Ketu — graceful detachment in cluster.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Solo-aesthetic opens.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Peak Venus-Ketu day.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Solo-aesthetic closes.' },

  // — Rahu aspects natal —
  { name: 'Rahu aspect Sun in 3rd house', description: 'Rahu on 3H Sun — chaotic authority. Watch over-claiming.' },
  { name: 'Rahu aspect Sun in 3rd house : Starts', description: 'Chaotic-authority opens.' },
  { name: 'Rahu aspect Sun in 3rd house : Exact', description: 'Peak Rahu-Sun day. Move with discipline.' },
  { name: 'Rahu aspect Sun in 3rd house : Ends', description: 'Chaotic-authority closes.' },
  { name: 'Rahu aspect Moon in 2nd house', description: 'Rahu on 2H Moon — chaotic income/voice.' },
  { name: 'Rahu aspect Moon in 2nd house : Starts', description: 'Chaotic-income opens.' },
  { name: 'Rahu aspect Moon in 2nd house : Exact', description: 'Peak Rahu-Moon day. Don\'t leverage on sudden wealth.' },
  { name: 'Rahu aspect Moon in 2nd house : Ends', description: 'Chaotic-income closes.' },
  { name: 'Rahu aspect Mercury in 3rd house', description: 'Rahu on 3H Mercury (own sign) — explosive breakthrough.' },
  { name: 'Rahu aspect Mercury in 3rd house : Starts', description: 'Breakthrough-mind opens.' },
  { name: 'Rahu aspect Mercury in 3rd house : Exact', description: 'Peak Rahu-Mercury day. Ship boundary-breaking work.' },
  { name: 'Rahu aspect Mercury in 3rd house : Ends', description: 'Breakthrough-mind closes.' },
  { name: 'Rahu aspect Venus in 4th house', description: 'Rahu on 4H Venus — chaotic home dynamics.' },
  { name: 'Rahu aspect Venus in 4th house : Starts', description: 'Home-chaos opens.' },
  { name: 'Rahu aspect Venus in 4th house : Exact', description: 'Peak Rahu-Venus day. Move with discipline.' },
  { name: 'Rahu aspect Venus in 4th house : Ends', description: 'Home-chaos closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Rahu on 7H exalted Mars — chaotic partnerships.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Chaotic-partnership opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Peak Rahu-Mars day. Verify before signing.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Chaotic-partnership closes.' },
  { name: 'Rahu aspect Jupiter in 6th house', description: 'Rahu on 6H Jupiter — favorable. Defeat enemies.' },
  { name: 'Rahu aspect Jupiter in 6th house : Starts', description: 'Unconventional-service opens.' },
  { name: 'Rahu aspect Jupiter in 6th house : Exact', description: 'Peak Rahu-Jupiter day. Win unconventional victory.' },
  { name: 'Rahu aspect Jupiter in 6th house : Ends', description: 'Unconventional-service closes.' },
  { name: 'Rahu aspect Saturn in 8th house', description: 'Rahu on 8H Saturn — sudden transformation events.' },
  { name: 'Rahu aspect Saturn in 8th house : Starts', description: 'Sudden-transformation opens.' },
  { name: 'Rahu aspect Saturn in 8th house : Exact', description: 'Peak Rahu-Saturn day. Vipareet wisdom.' },
  { name: 'Rahu aspect Saturn in 8th house : Ends', description: 'Sudden-transformation closes.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Rahu return — once-in-18-years foreign-dharma peak.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return opens.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Peak Rahu return day. Mark threshold.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return closes.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Rahu opposes Ketu — axis activation.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Nodal-axis opens.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Peak axis day. Clearer dharma direction.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal-axis closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
