// db/seed_relationship_taurus.js
//
// Per-ascendant fill-in seed for the **relationship** category, scoped to a
// representative Taurus ascendant native with:
//   Ascendant: Taurus
//   Natal placements (sidereal Lahiri):
//     Sun=4th (Leo, own)  Moon=3rd (Cancer, own)  Mercury=5th (Virgo, own+exalted)
//     Venus=1st (Taurus, own — Malavya Yoga)  Mars=7th (Scorpio, own — Ruchaka Yoga)
//     Jupiter=11th (Pisces, own)  Saturn=10th (Aquarius, own — Sasa Yoga, yogakaraka)
//     Rahu=8th (Sagittarius)  Ketu=2nd (Gemini)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose relationship-specific interpretations, then run:
//
//   node db/seed_relationship_taurus.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./relationship');

const ASCENDANT = 'Taurus';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Venus ruler of the 1st House in the 1st House', description: 'You are the magnet. Your face, body, voice, posture, taste — these are what the room responds to. Slow, deliberate, sensual presence is your romantic signature; rushed approaches misfire. Partners are drawn to the stillness, the warmth, the curated aesthetic, the unmistakable comfort of being near you. The shadow: the same magnetism that pulls everyone in can become a comfort-trap — when admiration replaces intimacy, the relationship quietly stalls. Choose the partner who sees through the surface.' },
  { name: 'Mercury ruler of the 2nd House in the 5th House', description: 'Romance unfolds through play, wit, performance, creative back-and-forth. Family-of-origin money topics are best handled with the partner as a creative project, not a chore. You speak well in love — the love note, the playful text, the witty banter, the curated date — and partners who respond to language and craft compound with you. The shadow: speech that performs intimacy without delivering it; track whether the polished message also carries warmth.' },
  { name: 'Moon ruler of the 3rd House in the 3rd House', description: 'Emotional courage through communication is the love-language. The brave message, the candid text, the warm sibling-like banter, the willingness to say the difficult thing. Partners who match your communicative nerve land; partners who go silent under pressure drift. The shadow: emotional weather flooding the message — wait an hour after a hot day before sending the bold note.' },
  { name: 'Sun ruler of the 4th House in the 4th House', description: 'Home is the proving ground of love. Partners enter through the front door of family, property, hearth. The relationship that survives is the one your house recognizes — that fits the kitchen, the dining table, the family rhythm. Father-figure approval is unusually weighty. The shadow: paternal projections coloring partner-choice. Honor the lineage, but choose the love yourself.' },
  { name: 'Mercury ruler of the 5th House in the 5th House', description: 'Romance is exalted-Mercury territory — sharp, witty, playful, creative, performance-tinged. Courtship as art form. You charm through cleverness; partners who can banter at your tempo become the long-term match. Children, creative offspring, mentee-relationships, romance-tinged collaborations all light up here. The shadow: over-mentalizing the feeling — sometimes the heart wants the hug, not the apt sentence.' },
  { name: 'Venus ruler of the 6th House in the 1st House', description: 'Conflict, daily-grind friction, debt-and-stress in the partnership all land directly on your body. The fight does not stay in the air; it lodges in your shoulders, your sleep, your skin. Working out adversity through service-mode together — practical errands, joint chores, mutual care — heals more than confrontation does. The shadow: charm used to dodge the conflict will compound the underlying friction.' },
  { name: 'Mars ruler of the 7th House in the 7th House', description: 'Partner is intense — Ruchaka Mars on the 7H throne. Fierce, magnetic, possessive, transformative, sexually charged, secretive at depth. The relationship has volcanic torque; small differences ignite, deep loyalty forms in the same fire. Partners with weak edges get burned; partners with their own flame stay. The shadow: combat that leaves real scars — channel the intensity into shared mission, not at each other.' },
  { name: 'Jupiter ruler of the 8th House in the 11th House', description: 'Sexual depth, occult intimacy, transformation-shared, inheritance-blended — all route through the wide-network engine. Long-arc joint-equity (joint accounts, shared estates, family trusts that bridge two clans) flows through ethical, friend-circle-blessed structures. The shadow: ethical drift in the joint-finance — re-audit the principle behind each large blended decision.' },
  { name: 'Saturn ruler of the 9th House in the 10th House', description: 'Dharma-aligned partnership. The relationship that lasts is the one that shares your principle, your ethical north, your long-arc commitment. Marriage often delays; when it lands, it is structural and durable. Foreign or teacher-figure partner is common; the relationship has the gravity of mission rather than the lightness of play. The shadow: dharma-rigidity that misses the partner\'s living, evolving shape.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Marriage is for the long horizon — Sasa-Yoga durability. The serious career-aligned partner; the union that becomes a public mantle; the one who shows up at every formal event for forty years. Marriage may delay until structural-career maturity; when it forms, it is permanent. The shadow: the partnership becoming another corporate role — keep the warmth alive against the weight.' },
  { name: 'Jupiter ruler of the 11th House in the 11th House', description: 'Friendship-as-foundation. The partner often emerges from the wide friend-circle, the international network, the cooperative-platform, the teacher-mentee chain. Friends are the matchmakers; the wedding has a hundred well-wishers from across continents. The shadow: too many advisors in the relationship — the inner sanctum needs privacy.' },
  { name: 'Mars ruler of the 12th House in the 7th House', description: 'Foreign or behind-the-scenes intensities feed the partnership. Spouse may live abroad, work in confidential mandates, hold a private inner-life that is fierce. The bedroom is where the most action happens; the public face of the marriage is composed, the private one is volcanic. The shadow: hidden conflicts that drain liquidity-and-trust; name the friction early before it goes underground.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 4th (Dispositor)', description: 'When this engine fires, the home becomes the relationship\'s proving ground. Hosting family, cooking together, real-estate decisions, family-meet-and-greet. The shadow: paternal projection on partner-choice — see the partner, not the family-acceptance.' },
  { name: 'Moon in 3rd (Dispositor)', description: 'When this engine fires, courageous communication wins. The brave message that has been waiting, the candid conversation about the relationship, the warm sibling-like outreach. The shadow: emotional reactivity — wait an hour before pressing send when the day was hot.' },
  { name: 'Mercury in 5th (Dispositor)', description: 'When this engine fires, romance is playful, witty, performance-tinged. The clever date, the curated note, the creative collaboration with romantic edge. Children-related conversations gain warmth. The shadow: over-mentalizing; let some moments stay non-verbal.' },
  { name: 'Venus in 1st (Dispositor)', description: 'When this engine fires, the magnetism is at peak. Old admirers re-emerge; new ones arrive through your simple presence. Best windows for first-meetings, public romantic gestures, photo-driven dating. The shadow: surface-attraction over substance; verify the resonance under the gloss.' },
  { name: 'Mars in 7th (Dispositor)', description: 'When this engine fires, partnership intensity peaks. Fierce talks, transformative sex, contested decisions, deep emotional combat that ends in deeper loyalty. The shadow: fights that burn what should not be burned — pick the battle inside the love.' },
  { name: 'Jupiter in 11th (Dispositor)', description: 'When this engine fires, friendship-network drives the relationship. Friend-introductions, cooperative-platform romance, international-friend matchmaking, teacher-mentee romantic emergence. The shadow: too many advisors crowding the inner sanctum.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, the relationship gains structural weight. Public commitment moves, formal recognition, long-arc joint-planning. The shadow: corporate-tone seeping into the love — keep the warmth alive against the structure.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual personal-magnetism peak. Old admirers re-emerge; new attraction lands easily. Best four-week window for first-impression scenarios.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on speech and family-finance in the relationship. Money-conversations with the partner clarify; voice carries weight.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage in romantic communication. Send the brave note; have the candid talk; risk the message you have been postponing.' },
  { name: 'Sun Transits the 4th House', description: 'Annual home-throne activation in love. Host the partner at home; have the family-meeting; sign the joint property paper.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on romance, play, courtship. Best four-week window for first-dates, creative-collaboration romance, performance-tinged charm.' },
  { name: 'Sun Transits the 6th House', description: 'Solar light on conflict-management in the relationship. Address the daily-grind friction; resolve through service, not confrontation.' },
  { name: 'Sun Transits the 7th House', description: 'Annual partnership-visibility peak. Spouse and principal-counterparty light up. Renew the vows, formalize the commitment, take the deal public.' },
  { name: 'Sun Transits the 8th House', description: 'Solar fire in the intimacy-and-transformation chamber. Sexual chemistry sharpens; joint-finance decisions surface. Foreign-Rahu zone activated.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma-aligned partnership. Travel together; meet the partner\'s teacher; visit the temple/abroad together.' },
  { name: 'Sun Transits the 10th House', description: 'Solar fire on public partnership-status. Couple-as-public-figure window; formal events, board-couple appearances.' },
  { name: 'Sun Transits the 11th House', description: 'Solar light on friend-circle-as-relationship-engine. Group dinners, cooperative-platform events, international-friend matchmaking.' },
  { name: 'Sun Transits the 12th House', description: 'Solar light on confidential and foreign romance. Long-distance pull, foreign-trip with partner, retreat-as-relationship-medicine.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional-self window. The partner reads your mood directly; show up warm.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on voice and family-money in the relationship. Soft-spoken negotiations land.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional courage on communication. Send the brave note, take the candid call.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-emotion peak. Cook for the partner; host the family; the kitchen-table heals.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on play and creativity in love. The poetic gesture, the warm date, the playful surprise.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on daily friction. Address the small grievance with care; do not let it ferment.' },
  { name: 'Moon Transits the 7th House', description: 'Monthly partnership-pulse peak. Read the partner\'s mood before suggesting anything heavy; warmth wins the day.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight in the intimacy-chamber. Old fears about loyalty surface; process gently.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward shared dharma. Travel-together draft; pilgrimage-talk; teacher-couple conversation.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on the relationship\'s public face. The couple-photo, the social-event read-out.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth in friend-circle. Group dinner, friend-matchmaking, cooperative-platform romance.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness in love. Quiet-time, foreign-couple-trip planning, dream-rich romantic phase.' },
  { name: 'Mercury Transits the 1st House', description: 'Sharp self-articulation in the partnership. Refresh the bio, the dating profile, the founder-couple narrative.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation in love. Joint-finance plan, salary-with-partner conversation, family-finance memos.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s home turf for the love-message. Peak window for content-with-partner, written communications, sibling-channel deals.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-throne articulation. Real-estate paperwork, family-business memo, mother-channel correspondence about the partner.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury exalted on the romance throne. Witty courtship, playful messages, creative collaboration with partner peak.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp daily-friction articulation. Document the recurring grievance; the paper-trail clarifies.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, JV memos, written-vows, contractual love.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp intimacy-chamber articulation. Joint-account documentation, will-and-trust paperwork, sex-and-secrecy conversations.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp shared-dharma articulation. Travel-together planning, teacher-couple correspondence, ethical-partnership memo.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp public-partnership articulation. Couple-press releases, board-couple memos, formal status-updates.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp friend-network articulation. Cooperative-platform invites, international-friend introductions to the partner.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp confidential articulation. Foreign-correspondence with partner, retreat-strategy memos.' },
  { name: 'Venus Transits the 1st House', description: 'Venus on its Malavya throne — peak personal-magnetism month. New attraction lands easily; old admirers re-emerge.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on voice and family-money in love. Pricing the joint-life; family-finance softens.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on communication. The elegantly-worded brave note; the soft-spoken candid call.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on the home-throne. Aesthetic upgrades to the shared space, family-business diplomacy, mother-channel warmth.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on romance. Peak window for first-dates, anniversaries, creative-collaboration romance, child-conception conversations.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on daily-friction. Mediated grievances, charm-led conflict-resolution, soft-spoken settling.' },
  { name: 'Venus Transits the 7th House', description: 'Beauty on the partnership engine. Anchor-deal warmth, soft JV diplomacy, marriage-renewal energy.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in the intimacy-chamber. Sexual warmth, joint-finance softening, foreign-occult intimacy with grace.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on shared dharma. International-couple-trips, teacher-couple grace, ethical-partnership inflection.' },
  { name: 'Venus Transits the 10th House', description: 'Peak public-couple-aesthetic. Couple-photographs, board-couple events, brand-couple moments.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on friend-circle. Cooperative-platform diplomacy, international-friend-matchmaking, board-friend warmth.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on confidential and foreign romance. Long-distance warmth, retreat-couple, foreign-luxury back channel.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on the body. Sexual charge peaks; bold approaches land. Watch impulsivity in the message-tone.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on voice and family-money. Contested money-conversations with partner; argue from documentation.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on communication. Bold, fierce, brave messaging. Push the candid talk you have been postponing.' },
  { name: 'Mars Transits the 4th House', description: 'Mars on the home-throne. Property-disputes with partner; family-business friction. Don\'t fight the family in heat.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on romance. Bold first-moves, contested dating, fierce courtship. The push works.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on conflict — Mars\'s strong terrain. Address the daily-grind grievance; press the friction to resolution.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on its own throne (Scorpio 7H — Ruchaka activation). Peak partnership-intensity year. Sign the JV-of-love, divorce the dead deal, demand the relationship clarity.' },
  { name: 'Mars Transits the 8th House', description: 'Mars in the intimacy-chamber. Sexual charge sharpens; foreign-occult Rahu zone activates; joint-finance combat. Verify integrity before each fight.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on shared dharma. Bold travel-together moves, contested teacher-couple positions, fierce religious-organization combat.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on public-couple status. Bold couple-as-public-figure moves, contested formal-event positions.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on friend-circle. Bold cooperative-platform combat, contested friend-matchmaking, board-friend disputes.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential combat. Hidden enemies in the love-zone, foreign-affair pull, off-balance-sheet combat with partner.' },
  { name: 'Jupiter Transits the 1st House', description: 'Major year for self-magnetism expansion. Public-mantle assumption that draws the right partner; the body itself expands — discipline diet to keep the magnetism sharp.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Major year for voice and family-money expansion in love. Joint-money inflows, family-finance breakthrough.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Major year for communication-expansion in love. Publishing-with-partner, broadcast-couple, sibling-channel growth.' },
  { name: 'Jupiter Transits the 4th House', description: 'Major year for home-throne expansion. Real-estate acquisition with partner, family-meeting blessing, mother-line approval.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for romance and child-expansion. Engagement, marriage, conception, creative-child-with-partner.' },
  { name: 'Jupiter Transits the 6th House', description: 'Major year for adversary-victory in the relationship. Long grievances resolve favorably; chronic frictions fade.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major year for partnership-expansion. Marriage if unmarried; renewal/upgrade if married. Anchor-deal closure year.' },
  { name: 'Jupiter Transits the 8th House', description: 'Major year for intimacy and joint-finance expansion. Inheritance, equity-event, occult-research royalty. Verify ethical bedrock.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major year for dharma-expansion together. Foreign credentials, teaching-platform breakthrough, guru-blessing chapter.' },
  { name: 'Jupiter Transits the 10th House', description: 'Major year for public-couple expansion. Chief-of-something-couple offers, board-couple appointments, formal-recognition.' },
  { name: 'Jupiter Transits the 11th House', description: 'Jupiter on its own throne. Peak friend-circle gain year; international-friend-matchmaking peak; cooperative-platform romance compounds.' },
  { name: 'Jupiter Transits the 12th House', description: 'Major year for confidential and foreign expansion. Foreign-couple-trip, retreat-couple, behind-scenes blessing-chapter.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on the body and self-magnetism. Vanity-romance falls away; durable self emerges. Slow weight, joint, bone reckoning affects partner-readiness.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on voice and family-money in love. Slow joint-savings ritual; family-finance restructuring with partner.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on communication. Long-arc message-systems with partner; sibling-channel formalization.' },
  { name: 'Saturn Transits the 4th House', description: 'Multi-year discipline on the home-throne. Real-estate restructuring with partner; family-business reckoning; mother\'s health-and-relationship-position as long-arc concern.' },
  { name: 'Saturn Transits the 5th House', description: 'Multi-year discipline on romance and children. The slow courtship; the long-conception chapter; the patient creative-child-with-partner.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain. Multi-year discipline on daily-friction; long grievances structured into resolution.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnership. Spouse-and-deal commitments scrutinized; weak relationships end; strong ones formalize into 30-year structures.' },
  { name: 'Saturn Transits the 8th House', description: 'Multi-year reckoning in the intimacy-chamber. Inheritance disputes, joint-finance restructuring, foreign-occult navigation. Patience pays.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year shared-dharma discipline. Long credential-paths together, judicial-process couple, teaching-institution partnership.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on its own throne. Peak structural-couple chapter; chief-of-something-couple crystallizes; legacy-grade marriage sets in.' },
  { name: 'Saturn Transits the 11th House', description: 'Multi-year discipline on the friend-network. Cooperative-platform formalization, international-friend deepening, board-couple consolidation.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on confidential and foreign love. Long retreat-couple chapter, foreign-confidential mandates, off-balance-sheet structuring with partner.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive identity-reinvention in love. New persona, new attraction, new partner-pull. Verify each move; the obsession runs hot.' },
  { name: 'Rahu Transits the 2nd House', description: 'Eighteen-month obsession on voice and family-money in love. Sudden joint-money chaos; verify each scheme.' },
  { name: 'Rahu Transits the 3rd House', description: 'Eighteen-month obsessive communication chapter in love. Viral love-content, controversial sibling-channel moves.' },
  { name: 'Rahu Transits the 4th House', description: 'Eighteen-month home-throne obsession. Foreign-property pull with partner, family-business reinvention, real-estate fevers.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month obsessive romance chapter. Speculation in love, viral first-meetings, controversial public-stage romance.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Eighteen-month obsessive grievance-defeat chapter. Long-running enemies of the relationship fall.' },
  { name: 'Rahu Transits the 7th House', description: 'Eighteen-month obsessive partnership chapter. Foreign spouse, controversial JV, sudden anchor-counterparty.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on its strong terrain (8H). Eighteen-month obsessive intimacy chapter. Inheritance chaos, joint-finance windfalls, foreign-occult breakthroughs. Verify everything.' },
  { name: 'Rahu Transits the 9th House', description: 'Eighteen-month foreign-dharma obsession together. International guru-pull as a couple, controversial teaching-platforms, foreign-credential push.' },
  { name: 'Rahu Transits the 10th House', description: 'Eighteen-month public-couple-reinvention obsession. Sudden public mantles, unconventional couple-roles.' },
  { name: 'Rahu Transits the 11th House', description: 'Eighteen-month obsessive friend-circle chapter. Sudden viral-network gains, controversial cooperative-platforms, foreign-friend-matchmaking.' },
  { name: 'Rahu Transits the 12th House', description: 'Eighteen-month foreign-confidential obsession in love. Hidden mandates, foreign-occult chapters, off-balance-sheet intensities with partner.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping window. Old self-image as partner-magnet feels empty. Sit; do not over-correct.' },
  { name: 'Ketu Transits the 2nd House', description: 'Eighteen-month detachment from voice and family-money. Old earning-paths and family-channel feel hollow; the cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Eighteen-month communication-detachment. Old message-loops feel finished; sibling-channel quiets.' },
  { name: 'Ketu Transits the 4th House', description: 'Eighteen-month home-throne detachment. Old real-estate plans feel weightless; family-attachment to the partner dissolves.' },
  { name: 'Ketu Transits the 5th House', description: 'Eighteen-month romance-detachment. Old courtship-loops feel finished; speculative-love cravings fall away.' },
  { name: 'Ketu Transits the 6th House', description: 'Eighteen-month grievance-detachment. Long-standing relationship-grievances dissolve quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Eighteen-month partnership-detachment. Old deal feels finished; spouse / principal-counterparty dynamic loosens.' },
  { name: 'Ketu Transits the 8th House', description: 'Eighteen-month intimacy-acceleration. Old sexual-loops dissolve; deep occult-research detachment in the bedroom.' },
  { name: 'Ketu Transits the 9th House', description: 'Eighteen-month shared-dharma detachment. Old guru-attachments fade; principle-without-attachment ripens together.' },
  { name: 'Ketu Transits the 10th House', description: 'Eighteen-month public-couple-eclipse. Old public-mantle of the couple feels weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month friend-circle detachment. Old friend-network drifts; cooperative-platform around couple quiets.' },
  { name: 'Ketu Transits the 12th House', description: 'Eighteen-month confidential-and-foreign detachment. Old retreats, foreign-mandates close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar fire on personal-magnetism. Old admirers re-emerge; new attraction lands.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Magnetism window opens. Polish the public-self.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the visible romantic move.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Magnetism window closes. Convert attraction into commitment.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar fire on public-couple status. Couple-as-public-figure window.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Public-couple window opens. Plan the formal event.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak day. Make the public-couple appearance.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Public-couple window closes.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on personal-magnetism. The partner reads your mood directly.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Show up warm; the magnetism is feeling-led today.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-couple status. Warm couple-photo windows.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Public-couple-emotion window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the warm-toned formal-event appearance.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Public-couple-emotion window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-articulation in love. Refresh the bio, the dating profile, the founder-couple narrative.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Self-articulation window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Send the polished introduction; publish the personal post.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Self-articulation window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp public-couple articulation. Couple-press, formal-status updates.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Public-couple-articulation window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Issue the formal status, send the couple-press release.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Public-couple-articulation window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Venus on its Malavya throne — peak personal-magnetism. The smile lands; the warm presence pulls.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Malavya-self window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak Malavya day. Show up where you want to be seen; the magnetism is at its yearly high.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Malavya-self window closes. Convert magnetism into commitment.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Beauty on public-couple status. Couple-aesthetic peaks.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Public-couple-beauty window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the couple-photo, attend the elegant formal event.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Public-couple-beauty window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Mars on the body. Sexual charge peaks; bold approaches land. Watch the message-tone.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Body-fire window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the bold romantic move; pair speed with discipline.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Body-fire window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Mars on public-couple status. Bold couple-as-public-figure moves.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Public-couple-fire window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak day. Make the bold couple-public statement.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Public-couple-fire window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of personal-magnetism. The body reads as fuller, more attractive, more elder-warm.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the public-mantle that draws the right partner.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak public-couple expansion. Take the chief-couple offer, the prestige formal-event.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Public-couple-expansion window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak day. Accept the public-couple elevation.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Public-couple-expansion window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and self. Vanity-romance falls away; durable presence emerges.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Hold steady; what survives is permanent.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Saturn on public-couple status. Slow recognition; durable couple-foundation.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Public-couple-discipline window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day. The structural couple-recognition crystallizes.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Public-couple-discipline window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion. Foreign or unconventional self-magnetism emerges. Watch obsession.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window begins.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic public-couple expansion. Sudden public mantles, unconventional couple-positions.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Public-couple-reinvention window begins.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the bold couple-pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Public-couple-reinvention window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. Old persona-as-magnet feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Public-couple eclipse. Old formal-couple-mantle feels weightless.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Public-couple-eclipse window begins.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. The public-couple-role dissolves quietly. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Public-couple-eclipse window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting the long-arc relationship engine. Old marriage-templates collapse; the multi-year structural rebuild forges a permanent foundation. The partnership that survives this becomes legacy-grade.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on the marriage-engine. Old patterns dismantle.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak day. The old structure breaks; the rebuilt partnership emerges with permanent gravity.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Structural-transformation chapter completes. The new relationship-foundation is permanent.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the Venus-on-lagna magnetism. Unexpected attraction, abrupt aesthetic-pivot, surprise romantic-shift.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden romantic-disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak day. The unexpected attraction lands; the aesthetic-pivot is forced. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Romantic-disruption window closes. Integrate the changes.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 4th house', description: 'Solar fire on the home-throne in love. Family-meeting, real-estate-with-partner, mother-line approval window.' },
  { name: 'Sun aspect Sun in 4th house : Starts', description: 'Home-throne-love window opens.' },
  { name: 'Sun aspect Sun in 4th house : Exact', description: 'Peak day. Host the family, sign the joint property paper, take the mother-line conversation.' },
  { name: 'Sun aspect Sun in 4th house : Ends', description: 'Home-throne-love window closes.' },
  { name: 'Sun aspect Moon in 3rd house', description: 'Visibility through brave love-communication. The bold message, the candid conversation.' },
  { name: 'Sun aspect Moon in 3rd house : Starts', description: 'Brave-communication window opens.' },
  { name: 'Sun aspect Moon in 3rd house : Exact', description: 'Peak day. Send the brave note, take the candid call.' },
  { name: 'Sun aspect Moon in 3rd house : Ends', description: 'Brave-communication window closes.' },
  { name: 'Sun aspect Mercury in 5th house', description: 'Solar fire on romance and play. Witty dates, performance-tinged courtship, creative collaboration with romantic edge.' },
  { name: 'Sun aspect Mercury in 5th house : Starts', description: 'Play-window opens.' },
  { name: 'Sun aspect Mercury in 5th house : Exact', description: 'Peak day. Take the playful date, write the witty note.' },
  { name: 'Sun aspect Mercury in 5th house : Ends', description: 'Play-window closes.' },
  { name: 'Sun aspect Venus in 1st house', description: 'Solar fire on personal-magnetism. The face, body, voice, taste — all visibly luminous. Old admirers re-emerge.' },
  { name: 'Sun aspect Venus in 1st house : Starts', description: 'Magnetism window opens.' },
  { name: 'Sun aspect Venus in 1st house : Exact', description: 'Peak day. Show up where you want to be seen; the magnetism is solar-lit.' },
  { name: 'Sun aspect Venus in 1st house : Ends', description: 'Magnetism window closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Solar fire on the partnership engine. Anchor-deal visibility, JV declarations, public-facing contract moves with partner.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Partnership-fire window opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Peak day. Sign the JV-of-love, demand the relationship-terms.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Partnership-fire window closes.' },
  { name: 'Sun aspect Jupiter in 11th house', description: 'Solar fire on friend-circle as relationship-engine. International introductions, board-couple invitations, cooperative-platform romance.' },
  { name: 'Sun aspect Jupiter in 11th house : Starts', description: 'Friend-circle-fire window opens.' },
  { name: 'Sun aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the international intro, accept the friend-matchmaking.' },
  { name: 'Sun aspect Jupiter in 11th house : Ends', description: 'Friend-circle-fire window closes.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on the durable-couple engine. Public-mantle assumption together; couple-as-public-figure declarations.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Durable-couple window opens.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak day. Take the public-couple-elevation; declare the legacy partnership.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Durable-couple window closes.' },
  { name: 'Sun aspect Rahu in 8th house', description: 'Solar fire in the foreign-occult intimacy chamber. Joint-finance-event visibility; sex-and-secrecy clarification.' },
  { name: 'Sun aspect Rahu in 8th house : Starts', description: 'Intimacy-chamber window opens.' },
  { name: 'Sun aspect Rahu in 8th house : Exact', description: 'Peak day. Take the joint-finance move with full documentation.' },
  { name: 'Sun aspect Rahu in 8th house : Ends', description: 'Intimacy-chamber window closes.' },
  { name: 'Sun aspect Ketu in 2nd house', description: 'Solar light on detached-voice/family-money zone in love. Old earning-paths-with-partner feel finished.' },
  { name: 'Sun aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-love window opens.' },
  { name: 'Sun aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the family-money channel that has been hollow.' },
  { name: 'Sun aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-love window closes.' },
  { name: 'Moon aspect Sun in 4th house', description: 'Emotional charge on home-throne love. Mother-channel conversations about partner; real-estate read-outs.' },
  { name: 'Moon aspect Sun in 4th house : Starts', description: 'Home-emotion-love window opens.' },
  { name: 'Moon aspect Sun in 4th house : Exact', description: 'Peak day. Cook for the partner, host the family, sign the warm property paper.' },
  { name: 'Moon aspect Sun in 4th house : Ends', description: 'Home-emotion-love window closes.' },
  { name: 'Moon aspect Moon in 3rd house', description: 'Emotional courage in love-communication. The brave message; the candid sales call to the heart.' },
  { name: 'Moon aspect Moon in 3rd house : Starts', description: 'Communication-emotion window opens.' },
  { name: 'Moon aspect Moon in 3rd house : Exact', description: 'Peak day. Send the bold love-note.' },
  { name: 'Moon aspect Moon in 3rd house : Ends', description: 'Communication-emotion window closes.' },
  { name: 'Moon aspect Mercury in 5th house', description: 'Emotional charge on play and romance. The poetic gesture, the warm performance, the heart-led creative date.' },
  { name: 'Moon aspect Mercury in 5th house : Starts', description: 'Play-emotion window opens.' },
  { name: 'Moon aspect Mercury in 5th house : Exact', description: 'Peak day. Capture the warm draft of the love-letter.' },
  { name: 'Moon aspect Mercury in 5th house : Ends', description: 'Play-emotion window closes.' },
  { name: 'Moon aspect Venus in 1st house', description: 'Emotional charge on personal-magnetism. The warm-presence day; partners feel the heart through the body.' },
  { name: 'Moon aspect Venus in 1st house : Starts', description: 'Magnetism-emotion window opens.' },
  { name: 'Moon aspect Venus in 1st house : Exact', description: 'Peak day. Show up warm; the magnetism is heart-led today.' },
  { name: 'Moon aspect Venus in 1st house : Ends', description: 'Magnetism-emotion window closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge on the partnership engine. Read the partner\'s temperature; soften the deal-tone.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Partnership-emotion window opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Peak day. Lead with warmth in the partner-meeting; defuse before debating.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Partnership-emotion window closes.' },
  { name: 'Moon aspect Jupiter in 11th house', description: 'Emotional warmth in friend-circle. International friend-call, board-couple warmth, cooperative-platform heart.' },
  { name: 'Moon aspect Jupiter in 11th house : Starts', description: 'Friend-circle-emotion window opens.' },
  { name: 'Moon aspect Jupiter in 11th house : Exact', description: 'Peak day. Reach out to the long-arc international friend.' },
  { name: 'Moon aspect Jupiter in 11th house : Ends', description: 'Friend-circle-emotion window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on durable-couple status. Senior-network warmth around the long-arc partnership.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Durable-couple-emotion window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day. Take the warm-toned senior-couple call.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Durable-couple-emotion window closes.' },
  { name: 'Moon aspect Rahu in 8th house', description: 'Emotional charge in the intimacy-chamber. Old fears about loyalty surface; process gently.' },
  { name: 'Moon aspect Rahu in 8th house : Starts', description: 'Intimacy-emotion window opens.' },
  { name: 'Moon aspect Rahu in 8th house : Exact', description: 'Peak day. Defer joint-finance moves two days; let the emotion settle.' },
  { name: 'Moon aspect Rahu in 8th house : Ends', description: 'Intimacy-emotion window closes.' },
  { name: 'Moon aspect Ketu in 2nd house', description: 'Emotional detachment from voice / family-money. Old earning-paths-with-partner feel hollow; cravings dissolve.' },
  { name: 'Moon aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-emotion window opens.' },
  { name: 'Moon aspect Ketu in 2nd house : Exact', description: 'Peak day. Sit with the income-paths feeling weightless; do not panic-pivot.' },
  { name: 'Moon aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-emotion window closes.' },
  { name: 'Mercury aspect Sun in 4th house', description: 'Sharp articulation of home-throne love. Real-estate paperwork, family-business memo, mother-channel correspondence.' },
  { name: 'Mercury aspect Sun in 4th house : Starts', description: 'Home-articulation window opens.' },
  { name: 'Mercury aspect Sun in 4th house : Exact', description: 'Peak day. Send the property memo, write the warm mother-channel note.' },
  { name: 'Mercury aspect Sun in 4th house : Ends', description: 'Home-articulation window closes.' },
  { name: 'Mercury aspect Moon in 3rd house', description: 'Sharp courage-communication. Bold love-messages, brave candid notes, sibling-channel love-campaigns.' },
  { name: 'Mercury aspect Moon in 3rd house : Starts', description: 'Courage-articulation window opens.' },
  { name: 'Mercury aspect Moon in 3rd house : Exact', description: 'Peak day. Send the bold love-sequence.' },
  { name: 'Mercury aspect Moon in 3rd house : Ends', description: 'Courage-articulation window closes.' },
  { name: 'Mercury aspect Mercury in 5th house', description: 'Mercury\'s exalted return on the romance throne. Peak witty-courtship day. Polished love-letters, performance-grade banter, masterpiece flirtation.' },
  { name: 'Mercury aspect Mercury in 5th house : Starts', description: 'Exalted-romance window opens. Plan the masterpiece courtship.' },
  { name: 'Mercury aspect Mercury in 5th house : Exact', description: 'Peak day. Send the polished love-letter; the wit is at its sharpest annual setting.' },
  { name: 'Mercury aspect Mercury in 5th house : Ends', description: 'Exalted-romance window closes. Lock in romantic commitments.' },
  { name: 'Mercury aspect Venus in 1st house', description: 'Sharp personal-brand-articulation in love. Bio refresh, dating-profile polish, founder-couple narrative.' },
  { name: 'Mercury aspect Venus in 1st house : Starts', description: 'Self-articulation-love window opens.' },
  { name: 'Mercury aspect Venus in 1st house : Exact', description: 'Peak day. Publish the polished bio, send the brand-of-self love-message.' },
  { name: 'Mercury aspect Venus in 1st house : Ends', description: 'Self-articulation-love window closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Sharp partnership-articulation. Term sheets, JV memos, written-vows, contractual love.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Partnership-articulation window opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Peak day. Send the term sheet, sign the partnership memo.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Partnership-articulation window closes.' },
  { name: 'Mercury aspect Jupiter in 11th house', description: 'Sharp friend-circle articulation. International newsletters, cooperative-platform invites, board-couple memos.' },
  { name: 'Mercury aspect Jupiter in 11th house : Starts', description: 'Friend-articulation window opens.' },
  { name: 'Mercury aspect Jupiter in 11th house : Exact', description: 'Peak day. Send the international friend-circle update.' },
  { name: 'Mercury aspect Jupiter in 11th house : Ends', description: 'Friend-articulation window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Sharp durable-couple articulation. Public-mantle press, prestige-couple announcements.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Durable-couple-articulation window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day. Issue the formal couple-status update.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Durable-couple-articulation window closes.' },
  { name: 'Mercury aspect Rahu in 8th house', description: 'Sharp intimacy-chamber articulation. Joint-finance memos, will-and-trust paperwork, sex-and-secrecy conversations.' },
  { name: 'Mercury aspect Rahu in 8th house : Starts', description: 'Intimacy-articulation window opens.' },
  { name: 'Mercury aspect Rahu in 8th house : Exact', description: 'Peak day. Document the joint-finance precisely; the paperwork is your protection.' },
  { name: 'Mercury aspect Rahu in 8th house : Ends', description: 'Intimacy-articulation window closes.' },
  { name: 'Mercury aspect Ketu in 2nd house', description: 'Sharp voice-detachment articulation. Audit the family-money channel; write the closure-of-old-channel memo.' },
  { name: 'Mercury aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-articulation window opens.' },
  { name: 'Mercury aspect Ketu in 2nd house : Exact', description: 'Peak day. Write the closure note for the dead family-money channel.' },
  { name: 'Mercury aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-articulation window closes.' },
  { name: 'Venus aspect Sun in 4th house', description: 'Beauty on home-throne love. Aesthetic upgrades to the shared space, family-business diplomacy, warm mother-channel.' },
  { name: 'Venus aspect Sun in 4th house : Starts', description: 'Home-beauty-love window opens.' },
  { name: 'Venus aspect Sun in 4th house : Exact', description: 'Peak day. Soften the property negotiation, host the elegant family meeting.' },
  { name: 'Venus aspect Sun in 4th house : Ends', description: 'Home-beauty-love window closes.' },
  { name: 'Venus aspect Moon in 3rd house', description: 'Beauty on courageous communication in love. Tone the bold message; soften the brave candid call.' },
  { name: 'Venus aspect Moon in 3rd house : Starts', description: 'Communication-beauty window opens.' },
  { name: 'Venus aspect Moon in 3rd house : Exact', description: 'Peak day. Send the elegantly-worded brave note.' },
  { name: 'Venus aspect Moon in 3rd house : Ends', description: 'Communication-beauty window closes.' },
  { name: 'Venus aspect Mercury in 5th house', description: 'Beauty on romance and play. Performance-aesthetics, course-design romance, speculative-creative-pitch elegance to the heart.' },
  { name: 'Venus aspect Mercury in 5th house : Starts', description: 'Romance-beauty window opens.' },
  { name: 'Venus aspect Mercury in 5th house : Exact', description: 'Peak day. Polish the performance, redesign the date, present with elegant analytic.' },
  { name: 'Venus aspect Mercury in 5th house : Ends', description: 'Romance-beauty window closes.' },
  { name: 'Venus aspect Venus in 1st house', description: 'Venus on its Malavya throne. Peak personal-magnetism day of the year. The face, body, voice, taste — at peak warm setting.' },
  { name: 'Venus aspect Venus in 1st house : Starts', description: 'Malavya-window opens. Plan the founder-as-product launch in love.' },
  { name: 'Venus aspect Venus in 1st house : Exact', description: 'Peak Malavya day. Show up where you want to be seen; the magnetism is at peak yearly setting.' },
  { name: 'Venus aspect Venus in 1st house : Ends', description: 'Malavya-window closes. Lock in attraction-into-commitment.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Beauty on the partnership engine. Mediated JV diplomacy, anchor-deal warmth, spouse-and-counterparty softening.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Partnership-beauty window opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Peak day. Sign the warm JV-of-love, mediate the partner-standoff.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Partnership-beauty window closes.' },
  { name: 'Venus aspect Jupiter in 11th house', description: 'Beauty on friend-circle. Cooperative-platform diplomacy, international-friend warmth, board-couple grace.' },
  { name: 'Venus aspect Jupiter in 11th house : Starts', description: 'Friend-beauty window opens.' },
  { name: 'Venus aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the international-friend call, attend the cooperative-platform gala.' },
  { name: 'Venus aspect Jupiter in 11th house : Ends', description: 'Friend-beauty window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Beauty on the durable-couple engine. Senior-network couple-charm, structural-authority diplomacy, public-couple-elegance.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Durable-couple-beauty window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day. Take the senior-couple meeting, present the prestige-couple pitch.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Durable-couple-beauty window closes.' },
  { name: 'Venus aspect Rahu in 8th house', description: 'Beauty in the intimacy-chamber. Sexual warmth, joint-finance softening, foreign-occult intimacy with grace.' },
  { name: 'Venus aspect Rahu in 8th house : Starts', description: 'Intimacy-beauty window opens.' },
  { name: 'Venus aspect Rahu in 8th house : Exact', description: 'Peak day. Take the elegant intimate meeting; verify the bedrock under the gloss.' },
  { name: 'Venus aspect Rahu in 8th house : Ends', description: 'Intimacy-beauty window closes.' },
  { name: 'Venus aspect Ketu in 2nd house', description: 'Beauty on voice-detachment in love. Old family-money channels feel weightless; speak less to gain more.' },
  { name: 'Venus aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-beauty window opens.' },
  { name: 'Venus aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the family-money channel that has been hollow.' },
  { name: 'Venus aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-beauty window closes.' },
  { name: 'Mars aspect Sun in 4th house', description: 'Mars on home-throne love. Property disputes with partner, family-business friction, real-estate aggression. Don\'t fight family in heat.' },
  { name: 'Mars aspect Sun in 4th house : Starts', description: 'Home-fire-love window opens.' },
  { name: 'Mars aspect Sun in 4th house : Exact', description: 'Peak day. Defer family confrontation two days.' },
  { name: 'Mars aspect Sun in 4th house : Ends', description: 'Home-fire-love window closes.' },
  { name: 'Mars aspect Moon in 3rd house', description: 'Mars on courageous communication in love. Bold message-pushes, brave candid demands, fierce campaigns.' },
  { name: 'Mars aspect Moon in 3rd house : Starts', description: 'Courage-fire window opens.' },
  { name: 'Mars aspect Moon in 3rd house : Exact', description: 'Peak day. Push the candid talk; send the contested love-note.' },
  { name: 'Mars aspect Moon in 3rd house : Ends', description: 'Courage-fire window closes.' },
  { name: 'Mars aspect Mercury in 5th house', description: 'Mars on romance and play. Bold first-moves, contested dating, fierce courtship.' },
  { name: 'Mars aspect Mercury in 5th house : Starts', description: 'Romance-fire window opens.' },
  { name: 'Mars aspect Mercury in 5th house : Exact', description: 'Peak day. Make the bold first-move.' },
  { name: 'Mars aspect Mercury in 5th house : Ends', description: 'Romance-fire window closes.' },
  { name: 'Mars aspect Venus in 1st house', description: 'Mars on personal-magnetism. Bold founder-of-self moves, contested aesthetic pivots, sexual charge in self-presentation.' },
  { name: 'Mars aspect Venus in 1st house : Starts', description: 'Magnetism-fire window opens.' },
  { name: 'Mars aspect Venus in 1st house : Exact', description: 'Peak day. Take the bold romantic move; pair speed with discipline.' },
  { name: 'Mars aspect Venus in 1st house : Ends', description: 'Magnetism-fire window closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Mars on its own throne (Scorpio 7H — Ruchaka activation). Peak partnership-fire day of the year. Sign the JV-of-love, divorce the dead deal, demand the partnership clarity.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Ruchaka-window opens. Prepare the bold partnership move.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Peak Ruchaka day. The deal is signed, the standoff broken, the JV forced to clarity.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Ruchaka-window closes. Lock in contractual love-commitments.' },
  { name: 'Mars aspect Jupiter in 11th house', description: 'Mars on friend-circle. Bold cooperative-platform combat, contested friend-matchmaking, board-friend disputes.' },
  { name: 'Mars aspect Jupiter in 11th house : Starts', description: 'Friend-fire window opens.' },
  { name: 'Mars aspect Jupiter in 11th house : Exact', description: 'Peak day. Push the international-network move; contest the friend-matchmaking.' },
  { name: 'Mars aspect Jupiter in 11th house : Ends', description: 'Friend-fire window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Mars on durable-couple status. Bold public-couple combat, contested formal-event positions, structural-couple combat.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Durable-couple-fire window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day. Force the structural-couple conversation.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Durable-couple-fire window closes.' },
  { name: 'Mars aspect Rahu in 8th house', description: 'Mars in the intimacy-chamber. Surgical action on joint-finance, force-plays in restructuring, fierce opaque-deal navigation in love.' },
  { name: 'Mars aspect Rahu in 8th house : Starts', description: 'Intimacy-fire window opens. Verify integrity before fighting.' },
  { name: 'Mars aspect Rahu in 8th house : Exact', description: 'Peak day. Take the surgical joint-finance action with full documentation.' },
  { name: 'Mars aspect Rahu in 8th house : Ends', description: 'Intimacy-fire window closes.' },
  { name: 'Mars aspect Ketu in 2nd house', description: 'Mars on voice-detachment in love. Sudden family-money disputes; old voice-channels detonate.' },
  { name: 'Mars aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-fire window opens.' },
  { name: 'Mars aspect Ketu in 2nd house : Exact', description: 'Peak day. Forcefully close the dead family-money channel.' },
  { name: 'Mars aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-fire window closes.' },
  { name: 'Jupiter aspect Sun in 4th house', description: 'Wisdom-expansion of the home-throne in love. Real-estate-with-partner gains, family-business-couple expansion.' },
  { name: 'Jupiter aspect Sun in 4th house : Starts', description: 'Home-expansion-love window opens.' },
  { name: 'Jupiter aspect Sun in 4th house : Exact', description: 'Peak day. Acquire property with partner, expand the family-business couple, take the mother-line inflection.' },
  { name: 'Jupiter aspect Sun in 4th house : Ends', description: 'Home-expansion-love window closes.' },
  { name: 'Jupiter aspect Moon in 3rd house', description: 'Wisdom on courageous love-communication. Publishing-with-partner, broadcast-couple, sibling-channel growth.' },
  { name: 'Jupiter aspect Moon in 3rd house : Starts', description: 'Communication-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 3rd house : Exact', description: 'Peak day. Publish the book together, accept the broadcast-couple-platform.' },
  { name: 'Jupiter aspect Moon in 3rd house : Ends', description: 'Communication-expansion window closes.' },
  { name: 'Jupiter aspect Mercury in 5th house', description: 'Wisdom on romance and children. Engagement, marriage, conception, creative-child-with-partner.' },
  { name: 'Jupiter aspect Mercury in 5th house : Starts', description: 'Romance-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 5th house : Exact', description: 'Peak day. Propose, accept, conceive, formalize the romance.' },
  { name: 'Jupiter aspect Mercury in 5th house : Ends', description: 'Romance-expansion window closes.' },
  { name: 'Jupiter aspect Venus in 1st house', description: 'Wisdom on personal-magnetism. Founder-as-product elevation in love; public-face role expansion.' },
  { name: 'Jupiter aspect Venus in 1st house : Starts', description: 'Magnetism-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 1st house : Exact', description: 'Peak day. Accept the public-face elevation that draws the right partner.' },
  { name: 'Jupiter aspect Venus in 1st house : Ends', description: 'Magnetism-expansion window closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Wisdom on the partnership engine. Anchor-deal expansion, JV-of-love elevation, marriage-and-equity-partner inflection.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Partnership-expansion window opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak day. Sign the elevated JV-of-love; accept the marriage-or-merger inflection.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Partnership-expansion window closes.' },
  { name: 'Jupiter aspect Jupiter in 11th house', description: 'Jupiter on its own throne (Pisces 11H). Peak friend-circle gain day of the cycle. International friend-matchmaking peaks; cooperative-platform romance compounds.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Starts', description: 'Friend-circle-gain window opens.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the international-friend matchmaking; accept the cooperative-platform romance.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Ends', description: 'Friend-circle-gain window closes.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on the durable-couple engine. Chief-of-something-couple offers, prestige-role acceptance, board-couple appointments.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Durable-couple-expansion window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day. Accept the public-couple-elevation; formalize the legacy-grade marriage.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Durable-couple-expansion window closes.' },
  { name: 'Jupiter aspect Rahu in 8th house', description: 'Wisdom on the intimacy-chamber. Inheritance-windfalls together, joint-finance gains, occult-research royalty for the couple. Jupiter sanctifies the opaque.' },
  { name: 'Jupiter aspect Rahu in 8th house : Starts', description: 'Intimacy-expansion window opens.' },
  { name: 'Jupiter aspect Rahu in 8th house : Exact', description: 'Peak day. Take the joint-finance windfall, accept the inheritance settlement together.' },
  { name: 'Jupiter aspect Rahu in 8th house : Ends', description: 'Intimacy-expansion window closes.' },
  { name: 'Jupiter aspect Ketu in 2nd house', description: 'Wisdom on voice-detachment in love. The dead family-money channel graduates into a teaching-of-the-lesson; speak less, monetize the wisdom.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-expansion window opens.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Exact', description: 'Peak day. Convert the abandoned earning channel into a teaching artifact for the couple.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-expansion window closes.' },
  { name: 'Saturn aspect Sun in 4th house', description: 'Structural pressure on the home-throne. Real-estate restructuring with partner, family-business reckoning, mother-line as long-arc concern.' },
  { name: 'Saturn aspect Sun in 4th house : Starts', description: 'Home-discipline-love window opens.' },
  { name: 'Saturn aspect Sun in 4th house : Exact', description: 'Peak day. Take the slow real-estate decision with partner; restructure the family-business couple.' },
  { name: 'Saturn aspect Sun in 4th house : Ends', description: 'Home-discipline-love window closes.' },
  { name: 'Saturn aspect Moon in 3rd house', description: 'Structural pressure on courageous communication. Long-arc message-systems with partner; sibling-channel formalization.' },
  { name: 'Saturn aspect Moon in 3rd house : Starts', description: 'Communication-discipline window opens.' },
  { name: 'Saturn aspect Moon in 3rd house : Exact', description: 'Peak day. Lock in the multi-year communication rhythm with partner.' },
  { name: 'Saturn aspect Moon in 3rd house : Ends', description: 'Communication-discipline window closes.' },
  { name: 'Saturn aspect Mercury in 5th house', description: 'Structural pressure on romance and children. The slow courtship; the long conception chapter; the patient creative-child-with-partner.' },
  { name: 'Saturn aspect Mercury in 5th house : Starts', description: 'Romance-discipline window opens.' },
  { name: 'Saturn aspect Mercury in 5th house : Exact', description: 'Peak day. Commit to the multi-year romantic project; lock in the long-courtship structure.' },
  { name: 'Saturn aspect Mercury in 5th house : Ends', description: 'Romance-discipline window closes.' },
  { name: 'Saturn aspect Venus in 1st house', description: 'Structural pressure on personal-magnetism. Slow self-evolution; vanity-romance falls away; the durable presence sets in.' },
  { name: 'Saturn aspect Venus in 1st house : Starts', description: 'Magnetism-discipline window opens.' },
  { name: 'Saturn aspect Venus in 1st house : Exact', description: 'Peak day. Eliminate the vanity-romance commitments; lock in the durable self-presentation.' },
  { name: 'Saturn aspect Venus in 1st house : Ends', description: 'Magnetism-discipline window closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Structural pressure on the partnership engine. Spouse-commitments scrutinized; weak deals end; strong ones formalize into 30-year structures.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Partnership-discipline window opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Peak day. Divorce the weak deal, formalize the strong JV-of-love, lock in the 30-year partnership.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Partnership-discipline window closes.' },
  { name: 'Saturn aspect Jupiter in 11th house', description: 'Structural pressure on the friend-network. Cooperative platforms formalize; international friend-circles deepen; board-couple consolidates.' },
  { name: 'Saturn aspect Jupiter in 11th house : Starts', description: 'Friend-discipline window opens.' },
  { name: 'Saturn aspect Jupiter in 11th house : Exact', description: 'Peak day. Sign the cooperative-platform charter; formalize the international friend-circle.' },
  { name: 'Saturn aspect Jupiter in 11th house : Ends', description: 'Friend-discipline window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Saturn on its own Sasa throne. Peak structural-couple day of the multi-decade cycle. Chief-of-something-couple crystallizes; legacy-grade marriage sets in permanently.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Sasa-Yoga peak window opens.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak Sasa day. Accept the public-couple-mantle; declare the legacy-grade partnership.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Sasa-Yoga peak window closes.' },
  { name: 'Saturn aspect Rahu in 8th house', description: 'Structural pressure in the intimacy-chamber. Inheritance disputes, joint-finance restructuring, foreign-occult navigation. Patience pays.' },
  { name: 'Saturn aspect Rahu in 8th house : Starts', description: 'Intimacy-discipline window opens.' },
  { name: 'Saturn aspect Rahu in 8th house : Exact', description: 'Peak day. Hold the line on slow joint-finance restructuring.' },
  { name: 'Saturn aspect Rahu in 8th house : Ends', description: 'Intimacy-discipline window closes.' },
  { name: 'Saturn aspect Ketu in 2nd house', description: 'Structural pressure on voice-detachment. Old family-money channels formally close; the structural release is documented.' },
  { name: 'Saturn aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-discipline window opens.' },
  { name: 'Saturn aspect Ketu in 2nd house : Exact', description: 'Peak day. Sign the formal closure of the dead family-money channel.' },
  { name: 'Saturn aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-discipline window closes.' },
  { name: 'Rahu aspect Sun in 4th house', description: 'Chaotic expansion on home-throne love. Foreign-property pull with partner, family-business reinvention.' },
  { name: 'Rahu aspect Sun in 4th house : Starts', description: 'Home-chaos-love window opens.' },
  { name: 'Rahu aspect Sun in 4th house : Exact', description: 'Peak day. Vet the foreign-property paperwork before signing.' },
  { name: 'Rahu aspect Sun in 4th house : Ends', description: 'Home-chaos-love window closes.' },
  { name: 'Rahu aspect Moon in 3rd house', description: 'Chaotic expansion on courageous communication. Viral love-content, controversial sibling-channel moves.' },
  { name: 'Rahu aspect Moon in 3rd house : Starts', description: 'Communication-chaos window opens.' },
  { name: 'Rahu aspect Moon in 3rd house : Exact', description: 'Peak day. Push the viral love-message — but check integrity twice.' },
  { name: 'Rahu aspect Moon in 3rd house : Ends', description: 'Communication-chaos window closes.' },
  { name: 'Rahu aspect Mercury in 5th house', description: 'Chaotic expansion on romance. Speculation in love, viral first-meetings, controversial public-stage romance.' },
  { name: 'Rahu aspect Mercury in 5th house : Starts', description: 'Romance-chaos window opens.' },
  { name: 'Rahu aspect Mercury in 5th house : Exact', description: 'Peak day. Take the speculative-romance move with full ethical-bedrock check.' },
  { name: 'Rahu aspect Mercury in 5th house : Ends', description: 'Romance-chaos window closes.' },
  { name: 'Rahu aspect Venus in 1st house', description: 'Chaotic expansion on personal-magnetism. Viral founder-of-self moments, sudden aesthetic-pivots, controversial public-face shifts.' },
  { name: 'Rahu aspect Venus in 1st house : Starts', description: 'Magnetism-chaos window opens.' },
  { name: 'Rahu aspect Venus in 1st house : Exact', description: 'Peak day. Take the bold aesthetic-pivot — verify the underlying integrity.' },
  { name: 'Rahu aspect Venus in 1st house : Ends', description: 'Magnetism-chaos window closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic expansion on the partnership engine. Foreign spouse, controversial JV, sudden anchor-counterparty.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Partnership-chaos window opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Peak day. Vet the controversial JV thoroughly.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Partnership-chaos window closes.' },
  { name: 'Rahu aspect Jupiter in 11th house', description: 'Chaotic expansion on friend-circle. Sudden viral-network gains, controversial cooperative-platforms in love.' },
  { name: 'Rahu aspect Jupiter in 11th house : Starts', description: 'Friend-chaos window opens.' },
  { name: 'Rahu aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the viral-network move — verify ethical bedrock.' },
  { name: 'Rahu aspect Jupiter in 11th house : Ends', description: 'Friend-chaos window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Chaotic expansion on durable-couple status. Sudden public mantles, unconventional couple-positions.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Durable-couple-chaos window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day. Take the unconventional couple-pivot — verify the institutional bedrock.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Durable-couple-chaos window closes.' },
  { name: 'Rahu aspect Rahu in 8th house', description: 'Rahu return on its strong terrain (8H). Peak intimacy-chaos day. Joint-finance windfalls, inheritance chaos, foreign-occult breakthroughs.' },
  { name: 'Rahu aspect Rahu in 8th house : Starts', description: 'Rahu-return window opens.' },
  { name: 'Rahu aspect Rahu in 8th house : Exact', description: 'Peak Rahu-return day. Take the joint-finance move with full documentation.' },
  { name: 'Rahu aspect Rahu in 8th house : Ends', description: 'Rahu-return window closes.' },
  { name: 'Rahu aspect Ketu in 2nd house', description: 'Chaotic expansion on voice-detachment — Rahu-Ketu axis stress. Sudden family-money turbulence in love.' },
  { name: 'Rahu aspect Ketu in 2nd house : Starts', description: 'Axis-chaos window opens.' },
  { name: 'Rahu aspect Ketu in 2nd house : Exact', description: 'Peak day. Defer voice-channel decisions; the axis is too loud.' },
  { name: 'Rahu aspect Ketu in 2nd house : Ends', description: 'Axis-chaos window closes.' },
  { name: 'Ketu aspect Sun in 4th house', description: 'Detachment on home-throne love. Old real-estate-with-partner plans feel weightless; family-business attachment dissolves.' },
  { name: 'Ketu aspect Sun in 4th house : Starts', description: 'Home-detachment window opens.' },
  { name: 'Ketu aspect Sun in 4th house : Exact', description: 'Peak day. Sit with the home-throne feeling weightless; do not panic-sell.' },
  { name: 'Ketu aspect Sun in 4th house : Ends', description: 'Home-detachment window closes.' },
  { name: 'Ketu aspect Moon in 3rd house', description: 'Detachment on courageous love-communication. Old message-loops feel finished.' },
  { name: 'Ketu aspect Moon in 3rd house : Starts', description: 'Communication-detachment window opens.' },
  { name: 'Ketu aspect Moon in 3rd house : Exact', description: 'Peak day. Release the message-loop that feels dead.' },
  { name: 'Ketu aspect Moon in 3rd house : Ends', description: 'Communication-detachment window closes.' },
  { name: 'Ketu aspect Mercury in 5th house', description: 'Detachment on romance. Old courtship-loops feel finished; speculative-love cravings fall away.' },
  { name: 'Ketu aspect Mercury in 5th house : Starts', description: 'Romance-detachment window opens.' },
  { name: 'Ketu aspect Mercury in 5th house : Exact', description: 'Peak day. Release the dead romance-loop; the field is clearing.' },
  { name: 'Ketu aspect Mercury in 5th house : Ends', description: 'Romance-detachment window closes.' },
  { name: 'Ketu aspect Venus in 1st house', description: 'Detachment on personal-magnetism. Old founder-of-self persona feels hollow; the magnetism quiets.' },
  { name: 'Ketu aspect Venus in 1st house : Starts', description: 'Magnetism-detachment window opens.' },
  { name: 'Ketu aspect Venus in 1st house : Exact', description: 'Peak day. Sit with the magnetism feeling weightless; do not over-perform.' },
  { name: 'Ketu aspect Venus in 1st house : Ends', description: 'Magnetism-detachment window closes.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Detachment on the partnership engine. Old deal feels finished; spouse / principal-counterparty dynamic loosens.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Partnership-detachment window opens.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Peak day. Release the dead deal; the partnership has graduated.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Partnership-detachment window closes.' },
  { name: 'Ketu aspect Jupiter in 11th house', description: 'Detachment on friend-circle. Old friend-network drifts; cooperative-platform around love quiets.' },
  { name: 'Ketu aspect Jupiter in 11th house : Starts', description: 'Friend-detachment window opens.' },
  { name: 'Ketu aspect Jupiter in 11th house : Exact', description: 'Peak day. Release the friend-circle that has run its course.' },
  { name: 'Ketu aspect Jupiter in 11th house : Ends', description: 'Friend-detachment window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Detachment on durable-couple status. Old public-couple mantle feels weightless; the formal role feels like a costume.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Public-couple-eclipse window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day. Sit with the formal-couple-role feeling hollow.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Public-couple-eclipse window closes.' },
  { name: 'Ketu aspect Rahu in 8th house', description: 'Detachment on the intimacy-chamber — Rahu-Ketu axis stress. Old crisis-loops dissolve.' },
  { name: 'Ketu aspect Rahu in 8th house : Starts', description: 'Axis-detachment window opens.' },
  { name: 'Ketu aspect Rahu in 8th house : Exact', description: 'Peak day. Release the crisis that has been the engine.' },
  { name: 'Ketu aspect Rahu in 8th house : Ends', description: 'Axis-detachment window closes.' },
  { name: 'Ketu aspect Ketu in 2nd house', description: 'Ketu return on voice-detachment. Old family-money channels formally close; cravings dissolve.' },
  { name: 'Ketu aspect Ketu in 2nd house : Starts', description: 'Ketu-return window opens.' },
  { name: 'Ketu aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the family-money channel that has been hollow for years.' },
  { name: 'Ketu aspect Ketu in 2nd house : Ends', description: 'Ketu-return window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} relationship] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
