// db/seed_food_capricorn.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to the
// user with:
//   Ascendant: Capricorn
//   Natal placements (sidereal Lahiri):
//     Sun=8th  Moon=10th  Mercury=8th  Venus=7th  Mars=9th
//     Jupiter=8th  Saturn=1st  Rahu=12th  Ketu=6th
//
// All 530 events below are the ones the kerykeion engine could emit for
// this user across any transitDate, narrowed from the full per-ascendant
// enumeration (~4,328 names) by the natal chart. Fill in the `description`
// strings as you compose food-specific interpretations, then run:
//
//   node db/seed_food_capricorn.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.
// Re-running with a filled description overwrites the existing row.

const db = require('./food');

const ASCENDANT = 'Capricorn';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS — fixed by ascendant + natal positions (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter ruler of the 12th House in the 8th House', description: '' },
  { name: 'Jupiter ruler of the 3rd House in the 8th House', description: '' },
  { name: 'Mars ruler of the 11th House in the 9th House', description: '' },
  { name: 'Mars ruler of the 4th House in the 9th House', description: '' },
  { name: 'Mercury ruler of the 6th House in the 8th House', description: '' },
  { name: 'Mercury ruler of the 9th House in the 8th House', description: '' },
  { name: 'Moon ruler of the 7th House in the 10th House', description: '' },
  { name: 'Saturn ruler of the 1st House in the 1st House', description: '' },
  { name: 'Saturn ruler of the 2nd House in the 1st House', description: '' },
  { name: 'Sun ruler of the 8th House in the 8th House', description: '' },
  { name: 'Venus ruler of the 10th House in the 7th House', description: '' },
  { name: 'Venus ruler of the 5th House in the 7th House', description: '' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS — sign-lord placements (deduped) (6)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter in 8th (Dispositor)', description: '' },
  { name: 'Mercury in 8th (Dispositor)', description: '' },
  { name: 'Moon in 10th (Dispositor)', description: '' },
  { name: 'Saturn in 1st (Dispositor)', description: '' },
  { name: 'Sun in 8th (Dispositor)', description: '' },
  { name: 'Venus in 7th (Dispositor)', description: '' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS — every planet through every house (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter Transits the 10th House', description: '' },
  { name: 'Jupiter Transits the 11th House', description: '' },
  { name: 'Jupiter Transits the 12th House', description: '' },
  { name: 'Jupiter Transits the 1st House', description: '' },
  { name: 'Jupiter Transits the 2nd House', description: '' },
  { name: 'Jupiter Transits the 3rd House', description: '' },
  { name: 'Jupiter Transits the 4th House', description: '' },
  { name: 'Jupiter Transits the 5th House', description: '' },
  { name: 'Jupiter Transits the 6th House', description: '' },
  { name: 'Jupiter Transits the 7th House', description: '' },
  { name: 'Jupiter Transits the 8th House', description: '' },
  { name: 'Jupiter Transits the 9th House', description: '' },
  { name: 'Ketu Transits the 10th House', description: '' },
  { name: 'Ketu Transits the 11th House', description: '' },
  { name: 'Ketu Transits the 12th House', description: '' },
  { name: 'Ketu Transits the 1st House', description: '' },
  { name: 'Ketu Transits the 2nd House', description: '' },
  { name: 'Ketu Transits the 3rd House', description: '' },
  { name: 'Ketu Transits the 4th House', description: '' },
  { name: 'Ketu Transits the 5th House', description: '' },
  { name: 'Ketu Transits the 6th House', description: '' },
  { name: 'Ketu Transits the 7th House', description: '' },
  { name: 'Ketu Transits the 8th House', description: '' },
  { name: 'Ketu Transits the 9th House', description: '' },
  { name: 'Mars Transits the 10th House', description: '' },
  { name: 'Mars Transits the 11th House', description: '' },
  { name: 'Mars Transits the 12th House', description: '' },
  { name: 'Mars Transits the 1st House', description: '' },
  { name: 'Mars Transits the 2nd House', description: '' },
  { name: 'Mars Transits the 3rd House', description: '' },
  { name: 'Mars Transits the 4th House', description: '' },
  { name: 'Mars Transits the 5th House', description: '' },
  { name: 'Mars Transits the 6th House', description: '' },
  { name: 'Mars Transits the 7th House', description: '' },
  { name: 'Mars Transits the 8th House', description: '' },
  { name: 'Mars Transits the 9th House', description: '' },
  { name: 'Mercury Transits the 10th House', description: '' },
  { name: 'Mercury Transits the 11th House', description: '' },
  { name: 'Mercury Transits the 12th House', description: '' },
  { name: 'Mercury Transits the 1st House', description: '' },
  { name: 'Mercury Transits the 2nd House', description: '' },
  { name: 'Mercury Transits the 3rd House', description: '' },
  { name: 'Mercury Transits the 4th House', description: '' },
  { name: 'Mercury Transits the 5th House', description: '' },
  { name: 'Mercury Transits the 6th House', description: '' },
  { name: 'Mercury Transits the 7th House', description: '' },
  { name: 'Mercury Transits the 8th House', description: '' },
  { name: 'Mercury Transits the 9th House', description: '' },
  { name: 'Moon Transits the 10th House', description: '' },
  { name: 'Moon Transits the 11th House', description: '' },
  { name: 'Moon Transits the 12th House', description: '' },
  { name: 'Moon Transits the 1st House', description: '' },
  { name: 'Moon Transits the 2nd House', description: '' },
  { name: 'Moon Transits the 3rd House', description: '' },
  { name: 'Moon Transits the 4th House', description: '' },
  { name: 'Moon Transits the 5th House', description: '' },
  { name: 'Moon Transits the 6th House', description: '' },
  { name: 'Moon Transits the 7th House', description: '' },
  { name: 'Moon Transits the 8th House', description: '' },
  { name: 'Moon Transits the 9th House', description: '' },
  { name: 'Rahu Transits the 10th House', description: '' },
  { name: 'Rahu Transits the 11th House', description: '' },
  { name: 'Rahu Transits the 12th House', description: '' },
  { name: 'Rahu Transits the 1st House', description: '' },
  { name: 'Rahu Transits the 2nd House', description: '' },
  { name: 'Rahu Transits the 3rd House', description: '' },
  { name: 'Rahu Transits the 4th House', description: '' },
  { name: 'Rahu Transits the 5th House', description: '' },
  { name: 'Rahu Transits the 6th House', description: '' },
  { name: 'Rahu Transits the 7th House', description: '' },
  { name: 'Rahu Transits the 8th House', description: '' },
  { name: 'Rahu Transits the 9th House', description: '' },
  { name: 'Saturn Transits the 10th House', description: '' },
  { name: 'Saturn Transits the 11th House', description: '' },
  { name: 'Saturn Transits the 12th House', description: '' },
  { name: 'Saturn Transits the 1st House', description: '' },
  { name: 'Saturn Transits the 2nd House', description: '' },
  { name: 'Saturn Transits the 3rd House', description: '' },
  { name: 'Saturn Transits the 4th House', description: '' },
  { name: 'Saturn Transits the 5th House', description: '' },
  { name: 'Saturn Transits the 6th House', description: '' },
  { name: 'Saturn Transits the 7th House', description: '' },
  { name: 'Saturn Transits the 8th House', description: '' },
  { name: 'Saturn Transits the 9th House', description: '' },
  { name: 'Sun Transits the 10th House', description: '' },
  { name: 'Sun Transits the 11th House', description: '' },
  { name: 'Sun Transits the 12th House', description: '' },
  { name: 'Sun Transits the 1st House', description: '' },
  { name: 'Sun Transits the 2nd House', description: '' },
  { name: 'Sun Transits the 3rd House', description: '' },
  { name: 'Sun Transits the 4th House', description: '' },
  { name: 'Sun Transits the 5th House', description: '' },
  { name: 'Sun Transits the 6th House', description: '' },
  { name: 'Sun Transits the 7th House', description: '' },
  { name: 'Sun Transits the 8th House', description: '' },
  { name: 'Sun Transits the 9th House', description: '' },
  { name: 'Venus Transits the 10th House', description: '' },
  { name: 'Venus Transits the 11th House', description: '' },
  { name: 'Venus Transits the 12th House', description: '' },
  { name: 'Venus Transits the 1st House', description: '' },
  { name: 'Venus Transits the 2nd House', description: '' },
  { name: 'Venus Transits the 3rd House', description: '' },
  { name: 'Venus Transits the 4th House', description: '' },
  { name: 'Venus Transits the 5th House', description: '' },
  { name: 'Venus Transits the 6th House', description: '' },
  { name: 'Venus Transits the 7th House', description: '' },
  { name: 'Venus Transits the 8th House', description: '' },
  { name: 'Venus Transits the 9th House', description: '' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS — Ascendant + Midheaven (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: '' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: '' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: '' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: '' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: '' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Mars Aspecting Midheaven (MC)', description: '' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: '' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: '' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: '' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Moon Aspecting Midheaven (MC)', description: '' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: '' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: '' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: '' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: '' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Sun Aspecting Ascendant (ASC)', description: '' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Sun Aspecting Midheaven (MC)', description: '' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: '' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: '' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: '' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: '' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: '' },
  { name: 'Venus Aspecting Midheaven (MC)', description: '' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: '' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: '' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: '' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER-PLANET SPECIALS — Uranus-Venus, Pluto-Saturn (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: '' },
  { name: 'Pluto conjunct Saturn : Ends', description: '' },
  { name: 'Pluto conjunct Saturn : Exact', description: '' },
  { name: 'Pluto conjunct Saturn : Starts', description: '' },
  { name: 'Uranus conjunct Venus', description: '' },
  { name: 'Uranus conjunct Venus : Ends', description: '' },
  { name: 'Uranus conjunct Venus : Exact', description: '' },
  { name: 'Uranus conjunct Venus : Starts', description: '' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS — natal house fixed by birth chart (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter aspect Jupiter in 8th house', description: '' },
  { name: 'Jupiter aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Jupiter aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Jupiter aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Jupiter aspect Ketu in 6th house', description: '' },
  { name: 'Jupiter aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Jupiter aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Jupiter aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Jupiter aspect Mars in 9th house', description: '' },
  { name: 'Jupiter aspect Mars in 9th house : Ends', description: '' },
  { name: 'Jupiter aspect Mars in 9th house : Exact', description: '' },
  { name: 'Jupiter aspect Mars in 9th house : Starts', description: '' },
  { name: 'Jupiter aspect Mercury in 8th house', description: '' },
  { name: 'Jupiter aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Jupiter aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Jupiter aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Jupiter aspect Moon in 10th house', description: '' },
  { name: 'Jupiter aspect Moon in 10th house : Ends', description: '' },
  { name: 'Jupiter aspect Moon in 10th house : Exact', description: '' },
  { name: 'Jupiter aspect Moon in 10th house : Starts', description: '' },
  { name: 'Jupiter aspect Rahu in 12th house', description: '' },
  { name: 'Jupiter aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Jupiter aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Jupiter aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Jupiter aspect Saturn in 1st house', description: '' },
  { name: 'Jupiter aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Jupiter aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Jupiter aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Jupiter aspect Sun in 8th house', description: '' },
  { name: 'Jupiter aspect Sun in 8th house : Ends', description: '' },
  { name: 'Jupiter aspect Sun in 8th house : Exact', description: '' },
  { name: 'Jupiter aspect Sun in 8th house : Starts', description: '' },
  { name: 'Jupiter aspect Venus in 7th house', description: '' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: '' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: '' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: '' },
  { name: 'Ketu aspect Jupiter in 8th house', description: '' },
  { name: 'Ketu aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Ketu aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Ketu aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Ketu aspect Ketu in 6th house', description: '' },
  { name: 'Ketu aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Ketu aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Ketu aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Ketu aspect Mars in 9th house', description: '' },
  { name: 'Ketu aspect Mars in 9th house : Ends', description: '' },
  { name: 'Ketu aspect Mars in 9th house : Exact', description: '' },
  { name: 'Ketu aspect Mars in 9th house : Starts', description: '' },
  { name: 'Ketu aspect Mercury in 8th house', description: '' },
  { name: 'Ketu aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Ketu aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Ketu aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Ketu aspect Moon in 10th house', description: '' },
  { name: 'Ketu aspect Moon in 10th house : Ends', description: '' },
  { name: 'Ketu aspect Moon in 10th house : Exact', description: '' },
  { name: 'Ketu aspect Moon in 10th house : Starts', description: '' },
  { name: 'Ketu aspect Rahu in 12th house', description: '' },
  { name: 'Ketu aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Ketu aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Ketu aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Ketu aspect Saturn in 1st house', description: '' },
  { name: 'Ketu aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Ketu aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Ketu aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Ketu aspect Sun in 8th house', description: '' },
  { name: 'Ketu aspect Sun in 8th house : Ends', description: '' },
  { name: 'Ketu aspect Sun in 8th house : Exact', description: '' },
  { name: 'Ketu aspect Sun in 8th house : Starts', description: '' },
  { name: 'Ketu aspect Venus in 7th house', description: '' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: '' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: '' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: '' },
  { name: 'Mars aspect Jupiter in 8th house', description: '' },
  { name: 'Mars aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Mars aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Mars aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Mars aspect Ketu in 6th house', description: '' },
  { name: 'Mars aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Mars aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Mars aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Mars aspect Mars in 9th house', description: '' },
  { name: 'Mars aspect Mars in 9th house : Ends', description: '' },
  { name: 'Mars aspect Mars in 9th house : Exact', description: '' },
  { name: 'Mars aspect Mars in 9th house : Starts', description: '' },
  { name: 'Mars aspect Mercury in 8th house', description: '' },
  { name: 'Mars aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Mars aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Mars aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Mars aspect Moon in 10th house', description: '' },
  { name: 'Mars aspect Moon in 10th house : Ends', description: '' },
  { name: 'Mars aspect Moon in 10th house : Exact', description: '' },
  { name: 'Mars aspect Moon in 10th house : Starts', description: '' },
  { name: 'Mars aspect Rahu in 12th house', description: '' },
  { name: 'Mars aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Mars aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Mars aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Mars aspect Saturn in 1st house', description: '' },
  { name: 'Mars aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Mars aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Mars aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Mars aspect Sun in 8th house', description: '' },
  { name: 'Mars aspect Sun in 8th house : Ends', description: '' },
  { name: 'Mars aspect Sun in 8th house : Exact', description: '' },
  { name: 'Mars aspect Sun in 8th house : Starts', description: '' },
  { name: 'Mars aspect Venus in 7th house', description: '' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: '' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: '' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: '' },
  { name: 'Mercury aspect Jupiter in 8th house', description: '' },
  { name: 'Mercury aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Mercury aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Mercury aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Mercury aspect Ketu in 6th house', description: '' },
  { name: 'Mercury aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Mercury aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Mercury aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Mercury aspect Mars in 9th house', description: '' },
  { name: 'Mercury aspect Mars in 9th house : Ends', description: '' },
  { name: 'Mercury aspect Mars in 9th house : Exact', description: '' },
  { name: 'Mercury aspect Mars in 9th house : Starts', description: '' },
  { name: 'Mercury aspect Mercury in 8th house', description: '' },
  { name: 'Mercury aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Mercury aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Mercury aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Mercury aspect Moon in 10th house', description: '' },
  { name: 'Mercury aspect Moon in 10th house : Ends', description: '' },
  { name: 'Mercury aspect Moon in 10th house : Exact', description: '' },
  { name: 'Mercury aspect Moon in 10th house : Starts', description: '' },
  { name: 'Mercury aspect Rahu in 12th house', description: '' },
  { name: 'Mercury aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Mercury aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Mercury aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Mercury aspect Saturn in 1st house', description: '' },
  { name: 'Mercury aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Mercury aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Mercury aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Mercury aspect Sun in 8th house', description: '' },
  { name: 'Mercury aspect Sun in 8th house : Ends', description: '' },
  { name: 'Mercury aspect Sun in 8th house : Exact', description: '' },
  { name: 'Mercury aspect Sun in 8th house : Starts', description: '' },
  { name: 'Mercury aspect Venus in 7th house', description: '' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: '' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: '' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: '' },
  { name: 'Moon aspect Jupiter in 8th house', description: '' },
  { name: 'Moon aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Moon aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Moon aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Moon aspect Ketu in 6th house', description: '' },
  { name: 'Moon aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Moon aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Moon aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Moon aspect Mars in 9th house', description: '' },
  { name: 'Moon aspect Mars in 9th house : Ends', description: '' },
  { name: 'Moon aspect Mars in 9th house : Exact', description: '' },
  { name: 'Moon aspect Mars in 9th house : Starts', description: '' },
  { name: 'Moon aspect Mercury in 8th house', description: '' },
  { name: 'Moon aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Moon aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Moon aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Moon aspect Moon in 10th house', description: '' },
  { name: 'Moon aspect Moon in 10th house : Ends', description: '' },
  { name: 'Moon aspect Moon in 10th house : Exact', description: '' },
  { name: 'Moon aspect Moon in 10th house : Starts', description: '' },
  { name: 'Moon aspect Rahu in 12th house', description: '' },
  { name: 'Moon aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Moon aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Moon aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Moon aspect Saturn in 1st house', description: '' },
  { name: 'Moon aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Moon aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Moon aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Moon aspect Sun in 8th house', description: '' },
  { name: 'Moon aspect Sun in 8th house : Ends', description: '' },
  { name: 'Moon aspect Sun in 8th house : Exact', description: '' },
  { name: 'Moon aspect Sun in 8th house : Starts', description: '' },
  { name: 'Moon aspect Venus in 7th house', description: '' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: '' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: '' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: '' },
  { name: 'Rahu aspect Jupiter in 8th house', description: '' },
  { name: 'Rahu aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Rahu aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Rahu aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Rahu aspect Ketu in 6th house', description: '' },
  { name: 'Rahu aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Rahu aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Rahu aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Rahu aspect Mars in 9th house', description: '' },
  { name: 'Rahu aspect Mars in 9th house : Ends', description: '' },
  { name: 'Rahu aspect Mars in 9th house : Exact', description: '' },
  { name: 'Rahu aspect Mars in 9th house : Starts', description: '' },
  { name: 'Rahu aspect Mercury in 8th house', description: '' },
  { name: 'Rahu aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Rahu aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Rahu aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Rahu aspect Moon in 10th house', description: '' },
  { name: 'Rahu aspect Moon in 10th house : Ends', description: '' },
  { name: 'Rahu aspect Moon in 10th house : Exact', description: '' },
  { name: 'Rahu aspect Moon in 10th house : Starts', description: '' },
  { name: 'Rahu aspect Rahu in 12th house', description: '' },
  { name: 'Rahu aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Rahu aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Rahu aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Rahu aspect Saturn in 1st house', description: '' },
  { name: 'Rahu aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Rahu aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Rahu aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Rahu aspect Sun in 8th house', description: '' },
  { name: 'Rahu aspect Sun in 8th house : Ends', description: '' },
  { name: 'Rahu aspect Sun in 8th house : Exact', description: '' },
  { name: 'Rahu aspect Sun in 8th house : Starts', description: '' },
  { name: 'Rahu aspect Venus in 7th house', description: '' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: '' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: '' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: '' },
  { name: 'Saturn aspect Jupiter in 8th house', description: '' },
  { name: 'Saturn aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Saturn aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Saturn aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Saturn aspect Ketu in 6th house', description: '' },
  { name: 'Saturn aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Saturn aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Saturn aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Saturn aspect Mars in 9th house', description: '' },
  { name: 'Saturn aspect Mars in 9th house : Ends', description: '' },
  { name: 'Saturn aspect Mars in 9th house : Exact', description: '' },
  { name: 'Saturn aspect Mars in 9th house : Starts', description: '' },
  { name: 'Saturn aspect Mercury in 8th house', description: '' },
  { name: 'Saturn aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Saturn aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Saturn aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Saturn aspect Moon in 10th house', description: '' },
  { name: 'Saturn aspect Moon in 10th house : Ends', description: '' },
  { name: 'Saturn aspect Moon in 10th house : Exact', description: '' },
  { name: 'Saturn aspect Moon in 10th house : Starts', description: '' },
  { name: 'Saturn aspect Rahu in 12th house', description: '' },
  { name: 'Saturn aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Saturn aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Saturn aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Saturn aspect Saturn in 1st house', description: '' },
  { name: 'Saturn aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Saturn aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Saturn aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Saturn aspect Sun in 8th house', description: '' },
  { name: 'Saturn aspect Sun in 8th house : Ends', description: '' },
  { name: 'Saturn aspect Sun in 8th house : Exact', description: '' },
  { name: 'Saturn aspect Sun in 8th house : Starts', description: '' },
  { name: 'Saturn aspect Venus in 7th house', description: '' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: '' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: '' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: '' },
  { name: 'Sun aspect Jupiter in 8th house', description: '' },
  { name: 'Sun aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Sun aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Sun aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Sun aspect Ketu in 6th house', description: '' },
  { name: 'Sun aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Sun aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Sun aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Sun aspect Mars in 9th house', description: '' },
  { name: 'Sun aspect Mars in 9th house : Ends', description: '' },
  { name: 'Sun aspect Mars in 9th house : Exact', description: '' },
  { name: 'Sun aspect Mars in 9th house : Starts', description: '' },
  { name: 'Sun aspect Mercury in 8th house', description: '' },
  { name: 'Sun aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Sun aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Sun aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Sun aspect Moon in 10th house', description: '' },
  { name: 'Sun aspect Moon in 10th house : Ends', description: '' },
  { name: 'Sun aspect Moon in 10th house : Exact', description: '' },
  { name: 'Sun aspect Moon in 10th house : Starts', description: '' },
  { name: 'Sun aspect Rahu in 12th house', description: '' },
  { name: 'Sun aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Sun aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Sun aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Sun aspect Saturn in 1st house', description: '' },
  { name: 'Sun aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Sun aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Sun aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Sun aspect Sun in 8th house', description: '' },
  { name: 'Sun aspect Sun in 8th house : Ends', description: '' },
  { name: 'Sun aspect Sun in 8th house : Exact', description: '' },
  { name: 'Sun aspect Sun in 8th house : Starts', description: '' },
  { name: 'Sun aspect Venus in 7th house', description: '' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: '' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: '' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: '' },
  { name: 'Venus aspect Jupiter in 8th house', description: '' },
  { name: 'Venus aspect Jupiter in 8th house : Ends', description: '' },
  { name: 'Venus aspect Jupiter in 8th house : Exact', description: '' },
  { name: 'Venus aspect Jupiter in 8th house : Starts', description: '' },
  { name: 'Venus aspect Ketu in 6th house', description: '' },
  { name: 'Venus aspect Ketu in 6th house : Ends', description: '' },
  { name: 'Venus aspect Ketu in 6th house : Exact', description: '' },
  { name: 'Venus aspect Ketu in 6th house : Starts', description: '' },
  { name: 'Venus aspect Mars in 9th house', description: '' },
  { name: 'Venus aspect Mars in 9th house : Ends', description: '' },
  { name: 'Venus aspect Mars in 9th house : Exact', description: '' },
  { name: 'Venus aspect Mars in 9th house : Starts', description: '' },
  { name: 'Venus aspect Mercury in 8th house', description: '' },
  { name: 'Venus aspect Mercury in 8th house : Ends', description: '' },
  { name: 'Venus aspect Mercury in 8th house : Exact', description: '' },
  { name: 'Venus aspect Mercury in 8th house : Starts', description: '' },
  { name: 'Venus aspect Moon in 10th house', description: '' },
  { name: 'Venus aspect Moon in 10th house : Ends', description: '' },
  { name: 'Venus aspect Moon in 10th house : Exact', description: '' },
  { name: 'Venus aspect Moon in 10th house : Starts', description: '' },
  { name: 'Venus aspect Rahu in 12th house', description: '' },
  { name: 'Venus aspect Rahu in 12th house : Ends', description: '' },
  { name: 'Venus aspect Rahu in 12th house : Exact', description: '' },
  { name: 'Venus aspect Rahu in 12th house : Starts', description: '' },
  { name: 'Venus aspect Saturn in 1st house', description: '' },
  { name: 'Venus aspect Saturn in 1st house : Ends', description: '' },
  { name: 'Venus aspect Saturn in 1st house : Exact', description: '' },
  { name: 'Venus aspect Saturn in 1st house : Starts', description: '' },
  { name: 'Venus aspect Sun in 8th house', description: '' },
  { name: 'Venus aspect Sun in 8th house : Ends', description: '' },
  { name: 'Venus aspect Sun in 8th house : Exact', description: '' },
  { name: 'Venus aspect Sun in 8th house : Starts', description: '' },
  { name: 'Venus aspect Venus in 7th house', description: '' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: '' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: '' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: '' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
