// db/seed_career_aries.js
//
// Per-ascendant fill-in seed for the **career** category, scoped to a
// representative Aries ascendant native with:
//   Ascendant: Aries
//   Natal placements (sidereal Lahiri):
//     Sun=5th (Leo, own)  Moon=4th (Cancer, own)  Mercury=6th (Virgo, own+exalted)
//     Venus=12th (Pisces, exalted)  Mars=1st (Aries, own — Ruchaka Yoga)
//     Jupiter=9th (Sagittarius, own)  Saturn=10th (Capricorn, own — Sasa Yoga)
//     Rahu=5th (Leo, conjunct Sun)  Ketu=11th (Aquarius)
//
// All 530 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose career-specific interpretations, then run:
//
//   node db/seed_career_aries.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./career');

const ASCENDANT = 'Aries';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mars ruler of the 1st House in the 1st House', description: 'You are built to lead from the front. Founder roles, head-of-craft positions, athletic professions, military and security work, surgery, real-asset development, sales leadership — you compound through directness, stamina, and being first in the room. Timid bosses bore you, and roles that require invisibility wear you down within a year. Self-employment is rarely a phase, it is the structural truth. The shadow: impatience that clips off slower colleagues — learn to hold the front line without burning the supply chain.' },
  { name: 'Venus ruler of the 2nd House in the 12th House', description: 'Income arrives from foreign clients, behind-the-scenes patrons, hospitality, luxury, beauty, wellness, charity, film, music — circuits that pay quietly rather than publicly. Foreign-currency deposits compound. Hidden benefactors appear at the right moment. The bedroom-and-pleasure economies pay you well. The shadow: liquid wealth slips through your fingers when there is no structured savings ritual; the same channel that earns also dissolves what is not pinned down.' },
  { name: 'Mercury ruler of the 3rd House in the 6th House', description: 'Earn through writing, teaching, technical operations, audit, debt-recovery, HR adjudication, code, analytics — any craft where precision wins the wage. Subordinates and younger colleagues are the principal channel; they execute your direction sharply because the documentation is clear. Workplace conflicts resolve in your favor when fought with paperwork, not heat. The shadow: weaponized analysis that wounds. Used cruelly the same precision costs you allies.' },
  { name: 'Moon ruler of the 4th House in the 4th House', description: 'Career flourishes when home and office are co-engineered. Real estate, family business, hospitality, education, food, mother-related industries, work-from-home setups — all native. Senior women and mother-figures in the network reliably tilt trajectory. Relocating to a city or neighborhood that nourishes you produces the next decade\'s biggest jump. The shadow: emotional weather around home contaminates the workday — discipline the boundary morning by morning.' },
  { name: 'Sun ruler of the 5th House in the 5th House', description: 'You are wired to be the visible creative principal — head of a creative practice, principal artist, mentor of mentees, kingmaker of younger talent, advisor to speculative ventures. There is an ambition undertow that craves fame, large stages, larger-than-life recognition. Performing arts, sports management, education-with-status, advisory boards — all native. The shadow: chasing the spotlight at the cost of dharma. Verify each ambitious leap against a quieter inner standard.' },
  { name: 'Mercury ruler of the 6th House in the 6th House', description: 'Audit, compliance, regulatory, debt recovery, litigation support, HR adjudication, ops excellence, technical writing, healing professions — supreme command. Every adversary teaches you. The harder the case, the more authority you accrue. Subordinates are loyal because you fight for them with documents. The shadow: addicted to the conflict — learn to choose battles, not collect them.' },
  { name: 'Venus ruler of the 7th House in the 12th House', description: 'Partnerships are foreign, devotional, hidden, or service-domain. Spouse and principal client arrive from abroad or from a pleasure, hospitality, or healing background. Business unions compound when worked behind the scenes rather than in the limelight; retreats, ashrams, hotels, hospitals, monastic settings are where the work matures. Public-facing JVs feel hollow. The shadow: counterparties drift abroad or inward when you push for visibility prematurely.' },
  { name: 'Mars ruler of the 8th House in the 1st House', description: 'You absorb and discharge industry chaos through your own person. Surgical roles, occult and research craft, crisis-leadership, turnaround consulting, special-forces-style mandates, longevity work, Ayurveda, yoga professions — all native. You survive industry waves that take down peers because shock is fuel for you, not sand. The shadow: accidents, burns, sudden injuries — cultivate intense regular exercise so the energy has a clean outlet.' },
  { name: 'Jupiter ruler of the 9th House in the 9th House', description: 'You are built to be the teacher, judge, ethical authority, foreign-expansion architect. Career fortune routes through higher learning, publishing, judiciary, policy, religious or philosophical work, foreign clients — any role where principle is the product. Mentor figures arrive as gurus, not as bosses. The shadow: lofty principle that loses touch with delivery. Wisdom must be paired with structural discipline to convert into wage.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Slow, permanent, irreversible status accrual is the path. Government, corporate ladder, infrastructure, regulatory mastery, longevity-of-firm leadership, mining, real assets, audit and compliance leadership. There will not be a meteoric rise; you will arrive at chief-of-something twenty years later than the flashy peers, and still be there long after they have flamed out. The shadow: workaholism that erodes everything else — honor the dharma, but cap the hours.' },
  { name: 'Saturn ruler of the 11th House in the 10th House', description: 'Bonuses, equity vesting, profit-share, board appointments arrive as a function of your title and tenure rather than via networking heroics. Senior peers, elder colleagues, and government-affiliated networks are the principal gain channel. Friendships forged in formal professional settings outlast ones forged in casual leisure. The shadow: confusing the network with the job — your truest friends may not be your best career-gain channel.' },
  { name: 'Jupiter ruler of the 12th House in the 9th House', description: 'Foreign work, pilgrimages, monastic retreats, sabbaticals at religious or academic institutions enrich the career. Charitable expenditure, pro-bono teaching, ethical loss-leader mandates compound long-term reputation. Time spent abroad rarely shows up as line-item revenue but it shows up later as authority. The shadow: principled over-commitment to a noble cause that drains liquidity — wisdom expansion needs disciplined gating.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (6)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 5th (Dispositor)', description: 'When this engine fires, career advances through visible creative authority — launches, performances, teaching engagements, mentee placements, speculative wins. Industries: creative direction, education-with-status, sports leadership, advisory boards, principal-creator roles. The shadow: ego that confuses spectacle with substance. Keep an inner-circle who corrects you when the showmanship runs ahead of the work.' },
  { name: 'Moon in 4th (Dispositor)', description: 'When this engine fires, career news arrives via home, mother, real-estate, food and hospitality, family-business contacts. The kitchen-table conversation tilts trajectory. Industries: real estate, education, hospitality, food, family-business consultancy, mother-related sectors. The shadow: emotional weather at home flooding the office — build a clean morning ritual to seal the boundary.' },
  { name: 'Mercury in 6th (Dispositor)', description: 'When this engine fires, expect surgical-precision wins in audit, debt-recovery, technical writing, conflict-resolution, regulatory navigation. Best windows for shipping the masterpiece spec, closing the long-running case, leading the HR transformation. The shadow: addicted to being right — precision used to wound costs allies you would have wanted later.' },
  { name: 'Jupiter in 9th (Dispositor)', description: 'When this engine fires, foreign-fortune mentor blessings flow — visa wins, certification clearances, judicial victories, publishing breakthroughs, ethics-led promotions. Industries: judiciary, publishing, religion-adjacent, education, foreign-affairs, NGO leadership. The shadow: principled obstinacy that closes off practical options. Wisdom must stay porous.' },
  { name: 'Mars in 1st (Dispositor)', description: 'When this engine fires, career advances through direct action — the cold call, the unilateral decision, the bold pivot, the founder-style move. Industries: founder roles, athletic, military and security, surgery, real-asset development, sales leadership. The shadow: scorched-earth wins. The casualties remember you longer than the victories.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, the slow promotion lands, the structural authority crystallizes, the long-deferred recognition arrives — and feels oddly weightless. You wanted it for years; the wanting was the energy. Honor the achievement; do not chase the next one to recapture the old hunger.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak visibility window of self. Authority radiates; the body feels lit; presentations, interviews, founder-pitches land with extra weight. Best four-week window of the year for a personal-brand reset, taking on a public mantle, leading a competitive launch. Watch ego friction with father-figures and senior bosses.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on income, voice, family-finance. Excellent for negotiating compensation, recording the talk, locking the salary commitment. Family-money matters surface and resolve through directness. Throat-care matters; vocal projects favored.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on writing, peers, short bursts of effort. Ship the document, send the bold proposal, push the sales sequence. Younger colleagues respond to direct authority. Good window for siblings-and-peers career conversations.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home anchor. Real-estate decisions, mother-related career conversations, family-business inflection. Authority through home-base; visible work-from-home phase. Watch chest and heart fatigue.' },
  { name: 'Sun Transits the 5th House', description: 'Annual return-style activation of creative authority and ambition. Best four-week window of the year for launching the creative project, taking on a public mentor role, accepting a board or advisory seat, pitching the speculative idea. Father-figures and authority-figures notice you.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on technical execution and enemy-defeat. Best window for the audit you have been postponing, the hard HR conversation, the regulatory filing, the debt-recovery action. Adversaries weaken in your favor.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on partnerships and public-facing deals. Visibility through contracts; spouse and principal-client dynamics light up. Sign the anchor partnership, demand the JV terms, go public with a deal. Watch ego friction with counterparties.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in the transformation chamber. Career decisions take on surgical edge — succession, regulatory navigation, restructuring leadership. Inheritance, severance, equity events surface for clarification. The chaos here is structural promotion in disguise.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on the dharma-mentor engine. Best window for international-stage talks, publishing, certification, judicial proceedings, mentor-driven moves. A father-figure or senior guru delivers a decisive blessing or test.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility window. Best for launching the flagship initiative, demanding the title bump, leading a competitive pitch, accepting the chief-of-something role. The room reads you as the senior-track candidate.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on the gains and networks zone with a detachment undertone. Bonus pool conversations, equity true-ups, board invitations land — and feel oddly weightless. Senior peers notice you; the recognition comes wrapped in a "is this what I was chasing?" question.' },
  { name: 'Sun Transits the 12th House', description: 'Public visibility dims for a month — but behind-the-scenes work, foreign correspondence, confidential mandates, retreats are favored. Quiet authority compounds out of sight. Best for white papers, off-balance-sheet structuring, next-quarter strategy.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of emotional charge on persona. Watch impulsive declarations; channel the energy into a body-anchored move — workout, pitch, founder declaration.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional warmth in income, voice, family-finance. Speak when warm; family-financial conversations land softly.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on writing, peers, short bursts. Send the warm-toned email, make the call that needs to land softly.' },
  { name: 'Moon Transits the 4th House', description: 'Peak monthly home-emotional days. Work from home, host the team meal, take the family-related call. Mother-channel news arrives.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative authority. Channel the depth into a creative push; avoid impulsive speculation; the ambition wave amplifies emotion to dangerous levels.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on the service and conflict zone. Empathetic HR work, mentoring juniors, settling a conflict softly. Avoid harsh subordinate-corrections.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnerships. Read the partner\'s mood before pushing terms. Best for warming a cold negotiation.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight in the transformation chamber. Sensitive to organizational mood around restructuring; defer non-urgent decisions two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward foreign work, gurus, higher-learning. Big-vision dreams; capture them, defer execution.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on public reputation. The room reads you; opening line, posture, and dress matter more than usual today.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth toward the network with a detachment undertone. Reach out, accept the invite — but expect to feel oddly distant from the gathering.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional charge on foreign, devotional, and luxury zones. Sleep more, write privately, take the bath; behind-scenes warmth compounds.' },
  { name: 'Mercury Transits the 1st House', description: 'Bold, punchy communication of self. Best for founder-style outreach, sharp CV refresh, the assertive intro letter. Watch overly aggressive phrasing.' },
  { name: 'Mercury Transits the 2nd House', description: 'Patient, well-structured communication around income, voice, family-finance. Excellent for salary cases, contract paperwork, family-finance emails.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak writing, effort, peer-leadership window of any quarter. Ship the document, publish the analysis, send the proposal. Younger colleagues align fast.' },
  { name: 'Mercury Transits the 4th House', description: 'Emotionally attuned home, family, and real-estate paperwork. Best for lease drafts, mother-correspondence, family-business communications.' },
  { name: 'Mercury Transits the 5th House', description: 'Bold, dramatic creative communication. Pitch the speculative idea, draft the bold creative brief, write the mentee-coaching note. Verify before sending — the volume runs hot.' },
  { name: 'Mercury Transits the 6th House', description: 'Peak surgical-mind window of any quarter. Audit reports, regulatory filings, debt-recovery letters, technical specs, HR adjudications. The mind sees what others miss.' },
  { name: 'Mercury Transits the 7th House', description: 'Diplomatic, balanced contract negotiation in writing. Best for partnership term-sheets, formal JV drafts, the precise mediation letter.' },
  { name: 'Mercury Transits the 8th House', description: 'Investigative depth-writing window. Forensic reports, due diligence, regulatory responses, taxation drafts. Confidentiality matters.' },
  { name: 'Mercury Transits the 9th House', description: 'Visionary writing window. Foreign correspondence, philosophical drafts, judicial filings. Strong on principle, weak on detail — pair with a checklist.' },
  { name: 'Mercury Transits the 10th House', description: 'Disciplined, structural career-communication. Press releases, all-hands updates, formal status memos.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp-but-detached network communication. Best for structured outreach to senior allies; avoid emotionally charged friend-asks.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential, devotional, and foreign correspondence window. NDAs, off-the-record briefings, foreign client emails. Watch leaks.' },
  { name: 'Venus Transits the 1st House', description: 'Warmth on the persona. Excellent for client-facing meetings, branding updates, charm-driven asks. The smile lands; people remember you well.' },
  { name: 'Venus Transits the 2nd House', description: 'Soft income, voice, family-finance window. Salary asks land softer; expert commentary attracts paid offers. Indulgence in food and throat-care.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful writing and communication. Peer relationships warm; sales correspondence and mentoring conversations favored.' },
  { name: 'Venus Transits the 4th House', description: 'Beautiful home, real-estate, mother window. Sign the lease, beautify the office, host the gathering, call mother.' },
  { name: 'Venus Transits the 5th House', description: 'Peak creative-aesthetic visibility. Best for launching aesthetic creative output, advisory income, mentor-protégé warmth. Speculation favored if grounded.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic service excellence. HR work, team-building, conflict resolution all favored. The difficult colleague becomes the receptive ally.' },
  { name: 'Venus Transits the 7th House', description: 'Peak partnership window. Sign the JV, formalize the long-pending alliance, close the anchor client. Spouse or partner brings career luck.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic navigation of inheritance, severance, and equity events. Excellent for negotiating a fair restructuring or settlement.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful foreign engagement, ethical advisory, publishing diplomacy. Travel for work feels lucky and warm.' },
  { name: 'Venus Transits the 10th House', description: 'Softens the public face. Best for design-driven public projects, brand campaigns, PR moves.' },
  { name: 'Venus Transits the 11th House', description: 'Graceful gains and networks with a cool undertone. Bonus and equity events favored; female mentors and senior allies open doors — but the joy of the win feels muted.' },
  { name: 'Venus Transits the 12th House', description: 'Annual peak window for foreign, luxury, and devotional channels. Hidden patrons surface, foreign offers land, retreats and pilgrimages enrich the career.' },
  { name: 'Mars Transits the 1st House', description: 'One of the most powerful self-and-action windows of any two-year cycle. Launch the founder move, sign the founder paper, take the body-anchored bold step.' },
  { name: 'Mars Transits the 2nd House', description: 'Heated income and family-finance battles. Aggressive salary asks possible but data-back them; impulse can backfire here. Watch sharp speech; throat and dental care.' },
  { name: 'Mars Transits the 3rd House', description: 'Fierce effort and communication window. Best for shipping under deadline, executing the technical sprint, defending the document. Watch sharp emails.' },
  { name: 'Mars Transits the 4th House', description: 'Heated home-base disputes flare and resolve. Excellent for decisive real-estate action; watch family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Hot creative-speculative drive. Best for pushing through a stalled creative project, taking the calculated investment risk, asserting authority over mentees. Verify before leaping — the volume amplifies.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable service combat. Win the workplace dispute, settle the debt aggressively, defeat a rival client. Health watch.' },
  { name: 'Mars Transits the 7th House', description: 'Friction in partnerships. Hard to negotiate cleanly; defer the contract close seven to ten days if possible.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical action in the transformation chamber. Restructurings, succession battles, audit fights. You hold steady where others panic.' },
  { name: 'Mars Transits the 9th House', description: 'Bold dharma-action window. Foreign-engagement push, certification fight, judicial action favored.' },
  { name: 'Mars Transits the 10th House', description: 'Among the strongest career-action windows of any two-year cycle. Launch the flagship, demand the title bump, lead the competitive pitch.' },
  { name: 'Mars Transits the 11th House', description: 'Assertive network and gain push with a detachment undertone. Bonus negotiations, board-position asks, profit-share fights. Win it but expect emotional flatness.' },
  { name: 'Mars Transits the 12th House', description: 'Heated foreign, luxury, and hidden-channel zone. Behind-scenes power plays, foreign trade fights, hospitality-industry sharp moves. Sleep loss possible.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual-tier expansion of self, persona, founder identity. Take the role expansion, accept the public mantle, declare the bigger ambition. The one-year window seeds the next decade.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom-blessing on income, voice, family-finance. Compensation cases, family-wealth structuring, vocal authority all expand.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on writing, peers, short-burst effort. Major publication, high-value peer relationships, mentee placements favored.' },
  { name: 'Jupiter Transits the 4th House', description: 'Peak home, family, and real-estate expansion year. Buy the home, deepen with mother, invest in the office.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major creative-launch year. Mentee placements, advisory-board ascensions, speculative wins (verify due-diligence before each). Take the visible authority position you have been declining.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom into service and conflict zone. Difficult clients become teachers; debt-resolution favored; HR-leadership advances. Health watch — wisdom in the service house tends toward weight gain.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom into partnership zone. Anchor JV, marriage of business and personal partnership, the prestige-client signing.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into the transformation chamber. Inheritance, severance, equity favorably resolves; longevity wins; restructuring brings authority.' },
  { name: 'Jupiter Transits the 9th House', description: 'Among the most blessed windows of any twelve-year cycle. Foreign expansion, certification, judicial wins, publishing breakthroughs, guru-blessings.' },
  { name: 'Jupiter Transits the 10th House', description: 'Peak career-zenith year. Take the chief-of-something role, accept the prestige offer, demand the elevation.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom-blessing on the gains zone with a detachment undertone. Bonus pools, equity vesting, board appointments compound — feel them with equanimity.' },
  { name: 'Jupiter Transits the 12th House', description: 'Peak foreign, luxury, and devotional year. Foreign sabbatical, retreat-led work, hidden-patron emergence, charitable career-mandates.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on body and identity. Health discipline, persona simplification, slow founder-craft. Don\'t expect speed; expect permanence.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on income, voice, family-finance. Slow but real wage growth; family-financial restructuring; vocal-craft compounding.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on writing, peers, effort. Builds long-form authorship, peer authority, sibling-relations restructuring.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy emotional and home weight; mother-related responsibility intensifies; real-estate decisions feel structural. The home foundation is being rebuilt for a longer life.' },
  { name: 'Saturn Transits the 5th House', description: 'Creative authority is tested. Mentee relationships restructure; speculation must be tightly disciplined; the fame-pull cools into something earned.' },
  { name: 'Saturn Transits the 6th House', description: 'Best multi-year window for building audit and regulatory authority, settling long-debt cases, leading HR transformation. Slow and structural, but every move accrues credit.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnerships. Long-arc business unions; the spouse or partner ages alongside you in the work. Slow legal proceedings.' },
  { name: 'Saturn Transits the 8th House', description: 'Major life restructuring window. Inheritance, severance, regulatory chapters open and close. Hold steady; patience compounds.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year discipline on dharma, foreign, teacher domain. Slow visa or certification process; gurus age; principles tested in the body.' },
  { name: 'Saturn Transits the 10th House', description: 'The 2.5-year window that seeds the next 30-year career chapter. Take the chief role; commit to the long structure. There is no faster route through this gate.' },
  { name: 'Saturn Transits the 11th House', description: 'Disciplined, structural gains. Bonus pools formalize, profit-share systematizes, board appointments crystallize. The network purges what is no longer dharmic for you.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on foreign, luxury, and devotional channels. Sabbaticals turn structural; foreign work formalizes; pleasure-spending audits itself.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive self-reinvention window. New persona, new ambition, new founder identity. Verify each leap against close-circle counsel.' },
  { name: 'Rahu Transits the 2nd House', description: 'Obsessive ambition around income, voice, family-finance. Be careful of get-rich-quick schemes; family-money pressure rises.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive communication push. Viral content, mass outreach, ambition-driven peer maneuvering. Verify before publishing.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home, real-estate, mother chapter. Foreign relocation pull strong; mother-related obsession.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month peak ambition window — creative fame, speculative obsession, mentee-frenzy. Verify integrity before each leap.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable for dramatic enemy-defeat, big debt-recovery, regulatory victory, HR transformation. The shadow is at home in the service house.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive partnership chapter. Foreign partner pull, unconventional JVs, controversial alliances. Verify carefully.' },
  { name: 'Rahu Transits the 8th House', description: 'Obsessive transformation chapter. Sudden inheritance, regulatory obsession, occult and research deep-dive. Stay grounded.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign-fortune obsession. International expansion, foreign certification, controversial guru. Vet the dharma channel.' },
  { name: 'Rahu Transits the 10th House', description: 'Obsessive career-elevation push. Sudden promotion offers, foreign career-pull, unconventional executive offers. Vet the legitimacy.' },
  { name: 'Rahu Transits the 11th House', description: 'Obsessive gains and networks chapter. Career-defining bonus events, equity revaluations, board-positioning. Stay clean — the temptation to game it is high.' },
  { name: 'Rahu Transits the 12th House', description: 'Obsessive foreign, luxury, devotional chapter. Foreign relocation, hidden-patron pursuits, retreat-driven careers. Verify each path.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping window. The old persona feels empty; the founder-warrior question itself drops out. Sit; do not over-rebuild.' },
  { name: 'Ketu Transits the 2nd House', description: 'Detachment from income, voice, family-finance. Income feels meaningless; family-money matters dissolve. Don\'t panic-renegotiate.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from peers, writing, short-effort zone. Solo deep-work favored; team-coordination misfires.' },
  { name: 'Ketu Transits the 4th House', description: 'Home and mother detachment. Sell-property impulses, mother\'s independence, leave-the-city signals.' },
  { name: 'Ketu Transits the 5th House', description: 'Creative-authority eclipse. Old creative ambition feels hollow; mentee-pull fades; speculation loses charge.' },
  { name: 'Ketu Transits the 6th House', description: 'Service detachment. Old conflicts dissolve without victory; debts forgiven or written off; HR cases close quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership detachment. Old JVs unwind; spouse or partner needs space; counterparties withdraw.' },
  { name: 'Ketu Transits the 8th House', description: 'Transformation acceleration. Old chapters end abruptly; inheritance, severance closes; regulatory cases dissolve.' },
  { name: 'Ketu Transits the 9th House', description: 'Dharma detachment. Old gurus feel finished; foreign-fortune ambitions cool; principle-without-attachment ripens.' },
  { name: 'Ketu Transits the 10th House', description: 'Career eclipse window. Old roles feel hollow; promotions feel weightless; layoffs happen quietly.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month deep purification of network and gains motivations. Friends drift, bonuses feel weightless, ambitions purify.' },
  { name: 'Ketu Transits the 12th House', description: 'Foreign, luxury, devotional dissolution. Pilgrimage-pull strong; pleasure-spending evaporates; old hidden-patron channels close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through persona. Best for leadership declarations, public-mantle assumption, founder-style debut.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish public-facing materials; prepare the leadership pitch.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the stage, declare the role, accept the public mantle.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Convert visibility into a binding title or formal recognition.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Peak career-visibility window. Launch flagship initiatives; demand title-elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens. Plan the upward move; brief the boss.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-visibility day. Take the elevation, lead the pitch, accept the prestige role.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-visibility window closes. Lock in any title or compensation moves before momentum fades.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona; warm public reception possible.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens. Prepare to be felt, not just seen.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Public mood favors you; warm presentations land.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes. The wave passes fast; lock in connections.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public reputation; warm career news possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional career window opens. Senior-network warmth rises.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional career day. Take the warm-toned client meeting, the empathetic team-talk.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional career window closes. Move warm leads into formal commitments.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-communication. Best for personal-brand updates, founder-narrative refresh.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Mind-on-self window opens. Refresh the CV, the bio, the founder-story.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak self-communication day. Send the bold intro letter, publish the personal post.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mind-on-self window closes. Lock in the personal-brand commitments.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp career-communication. Press releases, all-hands updates, status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-communication window opens. Prepare the public message.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak career-communication day. Publish, present, send the formal update.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-communication window closes. Convert messaging into commitment.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Warmth on the persona. Charm-asks favored; the smile lands.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Charm-self window opens. Prepare the diplomatic outreach.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. Make the warm ask, take the social meeting, deliver the persuasion.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm-self window closes. Convert warmth into binding agreements.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens the public face. Brand campaigns, design-led PR, beauty-driven status moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-career window opens. Plan the brand refresh, the visual update.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-career day. Launch the campaign, present the redesign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-career window closes. Lock in design commitments.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold, body-anchored self-action; founder declarations; warrior moves.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens. Prepare the bold move; train the body.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Take the founder action, sign the bold paper, lead the charge.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes. Lock in the action; channel residual energy into discipline.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold, decisive career action. Launch flagship initiatives; demand title-bumps; lead competitive pitches.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens. Prepare the bold play.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak career-action day. Launch, demand, lead.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action window closes. Convert moves into permanent positions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the role-elevation; declare the larger ambition.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens. Plan the public-mantle assumption.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the elevation, declare the ambition, take the public role.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes. Lock in the title, the public commitment.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the chief role, the prestige offer, the board appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion window opens. Brief the senior network.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day. Accept the chief-of-something role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion window closes. Convert offers into binding commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity. Slow down, simplify, build for permanence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens. Eliminate vanity commitments; prepare for slow grind.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. The reckoning is acute. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public work tested for staying power. Slow recognition; foundation-laying.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline window opens. Structure work for years.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak career-discipline day. The promotion delayed; the foundation laid.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-discipline window closes. Convert effort into title or compensation.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion; foreign or unconventional self emerges. Watch obsession.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window begins. Sudden ambition surfaces.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak reinvention day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes. Decide which experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic visibility expansion. Sudden promotions, unconventional opportunities, foreign career pull.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Career-reinvention window begins. Vet unconventional offers carefully.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak career-reinvention day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Career-reinvention window closes. Lock in legitimate pivots; release illusory ones.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. The old founder-warrior persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens. The pull to step away rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak stripping day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes. Move forward leaner.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. Promotions stall; recognition feels hollow.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse window begins. Don\'t over-defend a role wanting to end.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak career-eclipse day. The role dissolves quietly. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse window closes. Move forward to the cleaner platform.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting your career engine. Your industry rewrites; old hierarchies collapse. Multi-year career-platform transformation; you emerge with rebuilt structural authority.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on your career engine. Old corporate frameworks dismantle. Position for the long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day. The old system breaks; the new one is forced into being. You hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The structural-transformation chapter completes. You emerge with rebuilt authority and a permanent professional foundation.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the foreign and hidden-patron channel. Unexpected foreign offers; surprise hidden-patron emergence; abrupt shifts in the pleasure, devotional, or luxury career circuit.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden disruption window opens. Expect foreign offers, hidden-patron surprises, abrupt back-channel shifts.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. The foreign offer arrives, the hidden patron surfaces, the back-channel pivots. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption window closes. Integrate the changes; release the experiments that didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 5th house', description: 'Birthday-window ego activation in the creative-authority zone. Best for launching the creative project, taking the visible mentor role, accepting the speculative pitch.' },
  { name: 'Sun aspect Sun in 5th house : Starts', description: 'Annual creative-authority window opens. Plan the year\'s flagship creative move.' },
  { name: 'Sun aspect Sun in 5th house : Exact', description: 'Peak creative-authority day. Launch, declare, take the platform.' },
  { name: 'Sun aspect Sun in 5th house : Ends', description: 'Creative-authority window closes. Lock in the year\'s creative commitments.' },
  { name: 'Sun aspect Moon in 4th house', description: 'Visibility through home, mother, real-estate. Mother-channel career news possible.' },
  { name: 'Sun aspect Moon in 4th house : Starts', description: 'Home-visibility window opens. Prepare the family-business or real-estate conversation.' },
  { name: 'Sun aspect Moon in 4th house : Exact', description: 'Peak day for home-anchored visibility. Sign the lease, host the mother, take the family-business call.' },
  { name: 'Sun aspect Moon in 4th house : Ends', description: 'Home-visibility window closes. Lock in real-estate or family-business commitments.' },
  { name: 'Sun aspect Mercury in 6th house', description: 'Solar fire on the surgical-mind engine. Audit reports, regulatory filings, technical writing peak.' },
  { name: 'Sun aspect Mercury in 6th house : Starts', description: 'Surgical-mind window opens. Plan the high-precision deliverable.' },
  { name: 'Sun aspect Mercury in 6th house : Exact', description: 'Peak surgical-mind day. Publish the audit, file the case, ship the spec.' },
  { name: 'Sun aspect Mercury in 6th house : Ends', description: 'Surgical-mind window closes. Lock in the technical commitments.' },
  { name: 'Sun aspect Venus in 12th house', description: 'Solar light on foreign, luxury, devotional zone. Foreign-client engagement, hidden-patron emergence, retreat-driven work favored.' },
  { name: 'Sun aspect Venus in 12th house : Starts', description: 'Foreign-channel window opens. Plan the foreign trip, the retreat, the hidden mandate.' },
  { name: 'Sun aspect Venus in 12th house : Exact', description: 'Peak day for foreign, devotional, luxury authority. Take the foreign call; visit the retreat.' },
  { name: 'Sun aspect Venus in 12th house : Ends', description: 'Foreign-channel window closes. Lock in the foreign commitments.' },
  { name: 'Sun aspect Mars in 1st house', description: 'Solar fire on warrior identity. Founder declarations, body-anchored bold moves, athletic-career moments.' },
  { name: 'Sun aspect Mars in 1st house : Starts', description: 'Founder-fire window opens. Train; prepare the bold move.' },
  { name: 'Sun aspect Mars in 1st house : Exact', description: 'Peak founder-fire day. Lead the charge, take the founder action.' },
  { name: 'Sun aspect Mars in 1st house : Ends', description: 'Founder-fire window closes. Lock in the bold moves.' },
  { name: 'Sun aspect Jupiter in 9th house', description: 'Solar light on the dharma-mentor engine. Foreign-fortune visibility, judicial wins, publishing breakthroughs.' },
  { name: 'Sun aspect Jupiter in 9th house : Starts', description: 'Dharma-visibility window opens. Brief the senior mentor; plan the foreign move.' },
  { name: 'Sun aspect Jupiter in 9th house : Exact', description: 'Peak dharma-visibility day. Sign the international deal; accept the senior blessing.' },
  { name: 'Sun aspect Jupiter in 9th house : Ends', description: 'Dharma-visibility window closes. Lock in foreign commitments.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on the career-mastery engine. Peak career-zenith days; chief-of-something invitations.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Career-zenith window opens. Polish the executive-track materials.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak career-zenith day. Accept the elevation; take the chief role.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Career-zenith window closes. Lock in the title or compensation move.' },
  { name: 'Sun aspect Rahu in 5th house', description: 'Ambition-amplified ego activation. Watch fame-grasping; verify ambition is anchored to dharma.' },
  { name: 'Sun aspect Rahu in 5th house : Starts', description: 'Ambition-amplified window opens. Beware spectacle-over-substance.' },
  { name: 'Sun aspect Rahu in 5th house : Exact', description: 'Peak ambition day. The bold leap presents — verify integrity twice.' },
  { name: 'Sun aspect Rahu in 5th house : Ends', description: 'Ambition-amplified window closes. Keep what was anchored; release what was vanity.' },
  { name: 'Sun aspect Ketu in 11th house', description: 'Solar light on the detached-gains zone. Bonus or board-news arrives; feel it without grasping.' },
  { name: 'Sun aspect Ketu in 11th house : Starts', description: 'Detached-gains window opens. Prepare for muted recognition.' },
  { name: 'Sun aspect Ketu in 11th house : Exact', description: 'Peak detached-gains day. The recognition lands and feels weightless.' },
  { name: 'Sun aspect Ketu in 11th house : Ends', description: 'Detached-gains window closes. Move forward with cleaner ambition.' },
  { name: 'Moon aspect Sun in 5th house', description: 'Emotional charge on creative authority. Warm mentor-protégé moments, public-facing emotional pitches.' },
  { name: 'Moon aspect Sun in 5th house : Starts', description: 'Emotion-on-creative window opens. Soften the launch tone.' },
  { name: 'Moon aspect Sun in 5th house : Exact', description: 'Peak emotional-creative day. Make the heart-led pitch.' },
  { name: 'Moon aspect Sun in 5th house : Ends', description: 'Emotional-creative window closes. Lock in warm commitments.' },
  { name: 'Moon aspect Moon in 4th house', description: 'Monthly home-emotional peak. Family-business or mother-channel news.' },
  { name: 'Moon aspect Moon in 4th house : Starts', description: 'Home-emotional window opens. Prepare for emotional-home wave.' },
  { name: 'Moon aspect Moon in 4th house : Exact', description: 'Peak home-emotional day. Host mother, take the family-business call.' },
  { name: 'Moon aspect Moon in 4th house : Ends', description: 'Home-emotional window closes. Lock in home commitments.' },
  { name: 'Moon aspect Mercury in 6th house', description: 'Emotional intelligence on service and conflict zone. Empathetic HR work, gentle audits, warm subordinate-mentoring.' },
  { name: 'Moon aspect Mercury in 6th house : Starts', description: 'Emotion-on-service window opens. Soften the technical tone.' },
  { name: 'Moon aspect Mercury in 6th house : Exact', description: 'Peak day for empathetic technical work. Hold the warm 1:1; deliver the gentle correction.' },
  { name: 'Moon aspect Mercury in 6th house : Ends', description: 'Emotional-service window closes. Lock in HR or audit commitments.' },
  { name: 'Moon aspect Venus in 12th house', description: 'Emotional warmth on foreign, devotional, luxury zone. Devotional pull, retreat-yearning, foreign-friend warmth.' },
  { name: 'Moon aspect Venus in 12th house : Starts', description: 'Emotion-on-foreign window opens. Plan the retreat or foreign trip.' },
  { name: 'Moon aspect Venus in 12th house : Exact', description: 'Peak emotional-foreign day. Take the foreign call, visit the temple, sit with the devotion.' },
  { name: 'Moon aspect Venus in 12th house : Ends', description: 'Emotional-foreign window closes. Lock in the foreign or retreat commitment.' },
  { name: 'Moon aspect Mars in 1st house', description: 'Emotional charge on warrior identity. Body feels the work; warm founder-narratives land.' },
  { name: 'Moon aspect Mars in 1st house : Starts', description: 'Emotion-on-self window opens. Train the body; warm the founder-pitch.' },
  { name: 'Moon aspect Mars in 1st house : Exact', description: 'Peak emotional-self day. Lead from the heart and the gut together.' },
  { name: 'Moon aspect Mars in 1st house : Ends', description: 'Emotional-self window closes. Convert energy to commitment.' },
  { name: 'Moon aspect Jupiter in 9th house', description: 'Emotional pull toward dharma, foreign, teacher. Mentor-warmth, philosophical openness, foreign-friend emotion.' },
  { name: 'Moon aspect Jupiter in 9th house : Starts', description: 'Emotion-on-mentor window opens. Reach out to senior mentors.' },
  { name: 'Moon aspect Jupiter in 9th house : Exact', description: 'Peak warm-mentor day. Take the senior call; commit to the foreign-fortune step.' },
  { name: 'Moon aspect Jupiter in 9th house : Ends', description: 'Mentor-warmth window closes. Lock in the dharma commitments.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on the career zenith. Sensitive to senior-mood; reputation feels read.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Emotion-on-career window opens. Read the room before pushing terms.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak emotional-career day. Hold the warm-but-firm executive conversation.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Emotional-career window closes. Lock in commitments.' },
  { name: 'Moon aspect Rahu in 5th house', description: 'Emotional charge on ambition zone. Watch obsessive-craving; ground emotion in dharma.' },
  { name: 'Moon aspect Rahu in 5th house : Starts', description: 'Emotion-on-ambition window opens. Watch the spectacle pull.' },
  { name: 'Moon aspect Rahu in 5th house : Exact', description: 'Peak emotion-ambition day. The fame-pull peaks; verify integrity.' },
  { name: 'Moon aspect Rahu in 5th house : Ends', description: 'Emotion-ambition window closes. Release what was vanity.' },
  { name: 'Moon aspect Ketu in 11th house', description: 'Emotional detachment from gains and network. Friendships feel cool; bonus news lands flat.' },
  { name: 'Moon aspect Ketu in 11th house : Starts', description: 'Emotion-on-detachment window opens. Don\'t panic; the cooling is purifying.' },
  { name: 'Moon aspect Ketu in 11th house : Exact', description: 'Peak detachment day. Sit with the cool friend-feeling; don\'t over-rebuild.' },
  { name: 'Moon aspect Ketu in 11th house : Ends', description: 'Detachment window closes. Cleaner network resumes.' },
  { name: 'Mercury aspect Sun in 5th house', description: 'Sharp, ambitious creative-communication. Pitch decks, mentor newsletters, speculative writing.' },
  { name: 'Mercury aspect Sun in 5th house : Starts', description: 'Mind-on-creative window opens. Draft the bold pitch.' },
  { name: 'Mercury aspect Sun in 5th house : Exact', description: 'Peak creative-mind day. Send the speculative proposal; publish the manifesto.' },
  { name: 'Mercury aspect Sun in 5th house : Ends', description: 'Creative-mind window closes. Lock in the publication.' },
  { name: 'Mercury aspect Moon in 4th house', description: 'Emotionally tuned home, family, real-estate writing. Lease drafts, mother-correspondence, family-business memos.' },
  { name: 'Mercury aspect Moon in 4th house : Starts', description: 'Mind-on-home window opens. Prepare the family-business communication.' },
  { name: 'Mercury aspect Moon in 4th house : Exact', description: 'Peak home-mind day. Send the lease, the mother-letter, the family memo.' },
  { name: 'Mercury aspect Moon in 4th house : Ends', description: 'Home-mind window closes. Lock in the home and family paperwork.' },
  { name: 'Mercury aspect Mercury in 6th house', description: 'Peak surgical-mind window of any three-month cycle. The audit, the spec, the regulatory filing — all favored.' },
  { name: 'Mercury aspect Mercury in 6th house : Starts', description: 'Sharp-mind window opens on technical engine. Plan the high-precision deliverable.' },
  { name: 'Mercury aspect Mercury in 6th house : Exact', description: 'Peak technical-mind day. Ship the masterpiece document.' },
  { name: 'Mercury aspect Mercury in 6th house : Ends', description: 'Sharp-mind window closes. Lock in the technical commitments.' },
  { name: 'Mercury aspect Venus in 12th house', description: 'Graceful foreign, devotional, luxury writing. NDA drafts, foreign-client correspondence, retreat-mandate emails.' },
  { name: 'Mercury aspect Venus in 12th house : Starts', description: 'Mind-on-foreign window opens. Draft the foreign brief.' },
  { name: 'Mercury aspect Venus in 12th house : Exact', description: 'Peak foreign-mind day. Send the foreign letter; finalize the NDA.' },
  { name: 'Mercury aspect Venus in 12th house : Ends', description: 'Mind-on-foreign window closes. Lock in the foreign or confidential commitments.' },
  { name: 'Mercury aspect Mars in 1st house', description: 'Punchy, bold self-communication. Founder-narrative refresh, sharp CV, the assertive intro letter.' },
  { name: 'Mercury aspect Mars in 1st house : Starts', description: 'Mind-on-self window opens. Refresh the founder-story.' },
  { name: 'Mercury aspect Mars in 1st house : Exact', description: 'Peak founder-communication day. Send the bold intro.' },
  { name: 'Mercury aspect Mars in 1st house : Ends', description: 'Founder-mind window closes. Lock in the personal-brand commitments.' },
  { name: 'Mercury aspect Jupiter in 9th house', description: 'Visionary writing window. Foreign correspondence, philosophical drafts, judicial filings.' },
  { name: 'Mercury aspect Jupiter in 9th house : Starts', description: 'Mind-on-mentor window opens. Plan the major publication.' },
  { name: 'Mercury aspect Jupiter in 9th house : Exact', description: 'Peak visionary-writing day. Publish the principle-driven piece.' },
  { name: 'Mercury aspect Jupiter in 9th house : Ends', description: 'Visionary-writing window closes. Lock in the publication.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Disciplined career-communication. Press releases, structural memos, executive-grade status updates.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Mind-on-career window opens. Prepare the formal communication.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak structural-communication day. Send the all-hands; publish the press release.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Structural-communication window closes. Lock in the formal messaging.' },
  { name: 'Mercury aspect Rahu in 5th house', description: 'Bold, viral creative communication. Verify before sending; the volume runs hot and may distort.' },
  { name: 'Mercury aspect Rahu in 5th house : Starts', description: 'Mind-on-ambition window opens. Draft carefully.' },
  { name: 'Mercury aspect Rahu in 5th house : Exact', description: 'Peak ambition-mind day. Viral pitch lands — verify integrity twice.' },
  { name: 'Mercury aspect Rahu in 5th house : Ends', description: 'Ambition-mind window closes. Keep grounded pieces; release inflated ones.' },
  { name: 'Mercury aspect Ketu in 11th house', description: 'Sharp-but-detached network communication. Structured outreach to allies; avoid friend-pleading.' },
  { name: 'Mercury aspect Ketu in 11th house : Starts', description: 'Mind-on-detachment window opens. Send formal not emotional asks.' },
  { name: 'Mercury aspect Ketu in 11th house : Exact', description: 'Peak detached-mind day. Cold professional outreach lands.' },
  { name: 'Mercury aspect Ketu in 11th house : Ends', description: 'Detached-mind window closes. Cleaner network communication resumes.' },
  { name: 'Venus aspect Sun in 5th house', description: 'Graceful creative-authority. Aesthetic creative output, mentor-warmth, charm-driven mentee placement.' },
  { name: 'Venus aspect Sun in 5th house : Starts', description: 'Charm-on-creative window opens. Plan the aesthetic launch.' },
  { name: 'Venus aspect Sun in 5th house : Exact', description: 'Peak charm-creative day. Launch the beautiful project.' },
  { name: 'Venus aspect Sun in 5th house : Ends', description: 'Charm-creative window closes. Lock in the aesthetic commitments.' },
  { name: 'Venus aspect Moon in 4th house', description: 'Beautiful home, mother, real-estate window. Sign the lease, beautify the office, host the warm gathering.' },
  { name: 'Venus aspect Moon in 4th house : Starts', description: 'Charm-on-home window opens. Plan the home-beautification, the family gathering.' },
  { name: 'Venus aspect Moon in 4th house : Exact', description: 'Peak home-aesthetic day. Sign, host, beautify.' },
  { name: 'Venus aspect Moon in 4th house : Ends', description: 'Home-aesthetic window closes. Lock in the home commitments.' },
  { name: 'Venus aspect Mercury in 6th house', description: 'Diplomatic service excellence. HR work, team-building, conflict resolution all soften.' },
  { name: 'Venus aspect Mercury in 6th house : Starts', description: 'Charm-on-service window opens. Soften the technical tone.' },
  { name: 'Venus aspect Mercury in 6th house : Exact', description: 'Peak diplomatic-service day. The hard HR talk lands warmly.' },
  { name: 'Venus aspect Mercury in 6th house : Ends', description: 'Diplomatic-service window closes. Lock in HR or audit commitments.' },
  { name: 'Venus aspect Venus in 12th house', description: 'Peak foreign, luxury, devotional window. Hidden patrons surface; foreign offers land.' },
  { name: 'Venus aspect Venus in 12th house : Starts', description: 'Foreign-luxury window opens. Plan the foreign trip; the retreat.' },
  { name: 'Venus aspect Venus in 12th house : Exact', description: 'Peak foreign-luxury day. Foreign patron lands; retreat-mandate clarifies.' },
  { name: 'Venus aspect Venus in 12th house : Ends', description: 'Foreign-luxury window closes. Lock in foreign and retreat commitments.' },
  { name: 'Venus aspect Mars in 1st house', description: 'Warmth on the persona. Charm-driven founder-asks; warm leadership presence.' },
  { name: 'Venus aspect Mars in 1st house : Starts', description: 'Charm-on-self window opens. Plan the warm founder outreach.' },
  { name: 'Venus aspect Mars in 1st house : Exact', description: 'Peak charm-founder day. Make the warm bold ask.' },
  { name: 'Venus aspect Mars in 1st house : Ends', description: 'Charm-founder window closes. Lock in personal-brand warmth.' },
  { name: 'Venus aspect Jupiter in 9th house', description: 'Graceful foreign and dharma window. Diplomatic foreign engagement, ethical advisory.' },
  { name: 'Venus aspect Jupiter in 9th house : Starts', description: 'Charm-on-mentor window opens. Plan the diplomatic foreign move.' },
  { name: 'Venus aspect Jupiter in 9th house : Exact', description: 'Peak charm-dharma day. Sign the foreign deal warmly.' },
  { name: 'Venus aspect Jupiter in 9th house : Ends', description: 'Charm-dharma window closes. Lock in foreign commitments.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Softens the public face. Brand campaigns, design-led PR moves.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Charm-on-career window opens. Plan the brand refresh.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak design-career day. Launch the campaign.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Charm-career window closes. Lock in design commitments.' },
  { name: 'Venus aspect Rahu in 5th house', description: 'Glamour-amplified creative window. Spotlight launches, fame-driven mentor placements. Verify glamour vs. substance.' },
  { name: 'Venus aspect Rahu in 5th house : Starts', description: 'Glamour window opens. Vet the dazzle.' },
  { name: 'Venus aspect Rahu in 5th house : Exact', description: 'Peak glamour day. Take the spotlight — anchor in dharma.' },
  { name: 'Venus aspect Rahu in 5th house : Ends', description: 'Glamour window closes. Keep what was real.' },
  { name: 'Venus aspect Ketu in 11th house', description: 'Graceful but cool gains and networks. Bonus and board news arrives in a muted register.' },
  { name: 'Venus aspect Ketu in 11th house : Starts', description: 'Charm-on-detachment window opens. Don\'t expect emotional warmth from the gain.' },
  { name: 'Venus aspect Ketu in 11th house : Exact', description: 'Peak detached-charm day. The bonus lands; feel it without grasping.' },
  { name: 'Venus aspect Ketu in 11th house : Ends', description: 'Detached-charm window closes. Cleaner gains-relationship resumes.' },
  { name: 'Mars aspect Sun in 5th house', description: 'Fiery creative-authority push. Bold creative launches, aggressive speculative trades. Verify ambition does not inflate.' },
  { name: 'Mars aspect Sun in 5th house : Starts', description: 'Fire-on-creative window opens. Train and prepare.' },
  { name: 'Mars aspect Sun in 5th house : Exact', description: 'Peak fiery-creative day. Launch hard; verify integrity.' },
  { name: 'Mars aspect Sun in 5th house : Ends', description: 'Fiery-creative window closes. Lock in disciplined wins.' },
  { name: 'Mars aspect Moon in 4th house', description: 'Heated home and family-business push. Decisive real-estate moves; watch family arguments.' },
  { name: 'Mars aspect Moon in 4th house : Starts', description: 'Fire-on-home window opens. Prepare the bold real-estate move.' },
  { name: 'Mars aspect Moon in 4th house : Exact', description: 'Peak fire-home day. Sign or close decisively; soften family communication.' },
  { name: 'Mars aspect Moon in 4th house : Ends', description: 'Fire-home window closes. Lock in the home and family decisions.' },
  { name: 'Mars aspect Mercury in 6th house', description: 'Fiery surgical-mind push. Win the conflict, settle the debt aggressively.' },
  { name: 'Mars aspect Mercury in 6th house : Starts', description: 'Fire-on-mind window opens. Prepare the technical fight.' },
  { name: 'Mars aspect Mercury in 6th house : Exact', description: 'Peak surgical-fire day. Defeat the rival; close the debt case.' },
  { name: 'Mars aspect Mercury in 6th house : Ends', description: 'Surgical-fire window closes. Lock in the conflict wins.' },
  { name: 'Mars aspect Venus in 12th house', description: 'Heated foreign, luxury, devotional zone. Behind-scenes power plays, foreign trade fights.' },
  { name: 'Mars aspect Venus in 12th house : Starts', description: 'Fire-on-foreign window opens. Prepare the hidden move.' },
  { name: 'Mars aspect Venus in 12th house : Exact', description: 'Peak fire-foreign day. Foreign or hidden battle peaks.' },
  { name: 'Mars aspect Venus in 12th house : Ends', description: 'Fire-foreign window closes. Lock in foreign and hidden wins.' },
  { name: 'Mars aspect Mars in 1st house', description: 'Peak self-action window of any two-year cycle. Founder declarations, body-anchored bold moves.' },
  { name: 'Mars aspect Mars in 1st house : Starts', description: 'Self-action window opens. Train hard; prepare the founder play.' },
  { name: 'Mars aspect Mars in 1st house : Exact', description: 'Peak self-action day. Take the founder action; sign the bold paper.' },
  { name: 'Mars aspect Mars in 1st house : Ends', description: 'Self-action window closes. Lock in the action.' },
  { name: 'Mars aspect Jupiter in 9th house', description: 'Fiery dharma push. Foreign-engagement aggression, certification fight, judicial-action decisive.' },
  { name: 'Mars aspect Jupiter in 9th house : Starts', description: 'Fire-on-mentor window opens. Prepare the dharma fight.' },
  { name: 'Mars aspect Jupiter in 9th house : Exact', description: 'Peak dharma-fire day. Win the judicial battle; force the visa.' },
  { name: 'Mars aspect Jupiter in 9th house : Ends', description: 'Dharma-fire window closes. Lock in the dharma wins.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Fiery career-mastery push. Bold career-zenith demands, founder-style chief-of-something asks.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Fire-on-career window opens. Prepare the executive demand.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak career-fire day. Demand the elevation; lead the pitch.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Career-fire window closes. Lock in title or compensation.' },
  { name: 'Mars aspect Rahu in 5th house', description: 'Fiery ambition with shadow. Bold speculative or fame-leaning moves; verify integrity twice.' },
  { name: 'Mars aspect Rahu in 5th house : Starts', description: 'Fire-on-ambition window opens. Vet the leap.' },
  { name: 'Mars aspect Rahu in 5th house : Exact', description: 'Peak fire-ambition day. Take the bold leap — anchor in dharma.' },
  { name: 'Mars aspect Rahu in 5th house : Ends', description: 'Fire-ambition window closes. Keep grounded wins.' },
  { name: 'Mars aspect Ketu in 11th house', description: 'Heated gain and network push with detachment. Bonus negotiation, board-position fight; expect emotional flatness.' },
  { name: 'Mars aspect Ketu in 11th house : Starts', description: 'Fire-on-detachment window opens. Push the gain hard.' },
  { name: 'Mars aspect Ketu in 11th house : Exact', description: 'Peak fire-detachment day. Win the bonus or board ask.' },
  { name: 'Mars aspect Ketu in 11th house : Ends', description: 'Fire-detachment window closes. Lock in the gain.' },
  { name: 'Jupiter aspect Sun in 5th house', description: 'Peak wisdom on creative-authority. Major creative launches, mentor-blessed speculative work, fame-anchored-in-dharma moments.' },
  { name: 'Jupiter aspect Sun in 5th house : Starts', description: 'Wisdom-on-creative window opens. Plan the principled launch.' },
  { name: 'Jupiter aspect Sun in 5th house : Exact', description: 'Peak wisdom-creative day. Launch with depth; the senior blessing arrives.' },
  { name: 'Jupiter aspect Sun in 5th house : Ends', description: 'Wisdom-creative window closes. Lock in the principled commitments.' },
  { name: 'Jupiter aspect Moon in 4th house', description: 'Wisdom-blessing on home, mother, real-estate. Buy the home, deepen with mother, expand the family business.' },
  { name: 'Jupiter aspect Moon in 4th house : Starts', description: 'Wisdom-on-home window opens. Plan the real-estate or family-business expansion.' },
  { name: 'Jupiter aspect Moon in 4th house : Exact', description: 'Peak home-blessing day. Sign the lease, finalize the family-business deal.' },
  { name: 'Jupiter aspect Moon in 4th house : Ends', description: 'Home-blessing window closes. Lock in the home commitments.' },
  { name: 'Jupiter aspect Mercury in 6th house', description: 'Wisdom on technical, conflict, service zone. Difficult clients become teachers; debt-resolution favored; HR-leadership advances.' },
  { name: 'Jupiter aspect Mercury in 6th house : Starts', description: 'Wisdom-on-mind window opens. Plan the major analytical project.' },
  { name: 'Jupiter aspect Mercury in 6th house : Exact', description: 'Peak wisdom-mind day. Publish the masterpiece; resolve the debt; lead the HR transformation.' },
  { name: 'Jupiter aspect Mercury in 6th house : Ends', description: 'Wisdom-mind window closes. Lock in the technical commitments.' },
  { name: 'Jupiter aspect Venus in 12th house', description: 'Peak foreign, luxury, devotional expansion. Foreign sabbatical, retreat-led work, hidden-patron emergence.' },
  { name: 'Jupiter aspect Venus in 12th house : Starts', description: 'Wisdom-on-foreign window opens. Plan the retreat or foreign sabbatical.' },
  { name: 'Jupiter aspect Venus in 12th house : Exact', description: 'Peak foreign-blessing day. Foreign offer lands; retreat-mandate clarifies.' },
  { name: 'Jupiter aspect Venus in 12th house : Ends', description: 'Wisdom-foreign window closes. Lock in foreign commitments.' },
  { name: 'Jupiter aspect Mars in 1st house', description: 'Wisdom on warrior identity. Founder-role expansion, public-mantle assumption.' },
  { name: 'Jupiter aspect Mars in 1st house : Starts', description: 'Wisdom-on-self window opens. Plan the founder-role elevation.' },
  { name: 'Jupiter aspect Mars in 1st house : Exact', description: 'Peak founder-blessing day. Accept the public mantle.' },
  { name: 'Jupiter aspect Mars in 1st house : Ends', description: 'Founder-blessing window closes. Lock in the role.' },
  { name: 'Jupiter aspect Jupiter in 9th house', description: 'Peak dharma window of any twelve-year cycle. Foreign-fortune, certification, judicial wins, publishing breakthroughs.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Starts', description: 'Dharma-return window opens. Plan the major foreign or principle-led move.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Exact', description: 'Peak dharma-return day. Take the foreign call; accept the senior blessing.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Ends', description: 'Dharma-return window closes. Lock in the dharma commitments.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on career-mastery. Take the chief role, the prestige offer, the elevation.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Wisdom-on-career window opens. Brief senior network.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak career-zenith day. Accept the chief-of-something role.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Career-zenith window closes. Lock in the elevation.' },
  { name: 'Jupiter aspect Rahu in 5th house', description: 'Wisdom on ambition. The fame-pull gets a guru; speculation tempers; fame anchors in dharma.' },
  { name: 'Jupiter aspect Rahu in 5th house : Starts', description: 'Wisdom-on-ambition window opens. Plan principled ambition.' },
  { name: 'Jupiter aspect Rahu in 5th house : Exact', description: 'Peak wisdom-ambition day. The fame-pull is checked by principle.' },
  { name: 'Jupiter aspect Rahu in 5th house : Ends', description: 'Wisdom-ambition window closes. Keep dharmic ambition.' },
  { name: 'Jupiter aspect Ketu in 11th house', description: 'Wisdom on detached gains. Bonus and equity events compound — feel them with equanimity.' },
  { name: 'Jupiter aspect Ketu in 11th house : Starts', description: 'Wisdom-on-detachment window opens. Receive without grasping.' },
  { name: 'Jupiter aspect Ketu in 11th house : Exact', description: 'Peak wisdom-detachment day. Major gain lands; honor without clinging.' },
  { name: 'Jupiter aspect Ketu in 11th house : Ends', description: 'Wisdom-detachment window closes. Cleaner gains-orientation locked.' },
  { name: 'Saturn aspect Sun in 5th house', description: 'Structural test of creative-authority. Speculation tightens; mentee relationships restructure; ambitions earn slow.' },
  { name: 'Saturn aspect Sun in 5th house : Starts', description: 'Discipline-on-creative window opens. Audit the speculative book.' },
  { name: 'Saturn aspect Sun in 5th house : Exact', description: 'Peak discipline-creative day. The fame-pull is structurally checked. Build for permanence.' },
  { name: 'Saturn aspect Sun in 5th house : Ends', description: 'Discipline-creative window closes. Cleaner creative engine remains.' },
  { name: 'Saturn aspect Moon in 4th house', description: 'Heaviness on home and mother. Mother-related responsibility intensifies; real-estate decisions feel structural.' },
  { name: 'Saturn aspect Moon in 4th house : Starts', description: 'Discipline-on-home window opens. Prepare for slow, heavy home and family chapter.' },
  { name: 'Saturn aspect Moon in 4th house : Exact', description: 'Peak discipline-home day. Mother needs care; real-estate restructures.' },
  { name: 'Saturn aspect Moon in 4th house : Ends', description: 'Discipline-home window closes. The structural home foundation set.' },
  { name: 'Saturn aspect Mercury in 6th house', description: 'Favorable for service-mastery. Best window for building audit and regulatory authority, settling long-debts, leading HR transformation.' },
  { name: 'Saturn aspect Mercury in 6th house : Starts', description: 'Discipline-on-mind window opens. Plan the multi-year audit and regulatory build.' },
  { name: 'Saturn aspect Mercury in 6th house : Exact', description: 'Peak discipline-mind day. The structural audit or case lands.' },
  { name: 'Saturn aspect Mercury in 6th house : Ends', description: 'Discipline-mind window closes. Lock in the structural-technical wins.' },
  { name: 'Saturn aspect Venus in 12th house', description: 'Multi-year discipline on foreign, devotional, luxury. Sabbaticals turn structural; foreign work formalizes; pleasure-spending audits.' },
  { name: 'Saturn aspect Venus in 12th house : Starts', description: 'Discipline-on-foreign window opens. Audit foreign and luxury commitments.' },
  { name: 'Saturn aspect Venus in 12th house : Exact', description: 'Peak discipline-foreign day. Foreign mandate formalizes; retreat structures.' },
  { name: 'Saturn aspect Venus in 12th house : Ends', description: 'Discipline-foreign window closes. Lock in foreign or devotional structures.' },
  { name: 'Saturn aspect Mars in 1st house', description: 'Heavy structural test of warrior identity. Slow founder-craft; body-discipline; permanence over speed.' },
  { name: 'Saturn aspect Mars in 1st house : Starts', description: 'Discipline-on-self window opens. Slow the founder-pace; build for years.' },
  { name: 'Saturn aspect Mars in 1st house : Exact', description: 'Peak discipline-self day. The founder-engine is tested for staying power.' },
  { name: 'Saturn aspect Mars in 1st house : Ends', description: 'Discipline-self window closes. The structural founder-foundation set.' },
  { name: 'Saturn aspect Jupiter in 9th house', description: 'Multi-year discipline on dharma, foreign, teacher domain. Slow visa or certification process; gurus age; principles tested.' },
  { name: 'Saturn aspect Jupiter in 9th house : Starts', description: 'Discipline-on-mentor window opens. Prepare for slow dharma chapter.' },
  { name: 'Saturn aspect Jupiter in 9th house : Exact', description: 'Peak discipline-mentor day. The principle is tested under structural pressure.' },
  { name: 'Saturn aspect Jupiter in 9th house : Ends', description: 'Discipline-mentor window closes. The principles that survived are permanent.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Peak career-restructure window of any thirty-year cycle. The chief-role assumption, the long-platform foundation.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Career-restructure window opens. Plan for the long-arc structure.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak career-restructure day. Accept the multi-decade career chapter.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Career-restructure window closes. The career-structure permanently reset.' },
  { name: 'Saturn aspect Rahu in 5th house', description: 'Discipline on ambition. Speculative bubbles deflate; fame-grasping cools; structural ambition crystallizes.' },
  { name: 'Saturn aspect Rahu in 5th house : Starts', description: 'Discipline-on-ambition window opens. Audit ambition.' },
  { name: 'Saturn aspect Rahu in 5th house : Exact', description: 'Peak discipline-ambition day. The fame-bubble pops; structural ambition remains.' },
  { name: 'Saturn aspect Rahu in 5th house : Ends', description: 'Discipline-ambition window closes. Cleaner ambition locked.' },
  { name: 'Saturn aspect Ketu in 11th house', description: 'Disciplined, structural gains; the network purges what is no longer dharmic.' },
  { name: 'Saturn aspect Ketu in 11th house : Starts', description: 'Discipline-on-detachment window opens. Audit the network.' },
  { name: 'Saturn aspect Ketu in 11th house : Exact', description: 'Peak discipline-detachment day. The structural gain locks in; the obsolete falls away.' },
  { name: 'Saturn aspect Ketu in 11th house : Ends', description: 'Discipline-detachment window closes. Cleaner gains-platform set.' },
  { name: 'Rahu aspect Sun in 5th house', description: 'Peak ambition window of any eighteen-year cycle. Creative fame, speculative obsession, mentee-frenzy. Verify dharma.' },
  { name: 'Rahu aspect Sun in 5th house : Starts', description: 'Ambition-return window opens. Beware spectacle obsession.' },
  { name: 'Rahu aspect Sun in 5th house : Exact', description: 'Peak ambition-return day. The fame-leap presents — verify integrity.' },
  { name: 'Rahu aspect Sun in 5th house : Ends', description: 'Ambition-return window closes. Keep dharmic ambition; release vanity.' },
  { name: 'Rahu aspect Moon in 4th house', description: 'Obsessive home, mother, real-estate chapter. Foreign relocation pull, mother-obsession, family-business turbulence.' },
  { name: 'Rahu aspect Moon in 4th house : Starts', description: 'Reinvention-on-home window opens. Verify big home and relocation moves.' },
  { name: 'Rahu aspect Moon in 4th house : Exact', description: 'Peak reinvention-home day. The foreign-relocation pull peaks.' },
  { name: 'Rahu aspect Moon in 4th house : Ends', description: 'Reinvention-home window closes. Keep grounded home-decisions.' },
  { name: 'Rahu aspect Mercury in 6th house', description: 'Favorable. Defeat a powerful enemy, big debt-recovery, regulatory victory, HR transformation.' },
  { name: 'Rahu aspect Mercury in 6th house : Starts', description: 'Reinvention-on-mind window opens. Prepare for big enemy and debt fight.' },
  { name: 'Rahu aspect Mercury in 6th house : Exact', description: 'Peak reinvention-mind day. Major adversary or debt yields.' },
  { name: 'Rahu aspect Mercury in 6th house : Ends', description: 'Reinvention-mind window closes. Lock in the enemy and debt wins.' },
  { name: 'Rahu aspect Venus in 12th house', description: 'Obsessive foreign, luxury, devotional pull. Foreign relocation, hidden-patron pursuits, retreat-driven careers.' },
  { name: 'Rahu aspect Venus in 12th house : Starts', description: 'Reinvention-on-foreign window opens. Verify foreign moves carefully.' },
  { name: 'Rahu aspect Venus in 12th house : Exact', description: 'Peak reinvention-foreign day. The foreign-fortune pull peaks.' },
  { name: 'Rahu aspect Venus in 12th house : Ends', description: 'Reinvention-foreign window closes. Lock in the legitimate foreign moves.' },
  { name: 'Rahu aspect Mars in 1st house', description: 'Obsessive founder-identity push. New persona, new ambition. Verify before declaring.' },
  { name: 'Rahu aspect Mars in 1st house : Starts', description: 'Reinvention-on-self window opens. Beware impulsive founder declarations.' },
  { name: 'Rahu aspect Mars in 1st house : Exact', description: 'Peak reinvention-self day. The founder-leap presents — verify.' },
  { name: 'Rahu aspect Mars in 1st house : Ends', description: 'Reinvention-self window closes. Keep grounded founder-moves.' },
  { name: 'Rahu aspect Jupiter in 9th house', description: 'Foreign-fortune obsession. Sudden international expansion, controversial guru, certification-fight.' },
  { name: 'Rahu aspect Jupiter in 9th house : Starts', description: 'Reinvention-on-mentor window opens. Vet the dharma channel.' },
  { name: 'Rahu aspect Jupiter in 9th house : Exact', description: 'Peak reinvention-mentor day. The foreign-fortune leap presents.' },
  { name: 'Rahu aspect Jupiter in 9th house : Ends', description: 'Reinvention-mentor window closes. Keep principled foreign moves.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Obsessive career-elevation push. Sudden promotion offers, foreign career-pull, unconventional executive offers.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Reinvention-on-career window opens. Vet the executive offer.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak reinvention-career day. The bold career-leap presents — verify.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Reinvention-career window closes. Lock in legitimate elevation.' },
  { name: 'Rahu aspect Rahu in 5th house', description: 'Eighteen-year apex of the ambition cycle. The fame, speculation, mentor-obsession peaks. Anchor in dharma.' },
  { name: 'Rahu aspect Rahu in 5th house : Starts', description: 'Ambition-cycle peak window opens. Watch for spectacle obsession.' },
  { name: 'Rahu aspect Rahu in 5th house : Exact', description: 'Peak ambition-cycle day. The cycle peaks. Verify dharma.' },
  { name: 'Rahu aspect Rahu in 5th house : Ends', description: 'Ambition-cycle window closes. Cleaner ambition cycle begins.' },
  { name: 'Rahu aspect Ketu in 11th house', description: 'Generational reckoning of gains and networks vs. ambitions. Career-defining bonus events; networks reorganize.' },
  { name: 'Rahu aspect Ketu in 11th house : Starts', description: 'Generational reckoning begins. Major network and gains reckoning ahead.' },
  { name: 'Rahu aspect Ketu in 11th house : Exact', description: 'Peak reckoning day. Career-defining gain event lands; old network dissolves.' },
  { name: 'Rahu aspect Ketu in 11th house : Ends', description: 'Reckoning window closes. New gains-platform locked.' },
  { name: 'Ketu aspect Sun in 5th house', description: 'Creative-authority eclipse. Old creative ambition feels hollow; mentee-pull fades; speculation loses charge.' },
  { name: 'Ketu aspect Sun in 5th house : Starts', description: 'Eclipse-on-creative window opens. The fame-pull cools.' },
  { name: 'Ketu aspect Sun in 5th house : Exact', description: 'Peak eclipse-creative day. The old ambition dissolves; cleaner creativity remains.' },
  { name: 'Ketu aspect Sun in 5th house : Ends', description: 'Eclipse-creative window closes. Cleaner creative engine resumes.' },
  { name: 'Ketu aspect Moon in 4th house', description: 'Home and mother detachment. Sell-property impulses, mother\'s independence, leave-the-city signals.' },
  { name: 'Ketu aspect Moon in 4th house : Starts', description: 'Eclipse-on-home window opens. Consider what to release.' },
  { name: 'Ketu aspect Moon in 4th house : Exact', description: 'Peak eclipse-home day. The simplification impulse peaks.' },
  { name: 'Ketu aspect Moon in 4th house : Ends', description: 'Eclipse-home window closes. The leaner home-base persists.' },
  { name: 'Ketu aspect Mercury in 6th house', description: 'Service detachment. Old conflicts dissolve without victory; debts written off; HR cases close quietly.' },
  { name: 'Ketu aspect Mercury in 6th house : Starts', description: 'Eclipse-on-mind window opens. Don\'t over-defend old conflicts.' },
  { name: 'Ketu aspect Mercury in 6th house : Exact', description: 'Peak eclipse-mind day. Old enemies disengage on their own.' },
  { name: 'Ketu aspect Mercury in 6th house : Ends', description: 'Eclipse-mind window closes. Cleaner conflict-platform resumes.' },
  { name: 'Ketu aspect Venus in 12th house', description: 'Foreign, luxury, devotional dissolution. Pilgrimage-pull, pleasure-spending evaporation, hidden-channel closure.' },
  { name: 'Ketu aspect Venus in 12th house : Starts', description: 'Eclipse-on-foreign window opens. The retreat-impulse rises.' },
  { name: 'Ketu aspect Venus in 12th house : Exact', description: 'Peak eclipse-foreign day. Old foreign or pleasure channel closes.' },
  { name: 'Ketu aspect Venus in 12th house : Ends', description: 'Eclipse-foreign window closes. Cleaner foreign-channel resumes.' },
  { name: 'Ketu aspect Mars in 1st house', description: 'Founder-identity stripping. The old warrior-persona feels finished.' },
  { name: 'Ketu aspect Mars in 1st house : Starts', description: 'Eclipse-on-self window opens. Don\'t over-defend the old founder-role.' },
  { name: 'Ketu aspect Mars in 1st house : Exact', description: 'Peak eclipse-self day. Old founder-identity dissolves.' },
  { name: 'Ketu aspect Mars in 1st house : Ends', description: 'Eclipse-self window closes. Cleaner founder-platform emerges.' },
  { name: 'Ketu aspect Jupiter in 9th house', description: 'Dharma detachment. Old gurus feel finished; foreign-fortune ambitions cool; principle-without-attachment ripens.' },
  { name: 'Ketu aspect Jupiter in 9th house : Starts', description: 'Eclipse-on-mentor window opens. The senior-relationship recalibrates.' },
  { name: 'Ketu aspect Jupiter in 9th house : Exact', description: 'Peak eclipse-mentor day. Old principle dissolves; cleaner dharma emerges.' },
  { name: 'Ketu aspect Jupiter in 9th house : Ends', description: 'Eclipse-mentor window closes. Cleaner dharma-platform resumes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Career eclipse. Old roles feel hollow; promotions feel weightless; layoffs happen quietly.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Eclipse-on-career window opens. Don\'t over-defend the old role.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak eclipse-career day. The role dissolves; cleaner career-platform emerges.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Eclipse-career window closes. The leaner career-engine remains.' },
  { name: 'Ketu aspect Rahu in 5th house', description: 'Generational ambition vs. detachment reckoning. Old fame-grasping dissolves; cleaner creative engine.' },
  { name: 'Ketu aspect Rahu in 5th house : Starts', description: 'Reckoning-on-ambition window opens. Watch the dissolution carefully.' },
  { name: 'Ketu aspect Rahu in 5th house : Exact', description: 'Peak reckoning day. Old ambition cycle ends; new one seeds.' },
  { name: 'Ketu aspect Rahu in 5th house : Ends', description: 'Reckoning-on-ambition window closes. Cleaner ambition seeded.' },
  { name: 'Ketu aspect Ketu in 11th house', description: 'Eighteen-year apex of the detachment cycle. Network purification, gains-orientation cleanse, friend-letting-go peaks.' },
  { name: 'Ketu aspect Ketu in 11th house : Starts', description: 'Detachment-cycle peak window opens. The network-dissolution begins.' },
  { name: 'Ketu aspect Ketu in 11th house : Exact', description: 'Peak detachment-cycle day. The old network and gain orientation completes.' },
  { name: 'Ketu aspect Ketu in 11th house : Ends', description: 'Detachment-cycle window closes. Cleaner gains-platform locked.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} career] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
