// db/seed_advice_sagittarius.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Sagittarius ascendant native with:
//   Ascendant: Sagittarius
//   Natal placements (sidereal Lahiri):
//     Sun=9th (Leo, own)  Moon=8th (Cancer, own)
//     Mercury=10th (Virgo, own+exalted — Bhadra + yogakaraka)
//     Venus=11th (Libra, own)  Mars=5th (Aries, own)
//     Jupiter=1st (Sagittarius, own — Hamsa Mahapurusha Yoga)
//     Saturn=2nd (Capricorn, own)
//     Rahu=6th (Taurus)  Ketu=12th (Scorpio)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose advice-specific interpretations, then run:
//
//   node db/seed_advice_sagittarius.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./advice');

const ASCENDANT = 'Sagittarius';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter ruler of the 1st House in the 1st House', description: 'Teach today. Whatever you know that someone else needs — share it openly. Take the public-mantle step you have been deferring; the body itself reads as authoritative right now and people defer accordingly. Skip meetings that exist only to confirm what you already know. The principle is your edge; small-talk is a tax.' },
  { name: 'Saturn ruler of the 2nd House in the 2nd House', description: 'Speak slowly about money today. Family-finance conversation, salary case, joint-budget discussion — all land well in writing or in person if measured. Defer impulsive purchases twenty-four hours; the slow rail compounds. Vocal-care matters; honey, ghee, soothing teas if speaking publicly.' },
  { name: 'Saturn ruler of the 3rd House in the 2nd House', description: 'Send the structured message today. The methodical document beats the chatty email; the prepared brief beats the off-the-cuff remark. Younger siblings or peer-cohort respond when authority is paired with structure. Avoid sharp text exchanges — write it long-form or wait.' },
  { name: 'Jupiter ruler of the 4th House in the 1st House', description: 'Tend to the home as an extension of self today. The dwelling-and-body share weather; what nourishes one nourishes the other. Mother-call favored; family-business decisions land well. Real-estate paperwork carries weight when signed today.' },
  { name: 'Mars ruler of the 5th House in the 5th House', description: 'Move boldly on the creative front today. Pitch the speculative idea; lead the mentee; ship the creative project that has been sitting; sign the bold paper. The energy runs hot — channel into action, not into argument.' },
  { name: 'Venus ruler of the 6th House in the 11th House', description: 'Tend to the friend-network today. The senior-female mentor wants a check-in; the gathering you have been postponing wants a yes. Conflict-resolution lands gracefully through the group rather than directly — route through the mutual ally.' },
  { name: 'Mercury ruler of the 7th House in the 10th House', description: 'Negotiate the public-couple front today. Joint announcements, partnership term-sheets, formal alliance papers, brand-couple polish. The voice is sharp at MC; deploy precision in writing.' },
  { name: 'Moon ruler of the 8th House in the 8th House', description: 'Go to the depths today. The deferred succession conversation, the in-law issue, the shared-resource confusion — face it. Emotional fluency in the dark water is your edge. Avoid surface-only social interactions; they will feel hollow.' },
  { name: 'Sun ruler of the 9th House in the 9th House', description: 'Honor the principle today. Where there is a choice between expedience and dharma, choose dharma — even at visible cost. Foreign or higher-learning conversations, mentor-meetings, ceremonial commitments all land well. The father-figure or guru-figure may surface with a decisive word.' },
  { name: 'Mercury ruler of the 10th House in the 10th House', description: 'Publish the precise document today. The career-defining brief, the executive memo, the press release, the formal status update — all carry weight. Voice-care matters; rest the throat; eat lightly before public engagements.' },
  { name: 'Venus ruler of the 11th House in the 11th House', description: 'Cultivate the gain-channel today. Bonus-conversation, board-position ask, equity discussion, female-mentor call. Group friendships outweigh tight pairs today. Aesthetic gatherings carry network weight.' },
  { name: 'Mars ruler of the 12th House in the 5th House', description: 'Move on the hidden-creative front today. Behind-scenes work that feeds the public creative output — the early-morning writing, the foreign-trip drafting, the retreat-time speculation. Pleasure-spending should be disciplined; the creative output is the real return.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 9th (Dispositor)', description: 'Choose the principle today. Foreign-fortune favors the dharmic move; expedience costs you for years. Make the principled call, take the foreign meeting, honor the mentor.' },
  { name: 'Moon in 8th (Dispositor)', description: 'Sit with the depth today. Old emotional patterns, in-law dynamics, shared-resource anxieties surface. Don\'t paper over with action; honor with quiet.' },
  { name: 'Mercury in 10th (Dispositor)', description: 'Publish the precise piece today. The career document, the public statement, the brand-defining brief — ship it.' },
  { name: 'Venus in 11th (Dispositor)', description: 'Tend to the gain-network today. Group gathering, senior-female mentor call, aesthetic-network move.' },
  { name: 'Mars in 5th (Dispositor)', description: 'Take the bold creative leap today. The founder move, the speculative bet, the protégé-direction. Verify, then lead.' },
  { name: 'Jupiter in 1st (Dispositor)', description: 'Teach today. The public-mantle step, the principled declaration, the wisdom-sharing. The body radiates authority.' },
  { name: 'Saturn in 2nd (Dispositor)', description: 'Honor the slow rail today. Defer the impulse twenty-four hours; the structural move compounds.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual visibility window. Lead with the wise-self; take on a public-mantle role; declare the larger principle that organizes this year.' },
  { name: 'Sun Transits the 2nd House', description: 'Speak about slow-money openly. Compensation cases, family-finance settlements, voice-led income work all favored.' },
  { name: 'Sun Transits the 3rd House', description: 'Push the courageous communication. The methodical letter, the deferred sibling message, the bold peer-proposal — all favored.' },
  { name: 'Sun Transits the 4th House', description: 'Anchor in home and mother for the month. Real-estate decisions, family-business inflection, work-from-home phase favored.' },
  { name: 'Sun Transits the 5th House', description: 'Annual peak creative-visibility — Sun joining your natal Mars. Launch, declare, propose, perform. Take the bold creative stage.' },
  { name: 'Sun Transits the 6th House', description: 'Best window of the year for confronting conflict — Sun on natal Rahu. The audit, the difficult HR talk, the regulatory filing, the long-running adversary case — all close cleanly.' },
  { name: 'Sun Transits the 7th House', description: 'Annual peak partnership window. Sign the JV; close the partnership conversation; formalize the alliance. Watch ego friction with the spouse.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light on transformation — Sun on natal Moon. Inheritance, succession, deep intimacy conversations surface for clarification.' },
  { name: 'Sun Transits the 9th House', description: 'Annual peak dharma window — Sun returning to its own sign in own house. Foreign-fortune moves, judicial proceedings, certification breakthroughs, mentor-blessings cluster.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career window — Sun on natal Mercury at MC. Launch the flagship; demand the title bump; lead the competitive pitch.' },
  { name: 'Sun Transits the 11th House', description: 'Sun on natal Venus — peak gain-and-network month. Bonus conversations, equity events, board-news. Senior-female mentors weigh in.' },
  { name: 'Sun Transits the 12th House', description: 'Sun on natal Ketu — visibility dims; foreign correspondence, retreats, behind-scenes work favored. Sleep more.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional charge on persona. Lead with warmth; the body and mood are linked today.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional warmth on slow-money. Speak with measured care; family-money conversations land softer.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional warmth with siblings and peer-cohort. Send the warm message; make the gentle call.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-emotional peak. Cook, call mother, tend the dwelling.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative authority — Moon on natal Mars. Heart-led creative push; protégé-warmth wave; avoid impulsive moves.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge in the conflict zone — Moon on natal Rahu. Empathetic conflict-resolution; soft repair work.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnerships. Read the partner mood; warmth wins what aggression loses.' },
  { name: 'Moon Transits the 8th House', description: 'Moon return in own sign in own house — peak emotional-intimacy window. Honor depth conversations.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma — Moon on natal Sun. Big-vision dreams; values-conversations land warm.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on public reputation — Moon on natal Mercury at MC. The room reads you today.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth on the friend-network — Moon on natal Venus. Reach out; accept the invite.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional charge on retreat-zone — Moon on natal Ketu. Sleep more, deepen privately.' },
  { name: 'Mercury Transits the 1st House', description: 'Mind-on-self window — Mercury on natal Jupiter. Refresh the wise-self narrative; principled personal post.' },
  { name: 'Mercury Transits the 2nd House', description: 'Mercury on natal Saturn — disciplined slow-money planning. Compensation cases, family-finance paperwork, structural budget review.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak writing and peer-leadership window. Ship the document, publish the analysis, send the proposal.' },
  { name: 'Mercury Transits the 4th House', description: 'Emotionally attuned home and family-paperwork. Lease drafts, mother-correspondence.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury on natal Mars — bold creative communication. Pitch the speculative idea; punchy creative brief.' },
  { name: 'Mercury Transits the 6th House', description: 'Mercury on natal Rahu — peak surgical-mind window. Audit reports, regulatory filings, technical specs.' },
  { name: 'Mercury Transits the 7th House', description: 'Mercury return in own sign — peak partnership-communication. Term-sheets, JV drafts, mediation letters.' },
  { name: 'Mercury Transits the 8th House', description: 'Mercury on natal Moon — depth-writing. Forensic reports, due-diligence, taxation drafts.' },
  { name: 'Mercury Transits the 9th House', description: 'Mercury on natal Sun — visionary writing. Foreign correspondence, philosophical drafts, judicial filings.' },
  { name: 'Mercury Transits the 10th House', description: 'Mercury return at MC — peak career-communication. Press releases, executive memos, status updates.' },
  { name: 'Mercury Transits the 11th House', description: 'Mercury on natal Venus — graceful network communication. Senior-network outreach, friend-circle correspondence.' },
  { name: 'Mercury Transits the 12th House', description: 'Mercury on natal Ketu — confidential, foreign correspondence. NDAs, off-record briefings.' },
  { name: 'Venus Transits the 1st House', description: 'Warmth on the wise-self — Venus on natal Jupiter. Excellent for charm-asks, client-meetings, branding updates.' },
  { name: 'Venus Transits the 2nd House', description: 'Soft income window — Venus on natal Saturn. Salary asks land softer; family-money diplomatic ease.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful sibling and peer-warmth. Sales correspondence, mentoring conversations.' },
  { name: 'Venus Transits the 4th House', description: 'Beautiful home, real-estate, mother window. Sign the lease, beautify the office, host.' },
  { name: 'Venus Transits the 5th House', description: 'Venus on natal Mars — peak romance-aesthetic visibility. Beautiful date-meal, creative-romantic gesture.' },
  { name: 'Venus Transits the 6th House', description: 'Venus on natal Rahu — diplomatic conflict-resolution. Difficult colleague becomes warm ally.' },
  { name: 'Venus Transits the 7th House', description: 'Peak partnership window. Sign the JV; close the long-pending alliance.' },
  { name: 'Venus Transits the 8th House', description: 'Venus on natal Moon — diplomatic intimacy and shared-resource navigation.' },
  { name: 'Venus Transits the 9th House', description: 'Venus on natal Sun — graceful foreign-engagement, ceremonial commitment.' },
  { name: 'Venus Transits the 10th House', description: 'Venus on natal Mercury at MC — softens the public face. Brand-couple polish.' },
  { name: 'Venus Transits the 11th House', description: 'Venus return to own sign — peak gain-and-friend-network warmth.' },
  { name: 'Venus Transits the 12th House', description: 'Venus on natal Ketu — annual peak foreign, hidden, devotional window.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on natal Jupiter — body-anchored bold action. Founder-style commitment-asks; principled declarations.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on natal Saturn — heated income battles. Aggressive salary asks possible but data-back them.' },
  { name: 'Mars Transits the 3rd House', description: 'Sharp peer-and-sibling push. Confrontations possible; defend the document.' },
  { name: 'Mars Transits the 4th House', description: 'Heated home-base disputes flare and resolve. Decisive real-estate action; watch family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Mars return on natal Mars — peak performance fire. Bold creative push; calculated speculative leap.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on natal Rahu — favorable conflict combat. Win the long workplace dispute.' },
  { name: 'Mars Transits the 7th House', description: 'Friction in partnerships. Hard to negotiate cleanly; defer the contract close seven days.' },
  { name: 'Mars Transits the 8th House', description: 'Mars on natal Moon — surgical action on transformation. Restructurings, succession battles.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on natal Sun — bold dharma-action. Foreign-engagement push, principled fight.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on natal Mercury at MC — strongest career-action window. Launch flagship, demand elevation.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on natal Venus — assertive gain push. Bonus negotiations, board-position asks.' },
  { name: 'Mars Transits the 12th House', description: 'Mars on natal Ketu — heated foreign, hidden zone. Behind-scenes power plays.' },
  { name: 'Jupiter Transits the 1st House', description: 'Jupiter return in own sign in lagna — most blessed annual window. Take the role expansion; declare the bigger ambition.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Jupiter on natal Saturn — wisdom-blessing on slow-income. Compensation, family-wealth structuring expand.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on writing, peers, short-burst effort. Major publication, mentee placements.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter return in own sign in 4H — peak home-expansion year. Buy the home; deepen with mother.' },
  { name: 'Jupiter Transits the 5th House', description: 'Jupiter on natal Mars — major creative-launch year. Mentee placements, advisory ascensions.' },
  { name: 'Jupiter Transits the 6th House', description: 'Jupiter on natal Rahu — wisdom in service-and-conflict zone. Health watch.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom into partnership zone. Anchor partnership, prestige-client signing.' },
  { name: 'Jupiter Transits the 8th House', description: 'Jupiter on natal Moon — wisdom into transformation. Inheritance, severance, equity favorably resolve.' },
  { name: 'Jupiter Transits the 9th House', description: 'Jupiter on natal Sun in own sign — among the most blessed windows of any twelve-year cycle. Foreign expansion, judicial wins.' },
  { name: 'Jupiter Transits the 10th House', description: 'Jupiter on natal Mercury at MC — peak career-zenith year. Take the chief role.' },
  { name: 'Jupiter Transits the 11th House', description: 'Jupiter on natal Venus — wisdom-blessing on gain-zone. Bonus pools, equity vesting compound.' },
  { name: 'Jupiter Transits the 12th House', description: 'Jupiter on natal Ketu — peak foreign, devotional year. Foreign sabbatical, retreat-led work.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn over natal Jupiter — multi-year structural pressure on body and persona. Slow simplification.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn return in own sign in 2H — multi-year discipline on slow-income. Structural family-money decisions.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn in own sign Aquarius — multi-year discipline on writing, peers. Long-form authorship builds.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy emotional-home weight; mother-related responsibility intensifies.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn over natal Mars — creative authority tested. Mentee relationships restructure.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn over natal Rahu — best multi-year window for resolving long conflicts.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnerships. Long-arc business unions.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn over natal Moon — major emotional-restructuring window. Patience compounds.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn over natal Sun — multi-year discipline on dharma. Father-figure restructures.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn over natal Mercury at MC — the 2.5-year window seeding the next 30-year career chapter.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn over natal Venus — disciplined structural gains. Network purges what is not dharmic.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn over natal Ketu — multi-year discipline on foreign, hidden, devotional channels.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu over natal Jupiter — eighteen-month obsessive self-reinvention. Verify each leap.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu over natal Saturn — obsessive ambition around income. Beware get-rich-quick.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive communication push. Viral content; verify before publishing.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home, real-estate, mother chapter. Foreign relocation pull strong.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu over natal Mars — eighteen-month peak ambition window for creative fame.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu return on its own placement — favorable for dramatic conflict-resolution.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive partnership chapter. Foreign partner pull; verify carefully.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu over natal Moon — obsessive transformation chapter.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu over natal Sun — foreign-fortune obsession. Vet the dharma channel.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu over natal Mercury at MC — obsessive career-elevation push.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu over natal Venus — obsessive gain-and-network chapter.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu over natal Ketu — obsessive foreign, hidden chapter.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu over natal Jupiter — eighteen-month identity-stripping window. Sit; do not over-rebuild.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu over natal Saturn — detachment from income, voice. Don\'t panic-renegotiate.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from peers, writing. Solo deep-work favored.' },
  { name: 'Ketu Transits the 4th House', description: 'Home and mother detachment. Sell-property impulses.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu over natal Mars — creative-authority eclipse.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu opposite Rahu — service detachment. Old conflicts dissolve.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership detachment. Old commitments unwind.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu over natal Moon — transformation acceleration.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu over natal Sun — dharma detachment. Old gurus feel finished.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu over natal Mercury at MC — career eclipse.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu over natal Venus — eighteen-month deep purification of network.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu return on its own placement — foreign, devotional dissolution at peak.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through the wise-self. Take the public step.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish the public-facing materials.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the stage, declare the role.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Convert visibility into binding commitment.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Peak career-visibility. Launch flagship; demand title-elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens. Brief the boss; plan the upward move.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-visibility day. Take the elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-visibility window closes. Lock in title or compensation moves.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Warm reception possible.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens. Prepare to be felt.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Warmth lands.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes. Lock in connections.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public reputation; warm career news possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional career window opens. Senior-network warmth rises.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional career day. Warm-toned client meeting.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional career window closes. Move warm leads into formal commitments.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-communication. Personal-brand updates favored.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Mind-on-self window opens. Refresh the bio.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak self-communication day. Send the bold intro letter.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mind-on-self window closes. Lock in personal-brand commitments.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp career-communication. Press releases, status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-communication window opens. Prepare the public message.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak career-communication day. Publish, present.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-communication window closes. Convert messaging into commitment.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Warmth on persona. Charm-asks favored.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Charm-self window opens. Prepare the diplomatic outreach.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. Make the warm ask.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm-self window closes. Convert warmth into binding agreements.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens the public face. Brand campaigns favored.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-career window opens. Plan the brand refresh.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-career day. Launch the campaign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-career window closes. Lock in design commitments.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold self-action; founder declarations.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens. Train; prepare the bold move.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Sign the bold paper.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes. Lock in the action.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold career action. Launch flagship initiatives.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens. Prepare the bold play.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak career-action day. Launch, demand, lead.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action window closes. Convert moves into permanent positions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the role-elevation.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens. Plan the public-mantle.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the elevation.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes. Lock in the title.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the chief role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion window opens. Brief the senior network.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day. Accept the chief-of-something role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion window closes. Convert offers into binding commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity. Slow down.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens. Eliminate vanity commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public work tested for staying power. Slow recognition.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline window opens. Structure work for years.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak career-discipline day. Foundation laid.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-discipline window closes. Convert effort into title.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion. Foreign or unconventional self emerges.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window begins. Sudden ambition.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak reinvention day. Unconventional move — check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes. Decide which experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic visibility expansion. Sudden promotions.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Career-reinvention window begins. Vet unconventional offers.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak career-reinvention day. Verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Career-reinvention window closes. Lock in legitimate pivots.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. Old wise-teacher persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens. Pull to step away rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak stripping day. Sit with the dissolution.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes. Move forward leaner.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. Promotions stall.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse window begins. Don\'t over-defend a role wanting to end.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak career-eclipse day. Role dissolves quietly.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse window closes. Move forward to cleaner platform.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting your slow-income engine. Industry-wide hierarchies collapse. Hold structural patience as peers panic.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on income engine. Position for the long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day. Old wage system breaks; new one is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Income-transformation chapter completes. Rebuilt foundation survives shocks.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption in gain-and-network channel. Unexpected bonus, board invitations.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden disruption window opens on gains. Expect surprise mentor moves.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. Equity event lands; senior-female mentor delivers an unannounced lift.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption window closes on gains. Integrate the changes.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 9th house', description: 'Annual dharma-window. Sign the principled commitment, take the foreign meeting, honor the mentor.' },
  { name: 'Sun aspect Sun in 9th house : Starts', description: 'Annual dharma-window opens. Plan the year\'s flagship principled move.' },
  { name: 'Sun aspect Sun in 9th house : Exact', description: 'Peak dharma day. Sign the international commitment.' },
  { name: 'Sun aspect Sun in 9th house : Ends', description: 'Dharma window closes. Lock in the year\'s ethical commitments.' },
  { name: 'Sun aspect Moon in 8th house', description: 'Visibility through transformation. Inheritance, succession, deep-intimacy conversations.' },
  { name: 'Sun aspect Moon in 8th house : Starts', description: 'Transformation-visibility window opens. Prepare for chapter-ending conversation.' },
  { name: 'Sun aspect Moon in 8th house : Exact', description: 'Peak transformation-visibility day. Sign the succession papers.' },
  { name: 'Sun aspect Moon in 8th house : Ends', description: 'Transformation-visibility window closes. Lock in the chapter-ending commitments.' },
  { name: 'Sun aspect Mercury in 10th house', description: 'Solar fire on career-zenith. Press releases, executive briefings peak.' },
  { name: 'Sun aspect Mercury in 10th house : Starts', description: 'Career-zenith window opens. Polish the executive materials.' },
  { name: 'Sun aspect Mercury in 10th house : Exact', description: 'Peak career-zenith day. Accept the elevation.' },
  { name: 'Sun aspect Mercury in 10th house : Ends', description: 'Career-zenith window closes. Lock in title and compensation.' },
  { name: 'Sun aspect Venus in 11th house', description: 'Solar light on gains. Bonus announcements, equity events, board-news.' },
  { name: 'Sun aspect Venus in 11th house : Starts', description: 'Gain-visibility window opens. Brief the senior network.' },
  { name: 'Sun aspect Venus in 11th house : Exact', description: 'Peak gain day. Accept the bonus, sign the equity, take the board seat.' },
  { name: 'Sun aspect Venus in 11th house : Ends', description: 'Gain-visibility window closes. Lock in gain commitments.' },
  { name: 'Sun aspect Mars in 5th house', description: 'Solar fire on creative authority. Bold creative moves, mentee-direction.' },
  { name: 'Sun aspect Mars in 5th house : Starts', description: 'Creative-fire window opens. Train; prepare the bold move.' },
  { name: 'Sun aspect Mars in 5th house : Exact', description: 'Peak creative-fire day. Lead the launch.' },
  { name: 'Sun aspect Mars in 5th house : Ends', description: 'Creative-fire window closes. Lock in the creative commitments.' },
  { name: 'Sun aspect Jupiter in 1st house', description: 'Solar light on the wise-self in lagna. Public-mantle assumption favored.' },
  { name: 'Sun aspect Jupiter in 1st house : Starts', description: 'Wise-self window opens. Polish the public-mantle materials.' },
  { name: 'Sun aspect Jupiter in 1st house : Exact', description: 'Peak wise-self day. Accept the teacher-elevation.' },
  { name: 'Sun aspect Jupiter in 1st house : Ends', description: 'Wise-self window closes. Lock in the public commitments.' },
  { name: 'Sun aspect Saturn in 2nd house', description: 'Solar fire on slow-income. Compensation cases lights; family-money matters resolve.' },
  { name: 'Sun aspect Saturn in 2nd house : Starts', description: 'Slow-income window opens. Prepare the structural case.' },
  { name: 'Sun aspect Saturn in 2nd house : Exact', description: 'Peak slow-income day. Sign the compensation paper.' },
  { name: 'Sun aspect Saturn in 2nd house : Ends', description: 'Slow-income window closes. Lock in the income commitments.' },
  { name: 'Sun aspect Rahu in 6th house', description: 'Solar fire on obsessive-service zone. Win the long adversary case.' },
  { name: 'Sun aspect Rahu in 6th house : Starts', description: 'Service-victory window opens. Sharpen the case file.' },
  { name: 'Sun aspect Rahu in 6th house : Exact', description: 'Peak service-victory day. Defeat the rival.' },
  { name: 'Sun aspect Rahu in 6th house : Ends', description: 'Service-victory window closes. Lock in the wins.' },
  { name: 'Sun aspect Ketu in 12th house', description: 'Solar light on foreign-detached zone. Hidden recognition; foreign-channel news.' },
  { name: 'Sun aspect Ketu in 12th house : Starts', description: 'Foreign-detached window opens. Prepare for muted recognition.' },
  { name: 'Sun aspect Ketu in 12th house : Exact', description: 'Peak foreign-detached day. Recognition lands and feels weightless.' },
  { name: 'Sun aspect Ketu in 12th house : Ends', description: 'Foreign-detached window closes. Move forward with cleaner intent.' },
  { name: 'Moon aspect Sun in 9th house', description: 'Emotional charge on dharma. Warm mentor-conversations, principled emotional pitches.' },
  { name: 'Moon aspect Sun in 9th house : Starts', description: 'Dharma-warmth window opens. Soften the principled tone.' },
  { name: 'Moon aspect Sun in 9th house : Exact', description: 'Peak dharma-warmth day. Make the heart-led principled call.' },
  { name: 'Moon aspect Sun in 9th house : Ends', description: 'Dharma-warmth window closes. Lock in warm mentor-commitments.' },
  { name: 'Moon aspect Moon in 8th house', description: 'Monthly transformation-emotion peak. Inheritance, succession conversations land with weight.' },
  { name: 'Moon aspect Moon in 8th house : Starts', description: 'Transformation-emotion window opens. Prepare for deep-water wave.' },
  { name: 'Moon aspect Moon in 8th house : Exact', description: 'Peak transformation-emotion day. Hold the depth conversation.' },
  { name: 'Moon aspect Moon in 8th house : Ends', description: 'Transformation-emotion window closes. Lock in chapter-ending commitments.' },
  { name: 'Moon aspect Mercury in 10th house', description: 'Emotional intelligence at MC. Warm executive briefings, heart-led status memos.' },
  { name: 'Moon aspect Mercury in 10th house : Starts', description: 'Emotion-on-MC window opens. Soften the executive tone.' },
  { name: 'Moon aspect Mercury in 10th house : Exact', description: 'Peak day for empathetic top-tier communication.' },
  { name: 'Moon aspect Mercury in 10th house : Ends', description: 'Emotion-on-MC window closes. Lock in warm top-tier commitments.' },
  { name: 'Moon aspect Venus in 11th house', description: 'Emotional warmth on gain-zone. Senior-female mentor reaches out.' },
  { name: 'Moon aspect Venus in 11th house : Starts', description: 'Gain-warmth window opens. Reach out to senior allies.' },
  { name: 'Moon aspect Venus in 11th house : Exact', description: 'Peak gain-warmth day. Accept the warm bonus call.' },
  { name: 'Moon aspect Venus in 11th house : Ends', description: 'Gain-warmth window closes. Lock in warm gain commitments.' },
  { name: 'Moon aspect Mars in 5th house', description: 'Emotional charge on creative authority. Heart-led creative push.' },
  { name: 'Moon aspect Mars in 5th house : Starts', description: 'Creative-warmth window opens. Soften the creative direction.' },
  { name: 'Moon aspect Mars in 5th house : Exact', description: 'Peak creative-warmth day. Make the heart-led creative pitch.' },
  { name: 'Moon aspect Mars in 5th house : Ends', description: 'Creative-warmth window closes. Lock in the creative commitments.' },
  { name: 'Moon aspect Jupiter in 1st house', description: 'Emotional warmth on the wise-self. Body reads as approachable.' },
  { name: 'Moon aspect Jupiter in 1st house : Starts', description: 'Wise-warmth window opens. Prepare the warm teacher-tone.' },
  { name: 'Moon aspect Jupiter in 1st house : Exact', description: 'Peak wise-warmth day. Take the heart-led teaching engagement.' },
  { name: 'Moon aspect Jupiter in 1st house : Ends', description: 'Wise-warmth window closes. Lock in warm public commitments.' },
  { name: 'Moon aspect Saturn in 2nd house', description: 'Emotional weight on slow-income. Family-money conversations land warm.' },
  { name: 'Moon aspect Saturn in 2nd house : Starts', description: 'Slow-income emotion window opens. Soften the income tone.' },
  { name: 'Moon aspect Saturn in 2nd house : Exact', description: 'Peak slow-income emotion day. Hold the warm family-finance conversation.' },
  { name: 'Moon aspect Saturn in 2nd house : Ends', description: 'Slow-income emotion window closes. Lock in warm income commitments.' },
  { name: 'Moon aspect Rahu in 6th house', description: 'Emotional charge on obsessive service. Empathetic conflict-resolution.' },
  { name: 'Moon aspect Rahu in 6th house : Starts', description: 'Service-warmth window opens. Soften the conflict tone.' },
  { name: 'Moon aspect Rahu in 6th house : Exact', description: 'Peak service-warmth day. Hold the empathetic 1:1.' },
  { name: 'Moon aspect Rahu in 6th house : Ends', description: 'Service-warmth window closes. Lock in the empathetic commitments.' },
  { name: 'Moon aspect Ketu in 12th house', description: 'Emotional charge on dissolution-zone. Foreign-friend warmth, retreat-tone.' },
  { name: 'Moon aspect Ketu in 12th house : Starts', description: 'Dissolution-warmth window opens. Sleep more.' },
  { name: 'Moon aspect Ketu in 12th house : Exact', description: 'Peak dissolution-warmth day. Take the warm foreign call.' },
  { name: 'Moon aspect Ketu in 12th house : Ends', description: 'Dissolution-warmth window closes. Move forward warmer-but-leaner.' },
  { name: 'Mercury aspect Sun in 9th house', description: 'Sharp mind on dharma. Foreign correspondence, judicial filings, certification-paperwork peak.' },
  { name: 'Mercury aspect Sun in 9th house : Starts', description: 'Dharma-mind window opens. Prepare the foreign-or-judicial document.' },
  { name: 'Mercury aspect Sun in 9th house : Exact', description: 'Peak dharma-mind day. File the foreign motion.' },
  { name: 'Mercury aspect Sun in 9th house : Ends', description: 'Dharma-mind window closes. Lock in the foreign paperwork.' },
  { name: 'Mercury aspect Moon in 8th house', description: 'Sharp mind on transformation. Forensic reports, due diligence.' },
  { name: 'Mercury aspect Moon in 8th house : Starts', description: 'Transformation-mind window opens. Prepare the depth-document.' },
  { name: 'Mercury aspect Moon in 8th house : Exact', description: 'Peak transformation-mind day. Ship the forensic disclosure.' },
  { name: 'Mercury aspect Moon in 8th house : Ends', description: 'Transformation-mind window closes. Lock in the depth-paperwork.' },
  { name: 'Mercury aspect Mercury in 10th house', description: 'Mercury return aspect — peak career-zenith communication.' },
  { name: 'Mercury aspect Mercury in 10th house : Starts', description: 'Career-zenith communication window opens. Polish the public message.' },
  { name: 'Mercury aspect Mercury in 10th house : Exact', description: 'Peak career-zenith communication day. Publish the platform-defining piece.' },
  { name: 'Mercury aspect Mercury in 10th house : Ends', description: 'Career-zenith communication window closes. Convert messaging into commitment.' },
  { name: 'Mercury aspect Venus in 11th house', description: 'Sharp mind on the gains zone. Structured outreach to senior allies.' },
  { name: 'Mercury aspect Venus in 11th house : Starts', description: 'Gain-mind window opens. Draft the senior-network ask.' },
  { name: 'Mercury aspect Venus in 11th house : Exact', description: 'Peak gain-mind day. Send the precise board-position letter.' },
  { name: 'Mercury aspect Venus in 11th house : Ends', description: 'Gain-mind window closes. Lock in the gain-paperwork.' },
  { name: 'Mercury aspect Mars in 5th house', description: 'Sharp mind on creative authority. Bold creative brief.' },
  { name: 'Mercury aspect Mars in 5th house : Starts', description: 'Creative-mind window opens. Draft the bold brief.' },
  { name: 'Mercury aspect Mars in 5th house : Exact', description: 'Peak creative-mind day. Send the punchy creative pitch.' },
  { name: 'Mercury aspect Mars in 5th house : Ends', description: 'Creative-mind window closes. Lock in the creative paperwork.' },
  { name: 'Mercury aspect Jupiter in 1st house', description: 'Sharp mind on the wise-self. Teacher-narrative refresh.' },
  { name: 'Mercury aspect Jupiter in 1st house : Starts', description: 'Wise-mind window opens. Draft the teacher-narrative.' },
  { name: 'Mercury aspect Jupiter in 1st house : Exact', description: 'Peak wise-mind day. Publish the principled personal piece.' },
  { name: 'Mercury aspect Jupiter in 1st house : Ends', description: 'Wise-mind window closes. Lock in the public commitments.' },
  { name: 'Mercury aspect Saturn in 2nd house', description: 'Sharp mind on slow-income. Compensation memos, family-money paperwork.' },
  { name: 'Mercury aspect Saturn in 2nd house : Starts', description: 'Slow-income-mind window opens. Draft the structural salary case.' },
  { name: 'Mercury aspect Saturn in 2nd house : Exact', description: 'Peak slow-income-mind day. File the compensation paper.' },
  { name: 'Mercury aspect Saturn in 2nd house : Ends', description: 'Slow-income-mind window closes. Lock in the income paperwork.' },
  { name: 'Mercury aspect Rahu in 6th house', description: 'Sharp mind on obsessive service. Audit reports, regulatory filings.' },
  { name: 'Mercury aspect Rahu in 6th house : Starts', description: 'Service-mind window opens. Sharpen the case file.' },
  { name: 'Mercury aspect Rahu in 6th house : Exact', description: 'Peak service-mind day. Ship the audit.' },
  { name: 'Mercury aspect Rahu in 6th house : Ends', description: 'Service-mind window closes. Lock in technical commitments.' },
  { name: 'Mercury aspect Ketu in 12th house', description: 'Sharp mind on dissolution-zone. Confidential briefings.' },
  { name: 'Mercury aspect Ketu in 12th house : Starts', description: 'Dissolution-mind window opens. Prepare the confidential document.' },
  { name: 'Mercury aspect Ketu in 12th house : Exact', description: 'Peak dissolution-mind day. Send the off-record briefing.' },
  { name: 'Mercury aspect Ketu in 12th house : Ends', description: 'Dissolution-mind window closes. Lock in confidential commitments.' },
  { name: 'Venus aspect Sun in 9th house', description: 'Warmth on the dharma engine. Graceful foreign-engagement.' },
  { name: 'Venus aspect Sun in 9th house : Starts', description: 'Dharma-warmth window opens. Plan the foreign trip.' },
  { name: 'Venus aspect Sun in 9th house : Exact', description: 'Peak dharma-warmth day. Take the foreign call.' },
  { name: 'Venus aspect Sun in 9th house : Ends', description: 'Dharma-warmth window closes. Lock in foreign commitments.' },
  { name: 'Venus aspect Moon in 8th house', description: 'Warmth on transformation chamber. Diplomatic intimacy.' },
  { name: 'Venus aspect Moon in 8th house : Starts', description: 'Transformation-warmth window opens. Soften the chapter-ending tone.' },
  { name: 'Venus aspect Moon in 8th house : Exact', description: 'Peak transformation-warmth day. Hold the gentle inheritance conversation.' },
  { name: 'Venus aspect Moon in 8th house : Ends', description: 'Transformation-warmth window closes. Lock in warm chapter-ending commitments.' },
  { name: 'Venus aspect Mercury in 10th house', description: 'Warmth at MC. Brand campaigns, design-led PR.' },
  { name: 'Venus aspect Mercury in 10th house : Starts', description: 'MC-warmth window opens. Plan the brand refresh.' },
  { name: 'Venus aspect Mercury in 10th house : Exact', description: 'Peak MC-warmth day. Launch the campaign.' },
  { name: 'Venus aspect Mercury in 10th house : Ends', description: 'MC-warmth window closes. Lock in the design commitments.' },
  { name: 'Venus aspect Venus in 11th house', description: 'Venus return aspect — peak gain-and-network warmth.' },
  { name: 'Venus aspect Venus in 11th house : Starts', description: 'Gain-return window opens. Reach out to senior-female mentors.' },
  { name: 'Venus aspect Venus in 11th house : Exact', description: 'Peak gain-return day. Accept the warm bonus.' },
  { name: 'Venus aspect Venus in 11th house : Ends', description: 'Gain-return window closes. Lock in the gain commitments.' },
  { name: 'Venus aspect Mars in 5th house', description: 'Warmth on creative authority. Aesthetic creative output.' },
  { name: 'Venus aspect Mars in 5th house : Starts', description: 'Creative-warmth window opens. Plan the aesthetic launch.' },
  { name: 'Venus aspect Mars in 5th house : Exact', description: 'Peak creative-warmth day. Launch the beautiful creative product.' },
  { name: 'Venus aspect Mars in 5th house : Ends', description: 'Creative-warmth window closes. Lock in the creative commitments.' },
  { name: 'Venus aspect Jupiter in 1st house', description: 'Warmth on the wise-self. Charm-asks where principle is also visible.' },
  { name: 'Venus aspect Jupiter in 1st house : Starts', description: 'Wise-charm window opens. Prepare the warm teacher outreach.' },
  { name: 'Venus aspect Jupiter in 1st house : Exact', description: 'Peak wise-charm day. Make the warm principled ask.' },
  { name: 'Venus aspect Jupiter in 1st house : Ends', description: 'Wise-charm window closes. Lock in the warm public commitments.' },
  { name: 'Venus aspect Saturn in 2nd house', description: 'Warmth on slow-income. Salary asks land softer.' },
  { name: 'Venus aspect Saturn in 2nd house : Starts', description: 'Slow-income-warmth window opens. Soften the income-ask tone.' },
  { name: 'Venus aspect Saturn in 2nd house : Exact', description: 'Peak slow-income-warmth day. Make the warm salary ask.' },
  { name: 'Venus aspect Saturn in 2nd house : Ends', description: 'Slow-income-warmth window closes. Lock in the warm income commitments.' },
  { name: 'Venus aspect Rahu in 6th house', description: 'Warmth on obsessive service. Difficult colleague becomes ally.' },
  { name: 'Venus aspect Rahu in 6th house : Starts', description: 'Service-warmth window opens. Soften the conflict tone.' },
  { name: 'Venus aspect Rahu in 6th house : Exact', description: 'Peak service-warmth day. Hold the warm 1:1.' },
  { name: 'Venus aspect Rahu in 6th house : Ends', description: 'Service-warmth window closes. Lock in warm service commitments.' },
  { name: 'Venus aspect Ketu in 12th house', description: 'Warmth on dissolution-zone. Hidden patrons surface.' },
  { name: 'Venus aspect Ketu in 12th house : Starts', description: 'Dissolution-warmth window opens. Plan the foreign trip.' },
  { name: 'Venus aspect Ketu in 12th house : Exact', description: 'Peak dissolution-warmth day. Take the foreign-warmth call.' },
  { name: 'Venus aspect Ketu in 12th house : Ends', description: 'Dissolution-warmth window closes. Lock in foreign commitments.' },
  { name: 'Mars aspect Sun in 9th house', description: 'Action on dharma. Bold foreign-engagement push.' },
  { name: 'Mars aspect Sun in 9th house : Starts', description: 'Dharma-action window opens. Train; prepare the principled bold move.' },
  { name: 'Mars aspect Sun in 9th house : Exact', description: 'Peak dharma-action day. Lead the principled charge.' },
  { name: 'Mars aspect Sun in 9th house : Ends', description: 'Dharma-action window closes. Lock in the foreign commitments.' },
  { name: 'Mars aspect Moon in 8th house', description: 'Action on transformation chamber. Surgical succession battles.' },
  { name: 'Mars aspect Moon in 8th house : Starts', description: 'Transformation-action window opens. Prepare for the chapter-ending push.' },
  { name: 'Mars aspect Moon in 8th house : Exact', description: 'Peak transformation-action day. Lead the restructuring.' },
  { name: 'Mars aspect Moon in 8th house : Ends', description: 'Transformation-action window closes. Lock in the chapter-ending commitments.' },
  { name: 'Mars aspect Mercury in 10th house', description: 'Action at MC. Strongest career-action windows.' },
  { name: 'Mars aspect Mercury in 10th house : Starts', description: 'MC-action window opens. Prepare the bold play.' },
  { name: 'Mars aspect Mercury in 10th house : Exact', description: 'Peak MC-action day. Launch, demand, lead.' },
  { name: 'Mars aspect Mercury in 10th house : Ends', description: 'MC-action window closes. Convert moves into permanent positions.' },
  { name: 'Mars aspect Venus in 11th house', description: 'Action on gains zone. Assertive bonus negotiations.' },
  { name: 'Mars aspect Venus in 11th house : Starts', description: 'Gain-action window opens. Prepare the structured ask.' },
  { name: 'Mars aspect Venus in 11th house : Exact', description: 'Peak gain-action day. Make the bonus push.' },
  { name: 'Mars aspect Venus in 11th house : Ends', description: 'Gain-action window closes. Lock in the gain commitments.' },
  { name: 'Mars aspect Mars in 5th house', description: 'Mars return aspect — peak creative-warrior charge.' },
  { name: 'Mars aspect Mars in 5th house : Starts', description: 'Creative-warrior window opens. Train.' },
  { name: 'Mars aspect Mars in 5th house : Exact', description: 'Peak creative-warrior day. Lead the creative charge.' },
  { name: 'Mars aspect Mars in 5th house : Ends', description: 'Creative-warrior window closes. Lock in the creative commitments.' },
  { name: 'Mars aspect Jupiter in 1st house', description: 'Action on the wise-self. Founder-as-teacher declarations.' },
  { name: 'Mars aspect Jupiter in 1st house : Starts', description: 'Wise-action window opens. Prepare the principled bold move.' },
  { name: 'Mars aspect Jupiter in 1st house : Exact', description: 'Peak wise-action day. Take the principled founder action.' },
  { name: 'Mars aspect Jupiter in 1st house : Ends', description: 'Wise-action window closes. Lock in the public commitments.' },
  { name: 'Mars aspect Saturn in 2nd house', description: 'Action on slow-income. Heated income battles.' },
  { name: 'Mars aspect Saturn in 2nd house : Starts', description: 'Slow-income-action window opens. Prepare the data-backed case.' },
  { name: 'Mars aspect Saturn in 2nd house : Exact', description: 'Peak slow-income-action day. Make the salary push.' },
  { name: 'Mars aspect Saturn in 2nd house : Ends', description: 'Slow-income-action window closes. Lock in the income commitments.' },
  { name: 'Mars aspect Rahu in 6th house', description: 'Action on obsessive service. Win the long workplace dispute.' },
  { name: 'Mars aspect Rahu in 6th house : Starts', description: 'Service-action window opens. Sharpen the strategy.' },
  { name: 'Mars aspect Rahu in 6th house : Exact', description: 'Peak service-action day. Lead the regulatory charge.' },
  { name: 'Mars aspect Rahu in 6th house : Ends', description: 'Service-action window closes. Lock in the wins.' },
  { name: 'Mars aspect Ketu in 12th house', description: 'Action on dissolution-zone. Behind-scenes power plays.' },
  { name: 'Mars aspect Ketu in 12th house : Starts', description: 'Dissolution-action window opens. Prepare the hidden push.' },
  { name: 'Mars aspect Ketu in 12th house : Exact', description: 'Peak dissolution-action day. Make the foreign-back-channel move.' },
  { name: 'Mars aspect Ketu in 12th house : Ends', description: 'Dissolution-action window closes. Lock in the foreign commitments.' },
  { name: 'Jupiter aspect Sun in 9th house', description: 'Wisdom-blessing on dharma in own sign. Among the most blessed windows of any twelve-year cycle.' },
  { name: 'Jupiter aspect Sun in 9th house : Starts', description: 'Dharma-blessing window opens. Brief the senior mentor.' },
  { name: 'Jupiter aspect Sun in 9th house : Exact', description: 'Peak dharma-blessing day. Sign the international deal.' },
  { name: 'Jupiter aspect Sun in 9th house : Ends', description: 'Dharma-blessing window closes. Lock in foreign and ethical commitments.' },
  { name: 'Jupiter aspect Moon in 8th house', description: 'Wisdom into transformation. Inheritance favorably resolves.' },
  { name: 'Jupiter aspect Moon in 8th house : Starts', description: 'Transformation-blessing window opens. Prepare for chapter-ending favor.' },
  { name: 'Jupiter aspect Moon in 8th house : Exact', description: 'Peak transformation-blessing day. Sign the inheritance papers.' },
  { name: 'Jupiter aspect Moon in 8th house : Ends', description: 'Transformation-blessing window closes. Lock in the chapter-ending commitments.' },
  { name: 'Jupiter aspect Mercury in 10th house', description: 'Wisdom at MC. Peak career-zenith year.' },
  { name: 'Jupiter aspect Mercury in 10th house : Starts', description: 'MC-blessing window opens. Polish the executive-track materials.' },
  { name: 'Jupiter aspect Mercury in 10th house : Exact', description: 'Peak MC-blessing day. Accept the chief role.' },
  { name: 'Jupiter aspect Mercury in 10th house : Ends', description: 'MC-blessing window closes. Lock in the title and board commitments.' },
  { name: 'Jupiter aspect Venus in 11th house', description: 'Wisdom on the gain zone. Bonus pools compound.' },
  { name: 'Jupiter aspect Venus in 11th house : Starts', description: 'Gain-blessing window opens. Brief the senior network.' },
  { name: 'Jupiter aspect Venus in 11th house : Exact', description: 'Peak gain-blessing day. Accept the bonus, the equity.' },
  { name: 'Jupiter aspect Venus in 11th house : Ends', description: 'Gain-blessing window closes. Lock in the gain commitments.' },
  { name: 'Jupiter aspect Mars in 5th house', description: 'Wisdom on creative authority. Major creative-launch favor.' },
  { name: 'Jupiter aspect Mars in 5th house : Starts', description: 'Creative-blessing window opens. Plan the year\'s flagship creative move.' },
  { name: 'Jupiter aspect Mars in 5th house : Exact', description: 'Peak creative-blessing day. Take the visible authority position.' },
  { name: 'Jupiter aspect Mars in 5th house : Ends', description: 'Creative-blessing window closes. Lock in the creative commitments.' },
  { name: 'Jupiter aspect Jupiter in 1st house', description: 'Jupiter return aspect — annual-tier expansion of self.' },
  { name: 'Jupiter aspect Jupiter in 1st house : Starts', description: 'Self-blessing window opens. Plan the public-mantle assumption.' },
  { name: 'Jupiter aspect Jupiter in 1st house : Exact', description: 'Peak self-blessing day. Accept the elevation.' },
  { name: 'Jupiter aspect Jupiter in 1st house : Ends', description: 'Self-blessing window closes. Lock in the public commitments.' },
  { name: 'Jupiter aspect Saturn in 2nd house', description: 'Wisdom on slow-income. Compensation cases close in your favor.' },
  { name: 'Jupiter aspect Saturn in 2nd house : Starts', description: 'Income-blessing window opens. Prepare the structural case.' },
  { name: 'Jupiter aspect Saturn in 2nd house : Exact', description: 'Peak income-blessing day. Sign the compensation lift.' },
  { name: 'Jupiter aspect Saturn in 2nd house : Ends', description: 'Income-blessing window closes. Lock in the income commitments.' },
  { name: 'Jupiter aspect Rahu in 6th house', description: 'Wisdom on obsessive service. Difficult clients become teachers.' },
  { name: 'Jupiter aspect Rahu in 6th house : Starts', description: 'Service-blessing window opens. Reframe the conflict as teaching.' },
  { name: 'Jupiter aspect Rahu in 6th house : Exact', description: 'Peak service-blessing day. Win the dispute through wisdom.' },
  { name: 'Jupiter aspect Rahu in 6th house : Ends', description: 'Service-blessing window closes. Lock in the service-victory commitments.' },
  { name: 'Jupiter aspect Ketu in 12th house', description: 'Wisdom on dissolution-zone. Foreign-fortune favor.' },
  { name: 'Jupiter aspect Ketu in 12th house : Starts', description: 'Dissolution-blessing window opens. Plan the foreign sabbatical.' },
  { name: 'Jupiter aspect Ketu in 12th house : Exact', description: 'Peak dissolution-blessing day. Take the foreign-channel offer.' },
  { name: 'Jupiter aspect Ketu in 12th house : Ends', description: 'Dissolution-blessing window closes. Lock in the foreign commitments.' },
  { name: 'Saturn aspect Sun in 9th house', description: 'Structural test of dharma. Father-figure relationship restructures.' },
  { name: 'Saturn aspect Sun in 9th house : Starts', description: 'Dharma-discipline window opens. Prepare for the slow ethical reckoning.' },
  { name: 'Saturn aspect Sun in 9th house : Exact', description: 'Peak dharma-discipline day. The principle is tested.' },
  { name: 'Saturn aspect Sun in 9th house : Ends', description: 'Dharma-discipline window closes. What survived is permanent.' },
  { name: 'Saturn aspect Moon in 8th house', description: 'Major life-restructuring. Inheritance, severance chapters open and close.' },
  { name: 'Saturn aspect Moon in 8th house : Starts', description: 'Transformation-discipline window opens. Prepare for the chapter-ending grind.' },
  { name: 'Saturn aspect Moon in 8th house : Exact', description: 'Peak transformation-discipline day. Sign the chapter-ending papers.' },
  { name: 'Saturn aspect Moon in 8th house : Ends', description: 'Transformation-discipline window closes. The new structure holds.' },
  { name: 'Saturn aspect Mercury in 10th house', description: 'The 2.5-year window seeding the next 30-year career chapter.' },
  { name: 'Saturn aspect Mercury in 10th house : Starts', description: 'MC-discipline window opens. Polish the long-game executive materials.' },
  { name: 'Saturn aspect Mercury in 10th house : Exact', description: 'Peak MC-discipline day. The chief role lands.' },
  { name: 'Saturn aspect Mercury in 10th house : Ends', description: 'MC-discipline window closes. Convert effort into title.' },
  { name: 'Saturn aspect Venus in 11th house', description: 'Disciplined structural gains. Bonus pools formalize.' },
  { name: 'Saturn aspect Venus in 11th house : Starts', description: 'Gain-discipline window opens. Audit the network.' },
  { name: 'Saturn aspect Venus in 11th house : Exact', description: 'Peak gain-discipline day. The structured commitment lands.' },
  { name: 'Saturn aspect Venus in 11th house : Ends', description: 'Gain-discipline window closes. Clean-network is what remains.' },
  { name: 'Saturn aspect Mars in 5th house', description: 'Creative authority tested by structural delay.' },
  { name: 'Saturn aspect Mars in 5th house : Starts', description: 'Creative-discipline window opens. Audit the speculative book.' },
  { name: 'Saturn aspect Mars in 5th house : Exact', description: 'Peak creative-discipline day. The slow creative commitment lands.' },
  { name: 'Saturn aspect Mars in 5th house : Ends', description: 'Creative-discipline window closes. What earned was earned.' },
  { name: 'Saturn aspect Jupiter in 1st house', description: 'Multi-year structural pressure on body, persona, founder identity.' },
  { name: 'Saturn aspect Jupiter in 1st house : Starts', description: 'Self-discipline window opens. Eliminate vanity commitments.' },
  { name: 'Saturn aspect Jupiter in 1st house : Exact', description: 'Peak self-discipline day. Hold steady.' },
  { name: 'Saturn aspect Jupiter in 1st house : Ends', description: 'Self-discipline window closes. What survived is permanent.' },
  { name: 'Saturn aspect Saturn in 2nd house', description: 'Saturn return-aspect on slow-income. Slowest income lift of the decade.' },
  { name: 'Saturn aspect Saturn in 2nd house : Starts', description: 'Income-discipline window opens. Prepare for slow but real wage growth.' },
  { name: 'Saturn aspect Saturn in 2nd house : Exact', description: 'Peak income-discipline day. Structural salary case settles after delay.' },
  { name: 'Saturn aspect Saturn in 2nd house : Ends', description: 'Income-discipline window closes. New foundation is permanent.' },
  { name: 'Saturn aspect Rahu in 6th house', description: 'Best multi-year window for resolving long-running conflicts.' },
  { name: 'Saturn aspect Rahu in 6th house : Starts', description: 'Service-discipline window opens. Prepare for the long case.' },
  { name: 'Saturn aspect Rahu in 6th house : Exact', description: 'Peak service-discipline day. The transformation crystallizes.' },
  { name: 'Saturn aspect Rahu in 6th house : Ends', description: 'Service-discipline window closes. The slow win is permanent.' },
  { name: 'Saturn aspect Ketu in 12th house', description: 'Multi-year discipline on foreign, hidden, devotional channels.' },
  { name: 'Saturn aspect Ketu in 12th house : Starts', description: 'Dissolution-discipline window opens. Audit foreign and pleasure budgets.' },
  { name: 'Saturn aspect Ketu in 12th house : Exact', description: 'Peak dissolution-discipline day. Foreign sabbatical formalizes.' },
  { name: 'Saturn aspect Ketu in 12th house : Ends', description: 'Dissolution-discipline window closes. Disciplined hidden-channel is permanent.' },
  { name: 'Rahu aspect Sun in 9th house', description: 'Foreign-fortune obsession on dharma. Vet the dharma channel.' },
  { name: 'Rahu aspect Sun in 9th house : Starts', description: 'Dharma-obsession window opens. Beware the spectacular guru.' },
  { name: 'Rahu aspect Sun in 9th house : Exact', description: 'Peak dharma-obsession day. Verify integrity twice.' },
  { name: 'Rahu aspect Sun in 9th house : Ends', description: 'Dharma-obsession window closes. Keep what was anchored.' },
  { name: 'Rahu aspect Moon in 8th house', description: 'Obsessive transformation. Sudden inheritance, regulatory obsession.' },
  { name: 'Rahu aspect Moon in 8th house : Starts', description: 'Transformation-obsession window opens. Beware emotional distortion.' },
  { name: 'Rahu aspect Moon in 8th house : Exact', description: 'Peak transformation-obsession day. Verify.' },
  { name: 'Rahu aspect Moon in 8th house : Ends', description: 'Transformation-obsession window closes. Keep grounded gains.' },
  { name: 'Rahu aspect Mercury in 10th house', description: 'Obsessive career-elevation push. Vet the legitimacy.' },
  { name: 'Rahu aspect Mercury in 10th house : Starts', description: 'MC-obsession window opens. Vet incoming offers.' },
  { name: 'Rahu aspect Mercury in 10th house : Exact', description: 'Peak MC-obsession day. Verify integrity.' },
  { name: 'Rahu aspect Mercury in 10th house : Ends', description: 'MC-obsession window closes. Lock in legitimate pivots.' },
  { name: 'Rahu aspect Venus in 11th house', description: 'Obsessive gain-and-network chapter. Stay clean.' },
  { name: 'Rahu aspect Venus in 11th house : Starts', description: 'Gain-obsession window opens. Audit network for integrity.' },
  { name: 'Rahu aspect Venus in 11th house : Exact', description: 'Peak gain-obsession day. Verify.' },
  { name: 'Rahu aspect Venus in 11th house : Ends', description: 'Gain-obsession window closes. Keep clean gains.' },
  { name: 'Rahu aspect Mars in 5th house', description: 'Eighteen-month peak ambition window for creative fame.' },
  { name: 'Rahu aspect Mars in 5th house : Starts', description: 'Creative-obsession window opens. Beware spectacle-over-substance.' },
  { name: 'Rahu aspect Mars in 5th house : Exact', description: 'Peak creative-obsession day. Verify integrity twice.' },
  { name: 'Rahu aspect Mars in 5th house : Ends', description: 'Creative-obsession window closes. Keep what was anchored.' },
  { name: 'Rahu aspect Jupiter in 1st house', description: 'Obsessive self-reinvention. New persona, new ambition.' },
  { name: 'Rahu aspect Jupiter in 1st house : Starts', description: 'Self-obsession window opens. Beware identity hijack.' },
  { name: 'Rahu aspect Jupiter in 1st house : Exact', description: 'Peak self-obsession day. Take the unconventional move — but check basics.' },
  { name: 'Rahu aspect Jupiter in 1st house : Ends', description: 'Self-obsession window closes. Decide which experiments to keep.' },
  { name: 'Rahu aspect Saturn in 2nd house', description: 'Obsessive ambition around income. Beware get-rich-quick.' },
  { name: 'Rahu aspect Saturn in 2nd house : Starts', description: 'Income-obsession window opens. Beware shortcuts.' },
  { name: 'Rahu aspect Saturn in 2nd house : Exact', description: 'Peak income-obsession day. Verify integrity.' },
  { name: 'Rahu aspect Saturn in 2nd house : Ends', description: 'Income-obsession window closes. Trust the slow rail.' },
  { name: 'Rahu aspect Rahu in 6th house', description: 'Rahu return aspect — favorable for dramatic enemy-defeat.' },
  { name: 'Rahu aspect Rahu in 6th house : Starts', description: 'Service-victory window opens. Sharpen the strategy.' },
  { name: 'Rahu aspect Rahu in 6th house : Exact', description: 'Peak service-victory day. Defeat the rival.' },
  { name: 'Rahu aspect Rahu in 6th house : Ends', description: 'Service-victory window closes. Lock in the wins.' },
  { name: 'Rahu aspect Ketu in 12th house', description: 'Nodal axis obsession on dissolution. Verify each path.' },
  { name: 'Rahu aspect Ketu in 12th house : Starts', description: 'Dissolution-obsession window opens. Beware spectacular hidden offers.' },
  { name: 'Rahu aspect Ketu in 12th house : Exact', description: 'Peak dissolution-obsession day. Verify integrity.' },
  { name: 'Rahu aspect Ketu in 12th house : Ends', description: 'Dissolution-obsession window closes. Keep dharmic foreign gains.' },
  { name: 'Ketu aspect Sun in 9th house', description: 'Dharma detachment. Old gurus feel finished.' },
  { name: 'Ketu aspect Sun in 9th house : Starts', description: 'Dharma-eclipse window opens. The pull to step away rises.' },
  { name: 'Ketu aspect Sun in 9th house : Exact', description: 'Peak dharma-eclipse day. Old guru-relationship dissolves quietly.' },
  { name: 'Ketu aspect Sun in 9th house : Ends', description: 'Dharma-eclipse window closes. Move forward leaner.' },
  { name: 'Ketu aspect Moon in 8th house', description: 'Transformation acceleration. Old chapters end abruptly.' },
  { name: 'Ketu aspect Moon in 8th house : Starts', description: 'Transformation-eclipse window opens. Prepare for fast endings.' },
  { name: 'Ketu aspect Moon in 8th house : Exact', description: 'Peak transformation-eclipse day. Old chapter ends abruptly.' },
  { name: 'Ketu aspect Moon in 8th house : Ends', description: 'Transformation-eclipse window closes. New chapter begins lean.' },
  { name: 'Ketu aspect Mercury in 10th house', description: 'Career eclipse. Old roles feel hollow.' },
  { name: 'Ketu aspect Mercury in 10th house : Starts', description: 'MC-eclipse window opens. Don\'t over-defend a role wanting to end.' },
  { name: 'Ketu aspect Mercury in 10th house : Exact', description: 'Peak MC-eclipse day. Role dissolves quietly.' },
  { name: 'Ketu aspect Mercury in 10th house : Ends', description: 'MC-eclipse window closes. Move forward to cleaner platform.' },
  { name: 'Ketu aspect Venus in 11th house', description: 'Deep purification of network. Friends drift.' },
  { name: 'Ketu aspect Venus in 11th house : Starts', description: 'Gain-eclipse window opens. Network purifies.' },
  { name: 'Ketu aspect Venus in 11th house : Exact', description: 'Peak gain-eclipse day. Old friend drifts.' },
  { name: 'Ketu aspect Venus in 11th house : Ends', description: 'Gain-eclipse window closes. Clean-network is what remains.' },
  { name: 'Ketu aspect Mars in 5th house', description: 'Creative-authority eclipse. Old creative ambition feels hollow.' },
  { name: 'Ketu aspect Mars in 5th house : Starts', description: 'Creative-eclipse window opens. Fame-pull cools.' },
  { name: 'Ketu aspect Mars in 5th house : Exact', description: 'Peak creative-eclipse day. Old creative ambition feels finished.' },
  { name: 'Ketu aspect Mars in 5th house : Ends', description: 'Creative-eclipse window closes. New chapter begins quieter.' },
  { name: 'Ketu aspect Jupiter in 1st house', description: 'Identity-stripping. Wise-self question itself dissolves.' },
  { name: 'Ketu aspect Jupiter in 1st house : Starts', description: 'Self-eclipse window opens. Pull to step away rises.' },
  { name: 'Ketu aspect Jupiter in 1st house : Exact', description: 'Peak self-eclipse day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu aspect Jupiter in 1st house : Ends', description: 'Self-eclipse window closes. Move forward leaner.' },
  { name: 'Ketu aspect Saturn in 2nd house', description: 'Detachment from income. Income feels meaningless.' },
  { name: 'Ketu aspect Saturn in 2nd house : Starts', description: 'Income-eclipse window opens. Income-meaning evaporates.' },
  { name: 'Ketu aspect Saturn in 2nd house : Exact', description: 'Peak income-eclipse day. Sit with it.' },
  { name: 'Ketu aspect Saturn in 2nd house : Ends', description: 'Income-eclipse window closes. Slow rail still runs.' },
  { name: 'Ketu aspect Rahu in 6th house', description: 'Nodal axis eclipse on service. Old conflicts dissolve.' },
  { name: 'Ketu aspect Rahu in 6th house : Starts', description: 'Service-eclipse window opens. Old enmities cool.' },
  { name: 'Ketu aspect Rahu in 6th house : Exact', description: 'Peak service-eclipse day. Old rival drops out of the picture.' },
  { name: 'Ketu aspect Rahu in 6th house : Ends', description: 'Service-eclipse window closes. Clean board is what remains.' },
  { name: 'Ketu aspect Ketu in 12th house', description: 'Ketu return aspect on its own placement — foreign, devotional dissolution at peak.' },
  { name: 'Ketu aspect Ketu in 12th house : Starts', description: 'Dissolution-return window opens. Foreign-pull rises.' },
  { name: 'Ketu aspect Ketu in 12th house : Exact', description: 'Peak dissolution-return day. Pilgrimage or retreat lands.' },
  { name: 'Ketu aspect Ketu in 12th house : Ends', description: 'Dissolution-return window closes. Move forward leaner.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
