// db/seed_food_virgo.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own — 11L in 11H)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga, yogakaraka)
//     Venus=7th (Pisces, exalted — Malavya Yoga, 2L+9L Dhana-Dharma)
//     Mars=8th (Aries, own)  Jupiter=4th (Sagittarius, own — Hamsa Yoga, 4L+7L)
//     Saturn=5th (Capricorn, own — 5L+6L)  Rahu=9th (Taurus)  Ketu=3rd (Scorpio)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose food-specific interpretations, then run:
//
//   node db/seed_food_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./food');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'Your body is a precision instrument running on a sensitive Vata-Pitta nervous system. Slow, warm, regular meals are non-negotiable — skipped meals translate directly into mental fog and skin reactions. Bitter and astringent tastes (Virgo signatures) cleanse the system: bitter greens, turmeric, neem, dandelion, mung dal, cooked seasonal vegetables. Avoid raw-cold foods, heavy fermented items, and chaotic eating windows; the gut reads disorder before the mind does. Skin reflects the gut directly — if breakouts or rashes appear, audit the last 72 hours of food before reaching for topicals. Hydrate warm, not iced. The shadow: hyper-restrictive eating that becomes its own form of stress; perfectionism in diet is a Virgo trap that costs more than it saves.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'Food and partnership are fused. The meals shared with the spouse / principal partner are the deepest nourishment-channel for this body. Cooking together, eating together, learning the partner\'s family recipes all carry actual nutritive weight beyond the calories. Family-finance follows the same channel — household food budget conversations belong in the relational sphere, not the spreadsheet. Industries with food-as-relational core (hospitality, restaurant ownership with partner, food-blogging-as-couple, culinary advisory, wedding catering) suit. The shadow: comfort-eating triggered by relationship friction; address the relational signal before reaching for the second helping.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'Pitta fire stored deep — strong digestive capacity *when* the body is rested, but sharp acid reactions when stressed. The 8th-house Mars means you can metabolize intense flavors (chili, garlic, onion, pickle) better than peers, but only in disciplined quantities. Sibling-table dynamics carry charge — family meals with siblings can trigger old digestive patterns. The shadow: aggressive eating during work-stress that detonates the gut for 48 hours; eat alone when angry.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'The family kitchen is your dharma-kitchen. Mother\'s recipes, grandmother\'s rituals, traditional preparations carry actual healing weight here. Hamsa-Yoga in 4H makes the family meal almost sacramental — Sunday lunch, festival cooking, lineage-recipe preservation are not optional luxuries but structural nourishment. Traditional ghee, lentils, rice, seasonal vegetables, slow-cooked dals, traditional spice combinations (turmeric-cumin-coriander) are the body\'s native fuel. Avoid foreign cuisines as primary-staple; honor them as occasional explorations. The shadow: emotional eating triggered by mother-line sadness; cook the heritage recipe instead of ordering takeout.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Disciplined eating schedule is the foundation. Fixed meal times, disciplined portion control, multi-decade consistency in food rules — Saturn-own-in-5 wires this body to thrive on long-arc dietary commitments. Intermittent fasting (gentle, not extreme), traditional vrata / fast-day rituals, structured meal-prep protocols all suit. The body recovers slowly from dietary chaos; one chaotic week can take three to undo. Children-and-mentees benefit from your structured-food-wisdom — pass it forward. The shadow: the inner-critic in the kitchen; lower the gate occasionally and enjoy the meal.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'Daily-routine food becomes the moat against illness and adversaries (literal and figurative). Structured eating schedule is a competitive advantage — your immune system, mental clarity, and physical stamina compound over decades through this discipline. Audit-grade meal logs, regular blood panels, methodical hydration tracking are not over-engineering for this body — they are the precision tooling. The shadow: turning the kitchen into a compliance environment; warmth must remain in the food itself.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Spouse-and-mother converge in the kitchen. The home becomes the place where partner and family-elders co-cook; in-laws often share recipes that become permanent additions. Cooking with the spouse is one of the deepest dharma-acts available to you. Industries: family-hospitality, traditional-cuisine restaurants with partner, recipe-preservation projects with in-laws. The shadow: family-elder food preferences overruling your own dietary intelligence; respect the lineage but trust your gut.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'The body is built for intense, occasionally-extreme food experiences — fasting cycles, raw-spice tolerance, elimination-protocol experiments — but only when fully rested. The 8th-house own Mars handles transformation-grade dietary moves (cleanses, panchakarma, surgical-recovery diets) better than peers. Genetic-or-lineage inherited digestive patterns surface here; family medical history of gut/metabolic issues is worth tracking. The shadow: thrill-seeking diet experiments without baseline discipline; the 8th rewards the disciplined surgeon, not the cowboy.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'Foreign cuisines learned through partnership become permanent dharma-additions. The spouse / principal teacher introduces you to Mediterranean, Japanese, Italian, Persian, or other tradition that becomes household-staple. Traveling-with-partner triggers the deepest food-discoveries. Industries: international-cuisine partnership ventures, foreign-cookbook publishing with co-author, travel-food advisory. The shadow: confusing the partner\'s preferred cuisine with your body\'s actual fuel; check the digestive evidence.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'Public profile and food-self are welded together. The way you eat (publicly, in meetings, at events) carries professional signal — your discipline, taste, attention all read. Power-lunch dynamics matter; choose menus thoughtfully. Best public-eating: clean, vegetarian-leaning, well-prepared, never-extreme. The shadow: performance-eating in front of clients that wrecks digestion privately; honor the body more than the optics.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Community meals and friend-table eating are central nourishment-channels. Alumni dinners, cooperative-meal cultures, peer-circle food rituals carry emotional-trust weight. The 11L own here means group-cooking events (potlucks, dinner parties, shared kitchens) recharge you in ways solo eating cannot. Female-friend kitchen-time especially nourishing. The shadow: emotional eating triggered by group-mood swings; protect digestion on big network weeks.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'Solar fire is dimmed in moksha-house — the body responds beautifully to gentle warming foods rather than intense solar-pitta heat. Warm cooked grains, ghee-cooked vegetables, mild spices, golden-milk tradition, dawn-eating rituals all suit. Eating alone in retreat-mode (silent meals, solitary breakfasts) is genuinely nutritive for this configuration. Foreign-retreat foods (monastery meals, ashram-style cooking, hospital diets, boarding-school meals) often surprise by suiting the body. The shadow: skipping meals during deep solitary work — the 12H Sun fades faster than the body realizes.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, the retreat-meal / solitary-eating channel restores. Best windows for silent meals, dawn-breakfast rituals, monastery-style food simplicity, foreign-retreat dining.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, the community-meal channel pays. Best windows for hosting dinners, joining the cooking-club, organizing the alumni potluck, sharing recipes in the peer circle.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, precision-eating routines reset cleanly. Best windows for diet-protocol launches, food-journal restarts, ingredient-quality upgrades. The yogakaraka body responds faster than peers to small-precision changes.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, the family-kitchen / mother-recipe channel restores. Best windows for cooking heritage dishes, organizing the family recipe archive, hosting the lineage meal.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, intense-protocol food experiments are tolerated. Best windows for cleanses, panchakarma, fasting cycles, elimination protocols — but only with full rest in support.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, the structured-eating discipline locks in. Best windows for committing to a multi-month food protocol, fasting schedule, or meal-prep system that you intend to keep for years.' },
  { name: 'Venus in 7th (Dispositor)', description: 'When this engine fires, the partner-cooked / shared-meal channel restores. Best windows for couples-cooking, recipe-learning together, restaurant explorations with spouse.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak of personal vital fire. Up the warming foods slightly, lean into solar spices (turmeric, ginger, black pepper). The body wants visibility through clean-eating clarity. Avoid heavy-greasy meals during the spotlight month.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on family-finance and voice. Throat care matters; warm broths, honey-ginger tea, vocal-soothing foods. Family-money meal conversations land warmly.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on communication. Energy-up foods favored — light grains, fresh fruit, hydrating soups. Ketu zone — keep meals from drifting too detached / minimalist.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home-throne. Best month for cooking heritage recipes at home, hosting family meals, mother-channel kitchen time.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on creative-discipline. Best month for launching a structured-eating protocol you intend to keep. Saturn-territory grounds the discipline.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on health and routine. Best month for medical check-ups, blood panels, gut-protocol initiation. Adversaries (literal: pathogens, debt, conflict) weaken.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on partnership. Cook with partner, eat together more deliberately. Public-meal moments with spouse / principal client favored.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in transformation chamber. Cleanse / panchakarma / intense-protocol windows open — but with full rest in support. Mars-territory + Sun = high digestive fire; honor it.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma-mentor engine. Foreign cuisines, pilgrimage meals, teacher-tradition foods favor. Rahu zone — try the unconventional cuisine.' },
  { name: 'Sun Transits the 10th House', description: 'Solar fire on career visibility. Power-lunch month; food carries public-status signal. Choose clean, traditional, well-prepared menus for client meetings.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on wide-network gains. Community-dinner peak; friend-table moments carry warmth. Moon-territory — emotional nourishment through group eating.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return through 12H. Annual peak for retreat-eating, silent meals, fasting protocols, monastery-style simplicity. Foreign-retreat food experiences land beautifully.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of body-warmth charge. The body wants comforting, warm, slightly-rich food — soft grains, milky drinks, warm desserts. Honor the warmth.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on income/voice. Throat-care foods favored. Family-finance kitchen-table conversations land warm.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on communication. Warming sibling-table moments, candid food-conversations. Ketu zone — keep meals anchored, not minimalist.' },
  { name: 'Moon Transits the 4th House', description: 'Two-day home-throne emotional peak. Cook the heritage meal; mother-channel kitchen-time.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on romance/children. Cook for the loved ones; child-friendly meals; playful kitchen moments.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on health/routine. Gentle-on-gut foods favored; broths, simple grains, easy proteins. Avoid experimental items.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnership. Cook with / for partner; shared-meal warmth peaks.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on transformation zone. Defer extreme-protocol food moves two days. Eat simply, gently.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward foreign cuisine, dharma-foods, traveler-meals. Try the new tradition.' },
  { name: 'Moon Transits the 10th House', description: 'Public-eating warmth peak. Power-lunches land warm; client meals carry relational signal.' },
  { name: 'Moon Transits the 11th House', description: 'Moon-own peak — community-meal warmth. Host the dinner, join the potluck, attend the friend-table.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; solitary-meal pull. Best for silent breakfasts, retreat-eating, dream-led food choices.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury return through own + exalted lagna. Peak window for refining the personal food protocol. Audit the diet, reset the meal-times, reorganize the kitchen, refresh the nutritional approach. Most powerful Mercury food-window of the year.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Throat-care details, family-finance food-budget reset, vocal-led foods (sage, licorice, ginger).' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s home turf. Sharp food-research window — read the labels, study the ingredients, write the meal plan. Sibling-table communication on food rituals.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-kitchen articulation. Reorganize the pantry, document the family recipes, mother-channel cooking-conversation.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative-discipline articulation in food. Curriculum-grade meal planning, structured cookbook work, child-nutrition systems.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp health-routine articulation. Audit the gut, track the food-mood correlations, refine the supplement protocol.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Cook-together planning, shared-recipe documentation, joint-meal-prep system design.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-zone articulation. Cleanse-protocol research, panchakarma planning, fasting schedule design.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-articulation. Foreign-cuisine deep-research, pilgrimage-food planning, traditional-food doctrine study.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp public-eating articulation. Power-lunch planning, client-meal etiquette, public-food-image refinement.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Community-cookbook organization, peer-recipe-sharing systems, alumni-potluck planning.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp confidential articulation. Retreat-meal planning, silent-eating protocols, off-grid-food research.' },
  { name: 'Venus Transits the 1st House', description: 'Personal-magnetism window. Body responds beautifully to luxury-clean foods — high-quality oils, traditional ghee, well-aged grains, ethical-sourced ingredients.' },
  { name: 'Venus Transits the 2nd House', description: 'Venus on family-finance. Family-recipe warmth peaks; ancestral-food rituals favored.' },
  { name: 'Venus Transits the 3rd House', description: 'Charm on communication. Sibling-cooking moments, candid food-conversations. Ketu zone — keep warmth concrete.' },
  { name: 'Venus Transits the 4th House', description: 'Venus on home-throne. Beautify the kitchen, upgrade the dining setup, host the warm family meal.' },
  { name: 'Venus Transits the 5th House', description: 'Charm on romance/children. Romantic dinner planning, child-celebration meals, creative-cooking with loved ones.' },
  { name: 'Venus Transits the 6th House', description: 'Charm in health-zone. Gentle-luxury health foods, beautiful supplement protocols, gracefully-handled gut work.' },
  { name: 'Venus Transits the 7th House', description: 'Venus return through own exalted 7th. Monthly peak for cook-with-partner moments, shared-meal warmth, restaurant-dating.' },
  { name: 'Venus Transits the 8th House', description: 'Charm in transformation zone. Severance / inheritance / restructuring meals — eat with grace through hard chapters.' },
  { name: 'Venus Transits the 9th House', description: 'Charm on dharma-foods. Foreign-cuisine warmth, ethical-food-investment, teacher-tradition meals.' },
  { name: 'Venus Transits the 10th House', description: 'Charm on public-eating. Beautiful client-lunches, gracefully-handled board-dinners.' },
  { name: 'Venus Transits the 11th House', description: 'Charm in community-meals. Host the warm potluck; alumni dinner warmth peaks.' },
  { name: 'Venus Transits the 12th House', description: 'Charm in retreat-eating. Beautiful silent breakfasts, foreign-retreat warm foods.' },
  { name: 'Mars Transits the 1st House', description: 'Surge of force on the body. Watch for inflammation, skin reactions, gut acid flare-ups. Cool the system: cucumber, coconut water, mint, fennel.' },
  { name: 'Mars Transits the 2nd House', description: 'Force on family-finance and voice. Avoid sharp tones at the family table. Throat irritation possible; cool foods help.' },
  { name: 'Mars Transits the 3rd House', description: 'Force on communication. Sibling-table friction risk; eat alone if angry. Ketu zone — keep food choices grounded.' },
  { name: 'Mars Transits the 4th House', description: 'Force on home-throne. Property-related kitchen-stress; family-business friction at the table. Keep the temperature low at home meals.' },
  { name: 'Mars Transits the 5th House', description: 'Force on romance/children. Sharp competitive eating tendencies (overordering, overcooking); honor the disciplined-Saturn frame here.' },
  { name: 'Mars Transits the 6th House', description: 'Force on health/adversary zone. Best window for the offensive — pathogen-cleanse protocols, parasite-protocols, immune-rebuild work.' },
  { name: 'Mars Transits the 7th House', description: 'Force on partnership. Sharp food-friction with spouse; cool the kitchen temperature.' },
  { name: 'Mars Transits the 8th House', description: 'Mars through own territory. Surgical-cleanse window — panchakarma, deep fasting, intense-protocol experiments. Best done with full rest in support.' },
  { name: 'Mars Transits the 9th House', description: 'Force on dharma-engine. Aggressive doctrinal-food disputes (vegetarian/non-veg debates, fasting traditions). Stay grounded.' },
  { name: 'Mars Transits the 10th House', description: 'Force on career visibility. Power-lunch demands sharp; stay clean, controlled at the table.' },
  { name: 'Mars Transits the 11th House', description: 'Force on wide-network. Aggressive community-meal politics; eat what you brought rather than what is served if friction is high.' },
  { name: 'Mars Transits the 12th House', description: 'Force in moksha zone. Foreign-front aggressive food moves, retreat-cleanse intensities. Honor the body\'s rest needs.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual wisdom-on-self window. Body-weight and dietary doctrine consolidate. Year-block to lock the personal-food philosophy that survives multi-decade.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom on family-finance and voice. Year-block to expand voice-led income with throat-care, refine family-food ethics, take on traditional-cuisine roles.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on communication. Year-block to write the food memoir, formalize the recipe-collection, publish the dietary doctrine.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter return through own + Hamsa Yoga. Year-block for kitchen renovation, family-recipe archive completion, mother-line food-tradition documentation.' },
  { name: 'Jupiter Transits the 5th House', description: 'Wisdom on creative-discipline. Year-block for cookbook publication, child-nutrition curriculum, structured-creative culinary leadership.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom in conflict/health zone. Year-block where dietary adversaries weaken (allergies, intolerances, pathogens). Health regimens institutionalize.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom on partnership-meals. Year-block for couples-cooking philosophy consolidation, shared-recipe library, partner-cuisine teaching.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom in transformation zone. Year-block for inheritance-of-recipes, succession of family-cooking duties, longevity-food advisory.' },
  { name: 'Jupiter Transits the 9th House', description: 'Wisdom in dharma. Year-block for foreign-cuisine institutionalization, pilgrimage-food tradition, teacher-track culinary moves.' },
  { name: 'Jupiter Transits the 10th House', description: 'Wisdom on public-eating. Year-block for principal-of-cuisine appointment, cookbook authorship, formal lineage-transfer of recipes.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom in wide-network meals. Year-block for cooperative-kitchen leadership, alumni-cookbook institutionalization, ethical-food-platform leadership.' },
  { name: 'Jupiter Transits the 12th House', description: 'Wisdom in moksha zone. Year-block for retreat-residency cuisine, foreign-research food mandates, monastery-meal authoring.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn on the precision-instrument body. ~2.5-year discipline-on-body chapter. Body weight, food rules, posture all restructure. Lean, principled re-emergence.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn on family-finance/voice. Lean years on the food budget — structural rather than punitive. Voice deepens; throat care matters.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn on communication. Rigorous editing of food-related messaging; sibling-table relationships restructure. Solitary-cooking discipline grows.' },
  { name: 'Saturn Transits the 4th House', description: 'Saturn on the home-throne. Heavy chapter for kitchen renovation, mother\'s health, family-meal restructure. Foundational kitchen architecture built here.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn return through own 5H. ~2.5-year peak for institutional-grade food discipline. The structured-eating moat that lasts decades is laid here.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn on adversary/health/debt. Long grind chapter — chronic conditions stabilize through patience; gut-protocol becomes protocol-grade.' },
  { name: 'Saturn Transits the 7th House', description: 'Saturn on partnership-meals. Couples-eating routines tested for structural soundness. Weak food-traditions fall away; sound ones lock in for decades.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn on transformation. Heavy-but-gold chapter for recipe-inheritance, succession of food-rituals, longevity-protocol design.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn on dharma. Long-arc chapter for cuisine-credentialing, traditional-food doctrine, teacher-lineage rework in the kitchen.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on career-visibility. ~2.5 years of slow elevation in the public-food domain. The flashy chefs rotate; you remain.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn on wide-network meals. Structural rebuild of the community-cookbook channels. Some friend-table relationships fall away; deep ones lock in.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn on moksha-zone. Heavy chapter for retreat-residency cuisine, hospital-food protocols, monastery-meal disciplines.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu on persona. ~18-month chapter of unconventional food-presentation. Foreign / disruptive dietary moves. Risk: identity-overreach in eating; reward: breakthrough body-clarity.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu on family-finance/voice. Speculative food-income windows, foreign-currency-purchased ingredients, unconventional vocal-food ventures.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on communication. Foreign / disruptive food-content channels, viral recipe writing, unconventional sibling-table deals.' },
  { name: 'Rahu Transits the 4th House', description: 'Rahu on home-throne. Foreign-kitchen windows, unconventional family-business pivots, mother-line food disruption.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu on creative-discipline. Speculative-creative food experiments, foreign-curriculum cuisine ventures, viral-recipe opportunities.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu on adversary/health zone. Unconventional dietary enemies surface (food allergies revealed, hidden intolerances), foreign-protocol cleanses defeat them.' },
  { name: 'Rahu Transits the 7th House', description: 'Rahu on partnership-meals. Foreign-spouse / foreign-anchor-client cuisine introductions, unconventional shared-meal structures.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on transformation. Speculative-cleanse experiments, unconventional inheritance of recipes, foreign-restructured cuisine.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu return through 9H. ~18-month foreign-cuisine chapter — unconventional teacher in cooking, foreign credentialing, disruptive food-doctrine.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu on career-visibility. Sudden public-cuisine elevation through disruptive channels — viral case study, foreign-stage breakthrough.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu on wide-network meals. Foreign-friend windfalls in food, viral community-cooking moves, unconventional cookbook appointments.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu on moksha-zone. Foreign-retreat residency cuisines, confidential disruptive food-mandates, off-grid speculative-food ventures.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu on persona. Detachment from food-attachment; identity-stripping in eating. Body weight may shift; old food-habits dissolve. Useful for sabbatical thinking on diet.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu on family-finance/voice. Detachment from family-food attachment; voice quieter. Don\'t monetize the silence.' },
  { name: 'Ketu Transits the 3rd House', description: 'Ketu return through own territory. Detachment from communication noise around food; sibling-table disengagement. Best for solitary cooking; worst for food-marketing.' },
  { name: 'Ketu Transits the 4th House', description: 'Ketu on home-throne. Detachment from family-recipe attachment; kitchen feels oddly indifferent. Defer big kitchen-renovation moves.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu on creative-discipline. Detachment from validation-seeking cooking. Saturn-territory + Ketu = unusually pure-form food work.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu on adversary/health zone. Detachment from old food-grievances; the intolerances you thought mattered evaporate or transform.' },
  { name: 'Ketu Transits the 7th House', description: 'Ketu on partnership-meals. Detachment from anchor-meal warmth; defer big shared-cuisine signing. Exalted Venus usually softens.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu on transformation. Detachment from cleanse-thrill; the protocol arrives muted. Document carefully.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on dharma. Detachment from doctrinal certainty in food; old vegetarian/non-veg / fasting/non-fasting positions may stop fitting.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu on career-visibility. Detachment from public-eating attachment; the power-lunch arrives muted but private meals strengthen.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu on wide-network meals. Detachment from group-validation; some friend-tables drift. Trust the silence.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu on moksha-zone. Detachment-on-detachment — deep retreat-eating months, foreign-solitude meal windows.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar light on persona. Up the warming spices, lean into solar foods (turmeric, ginger, raisins). Body radiates clean-eating clarity.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Solar approach to lagna. Polish the food-self framing.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Today body-fire peaks. Make the visible clean-eating statement.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Light fades. Lock the dietary clarity gained.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar light on career-MC. Power-lunch month begins; food carries public signal.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Solar approach to MC. Prep clean public-meal protocols.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Today public-eating spotlight peaks. Choose clean menus for client meetings.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Solar light fades from MC. Lock the public-eating discipline.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Body wants warmth and softness — comforting foods, warm grains, soft desserts.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep softer comforting meals.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Today body wants comfort. Cook the warm soft meal.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional warmth fades. Return to disciplined fare.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-status. Public-meal warmth wanted; relational-food moments favored.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Approach. Warm up senior-track meal relationships.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Today senior-meal warmth peaks. Take the warm board-dinner.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Warmth fades. Lock the warm-status meals.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury on persona — food-articulation peak. Audit the meal plan; refresh the food protocol.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Approach. Draft the meal plan refresh.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Today food-precision peaks. Reset the diet protocol.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mercury fades. Lock the food-protocol changes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on public-status food-articulation. Power-lunch planning, board-dinner protocols.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Approach. Draft the client-meal etiquette.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Today public-meal articulation peaks. Submit the catering plan.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Mercury fades from MC. Lock the public-meal protocols.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Charm on persona. Body responds beautifully to luxury-clean foods, traditional ghee, well-aged grains, ethically-sourced ingredients.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep the warm-luxury meal sequence.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Today personal-food warmth peaks. Cook the beautiful meal.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm fades. Lock the luxury-clean staples.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Charm on public-status. Beautiful client-lunches, gracefully-handled board-dinners.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Approach. Soften senior-track meal outreach.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Today senior-meal charm peaks. Take the relational board-dinner.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Charm fades from MC. Lock the senior-meal warmth.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Force on persona. Watch inflammation, gut-acid flares. Cool the system — cucumber, coconut water, mint.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep the cooling foods.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Today body-heat peaks. Avoid spicy-fried; lean cool, calm.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Force fades. Resume warming spices gradually.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Force on public-status meals. Sharp client-lunch demands; stay controlled at the table.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Approach. Gather force for the demanding power-lunch.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Today public-meal force peaks. Stay clean, restrained at the senior table.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Force fades. Cool the meal-temperature.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom on persona. Lineage-anchored food choices, traditional-recipe wisdom, dharma-aligned dietary framing.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Approach. Polish the dharma-aligned food framing.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Today wisdom-on-food peaks. Cook the heritage recipe; lock the lineage-meal commitment.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Wisdom fades. Lock the lineage-anchored food gains.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Wisdom on public-status meals. Senior-track elevation through dharma-aligned cuisine — the principled chef appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Approach. Position the senior-cuisine move as dharma-aligned.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Today senior-cuisine dharma-elevation peaks. Take the principled appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Wisdom fades from MC. Lock the dharma-aligned cuisine status.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Discipline on persona. Body weight, food rules, posture restructure. Lean, principled re-emergence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Approach. Begin the personal food-discipline cycle.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Today food-discipline peaks. Lock the lean protocol.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Discipline closing. The leaner food-self in place.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Discipline on public-status meals. Slow elevation in public-food domain. Flashy chefs rotate; you remain.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Approach. Begin structural senior-cuisine positioning.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Today structural cuisine-status peak. Take the slow-but-permanent appointment.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Discipline closing. Senior-cuisine track in place.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Rahu on persona. Unconventional / foreign / disruptive dietary moves. Risk: identity-overreach in eating; reward: breakthrough.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Approach. The unconventional food-pivot is gathering.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Today disruptive-food-self peaks. Try the unconventional dietary protocol.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu fades. Decide which disruptive food-elements stay.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Rahu on public-status. Sudden public-cuisine elevation through disruptive channels.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Approach. Disruptive senior-cuisine move gathering.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Today disruptive cuisine-status peak. Take the unconventional culinary appointment.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu fades. Lock disruptive cuisine gains.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Ketu on persona. Detachment from food-attachment; sabbatical thinking on diet.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Approach. Pull toward food-solitude rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Today food-detachment peaks. Best for solitary fasting / meal-simplification.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Detachment fading. Re-engage food on quieter terms.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Ketu on public-status meals. Detachment from public-eating attachment; private meals strengthen.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Approach. Public-meal attachment unwinds.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Today public-meal detachment peaks. Useful information.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Detachment fading. Next meal-status chapter on internal grounds.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural transformation in food-discipline architecture. Eating rules, fasting protocols, dietary framework rebuilt at the foundation.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Pressure builds. Begin documenting the food-discipline architecture you want to preserve.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Today the generational rebuild peaks. The food-framework re-cast at depth.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Pressure releases. New food-architecture in place.' },
  { name: 'Uranus conjunct Venus', description: 'Disruptive innovation on the partnership-meal / cuisine engine. Spouse-cooked food, anchor-restaurant relationship, principal-cuisine teacher undergoes sudden re-architecture.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruptive pressure builds on the meal-partnership.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Today the meal-partnership rewiring peaks. The unconventional cuisine declaration lands.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption settling. New cuisine-partnership architecture in place.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar return through 12th. Annual peak for retreat-eating, fasting protocols, monastery-style simplicity.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Solar return approaching. Prep year-block retreat-meal drafts.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Solar return peak. Take the new-year retreat-meal commitment.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Solar return closing. Shadow-meal strategy on record.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar light on community-meals. Alumni-dinner peak, friend-table moments, peer-cookbook recognition.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Approach. Network-meal spotlight gathering.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Today network-meal spotlight peaks. Take the alumni-dinner; host the cookbook event.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Spotlight fades. Lock community-meal recognition.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar light on yogakaraka. Annual peak for personal food-clarity — clean diet declaration, principal-cuisine framing.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka spotlight gathering.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Today yogakaraka spotlight peaks. Make the clean-diet declaration; take principal-of-cuisine framing.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Spotlight fades. Lock the principal-cuisine appointment.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar light on partnership-meals. Visibility through couples-cooking; spouse / principal-client meal moments.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Approach. Partnership-meal spotlight gathering.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Today partnership-meal spotlight peaks. Host the warm shared-meal event.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Spotlight fades. Lock the public partnership-meals.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar light on cleanse-engine. Career-relationship food intersections in transformation chapters.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Approach. Cleanse-spotlight gathering.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Today cleanse-spotlight peaks. Lead the protocol; close the cleanse-event.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Spotlight fades. Lock cleanse gains.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar light on home-kitchen / Hamsa. Real-estate kitchen decisions, family-meal inflections, mother-line cooking conversations.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen spotlight gathering.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-spotlight peaks. Renovate the kitchen; archive family recipes.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Spotlight fades. Lock home-kitchen move.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar light on disciplined-eating engine. Best for launching long-arc food-protocols, structured fasting commitments.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Approach. Discipline spotlight gathering.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H spotlight peaks. Launch the structured food-protocol.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Spotlight fades. Lock disciplined-eating protocol.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Solar light on foreign-cuisine engine. International-cuisine talks, certifications, traditional-food doctrine moves.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-cuisine spotlight gathering.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H spotlight peaks. Take the foreign-cuisine talk; unconventional-cooking move.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Spotlight fades. Lock foreign-cuisine recognition.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Solar light on detached-food-communication. Brave solitary-cooking push gets quiet recognition.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-cooking spotlight gathering.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H spotlight peaks. Publish the solitary-cooking research.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Spotlight fades. Solitary-cooking output stands on record.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on moksha-solar food engine. Inwardness, retreat-meal warmth, confidential-eating moments.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Approach. Retreat-meal warmth gathering.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Today 12H emotional-meal warmth peaks. Take the silent breakfast, the retreat-style lunch.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Warmth fades. Retreat-meal practice consolidated.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon return — community-meal warmth peaks. Host the dinner; join the potluck; alumni-cooking warmth.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Moon return approaching. Community-meal warmth rising.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Moon return peak. Host the warm friend-table.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Moon return closing. Community-meal gains on record.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional charge on yogakaraka body. Body wants warm-comforting food; soft-grain, milky-drink, slow-cooked staples.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Approach. Personal-comfort meal need rising.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Today personal-warmth peaks. Cook the comfort meal.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Warmth fades. Lock the comfort-meal staples.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on partnership-meals. Read partner\'s mood before the meal; warm tone wins the kitchen.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Approach. Partnership-meal warmth rising.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Today partnership-meal warmth peaks. Cook the warm shared-meal.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Warmth fades. Lock the warm-partner-meal alliance.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on cleanse-zone. Defer extreme-protocol food moves two days. Eat simply, gently.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Approach. Crisis-emotion rising; food-fear surfaces.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Today crisis-weight peaks. Defer protocols; eat for comfort.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Weight fades. Re-engage transformation work.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional charge on home-kitchen / Hamsa. Mother-channel cooking warmth peaks; family-meal pulse-check.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen warmth rising.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Today home-kitchen warmth peaks. Cook the heritage meal; take mother\'s call.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Warmth fades. Home-bond consolidated.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional charge on disciplined-eating engine. Structured-eating routine picks up emotional warmth.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Approach. Discipline-warmth rising.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Today discipline-warmth peaks. Add heart to the rigorous protocol.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Warmth fades. Warm-rigorous discipline on record.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional charge on foreign-cuisine engine. Pilgrimage-meal thought, foreign-trip food draft, unconventional-teacher cooking-warmth.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-cuisine warmth rising.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H warmth peaks. Try the unconventional cuisine.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Warmth fades. Foreign-cuisine bond on record.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Emotional charge on detached-food-communication. Solitary-cooking mood; the brave food-message that does not need a reply.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-cooking warmth rising.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H warmth peaks. Cook the solitary meal; do not need a reply.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Warmth fades. Solitary-cooking warmth locked.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Articulation on moksha-solar food engine. Retreat-meal documentation; silent-eating protocols; off-stage food-memos.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Approach. Retreat-food writing picks up pace.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Today shadow-food articulation peaks. Ship the retreat-meal protocol.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Articulation fades. Retreat-food document locked.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Articulation on community-meal warmth. Alumni-cookbook posts, community-recipe documentation, peer-cooking memos.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Approach. Community-food articulation gathers.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Today community-food articulation peaks. Send the alumni-recipe note.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Articulation fades. Community-food message on record.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury return — most important food-articulation aspect. Bio refresh, food-philosophy declaration, principal-cuisine pitch.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Mercury return approaching. Prep food-philosophy refresh.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Mercury return peak. Ship the food-protocol declaration.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Mercury return closing. Yogakaraka food-articulation locked.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Articulation on partnership-meals. Couples-cooking documentation, shared-recipe library design.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Approach. Partnership-food articulation gathers.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Today partnership-food articulation peaks. Ship the shared-recipe collection.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Articulation fades. Partnership-recipes on record.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Articulation on cleanse-engine. Panchakarma planning, fasting schedule design, transformation-protocol research.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Approach. Cleanse articulation gathers.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Today cleanse-articulation peaks. Ship the cleanse-protocol document.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Articulation fades. Cleanse document locked.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Articulation on home-kitchen / Hamsa. Real-estate kitchen documentation, family-recipe archive, mother-channel cooking notes.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen articulation gathers.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-articulation peaks. Ship the family-recipe archive.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Articulation fades. Home-kitchen document on record.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Articulation on disciplined-eating engine. Cookbook drafts, structured-fasting design, child-nutrition curriculum.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-eating articulation gathers.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H articulation peaks. Ship the cookbook chapter.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Articulation fades. Disciplined-eating document locked.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Articulation on foreign-cuisine engine. Foreign-cookbook submissions, traditional-cuisine research papers.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-cuisine articulation gathers.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H articulation peaks. Submit the foreign-cuisine piece.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Articulation fades. Foreign-cuisine submission on record.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Articulation on detached-food-communication. Solitary-cooking notes, lineage-recipe production without audience.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-cooking writing gathers.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H articulation peaks. Ship the lineage-cooking notes.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Articulation fades. Solitary-cooking piece stands alone.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Charm on moksha-solar food engine. Foreign-warmth meals, confidential-collaboration cooking, retreat-relationships in food.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Approach. Shadow-meal warmth gathering.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Today Venus-on-12H-Sun peaks. Take the warm confidential meal.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Charm fades. Shadow-meal warmth locked.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Charm on community-meal warmth. Alumni warm-cookbook events, community-recipe affection.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Approach. Network-meal charm gathering.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Today Venus-on-network peaks. Take the warm peer-cooking call.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Charm fades. Lock warm-network cooking-bonds.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Charm on yogakaraka body. Personal-cuisine framing radiates; client-meals convert with relational warmth.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka-charm gathering.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Today Venus-on-yogakaraka peaks. Sign the warm cuisine-contract.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Charm fades. Lock warm-channel cooking-relationships.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus return — partnership-meal engine peaks. Shared-cuisine commitment, spouse-cooking warmth, principal-restaurant relationship locked.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Venus return approaching. Prep partnership-meal move.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Venus return peak. Lock structural partnership-meal commitment.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Venus return closing. Partnership-meals on record.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Charm on cleanse-engine. Severance / inheritance / health-event meals negotiated warmly.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Approach. Cleanse-warmth gathering.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Today Venus-on-Mars-8H peaks. Eat with grace through the cleanse.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Charm fades. Warm cleanse on record.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Charm on home-kitchen / Hamsa. Real-estate kitchen-beauty, mother-channel warmth, family-meal soft-power.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen charm gathering.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-charm peaks. Beautify the kitchen; host the warm family-meal.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Charm fades. Lock warm home-kitchen move.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Charm on disciplined-eating engine. Structured-protocol picks up grace; child-related meals warm.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Approach. Discipline-charm gathering.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Today Venus-on-Saturn-5H peaks. The rigorous-protocol picks up grace.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Charm fades. Graceful-rigorous discipline on record.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Charm on foreign-cuisine engine. Foreign-stage cuisine talks land warmly, ethical-food intros.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-cuisine charm gathering.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Today Venus-on-Rahu-9H peaks. Take the warm foreign-cuisine talk.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Charm fades. Warm foreign-cuisine bond on record.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Charm on detached-food-communication. Warm solitary-cooking note; gentle-research correspondence.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-cooking warmth gathering.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Today Venus-on-Ketu-3H peaks. Send the warm solitary-cooking note.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Charm fades. Gentle-research bond on record.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Force on moksha-solar engine. Confidential / retreat-cleanse mandates sharpen.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Approach. Retreat-cleanse force gathers.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Today force-on-12H-Sun peaks. Push the retreat-protocol hard.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Force fades. Retreat-cleanse gains lock in.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Force on wide-network meals. Aggressive group-cooking dynamics. Watch group-friction at the table.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Approach. Network-meal push gathers.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Today force-on-network-meals peaks. Take the bold group-cooking stance.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Force fades. Network-meal gains locked.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Force on yogakaraka body. Aggressive personal-protocol push; sharp dietary demands. Body needs cooling, rest after.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Approach. Personal-protocol gathers force.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Today force-on-yogakaraka peaks. Cool the system; avoid spicy excess.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Force fades. Lock food-protocol; rest.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Force on partnership-meals. Sharp food-friction with spouse; cool the kitchen temperature.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Approach. Partnership-meal friction gathers.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Today partnership-meal force peaks. Cool the relational-kitchen temperature.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Force fades. Partnership-meals consolidate on new terms.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars return — surgical-cleanse peak. Panchakarma, deep-fasting, intense-protocol experiments resolve under disciplined hand.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Mars return approaching. Cleanse-push gathers.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Mars return peak. Walk through the cleanse with full rest in support.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Mars return closing. Cleanse-resolution on record.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Force on home-kitchen / Hamsa. Property-related kitchen-stress; family-business friction at the table.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen friction gathers.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Today force-on-Jupiter-4H peaks. The kitchen-renovation negotiation reaches its point.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Force fades. Home-kitchen consolidates.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Force on disciplined-eating engine. Push to consolidate the food-protocol; competitive contest with own discipline.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Approach. Food-discipline push gathers.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Today force-on-Saturn-5H peaks. Lock the structured-eating protocol.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Force fades. Disciplined-eating gains lock in.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Force on foreign-cuisine engine. Aggressive doctrinal-food disputes (vegetarian/non-veg debates).' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Approach. Food-doctrine fight gathers.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Today force-on-Rahu-9H peaks. Take the food-doctrine stand.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Force fades. Food-doctrine stand on record.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Force on detached-food-communication engine. Sharp solitary cooking; fierce sibling-table confrontation.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Approach. Fierce-solitary cooking push gathers.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Today force-on-Ketu-3H peaks. Cook the brave solitary meal.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Force fades. Solitary-cooking push consolidated.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom on the moksha-solar food engine. Retreat-meal protocols, monastery-style simplicity, dawn-eating rituals gain dharma weight.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Approach. Retreat-meal practice gathering dharma weight.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Today wisdom-on-12H-Sun peaks. Lock the retreat-meal commitment.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Wisdom fades. The retreat-eating practice on record.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on community-meal warmth. Cooperative-kitchen institutionalization, alumni-cookbook ethical structures.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Approach. Community-meal channel picks up dharma framing.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Today wisdom-on-network peaks. Anchor wide-network meals in ethical structure.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Wisdom fades. The dharma-aligned community-meal architecture locked.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom touches the central yogakaraka body. Personal-food protocol picks up doctrinal weight; lineage-eating philosophy locks in.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Approach. Personal-food framing gathers lineage authority.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Today wisdom-on-yogakaraka peaks. Take the principal-of-cuisine framing.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Wisdom fades. The lineage-anchored food-self locked.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on the exalted partnership-meal engine. Couples-cooking philosophy consolidation, shared-recipe library, partner-cuisine teaching.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Approach. Partnership-meals pick up dharma weight.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Today wisdom-on-Venus-7H peaks. Lock the dharma-aligned shared-meal commitment.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Wisdom fades. The principled partnership-meals consolidated.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on the surgical-cleanse engine. Panchakarma protocols, fasting cycles, transformation-grade dietary moves take dharma-weight.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Approach. Cleanse-protocol gathering dharma framing.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Today wisdom-on-Mars-8H peaks. Lock the dharma-aligned cleanse protocol.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Wisdom fades. The principled cleanse on record.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter return — most important food-aspect of the chart. Hamsa-Yoga territory amplified. Year-block for kitchen renovation, family-recipe archive, mother-line food tradition documentation.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Jupiter return approaching. Prep the home-kitchen move.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Jupiter return peak. Renovate the kitchen, archive the family recipes.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Jupiter return closing. The home-kitchen lineage move consolidated.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on the disciplined-eating engine. Cookbook framework receives lineage-authority; structured fasting institutionalizes.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Approach. Food-discipline picks up lineage weight.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Today wisdom-on-Saturn-5H peaks. Lock the institutional cookbook / fasting curriculum.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Wisdom fades. The disciplined-eating architecture institutionalized.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Wisdom on the foreign-cuisine engine. Unconventional cooking-teacher gains lineage authority; foreign credentialing in cuisine.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-cuisine move gathers framing.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Today wisdom-on-Rahu-9H peaks. Take the unconventional cuisine-teacher track.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Wisdom fades. Foreign-cuisine path on record.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on detached-food-communication. Solitary cooking, food-doctrine writing without audience-pressure.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-food framing gathers.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Today wisdom-on-Ketu-3H peaks. Publish the lineage-cooking research.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Wisdom fades. The solitary-cooking output locked.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Discipline on moksha-solar food engine. Long-arc retreat-meal protocols; structural shadow-eating practice.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Approach. Retreat-meal discipline cycle beginning.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Today Saturn-on-12H-Sun peaks. Lock the long-arc retreat-meal commitment.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Discipline phase closing. Shadow-meal structure in place.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Discipline on community-meal channel. Structural rebuild of alumni / community / cookbook channels.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Approach. Community-meal discipline cycle beginning.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Today Saturn-on-network peaks. Some friend-tables fall away; deep ones lock in.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Discipline phase closing. Pruned food-network structural.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Discipline on yogakaraka body. Slow personal-food re-architecture. Body weight, posture, food rules tighten.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka food-discipline beginning.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Today Saturn-on-yogakaraka peaks. Make the lean, principled food-statement.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Discipline closing. Leaner food-self in place.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Discipline on partnership-meals. Shared-cuisine routines tested for structural soundness.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Approach. Partnership-meal discipline cycle beginning.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Today Saturn-on-Venus-7H peaks. Structural partnership-meal decision lands.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Discipline phase closing. Sound partnership-meals on record.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Discipline on cleanse-engine. Heavy-but-gold long-arc cleanse work; panchakarma over years.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Approach. Cleanse-discipline cycle beginning.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Today Saturn-on-Mars-8H peaks. Lock the long-arc cleanse protocol.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Discipline phase closing. Structural cleanse in place.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Discipline on home-kitchen / Hamsa. Heavy chapter for kitchen renovation, family-meal restructure. Foundational architecture built here.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen discipline cycle beginning.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Today Saturn-on-Jupiter-4H peaks. Structural kitchen / family-meal decision lands.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Discipline phase closing. Home-kitchen foundation structural.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn return — disciplined-eating chapter peak. Institutional-grade food protocol; structured fasting; the moat lasts decades.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn return approaching. Disciplined-eating chapter gathering.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Saturn return peak. Lock the institutional food-protocol.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn return closing. Multi-decade food-moat in place.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Discipline on foreign-cuisine engine. Slow, structural foreign-cuisine credentialing.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-cuisine discipline cycle beginning.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Today Saturn-on-Rahu-9H peaks. Lock the foreign-cuisine credential.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Discipline phase closing. Foreign-cuisine structure in place.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Discipline on detached-food-communication. Long-form solitary cooking, lineage-recipe production multi-year cadence.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-cooking discipline beginning.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Today Saturn-on-Ketu-3H peaks. Lock the long-form solitary-cooking project.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Discipline phase closing. Lineage-cooking output on record.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Disruption on moksha-solar food engine. Sudden foreign / retreat-cleanse mandate; speculative shadow-meal work.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Approach. Disruptive retreat-meal move gathering.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Today Rahu-on-12H-Sun peaks. Take the unconventional retreat-cleanse.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Disruption fading. Lock or release unconventional move.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Disruption on community-meal warmth. Foreign-friend windfalls in food, viral cooking moves.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Approach. Network-meal disruption gathering.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Today Rahu-on-network-meals peaks. Ride the viral wave; take unconventional cooking-seat.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Disruption fading. Decide which gains stay.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Disruption on yogakaraka body. Unconventional / foreign personal food-pivot. Risk: identity-overreach in eating; reward: breakthrough.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Approach. Disruptive food-self move gathering.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Today Rahu-on-yogakaraka peaks. Try the unconventional food protocol.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Disruption fading. Lock breakthrough; drop overreach.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Disruption on partnership-meals. Foreign-spouse-cuisine introductions, unconventional shared-meal structures.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Approach. Disruptive partnership-meal move gathering.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Today Rahu-on-Venus-7H peaks. The unconventional shared-cuisine declaration lands.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Disruption fading. Unusual partnership-meals consolidated.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Disruption on cleanse-engine. Speculative-cleanse experiments, unconventional inheritance of recipes.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Approach. Disruptive cleanse gathering.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Today Rahu-on-Mars-8H peaks. Walk into high-velocity cleanse with rest support.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Disruption fading. Cleanse gains documented.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Disruption on home-kitchen / Hamsa. Foreign-kitchen windows, unconventional family-cuisine pivots.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen disruption gathering.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Today Rahu-on-Jupiter-4H peaks. Take the foreign-kitchen / unconventional move.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Disruption fading. Unconventional kitchen move consolidated.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Disruption on disciplined-eating engine. Speculative-creative food experiments, foreign-curriculum cuisine ventures.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Approach. Discipline-disruption gathering.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Today Rahu-on-Saturn-5H peaks. Take the speculative-creative food venture; ground in discipline.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Disruption fading. Unconventional-creative food output on record.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Rahu return — foreign-cuisine engine peaks. Unconventional cooking-teacher, foreign credentialing, disruptive food-doctrine.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return approaching. Foreign-cuisine chapter gathering.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Rahu return peak. Make the foreign-cooking-teacher move.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return closing. Unconventional cuisine path consolidated.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Nodal-axis activation on food-communication. Foreign / disruptive cooking-content, viral recipe writing.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Approach. Nodal-axis food-communication disruption gathering.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Today nodal-axis peak. Viral / foreign cooking-content lands.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal pressure fading. Unconventional content gains documented.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on the moksha-solar food engine. The 12H Sun thins further — pure shadow-lane eating, ego-free retreat meals.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Approach. The 12H solar food-fire dims.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Today detachment-on-12H-Sun peaks. Best for monastery-meal simplicity.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Detachment fading. The shadow-meal practice consolidates.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on community-meal warmth. Some friend-tables drift; the alumni-cookbook quiets. Prune the food-network.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Approach. Group-meal warmth fades.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Today network-meal-detachment peaks. Trust the silence.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Detachment fading. Pruned food-network reveals real members.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on the yogakaraka body. Food-identity stripping; the principal-cuisine essence remains; ego-frame thins.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Approach. Public food-frame loosens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Today food-identity detachment peaks. Best for solitary cooking.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Detachment fading. Leaner food-self re-emerges.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on partnership-meals. Defer big shared-cuisine signing. Warmth feels distant; trust the lull.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Approach. Partnership-meal warmth dims.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Today shared-meal-detachment peaks. Defer cuisine commitments.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Detachment fading. Partnership-meal warmth returns.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on cleanse-engine. Cleanse-protocol arrives muted. Document; do not chase intensity.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Approach. Cleanse-thrill loosens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Today cleanse-detachment peaks. Protocol passes through quietly.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Detachment fading. The quiet cleanse on record.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on home-kitchen / Hamsa engine. Family-recipe attachment loosens; kitchen feels oddly indifferent.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-kitchen attachment loosens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-detachment peaks. Family-recipe decisions feel oddly indifferent.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Detachment fading. Home-kitchen re-engages quieter.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on disciplined-eating engine. Validation-seeking diet impulse fades; pure-form food work emerges.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Approach. Validation-attachment loosens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Today food-discipline-detachment peaks. Cook for nobody but yourself.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Detachment fading. Pure-form output stands alone.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Detachment on foreign-cuisine engine. Doctrinal certainty in food loosens; old vegetarian/non-veg / fasting positions may stop fitting.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Approach. Doctrinal food-certainty wobbles.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Today food-doctrine detachment peaks. Useful sabbatical from food-ideology.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Detachment fading. Food-doctrine returns on different terms.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Ketu return — food-communication detachment peak. Sibling-table goes quiet; food-marketing impulse fades. Pure solitary cooking.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Approach. Food-communication attachment loosens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Ketu return peak. Drop the food-marketing; the cooking stands alone.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu return closing. Re-engage food-communication on lighter terms.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
