// db/seed_advice_virgo.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga)
//     Venus=7th (Pisces, exalted — Malavya Yoga)
//     Mars=8th (Aries, own — 8L-in-8 Vipareet)
//     Jupiter=4th (Sagittarius, own — Hamsa Yoga)
//     Saturn=5th (Capricorn, own)
//     Rahu=3rd (Scorpio)  Ketu=9th (Taurus)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose advice-specific interpretations, then run:
//
//   node db/seed_advice_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./advice');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'Trust the analyst. Your central instrument is the discriminating mind — make decisions by writing them out, not by feeling them through. The pen, the spreadsheet, the structured pros-and-cons list is your dharma. Avoid moves that ask you to act before the mind has fully processed; the body will tell you it is wrong via stomach turbulence within 24 hours. The shadow: paralysis-by-analysis. Set deadlines on your own decision-making — past a date, ship the imperfect choice and adjust.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'Money decisions are partner decisions; do not make either alone. The partner — spouse, principal client, business co-founder — is genuinely the financial pivot of your life. Brief them before signing. Industries advice: lean toward deal-led, partnership-anchored work. The shadow: financial enmeshment that the relationship cannot survive separation from — keep some accounts genuinely your own, not as defection but as sovereignty.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'When the truth needs to be told, tell it surgically once and stop. The Mars-in-8H pattern lands a sharp message cleanly when delivered with discipline; it detonates the room when delivered in heat. Document before confronting. The shadow: addiction to the crisis-conversation; some weeks deserve calm — let calm be calm.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'Hamsa Yoga: the home is the temple. Decisions made at home, after a real meal cooked at home, will be wiser than decisions made on the road. Real-estate is a load-bearing pillar of your life — own the building you work from, the home you live in, the land your family roots in. Family-business is a dharma worth stewarding even if it does not look glamorous. The shadow: idealization of the home that quietly becomes refusal to leave when the dharma calls outward.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Build slow, build for permanence, and play sometimes. Saturn-in-own-sign in 5H wants creative work that compounds for decades — but also makes the work feel like duty. Schedule joy as deliberately as you schedule the regimen. Children come late and matter enormously. The shadow: gravity that turns playfulness into labor — rebellion via spontaneous play is sometimes the deepest discipline.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'Long enemies, chronic illnesses, and patient adversaries are the materials your most enduring work is built from. Vipareet potential — turn the obstacle into the case-study, the lawsuit into the textbook, the chronic illness into the protocol. The shadow: cultivating problems for material — let some chapters of life stay un-fictionalized.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Spouse arrives through the home, the family, the matriarchal channel, the educational lineage. Trust introductions from the family network. Marriage is a household, not a startup. The shadow: family expectations migrating onto the partner — clarify the dharma of the partnership separate from the lineage.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'Vipareet engine: the crises that flatten others are the platform you rise from. When the storm hits, lead from the front; when the storm is invented to make you feel useful, sit. The shadow: addiction to the high-stakes; calm life can feel like absence — sit with it.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'The principal teacher of your life arrives through the partner. Receive the influence; author your own scripture. Foreign clientele and cross-cultural partnerships compound — say yes to the international intro. The shadow: following the partner\'s dharma instead of writing your own.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'Bhadra peak — your career and your name are one. Build the personal brand patiently; the analyst-craftsman reputation is the long-arc asset. The shadow: the absence of an external boss can mean the absence of a check on bad calls — install peer-review into your own structure.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Mother-figures, female friend-circles, women-led communities are the channels that pay. Cultivate these networks; receive the mentorship offered by older women. The shadow: emotional weather steering financial decisions — separate the warmth from the contract.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'Authority is built in quiet chambers. Behind-the-scenes mandates, foreign assignments, retreats, archival work, monastic-style chief-of-staff roles — these are the throne rooms. The world catches up later. The shadow: the ego wanting visibility — the dharma wants invisibility. Honor the dharma.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, retreat-led action lands. Best for confidential moves, foreign assignments, archival projects.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, network-warmth pays. Reach out to mother-figure mentor; attend the women-led-network event.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, sharp-self decisions are best. Write the choice down; structure the move.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, home-anchored wisdom lands. Decide at home, after a meal cooked at home.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, surgical action lands. Lead the crisis-management move with discipline.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, slow-creative-discipline pays. Honor the long-arc; the patience compounds.' },
  { name: 'Venus in 7th (Dispositor)', description: 'When this engine fires, partner-led grace lands. Brief the partner; co-decide the move.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak self-radiance. Take public-facing moves, declare the role you have grown into. Watch ego-friction with father-figures and senior authorities.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on income, voice, family-finance. Negotiate fees, record the talk, lock the family-money decision.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on writing, peers, sales. Push the campaign, ship the post, lead the team-storming.' },
  { name: 'Sun Transits the 4th House', description: 'Hamsa home-throne fire. Best for real-estate decisions, family-business inflections, mother-channel calls.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on creative-discipline. Launch the long-arc thesis, the structured speculation, the mentorship role.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on adversary-management. Address the audit, the litigation, the difficult HR conversation.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on Malavya partnership. Sign the JV; renew the marriage; declare the public partnership.' },
  { name: 'Sun Transits the 8th House', description: 'Solar fire on Vipareet chamber. Lead the surgical succession move, the equity-event combat.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on Ketu zone. Release one teacher-attachment; receive the next chapter.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility. Demand the title, take the public role, lead the flagship pitch.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on emotional-network. Bonus conversations, equity true-ups, women-led-network introductions.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return on retreat-throne. Best for behind-the-scenes mandates, foreign assignments, monastic-style leadership.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional charge. Channel into a body-anchored move; choose warmth over speed.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on income and voice. Read the room before pricing; soft-spoken negotiation.' },
  { name: 'Moon Transits the 3rd House', description: 'Two-day window of warm communication. Send the brave-and-warm note; take the candid call.' },
  { name: 'Moon Transits the 4th House', description: 'Hamsa home-throne emotional peak. Cook a real meal; the reset compounds.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative-intellect. Capture the warm draft; do not over-edit.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict. Adversary may push triggers; respond from documentation, not heat.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on Malavya partnership. Read the partner temperature; warm tone wins.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on transformation. Defer high-stakes decisions two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma-detachment. Old shared-teacher attachments may dissolve.' },
  { name: 'Moon Transits the 10th House', description: 'Career-emotion peak. Public reception is warm; take the warm-toned client meeting.' },
  { name: 'Moon Transits the 11th House', description: 'Moon\'s own-sign return on gain-throne. Reach out to mother-figure mentor; the warm-network call lands.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; foreign and confidential pull. Best for retreat-planning, dream-led strategy.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury\'s Bhadra return. Peak self-articulation. Refresh the bio, the founder-story, the personal pitch.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Renegotiate fees; lock the family-finance plan.' },
  { name: 'Mercury Transits the 3rd House', description: 'Sharp short-burst communication. Content production, sales sequences, sibling-channel deals.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp Hamsa home-throne articulation. Real-estate paperwork, family-business memos, mother-channel correspondence.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative-discipline articulation. Ship the thesis chapter, the course module, the speculation memo.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp adversary-articulation. Audit memos, litigation briefs, HR documentation — surgical precision wins.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp Malavya partnership articulation. Term sheets, JV memos, contract negotiations.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp Vipareet articulation. Succession plans, restructuring memos, equity-event paperwork.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma articulation. Publish the paper, file the foreign certification, draft the curriculum.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp career-public articulation. Press releases, all-hands updates, status memos.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Community-platform updates, mother-figure-mentorship correspondence.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp behind-the-scenes articulation. Confidential memos, foreign correspondence, retreat-strategy drafts.' },
  { name: 'Venus Transits the 1st House', description: 'Beauty on the analyst-self. The room responds to your refined precision; charm-led moves win where pure analysis would not.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on income and voice. Pricing rises; voice-projects favored.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on communication. Tone the message; soften the pitch.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on Hamsa home-throne. Aesthetic upgrades; family-channel warmth; mother-call.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on creative-discipline. Polished course design, elegant thesis defense.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on conflict. Mediated settlements, charm-led HR.' },
  { name: 'Venus Transits the 7th House', description: 'Venus on Malavya throne. Peak partnership month. Sign the warm JV; take the anniversary moment.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in Vipareet chamber. Equity-event diplomacy; succession with grace.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on dharma. International stage with grace; cross-cultural diplomacy.' },
  { name: 'Venus Transits the 10th House', description: 'Public-aesthetic visibility. Brand campaigns; design-led PR; senior-network reads you as elegant.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on emotional-network. Cooperative-platform diplomacy; women-led-network warmth.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on retreat-throne. Confidential design work; foreign-luxury back channel.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on body-mind. Bold founder-craftsman moves; watch impulsivity. Pair speed with discipline.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on income and voice. Argue from documentation, not heat.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on communication. Bold sales sequences, fierce pitch-mode.' },
  { name: 'Mars Transits the 4th House', description: 'Mars on Hamsa home-throne. Property disputes, family friction. Don\'t fight family in heat — wait two days.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on creative-discipline. Bold creative shipping; contested speculative bets.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on adversary — strong terrain. The fight is winnable. Press the audit, push the lawsuit, fire the difficult subordinate.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on Malavya partnership. Bold deal-making; force-clarified partnership conversations.' },
  { name: 'Mars Transits the 8th House', description: 'Mars on its own Vipareet throne. Peak transformation-action year. Lead the surgical succession; force the equity-event resolution.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on dharma-detachment. Bold teaching declarations, foreign-credential pushes.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on career-throne. Bold public moves; demand-the-title windows. Watch heat with the boss.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on emotional-network. Contested cooperative-platform pushes; bold mother-figure-network engagement.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential combat. Behind-the-scenes warrior; watch hidden enemies.' },
  { name: 'Jupiter Transits the 1st House', description: 'Major year for self-expansion. Accept the role-elevation; declare the larger ambition. Discipline diet — Jupiter expands the body too.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Major year for income and voice expansion. Salary-jumps, family-money inflows, voice-project breakthrough.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Major year for communication-expansion. Publishing, broadcasting, sales-leadership growth.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter on Hamsa throne. Peak home-throne expansion year. Real-estate acquisition; family-business growth; school-leadership offers.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for creative-discipline expansion. Course-platform breakthrough, multi-year-thesis publication, mentor-of-mentees role.' },
  { name: 'Jupiter Transits the 6th House', description: 'Major year for adversary-victory. Long lawsuits resolve favorably; chronic adversaries fade.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major year for Malavya partnership expansion. Marriage, principal-client, JV principal arrive.' },
  { name: 'Jupiter Transits the 8th House', description: 'Major year for Vipareet transformation gains. Inheritance, severance, equity-event windfall.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major year for dharma-expansion. Foreign credentials, teaching-platform breakthrough, judicial endorsements.' },
  { name: 'Jupiter Transits the 10th House', description: 'Major year for public-career expansion. Chief-of-something offers, prestige roles, board appointments.' },
  { name: 'Jupiter Transits the 11th House', description: 'Major year for emotional-network gain. Bonus-pool windfall, equity true-up, women-led-network elevation.' },
  { name: 'Jupiter Transits the 12th House', description: 'Major year for behind-the-scenes expansion. Foreign work, retreats, confidential mandates, pilgrimage chapter.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on body and identity. Health discipline mandatory; vanity falls away.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on income, voice, family-finance.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on communication. Long-arc content systems compound.' },
  { name: 'Saturn Transits the 4th House', description: 'Multi-year discipline on Hamsa home-throne. Real-estate restructuring; family-reckoning.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn on its own creative throne. Peak structural-creative chapter of the cycle. The 10-year thesis lands.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain. Multi-year peak adversary-management. Patience-and-paperwork wins.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of Malavya partnership. Weak deals end; strong ones formalize for 30 years.' },
  { name: 'Saturn Transits the 8th House', description: 'Multi-year reckoning in Vipareet chamber. Patience pays.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year dharma-discipline. Long credential paths; slow climb to elder-teacher status.' },
  { name: 'Saturn Transits the 10th House', description: 'Multi-year structural-career chapter. Slow recognition; foundation-laying for legacy authority.' },
  { name: 'Saturn Transits the 11th House', description: 'Multi-year discipline on emotional-network. Cooperative platforms formalize; board roles consolidate.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on behind-the-scenes. Long retreat-chapter; quiet authority builds.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive identity-reinvention. Verify each move; the obsession runs hot.' },
  { name: 'Rahu Transits the 2nd House', description: 'Eighteen-month obsession on income and voice. Verify get-rich schemes.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on its strong terrain (3H). Eighteen-month obsessive communication chapter. Viral content, controversial messaging — verify integrity.' },
  { name: 'Rahu Transits the 4th House', description: 'Eighteen-month home-throne obsession. Foreign-property pull; verify titles.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month obsessive creative chapter. Speculation, viral courses — verify ethical bedrock.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Eighteen-month obsessive adversary-defeat chapter.' },
  { name: 'Rahu Transits the 7th House', description: 'Eighteen-month obsessive partnership chapter. Verify counterparty integrity.' },
  { name: 'Rahu Transits the 8th House', description: 'Eighteen-month obsessive Vipareet chapter. Verify everything in the opaque deal.' },
  { name: 'Rahu Transits the 9th House', description: 'Eighteen-month foreign-dharma obsession on Ketu zone. Vet the controversial teacher.' },
  { name: 'Rahu Transits the 10th House', description: 'Eighteen-month career-reinvention obsession. Verify each pivot.' },
  { name: 'Rahu Transits the 11th House', description: 'Eighteen-month obsessive wide-network chapter. Verify integrity.' },
  { name: 'Rahu Transits the 12th House', description: 'Eighteen-month foreign-confidential obsession. Hidden mandates, off-balance-sheet intensities.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping. Old persona feels empty. Sit; do not over-correct.' },
  { name: 'Ketu Transits the 2nd House', description: 'Eighteen-month detachment from income, voice, family-money. Cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Eighteen-month communication-detachment. Old content-loops feel finished.' },
  { name: 'Ketu Transits the 4th House', description: 'Eighteen-month home-throne detachment. Old real-estate plans feel weightless.' },
  { name: 'Ketu Transits the 5th House', description: 'Eighteen-month creative-detachment. Old performance-loops feel finished.' },
  { name: 'Ketu Transits the 6th House', description: 'Eighteen-month adversary-detachment. Long enemies fade quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Eighteen-month partnership-detachment. Old deal feels finished.' },
  { name: 'Ketu Transits the 8th House', description: 'Eighteen-month transformation-acceleration. Old crises evaporate.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on its own placement. Peak dharma-detachment chapter. Old guru-loyalties dissolve completely.' },
  { name: 'Ketu Transits the 10th House', description: 'Eighteen-month career-eclipse. Old role feels weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month wide-network detachment. Old friend-circles drift.' },
  { name: 'Ketu Transits the 12th House', description: 'Eighteen-month behind-the-scenes detachment. Old retreats close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through the analyst-craftsman persona. Take public stage.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish public-facing materials.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the stage; declare the role.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Convert into binding title.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Peak career-visibility window. Launch flagship initiatives.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-visibility day. Take the elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-visibility window closes. Lock in title or compensation.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Warm reception possible.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Receive the warmth.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public reputation.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional career window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional career day. Take the warm-toned senior call.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional career window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury\'s Bhadra throne. Peak self-articulation. Refresh CV; structure the choice.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Bhadra-self window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak Bhadra day. Send the carefully-articulated note; make the structured decision.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Bhadra-self window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp career-communication. Publish; present.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-communication window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Publish, present, send the formal update.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-communication window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Beauty on the analyst-self. Make the warm ask; charm-led moves win.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Venus-self window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. The warm ask works.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Venus-self window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens the public face. Brand campaigns; design-led PR.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-career window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak day. Launch the campaign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-career window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold body-anchored self-action; warrior moves.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Take the bold move.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold career action.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak career-action day. Lead.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the role-elevation.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the elevation.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the chief role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity. Slow down; build for permanence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Heavy structural pressure on career. Foundation-laying for legacy.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak career-discipline day.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-discipline window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion; verify each move.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window begins.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak reinvention day. Check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic visibility expansion. Verify before pivoting.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Career-reinvention window begins.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Career-reinvention window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. Sit with the dissolution.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak stripping day. Do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. Don\'t cling to a role wanting to end.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse window begins.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak career-eclipse day. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting your creative-discipline engine. Multi-year creative-platform transformation.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day. Old creative frameworks dismantle.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Structural-transformation chapter completes; rebuilt authority.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the Malavya partnership engine. Unexpected partner pivots.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden partnership disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak partnership disruption day. The relational pivot is forced.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Partnership disruption window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar light on retreat-throne. Best for behind-the-scenes mandates, foreign assignments, archival-research roles.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Retreat-throne window opens.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Peak day. Take the foreign assignment, the archival role.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Retreat-throne window closes.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar fire on emotional-network. Mother-figure mentorship inflection; women-led-network visibility.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Emotional-network window opens.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Peak day. Accept the mother-figure mentorship inflection.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Emotional-network window closes.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar fire on Bhadra. Founder-as-craftsman declaration; technical-authorship publication.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Bhadra-fire window opens.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Peak Bhadra-solar day. Publish; declare; launch.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Bhadra-fire window closes.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar fire on Malavya partnership. Anchor-deal visibility; spouse elevation; principal-client expansion.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Malavya-fire window opens.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Peak Malavya day. Sign the JV; take the deal public.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Malavya-fire window closes.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar fire on Vipareet engine. Surgical succession move; equity-event combat.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Vipareet-fire window opens.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Peak Vipareet-solar day. Lead the restructuring; force the resolution.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Vipareet-fire window closes.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar fire on Hamsa home-throne. Real-estate visibility, family-business public moves.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Hamsa-fire window opens.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Peak Hamsa-solar day. Acquire the property; expand the family business.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Hamsa-fire window closes.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar fire on creative-discipline. Long thesis defense; course-platform launch; mentorship debut.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Creative-discipline-fire window opens.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Peak day. Defend the thesis; launch the platform.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Creative-discipline-fire window closes.' },
  { name: 'Sun aspect Rahu in 3rd house', description: 'Solar fire on viral-content zone. Verify integrity before publishing.' },
  { name: 'Sun aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-fire window opens.' },
  { name: 'Sun aspect Rahu in 3rd house : Exact', description: 'Peak day. Take the bold communication move with full ethical-bedrock check.' },
  { name: 'Sun aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-fire window closes.' },
  { name: 'Sun aspect Ketu in 9th house', description: 'Solar light on dharma-detachment. Old guru-attachments dissolve; principle remains.' },
  { name: 'Sun aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-fire window opens.' },
  { name: 'Sun aspect Ketu in 9th house : Exact', description: 'Peak day. Release the old teacher-attachment.' },
  { name: 'Sun aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-fire window closes.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on retreat-throne. Quiet authority rises; pause public moves.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Retreat-emotion window opens.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Peak day. Take the confidential meeting; write the private memo.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Retreat-emotion window closes.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon\'s own-sign return on gain-throne. Peak monthly emotional-network warmth.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Gain-emotion window opens.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Peak day. Reach out to mother-figure mentor; take the women-led-network call.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Gain-emotion window closes.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional warmth on Bhadra. The technical writing carries feeling.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Bhadra-emotion window opens.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Peak day. Write the warm technical post.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Bhadra-emotion window closes.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on Malavya partnership. Read partner temperature; soften deal-tone.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Malavya-emotion window opens.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Peak day. Lead with warmth in the JV meeting.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Malavya-emotion window closes.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on Vipareet zone. Defer restructuring move two days.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Vipareet-emotion window opens.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Peak day. Sit with transformation-anxiety; do not act in heat.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Vipareet-emotion window closes.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional warmth on Hamsa home-throne. Mother-channel calls.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Hamsa-emotion window opens.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Peak day. Cook a real meal; visit family.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Hamsa-emotion window closes.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional weight on creative-discipline. The long thesis feels heavy; honor the long arc.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Creative-discipline-emotion window opens.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Peak day. Honor the slow craft; the heaviness is the foundation.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Creative-discipline-emotion window closes.' },
  { name: 'Moon aspect Rahu in 3rd house', description: 'Emotional swing on communication-chaos. Verify before publishing in heat.' },
  { name: 'Moon aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-emotion window opens.' },
  { name: 'Moon aspect Rahu in 3rd house : Exact', description: 'Peak day. Defer the viral-content move two days.' },
  { name: 'Moon aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-emotion window closes.' },
  { name: 'Moon aspect Ketu in 9th house', description: 'Emotional detachment from teacher.' },
  { name: 'Moon aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-emotion window opens.' },
  { name: 'Moon aspect Ketu in 9th house : Exact', description: 'Peak day. Sit with the teacher-attachment dissolving.' },
  { name: 'Moon aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-emotion window closes.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Sharp articulation of retreat-throne. Confidential memos, foreign correspondence.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Retreat-articulation window opens.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Peak day. Send the confidential memo.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Retreat-articulation window closes.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Sharp articulation on emotional-network. Community correspondence; mother-figure-mentor letter.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Network-articulation window opens.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Peak day. Send the warm community-letter.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Network-articulation window closes.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury\'s Bhadra return. Peak self-articulation day. The mind is at its sharpest annual setting.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Bhadra peak window opens.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Peak Bhadra day. Make the year\'s clearest decisions; ship the masterpiece deliverable.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Bhadra peak window closes.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Sharp Malavya partnership articulation. Term sheets, JV memos.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Partnership-articulation window opens.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Peak day. Send the term sheet; sign the contract.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Partnership-articulation window closes.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Sharp Vipareet articulation. Succession plans; restructuring memos; equity-event paperwork.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Vipareet-articulation window opens.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Peak day. Document the opaque deal precisely.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Vipareet-articulation window closes.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Sharp Hamsa home-throne articulation. Real-estate paperwork, family-business memos.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Hamsa-articulation window opens.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Peak day. File the property paper.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Hamsa-articulation window closes.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Sharp creative-discipline articulation. Multi-year-thesis chapters, course-module memos.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Creative-discipline-articulation window opens.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Peak day. Ship the thesis chapter.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Creative-discipline-articulation window closes.' },
  { name: 'Mercury aspect Rahu in 3rd house', description: 'Sharp communication-chaos articulation. Viral-content drafts — verify integrity.' },
  { name: 'Mercury aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-articulation window opens.' },
  { name: 'Mercury aspect Rahu in 3rd house : Exact', description: 'Peak day. Polish the viral-content draft; verify before publishing.' },
  { name: 'Mercury aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-articulation window closes.' },
  { name: 'Mercury aspect Ketu in 9th house', description: 'Sharp dharma-detachment articulation. Audit teacher-attachments.' },
  { name: 'Mercury aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-articulation window opens.' },
  { name: 'Mercury aspect Ketu in 9th house : Exact', description: 'Peak day. Write the closure note to the old teacher-channel.' },
  { name: 'Mercury aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-articulation window closes.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Beauty on retreat-throne. Confidential design work; foreign-luxury back channel.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Retreat-beauty window opens.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Peak day. Soften the confidential meeting; design the elegant retreat space.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Retreat-beauty window closes.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Beauty on emotional-network. Cooperative-platform diplomacy.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Network-beauty window opens.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Peak day. Take the warm women-led-network call.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Network-beauty window closes.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Beauty on Bhadra craftsman-throne. Refine the technical aesthetic.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Bhadra-beauty window opens.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Peak day. Polish the technical writing.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Bhadra-beauty window closes.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus on Malavya throne. Peak partnership-grace day. The deal closes warmly.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Malavya peak window opens.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Peak Malavya day. Take the elegant partnership move.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Malavya peak window closes.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Beauty in Vipareet chamber. Equity-event diplomacy.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Vipareet-beauty window opens.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Peak day. Take the elegant succession meeting.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Vipareet-beauty window closes.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Beauty on Hamsa home-throne. Property diplomacy; family-business charm.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Hamsa-beauty window opens.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Peak day. Soften the property negotiation.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Hamsa-beauty window closes.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Beauty on creative-discipline. Polished course design.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Creative-discipline-beauty window opens.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Peak day. Polish the course visuals.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Creative-discipline-beauty window closes.' },
  { name: 'Venus aspect Rahu in 3rd house', description: 'Beauty on communication-chaos zone. Polished viral content — verify integrity.' },
  { name: 'Venus aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-beauty window opens.' },
  { name: 'Venus aspect Rahu in 3rd house : Exact', description: 'Peak day. Polish the viral-content draft.' },
  { name: 'Venus aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-beauty window closes.' },
  { name: 'Venus aspect Ketu in 9th house', description: 'Beauty on dharma-detachment. Old teacher-aesthetic feels weightless.' },
  { name: 'Venus aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-beauty window opens.' },
  { name: 'Venus aspect Ketu in 9th house : Exact', description: 'Peak day. Release the old teacher-aesthetic.' },
  { name: 'Venus aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-beauty window closes.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Mars on retreat-throne. Behind-the-scenes warrior moves; foreign-mandate aggression.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Retreat-fire window opens.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Peak day. Take the confidential force-play.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Retreat-fire window closes.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Mars on gain-network. Bold mother-figure-network moves; contested cooperative-platform pushes.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Gain-fire window opens.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Peak day. Push the network move.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Gain-fire window closes.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Mars on Bhadra craftsman-throne. Bold founder-craftsman moves.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Bhadra-fire window opens.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Peak day. Take the bold technical-authorship move.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Bhadra-fire window closes.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Mars on Malavya partnership. Bold deal-making.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Malavya-fire window opens.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Peak day. Sign the JV; force the partnership clarity.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Malavya-fire window closes.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars on its own Vipareet throne. Peak transformation-fire day. Surgical action at full force.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Vipareet peak window opens.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Peak Vipareet day. Lead the restructuring; force the resolution.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Vipareet peak window closes.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Mars on Hamsa home-throne. Property disputes, family friction. Don\'t fight family in heat.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Hamsa-fire window opens.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Peak day. Defer family confrontation two days.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Hamsa-fire window closes.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Mars on creative-discipline. Bold creative shipping.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Creative-fire window opens.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Peak day. Ship the bold thesis; place the contested bet.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Creative-fire window closes.' },
  { name: 'Mars aspect Rahu in 3rd house', description: 'Mars on communication-chaos. Bold viral-content pushes.' },
  { name: 'Mars aspect Rahu in 3rd house : Starts', description: 'Communication-fire window opens.' },
  { name: 'Mars aspect Rahu in 3rd house : Exact', description: 'Peak day. Push the contested piece — verify integrity.' },
  { name: 'Mars aspect Rahu in 3rd house : Ends', description: 'Communication-fire window closes.' },
  { name: 'Mars aspect Ketu in 9th house', description: 'Mars on dharma-detachment. Forceful release of teacher-attachments.' },
  { name: 'Mars aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-fire window opens.' },
  { name: 'Mars aspect Ketu in 9th house : Exact', description: 'Peak day. Forcefully close the dead teacher-channel.' },
  { name: 'Mars aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-fire window closes.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom on retreat-throne. Confidential mandate elevation; foreign assignment expansion.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Retreat-expansion window opens.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Peak day. Accept the confidential mandate elevation.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Retreat-expansion window closes.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on emotional-network. Bonus-pool windfall; women-led-network elevation.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Gain-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Peak day. Take the bonus; accept the equity true-up.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Gain-expansion window closes.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom on Bhadra throne. Founder-craftsman elevation; technical-authorship breakthrough.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Bhadra-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Peak day. Accept the founder-craftsman elevation.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Bhadra-expansion window closes.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on Malavya partnership. Anchor-deal expansion; marriage inflection.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Malavya-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Peak day. Sign the elevated JV; accept the marriage inflection.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Malavya-expansion window closes.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on Vipareet engine. Inheritance windfall; succession-led elevation.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Vipareet-expansion window opens.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Peak day. Take the inheritance; accept the succession elevation.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Vipareet-expansion window closes.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter on its own Hamsa throne. Peak home-throne expansion day. Real-estate windfall; family-business inflection.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Hamsa peak window opens.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Peak Hamsa day. Acquire the property; expand the family business.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Hamsa peak window closes.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on creative-discipline. Course-platform breakthrough; multi-year-thesis publication.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Creative-discipline-expansion window opens.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Peak day. Launch the course platform; defend the thesis.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Creative-discipline-expansion window closes.' },
  { name: 'Jupiter aspect Rahu in 3rd house', description: 'Wisdom on communication-chaos. Viral-content elevation; controversial-journalism breakthrough.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Starts', description: 'Communication-chaos-expansion window opens.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Exact', description: 'Peak day. Take the bold viral-content move.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Ends', description: 'Communication-chaos-expansion window closes.' },
  { name: 'Jupiter aspect Ketu in 9th house', description: 'Wisdom on dharma-detachment. The released teacher-attachment becomes its own teaching.' },
  { name: 'Jupiter aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-expansion window opens.' },
  { name: 'Jupiter aspect Ketu in 9th house : Exact', description: 'Peak day. Convert the released attachment into your own teaching.' },
  { name: 'Jupiter aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-expansion window closes.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Structural pressure on retreat-throne. Long confidential mandates; slow foreign chapters.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Retreat-discipline window opens.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Peak day. Take the slow foreign assignment.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Retreat-discipline window closes.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Structural pressure on emotional-network. Cooperative platforms formalize.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Network-discipline window opens.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Peak day. Sign the cooperative-platform charter.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Network-discipline window closes.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Structural pressure on Bhadra craftsman-throne. Slow self-evolution; vanity-skills fall away.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Bhadra-discipline window opens.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Peak day. Eliminate vanity-skills.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Bhadra-discipline window closes.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Structural pressure on Malavya partnership. Weak deals end; strong ones formalize for 30 years.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Malavya-discipline window opens.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Peak day. Divorce the weak deal; formalize the strong JV.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Malavya-discipline window closes.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Structural pressure on Vipareet engine. Inheritance disputes; equity-event delays. Patience pays.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Vipareet-discipline window opens.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Peak day. Hold the line on the slow restructuring.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Vipareet-discipline window closes.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Structural pressure on Hamsa home-throne. Real-estate restructuring; family-reckoning.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Hamsa-discipline window opens.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Peak day. Take the slow real-estate decision.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Hamsa-discipline window closes.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn on its own creative throne. Peak structural-creative day of the multi-decade cycle.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn-creative peak window opens.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Peak day. Defend the long thesis; lock in the multi-decade structure.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn-creative peak window closes.' },
  { name: 'Saturn aspect Rahu in 3rd house', description: 'Structural pressure on communication-chaos. Long-arc viral-content discipline.' },
  { name: 'Saturn aspect Rahu in 3rd house : Starts', description: 'Communication-discipline window opens.' },
  { name: 'Saturn aspect Rahu in 3rd house : Exact', description: 'Peak day. Lock in the multi-year content schedule.' },
  { name: 'Saturn aspect Rahu in 3rd house : Ends', description: 'Communication-discipline window closes.' },
  { name: 'Saturn aspect Ketu in 9th house', description: 'Structural pressure on dharma-detachment. Teacher-release formally documented.' },
  { name: 'Saturn aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-discipline window opens.' },
  { name: 'Saturn aspect Ketu in 9th house : Exact', description: 'Peak day. Sign the formal closure of the dead teacher-channel.' },
  { name: 'Saturn aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-discipline window closes.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Chaotic expansion on retreat-throne. Foreign-mandate fevers; verify each.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Retreat-chaos window opens.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Peak day. Vet the foreign mandate twice.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Retreat-chaos window closes.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Chaotic expansion on emotional-network. Sudden viral-network gains.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Network-chaos window opens.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Peak day. Take the viral-network move — verify ethical bedrock.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Network-chaos window closes.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Chaotic expansion on Bhadra craftsman-throne. Sudden self-pivots.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Bhadra-chaos window opens.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Peak day. Take the bold pivot — verify the technical bedrock.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Bhadra-chaos window closes.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Chaotic expansion on Malavya partnership. Verify counterparty integrity.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Malavya-chaos window opens.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Peak day. Vet the controversial JV thoroughly.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Malavya-chaos window closes.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Chaotic expansion on Vipareet engine. Sudden equity-event windfalls; verify everything.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Vipareet-chaos window opens.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Peak day. Take the equity-event move with full documentation.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Vipareet-chaos window closes.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Chaotic expansion on Hamsa home-throne. Foreign-property pull; verify titles.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Hamsa-chaos window opens.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Peak day. Vet the foreign-property paperwork.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Hamsa-chaos window closes.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Chaotic expansion on creative-discipline. Speculative-fevers; viral-course pulls.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Creative-chaos window opens.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Peak day. Take the speculative-creative move with full ethical-bedrock check.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Creative-chaos window closes.' },
  { name: 'Rahu aspect Rahu in 3rd house', description: 'Rahu return on its own placement. Peak communication-chaos day. Verify ethical bedrock.' },
  { name: 'Rahu aspect Rahu in 3rd house : Starts', description: 'Rahu-return communication window opens.' },
  { name: 'Rahu aspect Rahu in 3rd house : Exact', description: 'Peak Rahu-return day. Push the viral message — verify integrity.' },
  { name: 'Rahu aspect Rahu in 3rd house : Ends', description: 'Rahu-return window closes.' },
  { name: 'Rahu aspect Ketu in 9th house', description: 'Rahu-Ketu axis return on dharma-detachment. Peak teacher-attachment turbulence.' },
  { name: 'Rahu aspect Ketu in 9th house : Starts', description: 'Axis-chaos window opens.' },
  { name: 'Rahu aspect Ketu in 9th house : Exact', description: 'Peak day. Defer dharma decisions; the axis is too loud.' },
  { name: 'Rahu aspect Ketu in 9th house : Ends', description: 'Axis-chaos window closes.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on retreat-throne. Old confidential mandates feel weightless.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Retreat-detachment window opens.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Peak day. Sit with the confidential-mandate feeling weightless.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Retreat-detachment window closes.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on emotional-network. Old friend-circles drift.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Network-detachment window opens.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Peak day. Release the old friend-circle.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Network-detachment window closes.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on Bhadra craftsman-throne. Old self-persona feels hollow.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Bhadra-detachment window opens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Peak day. Sit with the craft feeling weightless; do not over-perform.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Bhadra-detachment window closes.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on Malavya partnership. Old deal feels finished.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Malavya-detachment window opens.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Peak day. Sit with the deal feeling weightless.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Malavya-detachment window closes.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on Vipareet engine. Old crises evaporate.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Vipareet-detachment window opens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Peak day. Release the old crisis-loop.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Vipareet-detachment window closes.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on Hamsa home-throne. Old real-estate plans feel weightless.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Hamsa-detachment window opens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Peak day. Sit with the home-throne feeling weightless.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Hamsa-detachment window closes.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on creative-discipline. Old performance-loops feel finished.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Creative-detachment window opens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Peak day. Release the dead creative-loop.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Creative-detachment window closes.' },
  { name: 'Ketu aspect Rahu in 3rd house', description: 'Ketu-Rahu axis stress on communication. Old viral-content loops feel finished.' },
  { name: 'Ketu aspect Rahu in 3rd house : Starts', description: 'Communication-axis-detachment window opens.' },
  { name: 'Ketu aspect Rahu in 3rd house : Exact', description: 'Peak day. Sit with the content-channel quieting.' },
  { name: 'Ketu aspect Rahu in 3rd house : Ends', description: 'Communication-axis-detachment window closes.' },
  { name: 'Ketu aspect Ketu in 9th house', description: 'Ketu return on its own placement. Peak dharma-detachment day. Old teacher-attachments dissolve completely; inner-guru surfaces.' },
  { name: 'Ketu aspect Ketu in 9th house : Starts', description: 'Ketu-return dharma window opens.' },
  { name: 'Ketu aspect Ketu in 9th house : Exact', description: 'Peak Ketu-return day. The lineage-attachment evaporates; the principle without personality crystallizes.' },
  { name: 'Ketu aspect Ketu in 9th house : Ends', description: 'Ketu-return dharma window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
