// db/seed_advice_cancer.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Cancer ascendant native with:
//   Ascendant: Cancer
//   Natal: Sun=3rd Moon=2nd Mercury=3rd Venus=4th(own) Mars=7th(exalted)
//          Jupiter=6th(own) Saturn=8th(own) Rahu=9th Ketu=3rd

const db = require('./advice');

const ASCENDANT = 'Cancer';

const events = [
  // RULERS (12)
  { name: 'Moon ruler of the 1st House in the 2nd House', description: 'Your nervous system is regulated by warm food and warm words. When in doubt today, call mother or eat lunch with a friend rather than push through alone.' },
  { name: 'Sun ruler of the 2nd House in the 3rd House', description: 'Don\'t pitch verbally; draft the one-pager. Effort + precise sequence is your wage today.' },
  { name: 'Mercury ruler of the 3rd House in the 3rd House', description: 'Send the email; ship the document; close the loop with the peer. Procrastination on small comms costs more than usual today.' },
  { name: 'Venus ruler of the 4th House in the 4th House', description: 'Tidy the workspace; cook the slow meal; call mother. The day\'s problems often dissolve in a clean kitchen.' },
  { name: 'Mars ruler of the 5th House in the 7th House', description: 'Pitch with rigor; think structurally about the date-night or the joint project.' },
  { name: 'Jupiter ruler of the 6th House in the 6th House', description: 'The boring admin, the difficult client, the long-deferred health appointment — all yield outsized rewards when you show up dharmically today.' },
  { name: 'Saturn ruler of the 7th House in the 8th House', description: 'Don\'t force; observe. Joint-finance, in-law, deep-trust matters surface slowly. Be patient.' },
  { name: 'Saturn ruler of the 8th House in the 8th House', description: 'The forensic insight, the quiet research, the long-deferred audit — all produce more than visible action.' },
  { name: 'Jupiter ruler of the 9th House in the 6th House', description: 'Listen to your father-figure mentor; show up for the hard problem with principle; the universe blesses the unglamorous fix.' },
  { name: 'Mars ruler of the 10th House in the 7th House', description: 'Sign the contract with rigor. The partner-in-the-room shapes today\'s outcome.' },
  { name: 'Venus ruler of the 11th House in the 4th House', description: 'Reach out to the senior woman in your network; the family table opens doors.' },
  { name: 'Mercury ruler of the 12th House in the 3rd House', description: 'What\'s spoken carelessly costs you; what\'s written privately compounds.' },

  // DISPOSITORS (5)
  { name: 'Mercury in 3rd (Dispositor)', description: 'The precise written word is your power. Don\'t weaponize the analysis; deploy it. Use the Virgo precision to close, not to wound.' },
  { name: 'Sun in 3rd (Dispositor)', description: 'Lead through methodical effort, not through ego. Father-figure mentor or boss respects what you ship, not what you say.' },
  { name: 'Venus in 4th (Dispositor)', description: 'Harmony is your asset. Mediate the dispute, beautify the workspace, deepen with mother. The diplomat-aesthete in you serves today.' },
  { name: 'Saturn in 8th (Dispositor)', description: 'The slow structural work is protected. The forensic deep-dive, the audit, the regulatory work all favored. Patience compounds.' },
  { name: 'Jupiter in 6th (Dispositor)', description: 'Serve the hard problem with high principle. The Hamsa in you is awake; let it work.' },

  // TRANSITS (108)
  { name: 'Sun Transits the 1st House', description: 'Push through awkward visibility today. Don\'t hide just because the spotlight feels uncomfortable. Show up modestly but consistently.' },
  { name: 'Sun Transits the 2nd House', description: 'Speak warmly today; address family-finance; the throat needs cool drinks and gentle care.' },
  { name: 'Sun Transits the 3rd House', description: 'Best day to ship the document, write the analysis, take the courage assignment.' },
  { name: 'Sun Transits the 4th House', description: 'Best day for mother-call, real-estate decision, home-as-office work.' },
  { name: 'Sun Transits the 5th House', description: 'Best day to pitch the creative idea, take the calculated risk, mentor the protégé.' },
  { name: 'Sun Transits the 6th House', description: 'Best day for the unglamorous fix; the difficult client; the boring admin that compounds.' },
  { name: 'Sun Transits the 7th House', description: 'Best day to sign the contract, formalize the partnership, demand the rigorous terms.' },
  { name: 'Sun Transits the 8th House', description: 'Best day for the surgical decision, the restructuring, the deep-research insight.' },
  { name: 'Sun Transits the 9th House', description: 'Best day for the international call, the certification effort, the principled stand.' },
  { name: 'Sun Transits the 10th House', description: 'Best day to demand the title, lead the public initiative, refresh your career materials.' },
  { name: 'Sun Transits the 11th House', description: 'Best day to accept the senior invitation, formalize the alliance, ask for the gain.' },
  { name: 'Sun Transits the 12th House', description: 'Best day for behind-scenes work, the long-form draft, the quiet retreat.' },
  { name: 'Moon Transits the 1st House', description: 'High empathy day. Lead with warmth; the room reads you generously.' },
  { name: 'Moon Transits the 2nd House', description: 'Speak from the heart; family-finance feels close.' },
  { name: 'Moon Transits the 3rd House', description: 'Send the warm note; have the empathic peer-conversation.' },
  { name: 'Moon Transits the 4th House', description: 'Peak home day. Cook; nest; mother-call.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional creative depth. Channel into focused output, not impulsive moves.' },
  { name: 'Moon Transits the 6th House', description: 'Show up for someone who needs care; service heals you.' },
  { name: 'Moon Transits the 7th House', description: 'Read the partner\'s mood before pushing terms.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight in shared-zone. Defer hard decisions; sleep more.' },
  { name: 'Moon Transits the 9th House', description: 'Capture the big-vision dream; commit later.' },
  { name: 'Moon Transits the 10th House', description: 'The room reads you. Show up regulated; protect the public face.' },
  { name: 'Moon Transits the 11th House', description: 'Reach out to the senior friend; accept the warm invitation.' },
  { name: 'Moon Transits the 12th House', description: 'Quiet day; behind-scenes work; sleep early.' },
  { name: 'Mercury Transits the 1st House', description: 'Write the personal-state update; refresh your CV warmly.' },
  { name: 'Mercury Transits the 2nd House', description: 'Make the warm-toned salary case; record the heart-led talk.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak ship day. Send the document; close the loop; the mind is sharp.' },
  { name: 'Mercury Transits the 4th House', description: 'Handle real-estate paperwork; family-business calls; mother-letter.' },
  { name: 'Mercury Transits the 5th House', description: 'Write the creative brief, the mentee email, the pitch deck.' },
  { name: 'Mercury Transits the 6th House', description: 'Write SOPs, regulatory filings, conflict-resolution emails.' },
  { name: 'Mercury Transits the 7th House', description: 'Draft contract terms; send the precise legal note.' },
  { name: 'Mercury Transits the 8th House', description: 'Depth-research day; the forensic insight lands.' },
  { name: 'Mercury Transits the 9th House', description: 'Write visionary; defer precise contract language.' },
  { name: 'Mercury Transits the 10th House', description: 'Bold career-comm; press release; LinkedIn-style update.' },
  { name: 'Mercury Transits the 11th House', description: 'Patient outreach to senior allies; deal-driven introductions.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential writing; foreign correspondence; watch leaks.' },
  { name: 'Venus Transits the 1st House', description: 'Peak charisma day. Take the client meeting; ask for the favor.' },
  { name: 'Venus Transits the 2nd House', description: 'Luxurious salary diplomacy; family-finance harmony.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful peer-comm; the difficult email turns diplomatic.' },
  { name: 'Venus Transits the 4th House', description: 'Beautify; host; deepen with mother. Annual home-peak.' },
  { name: 'Venus Transits the 5th House', description: 'Date night; creative pleasure; advisory income flows.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic service; HR work; conflict-resolution lands.' },
  { name: 'Venus Transits the 7th House', description: 'Sign the partnership; close the long-pending client.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic shared-finance; gentle inheritance conversation.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful international engagement; cross-cultural diplomacy.' },
  { name: 'Venus Transits the 10th House', description: 'Softer public face; brand campaign; design-driven launch.' },
  { name: 'Venus Transits the 11th House', description: 'Peak gain/network day. Hosting; female-mentor connection.' },
  { name: 'Venus Transits the 12th House', description: 'Quiet pleasure; foreign luxury; watch over-spending on travel.' },
  { name: 'Mars Transits the 1st House', description: 'Energy up but emotionally fragile. Push with discipline; avoid impulsive declarations.' },
  { name: 'Mars Transits the 2nd House', description: 'Heated speech; data over emotion in salary asks; throat care.' },
  { name: 'Mars Transits the 3rd House', description: 'Fierce execution. Ship hard; defend the document.' },
  { name: 'Mars Transits the 4th House', description: 'Decisive home action; watch family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Push the stalled creative project; defend authority over mentees.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable. Win the workplace dispute; settle long debts.' },
  { name: 'Mars Transits the 7th House', description: 'Sign deals; demand rigor; watch domineering tone.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical action in restructuring zone. Lead through the chaos.' },
  { name: 'Mars Transits the 9th House', description: 'Assertive foreign moves; principled stand-taking.' },
  { name: 'Mars Transits the 10th House', description: 'Bold career assertion. Demand the promotion; lead the visible battle.' },
  { name: 'Mars Transits the 11th House', description: 'Aggressive bonus negotiation; equity disputes resolved through patient pressure.' },
  { name: 'Mars Transits the 12th House', description: 'Hidden frictions stir; avoid open warfare; fight from shadows or not at all.' },
  { name: 'Jupiter Transits the 1st House', description: 'Once-in-12-years personal expansion. Plan the long-term project.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Vocal/income/family-finance expansion; ask for raises now.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Flagship effort/writing year.' },
  { name: 'Jupiter Transits the 4th House', description: 'Exalted home expansion; buy property; deepen mother-bond.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major creative/advisory/mentee growth year.' },
  { name: 'Jupiter Transits the 6th House', description: 'Service-with-wisdom peak; difficult clients become teachers.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major partnership year; choose carefully (debilitated Jupiter).' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into transformation; inheritance/severance favored.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major dharma/foreign year.' },
  { name: 'Jupiter Transits the 10th House', description: 'Career visibility expansion; aim deliberately upward.' },
  { name: 'Jupiter Transits the 11th House', description: 'Gains/network/long-held desires expand; ask for raises.' },
  { name: 'Jupiter Transits the 12th House', description: 'Foreign/sabbatical/hidden-asset domain grows; retreats produce outsized resets.' },
  { name: 'Saturn Transits the 1st House', description: 'Sade Sati 2nd leg. Slow down; build for permanence; health discipline matters.' },
  { name: 'Saturn Transits the 2nd House', description: 'Sade Sati 3rd leg. Income/voice/family-finance discipline. Speak less, write more.' },
  { name: 'Saturn Transits the 3rd House', description: 'Heavy effort/writing chapter. The years-in-the-making courage move.' },
  { name: 'Saturn Transits the 4th House', description: 'Home/family-foundation under structural test.' },
  { name: 'Saturn Transits the 5th House', description: 'Creativity/speculation demand seriousness.' },
  { name: 'Saturn Transits the 6th House', description: 'Favorable. Long workplace battles won through patience.' },
  { name: 'Saturn Transits the 7th House', description: 'Heavy partnership chapter; what survives lasts decades.' },
  { name: 'Saturn Transits the 8th House', description: 'Once-in-29-years deep transformation reckoning.' },
  { name: 'Saturn Transits the 9th House', description: 'Dharma/foreign chapter under structural pressure.' },
  { name: 'Saturn Transits the 10th House', description: 'Heavy career visibility chapter; recognition delayed but permanent.' },
  { name: 'Saturn Transits the 11th House', description: 'Gains discipline; network shrinks to the real ones.' },
  { name: 'Saturn Transits the 12th House', description: 'Sade Sati 1st leg. Structural patience required.' },
  { name: 'Rahu Transits the 1st House', description: 'Once-in-18-years identity-shock. New persona experiment; vet derailments.' },
  { name: 'Rahu Transits the 2nd House', description: 'Chaotic income/voice/family-finance; don\'t leverage on sudden wealth.' },
  { name: 'Rahu Transits the 3rd House', description: 'Explosive writing/effort; viral content; watch over-claiming.' },
  { name: 'Rahu Transits the 4th House', description: 'Chaotic home/mother dynamics; foreign-property pulls.' },
  { name: 'Rahu Transits the 5th House', description: 'Speculative obsession; discipline the gambling impulse.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat enemies; expand foreign service domains.' },
  { name: 'Rahu Transits the 7th House', description: 'Chaotic partnerships; vet counterparties rigorously.' },
  { name: 'Rahu Transits the 8th House', description: 'Sudden inheritance/severance/regulatory shocks. Vipareet activation.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign-spiritual obsession peaks; cross-border career chapter activates.' },
  { name: 'Rahu Transits the 10th House', description: 'Meteoric career shifts; sudden promotion or pivot; don\'t over-leverage.' },
  { name: 'Rahu Transits the 11th House', description: 'Unconventional gains; foreign-money streams; watch unsustainable income illusions.' },
  { name: 'Rahu Transits the 12th House', description: 'Foreign relocation; hidden-asset reshuffles; sleep-disrupting visions.' },
  { name: 'Ketu Transits the 1st House', description: 'Identity stripping. Old career-self feels empty; don\'t leap impulsively.' },
  { name: 'Ketu Transits the 2nd House', description: 'Emotional detachment from income/voice/family. Purifying.' },
  { name: 'Ketu Transits the 3rd House', description: 'Old peer/effort patterns dissolve; solo work intensifies.' },
  { name: 'Ketu Transits the 4th House', description: 'Detachment from home/mother/real-estate; selling property favored.' },
  { name: 'Ketu Transits the 5th House', description: 'Creative output feels hollow; pursue non-monetary study.' },
  { name: 'Ketu Transits the 6th House', description: 'Chronic enemies disengage; long debts close; service obligations end.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership eclipse; long contracts quietly end; don\'t cling.' },
  { name: 'Ketu Transits the 8th House', description: 'Deep karmic transformation; honor what wants to end.' },
  { name: 'Ketu Transits the 9th House', description: 'Eclipse on dharma node; mentors drift; real dharma surfaces underneath.' },
  { name: 'Ketu Transits the 10th House', description: 'Visibility flickers; promotions stall; let what wants to leave, leave.' },
  { name: 'Ketu Transits the 11th House', description: 'Network thins; transactional friends fade; the real ones remain.' },
  { name: 'Ketu Transits the 12th House', description: 'Quiet foreign/isolation chapter; sleep/dreams clarify.' },

  // ANGLE ASPECTS (72)
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Show up; take the spotlight despite discomfort.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Prepare to be seen.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Take the meeting; ask for the title.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Lock in commitments.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar fire on career zenith — public recognition window.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Refresh public materials.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Show up at your best.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-spotlight fades. Convert leads.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Peak empathic-self day.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Empathic window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Lead with warmth.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Empathic window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Lunar charge on career zenith — mood regulates visibility.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Public-emotion window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Show up regulated.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Public-emotion window fades.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury sharpens self-articulation. Best for: interviews, personal statements.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Articulation window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak articulation day. Take the interview.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Articulation closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Written authority on display.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-comm window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Present the deck.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-comm closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Peak professional charm.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Charisma window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charisma day. Take the client meeting.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charisma window fades.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Diplomatic public visibility.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Public-warmth window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Launch the brand campaign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Public-warmth closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Push with discipline; avoid impulsive declarations.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action window opens with debilitated edge.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Bold ask; calm tone.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action window fades.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Competitive battles; watch combative tone.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Defend authority.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action cools.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Once-in-12-years self-expansion.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion begins. Plan the major personal project.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Mentors notice.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion closes. Lock in title elevations.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Board-level mentor blessings.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Take the elevation.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Body/identity under structural test.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self test begins.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Slow public recognition.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Foundation laid.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-Saturn closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Rahu-self window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Take unconventional move with discipline.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu-self closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Sudden promotions; unconventional offers.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Rahu-MC window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Verify before leveraging.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu-MC closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity stripping; don\'t leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Ketu-self window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Sit with dissonance.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Ketu-self closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Don\'t cling to dissolving role.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse closes.' },

  // OUTER SPECIALS (8)
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning on Saturn (Aquarius 8H). Old hierarchies collapse; vipareet activation.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Transformation chapter completes.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption on Venus (Libra 4H). Unexpected home/mother shifts; surprise offers.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Venus-disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption closes. Integrate.' },

  // ASPECTS (324)
  // — Jupiter aspects natal —
  { name: 'Jupiter aspect Sun in 3rd house', description: 'Broad authority through writing; ship the document.' },
  { name: 'Jupiter aspect Sun in 3rd house : Starts', description: 'Window opens for flagship written work.' },
  { name: 'Jupiter aspect Sun in 3rd house : Exact', description: 'Peak day for authoritative communication. Publish; present.' },
  { name: 'Jupiter aspect Sun in 3rd house : Ends', description: 'Window closes. Lock in commitments.' },
  { name: 'Jupiter aspect Moon in 2nd house', description: 'Vocal/family-finance expansion. Speak; people listen.' },
  { name: 'Jupiter aspect Moon in 2nd house : Starts', description: 'Voice-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 2nd house : Exact', description: 'Record the talk; ask for the raise.' },
  { name: 'Jupiter aspect Moon in 2nd house : Ends', description: 'Voice-expansion closes.' },
  { name: 'Jupiter aspect Mercury in 3rd house', description: 'Peak technical/written wisdom.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Starts', description: 'Mind-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Exact', description: 'Ship the masterpiece document.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Ends', description: 'Mind-expansion closes.' },
  { name: 'Jupiter aspect Venus in 4th house', description: 'Peak home expansion.' },
  { name: 'Jupiter aspect Venus in 4th house : Starts', description: 'Home-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 4th house : Exact', description: 'Peak home day. Sign the lease; deepen with mother.' },
  { name: 'Jupiter aspect Venus in 4th house : Ends', description: 'Home-expansion closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Major partnership window.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Partnership-expansion opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak partnership day. Sign the contract.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Partnership-expansion closes.' },
  { name: 'Jupiter aspect Jupiter in 6th house', description: 'Service-with-wisdom peak.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Starts', description: 'Service window opens.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Exact', description: 'Peak service day. Hard problem yields.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Ends', description: 'Service window closes.' },
  { name: 'Jupiter aspect Saturn in 8th house', description: 'Wisdom into transformation. Inheritance/severance favored.' },
  { name: 'Jupiter aspect Saturn in 8th house : Starts', description: 'Transformation-wisdom window opens.' },
  { name: 'Jupiter aspect Saturn in 8th house : Exact', description: 'Peak transformation-blessing day.' },
  { name: 'Jupiter aspect Saturn in 8th house : Ends', description: 'Transformation-wisdom closes.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Own-sign Jupiter on dharma node. Peak foreign/dharma window.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Foreign-dharma window opens.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Peak foreign-dharma day.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Foreign-dharma closes.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on detached-comm. Solo deep work flourishes.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Solo-wisdom opens.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Peak solo-wisdom day.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Solo-wisdom closes.' },

  // — Ketu aspects natal —
  { name: 'Ketu aspect Sun in 3rd house', description: 'Authority feels hollow; ego drops out of work.' },
  { name: 'Ketu aspect Sun in 3rd house : Starts', description: 'Authority-eclipse begins.' },
  { name: 'Ketu aspect Sun in 3rd house : Exact', description: 'Dharmic message lands.' },
  { name: 'Ketu aspect Sun in 3rd house : Ends', description: 'Authority-eclipse fades.' },
  { name: 'Ketu aspect Moon in 2nd house', description: 'Voice/income detachment. Purifying.' },
  { name: 'Ketu aspect Moon in 2nd house : Starts', description: 'Voice-detachment begins.' },
  { name: 'Ketu aspect Moon in 2nd house : Exact', description: 'Sit with dissonance.' },
  { name: 'Ketu aspect Moon in 2nd house : Ends', description: 'Voice-detachment fades.' },
  { name: 'Ketu aspect Mercury in 3rd house', description: 'Solo precision; collaborative misfires.' },
  { name: 'Ketu aspect Mercury in 3rd house : Starts', description: 'Detached-mind window opens.' },
  { name: 'Ketu aspect Mercury in 3rd house : Exact', description: 'Solo breakthrough.' },
  { name: 'Ketu aspect Mercury in 3rd house : Ends', description: 'Detached-mind closes.' },
  { name: 'Ketu aspect Venus in 4th house', description: 'Home-detachment; downsizing favored.' },
  { name: 'Ketu aspect Venus in 4th house : Starts', description: 'Home-detachment begins.' },
  { name: 'Ketu aspect Venus in 4th house : Exact', description: 'Peak home-Ketu day.' },
  { name: 'Ketu aspect Venus in 4th house : Ends', description: 'Home-detachment fades.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Partnership eclipse.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Partnership-eclipse begins.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Honor what closes.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Partnership-eclipse closes.' },
  { name: 'Ketu aspect Jupiter in 6th house', description: 'Service-detachment; chronic enemies disengage.' },
  { name: 'Ketu aspect Jupiter in 6th house : Starts', description: 'Service-detachment begins.' },
  { name: 'Ketu aspect Jupiter in 6th house : Exact', description: 'Peak service-Ketu day.' },
  { name: 'Ketu aspect Jupiter in 6th house : Ends', description: 'Service-detachment closes.' },
  { name: 'Ketu aspect Saturn in 8th house', description: 'Transformation-detachment; don\'t resist.' },
  { name: 'Ketu aspect Saturn in 8th house : Starts', description: 'Transformation-detachment begins.' },
  { name: 'Ketu aspect Saturn in 8th house : Exact', description: 'Buried truth surfaces.' },
  { name: 'Ketu aspect Saturn in 8th house : Ends', description: 'Transformation-detachment closes.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Axis activation in dharma.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Nodal-axis window begins.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Peak axis day.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Nodal-axis closes.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Once-in-18-years cluster reset.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Ketu-return opens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Mark threshold.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu-return closes.' },

  // — Mars aspects natal —
  { name: 'Mars aspect Sun in 3rd house', description: 'Fierce ship-write-defend day.' },
  { name: 'Mars aspect Sun in 3rd house : Starts', description: 'Mars-Sun cluster window opens.' },
  { name: 'Mars aspect Sun in 3rd house : Exact', description: 'Ship hard; watch temper.' },
  { name: 'Mars aspect Sun in 3rd house : Ends', description: 'Mars-Sun cluster closes.' },
  { name: 'Mars aspect Moon in 2nd house', description: 'Heated speech; throat care.' },
  { name: 'Mars aspect Moon in 2nd house : Starts', description: 'Voice-heat rising.' },
  { name: 'Mars aspect Moon in 2nd house : Exact', description: 'Calm fire on family-money.' },
  { name: 'Mars aspect Moon in 2nd house : Ends', description: 'Voice-heat fades.' },
  { name: 'Mars aspect Mercury in 3rd house', description: 'Sharp execution mind.' },
  { name: 'Mars aspect Mercury in 3rd house : Starts', description: 'Sharp-mind window opens.' },
  { name: 'Mars aspect Mercury in 3rd house : Exact', description: 'Send precise cutting note.' },
  { name: 'Mars aspect Mercury in 3rd house : Ends', description: 'Sharp-mind closes.' },
  { name: 'Mars aspect Venus in 4th house', description: 'Heated home dynamics.' },
  { name: 'Mars aspect Venus in 4th house : Starts', description: 'Home-heat opens.' },
  { name: 'Mars aspect Venus in 4th house : Exact', description: 'Decisive home action.' },
  { name: 'Mars aspect Venus in 4th house : Ends', description: 'Home-heat closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Peak partnership-action.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Mars-return opens.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Sign deals.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Mars-return closes.' },
  { name: 'Mars aspect Jupiter in 6th house', description: 'Fierce service-combat.' },
  { name: 'Mars aspect Jupiter in 6th house : Starts', description: 'Service-combat opens.' },
  { name: 'Mars aspect Jupiter in 6th house : Exact', description: 'Win the rivalry.' },
  { name: 'Mars aspect Jupiter in 6th house : Ends', description: 'Service-combat closes.' },
  { name: 'Mars aspect Saturn in 8th house', description: 'Surgical action in transformation.' },
  { name: 'Mars aspect Saturn in 8th house : Starts', description: 'Transformation-action opens.' },
  { name: 'Mars aspect Saturn in 8th house : Exact', description: 'Lead through chaos.' },
  { name: 'Mars aspect Saturn in 8th house : Ends', description: 'Transformation-action closes.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Assertive foreign moves.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Foreign-combat opens.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Push principled position.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Foreign-combat closes.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Sharp solo execution.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Solo-action opens.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Solo breakthrough.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Solo-action closes.' },

  // — Mercury aspects natal —
  { name: 'Mercury aspect Sun in 3rd house', description: 'Return-style activation. Best for: presentation; technical-leadership pitch.' },
  { name: 'Mercury aspect Sun in 3rd house : Starts', description: 'Editorial-authority opens.' },
  { name: 'Mercury aspect Sun in 3rd house : Exact', description: 'Ship the document.' },
  { name: 'Mercury aspect Sun in 3rd house : Ends', description: 'Editorial-authority closes.' },
  { name: 'Mercury aspect Moon in 2nd house', description: 'Articulate emotional speech.' },
  { name: 'Mercury aspect Moon in 2nd house : Starts', description: 'Voice-articulation opens.' },
  { name: 'Mercury aspect Moon in 2nd house : Exact', description: 'Speak from the heart with precision.' },
  { name: 'Mercury aspect Moon in 2nd house : Ends', description: 'Voice-articulation closes.' },
  { name: 'Mercury aspect Mercury in 3rd house', description: 'Annual peak technical day.' },
  { name: 'Mercury aspect Mercury in 3rd house : Starts', description: 'Mercury return opens.' },
  { name: 'Mercury aspect Mercury in 3rd house : Exact', description: 'Peak technical-mind day.' },
  { name: 'Mercury aspect Mercury in 3rd house : Ends', description: 'Mercury return closes.' },
  { name: 'Mercury aspect Venus in 4th house', description: 'Diplomatic family/home comm.' },
  { name: 'Mercury aspect Venus in 4th house : Starts', description: 'Home-comm opens.' },
  { name: 'Mercury aspect Venus in 4th house : Exact', description: 'Send the diplomatic note.' },
  { name: 'Mercury aspect Venus in 4th house : Ends', description: 'Home-comm closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Precise contractual comm.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Contract-comm opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Send term sheet.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Contract-comm closes.' },
  { name: 'Mercury aspect Jupiter in 6th house', description: 'Service-and-wisdom comm.' },
  { name: 'Mercury aspect Jupiter in 6th house : Starts', description: 'Service-comm opens.' },
  { name: 'Mercury aspect Jupiter in 6th house : Exact', description: 'Resolve chronic dispute.' },
  { name: 'Mercury aspect Jupiter in 6th house : Ends', description: 'Service-comm closes.' },
  { name: 'Mercury aspect Saturn in 8th house', description: 'Investigative depth-writing.' },
  { name: 'Mercury aspect Saturn in 8th house : Starts', description: 'Depth-writing opens.' },
  { name: 'Mercury aspect Saturn in 8th house : Exact', description: 'Forensic insight lands.' },
  { name: 'Mercury aspect Saturn in 8th house : Ends', description: 'Depth-writing closes.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Debilitated; foreign-vision study favored.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Foreign-vision opens.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Peak Mercury-Rahu day.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Foreign-vision closes.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Paradoxical detached precision.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Detached-precision opens.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Solo clarity.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Detached-precision closes.' },

  // — Moon aspects natal —
  { name: 'Moon aspect Sun in 3rd house', description: 'Feelings drive day. Warm-toned communication lands.' },
  { name: 'Moon aspect Sun in 3rd house : Starts', description: 'Feelings-on-authority opens.' },
  { name: 'Moon aspect Sun in 3rd house : Exact', description: 'Send emotionally honest memo.' },
  { name: 'Moon aspect Sun in 3rd house : Ends', description: 'Feelings-on-authority closes.' },
  { name: 'Moon aspect Moon in 2nd house', description: 'Annual emotional voice peak.' },
  { name: 'Moon aspect Moon in 2nd house : Starts', description: 'Voice emotional opens.' },
  { name: 'Moon aspect Moon in 2nd house : Exact', description: 'Speak warmly.' },
  { name: 'Moon aspect Moon in 2nd house : Ends', description: 'Voice emotional closes.' },
  { name: 'Moon aspect Mercury in 3rd house', description: 'Warm-toned writing.' },
  { name: 'Moon aspect Mercury in 3rd house : Starts', description: 'Warm-tone opens.' },
  { name: 'Moon aspect Mercury in 3rd house : Exact', description: 'Tone over content.' },
  { name: 'Moon aspect Mercury in 3rd house : Ends', description: 'Warm-tone closes.' },
  { name: 'Moon aspect Venus in 4th house', description: 'Peak home day. Cook; nest; mother.' },
  { name: 'Moon aspect Venus in 4th house : Starts', description: 'Home-emotional opens.' },
  { name: 'Moon aspect Venus in 4th house : Exact', description: 'Host gathering.' },
  { name: 'Moon aspect Venus in 4th house : Ends', description: 'Home-emotional closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge in partnership.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Partnership-emotion opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Soften contract conversation.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Partnership-emotion closes.' },
  { name: 'Moon aspect Jupiter in 6th house', description: 'Service-empathy day.' },
  { name: 'Moon aspect Jupiter in 6th house : Starts', description: 'Service-empathy opens.' },
  { name: 'Moon aspect Jupiter in 6th house : Exact', description: 'Resolve conflict warmly.' },
  { name: 'Moon aspect Jupiter in 6th house : Ends', description: 'Service-empathy closes.' },
  { name: 'Moon aspect Saturn in 8th house', description: 'Emotional weight; defer big decisions.' },
  { name: 'Moon aspect Saturn in 8th house : Starts', description: 'Transformation-emotion opens.' },
  { name: 'Moon aspect Saturn in 8th house : Exact', description: 'Sleep more.' },
  { name: 'Moon aspect Saturn in 8th house : Ends', description: 'Transformation-emotion closes.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional pull foreign/dharma.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Foreign-vision-emotion opens.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Capture dream; commit later.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Foreign-vision-emotion closes.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Solo-emotion. Solo writing flourishes.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Solo-emotion opens.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Solo deep-work.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Solo-emotion closes.' },

  // — Saturn aspects natal —
  { name: 'Saturn aspect Sun in 3rd house', description: 'Structural test of authority. Slow recognition.' },
  { name: 'Saturn aspect Sun in 3rd house : Starts', description: 'Authority-discipline opens.' },
  { name: 'Saturn aspect Sun in 3rd house : Exact', description: 'Ship disciplined output.' },
  { name: 'Saturn aspect Sun in 3rd house : Ends', description: 'Authority-discipline closes.' },
  { name: 'Saturn aspect Moon in 2nd house', description: 'Voice/income discipline.' },
  { name: 'Saturn aspect Moon in 2nd house : Starts', description: 'Voice-discipline opens.' },
  { name: 'Saturn aspect Moon in 2nd house : Exact', description: 'Patience compounds.' },
  { name: 'Saturn aspect Moon in 2nd house : Ends', description: 'Voice-discipline closes.' },
  { name: 'Saturn aspect Mercury in 3rd house', description: 'Long-form chapter.' },
  { name: 'Saturn aspect Mercury in 3rd house : Starts', description: 'Structural-comm opens.' },
  { name: 'Saturn aspect Mercury in 3rd house : Exact', description: 'Ship long-form work.' },
  { name: 'Saturn aspect Mercury in 3rd house : Ends', description: 'Structural-comm closes.' },
  { name: 'Saturn aspect Venus in 4th house', description: 'Home test. Buy carefully.' },
  { name: 'Saturn aspect Venus in 4th house : Starts', description: 'Home-discipline opens.' },
  { name: 'Saturn aspect Venus in 4th house : Exact', description: 'Home reckoning.' },
  { name: 'Saturn aspect Venus in 4th house : Ends', description: 'Home-discipline closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Heavy partnership chapter.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Partnership-discipline opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Reckoning of which deals are real.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Partnership-discipline closes.' },
  { name: 'Saturn aspect Jupiter in 6th house', description: 'Favorable. Long battles won through patience.' },
  { name: 'Saturn aspect Jupiter in 6th house : Starts', description: 'Service-discipline opens.' },
  { name: 'Saturn aspect Jupiter in 6th house : Exact', description: 'Peak Saturn-Jupiter day.' },
  { name: 'Saturn aspect Jupiter in 6th house : Ends', description: 'Service-discipline closes.' },
  { name: 'Saturn aspect Saturn in 8th house', description: 'Once-in-29-years deep transformation.' },
  { name: 'Saturn aspect Saturn in 8th house : Starts', description: 'Saturn return opens.' },
  { name: 'Saturn aspect Saturn in 8th house : Exact', description: 'Half-life reckoning.' },
  { name: 'Saturn aspect Saturn in 8th house : Ends', description: 'Saturn return closes.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Pressure on dharma node.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Foreign-discipline opens.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Dharma path reckoning.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Foreign-discipline closes.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Solo deep work compounds.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Solo-discipline opens.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Solo opus apex.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Solo-discipline closes.' },

  // — Sun aspects natal —
  { name: 'Sun aspect Sun in 3rd house', description: 'Annual peak. Pitch the document.' },
  { name: 'Sun aspect Sun in 3rd house : Starts', description: 'Solar return opens.' },
  { name: 'Sun aspect Sun in 3rd house : Exact', description: 'Ship; claim authorship.' },
  { name: 'Sun aspect Sun in 3rd house : Ends', description: 'Solar return closes.' },
  { name: 'Sun aspect Moon in 2nd house', description: 'Authoritative voice/family-finance window.' },
  { name: 'Sun aspect Moon in 2nd house : Starts', description: 'Voice-authority opens.' },
  { name: 'Sun aspect Moon in 2nd house : Exact', description: 'Speak with full authority.' },
  { name: 'Sun aspect Moon in 2nd house : Ends', description: 'Voice-authority closes.' },
  { name: 'Sun aspect Mercury in 3rd house', description: 'Annual visibility on technical mind.' },
  { name: 'Sun aspect Mercury in 3rd house : Starts', description: 'Technical-authority opens.' },
  { name: 'Sun aspect Mercury in 3rd house : Exact', description: 'Take authorship.' },
  { name: 'Sun aspect Mercury in 3rd house : Ends', description: 'Technical-authority closes.' },
  { name: 'Sun aspect Venus in 4th house', description: 'Annual visibility through home channels.' },
  { name: 'Sun aspect Venus in 4th house : Starts', description: 'Home-authority opens.' },
  { name: 'Sun aspect Venus in 4th house : Exact', description: 'Step into family-business leadership.' },
  { name: 'Sun aspect Venus in 4th house : Ends', description: 'Home-authority closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Annual peak partnership-authority.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Partnership-authority opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Sign anchor contract.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Partnership-authority closes.' },
  { name: 'Sun aspect Jupiter in 6th house', description: 'Service-authority peak.' },
  { name: 'Sun aspect Jupiter in 6th house : Starts', description: 'Service-authority opens.' },
  { name: 'Sun aspect Jupiter in 6th house : Exact', description: 'Take expert lead.' },
  { name: 'Sun aspect Jupiter in 6th house : Ends', description: 'Service-authority closes.' },
  { name: 'Sun aspect Saturn in 8th house', description: 'Authoritative leadership through transformation.' },
  { name: 'Sun aspect Saturn in 8th house : Starts', description: 'Transformation-leadership opens.' },
  { name: 'Sun aspect Saturn in 8th house : Exact', description: 'Lead through chaos.' },
  { name: 'Sun aspect Saturn in 8th house : Ends', description: 'Transformation-leadership closes.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Visibility through foreign/dharma channels.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Foreign-authority opens.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Take international stage.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Foreign-authority closes.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Paradoxical authority-on-detachment.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Solo-authority opens.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Solo authority lands.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Solo-authority closes.' },

  // — Venus aspects natal —
  { name: 'Venus aspect Sun in 3rd house', description: 'Graceful authoritative comm. Charm with substance.' },
  { name: 'Venus aspect Sun in 3rd house : Starts', description: 'Graceful-authority opens.' },
  { name: 'Venus aspect Sun in 3rd house : Exact', description: 'Peak Venus-Sun day.' },
  { name: 'Venus aspect Sun in 3rd house : Ends', description: 'Graceful-authority closes.' },
  { name: 'Venus aspect Moon in 2nd house', description: 'Luxurious income/voice window.' },
  { name: 'Venus aspect Moon in 2nd house : Starts', description: 'Income-luxury opens.' },
  { name: 'Venus aspect Moon in 2nd house : Exact', description: 'Negotiate generously.' },
  { name: 'Venus aspect Moon in 2nd house : Ends', description: 'Income-luxury closes.' },
  { name: 'Venus aspect Mercury in 3rd house', description: 'Graceful technical comm.' },
  { name: 'Venus aspect Mercury in 3rd house : Starts', description: 'Graceful-mind opens.' },
  { name: 'Venus aspect Mercury in 3rd house : Exact', description: 'Beautiful precision lands.' },
  { name: 'Venus aspect Mercury in 3rd house : Ends', description: 'Graceful-mind closes.' },
  { name: 'Venus aspect Venus in 4th house', description: 'Annual home-foundation peak.' },
  { name: 'Venus aspect Venus in 4th house : Starts', description: 'Venus return opens.' },
  { name: 'Venus aspect Venus in 4th house : Exact', description: 'Peak Venus return day.' },
  { name: 'Venus aspect Venus in 4th house : Ends', description: 'Venus return closes.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Partnership warmth + rigor.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Partnership-warmth opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Sign with both warmth and rigor.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Partnership-warmth closes.' },
  { name: 'Venus aspect Jupiter in 6th house', description: 'Diplomatic service excellence.' },
  { name: 'Venus aspect Jupiter in 6th house : Starts', description: 'Service-diplomacy opens.' },
  { name: 'Venus aspect Jupiter in 6th house : Exact', description: 'Resolve with grace.' },
  { name: 'Venus aspect Jupiter in 6th house : Ends', description: 'Service-diplomacy closes.' },
  { name: 'Venus aspect Saturn in 8th house', description: 'Diplomatic transformation.' },
  { name: 'Venus aspect Saturn in 8th house : Starts', description: 'Transformation-diplomacy opens.' },
  { name: 'Venus aspect Saturn in 8th house : Exact', description: 'Negotiate with diplomacy.' },
  { name: 'Venus aspect Saturn in 8th house : Ends', description: 'Transformation-diplomacy closes.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Graceful foreign engagement.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Foreign-diplomacy opens.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Sign cross-border deal.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Foreign-diplomacy closes.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Graceful detachment in cluster.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Solo-aesthetic opens.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Peak Venus-Ketu day.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Solo-aesthetic closes.' },

  // — Rahu aspects natal —
  { name: 'Rahu aspect Sun in 3rd house', description: 'Chaotic authority. Watch over-claiming.' },
  { name: 'Rahu aspect Sun in 3rd house : Starts', description: 'Chaotic-authority opens.' },
  { name: 'Rahu aspect Sun in 3rd house : Exact', description: 'Move with discipline.' },
  { name: 'Rahu aspect Sun in 3rd house : Ends', description: 'Chaotic-authority closes.' },
  { name: 'Rahu aspect Moon in 2nd house', description: 'Chaotic income/voice.' },
  { name: 'Rahu aspect Moon in 2nd house : Starts', description: 'Chaotic-income opens.' },
  { name: 'Rahu aspect Moon in 2nd house : Exact', description: 'Don\'t leverage on sudden wealth.' },
  { name: 'Rahu aspect Moon in 2nd house : Ends', description: 'Chaotic-income closes.' },
  { name: 'Rahu aspect Mercury in 3rd house', description: 'Explosive breakthrough.' },
  { name: 'Rahu aspect Mercury in 3rd house : Starts', description: 'Breakthrough-mind opens.' },
  { name: 'Rahu aspect Mercury in 3rd house : Exact', description: 'Ship boundary-breaking work.' },
  { name: 'Rahu aspect Mercury in 3rd house : Ends', description: 'Breakthrough-mind closes.' },
  { name: 'Rahu aspect Venus in 4th house', description: 'Chaotic home dynamics.' },
  { name: 'Rahu aspect Venus in 4th house : Starts', description: 'Home-chaos opens.' },
  { name: 'Rahu aspect Venus in 4th house : Exact', description: 'Move with discipline.' },
  { name: 'Rahu aspect Venus in 4th house : Ends', description: 'Home-chaos closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic partnerships.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Chaotic-partnership opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Verify before signing.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Chaotic-partnership closes.' },
  { name: 'Rahu aspect Jupiter in 6th house', description: 'Favorable. Defeat enemies.' },
  { name: 'Rahu aspect Jupiter in 6th house : Starts', description: 'Unconventional-service opens.' },
  { name: 'Rahu aspect Jupiter in 6th house : Exact', description: 'Win unconventional victory.' },
  { name: 'Rahu aspect Jupiter in 6th house : Ends', description: 'Unconventional-service closes.' },
  { name: 'Rahu aspect Saturn in 8th house', description: 'Sudden transformation events.' },
  { name: 'Rahu aspect Saturn in 8th house : Starts', description: 'Sudden-transformation opens.' },
  { name: 'Rahu aspect Saturn in 8th house : Exact', description: 'Vipareet wisdom.' },
  { name: 'Rahu aspect Saturn in 8th house : Ends', description: 'Sudden-transformation closes.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Once-in-18-years foreign-dharma peak.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return opens.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Mark threshold.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return closes.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Axis activation.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Nodal-axis opens.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Peak axis day. Clearer dharma direction.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal-axis closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
