// db/seed_relationship_sagittarius.js
//
// Per-ascendant fill-in seed for the **relationship** category, scoped to a
// representative Sagittarius ascendant native with:
//   Ascendant: Sagittarius
//   Natal placements (sidereal Lahiri):
//     Sun=9th (Leo, own)  Moon=8th (Cancer, own)
//     Mercury=10th (Virgo, own+exalted — Bhadra + yogakaraka)
//     Venus=11th (Libra, own)  Mars=5th (Aries, own)
//     Jupiter=1st (Sagittarius, own — Hamsa Mahapurusha Yoga)
//     Saturn=2nd (Capricorn, own)
//     Rahu=6th (Taurus)  Ketu=12th (Scorpio)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose relationship-specific interpretations, then run:
//
//   node db/seed_relationship_sagittarius.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./relationship');

const ASCENDANT = 'Sagittarius';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter ruler of the 1st House in the 1st House', description: 'You walk into rooms as the wise one — the principled, expansive, slightly larger-than-life self. In love, that is both gift and friction: partners are drawn to the gravity, then sometimes feel they must enroll in your school. You need a counterpart who is your peer in conviction, who can challenge a principle without flinching. Relationships fail when you turn intimacy into doctrine; they thrive when you let your partner correct you out of their own equal authority.' },
  { name: 'Saturn ruler of the 2nd House in the 2nd House', description: 'Speech of love runs slow, structural, and final. You don\'t flirt easily; you don\'t say "I love you" until you mean it for decades. Family-finance with the partner is approached with care: the joint account, the inheritance question, the long savings ritual. The voice that says affection prefers commitment-language to performance-language. The shadow: under-spoken affection that the partner reads as coldness — your slow words are deeper, but make sure they actually arrive.' },
  { name: 'Saturn ruler of the 3rd House in the 2nd House', description: 'Communication with siblings, peers, and close friends is methodical, structural, and a touch formal. You write rather than call; you prepare rather than improvise. Younger siblings or cohort-mates often look to you as the steady one. The shadow: peer-friendship that feels more like a project than a play — schedule unstructured time with the close ones; warmth needs space to wander.' },
  { name: 'Jupiter ruler of the 4th House in the 1st House', description: 'Home is co-extensive with your person — you carry your foundation in your body. Mother is not a distant figure but a wisdom-anchor who shaped your sense of self. The dwelling reads as an extension of who you are. Relationships compound when partners can integrate into the home you already are; they fail when partners ask you to dismantle the foundation to fit them in.' },
  { name: 'Mars ruler of the 5th House in the 5th House', description: 'Romance runs sharp, decisive, body-anchored, and pulled toward action rather than rumination. You like the partner who can keep up with the speed; you choose people who do not need lengthy reassurance to make moves. Children, mentees, and creative work are the visible love-objects. The shadow: speed in commitment that outruns due diligence — slow down enough to verify character, even when the chemistry says go.' },
  { name: 'Venus ruler of the 6th House in the 11th House', description: 'In intimate-circle conflicts you negotiate gracefully through the friend-network. Old workplace tensions resolve through the senior-female ally; the difficult sibling-conversation gets routed through a mutual friend. Friend-circle and conflict-zone overlap in your life — the people you fight with often become the people you befriend. The shadow: keeping problematic friends because the gain channel is real; clean the boundary even at gain-cost.' },
  { name: 'Mercury ruler of the 7th House in the 10th House', description: 'Marriage and primary partnership lean public, professional, peer-aged or peer-status. The spouse is met through career or formal channels and the relationship is part of your public face from the start. Industries: a partner who is a peer-professional; a deal-attorney; a co-founder. The relationship is also the brand. The shadow: confusing the joint career with the joint heart — the resume-quality of the union doesn\'t guarantee the home-quality; verify both.' },
  { name: 'Moon ruler of the 8th House in the 8th House', description: 'Sexuality, deep intimacy, and shared resources have an emotional fluency in the depths that few partners can match. You are not afraid of hard conversations about money, mortality, in-laws, inheritance. You bring genuine emotional depth to the parts of the relationship that most couples avoid. The shadow: drawing partners into emotional storms because the depth-charge is what feels real — learn to inhabit calm intimacy too, not only the dark-water dives.' },
  { name: 'Sun ruler of the 9th House in the 9th House', description: 'Romance is filtered through values, ethics, philosophy, foreign-fortune, and shared worldview — and the supreme dharma engine of the chart makes this lens stronger than usual. You commit to people whose principles you respect, lose interest fast in those whose ethics blur, and find foreign or cross-cultural partnerships natural. Teacher-student dynamics, age-gap relationships, pilgrimage-style courtships are all native. The shadow: principled rigidity that turns love into a doctrinal exam.' },
  { name: 'Mercury ruler of the 10th House in the 10th House', description: 'Public-facing relationship-as-brand is at peak articulation. The world reads you and your partner as a precision unit; reputation is shared and carefully composed. Joint announcements, joint career-moves, joint public-statements all carry weight. The shadow: marrying the joint press release rather than the partner — verify the relationship works at home, not only on the public stage.' },
  { name: 'Venus ruler of the 11th House in the 11th House', description: 'Friendships, social networks, and elder-friend circles are sovereign — and feminine, aesthetic, diplomatic in tone. Senior female mentors function as second-mothers across decades. Romantic introductions arrive through the female-led friend network. Group friendships rather than tight pairs are the primary social structure. The shadow: a friend-circle so warm and large that it dilutes the primary partnership — protect couple-time from network gravity.' },
  { name: 'Mars ruler of the 12th House in the 5th House', description: 'Bedroom-pleasures, hidden romance, and behind-the-scenes intimacy carry sharp, decisive, body-anchored charge that gets expressed through creative-public output. The book inspired by the love affair, the project incubated during the foreign trip with the partner, the speculative bet placed in retreat — these are how the 12H sweet-pleasure becomes the 5H visible win. The shadow: pleasure-spending on travel that drains the speculative budget; honor the foreign romance, but discipline the cost.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 9th (Dispositor)', description: 'When this engine fires, principled love and foreign-fortune bonds light up. Marriage proposals from abroad, ceremonial commitments, teacher-student bonds, ethics-driven courtships. Major life-decisions made together feel blessed; the dharma of the union becomes visible and the relationship gains structural meaning.' },
  { name: 'Moon in 8th (Dispositor)', description: 'When this engine fires, intimacy goes to the depths — sexuality, shared resources, in-law dynamics, mortality conversations. Old emotional knots in the relationship surface and resolve. The chaos is the offer; emotional fluency in the dark water is what the relationship needs right now.' },
  { name: 'Mercury in 10th (Dispositor)', description: 'When this engine fires, the public-couple image articulates clearly. Joint announcements, joint career-moves, the precision-document that defines the partnership in writing. The relationship becomes part of the brand — for better or sharper.' },
  { name: 'Venus in 11th (Dispositor)', description: 'When this engine fires, the female-led friend network introduces or restructures the romance. Senior-female mentors weigh in; old friend-circles open or close around the partnership; aesthetic group rituals (gatherings, weddings, parties) anchor the relationship.' },
  { name: 'Mars in 5th (Dispositor)', description: 'When this engine fires, romance moves fast and bold. Decisive moves, founder-style commitment-asks, children-and-mentee news, creative-collaboration with the partner. Verify the speed is shared, not imposed.' },
  { name: 'Jupiter in 1st (Dispositor)', description: 'When this engine fires, the wise-self anchors the partnership. Teacher-energy is offered openly; principled long-arc decisions land; the body itself signals readiness for commitment. The relationship deepens through declared values rather than performed romance.' },
  { name: 'Saturn in 2nd (Dispositor)', description: 'When this engine fires, family-finance and slow-income matters arrive in the relationship. The joint savings ritual, the inheritance conversation, the long financial commitment. Slow but real; the structure that survives.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual visibility window for the wise-self in love. Your warmth and conviction are more openly extended; partners receive you without you having to over-explain. Best four-week stretch for a principled relationship-step — a values-aligned proposal, a public-mantle moment as a couple.' },
  { name: 'Sun Transits the 2nd House', description: 'Conversations about slow-money, voice, and family-finance light up the partnership. The joint account, the family-money question, the inheritance trail — all surface for structural discussion.' },
  { name: 'Sun Transits the 3rd House', description: 'Sibling and peer-circle dynamics light up. Best for the long-deferred sibling conversation, the peer-friendship reset, the methodical-but-courageous letter.' },
  { name: 'Sun Transits the 4th House', description: 'Home-base spotlight. Mother-related developments; family approval; the dwelling itself becomes the conversation. Real-estate-and-relationship decisions intertwine.' },
  { name: 'Sun Transits the 5th House', description: 'Annual peak romance-visibility window — Sun joining your natal Mars in the 5H. Best for the bold declaration, the public outing, the proposal, the children-related announcement, the mentee-news. Verify the spectacle is anchored in substance.' },
  { name: 'Sun Transits the 6th House', description: 'Workplace and service-context relationship dynamics surface — Sun on natal Rahu. The work-spouse situation, the colleague-flirt, the work-friend conflict find clarity. Health-of-the-relationship audits favored.' },
  { name: 'Sun Transits the 7th House', description: 'Annual peak partnership-visibility window. Marriage, contracts, public-facing alliance moves. The 7L Mercury at MC means the public-couple thread is at peak charge. Watch ego friction with the spouse — solar light exposes as much as it illuminates.' },
  { name: 'Sun Transits the 8th House', description: 'Visibility on shared resources, sexuality, in-laws, and transformations — Sun on natal Moon. Inheritance, joint-taxation, deep intimacy conversations. Emotional fluency in the depths is what the relationship needs.' },
  { name: 'Sun Transits the 9th House', description: 'Annual peak dharma-window — Sun returning to its own sign in own house. Best window of the year for a wedding ceremony, a vow renewal, an ethics-driven commitment, a foreign-relationship clarification.' },
  { name: 'Sun Transits the 10th House', description: 'Visibility on the public face of the relationship — Sun on natal Mercury at MC. The world sees you as a unit; reputation moves accordingly. Best for the public announcement, the joint career-step, the formal status update.' },
  { name: 'Sun Transits the 11th House', description: 'Visibility on shared friendships, networks, gains — Sun on natal Venus. The female-led friend-circle as a couple; the joint birthday; the network introductions. Senior-female mentors weigh in.' },
  { name: 'Sun Transits the 12th House', description: 'Visibility dims; intimacy deepens behind closed doors — Sun on natal Ketu. Best for retreats, foreign trips together, devotional joint practice, private rituals.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional charge on the wise-self. Affection runs warmer; reach out to the partner with extra warmth. Watch over-philosophical declarations.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotion around slow-money, voice, family-finance. Speak about resources when warm; defer when overcooked. The structural conversation lands softer today.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge with siblings and close peers. Send the warm message; make the gentle call.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly emotional-home peak. The kitchen-table conversation lands; mother-call favored; partner appreciates being invited into your inner sanctum.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on romance — Moon on natal Mars. Heart-led creative-romantic gestures; children-related warmth. Avoid impulsive moves; the volume amplifies emotion to dangerous levels.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge in the service-and-conflict zone — Moon on natal Rahu. Empathetic intimate-circle conflict-resolution; soft repair work with siblings or extended family.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnerships. Read the partner mood before pushing; warmth wins what aggression loses. Best for warming a cold patch.' },
  { name: 'Moon Transits the 8th House', description: 'Moon return in own sign in own house — peak emotional-intimacy window. Sexuality, depth-conversations, in-law warmth, shared-resource emotional honesty.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma — Moon on natal Sun. Big-vision conversations with the partner about values, future, foreign moves; ceremonial-emotional warmth.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on public reputation — Moon on natal Mercury at MC. The room reads you as a couple; opening line, posture, dress matter today.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth in the gain-and-network zone — Moon on natal Venus. Reach out to the senior-female mentor; warm group-friend gathering favored.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional charge on foreign, devotional, hidden zones — Moon on natal Ketu. Sleep more, write privately, deepen behind closed doors.' },
  { name: 'Mercury Transits the 1st House', description: 'Mind-on-self window — Mercury on natal Jupiter. Best for principle-anchored relationship-conversations, refreshing the values-statement of the union.' },
  { name: 'Mercury Transits the 2nd House', description: 'Mercury on natal Saturn — disciplined, well-structured income-and-resource communication. Joint budgeting, savings rituals, family-money paperwork.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak sibling and peer-circle communication window. Send the long-deferred letter; make the methodical call.' },
  { name: 'Mercury Transits the 4th House', description: 'Emotionally attuned home and family-paperwork. Lease drafts, mother-correspondence, family-business communication.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury on natal Mars — bold creative-romantic communication. The punchy love letter, the children-related update, the mentee-coaching note.' },
  { name: 'Mercury Transits the 6th House', description: 'Mercury on natal Rahu — peak surgical-mind window for intimate-circle conflict-resolution. Sibling-rebuilding letters, family-system documents, fair adjudication of old wounds.' },
  { name: 'Mercury Transits the 7th House', description: 'Mercury return to its own sign — peak partnership-communication. Term-sheets, joint contracts, the precise mediation-letter to the spouse.' },
  { name: 'Mercury Transits the 8th House', description: 'Mercury on natal Moon — depth-writing in the intimacy zone. Forensic conversations about shared resources, due-diligence on in-laws, taxation drafts together.' },
  { name: 'Mercury Transits the 9th House', description: 'Mercury on natal Sun — visionary writing about love, values, foreign-future. Wedding-vows, ethics-statements, foreign-relationship clarifications.' },
  { name: 'Mercury Transits the 10th House', description: 'Mercury return to own + exalted at MC — peak public-couple communication. Joint announcements, formal partnership status updates.' },
  { name: 'Mercury Transits the 11th House', description: 'Mercury on natal Venus — graceful network-communication. Reach out to the female-led friend circle; structured warmth in group-friend correspondence.' },
  { name: 'Mercury Transits the 12th House', description: 'Mercury on natal Ketu — confidential, devotional, foreign correspondence. Private love-letters, retreat-correspondence, off-record foreign-channel notes.' },
  { name: 'Venus Transits the 1st House', description: 'Warmth on the wise-self — Venus on natal Jupiter. Excellent for charm-driven intimacy moves; the smile lands; partners and friends remember you well.' },
  { name: 'Venus Transits the 2nd House', description: 'Soft income, voice, family-finance window — Venus on natal Saturn. Joint-account warmth, family-money diplomatic ease, gentle resource-conversations.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful sibling and peer-friend warmth. The reconciliation letter, the soft sibling visit, the friend-circle gathering.' },
  { name: 'Venus Transits the 4th House', description: 'Beautiful home, real-estate, mother window. Sign the lease, beautify the dwelling, host the gathering, call mother.' },
  { name: 'Venus Transits the 5th House', description: 'Venus on natal Mars — peak romance-aesthetic visibility. Best for the beautiful date, the creative-romantic gesture, the children-related celebration.' },
  { name: 'Venus Transits the 6th House', description: 'Venus on natal Rahu — diplomatic intimate-circle conflict-resolution. Difficult sibling becomes warm ally; the family-system tension softens.' },
  { name: 'Venus Transits the 7th House', description: 'Peak partnership window — Venus opposite lagna. Sign the JV, the marriage-step, the long-pending alliance. The deal closes warm.' },
  { name: 'Venus Transits the 8th House', description: 'Venus on natal Moon — diplomatic navigation of shared resources, sexuality, in-laws. Warm intimacy; gentle deep-conversations.' },
  { name: 'Venus Transits the 9th House', description: 'Venus on natal Sun — graceful foreign-engagement, ethical commitment-conversations, ceremonial warmth. Travel together feels lucky.' },
  { name: 'Venus Transits the 10th House', description: 'Venus on natal Mercury at MC — softens the public face of the relationship. Brand-couple polish, joint photographs, public diplomatic moves.' },
  { name: 'Venus Transits the 11th House', description: 'Venus return to own sign — peak gain-and-friend-network warmth. Senior-female mentors warm; group-friend gatherings; aesthetic-network advancement.' },
  { name: 'Venus Transits the 12th House', description: 'Venus on natal Ketu — annual peak foreign-romance, hidden-pleasure, devotional-intimacy window. Retreats, foreign trips, private rituals.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on natal Jupiter — body-anchored bold relationship action. Founder-style commitment-asks; principled assertion. Verify the speed is shared.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on natal Saturn — heated joint-finance disputes. Aggressive money-conversations possible but data-back them; impulse can backfire.' },
  { name: 'Mars Transits the 3rd House', description: 'Sharp sibling-and-peer push. Confrontations with siblings or close friends; defend the document; watch sharp messages.' },
  { name: 'Mars Transits the 4th House', description: 'Heated home-base disputes flare and resolve. Decisive real-estate or family-business action; watch family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Mars return on natal Mars — hot creative-romantic drive. Push through the stalled partnership project; take the calculated relationship-risk; assert with the children. Verify before leaping.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on natal Rahu — sharp intimate-circle conflict. Win the long sibling dispute; settle the family-system debt aggressively; resolve the work-friend conflict.' },
  { name: 'Mars Transits the 7th House', description: 'Friction in partnerships. Hard to negotiate cleanly with the spouse; defer the contract-style conversation seven to ten days.' },
  { name: 'Mars Transits the 8th House', description: 'Mars on natal Moon — surgical intimacy work. Restructure the shared finances; settle the in-law dispute; deep emotional-physical reset.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on natal Sun — bold dharma-action with the partner. Foreign-move push, principled commitment-fight, ethics-driven action together.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on natal Mercury at MC — among the strongest public-couple action windows. Launch the joint project; demand the joint title-bump; lead the joint pitch.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on natal Venus — assertive friend-network action. Push for the friend-circle reset; close the gain-conversation; warm-but-firm group-friend leadership.' },
  { name: 'Mars Transits the 12th House', description: 'Mars on natal Ketu — heated foreign, hidden, behind-scenes zone. Foreign-trade fight with partner; bedroom intensity; sleep loss possible.' },
  { name: 'Jupiter Transits the 1st House', description: 'Jupiter return to own sign in lagna — most blessed annual window of any twelve-year cycle for the wise-self in relationship. Take the role expansion; declare the bigger ambition together. Body radiates expansion; partners lean in.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Jupiter on natal Saturn — wisdom-blessing on slow joint-finance. Family-wealth structuring, joint inheritance decisions, vocal-warmth in financial conversations.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on sibling and peer-friend zone. Major sibling-relationship advancement; high-value peer-friendship deepening; reconciliation favored.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter return in own sign in 4H — peak home, family, real-estate expansion year. Buy the home together; deepen with mother; invest in the joint dwelling.' },
  { name: 'Jupiter Transits the 5th House', description: 'Jupiter on natal Mars — major romance-launch year. Children-related news, mentee placements, creative-collaboration with partner all favored. Take the visible commitment-step you have been declining.' },
  { name: 'Jupiter Transits the 6th House', description: 'Jupiter on natal Rahu — wisdom in the intimate-conflict zone. Difficult siblings or extended-family become teachers; old family-system tensions resolve through wisdom.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom into partnership zone. Anchor partnership step, marriage-of-business-and-personal, prestige spouse-commitment.' },
  { name: 'Jupiter Transits the 8th House', description: 'Jupiter on natal Moon — wisdom into shared resources, sexuality, in-laws. Joint inheritance favorably resolves; longevity work; deep intimacy growth.' },
  { name: 'Jupiter Transits the 9th House', description: 'Jupiter on natal Sun in own sign — among the most blessed relationship-windows of any twelve-year cycle. Wedding ceremony, vow renewal, ethics-driven major commitment, foreign-relationship advancement.' },
  { name: 'Jupiter Transits the 10th House', description: 'Jupiter on natal Mercury at MC — peak public-couple year. The joint brand-elevation, the prestige-couple offer, the board-level appearance together.' },
  { name: 'Jupiter Transits the 11th House', description: 'Jupiter on natal Venus — wisdom-blessing on the gain-and-friend zone. Group friendships compound; senior-female mentors deliver decisive advice; aesthetic-network expansion.' },
  { name: 'Jupiter Transits the 12th House', description: 'Jupiter on natal Ketu — peak foreign, devotional, retreat year. Foreign sabbatical with partner; pilgrimage; hidden-patron emergence in romance.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn over natal Jupiter in lagna — multi-year structural pressure on body, persona, and how you show up in love. Slow simplification; relationships test by attrition; what stays is permanent.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn return to own sign in 2H — multi-year discipline on slow joint-finance. Structural family-money decisions; long-term savings commitment with partner.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn in own sign Aquarius — multi-year discipline on sibling-and-peer relationships. The estranged sibling, the cohort-friend reset, the methodical reconciliation.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy emotional-home weight; mother-related responsibility intensifies; real-estate-and-relationship decisions feel structural.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn over natal Mars — creative-romantic authority is tested. Mentee or children-relationships restructure; speculation in love must be tightly disciplined.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn over natal Rahu — best multi-year window for resolving long-running family-system conflicts, settling old sibling-debts, leading intimate-circle structural transformation.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnership. The spouse or principal partner ages alongside you in the work. Slow commitment-arc; legal proceedings drag.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn over natal Moon — major intimacy-restructuring with deep emotional charge. Inheritance, in-law chapters open and close. Patience compounds.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn over natal Sun — multi-year discipline on shared values, foreign-fortune, ceremonial commitment. Father-figure or guru-figure relationship restructures.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn over natal Mercury at MC — the 2.5-year window where the public-couple identity solidifies into something permanent. Long structural commitments visible to the world.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn over natal Venus — disciplined structural friendship. The network purges what is no longer dharmic; group-friendship rituals formalize.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn over natal Ketu — multi-year discipline on foreign, hidden, devotional channels. Sabbaticals turn structural; pleasure-spending audits itself; private rituals deepen.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu over natal Jupiter — eighteen-month obsessive self-reinvention chapter. New persona, new ambition, new expression of love. Verify each leap.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu over natal Saturn — obsessive ambition around joint-finance. Watch get-rich-quick logic in the partnership.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive sibling-and-peer push. Viral peer dynamics; cohort-friendship maneuvering; verify before publishing relationship-news.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home, real-estate, mother chapter. Foreign relocation pull strong; mother-related obsession.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu over natal Mars — eighteen-month peak ambition window for romantic spectacle, children-frenzy, mentee-obsession. Verify integrity before each leap.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu return on its own placement — favorable for dramatic intimate-circle conflict-resolution, sibling-debt recovery, family-system restructuring.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive partnership chapter. Foreign-partner pull, unconventional commitment, controversial alliance. Verify carefully.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu over natal Moon — obsessive transformation chapter. Sudden inheritance, regulatory obsession around the union, occult-intimacy deep-dive.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu over natal Sun — foreign-fortune romance obsession. Ethics-driven obsession; controversial guru-bond; international-commitment fervor.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu over natal Mercury at MC — obsessive public-couple elevation. Sudden brand-couple offers; verify legitimacy.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu over natal Venus — obsessive friend-network and gain chapter. Group-friend dynamics intensify; reset moments; stay clean.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu over natal Ketu — obsessive foreign, devotional, hidden chapter. Foreign relocation, hidden-romance pursuits, retreat-driven relationship reset. Verify each path.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu over natal Jupiter — eighteen-month identity-stripping window. The wise-self in love feels empty; the teacher-persona drops out. Sit; do not over-rebuild.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu over natal Saturn — detachment from joint-finance. Income-conversations feel meaningless; family-money matters dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from sibling and peer-circle. Solo deep-work favored; cohort-coordination misfires.' },
  { name: 'Ketu Transits the 4th House', description: 'Home and mother detachment. Sell-property impulses, mother\'s independence, leave-the-city signals.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu over natal Mars — creative-romantic-authority eclipse. Old desire-objects feel hollow; mentee-pull fades; speculation in love loses charge.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu opposite Rahu — service-and-conflict detachment. Old sibling-conflicts dissolve without victory; family-system debts forgiven.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership detachment. Old commitments unwind; spouse needs space; counterparties withdraw.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu over natal Moon — transformation acceleration with emotional dissolution. Old intimacy-chapters end abruptly; in-law cases dissolve.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu over natal Sun — dharma detachment. Old shared-values feel finished; foreign-fortune ambitions cool; principle-without-attachment ripens together.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu over natal Mercury at MC — public-couple eclipse. The joint brand feels hollow; old roles dissolve quietly.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu over natal Venus — eighteen-month deep purification of friendship. Friends drift; group rituals feel weightless; ambitions purify.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu return on its own placement — foreign, devotional dissolution at peak. Pilgrimage-pull strong; pleasure-spending evaporates; old hidden-romance channels close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through the wise-self in love. Best for principled commitment-declarations, public couples-moments.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish the public-facing relationship materials.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the public step, declare the commitment.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Convert visibility into binding agreement.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Peak public-couple visibility window. Joint announcements, joint career-moves.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Public-couple window opens. Plan the upward joint move.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak public-couple day. Take the joint elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Public-couple window closes. Lock in joint commitments.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona; warm reception possible.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens. Prepare to be felt, not just seen.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Warmth lands.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes. Lock in warm connections.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-couple image; warm joint news possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional-couple window opens. Soften the joint tone.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional-couple day. Take the warm joint engagement.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional-couple window closes. Lock in warm public commitments.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-communication. Best for personal narrative-refresh in the relationship.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Mind-on-self window opens. Refresh the values-statement.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak self-communication day. Send the principled note.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mind-on-self window closes. Lock in personal commitments.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp public-couple communication. Joint announcements, status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Couple-communication window opens. Prepare the joint message.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak couple-communication day. Publish, present together.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Couple-communication window closes. Convert messaging to commitment.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Warmth on the persona. Charm-asks favored; the smile lands.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Charm-self window opens. Prepare the diplomatic outreach.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. Make the warm ask, take the social meeting.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm-self window closes. Convert warmth into binding agreements.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens the public-couple face. Brand-couple polish, joint photographs.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-couple window opens. Plan the brand refresh.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-couple day. Launch the joint visual update.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-couple window closes. Lock in design commitments.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold, body-anchored self-action; founder-style commitment moves.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens. Prepare the bold relationship move.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Take the founder commitment-action.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes. Lock in the action.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold, decisive public-couple action. Launch joint flagship moves.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Couple-action window opens. Prepare the bold joint play.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak couple-action day. Launch, demand, lead together.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Couple-action window closes. Convert moves into permanent positions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona in love. Take the role-elevation; declare the larger ambition together.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens. Plan the public-mantle assumption.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the elevation; declare the ambition.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes. Lock in the public commitment.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak public-couple expansion. Take the joint chief role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Public-couple expansion window opens. Brief the senior network.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak public-couple expansion day. Accept the joint elevation.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Public-couple expansion window closes. Convert offers into binding commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity in love. Slow down, simplify.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens. Eliminate vanity commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. The reckoning is acute. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public-couple work tested for staying power. Slow recognition.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Couple-discipline window opens. Structure the joint work for years.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak couple-discipline day. The slow joint-recognition lands.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Couple-discipline window closes. Convert effort into formal commitment.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion in love. Foreign or unconventional self emerges.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window opens. Sudden ambition surfaces.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak reinvention day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes. Decide which experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic public-couple visibility expansion. Sudden joint opportunities.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Couple-reinvention window begins. Vet unconventional joint offers.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak couple-reinvention day. Take the bold joint pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Couple-reinvention window closes. Lock in legitimate pivots.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. The old wise-teacher persona in love feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens. The pull to step away rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak stripping day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes. Move forward leaner.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Public-couple visibility eclipse. Joint roles stall.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Couple-eclipse window begins. Don\'t over-defend a joint role wanting to end.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak couple-eclipse day. The joint role dissolves quietly.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Couple-eclipse window closes. Move forward to the cleaner platform together.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting the slow joint-finance engine. Family-money structures collapse and rebuild. You hold authority where peers panic — your structural patience is the asset.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on joint-finance. Old family-money frameworks dismantle. Position for the long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day for joint resources. The old structure breaks; the new one is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The joint-finance transformation chapter completes. You emerge with rebuilt resource foundation that survives shocks.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption in the friend-network and gains channel. Unexpected friendship reshuffles; surprise mentor-relationship shifts; abrupt invitations.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden disruption window opens on friendships. Expect surprise invitations, abrupt mentor-relationship shifts.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day for friendships. The unexpected invitation lands; the mentor delivers an unannounced lift.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption window closes on friendships. Integrate the changes; release the experiments that didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 9th house', description: 'Birthday-window ego activation in the dharma engine. Best for ethics-aligned commitment moves, foreign-fortune relationship steps.' },
  { name: 'Sun aspect Sun in 9th house : Starts', description: 'Annual dharma-window opens. Plan the year\'s flagship principled commitment.' },
  { name: 'Sun aspect Sun in 9th house : Exact', description: 'Peak dharma-day. Sign the international commitment, accept the senior blessing.' },
  { name: 'Sun aspect Sun in 9th house : Ends', description: 'Dharma-window closes. Lock in the year\'s ethical commitments.' },
  { name: 'Sun aspect Moon in 8th house', description: 'Visibility through transformation, sexuality, in-laws. Deep intimacy conversations gain spotlight.' },
  { name: 'Sun aspect Moon in 8th house : Starts', description: 'Transformation-visibility window opens. Prepare for in-law or inheritance conversation.' },
  { name: 'Sun aspect Moon in 8th house : Exact', description: 'Peak day for visible intimacy work. Hold the depth conversation.' },
  { name: 'Sun aspect Moon in 8th house : Ends', description: 'Transformation-visibility window closes. Lock in deep commitments.' },
  { name: 'Sun aspect Mercury in 10th house', description: 'Solar fire on public-couple zenith. Joint announcements, brand-couple moves at peak.' },
  { name: 'Sun aspect Mercury in 10th house : Starts', description: 'Public-couple window opens. Polish the joint executive materials.' },
  { name: 'Sun aspect Mercury in 10th house : Exact', description: 'Peak public-couple day. Take the joint elevation; deliver the joint announcement.' },
  { name: 'Sun aspect Mercury in 10th house : Ends', description: 'Public-couple window closes. Lock in the joint commitments.' },
  { name: 'Sun aspect Venus in 11th house', description: 'Solar light on the friend-network. Group-friend warmth peaks; senior-female mentor conversations.' },
  { name: 'Sun aspect Venus in 11th house : Starts', description: 'Friend-visibility window opens. Brief the senior network.' },
  { name: 'Sun aspect Venus in 11th house : Exact', description: 'Peak friend-day. Take the senior-female mentor call; host the group gathering.' },
  { name: 'Sun aspect Venus in 11th house : Ends', description: 'Friend-visibility window closes. Lock in friend commitments.' },
  { name: 'Sun aspect Mars in 5th house', description: 'Solar fire on creative-romantic authority. Bold romance moves, mentee-direction calls, decisive children-related steps.' },
  { name: 'Sun aspect Mars in 5th house : Starts', description: 'Romance-fire window opens. Train; prepare the bold creative-romantic move.' },
  { name: 'Sun aspect Mars in 5th house : Exact', description: 'Peak romance-fire day. Lead the launch, take the bold romantic action.' },
  { name: 'Sun aspect Mars in 5th house : Ends', description: 'Romance-fire window closes. Lock in the romantic commitments.' },
  { name: 'Sun aspect Jupiter in 1st house', description: 'Solar light on the wise-self. The body radiates teacher-warmth; commitment-elevation favored.' },
  { name: 'Sun aspect Jupiter in 1st house : Starts', description: 'Wise-self window opens. Polish the public-mantle materials.' },
  { name: 'Sun aspect Jupiter in 1st house : Exact', description: 'Peak wise-self day. Accept the teacher-elevation in the relationship.' },
  { name: 'Sun aspect Jupiter in 1st house : Ends', description: 'Wise-self window closes. Lock in the public commitments.' },
  { name: 'Sun aspect Saturn in 2nd house', description: 'Solar fire on the slow joint-finance engine. The structural family-money case finally lights.' },
  { name: 'Sun aspect Saturn in 2nd house : Starts', description: 'Slow-finance window opens. Prepare the structural joint-money case.' },
  { name: 'Sun aspect Saturn in 2nd house : Exact', description: 'Peak slow-finance day. Sign the joint compensation paper; close the family-money case.' },
  { name: 'Sun aspect Saturn in 2nd house : Ends', description: 'Slow-finance window closes. Lock in the joint resource commitments.' },
  { name: 'Sun aspect Rahu in 6th house', description: 'Solar fire on the obsessive-intimate-conflict zone. Win the long-running family-system feud.' },
  { name: 'Sun aspect Rahu in 6th house : Starts', description: 'Conflict-victory window opens. Sharpen the case.' },
  { name: 'Sun aspect Rahu in 6th house : Exact', description: 'Peak conflict-victory day. Settle the sibling debt; close the family rift.' },
  { name: 'Sun aspect Rahu in 6th house : Ends', description: 'Conflict-victory window closes. Lock in the wins.' },
  { name: 'Sun aspect Ketu in 12th house', description: 'Solar light on foreign-detached zone. Hidden-romance recognition; foreign-channel news lands.' },
  { name: 'Sun aspect Ketu in 12th house : Starts', description: 'Foreign-detached window opens. Prepare for muted recognition.' },
  { name: 'Sun aspect Ketu in 12th house : Exact', description: 'Peak foreign-detached day. Take the foreign call; honor the retreat.' },
  { name: 'Sun aspect Ketu in 12th house : Ends', description: 'Foreign-detached window closes. Move forward with cleaner intent.' },
  { name: 'Moon aspect Sun in 9th house', description: 'Emotional charge on dharma. Warm conversations about shared values, foreign future, ceremonial commitment.' },
  { name: 'Moon aspect Sun in 9th house : Starts', description: 'Dharma-warmth window opens. Soften the principled tone.' },
  { name: 'Moon aspect Sun in 9th house : Exact', description: 'Peak dharma-warmth day. Make the heart-led principled call together.' },
  { name: 'Moon aspect Sun in 9th house : Ends', description: 'Dharma-warmth window closes. Lock in warm joint commitments.' },
  { name: 'Moon aspect Moon in 8th house', description: 'Monthly transformation-emotion peak. Sexuality, in-laws, shared resources land with emotional weight.' },
  { name: 'Moon aspect Moon in 8th house : Starts', description: 'Transformation-emotion window opens. Prepare for the deep-water wave.' },
  { name: 'Moon aspect Moon in 8th house : Exact', description: 'Peak transformation-emotion day. Hold the depth conversation; honor the intimacy.' },
  { name: 'Moon aspect Moon in 8th house : Ends', description: 'Transformation-emotion window closes. Lock in the deep commitments.' },
  { name: 'Moon aspect Mercury in 10th house', description: 'Emotional intelligence at MC. Empathetic joint-announcements; warm public-couple moments.' },
  { name: 'Moon aspect Mercury in 10th house : Starts', description: 'Emotion-on-MC window opens. Soften the public-couple tone.' },
  { name: 'Moon aspect Mercury in 10th house : Exact', description: 'Peak day for empathetic public-couple work. Hold the warm joint engagement.' },
  { name: 'Moon aspect Mercury in 10th house : Ends', description: 'Emotion-on-MC window closes. Lock in the warm public-couple commitments.' },
  { name: 'Moon aspect Venus in 11th house', description: 'Emotional warmth on the friend-network. Senior-female mentor reaches out; group-friend warmth.' },
  { name: 'Moon aspect Venus in 11th house : Starts', description: 'Friend-warmth window opens. Reach out to the senior-female allies.' },
  { name: 'Moon aspect Venus in 11th house : Exact', description: 'Peak friend-warmth day. Host the group gathering; take the warm mentor call.' },
  { name: 'Moon aspect Venus in 11th house : Ends', description: 'Friend-warmth window closes. Lock in warm group commitments.' },
  { name: 'Moon aspect Mars in 5th house', description: 'Emotional charge on creative-romance. Heart-led romantic gestures; children-related warmth.' },
  { name: 'Moon aspect Mars in 5th house : Starts', description: 'Romance-warmth window opens. Soften the romantic direction.' },
  { name: 'Moon aspect Mars in 5th house : Exact', description: 'Peak romance-warmth day. Make the heart-led romantic gesture.' },
  { name: 'Moon aspect Mars in 5th house : Ends', description: 'Romance-warmth window closes. Lock in the romantic commitments.' },
  { name: 'Moon aspect Jupiter in 1st house', description: 'Emotional warmth on the wise-self. Body reads as approachable; teacher-warmth in love.' },
  { name: 'Moon aspect Jupiter in 1st house : Starts', description: 'Wise-warmth window opens. Prepare the warm teacher-tone.' },
  { name: 'Moon aspect Jupiter in 1st house : Exact', description: 'Peak wise-warmth day. Take the heart-led principled engagement.' },
  { name: 'Moon aspect Jupiter in 1st house : Ends', description: 'Wise-warmth window closes. Lock in warm public commitments.' },
  { name: 'Moon aspect Saturn in 2nd house', description: 'Emotional weight on slow joint-finance. Family-money conversations land with warmth.' },
  { name: 'Moon aspect Saturn in 2nd house : Starts', description: 'Slow-finance-emotion window opens. Soften the resource tone.' },
  { name: 'Moon aspect Saturn in 2nd house : Exact', description: 'Peak slow-finance-emotion day. Hold the warm family-finance conversation.' },
  { name: 'Moon aspect Saturn in 2nd house : Ends', description: 'Slow-finance-emotion window closes. Lock in the warm resource commitments.' },
  { name: 'Moon aspect Rahu in 6th house', description: 'Emotional charge on obsessive intimate-conflict. Empathetic family-system mediation.' },
  { name: 'Moon aspect Rahu in 6th house : Starts', description: 'Conflict-warmth window opens. Soften the conflict tone.' },
  { name: 'Moon aspect Rahu in 6th house : Exact', description: 'Peak conflict-warmth day. Hold the empathetic 1:1 with the difficult sibling.' },
  { name: 'Moon aspect Rahu in 6th house : Ends', description: 'Conflict-warmth window closes. Lock in the empathetic commitments.' },
  { name: 'Moon aspect Ketu in 12th house', description: 'Emotional charge on the dissolution-zone. Foreign-friend warmth, retreat-tone, behind-scenes empathetic intimacy.' },
  { name: 'Moon aspect Ketu in 12th house : Starts', description: 'Dissolution-warmth window opens. Sleep more; deepen privately.' },
  { name: 'Moon aspect Ketu in 12th house : Exact', description: 'Peak dissolution-warmth day. Take the warm foreign call; honor the retreat impulse.' },
  { name: 'Moon aspect Ketu in 12th house : Ends', description: 'Dissolution-warmth window closes. Move forward warmer-but-leaner.' },
  { name: 'Mercury aspect Sun in 9th house', description: 'Sharp mind on dharma. Foreign correspondence, ethics-statements, ceremonial-paperwork peak.' },
  { name: 'Mercury aspect Sun in 9th house : Starts', description: 'Dharma-mind window opens. Prepare the principled document.' },
  { name: 'Mercury aspect Sun in 9th house : Exact', description: 'Peak dharma-mind day. File the foreign-relationship motion; ship the values-statement.' },
  { name: 'Mercury aspect Sun in 9th house : Ends', description: 'Dharma-mind window closes. Lock in the foreign and ethical paperwork.' },
  { name: 'Mercury aspect Moon in 8th house', description: 'Sharp mind on transformation. Forensic conversations about shared resources; due-diligence on in-laws.' },
  { name: 'Mercury aspect Moon in 8th house : Starts', description: 'Transformation-mind window opens. Prepare the depth-document.' },
  { name: 'Mercury aspect Moon in 8th house : Exact', description: 'Peak transformation-mind day. Ship the forensic disclosure; deliver the in-law agreement.' },
  { name: 'Mercury aspect Moon in 8th house : Ends', description: 'Transformation-mind window closes. Lock in the depth-paperwork.' },
  { name: 'Mercury aspect Mercury in 10th house', description: 'Mercury return aspect — peak public-couple communication. Joint press releases, joint executive memos.' },
  { name: 'Mercury aspect Mercury in 10th house : Starts', description: 'Public-couple communication window opens. Polish the joint message.' },
  { name: 'Mercury aspect Mercury in 10th house : Exact', description: 'Peak public-couple communication day. Publish the joint platform-defining piece.' },
  { name: 'Mercury aspect Mercury in 10th house : Ends', description: 'Public-couple communication window closes. Convert messaging into commitment.' },
  { name: 'Mercury aspect Venus in 11th house', description: 'Sharp mind on the friend-network. Structured outreach to senior-female allies; precise group-friend invitations.' },
  { name: 'Mercury aspect Venus in 11th house : Starts', description: 'Friend-mind window opens. Draft the senior-network ask.' },
  { name: 'Mercury aspect Venus in 11th house : Exact', description: 'Peak friend-mind day. Send the precise group-friend invitation.' },
  { name: 'Mercury aspect Venus in 11th house : Ends', description: 'Friend-mind window closes. Lock in the friend-paperwork.' },
  { name: 'Mercury aspect Mars in 5th house', description: 'Sharp mind on creative-romance. The bold love letter, the children-related update, the punchy mentee-coaching note.' },
  { name: 'Mercury aspect Mars in 5th house : Starts', description: 'Romance-mind window opens. Draft the bold note.' },
  { name: 'Mercury aspect Mars in 5th house : Exact', description: 'Peak romance-mind day. Send the punchy creative-romantic pitch.' },
  { name: 'Mercury aspect Mars in 5th house : Ends', description: 'Romance-mind window closes. Lock in the romantic paperwork.' },
  { name: 'Mercury aspect Jupiter in 1st house', description: 'Sharp mind on the wise-self. Teacher-narrative refresh in love; values-anchored personal post.' },
  { name: 'Mercury aspect Jupiter in 1st house : Starts', description: 'Wise-mind window opens. Draft the values-narrative.' },
  { name: 'Mercury aspect Jupiter in 1st house : Exact', description: 'Peak wise-mind day. Publish the principled personal piece.' },
  { name: 'Mercury aspect Jupiter in 1st house : Ends', description: 'Wise-mind window closes. Lock in the public commitments.' },
  { name: 'Mercury aspect Saturn in 2nd house', description: 'Sharp mind on slow joint-finance. Joint-budget memos, family-money paperwork.' },
  { name: 'Mercury aspect Saturn in 2nd house : Starts', description: 'Slow-finance-mind window opens. Draft the structural joint-money case.' },
  { name: 'Mercury aspect Saturn in 2nd house : Exact', description: 'Peak slow-finance-mind day. File the joint-resource paper.' },
  { name: 'Mercury aspect Saturn in 2nd house : Ends', description: 'Slow-finance-mind window closes. Lock in the resource paperwork.' },
  { name: 'Mercury aspect Rahu in 6th house', description: 'Sharp mind on obsessive intimate-conflict. Family-system documents, sibling-mediation letters.' },
  { name: 'Mercury aspect Rahu in 6th house : Starts', description: 'Conflict-mind window opens. Sharpen the case file.' },
  { name: 'Mercury aspect Rahu in 6th house : Exact', description: 'Peak conflict-mind day. Ship the family-system disclosure.' },
  { name: 'Mercury aspect Rahu in 6th house : Ends', description: 'Conflict-mind window closes. Lock in the resolution paperwork.' },
  { name: 'Mercury aspect Ketu in 12th house', description: 'Sharp mind on the dissolution-zone. Confidential love-letters; off-record foreign-correspondence.' },
  { name: 'Mercury aspect Ketu in 12th house : Starts', description: 'Dissolution-mind window opens. Prepare the confidential note.' },
  { name: 'Mercury aspect Ketu in 12th house : Exact', description: 'Peak dissolution-mind day. Send the off-record foreign-channel note.' },
  { name: 'Mercury aspect Ketu in 12th house : Ends', description: 'Dissolution-mind window closes. Lock in confidential commitments.' },
  { name: 'Venus aspect Sun in 9th house', description: 'Warmth on the dharma engine. Graceful foreign-engagement; ceremonial commitment-conversations.' },
  { name: 'Venus aspect Sun in 9th house : Starts', description: 'Dharma-warmth window opens. Plan the foreign trip together.' },
  { name: 'Venus aspect Sun in 9th house : Exact', description: 'Peak dharma-warmth day. Take the foreign call together; honor the principled commitment.' },
  { name: 'Venus aspect Sun in 9th house : Ends', description: 'Dharma-warmth window closes. Lock in foreign and ethical commitments.' },
  { name: 'Venus aspect Moon in 8th house', description: 'Warmth on the transformation chamber. Diplomatic intimacy; gentle in-law conversations.' },
  { name: 'Venus aspect Moon in 8th house : Starts', description: 'Transformation-warmth window opens. Soften the chapter-ending tone.' },
  { name: 'Venus aspect Moon in 8th house : Exact', description: 'Peak transformation-warmth day. Hold the gentle inheritance conversation.' },
  { name: 'Venus aspect Moon in 8th house : Ends', description: 'Transformation-warmth window closes. Lock in warm chapter-ending commitments.' },
  { name: 'Venus aspect Mercury in 10th house', description: 'Warmth at MC. Brand-couple campaigns; the joint public face softens.' },
  { name: 'Venus aspect Mercury in 10th house : Starts', description: 'Couple-warmth window opens. Plan the joint brand refresh.' },
  { name: 'Venus aspect Mercury in 10th house : Exact', description: 'Peak couple-warmth day. Launch the joint campaign; present the redesign.' },
  { name: 'Venus aspect Mercury in 10th house : Ends', description: 'Couple-warmth window closes. Lock in the design commitments.' },
  { name: 'Venus aspect Venus in 11th house', description: 'Venus return aspect — peak friend-network warmth. Group-friend gatherings; senior-female mentor weighs in.' },
  { name: 'Venus aspect Venus in 11th house : Starts', description: 'Friend-return window opens. Reach out to the senior-female mentors.' },
  { name: 'Venus aspect Venus in 11th house : Exact', description: 'Peak friend-return day. Host the warm gathering; take the senior-mentor call.' },
  { name: 'Venus aspect Venus in 11th house : Ends', description: 'Friend-return window closes. Lock in the friend commitments.' },
  { name: 'Venus aspect Mars in 5th house', description: 'Warmth on creative-romance. Aesthetic romantic gestures; mentor-protégé warmth at peak.' },
  { name: 'Venus aspect Mars in 5th house : Starts', description: 'Romance-warmth window opens. Plan the aesthetic date.' },
  { name: 'Venus aspect Mars in 5th house : Exact', description: 'Peak romance-warmth day. Launch the beautiful romantic gesture.' },
  { name: 'Venus aspect Mars in 5th house : Ends', description: 'Romance-warmth window closes. Lock in the romantic commitments.' },
  { name: 'Venus aspect Jupiter in 1st house', description: 'Warmth on the wise-self. Charm-asks in love where principle is also visible.' },
  { name: 'Venus aspect Jupiter in 1st house : Starts', description: 'Wise-charm window opens. Prepare the warm principled outreach.' },
  { name: 'Venus aspect Jupiter in 1st house : Exact', description: 'Peak wise-charm day. Make the warm principled ask.' },
  { name: 'Venus aspect Jupiter in 1st house : Ends', description: 'Wise-charm window closes. Lock in the warm public commitments.' },
  { name: 'Venus aspect Saturn in 2nd house', description: 'Warmth on slow joint-finance. Joint-account warmth; family-finance diplomatic ease.' },
  { name: 'Venus aspect Saturn in 2nd house : Starts', description: 'Slow-finance-warmth window opens. Soften the resource tone.' },
  { name: 'Venus aspect Saturn in 2nd house : Exact', description: 'Peak slow-finance-warmth day. Make the warm joint-money ask.' },
  { name: 'Venus aspect Saturn in 2nd house : Ends', description: 'Slow-finance-warmth window closes. Lock in warm resource commitments.' },
  { name: 'Venus aspect Rahu in 6th house', description: 'Warmth on obsessive intimate-conflict. Difficult sibling becomes warm ally.' },
  { name: 'Venus aspect Rahu in 6th house : Starts', description: 'Conflict-warmth window opens. Soften the family-system tone.' },
  { name: 'Venus aspect Rahu in 6th house : Exact', description: 'Peak conflict-warmth day. Hold the warm 1:1 with the rival sibling.' },
  { name: 'Venus aspect Rahu in 6th house : Ends', description: 'Conflict-warmth window closes. Lock in warm family commitments.' },
  { name: 'Venus aspect Ketu in 12th house', description: 'Warmth on the dissolution-zone. Hidden patrons surface; foreign-romance offers land; retreat-warmth.' },
  { name: 'Venus aspect Ketu in 12th house : Starts', description: 'Dissolution-warmth window opens. Plan the foreign trip together.' },
  { name: 'Venus aspect Ketu in 12th house : Exact', description: 'Peak dissolution-warmth day. Take the foreign-channel call together.' },
  { name: 'Venus aspect Ketu in 12th house : Ends', description: 'Dissolution-warmth window closes. Lock in the foreign commitments.' },
  { name: 'Mars aspect Sun in 9th house', description: 'Action on dharma. Bold foreign-engagement; principled commitment-fight.' },
  { name: 'Mars aspect Sun in 9th house : Starts', description: 'Dharma-action window opens. Prepare the principled bold move.' },
  { name: 'Mars aspect Sun in 9th house : Exact', description: 'Peak dharma-action day. File the foreign motion; lead the principled charge together.' },
  { name: 'Mars aspect Sun in 9th house : Ends', description: 'Dharma-action window closes. Lock in the foreign commitments.' },
  { name: 'Mars aspect Moon in 8th house', description: 'Action on the transformation chamber. Surgical in-law conversations; decisive sexuality moves.' },
  { name: 'Mars aspect Moon in 8th house : Starts', description: 'Transformation-action window opens. Prepare the chapter-ending push.' },
  { name: 'Mars aspect Moon in 8th house : Exact', description: 'Peak transformation-action day. Lead the restructuring; sign the in-law agreement.' },
  { name: 'Mars aspect Moon in 8th house : Ends', description: 'Transformation-action window closes. Lock in the chapter-ending commitments.' },
  { name: 'Mars aspect Mercury in 10th house', description: 'Action at MC. Among the strongest public-couple action windows. Launch joint flagship.' },
  { name: 'Mars aspect Mercury in 10th house : Starts', description: 'MC-action window opens. Prepare the bold joint play.' },
  { name: 'Mars aspect Mercury in 10th house : Exact', description: 'Peak MC-action day. Launch, demand, lead together.' },
  { name: 'Mars aspect Mercury in 10th house : Ends', description: 'MC-action window closes. Convert moves into permanent positions.' },
  { name: 'Mars aspect Venus in 11th house', description: 'Action on the friend-network. Assertive group-friend leadership; warm-but-firm reset.' },
  { name: 'Mars aspect Venus in 11th house : Starts', description: 'Friend-action window opens. Prepare the structured ask.' },
  { name: 'Mars aspect Venus in 11th house : Exact', description: 'Peak friend-action day. Make the friend-circle reset move.' },
  { name: 'Mars aspect Venus in 11th house : Ends', description: 'Friend-action window closes. Lock in friend commitments.' },
  { name: 'Mars aspect Mars in 5th house', description: 'Mars return aspect — peak creative-romantic charge. Launch the founder romantic move; take the calculated speculative leap.' },
  { name: 'Mars aspect Mars in 5th house : Starts', description: 'Romance-warrior window opens. Train; prepare the bold romantic push.' },
  { name: 'Mars aspect Mars in 5th house : Exact', description: 'Peak romance-warrior day. Lead the romantic charge; sign the bold paper together.' },
  { name: 'Mars aspect Mars in 5th house : Ends', description: 'Romance-warrior window closes. Lock in the romantic commitments.' },
  { name: 'Mars aspect Jupiter in 1st house', description: 'Action on the wise-self. Founder-as-teacher declarations in love.' },
  { name: 'Mars aspect Jupiter in 1st house : Starts', description: 'Wise-action window opens. Prepare the principled bold move.' },
  { name: 'Mars aspect Jupiter in 1st house : Exact', description: 'Peak wise-action day. Take the principled commitment-action.' },
  { name: 'Mars aspect Jupiter in 1st house : Ends', description: 'Wise-action window closes. Lock in the public commitments.' },
  { name: 'Mars aspect Saturn in 2nd house', description: 'Action on slow joint-finance. Heated joint-money battles.' },
  { name: 'Mars aspect Saturn in 2nd house : Starts', description: 'Slow-finance-action window opens. Prepare the data-backed case.' },
  { name: 'Mars aspect Saturn in 2nd house : Exact', description: 'Peak slow-finance-action day. Make the joint-money push.' },
  { name: 'Mars aspect Saturn in 2nd house : Ends', description: 'Slow-finance-action window closes. Lock in the resource commitments.' },
  { name: 'Mars aspect Rahu in 6th house', description: 'Action on obsessive intimate-conflict. Win the long sibling dispute; settle the family-debt aggressively.' },
  { name: 'Mars aspect Rahu in 6th house : Starts', description: 'Conflict-action window opens. Sharpen the strategy.' },
  { name: 'Mars aspect Rahu in 6th house : Exact', description: 'Peak conflict-action day. Lead the family-system push.' },
  { name: 'Mars aspect Rahu in 6th house : Ends', description: 'Conflict-action window closes. Lock in the wins.' },
  { name: 'Mars aspect Ketu in 12th house', description: 'Action on the dissolution-zone. Behind-scenes power plays; foreign-trade fights with partner.' },
  { name: 'Mars aspect Ketu in 12th house : Starts', description: 'Dissolution-action window opens. Prepare the hidden push.' },
  { name: 'Mars aspect Ketu in 12th house : Exact', description: 'Peak dissolution-action day. Make the foreign back-channel move.' },
  { name: 'Mars aspect Ketu in 12th house : Ends', description: 'Dissolution-action window closes. Lock in the foreign commitments.' },
  { name: 'Jupiter aspect Sun in 9th house', description: 'Wisdom-blessing on dharma in own sign. Among the most blessed relationship-windows of any twelve-year cycle.' },
  { name: 'Jupiter aspect Sun in 9th house : Starts', description: 'Dharma-blessing window opens. Brief the senior mentor; plan the foreign step together.' },
  { name: 'Jupiter aspect Sun in 9th house : Exact', description: 'Peak dharma-blessing day. Sign the international commitment, accept the senior blessing.' },
  { name: 'Jupiter aspect Sun in 9th house : Ends', description: 'Dharma-blessing window closes. Lock in foreign and ethical commitments.' },
  { name: 'Jupiter aspect Moon in 8th house', description: 'Wisdom into transformation. Joint inheritance favorably resolves; deep intimacy growth.' },
  { name: 'Jupiter aspect Moon in 8th house : Starts', description: 'Transformation-blessing window opens. Prepare for chapter-ending favor.' },
  { name: 'Jupiter aspect Moon in 8th house : Exact', description: 'Peak transformation-blessing day. Sign the joint inheritance papers.' },
  { name: 'Jupiter aspect Moon in 8th house : Ends', description: 'Transformation-blessing window closes. Lock in the chapter-ending commitments.' },
  { name: 'Jupiter aspect Mercury in 10th house', description: 'Wisdom at MC. Peak public-couple year; brand-couple elevation; joint board-tier appearances.' },
  { name: 'Jupiter aspect Mercury in 10th house : Starts', description: 'MC-blessing window opens. Polish joint executive materials.' },
  { name: 'Jupiter aspect Mercury in 10th house : Exact', description: 'Peak MC-blessing day. Accept the joint chief-tier engagement.' },
  { name: 'Jupiter aspect Mercury in 10th house : Ends', description: 'MC-blessing window closes. Lock in the joint commitments.' },
  { name: 'Jupiter aspect Venus in 11th house', description: 'Wisdom on the friend-network. Group-friendships compound; senior-female mentors deliver decisive advice.' },
  { name: 'Jupiter aspect Venus in 11th house : Starts', description: 'Friend-blessing window opens. Brief the senior network.' },
  { name: 'Jupiter aspect Venus in 11th house : Exact', description: 'Peak friend-blessing day. Take the senior-mentor advice; deepen the group bonds.' },
  { name: 'Jupiter aspect Venus in 11th house : Ends', description: 'Friend-blessing window closes. Lock in the group commitments.' },
  { name: 'Jupiter aspect Mars in 5th house', description: 'Wisdom on creative-romance. Major romance-launch favor; children-related news; mentee placements.' },
  { name: 'Jupiter aspect Mars in 5th house : Starts', description: 'Romance-blessing window opens. Plan the year\'s flagship romantic move.' },
  { name: 'Jupiter aspect Mars in 5th house : Exact', description: 'Peak romance-blessing day. Take the visible commitment-step you have been declining.' },
  { name: 'Jupiter aspect Mars in 5th house : Ends', description: 'Romance-blessing window closes. Lock in the romantic commitments.' },
  { name: 'Jupiter aspect Jupiter in 1st house', description: 'Jupiter return aspect — annual-tier expansion of self in love. Take the role expansion; declare the bigger ambition together.' },
  { name: 'Jupiter aspect Jupiter in 1st house : Starts', description: 'Self-blessing window opens. Plan the public-mantle assumption.' },
  { name: 'Jupiter aspect Jupiter in 1st house : Exact', description: 'Peak self-blessing day. Accept the elevation; declare the ambition.' },
  { name: 'Jupiter aspect Jupiter in 1st house : Ends', description: 'Self-blessing window closes. Lock in the public commitments.' },
  { name: 'Jupiter aspect Saturn in 2nd house', description: 'Wisdom on slow joint-finance. Family-wealth structuring expands favorably.' },
  { name: 'Jupiter aspect Saturn in 2nd house : Starts', description: 'Resource-blessing window opens. Prepare the structural joint-money case.' },
  { name: 'Jupiter aspect Saturn in 2nd house : Exact', description: 'Peak resource-blessing day. Sign the joint compensation lift.' },
  { name: 'Jupiter aspect Saturn in 2nd house : Ends', description: 'Resource-blessing window closes. Lock in the joint resource commitments.' },
  { name: 'Jupiter aspect Rahu in 6th house', description: 'Wisdom on obsessive intimate-conflict. Difficult siblings become teachers; family-system tensions resolve through wisdom.' },
  { name: 'Jupiter aspect Rahu in 6th house : Starts', description: 'Conflict-blessing window opens. Reframe the family rift as teaching.' },
  { name: 'Jupiter aspect Rahu in 6th house : Exact', description: 'Peak conflict-blessing day. Win the family-system case through wisdom.' },
  { name: 'Jupiter aspect Rahu in 6th house : Ends', description: 'Conflict-blessing window closes. Lock in the resolution.' },
  { name: 'Jupiter aspect Ketu in 12th house', description: 'Wisdom on the dissolution-zone. Foreign-fortune favor; hidden-romance blessing; retreat-led intimacy.' },
  { name: 'Jupiter aspect Ketu in 12th house : Starts', description: 'Dissolution-blessing window opens. Plan the foreign sabbatical or pilgrimage together.' },
  { name: 'Jupiter aspect Ketu in 12th house : Exact', description: 'Peak dissolution-blessing day. Take the foreign-channel offer; honor the hidden mandate.' },
  { name: 'Jupiter aspect Ketu in 12th house : Ends', description: 'Dissolution-blessing window closes. Lock in the foreign commitments.' },
  { name: 'Saturn aspect Sun in 9th house', description: 'Structural test of dharma. Father-figure or guru-figure relationship restructures; principles tested.' },
  { name: 'Saturn aspect Sun in 9th house : Starts', description: 'Dharma-discipline window opens. Prepare for the slow ethical reckoning together.' },
  { name: 'Saturn aspect Sun in 9th house : Exact', description: 'Peak dharma-discipline day. The principle is tested. Hold steady together.' },
  { name: 'Saturn aspect Sun in 9th house : Ends', description: 'Dharma-discipline window closes. What survived is permanent.' },
  { name: 'Saturn aspect Moon in 8th house', description: 'Major intimacy-restructuring with deep emotional charge. In-law chapters open and close. Patience compounds.' },
  { name: 'Saturn aspect Moon in 8th house : Starts', description: 'Transformation-discipline window opens. Prepare for chapter-ending grind.' },
  { name: 'Saturn aspect Moon in 8th house : Exact', description: 'Peak transformation-discipline day. Sign the chapter-ending agreements.' },
  { name: 'Saturn aspect Moon in 8th house : Ends', description: 'Transformation-discipline window closes. The new structure holds.' },
  { name: 'Saturn aspect Mercury in 10th house', description: 'The 2.5-year window where the public-couple identity solidifies into something permanent.' },
  { name: 'Saturn aspect Mercury in 10th house : Starts', description: 'MC-discipline window opens. Polish the long-game joint materials.' },
  { name: 'Saturn aspect Mercury in 10th house : Exact', description: 'Peak MC-discipline day. The joint long-structure crystallizes.' },
  { name: 'Saturn aspect Mercury in 10th house : Ends', description: 'MC-discipline window closes. Convert effort into formal joint commitment.' },
  { name: 'Saturn aspect Venus in 11th house', description: 'Disciplined structural friendship. The network purges what is no longer dharmic; group-friendship rituals formalize.' },
  { name: 'Saturn aspect Venus in 11th house : Starts', description: 'Friend-discipline window opens. Audit the network for what is dharmic.' },
  { name: 'Saturn aspect Venus in 11th house : Exact', description: 'Peak friend-discipline day. The structured group commitment lands.' },
  { name: 'Saturn aspect Venus in 11th house : Ends', description: 'Friend-discipline window closes. The clean-network is what remains.' },
  { name: 'Saturn aspect Mars in 5th house', description: 'Creative-romantic authority is tested by structural delay. Mentee or children-relationships restructure.' },
  { name: 'Saturn aspect Mars in 5th house : Starts', description: 'Romance-discipline window opens. Audit the speculative-romance book.' },
  { name: 'Saturn aspect Mars in 5th house : Exact', description: 'Peak romance-discipline day. The slow romantic commitment lands.' },
  { name: 'Saturn aspect Mars in 5th house : Ends', description: 'Romance-discipline window closes. What earned was earned.' },
  { name: 'Saturn aspect Jupiter in 1st house', description: 'Multi-year structural pressure on body and identity in love. Slow simplification.' },
  { name: 'Saturn aspect Jupiter in 1st house : Starts', description: 'Self-discipline window opens. Eliminate vanity commitments.' },
  { name: 'Saturn aspect Jupiter in 1st house : Exact', description: 'Peak self-discipline day. The reckoning is acute. Hold steady.' },
  { name: 'Saturn aspect Jupiter in 1st house : Ends', description: 'Self-discipline window closes. What survived is permanent.' },
  { name: 'Saturn aspect Saturn in 2nd house', description: 'Saturn return-aspect on slow joint-finance. The slowest, most permanent resource lift of the decade.' },
  { name: 'Saturn aspect Saturn in 2nd house : Starts', description: 'Resource-discipline window opens. Prepare for slow but real joint-money growth.' },
  { name: 'Saturn aspect Saturn in 2nd house : Exact', description: 'Peak resource-discipline day. The structural joint-money case settles.' },
  { name: 'Saturn aspect Saturn in 2nd house : Ends', description: 'Resource-discipline window closes. The new joint-resource foundation is permanent.' },
  { name: 'Saturn aspect Rahu in 6th house', description: 'Best multi-year window for resolving long-running family-system conflicts.' },
  { name: 'Saturn aspect Rahu in 6th house : Starts', description: 'Conflict-discipline window opens. Prepare for the long case.' },
  { name: 'Saturn aspect Rahu in 6th house : Exact', description: 'Peak conflict-discipline day. The family-system transformation crystallizes.' },
  { name: 'Saturn aspect Rahu in 6th house : Ends', description: 'Conflict-discipline window closes. The slow win is permanent.' },
  { name: 'Saturn aspect Ketu in 12th house', description: 'Multi-year discipline on foreign, hidden, devotional channels. Sabbaticals turn structural.' },
  { name: 'Saturn aspect Ketu in 12th house : Starts', description: 'Dissolution-discipline window opens. Audit the foreign-and-pleasure budgets.' },
  { name: 'Saturn aspect Ketu in 12th house : Exact', description: 'Peak dissolution-discipline day. The foreign sabbatical formalizes.' },
  { name: 'Saturn aspect Ketu in 12th house : Ends', description: 'Dissolution-discipline window closes. The disciplined hidden-channel is permanent.' },
  { name: 'Rahu aspect Sun in 9th house', description: 'Foreign-fortune obsession on dharma. Ethics-driven obsession; controversial guru-bond.' },
  { name: 'Rahu aspect Sun in 9th house : Starts', description: 'Dharma-obsession window opens. Beware the spectacular guru.' },
  { name: 'Rahu aspect Sun in 9th house : Exact', description: 'Peak dharma-obsession day. The bold foreign leap presents — verify integrity.' },
  { name: 'Rahu aspect Sun in 9th house : Ends', description: 'Dharma-obsession window closes. Keep what was anchored; release vanity.' },
  { name: 'Rahu aspect Moon in 8th house', description: 'Obsessive transformation. Sudden inheritance, regulatory obsession around the union.' },
  { name: 'Rahu aspect Moon in 8th house : Starts', description: 'Transformation-obsession window opens. Beware emotional distortion.' },
  { name: 'Rahu aspect Moon in 8th house : Exact', description: 'Peak transformation-obsession day. The chapter-ending leap presents — verify.' },
  { name: 'Rahu aspect Moon in 8th house : Ends', description: 'Transformation-obsession window closes. Keep grounded gains.' },
  { name: 'Rahu aspect Mercury in 10th house', description: 'Obsessive public-couple elevation. Sudden brand-couple offers; verify legitimacy.' },
  { name: 'Rahu aspect Mercury in 10th house : Starts', description: 'MC-obsession window opens. Vet incoming joint offers.' },
  { name: 'Rahu aspect Mercury in 10th house : Exact', description: 'Peak MC-obsession day. The bold joint pivot presents — verify.' },
  { name: 'Rahu aspect Mercury in 10th house : Ends', description: 'MC-obsession window closes. Lock in legitimate pivots.' },
  { name: 'Rahu aspect Venus in 11th house', description: 'Obsessive friend-network and gain chapter. Group-friend dynamics intensify.' },
  { name: 'Rahu aspect Venus in 11th house : Starts', description: 'Friend-obsession window opens. Audit network for integrity.' },
  { name: 'Rahu aspect Venus in 11th house : Exact', description: 'Peak friend-obsession day. The big friend-news lands — verify.' },
  { name: 'Rahu aspect Venus in 11th house : Ends', description: 'Friend-obsession window closes. Keep clean friendships.' },
  { name: 'Rahu aspect Mars in 5th house', description: 'Eighteen-month peak ambition window for romantic spectacle, children-frenzy, mentee-obsession. Verify each leap.' },
  { name: 'Rahu aspect Mars in 5th house : Starts', description: 'Romance-obsession window opens. Beware spectacle-over-substance.' },
  { name: 'Rahu aspect Mars in 5th house : Exact', description: 'Peak romance-obsession day. The bold leap presents — verify integrity twice.' },
  { name: 'Rahu aspect Mars in 5th house : Ends', description: 'Romance-obsession window closes. Keep what was anchored to dharma.' },
  { name: 'Rahu aspect Jupiter in 1st house', description: 'Obsessive self-reinvention in love. New persona, new ambition.' },
  { name: 'Rahu aspect Jupiter in 1st house : Starts', description: 'Self-obsession window opens. Beware identity hijack.' },
  { name: 'Rahu aspect Jupiter in 1st house : Exact', description: 'Peak self-obsession day. Take the unconventional move — but check basics.' },
  { name: 'Rahu aspect Jupiter in 1st house : Ends', description: 'Self-obsession window closes. Decide which experiments to keep.' },
  { name: 'Rahu aspect Saturn in 2nd house', description: 'Obsessive ambition around joint-finance. Watch get-rich-quick logic in the partnership.' },
  { name: 'Rahu aspect Saturn in 2nd house : Starts', description: 'Resource-obsession window opens. Beware get-rich-quick.' },
  { name: 'Rahu aspect Saturn in 2nd house : Exact', description: 'Peak resource-obsession day. The big joint-finance leap presents — verify.' },
  { name: 'Rahu aspect Saturn in 2nd house : Ends', description: 'Resource-obsession window closes. Trust the slow rail.' },
  { name: 'Rahu aspect Rahu in 6th house', description: 'Rahu return aspect — favorable for dramatic intimate-circle conflict-resolution.' },
  { name: 'Rahu aspect Rahu in 6th house : Starts', description: 'Conflict-victory window opens. Sharpen the strategy.' },
  { name: 'Rahu aspect Rahu in 6th house : Exact', description: 'Peak conflict-victory day. Win the family-system case.' },
  { name: 'Rahu aspect Rahu in 6th house : Ends', description: 'Conflict-victory window closes. Lock in the wins.' },
  { name: 'Rahu aspect Ketu in 12th house', description: 'Nodal axis obsession on dissolution. Foreign relocation, hidden-romance pursuits.' },
  { name: 'Rahu aspect Ketu in 12th house : Starts', description: 'Dissolution-obsession window opens. Beware spectacular hidden offers.' },
  { name: 'Rahu aspect Ketu in 12th house : Exact', description: 'Peak dissolution-obsession day. Verify integrity.' },
  { name: 'Rahu aspect Ketu in 12th house : Ends', description: 'Dissolution-obsession window closes. Keep dharmic foreign gains.' },
  { name: 'Ketu aspect Sun in 9th house', description: 'Dharma detachment. Old shared values feel finished; foreign-fortune ambitions cool.' },
  { name: 'Ketu aspect Sun in 9th house : Starts', description: 'Dharma-eclipse window opens. The pull to step away from old principles rises.' },
  { name: 'Ketu aspect Sun in 9th house : Exact', description: 'Peak dharma-eclipse day. The old guru-relationship dissolves quietly.' },
  { name: 'Ketu aspect Sun in 9th house : Ends', description: 'Dharma-eclipse window closes. Move forward leaner.' },
  { name: 'Ketu aspect Moon in 8th house', description: 'Transformation acceleration. Old chapters end abruptly; in-law cases dissolve.' },
  { name: 'Ketu aspect Moon in 8th house : Starts', description: 'Transformation-eclipse window opens. Prepare for fast endings.' },
  { name: 'Ketu aspect Moon in 8th house : Exact', description: 'Peak transformation-eclipse day. Old chapter ends abruptly.' },
  { name: 'Ketu aspect Moon in 8th house : Ends', description: 'Transformation-eclipse window closes. New chapter begins lean.' },
  { name: 'Ketu aspect Mercury in 10th house', description: 'Public-couple eclipse. Old joint-roles feel hollow; brand-couple identity gets stripped.' },
  { name: 'Ketu aspect Mercury in 10th house : Starts', description: 'Couple-eclipse window opens. Don\'t over-defend a joint role wanting to end.' },
  { name: 'Ketu aspect Mercury in 10th house : Exact', description: 'Peak couple-eclipse day. The joint role dissolves quietly.' },
  { name: 'Ketu aspect Mercury in 10th house : Ends', description: 'Couple-eclipse window closes. Move forward to a cleaner joint platform.' },
  { name: 'Ketu aspect Venus in 11th house', description: 'Deep purification of friendship. Friends drift; group rituals feel weightless; ambitions purify.' },
  { name: 'Ketu aspect Venus in 11th house : Starts', description: 'Friend-eclipse window opens. The network purifies.' },
  { name: 'Ketu aspect Venus in 11th house : Exact', description: 'Peak friend-eclipse day. Old friend drifts.' },
  { name: 'Ketu aspect Venus in 11th house : Ends', description: 'Friend-eclipse window closes. The clean-network is what remains.' },
  { name: 'Ketu aspect Mars in 5th house', description: 'Creative-romantic-authority eclipse. Old desire-objects feel hollow.' },
  { name: 'Ketu aspect Mars in 5th house : Starts', description: 'Romance-eclipse window opens. The fame-pull cools.' },
  { name: 'Ketu aspect Mars in 5th house : Exact', description: 'Peak romance-eclipse day. Old desire feels finished.' },
  { name: 'Ketu aspect Mars in 5th house : Ends', description: 'Romance-eclipse window closes. The new chapter begins quieter.' },
  { name: 'Ketu aspect Jupiter in 1st house', description: 'Identity-stripping. The wise-self in love feels empty. Sit; do not over-rebuild.' },
  { name: 'Ketu aspect Jupiter in 1st house : Starts', description: 'Self-eclipse window opens. The pull to step away rises.' },
  { name: 'Ketu aspect Jupiter in 1st house : Exact', description: 'Peak self-eclipse day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu aspect Jupiter in 1st house : Ends', description: 'Self-eclipse window closes. Move forward leaner.' },
  { name: 'Ketu aspect Saturn in 2nd house', description: 'Detachment from joint-finance. Income-conversations feel meaningless.' },
  { name: 'Ketu aspect Saturn in 2nd house : Starts', description: 'Resource-eclipse window opens. The income-meaning evaporates.' },
  { name: 'Ketu aspect Saturn in 2nd house : Exact', description: 'Peak resource-eclipse day. Income feels meaningless. Sit.' },
  { name: 'Ketu aspect Saturn in 2nd house : Ends', description: 'Resource-eclipse window closes. The slow rail still runs underneath.' },
  { name: 'Ketu aspect Rahu in 6th house', description: 'Nodal axis eclipse on intimate-conflict. Old family-feuds dissolve without victory.' },
  { name: 'Ketu aspect Rahu in 6th house : Starts', description: 'Conflict-eclipse window opens. Old enmities cool.' },
  { name: 'Ketu aspect Rahu in 6th house : Exact', description: 'Peak conflict-eclipse day. The old rival sibling drops out.' },
  { name: 'Ketu aspect Rahu in 6th house : Ends', description: 'Conflict-eclipse window closes. The clean board is what remains.' },
  { name: 'Ketu aspect Ketu in 12th house', description: 'Ketu return aspect on its own placement — foreign, devotional dissolution at peak.' },
  { name: 'Ketu aspect Ketu in 12th house : Starts', description: 'Dissolution-return window opens. The foreign-pull rises.' },
  { name: 'Ketu aspect Ketu in 12th house : Exact', description: 'Peak dissolution-return day. The pilgrimage or retreat lands.' },
  { name: 'Ketu aspect Ketu in 12th house : Ends', description: 'Dissolution-return window closes. Move forward leaner.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} relationship] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
