// db/seed_career_virgo.js
//
// Per-ascendant fill-in seed for the **career** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own — 11L in 11H)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga, yogakaraka)
//     Venus=7th (Pisces, exalted — Malavya Yoga, 2L+9L Dhana-Dharma)
//     Mars=8th (Aries, own)  Jupiter=4th (Sagittarius, own — Hamsa Yoga, 4L+7L)
//     Saturn=5th (Capricorn, own — 5L+6L)  Rahu=9th (Taurus)  Ketu=3rd (Scorpio)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose career-specific interpretations, then run:
//
//   node db/seed_career_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./career');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'Your mind is the asset, and the body is its precision instrument. The market pays for surgical clarity — analyst, researcher, engineer, editor, doctor, scientist, auditor, strategist, technical-writer, code architect, craft specialist. The full-stack thinker who actually ships is rare; you are wired to be that. Personal effort translates directly into status because the same engine rules both self and the public profile. Detail-obsession reads as professionalism, not pedantry. The shadow: perfectionism that delays the release indefinitely. Ship the 90% draft; the 100% never lands. Also watch the body — overwork on a thin nervous system burns out the very instrument the career depends on.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'Money and family-finance arrive through the partner, the spouse, and the principal client. The contract closes because the relationship is warm. Industries: advisory, luxury services, hospitality at the principal-relationship tier, fashion partnership, design studios with co-principal, art dealing, wedding-or-couples-craft, finance-for-relationships. Wealth here is exalted — the spouse is also a teacher (9L), so partnership has a dharma dimension that compounds across years. The shadow: comfort-of-the-relationship that quietly disincentivizes the harder ask; do not let the warmth of the deal soften the price.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'Communication, content, and bold short-burst effort feed the transformation engine. Writing about crisis, research with a sharp edge, journalism on hidden subjects, sales of insurance/equity/inheritance products, technical sales of high-stakes tools, investigative analysis. Sibling-channel deals carry surgical weight here. The shadow: aggressive notes that detonate rather than open — temper the message before sending it into the 8th-house pressure zone.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'The home is the throne room, and wisdom guards the gate. Real estate, family-business succession, education-from-home, mother-line teaching, hospitality with an ethical-lineage signature, work-from-home founder roles, traditional-knowledge-led ventures. Hamsa Yoga in the 4th means the home itself is generative — a property purchase often doubles as a career inflection. The most stable chapters root in land, building, or the family seat. The shadow: over-protective parents (or your inner parent) overruling the riskier dharma move; honor lineage but choose the path yourself.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Creative output is structured, disciplined, slow-cooked, and serious. Long-form research, doctoral work, institutional curriculum design, board-game architecture, classical performance, traditional craft mastery, regulatory-creative hybrids, financial-modeling-as-art, slow-publishing. The 5th here is creative work that compounds across decades, not viral seasons. Saturn-own-in-5 also means children-and-mentees arrive late but stay loyal. The shadow: the inner critic that strangles the rough draft. Honor the discipline, but lower the gate occasionally.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'Your competitive edge is creative-system-building. Adversaries fall to the rigorous framework, the spreadsheet, the protocol, the methodology. Industries: regulatory consulting, audit-with-creative-leverage, education-as-competition, sport-coaching with system, legal frameworks, compliance design, performance-management. Daily routine carried like a discipline becomes the moat. The shadow: turning every relationship into a competition; in the 5th, the partner-and-child must be exempt from the audit.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Spouse and principal client arrive through the home, the family, the lineage. Family-business partner, in-laws as commercial allies, real-estate counterparties, mother-channel introductions to the anchor deal. Industries: family-office advisory, dynastic real estate, in-house consulting roles in family firms, education partnerships rooted in the home town. The 7L in 4H also means the deepest career chapters happen at home base, not in flashy capitals. The shadow: confusing the family\'s preferred partner with your own dharma\'s correct partner.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'Career is repeatedly transformed by crisis — and the crisis is the curriculum, not the punishment. Surgery, forensic work, insurance, life-and-death advisory, restructuring, M&A, tax-arbitration, oil-gas-mining, cyber-security, intelligence work, research into hidden mechanisms. Mars own in 8 means you are *built* to walk into the burning room and emerge with the system stabilized. Inheritance, severance, equity-event-driven gains route here. The shadow: thrill-seeking that mistakes adrenaline for dharma. The 8th rewards the disciplined surgeon, not the cowboy.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'Dharma and partner are fused. Your principal teacher will become your principal partner, or your partner will become your principal teacher — the channel is one. Industries: academic-and-spousal collaborations, dharma-led joint ventures, ethical-investment partnerships, foreign-spouse business, teaching-with-a-co-principal, wedding-counseling, couples-coaching with a doctrinal edge. The 9L exalted in 7 makes the foreign spouse / foreign teacher a real life path. The shadow: conflating partner-pleasure with dharma-truth; check whether the principle actually requires this person, or whether the comfort does.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'You *are* the brand. The 10th-lord in lagna means status is built through personal articulation, personal precision, personal showing-up. The exalted yogakaraka makes this the central career engine for life. Founder-architect, principal-consultant, public intellectual, head-of-craft, chief-research-officer, principal-engineer, lead-editor — the role-name almost always includes "principal" or "chief" by mid-career. Slow rise but irreversible. The shadow: identity so welded to the work that a career setback feels like an existential threat; build a self that exists outside the resume.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Wide network, friend-circles, alumni-and-team relationships, large gains. The 11L Moon own in own house = exceptional gains channel that runs on emotional-trust currency. Industries: alumni-led platforms, network-effect businesses, community-built products, bonus-pool roles, equity-vesting trajectories, advisory boards, cooperative ventures. Female friends, mother-figures, and emotionally-trusting peer groups are the central conduit. The shadow: emotional reactivity in group politics — the same channel that delivers gains can also deliver group-mood swings; protect your sleep on big-network weeks.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'The 12L in 12H makes loss a known geometry — foreign work, retreats, off-balance-sheet structures, sleep-economy, monasteries-as-clients, hospitals, charities, prisons, research-institutes, embassies. Light here is dimmed but lineage-aware: your father-figure or principal authority operates from the shadows, and you are wired the same way. Best chapters often happen abroad, in confidential mandates, or in dawn-hours of solitary work. The shadow: solar pride leaking into self-undoing — when the 12 fires, the ego-bruise is what burns out faster than the work; let it.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, the confidential / foreign / behind-the-scenes mandate carries the chapter. The retreat, the white-paper, the embassy posting, the off-balance-sheet structuring. Quiet authority in the shadow lane.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, the wide-network gains channel pays. Alumni introductions, community-led product wins, bonus-pool conversations, equity vesting events. The trust the team feels in you is liquid here.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, personal precision wins the day. Refresh the bio, lead the technical pitch, walk into the room as the principal-craftsman. The exalted yogakaraka is the dominant career key — most major status moves trace back to a Mercury-1H window.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, the home-and-lineage channel pays out. Real-estate decisions, family-business inflection, mother-line introductions to the anchor deal. Hamsa Yoga in 4 makes the home itself a wealth-generating asset.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, the surgical-crisis chapter opens. Restructuring, M&A, equity-event navigation, life-or-death advisory, forensic work, insurance close. Walk in calm, walk out with the system stabilized.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, slow creative discipline produces compounding output. The doctoral chapter, the long-form publication, the curriculum that becomes a standard, the institutional-creative role. Children/mentees arrive late but loyal.' },
  { name: 'Venus in 7th (Dispositor)', description: 'When this engine fires, the warm-partnership engine closes deals. Anchor client, spouse, principal collaborator carry the chapter. Exalted Venus 7H = the deepest income windows arrive through partnership, not solo work.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak personal-visibility window. Body radiates, the principal-craftsman framing lands. Best four-week window of the year for the founder declaration, the personal rebrand, the public mantle. Watch ego friction with father-figures.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on income, voice, family-finance. Negotiate the salary, record the talk, lock the family-money decision. Throat care matters; vocal-led work favored.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on writing, peers, short bursts. Ship the document, send the bold sales note, push the campaign sequence. Younger colleagues respond directly. Ketu-zone — the courage risks looking like over-detachment if uncalibrated.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home-throne. Real-estate decisions, family-business inflections, mother-line conversations, work-from-home founder moves all favored. Father-figures press their mark on lineage decisions.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on creative-discipline output. Best window for launching the long-form analysis, the curriculum, the doctoral milestone, the structured-creative product. Mentor-of-mentees roles light up.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on adversary-management, audit, regulatory work. Hard HR conversations, compliance filings, lawsuits you have postponed all favor the offensive now. Adversaries weaken.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on partnerships and public deals. Spouse and principal-client visibility peak. Sign the anchor partnership, demand JV terms, take the deal public. Venus territory — the deal closes warm.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in the transformation chamber. Career moves take surgical edge — succession, restructuring, equity-event navigation. Inheritance, severance matters surface. Mars own-territory — sharp execution rewarded.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma-mentor engine. Best window for international-stage talks, certifications, judicial proceedings, teacher-mentor moves. Rahu zone — unconventional teacher / foreign stage materializes.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility window. Best for launching the flagship initiative, demanding the title bump, leading the competitive pitch, accepting the chief-of-something role. Mercury-territory transited by Sun = the room reads you as principal-track.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on gains and wide-network zone. Bonus-pool conversations, equity true-ups, board invitations, alumni-network introductions. Moon-territory — the warmth of the network carries the win.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return through own sign in moksha house. Annual peak for confidential mandates, foreign work, retreats, white-papers, off-balance-sheet structuring. Quiet authority compounds. Best for next-year strategic drafts done alone.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of emotional charge on persona. The body wants to perform; channel into a precision-led move — the surgical pitch, the founder declaration, the principal-craftsman moment.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on income, voice, family-finance. Soft-spoken negotiations land; read the room before pricing.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on communication. Bold message, brave outreach. Ketu zone — the courage may tilt to detachment; calibrate the warmth back in.' },
  { name: 'Moon Transits the 4th House', description: 'Emotional pull to the home-throne. Mother-channel calls, real-estate read-outs, family-business pulse-check. Cook a real meal; the reset compounds.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative-discipline. The mind feels poetic but structured; capture the draft, the lyric, the rough framework. Saturn keeps it from tipping into froth.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict-management. The adversary may push the trigger; respond from documentation, not reaction.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on the partnership engine. Read the spouse / principal-client temperature before the meeting. Warm tone wins the day. Exalted Venus territory — the warmth is structural here.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on the transformation zone. Defer high-risk decisions two days. Old fears around chaos and crisis surface for processing.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma, teaching, foreign work. The mentor-call, the pilgrimage thought, the international-introduction draft. Rahu-zone — unconventional teacher signals.' },
  { name: 'Moon Transits the 10th House', description: 'Monthly career-pulse peak. Public reception is warm; senior-network read-outs favor you. Take the warm-toned client meeting.' },
  { name: 'Moon Transits the 11th House', description: 'Monthly home-engine peak (own-sign Moon territory). Reach out to the wide network — alumni, community, peer-trust circle. The gains channel runs warm.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; foreign and behind-the-scenes pull. Best for retreat planning, confidential drafting, dream-led strategy.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury return through own + exalted lagna. Peak self-articulation window of the year. Refresh bio, founder-story, personal pitch deck, the public-craftsman framing. Send the introduction emails. Most powerful Mercury transit for this chart.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Renegotiate the salary, write the family-finance plan, record the talk, pin the pricing.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s natural turf for short-burst communication. Peak window for content production, sales sequences, sibling-channel deals, journalism. Ketu zone — keep the message from drifting too detached.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-throne articulation. Real-estate paperwork, family-business memo, mother-channel correspondence, in-house technical documentation.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative-discipline analysis. Long-form research drafts, curriculum design, doctoral chapter completion, structured-publication production.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp adversary-management. Audit memos, litigation briefs, HR documentation, compliance filings — surgical-precision wins.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, JV memos, contract negotiations land cleanly. Send the partner the written framework.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-zone articulation. Restructuring memos, succession plans, insurance filings, forensic reports, equity-event documentation.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-and-teaching articulation. Course outlines, lecture decks, certification applications, international-publication submissions.' },
  { name: 'Mercury Transits the 10th House', description: 'Mercury through 10L\'s domain — peak career-articulation window. Promotion memos, board decks, principal-craftsman submissions, public lectures with status weight.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Alumni-newsletter writing, community-platform posts, board-advisory memos, bonus-negotiation framing.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp confidential-mandate articulation. White papers, off-balance-sheet memos, retreat-strategy drafts, foreign-correspondence work.' },
  { name: 'Venus Transits the 1st House', description: 'Personal-magnetism window. Body, voice, taste, presence radiate. Signed contracts feel warm; client-facing meetings convert.' },
  { name: 'Venus Transits the 2nd House', description: 'Venus through own-territory income/voice zone. Family-finance windfall windows, vocal performance favored, asset acquisition with grace.' },
  { name: 'Venus Transits the 3rd House', description: 'Charm on communication and short-burst effort. The warm message lands. Ketu zone — the warmth may slip into vagueness; keep the ask sharp.' },
  { name: 'Venus Transits the 4th House', description: 'Venus through the home-throne. Real-estate beauty decisions, mother-channel warmth, family-business soft-power moves.' },
  { name: 'Venus Transits the 5th House', description: 'Charm on creative-discipline. The structured craft picks up a graceful surface — the academic paper that reads beautifully, the regulation drafted with style.' },
  { name: 'Venus Transits the 6th House', description: 'Charm in conflict zone. The mediation, the diplomatic resolution, the gracefully-handled HR fight. Warmth disarms the adversary.' },
  { name: 'Venus Transits the 7th House', description: 'Venus return through own exalted 7th. Monthly peak partnership window. Sign the anchor deal, marry the spouse, lock the principal client. Most important Venus transit of the year for this chart.' },
  { name: 'Venus Transits the 8th House', description: 'Charm in transformation zone. Severance negotiated warmly, restructuring with humanity, insurance closed gracefully, M&A done with relational care.' },
  { name: 'Venus Transits the 9th House', description: 'Charm on dharma-engine. Foreign-stage talks land warmly, ethical-investment intros, teacher-mentor warmth, judicial proceedings unexpectedly graceful.' },
  { name: 'Venus Transits the 10th House', description: 'Charm on career visibility. Board-level diplomacy, principal-craftsman public moments with warmth, status-with-grace moves.' },
  { name: 'Venus Transits the 11th House', description: 'Charm in wide-network gains zone. Bonus pool warm-conversations, alumni introductions land, community-product launches gain affection.' },
  { name: 'Venus Transits the 12th House', description: 'Charm in moksha zone. Foreign-warmth, confidential-collaboration, retreat-relationships, off-grid-ventures find their unlikely funding.' },
  { name: 'Mars Transits the 1st House', description: 'Surge of personal force on the precision-instrument body. Best for launching the demanding push, the surgical move, the bold founder action. Burnout risk — temper with rest.' },
  { name: 'Mars Transits the 2nd House', description: 'Force on income, voice, family-finance. Aggressive pricing, vocal demands, family-money confrontations. Avoid sharp tones in commerce.' },
  { name: 'Mars Transits the 3rd House', description: 'Force on communication. Bold campaigns, sales pushes, content sprints. Ketu-zone — the bluntness can land cold; check warmth.' },
  { name: 'Mars Transits the 4th House', description: 'Force on home-throne. Property-related disputes, family-business friction, real-estate aggressive negotiation. Keep the temperature low at home.' },
  { name: 'Mars Transits the 5th House', description: 'Force on creative-discipline. The push to ship the long-form work; the competitive contest; the children-mentees ambition. Saturn-territory keeps it disciplined.' },
  { name: 'Mars Transits the 6th House', description: 'Force on adversary-management. Best window for offensive action — the lawsuit, the audit, the firing, the regulatory filing. Adversaries break under pressure.' },
  { name: 'Mars Transits the 7th House', description: 'Force on partnership zone. Sharp negotiations, demanding contract pushes — but watch friction with spouse / principal client. Cool the temperature before signing.' },
  { name: 'Mars Transits the 8th House', description: 'Mars through own territory — surgical-execution window. The crisis you walk into resolves under your hand. M&A, restructuring, forensic, equity events. Most powerful Mars transit for this chart.' },
  { name: 'Mars Transits the 9th House', description: 'Force on dharma-engine. Aggressive teaching, doctrinal disputes, foreign-stage assertions, certification battles. Rahu zone — unconventional doctrine fights surface.' },
  { name: 'Mars Transits the 10th House', description: 'Force on career visibility. Aggressive promotion pushes, competitive pitches, principal-track demands. The room responds to sharpness here.' },
  { name: 'Mars Transits the 11th House', description: 'Force on wide-network gains. Aggressive bonus negotiations, board-position pushes, alumni-network mobilizations. Watch group-friction with peers.' },
  { name: 'Mars Transits the 12th House', description: 'Force in moksha zone. Foreign-front aggressive moves, confidential mandate sharpness, hospital/prison-related work, behind-the-scenes operations. Keep the body protected.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual wisdom-on-self window (~12 months). The body, the personal brand, the public-craftsman pick up dharma weight. Best year-block for personal-credential moves, lineage-anchored rebranding.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom on income, voice, family-finance. Year-block to expand voice-led income, refine family-finance ethics, take on dharma-aligned wealth structures.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on communication. Year-block to publish the book, launch the content-channel-with-doctrine, formalize the writing practice. Ketu-zone — keep the doctrine grounded.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter return through own + Hamsa-Yoga territory. The single most important Jupiter transit of the chart. Year-block for property purchase, family-business inflection, mother-line teaching, lineage-anchored real-estate moves. Almost every major home and family decision compounds during this window.' },
  { name: 'Jupiter Transits the 5th House', description: 'Wisdom on creative-discipline. Year-block for doctoral defense, curriculum institutionalization, mentor-of-mentees roles, structured-creative leadership.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom in conflict-zone. Year-block where adversaries weaken, debts repay themselves, regulatory clarity arrives. Health regimens institutionalize.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom on partnership. Year-block for marriage, JV consolidation, anchor-client dharma-alignment, foreign-spouse / foreign-teacher partnerships.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom in transformation zone. Year-block for inheritance, equity events, succession planning, occult-research royalties, life-insurance and longevity advisory.' },
  { name: 'Jupiter Transits the 9th House', description: 'Wisdom in dharma-territory. Year-block for foreign-stage credentialing, judicial vindication, teacher-track elevation, pilgrimage-related career moves.' },
  { name: 'Jupiter Transits the 10th House', description: 'Wisdom on career visibility. Year-block for the principal-of-something appointment, the formal lineage transfer, the senior-track elevation. Reading-room reads you as elder-track.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom in wide-network gains zone. Year-block for cooperative-platform leadership, alumni-network institutionalization, bonus-equity ethical structures, dharma-led community gains.' },
  { name: 'Jupiter Transits the 12th House', description: 'Wisdom in moksha zone. Year-block for retreat-residencies, foreign-research mandates, monastery-as-client work, white-paper publications. Light-in-the-shadow productivity.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn on the precision-instrument body. ~2.5-year discipline-on-self chapter. Slow strip-down of inflated self-image; lean, principled re-emergence. Body weight and posture restructured. Public-craftsman framing tightens.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn on income/voice/family-finance. Lean years on the family balance sheet; structural rather than punitive — long-term wealth foundations laid. Voice deepens.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn on communication. Rigorous editing of the public message; sibling-channel relationships restructure. Ketu-zone — the loneliness during this period can be productive if held.' },
  { name: 'Saturn Transits the 4th House', description: 'Saturn on the home-throne. Heavy chapter for property, mother\'s health, family-business — but also the chapter where the *real* foundations of the home are built. Hamsa-Yoga territory becomes structural, not just ceremonial.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn return through own 5H — the disciplined-creative chapter of the life. ~2.5-year peak for institutional curriculum, doctoral milestone, long-form publication, structured-mentor work. The deep professional moat is laid here.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn on adversary/health/debt. Long grind chapter — but adversaries deplete themselves under your patience. Health regimens become protocol-grade. Debt structures lock in cleanly.' },
  { name: 'Saturn Transits the 7th House', description: 'Saturn on partnership. Marriage / anchor-client tested for structural soundness. Weak partnerships fall away; sound partnerships harden into multi-decade ones. Exalted Venus 7H softens the lesson.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn on transformation zone. Heavy-but-gold chapter for restructuring, succession, inheritance, equity-event navigation. Walk slow; the surgical work pays.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn on dharma. Long-arc chapter for credentialing, judicial proceedings, doctrinal restructure, teacher-lineage rework. Foreign-stage authority deepens by inches, not leaps.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on career-visibility — the structural-status chapter. ~2.5 years of slow, irreversible promotion to the principal-track. The flashy peers rotate; you remain.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn on wide-network gains. Structural rebuild of the alumni / community / board-advisory channels. Some friends fall away; deep ones lock in for life.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn on moksha-zone. Heavy chapter for foreign work, confidential mandates, retreat-residency, hospital/prison-related service. Body needs more sleep; honor it.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu on persona. ~18-month chapter of unconventional self-presentation. Public-craftsman framing gets a foreign / disruptive twist. Risk: identity-overreach. Reward: breakthrough visibility.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu on income/voice/family-finance. Speculative income windows, foreign-currency exposure, unconventional vocal-led ventures. Watch for too-good-to-be-true family-money offers.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on communication. Foreign / disruptive content channels, viral writing, unconventional sibling-network deals. Ketu-zone tension — anchor each disruptive move in disciplined craft.' },
  { name: 'Rahu Transits the 4th House', description: 'Rahu on home-throne. Foreign-property windows, unconventional family-business pivots, mother-line disruption. Hamsa-Yoga territory amplified but de-conventionalized.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu on creative-discipline. Speculative-creative windows, foreign-curriculum ventures, viral-research opportunities, unconventional mentor-channels. Saturn-territory grounds what would otherwise be froth.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu on adversary-zone. Unconventional enemies, foreign litigation, viral conflict. Strong Rahu in 6 typically defeats adversaries — the chaos is on their side, not yours.' },
  { name: 'Rahu Transits the 7th House', description: 'Rahu on partnership. Foreign-spouse / foreign-anchor-client window, unconventional JV structures. Exalted Venus 7H absorbs Rahu well — the unusual partner often turns out to be the right one.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on transformation zone. Speculative-equity events, unconventional inheritance, foreign restructuring, occult-research royalties. Mars-territory + Rahu = high-velocity transformation; harness, do not chase.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu return through 9H. ~18-month foreign-dharma chapter — unconventional teacher, foreign credentialing, disruptive doctrine. The unconventional path is your path during this window.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu on career-visibility. Sudden public-craftsman elevation through disruptive channels — viral case study, foreign-stage breakthrough, unconventional senior appointment.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu on wide-network gains. Foreign-friend windfalls, viral community moves, unconventional board appointments, speculative bonus structures.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu on moksha-zone. Foreign-retreat residencies, confidential disruptive mandates, off-balance-sheet speculative structures. Light-in-the-shadow Rahu can deliver large but opaque gains; verify.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu on persona. Detachment from public visibility; identity-stripping chapter. The ego-self thins out — but the principal-craftsman essence underneath is what remains. Useful for sabbatical thinking.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu on income/voice. Detachment from family-money attachment; voice may go quieter for a stretch. Don\'t monetize the silence.' },
  { name: 'Ketu Transits the 3rd House', description: 'Ketu return through own territory. Detachment from communication noise; sibling-channel disengagement. Best for solitary research; worst for marketing campaigns.' },
  { name: 'Ketu Transits the 4th House', description: 'Ketu on home-throne. Detachment from family-business / mother-line attachment. Property decisions feel oddly indifferent; defer the big purchase.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu on creative-discipline. Detachment from validation-seeking creative work. Saturn-territory + Ketu = unusually pure-form output; the work nobody asked for becomes the work that matters.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu on adversary-zone. Detachment from old grievances; the enemies you thought mattered evaporate. Unprocessed health issues may surface for resolution.' },
  { name: 'Ketu Transits the 7th House', description: 'Ketu on partnership. Detachment from anchor-client / spouse warmth; defer the big partnership signing if possible. Exalted Venus 7H usually softens the lesson.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu on transformation zone. Detachment from crisis-thrill; the inheritance / severance / equity event arrives but feels oddly muted. Document carefully.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on dharma. Detachment from doctrinal certainty; the old teacher-track may stop fitting. Useful sabbatical from credentialing.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu on career-visibility. Detachment from status-attachment; the promotion that arrives feels strangely unsatisfying — useful signal that the next chapter is internal.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu on wide-network gains. Detachment from group-validation; some friends drift away. The alumni-channel quiets; trust the silence.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu on moksha-zone. Detachment-on-detachment — deep retreat months, foreign-solitude windows, monastery-as-client work that asks nothing of the ego.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar light on persona — body warms, public visibility tightens. Best for taking the founder photo, the principal-craftsman framing, the personal pitch deck refresh.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Solar approach to lagna. Polish the public-craftsman framing now; the spotlight is rising.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Today the spotlight peaks. Make the founder declaration, take the public mantle, walk into the room as principal.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Light fades from persona. Consolidate the visibility gains; lock the assets behind the public moment.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar light on career-MC. Public-status visibility window — board-level moves, principal-craftsman appointments, senior-track recognition.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Solar approach to MC. Prep the senior-track move; the room is about to read you brighter.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Today the public-status spotlight peaks. Pitch the principal role, demand the title, take the senior platform.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Solar light fades from MC. Lock the recognition; document the senior-track move.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Body wants warmth; client-facing meetings benefit from softer tone.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional approach to lagna. Prep softer outreach, warm-toned messages.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Today the persona runs warm. Take the relationship-driven meeting, send the warm pitch.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional light fades. Consolidate warm-channel relationships built today.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-status. Public visibility benefits from warm, relational tone.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Approach phase. Warm up the senior-track relationships ahead of the public moment.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Today the public-status read runs warm. Lead with relational warmth in the senior meeting.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Warmth fades from MC. Lock the warm-status relationships built today.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury on persona — articulation peak. Bio refresh, founder-story polish, principal-craftsman pitch all favored.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Approach phase. Draft the personal pitch deck, the bio update.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Today the precision-articulation peaks. Ship the founder-story, send the introductions, deliver the technical pitch.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mercury fades from persona. Lock the articulation polish into permanent assets.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on public-status — articulation in senior-track lane. Board decks, principal-craftsman submissions, senior-platform talks.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Approach. Draft the board deck, the senior-track memo.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Today senior-track articulation peaks. Submit the board deck, deliver the senior-platform talk.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Mercury fades from MC. Lock the senior-track articulation into the organizational record.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Charm on persona. Body radiates; client meetings convert; the warm pitch lands.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep the warm-pitch sequence, the relationship-led outreach.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Today the personal-charm signal peaks. Sign the warm contracts; take the camera moments.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm fades from persona. Lock the warm-channel relationships built today.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Charm on public-status. Board-level diplomacy, principal-craftsman warmth, senior-track grace moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Approach. Soften the senior-track outreach.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Today senior-track charm peaks. Take the board-level relational meeting.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Charm fades from MC. Lock the senior-track warmth into formal alliances.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Force on persona. Bold pushes, demanding pitches, sharp founder moves favored — but watch burnout on the precision-instrument body.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep the demanding push; gather force.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Today force on persona peaks. Make the bold demand, send the sharp founder note. Body needs rest tonight.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Force fades from persona. Lock the gains from the bold push.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Force on public-status. Aggressive promotion pushes, competitive senior-track demands. Watch friction with current authority.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Approach. Gather force for the senior-track push.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Today public-status force peaks. Demand the title, deliver the competitive pitch.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Force fades from MC. Lock the senior-track gains; cool the friction with current authority.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom on persona. Lineage-anchored personal-brand moves, dharma-aligned founder framing, ethical-craftsman positioning.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Approach. Polish the dharma-aligned framing of the public-craftsman.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Today wisdom on persona peaks. Take the lineage photo, deliver the dharma-aligned founder talk.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Wisdom fades. Lock the lineage-anchored personal-brand gains.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Wisdom on public-status. Senior-track elevation through dharma-aligned channels — the principled appointment, the ethical-leadership recognition.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Approach. Position the senior-track move as dharma-aligned.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Today senior-track dharma-elevation peaks. Take the principled appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Wisdom fades from MC. Lock the dharma-aligned status into formal records.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Discipline on persona. Strip-down of inflated self-image; lean, principled re-emergence. Public-craftsman framing tightens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Approach. Begin the personal discipline cycle — body, posture, public framing.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Today discipline-on-persona peaks. Make the lean, principled public statement.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Discipline phase closing. Lock the leaner, more-principled public framing.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Discipline on public-status. Slow, structural, irreversible promotion to senior track. Flashy peers rotate; you remain.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Approach. Begin the structural senior-track positioning.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Today structural-status peak. Take the slow-but-permanent promotion.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Discipline phase closing. The structural senior-track is in place.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Rahu on persona. Unconventional / foreign / disruptive personal-brand moves. Risk: identity-overreach. Reward: breakthrough visibility.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Approach. The unconventional persona-pivot is gathering.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Today disruptive-persona peak. Make the unconventional public-brand move.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu fades. Decide which disruptive elements to keep, which to drop.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Rahu on public-status. Sudden, unconventional senior-track elevation — viral case study, foreign-stage breakthrough, disruptive appointment.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Approach. The unconventional senior-track move is gathering.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Today disruptive-status peak. Take the unconventional appointment, ride the viral moment.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu fades from MC. Lock the disruptive gains; document the unconventional path.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Ketu on persona. Detachment from public visibility; sabbatical-thinking favored. The ego-self thins; the principal-craftsman essence underneath remains.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Approach. The pull toward solitude is rising.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Today persona-detachment peaks. Best for solitary work, worst for self-promotion.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Detachment fading. Re-emerge with what survived the silence.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Ketu on public-status. Detachment from status-attachment; the promotion arrives muted. Useful signal that the next chapter is internal.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Approach. Status-attachment unwinds.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Today status-detachment peaks. The recognition feels strangely empty — useful information.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Detachment fading. The next status-chapter starts forming on internal grounds.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural transformation in 5L+6L Saturn territory. Career-discipline architecture rebuilt from the foundation. Curriculum, doctrine, framework — what survives this conjunction becomes the multi-decade asset.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Pressure builds on Saturn-territory. Begin documenting the structural architecture you want to preserve.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Today the generational rebuild peaks. The disciplined-creative framework is being re-cast at depth.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Pressure releases. The new structural architecture is in place; build outward from it.' },
  { name: 'Uranus conjunct Venus', description: 'Disruptive innovation on the partnership / income / dharma engine (Venus 2L+9L exalted in 7H). Spouse, anchor-client, principal-teacher relationship undergoes sudden re-architecture. The unconventional partner becomes the right partner.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruptive pressure builds on partnership. The conventional model starts cracking.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Today the partnership / dharma rewiring peaks. The unconventional partner declaration lands.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption settling. The new partnership architecture is in place — radically different from the old.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar return through the 12th. Annual peak for confidential mandates, foreign work, retreat-residencies, white-papers. Quiet authority compounds.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Solar return approaching. Prep the year-block strategic drafts.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Solar return peak. Take the new-year strategic drafts done alone.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Solar return closing. The shadow-lane strategy is on record.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar light on wide-network gains. Bonus-pool conversations, equity true-ups, board invitations, alumni introductions warm up.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Approach. Network-spotlight gathering.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Today network-spotlight peaks. Take the alumni call, the bonus-pool meeting.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Spotlight fades. Lock the network-recognition.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar light on the yogakaraka. Annual peak for personal-craftsman visibility — the founder photo, the principal-of-X declaration.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka spotlight gathering.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Today yogakaraka spotlight peaks. Make the founder declaration; take the principal-of-craft mantle.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Spotlight fades. Lock the principal-craftsman appointment.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar light on partnership. Visibility through contracts; spouse and principal-client dynamics light up.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Approach. Partnership-spotlight gathering.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Today partnership-spotlight peaks. Sign the anchor partnership; demand the JV terms.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Spotlight fades. Lock the public partnership.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar light on the surgical-transformation engine. Career decisions take surgical edge — succession, restructuring, equity-event navigation.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Approach. Transformation-spotlight gathering.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Today crisis-spotlight peaks. Lead the restructuring; close the equity event.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Spotlight fades. Lock the transformation gains.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar light on the home-throne / Hamsa. Real-estate decisions, family-business inflections, mother-line conversations all favored.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne spotlight gathering.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-spotlight peaks. Make the property purchase, the family-business move.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Spotlight fades. Lock the home-throne move.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar light on the disciplined-creative engine. Best for launching the long-form analysis, the curriculum, the doctoral milestone.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Approach. Creative-discipline spotlight gathering.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H spotlight peaks. Ship the long-form work; deliver the curriculum.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Spotlight fades. Lock the structured-creative output.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Solar light on the foreign-dharma engine. International-stage talks, certifications, judicial proceedings, teacher-mentor moves.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma spotlight gathering.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H spotlight peaks. Take the foreign-stage talk, the unconventional-teacher move.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Spotlight fades. Lock the foreign-dharma recognition.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Solar light on the detached-communication engine. The brave solitary-research push gets quiet recognition.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research spotlight gathering.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H spotlight peaks. Publish the solitary research; the right people see it.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Spotlight fades. The solitary-research output stands on record.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on the moksha-solar engine. Inwardness, foreign-pull, confidential-relationship warmth.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Approach. The shadow-lane warmth gathers.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Today 12H emotional warmth peaks. Take the confidential warm-toned meeting.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Warmth fades. The shadow-lane bond is consolidated.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon return — the wide-network gains channel runs warm. Reach out to alumni, community, peer-trust circle. The trust the team feels in you is liquid.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Moon return approaching. Network-warmth rising.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Moon return peak. Take the warm alumni call, the community-leadership meeting.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Moon return closing. The warm network gains are on record.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional charge on the yogakaraka. The body wants warmth in the principal-craftsman framing; soft-toned client meetings.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Approach. Personal-warmth rising.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Today personal-warmth peaks. Take the warm client meeting; send the soft-toned founder note.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Warmth fades. Lock the warm-channel relationships.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on partnership. Spouse / principal client temperature read; warm tone wins the day.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Approach. Partnership-warmth rising.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Today partnership-warmth peaks. Take the warm-toned anchor meeting.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Warmth fades. Lock the warm-partner alliance.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on the transformation zone. Defer high-risk decisions two days. Old fears around chaos surface for processing.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Approach. Crisis-emotion rising.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Today crisis-weight peaks. Defer signings; let the fear pass.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Weight fades. Re-engage the transformation work.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional charge on the home-throne / Hamsa. Mother-channel warmth peaks; family-business warm-pulse check.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Approach. Home-warmth rising.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Today home-warmth peaks. Cook the real meal, take the mother\'s call.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Warmth fades. The home-bond is consolidated.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional charge on the disciplined-creative engine. The structured-creative work picks up emotional warmth; the curriculum gains heart.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Approach. Creative-warmth rising.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Today creative-warmth peaks. Add heart to the rigorous output.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Warmth fades. The warm-rigorous work is on record.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional charge on the foreign-dharma engine. The pilgrimage thought, the international-introduction draft, the unconventional-teacher warmth.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma warmth rising.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H warmth peaks. Make the foreign-teacher reach-out.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Warmth fades. The foreign-dharma bond is on record.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Emotional charge on the detached-communication engine. Solitary-research mood; the brave message that does not need an audience.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research warmth rising.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H warmth peaks. Write the brave message; do not need a reply.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Warmth fades. The solitary-research warmth is locked.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Articulation on the moksha-solar engine. Confidential / foreign mandate documentation; white papers; off-balance-sheet memos.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane writing picks up pace.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Today shadow-lane articulation peaks. Ship the white paper, the confidential memo.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Articulation fades. The shadow-lane document is locked.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Articulation on the wide-network gains. Alumni newsletter, community-platform posts, board-advisory memos, bonus-negotiation framing.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Approach. Network-articulation gathers.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Today network-articulation peaks. Send the alumni newsletter, post the community update.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Articulation fades. The network-message is on record.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury return — the most important communication aspect of the chart. Bio refresh, founder-story, principal-craftsman pitch deck, technical authority articulation.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Mercury return approaching. Prep the personal-articulation refresh.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Mercury return peak. Ship the bio, the founder-story, the principal-craftsman framing.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Mercury return closing. The yogakaraka articulation is locked.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Articulation on partnership. Term sheets, JV memos, contract negotiations land cleanly. Send the partner the written framework.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Approach. Partnership-articulation gathers.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Today partnership-articulation peaks. Ship the term sheet, the JV memo.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Articulation fades. Partnership documents are on record.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Articulation on transformation. Restructuring memos, succession plans, insurance filings, forensic reports.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Approach. Transformation-articulation gathers.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Today crisis-articulation peaks. Ship the restructuring memo, the succession plan.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Articulation fades. The transformation document is locked.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Articulation on the home-throne / Hamsa. Real-estate paperwork, family-business memo, mother-channel correspondence, lineage-anchored documentation.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne articulation gathers.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-articulation peaks. Ship the real-estate doc, the family-business memo.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Articulation fades. The home-throne document is on record.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Articulation on the disciplined-creative engine. Long-form research drafts, curriculum design, doctoral chapter completion, structured-publication production.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-creative articulation gathers.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H articulation peaks. Ship the doctoral chapter, the curriculum module.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Articulation fades. The disciplined-creative document is locked.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Articulation on the foreign-dharma engine. Foreign-publication submissions, international-lecture decks, certification applications, doctrinal essays.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma articulation gathers.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H articulation peaks. Submit the foreign-publication piece.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Articulation fades. The foreign-dharma submission is on record.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Articulation on the detached-communication engine. Solitary research writing, lineage-content production without audience-pressure, deep-research notes.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research writing gathers.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H articulation peaks. Ship the lineage-research piece nobody asked for.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Articulation fades. The solitary-research piece stands.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Charm on the moksha-solar engine. Foreign-warmth, confidential-collaboration, retreat-relationships, off-grid-ventures find their funding.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane warmth gathering.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Today Venus-on-12H-Sun peaks. Take the warm confidential meeting; close the off-balance-sheet venture.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Charm fades. The shadow-lane warmth is locked.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Charm on the wide-network gains. Bonus-pool warm conversations, alumni warm intros, community-product affection.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Approach. Network-charm gathering.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Today Venus-on-network peaks. Take the warm board call, the alumni-led intro.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Charm fades. Lock the warm-network bonds.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Charm on the yogakaraka. Personal-craftsman framing radiates; client meetings convert; the warm pitch lands.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka-charm gathering.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Today Venus-on-yogakaraka peaks. Sign the warm contracts; lead with personal-craftsman grace.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Charm fades. Lock the warm-channel relationships.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus return — the partnership engine peaks. Sign the anchor deal, marry the spouse, lock the principal client. Most important Venus aspect of the chart.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Venus return approaching. Prep the partnership move.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Venus return peak. Lock the structural partnership; the warmth is at its annual peak.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Venus return closing. The partnership is on record.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Charm on the surgical-transformation engine. Severance negotiated warmly, restructuring with humanity, M&A done with relational care.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Approach. Transformation-warmth gathering.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Today Venus-on-Mars-8H peaks. Negotiate the severance / inheritance / restructuring with grace.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Charm fades. The warm transformation is on record.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Charm on the home-throne / Hamsa. Real-estate beauty decisions, mother-channel warmth, family-business soft-power moves.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne charm gathering.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-charm peaks. Take the warm property meeting, the family-business gentle pivot.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Charm fades. Lock the warm home-throne move.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Charm on the disciplined-creative engine. The structured craft picks up a graceful surface — the academic paper that reads beautifully.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Approach. Creative-charm gathering.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Today Venus-on-Saturn-5H peaks. The rigorous-creative work picks up grace.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Charm fades. The graceful-rigorous output is on record.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Charm on the foreign-dharma engine. Foreign-stage talks land warmly, ethical-investment intros, teacher-mentor warmth.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma charm gathering.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Today Venus-on-Rahu-9H peaks. Take the warm foreign-stage talk; close the ethical-investment intro.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Charm fades. The warm foreign-dharma bond is on record.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Charm on the detached-communication engine. The warm message that does not need a reply; gentle-research correspondence.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research warmth gathering.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Today Venus-on-Ketu-3H peaks. Send the warm note that does not need a reply.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Charm fades. The gentle-research bond is on record.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Force on the moksha-solar engine. Confidential / foreign mandates get aggressive; the shadow-lane work sharpens.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Approach. The shadow-lane work gathers force.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Today force-on-12H-Sun peaks. Push the confidential / foreign mandate hard.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Force fades. The shadow-lane gains lock in.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Force on the wide-network gains channel. Aggressive bonus-pool moves, board-position pushes, alumni-network mobilization. Watch group-friction.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Approach. The network-gains push gathers.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Today force-on-network peaks. Demand the bonus, take the board position.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Force fades. The network gains are locked.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Force on the yogakaraka. Aggressive personal-craftsman moves — the demanding founder push, the sharp principal-pitch. Body needs rest after.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Approach. The principal-craftsman gathers force.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Today force-on-yogakaraka peaks. Make the bold founder demand.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Force fades. Lock the bold-pitch gains; rest.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Force on partnership. Sharp negotiations — but watch friction with spouse / principal client. Cool the temperature before signing.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Approach. Partnership friction gathers.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Today partnership-force peaks. Demand the JV terms; cool the relational temperature.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Force fades. Partnership consolidates on the new terms.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars return — surgical-execution peak. The crisis you walk into resolves under your hand. M&A, restructuring, forensic, equity events.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Mars return approaching. The transformation push gathers.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Mars return peak. Walk into the burning room and stabilize the system.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Mars return closing. The crisis-resolution is on record.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Force on the home-throne / Hamsa. Aggressive property push, family-business confrontation, mother-line negotiation. Keep the home temperature low.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne friction gathers.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Today force-on-Jupiter-4H peaks. The property / family negotiation reaches its sharp point.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Force fades. Home-throne consolidates.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Force on the disciplined-creative engine. Push to ship the long-form work; competitive contest; mentor-track confrontation.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Approach. The creative-discipline push gathers.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Today force-on-Saturn-5H peaks. Ship the long-form work; win the competitive contest.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Force fades. The disciplined-creative gains lock in.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Force on the foreign-dharma engine. Aggressive doctrinal disputes, foreign-stage assertions, certification battles.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Approach. The dharma-fight gathers.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Today force-on-Rahu-9H peaks. Take the doctrinal stand on the foreign stage.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Force fades. The foreign-dharma stand is on record.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Force on the detached-communication engine. Sharp solitary writing; fierce research without audience-pressure.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Approach. The fierce-solitary push gathers.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Today force-on-Ketu-3H peaks. Ship the fierce research that nobody is waiting for.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Force fades. The solitary-research push is consolidated.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom touches the moksha-solar engine. Confidential mandates take on dharma-weight; the foreign / behind-the-scenes posting picks up lineage value.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Approach. The shadow-lane work is gathering dharma weight.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Today wisdom on the 12th-Sun peaks. Lock the confidential / foreign mandate with dharma-aligned framing.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Wisdom fades. Document the dharma-weight gained in the shadow-lane.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on the wide-network gains channel. Alumni-network institutionalization, community-led product dharma, bonus-pool ethical structures.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Approach. The network-gains engine picks up dharma framing.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Today wisdom-on-network peaks. Anchor the wide-network engine in ethical structure.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Wisdom fades. Lock the dharma-aligned network architecture.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom touches the central-yogakaraka engine. Personal-craftsman framing picks up doctrinal weight; teaching, lineage, principal-of-X moves crystallize.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Approach. The principal-craftsman framing gathers lineage authority.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Today wisdom-on-yogakaraka peaks. Take the principal-of-craft mantle with lineage backing.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Wisdom fades. The lineage-anchored principal-craftsman role is locked in.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on the exalted partnership / dharma / wealth engine. Marriage with dharma-alignment, JV with ethical framing, anchor-client with teacher-quality.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Approach. Partnership picks up dharma weight.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Today wisdom-on-Venus-7H peaks. Lock the dharma-aligned partnership.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Wisdom fades. The principled partnership is consolidated.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on the surgical-transformation engine. Inheritance, restructuring, equity events take on dharma-weight; the crisis becomes the lineage moment.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Approach. The transformation chapter gathers dharma framing.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Today wisdom-on-Mars-8H peaks. Lock the dharma-aligned restructuring move.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Wisdom fades. The principled crisis-resolution is on record.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter return — the most important transit-aspect of the chart. Hamsa-Yoga territory amplified by Jupiter itself. Year-block for property purchase, family-business inflection, mother-line teaching.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Jupiter return approaching. Prep the home-throne move.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Jupiter return peak. Make the property purchase, the family-business move, the mother-line teaching declaration.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Jupiter return closing. The home-throne lineage move is consolidated.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on the disciplined-creative engine. Doctoral framework receives lineage-authority; curriculum institutionalizes; structured-creative leadership crystallizes.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-creative work picks up lineage weight.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Today wisdom-on-Saturn-5H peaks. Lock the institutional curriculum.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Wisdom fades. The disciplined-creative architecture is institutionalized.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Wisdom on the foreign-dharma engine. Unconventional teacher-track gains lineage authority; foreign credentialing materializes.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma move gathers framing.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Today wisdom-on-Rahu-9H peaks. Take the unconventional teacher-track move.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Wisdom fades. Foreign-dharma path is on record.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on the detached-communication engine. Solitary research, doctrinal writing without audience-pressure, lineage-content production.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research framing gathers.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Today wisdom-on-Ketu-3H peaks. Publish the lineage-rooted research that nobody asked for.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Wisdom fades. The solitary-research output is locked in.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Discipline on the moksha-solar engine. Long-arc confidential / foreign mandate; structural shadow-lane work.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane discipline cycle beginning.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Today Saturn-on-12H-Sun peaks. Lock the long-arc confidential mandate.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Discipline phase closing. Shadow-lane structure is in place.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Discipline on the wide-network gains. Structural rebuild of alumni / community / board-advisory channels.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Approach. Network-discipline cycle beginning.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Today Saturn-on-network peaks. Some friends fall away; deep ones lock in for life.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Discipline phase closing. The pruned network is structural.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Discipline on the yogakaraka. Slow, structural personal-craftsman re-architecture. Body weight, posture, public framing tighten.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka discipline cycle beginning.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Today Saturn-on-yogakaraka peaks. Make the lean, principled public statement.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Discipline phase closing. The leaner principal-craftsman is in place.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Discipline on partnership. Marriage / anchor-client tested for structural soundness. Weak partnerships fall away; strong ones harden.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Approach. Partnership-discipline cycle beginning.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Today Saturn-on-Venus-7H peaks. The structural partnership decision lands.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Discipline phase closing. The structurally-sound partnership is on record.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Discipline on the surgical-transformation engine. Heavy-but-gold restructuring, succession, inheritance, equity-event work. Walk slow.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Approach. Transformation-discipline cycle beginning.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Today Saturn-on-Mars-8H peaks. Lock the long-arc restructuring move.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Discipline phase closing. The structural transformation is in place.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Discipline on the home-throne / Hamsa. Heavy chapter for property, mother\'s health, family-business — but the *real* foundations of the home are built here.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne discipline cycle beginning.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Today Saturn-on-Jupiter-4H peaks. The structural home / family decision lands.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Discipline phase closing. The home-throne foundation is structural.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn return — the disciplined-creative chapter peak. Institutional curriculum, doctoral milestone, long-form publication, structured-mentor work. Multi-decade moat laid here.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn return approaching. The disciplined-creative chapter is gathering.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Saturn return peak. Lock the institutional curriculum, the doctoral framework.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn return closing. The multi-decade creative moat is in place.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Discipline on the foreign-dharma engine. Slow, structural foreign credentialing; doctrinal restructure; teacher-lineage rework.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma discipline cycle beginning.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Today Saturn-on-Rahu-9H peaks. Lock the foreign credential, the doctrinal framework.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Discipline phase closing. The foreign-dharma structure is in place.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Discipline on the detached-communication engine. Long-form solitary research, lineage-content production with multi-year cadence.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research discipline cycle beginning.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Today Saturn-on-Ketu-3H peaks. Lock the long-form solitary-research project.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Discipline phase closing. The lineage-research output is on record.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Disruption on the moksha-solar engine. Sudden foreign / confidential mandate; speculative shadow-lane work.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Approach. Disruptive shadow-lane move gathering.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Today Rahu-on-12H-Sun peaks. Take the unconventional foreign mandate.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Disruption fading. Lock or release the unconventional shadow-lane move.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Disruption on the wide-network gains. Foreign-friend windfalls, viral-community moves, unconventional board appointments.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Approach. Network-disruption gathering.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Today Rahu-on-network peaks. Ride the viral wave; take the unconventional board seat.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Disruption fading. Decide which gains to keep, which were ephemeral.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Disruption on the yogakaraka. Unconventional / foreign personal-brand pivot. Risk: identity-overreach. Reward: breakthrough visibility.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Approach. Disruptive principal-craftsman move gathering.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Today Rahu-on-yogakaraka peaks. Make the unconventional public-brand move.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Disruption fading. Lock the breakthrough; drop the overreach.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Disruption on partnership. Foreign-spouse / foreign-anchor-client window. Exalted Venus 7H absorbs Rahu well — the unusual partner often turns out to be the right one.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Approach. Disruptive partnership move gathering.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Today Rahu-on-Venus-7H peaks. The unconventional partner declaration lands.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Disruption fading. The unusual partnership is consolidated.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Disruption on the surgical-transformation engine. Speculative-equity events, unconventional inheritance, foreign restructuring, occult-research royalties.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Approach. Disruptive transformation gathering.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Today Rahu-on-Mars-8H peaks. Walk into the high-velocity transformation; harness, do not chase.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Disruption fading. The transformation gains are documented.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Disruption on the home-throne / Hamsa. Foreign-property windows, unconventional family-business pivots, mother-line disruption.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne disruption gathering.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Today Rahu-on-Jupiter-4H peaks. Take the foreign-property / unconventional home move.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Disruption fading. The unconventional home-throne move is consolidated.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Disruption on the disciplined-creative engine. Speculative-creative windows, foreign-curriculum ventures, viral-research opportunities.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Approach. Creative-disruption gathering.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Today Rahu-on-Saturn-5H peaks. Take the speculative-creative venture; ground in disciplined craft.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Disruption fading. The unconventional-creative output is on record.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Rahu return — the foreign-dharma engine peaks. Unconventional teacher, foreign credentialing, disruptive doctrine. The unconventional path is the path during this window.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return approaching. The foreign-dharma chapter is gathering.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Rahu return peak. Make the foreign-teacher / unconventional-doctrine move.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return closing. The unconventional dharma path is consolidated.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Nodal-axis activation on the communication channel. Foreign / disruptive content channels, viral writing, unconventional sibling-network deals.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Approach. Nodal-axis communication disruption gathering.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Today nodal-axis peak on Ketu-3H. The viral / foreign content move lands.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal pressure fading. The unconventional content gains are documented.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on the moksha-solar engine. The 12H Sun thins further — pure shadow-lane work, ego-free confidential mandates.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Approach. The 12H solar light dims.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Today detachment-on-12H-Sun peaks. Best for monastery-as-client and ego-free retreat work.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Detachment fading. The shadow-lane work consolidates.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on the wide-network gains. Some friends drift; the alumni channel quiets. The signal: prune the network.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Approach. Group-warmth fades.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Today network-detachment peaks. Trust the silence; some peers walk away.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Detachment fading. The pruned network reveals its real members.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on the yogakaraka. Identity-stripping window — the principal-craftsman essence underneath survives; the ego-frame thins.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Approach. Public-craftsman ego-frame loosens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Today yogakaraka-detachment peaks. Best for solitary craft; worst for self-promotion.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Detachment fading. The leaner principal-craftsman re-emerges.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on partnership. Defer the big partnership signing if possible. The warmth feels distant; trust the lull.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Approach. Partnership warmth dims.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Today partnership-detachment peaks. Defer signings; allow the relational lull.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Detachment fading. Partnership warmth returns.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on the surgical-crisis engine. The inheritance / severance / equity event arrives muted. Document; do not chase the adrenaline.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Approach. Crisis-thrill loosens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Today crisis-detachment peaks. The transformation event passes through quietly.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Detachment fading. The quiet transformation is on record.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on the home-throne / Hamsa engine. Family-business attachment loosens; mother-line conversation goes quiet. Defer the big property move.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne attachment loosens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-detachment peaks. The family-business decisions feel oddly indifferent.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Detachment fading. The home-throne re-engages on quieter terms.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on the disciplined-creative engine. Validation-seeking creative impulse fades; the work nobody asked for becomes the work that matters.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Approach. Validation-attachment loosens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Today creative-detachment peaks. Make the work that nobody is asking for.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Detachment fading. The pure-form creative output stands on its own.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Detachment on the foreign-dharma engine. Doctrinal certainty loosens; teacher-track may stop fitting. Sabbatical from credentialing.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Approach. Doctrinal certainty wobbles.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Today doctrine-detachment peaks. Useful sabbatical from teacher-track ambition.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Detachment fading. The teacher-track returns on different terms.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Ketu return — communication-detachment peak. Sibling-channel goes quiet; marketing impulse fades. Pure solitary research window.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Approach. Communication-attachment loosens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Ketu return peak. Drop the marketing; the research stands alone.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu return closing. Re-engage communication on lighter terms.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} career] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
