// db/seed_career_taurus.js
//
// Per-ascendant fill-in seed for the **career** category, scoped to a
// representative Taurus ascendant native with:
//   Ascendant: Taurus
//   Natal placements (sidereal Lahiri):
//     Sun=4th (Leo, own)  Moon=3rd (Cancer, own)  Mercury=5th (Virgo, own+exalted)
//     Venus=1st (Taurus, own — Malavya Yoga)  Mars=7th (Scorpio, own — Ruchaka Yoga)
//     Jupiter=11th (Pisces, own)  Saturn=10th (Aquarius, own — Sasa Yoga, yogakaraka)
//     Rahu=8th (Sagittarius)  Ketu=2nd (Gemini)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose career-specific interpretations, then run:
//
//   node db/seed_career_taurus.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./career');

const ASCENDANT = 'Taurus';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Venus ruler of the 1st House in the 1st House', description: 'You are the product. Your face, voice, taste, body, presence — these are the assets the market is paying for. Designer, curator, artist, beautician, brand-founder, hospitality principal, performer, luxury-goods entrepreneur, model, food critic — circuits where the personal aesthetic *is* the deliverable. Slow, deliberate moves; never hurry the deal. Beauty, comfort, and refinement are the language of trust here. The shadow: the same magnetism that earns can lull you into complacent comfort — the routines that feel pleasurable can quietly become the ceiling.' },
  { name: 'Mercury ruler of the 2nd House in the 5th House', description: 'Money speaks creatively. Income arrives through writing, performing, speculative-analytic work, teaching, content, course-creation, coaching, advisory on creative-investment, education with a public-stage edge. Family-money tilts up when you treat it as a creative project, not a chore. Voice and articulation are revenue-generating organs — invest in both. The shadow: speculation that runs ahead of the documentation. Track the books with the same precision you bring to the creative output.' },
  { name: 'Moon ruler of the 3rd House in the 3rd House', description: 'Your career rides on courageous communication, short bold bursts, sibling-style alliances, content distribution, sales calls, broadcasts. Writing, podcasts, journalism, scripting, account-management, customer-success, frontline pitch — you compound through repeated small acts of nerve. Younger peers and siblings carry your work further than senior endorsements do. The shadow: emotional weather flooding the message; sleep before sending the bold note when the day was hot.' },
  { name: 'Sun ruler of the 4th House in the 4th House', description: 'The home is the throne room. Real estate, family-business succession, domestic-comfort industries, hospitality, education-from-home, mother-related sectors, work-from-home founder roles all native. The most stable career chapters root in property — owning the workspace, the building, the land, or the house from which the work flows. The shadow: father-figures and home-elders project their unfinished ambitions onto you. Honor the lineage, but choose the dharma yourself.' },
  { name: 'Mercury ruler of the 5th House in the 5th House', description: 'Sharp creative intellect compounds across the career. Performing-craft as career, education-with-stage, publishing, scripting, design-thinking leadership, creative direction with analytic spine, speculative-research advisory, mentor-of-mentees roles. The mind here is exalted — capable of surgical creative production that outclasses larger but blunter rivals. The shadow: over-mentalizing the creative impulse; sometimes the gut wants the rough draft, not the polished theorem.' },
  { name: 'Venus ruler of the 6th House in the 1st House', description: 'Conflict, debt, and adversary-management arrive through your own person rather than via process. The grievance, the audit, the lawsuit, the difficult subordinate — they walk into your room because you are the one they want to settle with. Beauty/diplomacy industries wrapped around enmity (HR, mediation, divorce law, design-arbitration, brand-reputation defense) suit you. The shadow: charm used to deflect rather than resolve will compound the issue.' },
  { name: 'Mars ruler of the 7th House in the 7th House', description: 'Partner is the engine. Co-founders, principal clients, spouse, anchor counterparties — these are sharp, demanding, transformative people who hold your career\'s torque. The deal is the unit of work. Industries: business-development leadership, JV architecture, M&A, surgical practice with partnership structure, dispute-litigation, equity-led ventures with co-principal. Public, fierce, contractual. The shadow: partner-fights that bleed into client-fights — when the temperature rises, document the deal first, let the heat cool second.' },
  { name: 'Jupiter ruler of the 8th House in the 11th House', description: 'Inheritance, equity events, restructuring windfalls, occult-research royalties arrive through wide friend-and-foreign networks. Crisis-management, transformation consulting, life-insurance, longevity science, occult publishing all have payouts that route through your wider community rather than your direct employer. The shadow: ethical drift inside the gain — verify each large windfall against your dharma before letting the network normalize it.' },
  { name: 'Saturn ruler of the 9th House in the 10th House', description: 'Dharma and structure fuse into one career engine. The senior-most authority in your industry is built through ethical, long-arc, lawful, principle-led work that the establishment recognizes. Government service, corporate-ladder-with-purpose, infrastructure leadership, public-policy, judiciary, large-scale systems engineering, regulatory technology, futurist research with formal endorsement. Foreign and traditional credentials compound. The shadow: rigidity where the principle has hardened past the point of being useful.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Slow, structural, irreversible status accrual — and the rise will route through systems, networks, technology platforms, government, large infrastructure, futurist projects, organizational engineering. You will arrive at chief-of-something later than the flashy peers, and still be there long after they have rotated. Aquarian Saturn favors innovation-with-discipline: distributed systems, public-good technology, large-cooperative ventures, board-level reform. The shadow: workaholism that erodes the body and the marriage — honor the dharma, but cap the hours.' },
  { name: 'Jupiter ruler of the 11th House in the 11th House', description: 'Wide international network, ethical friend-circle, teacher-mentee chain — the principal gain channel. Bonuses, equity vesting, board appointments, advisory income flow as a function of relationships you build across decades, often abroad and often through teaching/publishing. Large group ventures, cooperative platforms, distributed-equity structures favor you. The shadow: generosity that pays out faster than it earns — wisdom must be paired with disciplined gating.' },
  { name: 'Mars ruler of the 12th House in the 7th House', description: 'Loss, foreign work, and behind-the-scenes effort all feed into the partnership engine. Spouse and principal client often arrive from abroad or from a confidential / off-balance-sheet world. The fierce work happens out of sight and the public deal is the reveal. Industries: international JV, foreign clientele, defense, security, surgical/military partnership, off-grid construction, monastery/retreat-led ventures with a partner. The shadow: confidential conflicts with partner that drain liquidity invisibly — name the friction early.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 4th (Dispositor)', description: 'When this engine fires, the home becomes the office and the office takes on a hearth quality. Real-estate decisions, family-business inflection, mother-line career conversations, work-from-home founder moves. Industries: real estate, hospitality, family business, education-from-home, domestic-comfort. The shadow: father-figure ambition tilting your dharma off-center.' },
  { name: 'Moon in 3rd (Dispositor)', description: 'When this engine fires, courageous communication wins. The bold message, the brave outreach, the candid sales call, the writing that risks. Industries: media, journalism, content, broadcasting, sales, account-management, customer-success. The shadow: emotional reactivity in the message — pause an hour before pressing send when the day was charged.' },
  { name: 'Mercury in 5th (Dispositor)', description: 'When this engine fires, sharp creative-intellect output lands. Best windows for shipping the script, publishing the analysis, launching the course, presenting the design with the analytical spine, accepting the mentor-of-mentees role. Industries: education-with-stage, creative direction, publishing, advisory, speculative analysis. The shadow: over-mentalization that polishes the work past the point of release.' },
  { name: 'Venus in 1st (Dispositor)', description: 'When this engine fires, the career advances because the room responded to your presence — the meeting tilted on the smile, the posture, the taste. Industries: beauty, design, fashion, hospitality, art curation, brand founding, performance, food. The shadow: comfort-induced inertia. The same magnetism that opens doors will close them if you stop showing up sharply.' },
  { name: 'Mars in 7th (Dispositor)', description: 'When this engine fires, the deal closes through fierce, demanding, transformative partner-action. Industries: business-development, JV, M&A, surgical practice, equity-led ventures, dispute-litigation. Anchor counterparties hand you the next chapter. The shadow: partner-fights that detonate the deal — separate the relational temperature from the contractual mechanics.' },
  { name: 'Jupiter in 11th (Dispositor)', description: 'When this engine fires, large gains route through wide international networks, teacher-mentee chains, ethical friend-circles. Industries: cooperative platforms, distributed ventures, board-advisory, foreign-network leadership, ethical-investment vehicles, teaching guilds. The shadow: generosity outpacing income; gate the wisdom flow through proper compensation structures.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, the slow promotion lands and the structural authority crystallizes. Aquarian-Saturn favors innovation-led, network-anchored, large-systems leadership. Government, technology platforms, infrastructure, futurist projects. The shadow: the long-deferred recognition arrives feeling oddly weightless — honor it, do not chase the next rung to recapture the old hunger.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak visibility window of self. The body radiates, taste sharpens, presentations land. Best four-week window of the year for personal-brand reset, founder declarations, taking the public mantle. Watch ego friction with father-figures.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on income, voice, family-finance. Excellent for negotiating the salary, recording the talk, locking the family-money decision. Throat care matters; vocal projects favored.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on writing, peers, short bursts of effort. Ship the document, send the bold sales note, push the campaign sequence. Younger colleagues respond directly.' },
  { name: 'Sun Transits the 4th House', description: 'Annual return-style activation of the home-throne. Best four-week window of the year for real-estate decisions, family-business inflections, mother-line career conversations, home-base founder moves. Father-figures press their mark.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on the creative-intellect engine. Best window for launching the script, the course, the speculative analysis, the public lecture. Mentor-of-mentees roles light up.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on adversary-management, audit, debt-recovery. Best window for the hard HR conversation, the regulatory filing, the lawsuit you have been postponing. Adversaries weaken.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on partnerships and public-facing deals. Visibility through contracts; spouse and principal-client dynamics light up. Sign the anchor partnership, demand the JV terms, take the deal public.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in the transformation chamber. Career decisions take on surgical edge — succession, restructuring, equity-event navigation. Inheritance and severance matters surface. Foreign-occult Rahu zone activated; verify each opaque opportunity.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on the dharma-mentor engine. Best window for international-stage talks, certifications, judicial proceedings, teacher-mentor moves. A father-figure or senior guru delivers a decisive endorsement.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility window. Best for launching the flagship initiative, demanding the title bump, leading the competitive pitch, accepting the chief-of-something role. The room reads you as the senior-track candidate.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on gains and wide-network zone. Bonus-pool conversations, equity true-ups, board invitations, international-network introductions land. Senior peers notice you abroad.' },
  { name: 'Sun Transits the 12th House', description: 'Public visibility dims for a month — but behind-the-scenes work, foreign correspondence, confidential mandates, retreats are favored. Quiet authority compounds out of sight. Best for white papers, off-balance-sheet structuring, next-quarter strategy.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of emotional charge on persona. Channel into a body-anchored move — the warm pitch, the founder declaration, the curated public moment.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on income, voice, family-finance. Read the room before pricing; soft-spoken negotiations land.' },
  { name: 'Moon Transits the 3rd House', description: 'Monthly home-engine peak for communication. The brave message, the bold outreach, the candid sales call. Ride the courage; do not over-think it.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-throne peak. Mother-channel conversations, real-estate read-outs, family-business pulse-check. Cook a real meal; the emotional reset compounds.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative output. The mind feels poetic; capture the draft, the lyric, the rough idea. Don\'t over-edit the warmth out of it.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict-management. The adversary may push the trigger; respond from documentation, not reaction.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on the partnership engine. Read the spouse / principal-client temperature before the meeting. Warm tone wins the day.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on the transformation zone. Defer high-risk decisions two days. Old fears surface for processing.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma, teaching, foreign work. The mentor-call, the pilgrimage thought, the international-introduction draft.' },
  { name: 'Moon Transits the 10th House', description: 'Monthly career-pulse peak. Public reception is warm; senior-network read-outs favor you. Take the warm-toned client meeting.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional charge on the wide-network engine. Reach out to the international friend, the long-arc mentor, the cooperative-platform ally.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; foreign and behind-the-scenes pull. Best for retreat planning, confidential drafting, dream-led strategy.' },
  { name: 'Mercury Transits the 1st House', description: 'Sharp self-articulation window. Refresh the bio, the founder-story, the personal pitch deck. Send the introduction emails.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Renegotiate the salary, write the family-finance plan, record the talk, pin the price.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s home turf for short-burst communication. Peak window for content production, sales sequences, sibling-channel deals, journalism.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-throne articulation. The real-estate paperwork, the family-business memo, the mother-channel correspondence.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury\'s exalted home — peak of the creative-intellect year. Ship the script, the course, the speculative analysis, the design-with-spine deck.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp adversary-management. The audit memo, the litigation brief, the HR documentation — surgical-precision wins.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, JV memos, contract negotiations land cleanly. Send the partner the written framework.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-chamber articulation. Succession plans, restructuring memos, equity-event paperwork. Document the opaque deal.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-and-foreign articulation. Publish the paper, file the foreign certification, draft the teaching curriculum.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp career-public articulation. Press releases, all-hands updates, public-mantle communications. Send the formal status memo.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. International newsletters, cooperative-platform updates, friend-circle outreach.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp behind-the-scenes articulation. Confidential memos, foreign correspondence, retreat-strategy drafts.' },
  { name: 'Venus Transits the 1st House', description: 'Venus returns to its lagna throne — peak personal-magnetism month. Best for personal-brand reset, design refresh, founder-as-product launches, public-mantle assumption with aesthetic edge.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on income and voice. Pricing rises, voice projects favored, family-finance softens into agreement.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on communication. Tone the message; soften the pitch; let charm carry the bold note further than nerve alone could.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on the home-throne. Property decisions, family-business diplomacy, mother-channel warmth. Aesthetic upgrades to the work-from-home setup.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on creative-intellect. Performance, design, course aesthetics, speculative-creative pitches all favored. Soften the analytic spine with warmth.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on adversary-management. Mediated settlements, charm-led HR, brand-reputation diplomacy. Resolve through warmth, not weight.' },
  { name: 'Venus Transits the 7th House', description: 'Beauty on the partnership engine. Anchor-deal warmth; spouse and principal-client soften. Sign the JV, mediate the standoff with grace.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in the transformation chamber. Equity-event diplomacy; restructuring with aesthetic edge; foreign-occult Rahu zone with Venus softening — verify, but proceed.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on dharma and foreign work. International stages, teaching with grace, ethics-led design moves, cultural-diplomacy.' },
  { name: 'Venus Transits the 10th House', description: 'Peak public-aesthetic visibility. Brand campaigns, design-led PR, beauty-driven status moves. The senior-network reads you as the elegant authority.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on the wide-network engine. Cooperative-platform diplomacy, international-friend warmth, board-aesthetic moves.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on the behind-the-scenes engine. Confidential design work, retreat aesthetics, foreign-luxury back channel.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on the body. Bold founder moves, athletic performance, direct-action declarations. Watch impulsivity; pair speed with discipline.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on income and voice. Aggressive negotiation, bold price-setting, contested family-finance moves. Argue from documentation.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on communication. Bold sales sequences, contested journalism, fierce pitch-mode. Push the campaign now.' },
  { name: 'Mars Transits the 4th House', description: 'Mars on the home-throne. Property disputes, family-business friction, real-estate aggression. Don\'t fight the family in heat — wait two days.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on creative-intellect. Bold creative shipping, contested speculative bets, fierce mentor-mode. The script gets sent; the course gets launched; the bet gets placed.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on adversary-management — Mars\'s strong terrain. The fight is winnable. Press the audit, push the lawsuit, fire the difficult subordinate.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on its own throne (own sign Scorpio 7H). Peak partnership-action year. Sign the JV, demand the terms, divorce the deal that should end. Public, fierce, contractual.' },
  { name: 'Mars Transits the 8th House', description: 'Mars in the transformation chamber. Surgical action; succession force-plays; equity-event combat. Foreign-Rahu zone activated — verify each fight.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on dharma. Bold teaching declarations, foreign-credential pushes, judicial filings, religious-organization combat. Act on principle.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on the career-throne. Bold public moves, competitive pitches, demand-the-title windows. Storming the senior-track. Watch heat with the boss.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on the wide-network engine. Bold international-circle moves, contested cooperative-platform pushes, board-level combat.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential combat. Behind-the-scenes warrior, foreign-mandate aggression, off-balance-sheet pushes. Watch hidden enemies.' },
  { name: 'Jupiter Transits the 1st House', description: 'Major year for self-expansion. Public-mantle assumption, founder-role elevation, ambition declaration. The body itself expands — discipline diet and exercise to convert the wisdom into stamina.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Major year for income and voice expansion. Salary-jumps, family-money inflows, voice-project breakthrough.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Major year for communication-expansion. Publishing, broadcasting, sales-leadership, sibling-channel growth.' },
  { name: 'Jupiter Transits the 4th House', description: 'Major year for home-throne expansion. Real-estate acquisition, family-business growth, mother-line career inflection. The home itself expands.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for creative-intellect expansion. Course-platform breakthrough, performance-craft elevation, mentor-of-mentees role formalized.' },
  { name: 'Jupiter Transits the 6th House', description: 'Major year for adversary-victory. Long lawsuits resolve favorably; chronic adversaries fade; HR transformation lands; work systems consolidate.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major year for partnership expansion. Spouse, principal-client, JV principal arrive. Anchor-deal closure year. Marriage if unmarried; renewal if married.' },
  { name: 'Jupiter Transits the 8th House', description: 'Major year for transformation-zone gains. Inheritance, severance, equity-event windfall, occult-research royalty. Verify ethical bedrock; foreign-Rahu zone is intensified.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major year for dharma-expansion. Foreign credentials, teaching-platform breakthrough, judicial endorsements, guru-blessing chapters. International elevation.' },
  { name: 'Jupiter Transits the 10th House', description: 'Major year for public-career expansion. Chief-of-something offers, prestige roles, board appointments, formal-recognition windfalls. Status crystallizes.' },
  { name: 'Jupiter Transits the 11th House', description: 'Major year on Jupiter\'s own throne (own sign Pisces 11H). Peak of the wide-network gain engine. International networks pay; cooperative platforms compound; teacher-mentee chains deliver. The largest gain year of the cycle.' },
  { name: 'Jupiter Transits the 12th House', description: 'Major year for behind-the-scenes expansion. Foreign work, retreats, confidential mandates, off-balance-sheet wisdom-driven gains. Pilgrimage chapter.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on the body and identity. Health discipline mandatory; vanity commitments fall away. What survives is permanent. Slow weight, joint, bone reckoning.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on income, voice, family-finance. Salary stagnation possible; structure savings rituals. Slow throat / dental health attention.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on communication and short-effort work. Long-arc content systems compound; sibling-channel structures formalize.' },
  { name: 'Saturn Transits the 4th House', description: 'Multi-year discipline on home-throne. Real-estate restructuring, family-business reckoning, mother\'s health-and-career as long-arc concern.' },
  { name: 'Saturn Transits the 5th House', description: 'Multi-year discipline on creative-intellect. The script that takes 3 years to ship; the course that compounds across cohorts; speculative bets that mature slowly.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain. Multi-year discipline on adversary-management. Long lawsuits, regulatory mastery, structural HR. The patience-and-paperwork win.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnership. Spouse-and-client commitments scrutinized; weak deals end; strong ones formalize into 30-year structures.' },
  { name: 'Saturn Transits the 8th House', description: 'Multi-year reckoning in the transformation chamber. Inheritance disputes, equity-event delays, foreign-occult navigation. Patience pays.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year dharma-discipline. Long credential paths, judicial processes, teaching-institution leadership. The slow climb to elder-teacher status.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on its own throne (own sign Aquarius 10H — Sasa Yoga territory). Peak structural-career chapter of the multi-decade cycle. Chief-of-something crystallizes; legacy-grade authority sets in. Innovation, networks, technology, infrastructure leadership.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn on its other own sign (Aquarius / Capricorn lordship cluster). Multi-year discipline on wide-network gains. Cooperative platforms formalize, international friend-circles deepen, board roles consolidate.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on behind-the-scenes work. Long retreat-chapter, foreign-confidential mandates, off-balance-sheet structuring. Quiet authority builds.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive identity-reinvention. New persona, new ambitions, new public projection. Verify each move; the obsession can run hot.' },
  { name: 'Rahu Transits the 2nd House', description: 'Eighteen-month obsession on income and voice. Sudden family-money chaos; verify get-rich schemes; voice-projects with chaotic upside.' },
  { name: 'Rahu Transits the 3rd House', description: 'Eighteen-month obsessive communication chapter. Viral content, controversial journalism, sibling-channel intensities. Verify integrity.' },
  { name: 'Rahu Transits the 4th House', description: 'Eighteen-month home-throne obsession. Foreign-property pull, family-business reinvention, real-estate fevers. Verify each title.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month obsessive creative chapter. Speculation, viral courses, controversial public-stage moves. Verify ethical bedrock.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Eighteen-month obsessive adversary-defeat chapter. Long-running enemies fall; chronic conflicts resolve unconventionally.' },
  { name: 'Rahu Transits the 7th House', description: 'Eighteen-month obsessive partnership chapter. Foreign spouse, controversial JV, sudden anchor-client. Verify counterparty integrity.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on its strong terrain (8H). Eighteen-month obsessive transformation chapter. Inheritance chaos, equity-event windfalls, occult-research breakthroughs, foreign opaque dealings. Verify everything.' },
  { name: 'Rahu Transits the 9th House', description: 'Eighteen-month foreign-dharma obsession. International guru-pull, controversial teaching-platforms, foreign-credential push.' },
  { name: 'Rahu Transits the 10th House', description: 'Eighteen-month career-reinvention obsession. Sudden promotions, unconventional industries, foreign-career pull. Verify each pivot.' },
  { name: 'Rahu Transits the 11th House', description: 'Eighteen-month obsessive wide-network chapter. Sudden viral-network gains, controversial cooperative-platforms. Verify integrity.' },
  { name: 'Rahu Transits the 12th House', description: 'Eighteen-month foreign-confidential obsession. Hidden mandates, foreign-occult chapters, off-balance-sheet intensities.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping window. Old persona feels empty; ambitions detach. Sit; do not over-correct.' },
  { name: 'Ketu Transits the 2nd House', description: 'Eighteen-month detachment from income, voice, family-money. Old earning paths feel hollow; the cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Eighteen-month communication-detachment. Old content-loops feel finished; sibling-channel quiets.' },
  { name: 'Ketu Transits the 4th House', description: 'Eighteen-month home-throne detachment. Old real-estate plans feel weightless; family-business attachment dissolves.' },
  { name: 'Ketu Transits the 5th House', description: 'Eighteen-month creative-detachment. Old performance-loops feel finished; speculative cravings fall away.' },
  { name: 'Ketu Transits the 6th House', description: 'Eighteen-month adversary-detachment. Long enemies fade without intervention; chronic conflicts dissolve quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Eighteen-month partnership-detachment. Old deal feels finished; spouse / principal-client dynamic loosens.' },
  { name: 'Ketu Transits the 8th House', description: 'Eighteen-month transformation-acceleration. Old crises evaporate; deep occult-research detachment.' },
  { name: 'Ketu Transits the 9th House', description: 'Eighteen-month dharma-detachment. Old guru-attachments fade; principle-without-attachment ripens.' },
  { name: 'Ketu Transits the 10th House', description: 'Eighteen-month career-eclipse. Old role feels weightless; the title that was the destination feels like a costume.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month wide-network detachment. Old friend-circles drift; bonus-pool feels detached.' },
  { name: 'Ketu Transits the 12th House', description: 'Eighteen-month behind-the-scenes detachment. Old retreats, foreign-confidential mandates close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through persona. Best for leadership declarations, public-mantle assumption, founder-style debut.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish public-facing materials; prepare the leadership pitch.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the stage, declare the role, accept the public mantle.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Convert visibility into a binding title.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Peak career-visibility window. Launch flagship initiatives; demand title-elevation.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens. Plan the upward move; brief the boss.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak career-visibility day. Take the elevation, lead the pitch, accept the prestige role.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-visibility window closes. Lock in title or compensation moves.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona; warm public reception possible.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens. Prepare to be felt, not just seen.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Public mood favors you; warm presentations land.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes. Lock in connections.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public reputation; warm career news possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional career window opens. Senior-network warmth rises.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional career day. Take the warm-toned client meeting, the empathetic team-talk.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional career window closes. Move warm leads into formal commitments.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-communication. Best for personal-brand updates, founder-narrative refresh.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Mind-on-self window opens. Refresh the CV, the bio, the founder-story.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak self-communication day. Send the bold intro letter, publish the personal post.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mind-on-self window closes. Lock in personal-brand commitments.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp career-communication. Press releases, all-hands updates, status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-communication window opens. Prepare the public message.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak career-communication day. Publish, present, send the formal update.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-communication window closes. Convert messaging into commitment.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Venus on its own lagna throne — peak charm-day. The smile lands; the warm ask works; magnetism is at its yearly high.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Venus-self window opens. Plan the warm outreach, the diplomatic ask.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. Make the warm ask, take the social meeting, deliver the persuasion. Personal magnetism at peak.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Venus-self window closes. Convert warmth into binding agreements.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens the public face. Brand campaigns, design-led PR, beauty-driven status moves.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-career window opens. Plan the brand refresh, the visual update.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-career day. Launch the campaign, present the redesign.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-career window closes. Lock in design commitments.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold, body-anchored self-action; founder declarations; warrior moves.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens. Prepare the bold move; train the body.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Take the founder action, sign the bold paper, lead the charge.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes. Channel residual energy into discipline.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold, decisive career action. Launch flagship initiatives; demand title-bumps; lead competitive pitches.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Career-action window opens. Prepare the bold play.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak career-action day. Launch, demand, lead.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Career-action window closes. Convert moves into permanent positions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the role-elevation; declare the larger ambition.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens. Plan the public-mantle assumption.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the elevation, declare the ambition, take the public role.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes. Lock in the title, the public commitment.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the chief role, the prestige offer, the board appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Career-expansion window opens. Brief the senior network.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak career-expansion day. Accept the chief-of-something role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Career-expansion window closes. Convert offers into binding commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity. Slow down, simplify, build for permanence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens. Eliminate vanity commitments; prepare for slow grind.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. The reckoning is acute. Hold steady.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Structural-self window closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Saturn on its own MC throne. Peak structural-career window. Slow recognition; foundation-laying for legacy-grade authority.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-discipline window opens. Structure work for years.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak career-discipline day. The promotion delayed, the foundation laid, the permanent role crystallizes.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-discipline window closes. Convert effort into title and compensation.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion; foreign or unconventional self emerges. Watch obsession.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention window begins. Sudden ambition surfaces.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak reinvention day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Reinvention window closes. Decide which experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic visibility expansion. Sudden promotions, unconventional opportunities, foreign career pull.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Career-reinvention window begins. Vet unconventional offers carefully.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak career-reinvention day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Career-reinvention window closes. Lock in legitimate pivots; release illusory ones.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. The old persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens. The pull to step away rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak stripping day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Stripping window closes. Move forward leaner.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. Promotions stall; recognition feels hollow.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-eclipse window begins. Don\'t over-defend a role wanting to end.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak career-eclipse day. The role dissolves quietly. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-eclipse window closes. Move forward to the cleaner platform.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting your career engine. Your industry rewrites; old hierarchies collapse. Multi-year career-platform transformation; you emerge with rebuilt structural authority on the Aquarian-Saturn frontier (technology, networks, infrastructure, public-good systems).' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on your career engine. Old corporate frameworks dismantle. Position for the long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day. The old system breaks; the new one is forced into being. You hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The structural-transformation chapter completes. You emerge with rebuilt authority and a permanent professional foundation.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the Venus-on-lagna engine — your personal-brand and aesthetic identity. Unexpected design pivots, abrupt founder-as-product reinventions, surprise beauty/luxury industry shifts.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden personal-brand disruption window opens. Expect pivots in design, aesthetic identity, founder-presentation.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak personal-brand disruption day. The design lands or shatters; the aesthetic pivot is forced. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Personal-brand disruption window closes. Integrate the changes; release the experiments that didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 4th house', description: 'Solar fire on the home-throne engine. Best for real-estate decisions, family-business inflection, mother-line career conversations, work-from-home founder declarations.' },
  { name: 'Sun aspect Sun in 4th house : Starts', description: 'Annual home-throne window opens. Plan the year\'s real-estate or family-business move.' },
  { name: 'Sun aspect Sun in 4th house : Exact', description: 'Peak home-throne day. Sign the property paper, host the family-business meeting, take the home-channel call.' },
  { name: 'Sun aspect Sun in 4th house : Ends', description: 'Home-throne window closes. Lock in real-estate or family-business commitments.' },
  { name: 'Sun aspect Moon in 3rd house', description: 'Visibility through courageous communication. Bold messages, sales sequences, sibling-channel deals favored.' },
  { name: 'Sun aspect Moon in 3rd house : Starts', description: 'Communication-courage window opens. Prepare the bold pitch sequence.' },
  { name: 'Sun aspect Moon in 3rd house : Exact', description: 'Peak day for bold communication. Send the brave note, push the campaign, take the sibling-channel conversation.' },
  { name: 'Sun aspect Moon in 3rd house : Ends', description: 'Communication-courage window closes. Lock in messaging commitments.' },
  { name: 'Sun aspect Mercury in 5th house', description: 'Solar fire on creative-intellect. Course launches, performances, scripts, speculative-analytic deliveries peak.' },
  { name: 'Sun aspect Mercury in 5th house : Starts', description: 'Creative-intellect window opens. Plan the high-craft deliverable.' },
  { name: 'Sun aspect Mercury in 5th house : Exact', description: 'Peak creative-intellect day. Ship the script, launch the course, deliver the analysis.' },
  { name: 'Sun aspect Mercury in 5th house : Ends', description: 'Creative-intellect window closes. Lock in creative commitments.' },
  { name: 'Sun aspect Venus in 1st house', description: 'Solar fire on the personal-brand throne. Founder-as-product visibility peaks; aesthetic-identity declarations land.' },
  { name: 'Sun aspect Venus in 1st house : Starts', description: 'Personal-brand window opens. Plan the visual launch, the founder photo shoot, the brand declaration.' },
  { name: 'Sun aspect Venus in 1st house : Exact', description: 'Peak personal-brand day. Launch the founder-product, declare the aesthetic, accept the public-face role.' },
  { name: 'Sun aspect Venus in 1st house : Ends', description: 'Personal-brand window closes. Lock in design and brand commitments.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Solar fire on the partnership engine. Anchor-deal visibility, JV declarations, public-facing contract moves.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Partnership-fire window opens. Brief the spouse / principal-client.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Peak partnership-fire day. Sign the JV, demand the terms, take the deal public.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Partnership-fire window closes. Lock in contractual commitments.' },
  { name: 'Sun aspect Jupiter in 11th house', description: 'Solar fire on wide-network gains. International introductions, board invitations, cooperative-platform breakthroughs.' },
  { name: 'Sun aspect Jupiter in 11th house : Starts', description: 'Wide-network window opens. Brief the international circle.' },
  { name: 'Sun aspect Jupiter in 11th house : Exact', description: 'Peak wide-network day. Accept the board seat, take the international intro, lock the cooperative-platform pact.' },
  { name: 'Sun aspect Jupiter in 11th house : Ends', description: 'Wide-network window closes. Convert introductions into formal commitments.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on Sasa-Yoga career engine. Public-mantle assumption, chief-of-something declarations, prestige-role acceptance.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Sasa-Yoga window opens. Prepare the structural-authority move.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak structural-authority day. Take the chief role, accept the prestige seat, declare the legacy-grade authority.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Sasa-Yoga window closes. Convert authority into title, contract, and term.' },
  { name: 'Sun aspect Rahu in 8th house', description: 'Solar fire in the foreign-occult transformation chamber. Equity events, restructuring opportunities, opaque-deal visibility — verify integrity.' },
  { name: 'Sun aspect Rahu in 8th house : Starts', description: 'Foreign-occult window opens. Vet the opaque deal carefully.' },
  { name: 'Sun aspect Rahu in 8th house : Exact', description: 'Peak foreign-occult day. Take the equity-event move with full documentation.' },
  { name: 'Sun aspect Rahu in 8th house : Ends', description: 'Foreign-occult window closes. Lock legitimate moves; release illusions.' },
  { name: 'Sun aspect Ketu in 2nd house', description: 'Solar light on detached-voice/family-money zone. Old earning paths feel finished; speak less to gain more.' },
  { name: 'Sun aspect Ketu in 2nd house : Starts', description: 'Voice-detachment window opens. Audit which earning-paths are alive.' },
  { name: 'Sun aspect Ketu in 2nd house : Exact', description: 'Peak voice-detachment day. Release the earning channel that has been hollow.' },
  { name: 'Sun aspect Ketu in 2nd house : Ends', description: 'Voice-detachment window closes. Move forward with leaner revenue paths.' },
  { name: 'Moon aspect Sun in 4th house', description: 'Emotional charge on home-throne visibility. Mother-channel conversations, real-estate read-outs, family-business pulse.' },
  { name: 'Moon aspect Sun in 4th house : Starts', description: 'Home-emotion window opens.' },
  { name: 'Moon aspect Sun in 4th house : Exact', description: 'Peak day. Cook a real meal at home, host the family-business call, sign the warm property paper.' },
  { name: 'Moon aspect Sun in 4th house : Ends', description: 'Home-emotion window closes.' },
  { name: 'Moon aspect Moon in 3rd house', description: 'Emotional courage on communication. The brave message, the candid sales call, the warm sibling-channel outreach.' },
  { name: 'Moon aspect Moon in 3rd house : Starts', description: 'Communication-emotion window opens.' },
  { name: 'Moon aspect Moon in 3rd house : Exact', description: 'Peak day. Send the bold note, take the warm pitch call, write the courageous post.' },
  { name: 'Moon aspect Moon in 3rd house : Ends', description: 'Communication-emotion window closes.' },
  { name: 'Moon aspect Mercury in 5th house', description: 'Emotional charge on creative-intellect. The poetic draft, the warm course module, the heart-led performance.' },
  { name: 'Moon aspect Mercury in 5th house : Starts', description: 'Creative-emotion window opens.' },
  { name: 'Moon aspect Mercury in 5th house : Exact', description: 'Peak day. Capture the warm draft; do not over-edit.' },
  { name: 'Moon aspect Mercury in 5th house : Ends', description: 'Creative-emotion window closes.' },
  { name: 'Moon aspect Venus in 1st house', description: 'Emotional charge on personal-brand. The warm founder declaration, the heart-led aesthetic move.' },
  { name: 'Moon aspect Venus in 1st house : Starts', description: 'Personal-brand-emotion window opens.' },
  { name: 'Moon aspect Venus in 1st house : Exact', description: 'Peak day. Take the warm founder photo, declare the heart-led aesthetic.' },
  { name: 'Moon aspect Venus in 1st house : Ends', description: 'Personal-brand-emotion window closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge on partnership. Read the spouse / principal-client temperature; soften the deal-tone.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Partnership-emotion window opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Peak day. Lead with warmth in the JV meeting; defuse before debating.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Partnership-emotion window closes.' },
  { name: 'Moon aspect Jupiter in 11th house', description: 'Emotional warmth on wide-network. International friend-circle, board-seat warmth, cooperative-platform heart.' },
  { name: 'Moon aspect Jupiter in 11th house : Starts', description: 'Network-emotion window opens.' },
  { name: 'Moon aspect Jupiter in 11th house : Exact', description: 'Peak day. Reach out to the long-arc international friend; take the warm board call.' },
  { name: 'Moon aspect Jupiter in 11th house : Ends', description: 'Network-emotion window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on the structural-career engine. The senior-network warmth around the long-arc role.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Career-emotion window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day. Take the warm-toned senior-stakeholder call; honor the long-arc structure.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Career-emotion window closes.' },
  { name: 'Moon aspect Rahu in 8th house', description: 'Emotional charge on the foreign-occult transformation chamber. Old equity-event fears surface; process them.' },
  { name: 'Moon aspect Rahu in 8th house : Starts', description: 'Transformation-emotion window opens.' },
  { name: 'Moon aspect Rahu in 8th house : Exact', description: 'Peak day. Defer the opaque move two days; let the emotion settle first.' },
  { name: 'Moon aspect Rahu in 8th house : Ends', description: 'Transformation-emotion window closes.' },
  { name: 'Moon aspect Ketu in 2nd house', description: 'Emotional detachment from voice / family-money. Old earning paths feel hollow; the cravings around them dissolve.' },
  { name: 'Moon aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-emotion window opens.' },
  { name: 'Moon aspect Ketu in 2nd house : Exact', description: 'Peak day. Sit with the income-paths feeling weightless; do not panic-pivot.' },
  { name: 'Moon aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-emotion window closes.' },
  { name: 'Mercury aspect Sun in 4th house', description: 'Sharp articulation of home-throne. Real-estate paperwork, family-business memos, mother-channel correspondence.' },
  { name: 'Mercury aspect Sun in 4th house : Starts', description: 'Home-articulation window opens.' },
  { name: 'Mercury aspect Sun in 4th house : Exact', description: 'Peak day. Send the property memo, file the family-business document, write the warm mother-channel note.' },
  { name: 'Mercury aspect Sun in 4th house : Ends', description: 'Home-articulation window closes.' },
  { name: 'Mercury aspect Moon in 3rd house', description: 'Sharp courage-communication. Bold sales sequences, brave journalism drafts, sibling-channel campaigns.' },
  { name: 'Mercury aspect Moon in 3rd house : Starts', description: 'Courage-articulation window opens.' },
  { name: 'Mercury aspect Moon in 3rd house : Exact', description: 'Peak day. Send the bold sales sequence, publish the brave journalism, push the campaign.' },
  { name: 'Mercury aspect Moon in 3rd house : Ends', description: 'Courage-articulation window closes.' },
  { name: 'Mercury aspect Mercury in 5th house', description: 'Mercury\'s exalted return on its own creative-intellect throne. Peak articulation day for scripts, courses, speculative analyses, design decks.' },
  { name: 'Mercury aspect Mercury in 5th house : Starts', description: 'Exalted creative-intellect window opens. Plan the masterpiece deliverable.' },
  { name: 'Mercury aspect Mercury in 5th house : Exact', description: 'Peak day. Ship the script, publish the analysis, launch the course — the mind is at its sharpest annual setting.' },
  { name: 'Mercury aspect Mercury in 5th house : Ends', description: 'Exalted creative-intellect window closes. Lock in the year\'s creative commitments.' },
  { name: 'Mercury aspect Venus in 1st house', description: 'Sharp personal-brand articulation. Founder bios, brand decks, aesthetic-identity write-ups.' },
  { name: 'Mercury aspect Venus in 1st house : Starts', description: 'Personal-brand-articulation window opens.' },
  { name: 'Mercury aspect Venus in 1st house : Exact', description: 'Peak day. Publish the founder bio, send the brand deck, write the aesthetic manifesto.' },
  { name: 'Mercury aspect Venus in 1st house : Ends', description: 'Personal-brand-articulation window closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Sharp partnership-articulation. Term sheets, JV memos, contract drafts.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Partnership-articulation window opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Peak day. Send the term sheet, publish the JV memo, sign the contract draft.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Partnership-articulation window closes.' },
  { name: 'Mercury aspect Jupiter in 11th house', description: 'Sharp wide-network articulation. International newsletters, cooperative-platform updates, board memos.' },
  { name: 'Mercury aspect Jupiter in 11th house : Starts', description: 'Network-articulation window opens.' },
  { name: 'Mercury aspect Jupiter in 11th house : Exact', description: 'Peak day. Send the international newsletter, publish the platform update, brief the board.' },
  { name: 'Mercury aspect Jupiter in 11th house : Ends', description: 'Network-articulation window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Sharp Sasa-Yoga articulation. Public-mantle press releases, prestige-role announcements, structural-authority memos.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Structural-articulation window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day. Issue the press release, publish the role announcement, file the formal authority paper.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Structural-articulation window closes.' },
  { name: 'Mercury aspect Rahu in 8th house', description: 'Sharp foreign-occult articulation. Equity-event memos, restructuring documentation, opaque-deal paperwork.' },
  { name: 'Mercury aspect Rahu in 8th house : Starts', description: 'Foreign-occult-articulation window opens.' },
  { name: 'Mercury aspect Rahu in 8th house : Exact', description: 'Peak day. Document the opaque deal precisely; the paperwork is your protection.' },
  { name: 'Mercury aspect Rahu in 8th house : Ends', description: 'Foreign-occult-articulation window closes.' },
  { name: 'Mercury aspect Ketu in 2nd house', description: 'Sharp voice-detachment articulation. Audit the earning paths; write the closure-of-old-channel memo.' },
  { name: 'Mercury aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-articulation window opens.' },
  { name: 'Mercury aspect Ketu in 2nd house : Exact', description: 'Peak day. Write the closure note for the dead earning channel.' },
  { name: 'Mercury aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-articulation window closes.' },
  { name: 'Venus aspect Sun in 4th house', description: 'Beauty on the home-throne. Aesthetic upgrades to the workspace, family-business diplomacy, mother-channel warmth.' },
  { name: 'Venus aspect Sun in 4th house : Starts', description: 'Home-beauty window opens.' },
  { name: 'Venus aspect Sun in 4th house : Exact', description: 'Peak day. Soften the property negotiation, host the elegant family meeting, redesign the workspace.' },
  { name: 'Venus aspect Sun in 4th house : Ends', description: 'Home-beauty window closes.' },
  { name: 'Venus aspect Moon in 3rd house', description: 'Beauty on courageous communication. Tone the bold message; soften the brave pitch.' },
  { name: 'Venus aspect Moon in 3rd house : Starts', description: 'Communication-beauty window opens.' },
  { name: 'Venus aspect Moon in 3rd house : Exact', description: 'Peak day. Send the elegantly-worded brave note; charm carries the bold pitch further.' },
  { name: 'Venus aspect Moon in 3rd house : Ends', description: 'Communication-beauty window closes.' },
  { name: 'Venus aspect Mercury in 5th house', description: 'Beauty on creative-intellect. Performance aesthetics, course design, speculative-creative-pitch elegance.' },
  { name: 'Venus aspect Mercury in 5th house : Starts', description: 'Creative-beauty window opens.' },
  { name: 'Venus aspect Mercury in 5th house : Exact', description: 'Peak day. Polish the performance, redesign the course visuals, present with elegant analytic.' },
  { name: 'Venus aspect Mercury in 5th house : Ends', description: 'Creative-beauty window closes.' },
  { name: 'Venus aspect Venus in 1st house', description: 'Venus on its Malavya throne. Peak personal-brand magnetism day of the year. The face, body, voice, taste — all at their warmest annual setting.' },
  { name: 'Venus aspect Venus in 1st house : Starts', description: 'Malavya window opens. Plan the founder-as-product launch, the brand reset, the public-face declaration.' },
  { name: 'Venus aspect Venus in 1st house : Exact', description: 'Peak Malavya day. Launch the brand, declare the aesthetic, take the public stage as the magnetic principal.' },
  { name: 'Venus aspect Venus in 1st house : Ends', description: 'Malavya window closes. Lock in design and brand commitments.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Beauty on the partnership engine. Mediated JV diplomacy, anchor-deal warmth, spouse-and-client softening.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Partnership-beauty window opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Peak day. Sign the warm JV, mediate the partner-standoff, charm the principal client.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Partnership-beauty window closes.' },
  { name: 'Venus aspect Jupiter in 11th house', description: 'Beauty on the wide-network engine. Cooperative-platform diplomacy, international-friend warmth, board-aesthetic moves.' },
  { name: 'Venus aspect Jupiter in 11th house : Starts', description: 'Network-beauty window opens.' },
  { name: 'Venus aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the international-friend call, polish the board presentation, attend the cooperative-platform gala.' },
  { name: 'Venus aspect Jupiter in 11th house : Ends', description: 'Network-beauty window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Beauty on the Sasa-Yoga career engine. Senior-network charm, structural-authority diplomacy, public-face elegance.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Structural-beauty window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day. Take the senior-stakeholder warm meeting, present the prestige-role pitch with elegance.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Structural-beauty window closes.' },
  { name: 'Venus aspect Rahu in 8th house', description: 'Beauty in the foreign-occult chamber. Equity-event diplomacy, restructuring-with-aesthetic, opaque-deal softening — verify integrity.' },
  { name: 'Venus aspect Rahu in 8th house : Starts', description: 'Foreign-occult-beauty window opens.' },
  { name: 'Venus aspect Rahu in 8th house : Exact', description: 'Peak day. Take the elegant opaque-deal meeting; verify the bedrock under the gloss.' },
  { name: 'Venus aspect Rahu in 8th house : Ends', description: 'Foreign-occult-beauty window closes.' },
  { name: 'Venus aspect Ketu in 2nd house', description: 'Beauty on voice-detachment. Old earning-paths feel weightless; speak less to gain more.' },
  { name: 'Venus aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-beauty window opens.' },
  { name: 'Venus aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the earning channel that has been hollow; do not over-justify.' },
  { name: 'Venus aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-beauty window closes.' },
  { name: 'Mars aspect Sun in 4th house', description: 'Mars on the home-throne. Property disputes, family-business friction, real-estate aggression. Don\'t fight family in heat.' },
  { name: 'Mars aspect Sun in 4th house : Starts', description: 'Home-fire window opens.' },
  { name: 'Mars aspect Sun in 4th house : Exact', description: 'Peak day. Defer family confrontation two days; the heat distorts judgment.' },
  { name: 'Mars aspect Sun in 4th house : Ends', description: 'Home-fire window closes.' },
  { name: 'Mars aspect Moon in 3rd house', description: 'Mars on courageous communication. Bold sales pushes, contested journalism, fierce campaigns.' },
  { name: 'Mars aspect Moon in 3rd house : Starts', description: 'Courage-fire window opens.' },
  { name: 'Mars aspect Moon in 3rd house : Exact', description: 'Peak day. Push the campaign, send the contested piece, lead the sales storm.' },
  { name: 'Mars aspect Moon in 3rd house : Ends', description: 'Courage-fire window closes.' },
  { name: 'Mars aspect Mercury in 5th house', description: 'Mars on creative-intellect. Bold creative shipping, contested speculative bets, fierce mentor-mode.' },
  { name: 'Mars aspect Mercury in 5th house : Starts', description: 'Creative-fire window opens.' },
  { name: 'Mars aspect Mercury in 5th house : Exact', description: 'Peak day. Ship the bold script, place the contested bet, lead the fierce mentorship.' },
  { name: 'Mars aspect Mercury in 5th house : Ends', description: 'Creative-fire window closes.' },
  { name: 'Mars aspect Venus in 1st house', description: 'Mars on the personal-brand throne. Bold founder-as-product moves, contested aesthetic pivots, public-face combat.' },
  { name: 'Mars aspect Venus in 1st house : Starts', description: 'Personal-brand-fire window opens.' },
  { name: 'Mars aspect Venus in 1st house : Exact', description: 'Peak day. Take the bold founder pivot, declare the contested aesthetic, fight the brand-attack.' },
  { name: 'Mars aspect Venus in 1st house : Ends', description: 'Personal-brand-fire window closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Mars on its own throne (own sign Scorpio 7H, Ruchaka activation). Peak partnership-fire day of the year. The deal is signed, the standoff is broken, the JV is forced to clarity.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Ruchaka-window opens. Prepare the bold partnership move.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Peak Ruchaka day. Sign the JV, divorce the dead deal, demand the partnership terms. Mars on its throne fights cleanly.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Ruchaka-window closes. Lock in contractual commitments.' },
  { name: 'Mars aspect Jupiter in 11th house', description: 'Mars on the wide-network engine. Bold international-circle moves, contested cooperative-platform pushes, board-level combat.' },
  { name: 'Mars aspect Jupiter in 11th house : Starts', description: 'Network-fire window opens.' },
  { name: 'Mars aspect Jupiter in 11th house : Exact', description: 'Peak day. Push the international-network move, contest the cooperative-platform decision, lead the board fight.' },
  { name: 'Mars aspect Jupiter in 11th house : Ends', description: 'Network-fire window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Mars on the Sasa-Yoga career engine. Bold competitive pitches, demand-the-title moves, structural-authority combat.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Career-fire window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day. Lead the competitive pitch, demand the title-bump, force the structural-authority conversation.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Career-fire window closes.' },
  { name: 'Mars aspect Rahu in 8th house', description: 'Mars in the foreign-occult chamber. Surgical action on equity events, force-plays in restructuring, fierce opaque-deal navigation.' },
  { name: 'Mars aspect Rahu in 8th house : Starts', description: 'Foreign-occult-fire window opens. Verify integrity before fighting.' },
  { name: 'Mars aspect Rahu in 8th house : Exact', description: 'Peak day. Take the surgical equity-event action — but with full documentation.' },
  { name: 'Mars aspect Rahu in 8th house : Ends', description: 'Foreign-occult-fire window closes.' },
  { name: 'Mars aspect Ketu in 2nd house', description: 'Mars on voice-detachment. Sudden earning-path disputes; old voice-channels detonate cleanly.' },
  { name: 'Mars aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-fire window opens.' },
  { name: 'Mars aspect Ketu in 2nd house : Exact', description: 'Peak day. Forcefully close the dead earning channel; do not negotiate the closure.' },
  { name: 'Mars aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-fire window closes.' },
  { name: 'Jupiter aspect Sun in 4th house', description: 'Wisdom-expansion of the home-throne. Real-estate gains, family-business expansion, mother-line career inflection. Property acquisition windows.' },
  { name: 'Jupiter aspect Sun in 4th house : Starts', description: 'Home-expansion window opens.' },
  { name: 'Jupiter aspect Sun in 4th house : Exact', description: 'Peak day. Acquire the property, expand the family business, take the mother-line career inflection.' },
  { name: 'Jupiter aspect Sun in 4th house : Ends', description: 'Home-expansion window closes.' },
  { name: 'Jupiter aspect Moon in 3rd house', description: 'Wisdom on courageous communication. Publishing breakthroughs, broadcast-platform expansion, sibling-channel enlargement.' },
  { name: 'Jupiter aspect Moon in 3rd house : Starts', description: 'Communication-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 3rd house : Exact', description: 'Peak day. Publish the book, accept the broadcast platform, take the sibling-channel JV.' },
  { name: 'Jupiter aspect Moon in 3rd house : Ends', description: 'Communication-expansion window closes.' },
  { name: 'Jupiter aspect Mercury in 5th house', description: 'Wisdom on creative-intellect. Course-platform breakthrough, performance-craft elevation, formal mentor-of-mentees role.' },
  { name: 'Jupiter aspect Mercury in 5th house : Starts', description: 'Creative-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 5th house : Exact', description: 'Peak day. Launch the course platform, accept the elevated performance role, formalize the mentorship.' },
  { name: 'Jupiter aspect Mercury in 5th house : Ends', description: 'Creative-expansion window closes.' },
  { name: 'Jupiter aspect Venus in 1st house', description: 'Wisdom on the personal-brand throne. Founder-as-product elevation, public-face role expansion, brand-platform inflection.' },
  { name: 'Jupiter aspect Venus in 1st house : Starts', description: 'Personal-brand-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 1st house : Exact', description: 'Peak day. Accept the public-face elevation, launch the founder-platform, take the brand-leadership role.' },
  { name: 'Jupiter aspect Venus in 1st house : Ends', description: 'Personal-brand-expansion window closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Wisdom on the partnership engine. Anchor-deal expansion, JV elevation, marriage-and-equity-partner inflection.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Partnership-expansion window opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak day. Sign the elevated JV, accept the marriage-or-merger inflection, take the principal-client expansion.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Partnership-expansion window closes.' },
  { name: 'Jupiter aspect Jupiter in 11th house', description: 'Jupiter on its own throne (own sign Pisces 11H). Peak wide-network gains day of the cycle. International networks pay; cooperative platforms compound; teacher-mentee chains deliver.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Starts', description: 'Wide-network-gain window opens. Plan the international move, the cooperative-platform pact, the teacher-mentee inflection.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the international windfall, accept the cooperative-platform leadership, formalize the wide-network gain.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Ends', description: 'Wide-network-gain window closes. Lock in international and cooperative commitments.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on the Sasa-Yoga career engine. Chief-of-something offers, prestige-role acceptance, board appointments, formal-recognition windfalls.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Sasa-expansion window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day. Accept the chief role, take the prestige seat, formalize the legacy-grade authority.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Sasa-expansion window closes.' },
  { name: 'Jupiter aspect Rahu in 8th house', description: 'Wisdom on the foreign-occult chamber. Equity-event windfalls, inheritance gains, occult-research royalties — Jupiter sanctifies the opaque.' },
  { name: 'Jupiter aspect Rahu in 8th house : Starts', description: 'Foreign-occult-expansion window opens.' },
  { name: 'Jupiter aspect Rahu in 8th house : Exact', description: 'Peak day. Take the equity-event windfall, accept the inheritance settlement, formalize the occult-research royalty.' },
  { name: 'Jupiter aspect Rahu in 8th house : Ends', description: 'Foreign-occult-expansion window closes.' },
  { name: 'Jupiter aspect Ketu in 2nd house', description: 'Wisdom on voice-detachment. The dead earning-path graduates into a teaching-of-the-lesson; speak less, monetize the wisdom of the silence.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-expansion window opens.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Exact', description: 'Peak day. Convert the abandoned earning channel into a teaching artifact.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-expansion window closes.' },
  { name: 'Saturn aspect Sun in 4th house', description: 'Structural pressure on the home-throne. Real-estate restructuring, family-business reckoning, mother-line career as long-arc commitment.' },
  { name: 'Saturn aspect Sun in 4th house : Starts', description: 'Home-discipline window opens.' },
  { name: 'Saturn aspect Sun in 4th house : Exact', description: 'Peak day. Take the slow real-estate decision, restructure the family business, formalize the mother-line career commitment.' },
  { name: 'Saturn aspect Sun in 4th house : Ends', description: 'Home-discipline window closes.' },
  { name: 'Saturn aspect Moon in 3rd house', description: 'Structural pressure on courageous communication. Long-arc content systems, sibling-channel formalization, broadcast-platform discipline.' },
  { name: 'Saturn aspect Moon in 3rd house : Starts', description: 'Communication-discipline window opens.' },
  { name: 'Saturn aspect Moon in 3rd house : Exact', description: 'Peak day. Lock in the multi-year content schedule, formalize the sibling-channel structure, sign the broadcast-platform contract.' },
  { name: 'Saturn aspect Moon in 3rd house : Ends', description: 'Communication-discipline window closes.' },
  { name: 'Saturn aspect Mercury in 5th house', description: 'Structural pressure on creative-intellect. The 3-year script, the cohort-compounding course, the slow speculative thesis.' },
  { name: 'Saturn aspect Mercury in 5th house : Starts', description: 'Creative-discipline window opens.' },
  { name: 'Saturn aspect Mercury in 5th house : Exact', description: 'Peak day. Commit to the multi-year creative project, lock in the course-platform structure, sign the long thesis.' },
  { name: 'Saturn aspect Mercury in 5th house : Ends', description: 'Creative-discipline window closes.' },
  { name: 'Saturn aspect Venus in 1st house', description: 'Structural pressure on the personal-brand throne. Slow founder-as-product evolution; vanity-aesthetics fall away; the durable brand sets in.' },
  { name: 'Saturn aspect Venus in 1st house : Starts', description: 'Personal-brand-discipline window opens.' },
  { name: 'Saturn aspect Venus in 1st house : Exact', description: 'Peak day. Eliminate the vanity-brand commitments; lock in the durable founder-product structure.' },
  { name: 'Saturn aspect Venus in 1st house : Ends', description: 'Personal-brand-discipline window closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Structural pressure on the partnership engine. Spouse-and-client commitments scrutinized; weak deals end; strong ones formalize.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Partnership-discipline window opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Peak day. Divorce the weak deal, formalize the strong JV, lock in the 30-year partnership structure.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Partnership-discipline window closes.' },
  { name: 'Saturn aspect Jupiter in 11th house', description: 'Structural pressure on the wide-network engine. Cooperative platforms formalize; international friend-circles deepen; board roles consolidate.' },
  { name: 'Saturn aspect Jupiter in 11th house : Starts', description: 'Network-discipline window opens.' },
  { name: 'Saturn aspect Jupiter in 11th house : Exact', description: 'Peak day. Sign the cooperative-platform charter, formalize the international friend-circle, accept the board seat.' },
  { name: 'Saturn aspect Jupiter in 11th house : Ends', description: 'Network-discipline window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Saturn on its own Sasa throne. Peak structural-career day of the multi-decade cycle. Chief-of-something crystallizes; legacy-grade authority sets in permanently.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Sasa-Yoga peak window opens. The decades of slow work converge.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak Sasa day. Accept the chief role, declare the legacy authority, formalize the permanent structure.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Sasa-Yoga peak window closes. Lock in title, contract, term — for the long horizon.' },
  { name: 'Saturn aspect Rahu in 8th house', description: 'Structural pressure in the foreign-occult chamber. Inheritance disputes, equity-event delays, foreign-mandate restructuring. Patience pays.' },
  { name: 'Saturn aspect Rahu in 8th house : Starts', description: 'Foreign-occult-discipline window opens.' },
  { name: 'Saturn aspect Rahu in 8th house : Exact', description: 'Peak day. Hold the line on the slow restructuring; do not accelerate against the structure.' },
  { name: 'Saturn aspect Rahu in 8th house : Ends', description: 'Foreign-occult-discipline window closes.' },
  { name: 'Saturn aspect Ketu in 2nd house', description: 'Structural pressure on voice-detachment. Old earning-paths formally close; the structural release is documented.' },
  { name: 'Saturn aspect Ketu in 2nd house : Starts', description: 'Voice-detachment-discipline window opens.' },
  { name: 'Saturn aspect Ketu in 2nd house : Exact', description: 'Peak day. Sign the formal closure of the dead earning channel.' },
  { name: 'Saturn aspect Ketu in 2nd house : Ends', description: 'Voice-detachment-discipline window closes.' },
  { name: 'Rahu aspect Sun in 4th house', description: 'Chaotic expansion on the home-throne. Foreign-property pull, family-business reinvention, real-estate fevers. Verify titles.' },
  { name: 'Rahu aspect Sun in 4th house : Starts', description: 'Home-chaos window opens.' },
  { name: 'Rahu aspect Sun in 4th house : Exact', description: 'Peak day. Vet the foreign-property paperwork before signing.' },
  { name: 'Rahu aspect Sun in 4th house : Ends', description: 'Home-chaos window closes.' },
  { name: 'Rahu aspect Moon in 3rd house', description: 'Chaotic expansion on courageous communication. Viral content, controversial journalism, sibling-channel intensities.' },
  { name: 'Rahu aspect Moon in 3rd house : Starts', description: 'Communication-chaos window opens.' },
  { name: 'Rahu aspect Moon in 3rd house : Exact', description: 'Peak day. Push the viral content — but check the integrity twice.' },
  { name: 'Rahu aspect Moon in 3rd house : Ends', description: 'Communication-chaos window closes.' },
  { name: 'Rahu aspect Mercury in 5th house', description: 'Chaotic expansion on creative-intellect. Speculative-fevers, viral-course pull, controversial public-stage moves.' },
  { name: 'Rahu aspect Mercury in 5th house : Starts', description: 'Creative-chaos window opens.' },
  { name: 'Rahu aspect Mercury in 5th house : Exact', description: 'Peak day. Take the speculative-creative move with full ethical-bedrock check.' },
  { name: 'Rahu aspect Mercury in 5th house : Ends', description: 'Creative-chaos window closes.' },
  { name: 'Rahu aspect Venus in 1st house', description: 'Chaotic expansion on the personal-brand throne. Viral founder-as-product moments, sudden aesthetic-pivots, controversial public-face shifts.' },
  { name: 'Rahu aspect Venus in 1st house : Starts', description: 'Personal-brand-chaos window opens.' },
  { name: 'Rahu aspect Venus in 1st house : Exact', description: 'Peak day. Take the bold aesthetic-pivot — but verify the underlying integrity.' },
  { name: 'Rahu aspect Venus in 1st house : Ends', description: 'Personal-brand-chaos window closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic expansion on the partnership engine. Foreign spouse, controversial JV, sudden anchor-client. Verify counterparty integrity.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Partnership-chaos window opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Peak day. Vet the controversial JV thoroughly; the deal can be real or it can be smoke.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Partnership-chaos window closes.' },
  { name: 'Rahu aspect Jupiter in 11th house', description: 'Chaotic expansion on the wide-network engine. Sudden viral-network gains, controversial cooperative-platform pulls.' },
  { name: 'Rahu aspect Jupiter in 11th house : Starts', description: 'Network-chaos window opens.' },
  { name: 'Rahu aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the viral-network move — but verify ethical bedrock.' },
  { name: 'Rahu aspect Jupiter in 11th house : Ends', description: 'Network-chaos window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Chaotic expansion on the Sasa-Yoga career engine. Sudden promotions, unconventional industries, foreign-career pull.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Career-chaos window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day. Take the unconventional career move — verify the institutional bedrock.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Career-chaos window closes.' },
  { name: 'Rahu aspect Rahu in 8th house', description: 'Rahu return on its strong terrain (8H). Peak transformation-chaos day. Equity events, inheritance-windfalls, foreign-occult breakthroughs — verify everything.' },
  { name: 'Rahu aspect Rahu in 8th house : Starts', description: 'Rahu-return window opens. Vet each opaque opportunity carefully.' },
  { name: 'Rahu aspect Rahu in 8th house : Exact', description: 'Peak Rahu-return day. Take the equity-event move with full documentation; the chaos is structural.' },
  { name: 'Rahu aspect Rahu in 8th house : Ends', description: 'Rahu-return window closes. Lock legitimate moves; release illusions.' },
  { name: 'Rahu aspect Ketu in 2nd house', description: 'Chaotic expansion on voice-detachment — Rahu-Ketu axis stress. Sudden earning-path turbulence; old voice-channel chaos.' },
  { name: 'Rahu aspect Ketu in 2nd house : Starts', description: 'Axis-chaos window opens.' },
  { name: 'Rahu aspect Ketu in 2nd house : Exact', description: 'Peak day. Defer voice-channel decisions; the axis is too loud for clean choice.' },
  { name: 'Rahu aspect Ketu in 2nd house : Ends', description: 'Axis-chaos window closes.' },
  { name: 'Ketu aspect Sun in 4th house', description: 'Detachment on the home-throne. Old real-estate plans feel weightless; family-business attachment dissolves.' },
  { name: 'Ketu aspect Sun in 4th house : Starts', description: 'Home-detachment window opens.' },
  { name: 'Ketu aspect Sun in 4th house : Exact', description: 'Peak day. Sit with the home-throne feeling weightless; do not panic-sell or panic-leave.' },
  { name: 'Ketu aspect Sun in 4th house : Ends', description: 'Home-detachment window closes.' },
  { name: 'Ketu aspect Moon in 3rd house', description: 'Detachment on courageous communication. Old content-loops feel finished; sibling-channel quiets.' },
  { name: 'Ketu aspect Moon in 3rd house : Starts', description: 'Communication-detachment window opens.' },
  { name: 'Ketu aspect Moon in 3rd house : Exact', description: 'Peak day. Release the content-loop that feels dead; the silence is information.' },
  { name: 'Ketu aspect Moon in 3rd house : Ends', description: 'Communication-detachment window closes.' },
  { name: 'Ketu aspect Mercury in 5th house', description: 'Detachment on creative-intellect. Old performance-loops feel finished; speculative cravings fall away.' },
  { name: 'Ketu aspect Mercury in 5th house : Starts', description: 'Creative-detachment window opens.' },
  { name: 'Ketu aspect Mercury in 5th house : Exact', description: 'Peak day. Release the dead creative-loop; the field is clearing for a new iteration.' },
  { name: 'Ketu aspect Mercury in 5th house : Ends', description: 'Creative-detachment window closes.' },
  { name: 'Ketu aspect Venus in 1st house', description: 'Detachment on the personal-brand throne. Old founder-as-product persona feels hollow; the magnetism quiets.' },
  { name: 'Ketu aspect Venus in 1st house : Starts', description: 'Personal-brand-detachment window opens.' },
  { name: 'Ketu aspect Venus in 1st house : Exact', description: 'Peak day. Sit with the brand feeling weightless; do not over-perform to compensate.' },
  { name: 'Ketu aspect Venus in 1st house : Ends', description: 'Personal-brand-detachment window closes.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Detachment on the partnership engine. Old deal feels finished; spouse / principal-client dynamic loosens.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Partnership-detachment window opens.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Peak day. Release the dead deal; the partnership has graduated.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Partnership-detachment window closes.' },
  { name: 'Ketu aspect Jupiter in 11th house', description: 'Detachment on the wide-network engine. Old friend-circles drift; bonus-pool feels detached; cooperative platforms quiet.' },
  { name: 'Ketu aspect Jupiter in 11th house : Starts', description: 'Network-detachment window opens.' },
  { name: 'Ketu aspect Jupiter in 11th house : Exact', description: 'Peak day. Release the friend-circle that has run its course; the network purifies.' },
  { name: 'Ketu aspect Jupiter in 11th house : Ends', description: 'Network-detachment window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Detachment on the Sasa-Yoga career engine. Old role feels weightless; the title that was the destination feels like a costume.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Career-eclipse window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day. Sit with the title feeling hollow; do not panic-leave; the new role is forming silently.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Career-eclipse window closes.' },
  { name: 'Ketu aspect Rahu in 8th house', description: 'Detachment on the foreign-occult chamber — Rahu-Ketu axis stress. Old crisis-loops dissolve; deep occult-research detachment.' },
  { name: 'Ketu aspect Rahu in 8th house : Starts', description: 'Axis-detachment window opens.' },
  { name: 'Ketu aspect Rahu in 8th house : Exact', description: 'Peak day. Release the crisis that has been the engine; the axis is rebalancing.' },
  { name: 'Ketu aspect Rahu in 8th house : Ends', description: 'Axis-detachment window closes.' },
  { name: 'Ketu aspect Ketu in 2nd house', description: 'Ketu return on voice-detachment. Old earning-paths formally close; the cravings around them dissolve.' },
  { name: 'Ketu aspect Ketu in 2nd house : Starts', description: 'Ketu-return window opens.' },
  { name: 'Ketu aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the earning channel that has been hollow for years; the return is clean.' },
  { name: 'Ketu aspect Ketu in 2nd house : Ends', description: 'Ketu-return window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} career] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
