// db/seed_food_capricorn.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to the
// user with:
//   Ascendant: Capricorn
//   Natal placements (sidereal Lahiri):
//     Sun=8th  Moon=10th  Mercury=8th  Venus=7th  Mars=9th
//     Jupiter=8th  Saturn=1st  Rahu=12th  Ketu=6th
//
// All 530 events below are the ones the kerykeion engine could emit for
// this user across any transitDate, narrowed from the full per-ascendant
// enumeration (~4,328 names) by the natal chart. Fill in the `description`
// strings as you compose food-specific interpretations, then run:
//
//   node db/seed_food_capricorn.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.
// Re-running with a filled description overwrites the existing row.

const db = require('./food');

const ASCENDANT = 'Capricorn';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS — fixed by ascendant + natal positions (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter ruler of the 12th House in the 8th House', description: 'Your dietary expansion comes through retreat, foreign cuisine, and quiet eating. Solo meals heal you more than feasts. Be cautious with shared dishes, communal pots, and food eaten in social pressure — the 12th-to-8th channel makes you absorb subtle toxins from group eating. Favor fasting one day a week; it produces wisdom no diet book gives. Foreign herbs (turmeric, ashwagandha, ginseng), monastery-style meals, ashram food, and ascetic plates carry medicine for you.' },
  { name: 'Jupiter ruler of the 3rd House in the 8th House', description: 'Your siblings\' and peers\' eating habits affect your digestion more than you realize. Sharing meals with younger people in the workplace can introduce both inspiration and contamination. Write down what you eat for one week and watch the patterns — Mercury-paired-with-Jupiter wisdom in the 8th gives forensic insight into food-mood-digestion links. Investigative eating: read labels, study ingredient origins, learn the chemistry of what enters your body.' },
  { name: 'Mars ruler of the 11th House in the 9th House', description: 'Your gains in vitality come through clean, principled, dharmic eating. Mars exalted in Virgo-9th rewards precision: weighed portions, measured macros, structured fasts, eating-times respected. Avoid the "casual" approach to food — your body is a Vedic discipline, not a hobby. Foreign / Ayurvedic / dharmic dietary traditions (sattvic eating, Mediterranean, Japanese, ancestral) compound health gains. Bitter and astringent tastes (turmeric, neem, dark leafy greens) are medicine.' },
  { name: 'Mars ruler of the 4th House in the 9th House', description: 'Your home cooking and your dharma are linked. The kitchen you build, the recipes you inherit from your mother, the food rules of your ancestral home all carry karmic weight in your eating life. Cook your own meals when possible — restaurant food carries spiritual residue you don\'t need. Vehicle-based eating (in cars, on the run) is the worst habit for your Mars-Virgo digestive precision; sit, breathe, eat slowly.' },
  { name: 'Mercury ruler of the 6th House in the 8th House', description: 'Your digestion is your daily dharma. The 6th-to-8th channel makes investigative eating your gift: you can identify a food sensitivity, an ingredient intolerance, a chronic-disease-food link that doctors miss. Track what you eat; pattern-match symptoms; treat your body like a forensic case. Avoid debt-eating (eating to numb, eating from anxiety, stress-eating). Workplace food (vending machines, conference catering) often introduces problems — bring your own.' },
  { name: 'Mercury ruler of the 9th House in the 8th House', description: 'Your dietary wisdom comes through unconventional teachers — an Ayurvedic doctor, an obscure book, a foreign nutritionist, a forensic-style investigation of your own gut. Trust the obscure path. Father-figure dietary advice (your dad\'s old habits, the family doctor) may not fit you — research and customize. Foreign herbs and supplements (Asian, Ayurvedic, ancestral) often work better than mainstream Western nutrition.' },
  { name: 'Moon ruler of the 7th House in the 10th House', description: 'Your eating is social. You eat differently around partners, clients, family. Be aware of the table — public eating cycles your appetite with mood. Watch business-dinner overeating, client-entertainment drinking, the "I\'ll have what they\'re having" reflex. Mother-figure recipes carry emotional medicine; cook her dishes when you\'re drained. Female cooking partners (spouse, mother, female cooks) shape your palate and health more than you realize.' },
  { name: 'Saturn ruler of the 1st House in the 1st House', description: 'Your body is Vata-Saturn dominant — slow digestion, prone to dryness, cold extremities, irregular bowels under stress. Counsel: warm cooked food over raw and cold; oils and ghee, not dry / crunchy / processed; root vegetables, soups, stews, oatmeal, kitchari. Eat at regular times; the body craves rhythm. Avoid skipping meals. Slow eating, chewing thoroughly, sitting down to eat are not luxuries — they are medicine for your structural digestion.' },
  { name: 'Saturn ruler of the 2nd House in the 1st House', description: 'Your speech and your eating share a karmic line — the 2nd house is both. Mindful, slow, conscious eating produces both better digestion and better speech. Family wealth often correlates with food wealth: ancestral recipes, family-grown ingredients, heritage foods. Frugality in eating is healthy — feast occasionally, fast occasionally, eat moderately the rest of the time. Avoid rich-people-eating-traps: tasting menus, lavish dinners, status-driven indulgence.' },
  { name: 'Sun ruler of the 8th House in the 8th House', description: 'Food is your transformation chamber. Pitta-Sun in 8th makes your digestion fierce — when balanced, you can digest things that would wreck others; when imbalanced, you experience intense heartburn, gastritis, ulcers. Cooling foods (coconut water, milk, ghee, sweet fruits, leafy greens) balance the inner fire. Avoid excessive spicy, oily, fried foods, alcohol — your inner Sun is already hot enough. Eat in regenerative cycles: a heavy meal, then lighter days.' },
  { name: 'Venus ruler of the 10th House in the 7th House', description: 'Beauty in food matters to you. The plate matters; the setting matters; the company matters. Aesthetic eating (presentation, ambiance, ritual) supports your status and your digestion equally. Female cooking partners are central. Watch luxury-eating: Venus in Cancer can drift into emotional eating (ice cream, comfort food, indulgent desserts) when stressed by relationship dynamics. Cook with love or eat what someone cooked with love — the emotional vibration of food matters as much as nutrients.' },
  { name: 'Venus ruler of the 5th House in the 7th House', description: 'Creative cooking, dining-with-partners, romantic meals, children\'s recipes all nourish you. Speculative eating (trying new restaurants, novel cuisines, experimental dishes) is favored when shared with a counterparty whose palate you trust. Sweet and creamy foods (Venus-Cancer signature) attract you — moderate them carefully, your Saturn-1st digestion can\'t handle excess sweet. Wine, rich desserts, dairy indulgence in social settings are real risks; pace yourself.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS — sign-lord placements (deduped) (6)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter in 8th (Dispositor)', description: 'Wisdom about food comes through transformative eating experiences — a fast, a cleanse, a foreign cuisine, a depth-research into nutrition. Take big questions about your body and digestion to Ayurvedic / functional-medicine / depth-practitioners, not mainstream nutrition books. The shadow: indulgence in shared eating (boozy dinners, communal feasts) — protect your digestive boundaries.' },
  { name: 'Mercury in 8th (Dispositor)', description: 'Investigative eating is your gift. Read ingredient labels, research suppliers, learn the chemistry of what enters your body. Forensic food awareness — you can pinpoint sensitivities, intolerances, hidden additives that affect mood and digestion. Avoid mindless eating; bring attention to every bite.' },
  { name: 'Moon in 10th (Dispositor)', description: 'Your eating is publicly visible — work-dinners, client-entertainments, mother\'s cooking shape your patterns. Mood-eating is real; protect against eating to manage difficult workdays. Female cooking influences (mother, spouse, women in your network) shape your palate. Eating in the public eye (TV, screens, group settings) reduces digestion quality — eat in calm, private warmth.' },
  { name: 'Saturn in 1st (Dispositor)', description: 'Your body wants rhythm above all. Eat at regular times; sleep at regular times; the discipline of routine IS the diet. Vata-dominant constitution: warm cooked foods, oils and ghee, root vegetables, soups, stews, kitchari. Avoid raw/cold/processed/skipping meals. Aging-friendly eating — your body wants the discipline more than the variety.' },
  { name: 'Sun in 8th (Dispositor)', description: 'Strong Pitta digestive fire — when balanced, you can transform food powerfully; when imbalanced, you burn yourself with heartburn, ulcers, gastritis. Cooling foods (coconut water, ghee, sweet fruits, leafy greens) balance the fire. Avoid excessive spicy, oily, fried, alcohol. Eat in regenerative cycles.' },
  { name: 'Venus in 7th (Dispositor)', description: 'Aesthetic eating matters to you — the plate, the setting, the company. Beautiful food digests better. Cook with love or eat what someone cooked with love — emotional vibration of food matters as much as nutrients. Watch comfort-eating in stressed partnerships; the sweet/creamy/luxurious cravings are real. Pace and ritual.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS — every planet through every house (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter Transits the 10th House', description: 'A year of business-dinners, client lunches, work-feasts, public eating events. Watch weight gain — Jupiter expands at the table. Choose status-meals carefully; cancel half. Female bosses and mentors may invite you to lavish meals; show up but eat moderately. Build the practice of leaving food on the plate.' },
  { name: 'Jupiter Transits the 11th House', description: 'Group eating intensifies — alumni dinners, network lunches, profit-sharing celebrations. Generous abundance may cause stomach trouble. Trust senior colleagues\' food recommendations but moderate portions. Foreign cuisines through wealthy peers introduce new palates worth keeping.' },
  { name: 'Jupiter Transits the 12th House', description: 'A year favoring foreign cuisine, retreat-style eating, monastery meals, ashram food. Solo meals heal you. Spending on foreign food (imported teas, exotic spices, ancestral medicines) is favored. Sleep affects appetite; protect rest. Watch hidden indulgence — secret snacks, hidden sweets, late-night eating.' },
  { name: 'Jupiter Transits the 1st House', description: 'A year your body expands. Watch weight gain; this transit is famous for it. Practice portion discipline; favor warm cooked foods over rich heavy ones. Increase movement to compensate. Best for: starting a structured Ayurvedic diet, hiring a nutritionist, formalizing eating discipline.' },
  { name: 'Jupiter Transits the 2nd House', description: 'A year of wealth-eating: rich foods, fine dining, family-feast traditions. Tongue-and-throat health gets emphasized. Watch dental issues, mouth ulcers, sweet-tooth excess. Family food traditions deepen — ancestral recipes, shared food rituals, feast-day cooking favored.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Communication-while-eating: peer lunches, sibling meals, short-trip food adventures. Younger colleagues introduce new foods. Best for: starting a food blog, recipe column, cooking class. Watch hand-to-mouth snacking during writing/computing.' },
  { name: 'Jupiter Transits the 4th House', description: 'Home cooking flourishes. Renovate the kitchen, expand the pantry, host family meals. Mother-figure recipes carry blessings. Real-estate of food (gardens, food storage, kitchen tools) thrives. Vehicle eating (in cars) is the worst habit; don\'t form it.' },
  { name: 'Jupiter Transits the 5th House', description: 'Speculative eating: novel dishes, experimental cuisine, food adventures with creative friends. Children\'s food, family-friendly meals, sweet treats expand. Watch sweet-tooth indulgence — Jupiter in Taurus loves luxury. Excellent for: cooking classes, recipe writing, food investment ventures.' },
  { name: 'Jupiter Transits the 6th House', description: 'Health-driven eating expands. Best year for: starting a nutritionist relationship, joining a wellness program, formalizing dietary discipline. Service-meals (eating at work, conference catering) increase. Pet food / animal nutrition gets attention. Watch over-doing the wellness routine.' },
  { name: 'Jupiter Transits the 7th House', description: 'A year of partner-eating: marriage meals, client dinners, business dining. Female counterparties shape your palate. Restaurant eating peaks; watch the cumulative caloric load. Marriage-of-business-interest dining (closing deals over fine meals) favored.' },
  { name: 'Jupiter Transits the 8th House', description: 'Transformative eating — fasting, cleansing, deep dietary resets. Inheritance-related foods (heirloom recipes, ancestral cookbooks) surface. Watch hidden / secret eating; depth-research into your own gut microbiome. Best for: medical-supervised cleanses, depth-Ayurvedic protocols.' },
  { name: 'Jupiter Transits the 9th House', description: 'A year favoring foreign cuisine, principled eating (vegetarian, kosher, halal, sattvic), pilgrimage-meals. Father-figure or guru dietary guidance lands. Best for: certifying as a nutrition practitioner, taking the dietary teaching role, traveling for food research.' },
  { name: 'Ketu Transits the 10th House', description: 'Public-eating fatigue. Business dinners feel hollow; client lunches drain rather than nourish. Reduce work-related eating commitments. Plain, simple meals (rice, dal, soup) restore vitality more than restaurant fare.' },
  { name: 'Ketu Transits the 11th House', description: 'Group meals lose appeal. Alumni dinners, network lunches feel performative. Skip the celebratory feasts; eat alone or with one trusted companion. Save the money typically spent on group eating for one quality private meal.' },
  { name: 'Ketu Transits the 12th House', description: 'Detachment from food itself — appetite quiets; fasting feels natural. This transit favors monastic-style eating: simple, sparse, contemplative. One meal a day is enough on many days. Use the period to detoxify, not to indulge.' },
  { name: 'Ketu Transits the 1st House', description: 'Body-detachment. Appetite fluctuates dramatically. Use the period for radical dietary simplification — eliminate one category at a time and observe. Weight may shift. Don\'t panic-diet; let the body recalibrate.' },
  { name: 'Ketu Transits the 2nd House', description: 'Family-food dynamics shift. Ancestral recipes feel less compelling; family wealth around food (heirloom cookware, generational pantry items) feels burdensome. Simplify the kitchen. Watch dental, throat, mouth issues.' },
  { name: 'Ketu Transits the 3rd House', description: 'Peer-eating loses charge. Lunch invitations from colleagues feel obligatory. Eat alone when possible. Hand-to-mouth snacking during writing decreases naturally; this is healthy.' },
  { name: 'Ketu Transits the 4th House', description: 'Home-cooking enthusiasm dims. The kitchen feels burdensome; mother-figure recipes feel less compelling. Order in or eat simply. Don\'t force home-cooking rituals during this period; they\'ll return naturally.' },
  { name: 'Ketu Transits the 5th House', description: 'Creative eating loses appeal. Experimental cuisine feels gimmicky. Sweet-tooth quiets. Speculative dining (new restaurants, food trends) feels hollow. Eat what your body actually needs, not what entertains your tongue.' },
  { name: 'Ketu Transits the 6th House', description: 'Service-meals, work-eating, conference catering all feel toxic. Bring your own food. Health diagnoses around food sensitivities surface — pay attention. Best for: elimination diets, allergy testing, identifying long-buried food triggers.' },
  { name: 'Ketu Transits the 7th House', description: 'Partner-eating loses charge. Restaurant dates feel performative; client dinners drain. Female-cooking-partner dynamics shift. Eat solo when possible; intimate meals at home with one person beat any external dining.' },
  { name: 'Ketu Transits the 8th House', description: 'Deep dietary truths surface. Hidden food sensitivities, gut imbalances, microbiome issues become undeniable. Best transit for: deep cleansing, fasting protocols, medical-supervised resets. Inheritance of dietary patterns from ancestors becomes visible.' },
  { name: 'Ketu Transits the 9th House', description: 'Father-figure dietary advice loses authority. Traditional / inherited dietary dogma falls away. Foreign cuisine still appealing but principled eating (vegetarian, sattvic) feels less compelling. Question every "rule" you inherited about food.' },
  { name: 'Mars Transits the 10th House', description: 'Stress-eating at work peaks. Public-eating events feel intense. Watch acidic foods, alcohol, spicy cuisine — Pitta is high. Cool the system: cucumber, coconut water, leafy greens. Don\'t skip meals during high-stakes meeting weeks.' },
  { name: 'Mars Transits the 11th House', description: 'Group-meal energy charged with competitive heat. Network dinners may turn argumentative. Watch alcohol intake during income-related celebrations; bonus-celebration drinking has a high price tag the next morning. Hydrate.' },
  { name: 'Mars Transits the 12th House', description: 'Foreign / hidden eating risks. Travel food poisoning more likely; restaurant hygiene matters more than usual. Sleep poorly; late-night snacking tempting. Hidden inflammation flares. Avoid alcohol and spicy foods entirely if possible.' },
  { name: 'Mars Transits the 1st House', description: 'Appetite surges; body wants protein and intensity. Best for starting a fitness-driven eating plan. Watch fast eating, gulping, throat-burning hot drinks (Mars-Capricorn body line). Hot soups and stews favored over cold raw food.' },
  { name: 'Mars Transits the 2nd House', description: 'Spicy / pungent foods attractive. Watch acid reflux, mouth ulcers, dental issues. Speech-eating connection: fights at the family table. Income-related stress eating: don\'t over-consume during salary-negotiation weeks. Soft-cooked foods, less spice.' },
  { name: 'Mars Transits the 3rd House', description: 'Fast eating during work sprints. Watch hand-to-mouth snacking, eating-while-typing, food-on-the-go. Schedule sit-down meals deliberately. Hot small meals (soup, broth) favored over cold large ones.' },
  { name: 'Mars Transits the 4th House', description: 'Family-table tension. Arguments at home over food choices. Watch fire/oven accidents, kitchen burns. Vehicle-eating risks. Cook calmly; avoid heated discussions over meals. Mother-figure cooking conflicts possible.' },
  { name: 'Mars Transits the 5th House', description: 'Speculative-eating impulse: trying every new restaurant, experimenting with hot cuisine. Watch chocolate/wine/comfort food cravings during creative work. Children\'s eating may be combative. Channel the heat into one disciplined experiment.' },
  { name: 'Mars Transits the 6th House', description: 'Operational eating energy strong. Excellent for resolving long-running food sensitivities through aggressive elimination diets. Work-related digestive issues flare. Pet/animal feeding takes attention. Watch repetitive-strain injuries from cooking.' },
  { name: 'Mars Transits the 7th House', description: 'Partner-eating tension. Couples fights over food choices. Client lunches go combative. Mars debilitated here means food aggression backfires. Eat calmly; defer fights about diet to better weeks.' },
  { name: 'Mars Transits the 8th House', description: 'Intense digestive transformation. Heartburn, ulcers, GI inflammation peak. Sexual-energy-food link surges. Best for: medical-supervised cleansing under fire. Worst for: spicy/oily/alcohol indulgence — your inner Sun is already hot.' },
  { name: 'Mars Transits the 9th House', description: 'Disciplined-precise eating peak. Best for: starting a strict Ayurvedic protocol, certifying in nutrition, foreign-cuisine deep dives, fasting under teacher guidance. Mars-Mars-Virgo precision favors clean eating, weighed portions.' },
  { name: 'Mercury Transits the 10th House', description: 'Work-eating awareness peaks. Track lunches with senior management; food-talk and career-talk overlap. Best for: writing about food professionally, recipe documentation, presenting nutrition findings.' },
  { name: 'Mercury Transits the 11th House', description: 'Friend / network food chat increases. Recipe-sharing, restaurant-recommendations, group cookbook conversations. Best for: joining a food-related committee, advisory work in nutrition / food industry.' },
  { name: 'Mercury Transits the 12th House', description: 'Quiet food research, journal entries about eating, foreign-cookbook study. Best for: writing your own food journal, researching ancestral diets, drafting personal eating philosophy.' },
  { name: 'Mercury Transits the 1st House', description: 'Eating-habit awareness sharpens. Best for: updating dietary plan, refreshing nutrition tracker, drafting personal-rules-around-food. Speak less while eating; communication-and-digestion overlap means talking too much erodes meal quality.' },
  { name: 'Mercury Transits the 2nd House', description: 'Family-food and food-finance conversations. Best for: discussing budget with cooking partner, reviewing grocery spending, drafting meal plans. Speech and food share the 2nd-house line — slow eating supports clearer talking.' },
  { name: 'Mercury Transits the 3rd House', description: 'Fast eating during writing/work; best for short-trip food adventures. Snacking during peer conversations. Watch dehydration during focus sprints. Hand-to-mouth food awareness.' },
  { name: 'Mercury Transits the 4th House', description: 'Kitchen-renovation thinking, recipe-cataloging, meal-planning peaks. Best for: organizing the pantry, writing the family recipe book, drafting kitchen upgrades. Mother-figure food conversations productive.' },
  { name: 'Mercury Transits the 5th House', description: 'Recipe writing, food blogging, cooking-class research favored. Children\'s food preferences in focus. Best for: documenting creative cooking experiments, drafting food content for advisory roles.' },
  { name: 'Mercury Transits the 6th House', description: 'Investigative eating peaks. Read every label, research every supplier, learn the chemistry. Best for: identifying food sensitivities through tracking, formalizing wellness routines, drafting digestive protocols.' },
  { name: 'Mercury Transits the 7th House', description: 'Partner-eating coordination. Best for: meal-planning with spouse, restaurant-research with client, drafting wedding menus / event catering. Female-counterparty cooking advice productive.' },
  { name: 'Mercury Transits the 8th House', description: 'Deep food research peaks. Microbiome study, gut-health investigation, depth-Ayurveda research. Best for: writing the canonical wellness brief, depth-interviewing a nutritionist, forensic-tracking your own digestion.' },
  { name: 'Mercury Transits the 9th House', description: 'Foreign cookbook study, principled / ethical food research, Ayurvedic certification work. Best for: writing about food philosophy, taking food-related exams, deep-diving into ancestral / dharmic eating traditions.' },
  { name: 'Moon Transits the 10th House', description: 'Public-eating window. Best for: business meals where warmth matters, hosting clients, mother-recipes shared with the team. Female-boss approval over food. Watch mood-eating in client-pressure situations.' },
  { name: 'Moon Transits the 11th House', description: 'Friend / network meals carry emotional charge. Best for: warm group dinners with trusted peers, alumni meals, family-style group cooking. Watch sweet-tooth at celebration meals.' },
  { name: 'Moon Transits the 12th House', description: 'Quiet, retreat-style eating preferred. Solo meals heal. Sleep affects appetite tonight. Watch midnight-snacking driven by restless dreams. Foreign / contemplative food (monastery meals, ashram fare) appealing.' },
  { name: 'Moon Transits the 1st House', description: 'Body-attunement to food peaks for the next 2.5 days. Listen to actual hunger; eat what the body needs. Best for: body-reset days, gentle one-meal-a-day eating, self-care cooking.' },
  { name: 'Moon Transits the 2nd House', description: 'Family-food emotion. Best for: cooking inherited recipes, sharing meals with mother-figures, reviewing grocery budget with care. Sweet cravings rise; moderate.' },
  { name: 'Moon Transits the 3rd House', description: 'Sensitive eating window. Younger colleagues open up over food; food-conversations land emotionally. Short-trip eating. Watch hand-to-mouth snacking during emotional writing.' },
  { name: 'Moon Transits the 4th House', description: 'Home-cooking peaks for the brief window. Mother\'s recipes, family-style meals, emotional comfort food. Best for: warm soups, slow stews, traditional dishes. Watch family-table emotional eating.' },
  { name: 'Moon Transits the 5th House', description: 'Exalted Moon — peak warm-creative eating. Best for: cooking with children, hosting friends, novel desserts, romantic dinners. Sweet and creamy foods (Moon-Taurus signature) digest well briefly.' },
  { name: 'Moon Transits the 6th House', description: 'Health-food sensitivity. Watch what you eat today; digestion is touchy. Pets / animals may need extra food attention. Workplace lunch may not agree with you. Bring home-cooked food.' },
  { name: 'Moon Transits the 7th House', description: 'Peak partner-eating. Cooking with spouse, eating with clients, family meals all favored. Female-counterparty palates align with yours. Watch over-empathic eating (eating because they\'re eating).' },
  { name: 'Moon Transits the 8th House', description: 'Deep-emotional eating. Cravings for transformation foods (rich, intense, dark — chocolate, red wine, dark spices). Watch shadow-eating triggered by buried emotions. Sleep affects digestion.' },
  { name: 'Moon Transits the 9th House', description: 'Father-figure / mentor recipe traditions appealing. Foreign cuisine wisdom lands emotionally. Best for: cooking ancestral recipes, exploring traditional cuisines from your father\'s heritage.' },
  { name: 'Rahu Transits the 10th House', description: 'A public-eating chapter with high stakes. Trendy restaurants, viral food experiences, status-meals all multiply. Watch chemical additives, processed-foods, novelty cuisines that mismatch your Vata-Saturn body. Trend-eating is risky for you.' },
  { name: 'Rahu Transits the 11th House', description: 'Network-eating goes unconventional. Strange dietary trends spread through your peer group. Try cautiously; your body responds slowly and aggressive trends backfire. Don\'t adopt every fad your wealthy friends introduce.' },
  { name: 'Rahu Transits the 12th House', description: 'Foreign cuisine cravings amplify. Hidden eating habits (secret snacks, late-night indulgence, addictive substances) intensify. Watch alcohol, addictive sweets, processed-food dependencies. Foreign herbs and Ayurveda may paradoxically help.' },
  { name: 'Rahu Transits the 1st House', description: 'Body undergoes radical changes. Rahu in Capricorn-1st often produces dramatic weight gain or unusual food cravings. Cravings for unconventional foods. Watch sudden food-allergy onset, autoimmune triggers.' },
  { name: 'Rahu Transits the 2nd House', description: 'Income-eating overlap: trendy expensive foods, status-driven dining. Watch dental issues, mouth cancer screenings warranted. Speech-and-food: family-financial fights at the table.' },
  { name: 'Rahu Transits the 3rd House', description: 'Snacking-while-doing skyrockets. Watch hand-to-mouth food during constant work. Younger peer eating habits influence yours unduly. Bring discipline to eating rituals.' },
  { name: 'Rahu Transits the 4th House', description: 'Home cooking goes unconventional — exotic recipes, foreign ingredients, kitchen experiments. Watch food-storage issues, refrigerator failures, vehicle-eating habits. Mother-figure dietary advice may feel outdated.' },
  { name: 'Rahu Transits the 5th House', description: 'Speculative eating peaks: exotic restaurants, novel cuisines, trendy diets. Watch sugar / dessert / wine indulgence. Children\'s unusual food demands. Fad-diet temptation; resist it.' },
  { name: 'Rahu Transits the 6th House', description: 'Sudden food sensitivities, unusual diagnoses, autoimmune-style reactions surface. Pet/animal feeding gets complicated. Service-meal contamination risks. Best for: thorough allergy testing, microbiome analysis, depth-research into chronic issues.' },
  { name: 'Rahu Transits the 7th House', description: 'Partner-eating gets unconventional. Foreign-cuisine dates, exotic restaurant deals, unusual wedding-style food. Female-counterparty introduces strange palates. Marriage-of-business-interest dining intense and chaotic.' },
  { name: 'Rahu Transits the 8th House', description: 'Profound dietary transformation. Hidden food sensitivities surface; ancestral microbiome shifts; transformative cleansing protocols. Watch addiction-eating, secret cravings, hidden food disorders. Best for: depth-medical food work.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign / unusual / controversial dietary philosophies attractive. Foreign teachers offer unconventional protocols. Watch fad-Ayurveda, gimmicky-spiritual eating. Discriminate carefully; not all foreign diets fit your Vata constitution.' },
  { name: 'Saturn Transits the 10th House', description: 'Disciplined work-eating. Best for: formalizing meal-prep habits, structured business-meal etiquette, sober career-dining. Female mentor figures may set healthy eating examples. Reduce alcohol at work events.' },
  { name: 'Saturn Transits the 11th House', description: 'Disciplined group eating. Reduce frequency of network meals; the few you keep are higher quality. Long-term eating-related friendships consolidate. Best for: structured eating among trusted friends.' },
  { name: 'Saturn Transits the 12th House', description: 'Frugal, monastic eating phase. Best for: simplifying diet to essentials, formalizing fasting practice, embracing sparse meals. Hidden food expenses surface — track them. Foreign herbs and traditional medicines worth investing in.' },
  { name: 'Saturn Transits the 1st House', description: 'Body-discipline peak. Sade Sati phase 2 — the body asks for the strictest eating discipline of your life. Vata-friendly: warm, oily, cooked, regular times. Slow eating mandatory. Reduce raw/cold/skipping meals. The diet you adopt now reshapes the next decade of body health.' },
  { name: 'Saturn Transits the 2nd House', description: 'Sade Sati phase 3 — frugal eating, family-food discipline. Income-related food spending under review. Family wealth around food consolidates. Speech-and-eating: slow chewing, no talking with mouth full, mindful meals.' },
  { name: 'Saturn Transits the 3rd House', description: 'Long-form eating discipline. Best for: writing the multi-year food journal, drafting the canonical family cookbook, building slow-but-permanent eating habits. Sibling-style peer eating may feel constrained.' },
  { name: 'Saturn Transits the 4th House', description: 'Home-cooking burdened. Kitchen renovations, food-storage issues, mother-figure dietary problems. Vehicle eating gets restricted. Best for: long-overdue kitchen repairs, food-storage formalization.' },
  { name: 'Saturn Transits the 5th House', description: 'Disciplined creative cooking. Reduce sweet indulgence (Saturn-Taurus restraint). Children\'s eating may be regimented. Best for: structured meal-planning for family, multi-year recipe documentation.' },
  { name: 'Saturn Transits the 6th House', description: 'Excellent for daily-eating discipline. Saturn favors 6th-house service-eating — meal-prep routines, daily nutrition tracking, formal wellness programs. Health-related food restrictions arrive; honor them.' },
  { name: 'Saturn Transits the 7th House', description: 'Partner-eating disciplined; restaurant frequency reduces. Marriage / business meals more sober and intentional. Female-cooking-partner relationships formalize. Long-term shared eating habits crystallize.' },
  { name: 'Saturn Transits the 8th House', description: 'Ashtam Shani — chronic dietary issues surface. Long-buried food sensitivities, microbiome problems, gut-health crises demand attention. Worst for: speculative diet experiments. Best for: methodical medical-supervised dietary protocols.' },
  { name: 'Saturn Transits the 9th House', description: 'Disciplined Ayurvedic / dharmic eating. Best for: completing nutrition certification, formalizing principled diet (vegetarian, sattvic), long-form foreign-cuisine training. Father-figure dietary mentorship formalizes.' },
  { name: 'Sun Transits the 10th House', description: 'Public-eating spotlight. Reduce work-meal frequency this month. Father-figure-boss food expectations may pressure overeating; politely refuse extras. Vitality dimmed — focus on simple cooked meals.' },
  { name: 'Sun Transits the 11th House', description: 'Vitality-peak network eating. Best for: leading group-cooking events, hosting peers, accepting senior dietary advice. Watch alcohol at celebratory bonus / equity dinners.' },
  { name: 'Sun Transits the 12th House', description: 'Solitary, contemplative eating month. Foreign cuisine, ashram meals, simple plates. Vitality lower than usual — eat warming, nourishing foods. Watch hidden indulgence, late-night snacking.' },
  { name: 'Sun Transits the 1st House', description: 'Body vitality month. Best for: starting a new eating routine, body-aware meal planning, fitness-driven nutrition. Reduce ego-driven indulgence (showy meals, status drinking).' },
  { name: 'Sun Transits the 2nd House', description: 'Family-food and income-food awareness. Father-figure financial decisions may affect eating budget. Speech-and-food: family meal conversations carry weight. Watch dental issues.' },
  { name: 'Sun Transits the 3rd House', description: 'Peer-eating with authority — host the team lunch, lead the colleague dinner. Short-trip food adventures. Sibling food-traditions surface. Best for: courageous food experiments backed by knowledge.' },
  { name: 'Sun Transits the 4th House', description: 'Exalted Sun in 4th — peak home-cooking authority. Mother-figure recipe wisdom shines. Best for: hosting family meals, kitchen pride, vehicle-related food (road trips with cooked food).' },
  { name: 'Sun Transits the 5th House', description: 'Creative cooking authority. Best for: writing recipes, hosting children\'s meals, advisory work in food/nutrition. Investment in food businesses favored. Watch indulgence and vanity-eating.' },
  { name: 'Sun Transits the 6th House', description: 'Health-eating victory month. Defeats long-running food sensitivities; identifies dietary weaknesses; debt-eating habits broken. Best for: starting new wellness program with father-figure-doctor guidance.' },
  { name: 'Sun Transits the 7th House', description: 'Sun debilitated in Cancer — partner-eating dynamics moderate. Female-cooking-counterparty may overshadow your dietary preferences. Best for: collaborative meal planning; worst for ego-driven food demands.' },
  { name: 'Sun Transits the 8th House', description: 'Annual digestive-fire reset. Best for: medical-supervised cleansing, depth-Ayurvedic protocols, surgical-precision dietary changes. Watch heartburn, ulcers, gastritis. Cool the inner Sun.' },
  { name: 'Sun Transits the 9th House', description: 'Father-figure-mentor dietary wisdom peaks. Best for: certification in nutrition, foreign-cuisine immersion, principled-eating commitment. Travel for food research favored.' },
  { name: 'Venus Transits the 10th House', description: 'Peak diplomatic-dining. Beautiful business meals, aesthetic plating, charm-driven hospitality. Female-boss / female-client food preferences favored. Watch luxury-meal cumulative load.' },
  { name: 'Venus Transits the 11th House', description: 'Warm group meals. Friend dinners, alumni gatherings, network-cookouts all favored. Best for: warm reconnections over food. Watch sweet / wine indulgence in social settings.' },
  { name: 'Venus Transits the 12th House', description: 'Foreign aesthetic cuisine, contemplative beautiful plating, behind-the-scenes hospitality. Best for: foreign romantic dinners, ashram-aesthetic meals. Watch hidden indulgence in expensive imported foods.' },
  { name: 'Venus Transits the 1st House', description: 'Body-magnetism through aesthetic eating. Best for: refining wardrobe-and-eating coordination, presenting yourself at elegant meals, deliberate aesthetic upgrades to your kitchen and table. Watch indulgence.' },
  { name: 'Venus Transits the 2nd House', description: 'Family-aesthetic cooking. Beautifully presented meals at home, harmonious family-food traditions. Best for: investing in beautiful kitchenware, refined dining setups, gracious income spending on food.' },
  { name: 'Venus Transits the 3rd House', description: 'Exalted Venus — peak creative/aesthetic eating window of the year. Best for: launching food blog, podcast, recipe column, food-photography work, peer cooking collaboration.' },
  { name: 'Venus Transits the 4th House', description: 'Aesthetic home cooking. Best for: kitchen aesthetic upgrades, hosting at home with refinement, mother-figure recipe collaboration, beautiful family meals. Vehicle-aesthetic-meals (picnics, food at scenic spots) favored.' },
  { name: 'Venus Transits the 5th House', description: 'Peak creative-aesthetic eating. Best for: novel desserts, romantic dinners, children\'s elegant meals, hosting the mentor gathering with refined food. Wine, fine chocolate, refined sweets attractive — moderate.' },
  { name: 'Venus Transits the 6th House', description: 'Beautiful daily-eating routines. Best for: organizing the pantry aesthetically, refining meal-prep habits, gentle wellness eating. Pet feeding gets warmth.' },
  { name: 'Venus Transits the 7th House', description: 'Peak partner-eating. Marriage meals, client-gala dining, romantic-business-interest dinners all favored. Female-cooking-partner relationships peak in warmth and inspiration.' },
  { name: 'Venus Transits the 8th House', description: 'Intimate, transformative beautiful eating. Best for: warm depth-conversations over meals, transformative cleansing with aesthetic care, shared-resource food decisions made warmly. Watch romantic-business-overlap dining traps.' },
  { name: 'Venus Transits the 9th House', description: 'Venus debilitated in Virgo — aesthetic-precision eating. Foreign cuisine warmly precise; principled eating with grace. Best for: warmly framed Ayurvedic / dharmic eating, foreign-cookbook study with appreciation.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS — Ascendant + Midheaven (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Body expansion. Watch weight gain. Mentors / wise elders may invite you to lavish meals; eat moderately. Shift toward warm cooked foods, oils, ghee, root vegetables.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Body-expansion energy fades. Tighten the eating discipline; the discipline you build now defends what Jupiter\'s window granted.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'A senior figure may host you for a generous meal today. Show up, eat moderately, leave food on the plate. Watch over-eating driven by gratitude.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Body-expansion energy rising. Plan ahead — meal-prep lighter for the upcoming feast-week.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Public-meal events expand. Business dinners, client lunches, conference catering all surge. Watch cumulative caloric load. Cancel half the optional meals.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Public-meal abundance fades. Detox days favored. Return to home cooking.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'A career-related lavish meal today (industry award dinner, big client signing). Show up, eat moderately, leave with energy intact.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Public-meal expansion rising. Prepare the body — light meals before, sleep more, move more.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Appetite quiets; body wants simplicity. Best for: one-meal-a-day, fasting, simple plates of rice + dal, gentle elimination of complex foods.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Body-detachment fades. Reintroduce solid meals gradually; don\'t shock the digestion with sudden feasts.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Appetite at its lowest today. Honor the body\'s signal. Light broth, simple rice, herbal tea may be all you need. Don\'t force a regular meal schedule.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Body-appetite quieting. Anticipate lighter eating; stock the kitchen with simple foods rather than complex ingredients.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Public-eating fatigue. Business dinners feel hollow. Decline non-essential work meals.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Public-meal fatigue lifts. Selectively re-engage the strategic ones.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Skip the work-meal today if possible. Eat alone or with one trusted person.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Public-meal interest dimming. Decline incoming dinner invitations gracefully.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Body fire surges. Spicy / pungent cravings rise. Watch heartburn, mouth ulcers, throat irritation. Cool foods (coconut, cucumber, melon, leafy greens) balance the heat.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Body-fire energy fades. Recovery foods: ghee, sweet rice, milk, ripe fruits. Replenish what Mars burned.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Avoid spicy / oily / fried / alcohol today. Eat cool, soft, sweet foods. Drink coconut water. Hydrate aggressively.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Body heat rising. Pre-cool with hydration, ghee, simple cooked foods.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Stress-eating at work. Skip alcohol and spicy meals during high-pressure days. Bring home-cooked food rather than relying on office catering.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Work-stress eating fades. Recovery foods, longer meal breaks, no skipped meals.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak stress-eating risk today. Pack lunch from home; avoid the conference catering, the client-dinner alcohol.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Work-stress eating building. Stock the desk with healthy snacks for the high-pressure week ahead.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Awareness-around-eating sharp. Best for: tracking food intake, journaling meals, drafting personal eating rules.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Eating-tracking momentum fades. Lock in the patterns identified. Schedule a follow-up review next month.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak food-awareness day. Write down what you eat, exact portions, time, mood before/after. Patterns become clear.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Eating-awareness rising. Set up the food journal, the tracking app, the meal-prep calendar.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Work-meal coordination. Best for: planning client-dinner menus, drafting team-lunch preferences, food-related public memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Work-meal coordination window narrows. Lock in the bookings, send the menu approvals.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day for work-meal planning. Send the catering email, finalize the menu, schedule the client dining.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Work-meal coordination rising. Outline the upcoming work-related food events.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Body listens to mood; mood listens to food. Eat what your body actually needs today, not what your schedule prescribes.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Body-mood-food sensitivity fades. Return to structured meal times.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak intuitive-eating day. Trust hunger, trust fullness. Body knows.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Intuitive-eating window opening. Soften the rigid meal schedule for a day.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Mood-eating at work. Watch comfort-eating in pressure moments. Female-boss-meal warmth peaks; honor those invitations.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Mood-work-eating connection fades. Return to disciplined work-meal patterns.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional eating risk in work context. Watch the urge to bond with team over food. Eat what your body needs.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Mood-work-eating connection rising. Pre-plan healthy work meals.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Body cravings shift unusually. Foreign / processed / addictive foods attract. Watch body-image-driven extreme dieting; resist fads.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Unusual cravings fade. Return to disciplined Vata-friendly eating.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak cravings for novelty / foreign / addictive food. Resist; eat home cooked simple meals.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Unusual food cravings rising. Notice the impulse; don\'t act on it impulsively.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Trendy work-meals — the new restaurant the team wants to try, the viral food trend invading the office. Try cautiously; your body responds slowly.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Work-food trend appeal fades. Return to home-cooked office lunches.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak work-food trend pull. Politely decline the gimmick; eat what you brought.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Work-food trend pressure rising. Stock the desk for resistance.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Body discipline maximum. Vata-friendly: warm, oily, cooked, regular times. Slow eating mandatory.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Discipline-window narrows. The patterns built now are permanent; don\'t lose them in the relaxation phase.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak body-discipline day. Eat the simplest, warmest, most measured meal of the week.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Body discipline rising. Plan ahead; stock warm cooked staples.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public-meal discipline peaks. Reduce work-eating frequency; the few you keep are higher quality.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Public-meal discipline window narrows. Lock in the patterns of fewer, better work meals.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day for sober work-meal etiquette. Decline the alcohol, leave food on the plate, eat for substance not show.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Sober work-meal energy rising. Prepare to politely decline excess.' },
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Body vitality sharpens; appetite increases. Best for: starting body-aware eating plan, fitness-driven nutrition. Watch ego-eating (showy meals).' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Body-vitality window narrows. Maintain the routines you built; don\'t let post-peak relaxation undo them.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak body-vitality day. Best for: starting a new physical-nutrition routine, eating a substantive but disciplined meal.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Body-vitality rising. Stock vitality-supporting foods (warm cooked, ghee, root vegetables).' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Public-meal authority. Father-figure-boss food expectations may pressure. Decline the third drink with a smile.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Authority-driven public eating window narrows. Return to home cooking.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak public-meal authority moment. Lead the table with composure; eat moderately to model leadership.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Public-meal authority energy rising. Prepare to host or attend the high-visibility meal with dignity.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Body aesthetic peaks. Plate beauty, refined cuisine, sweet/creamy attractions. Indulge mindfully.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Aesthetic-eating window narrows. Settle into post-indulgence detox.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak aesthetic-eating day. Beautiful plates, fine ingredients, romantic dining. Pace the indulgence.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Aesthetic-eating energy rising. Plan the elegant meal for the peak.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Public-meal warmth. Host the elegant client dinner, deliver the aesthetically refined business meal.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Public-meal warmth window narrows. Lock in the partnerships forged at the table.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak warm-public-meal day. Sign the partnership over dinner, host the gala, deliver the beautiful business meal.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Warm-public-meal energy rising. Plan the elegant work-event for the peak.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER-PLANET SPECIALS — Uranus-Venus, Pluto-Saturn (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generation-defining body restructuring. The constitution itself shifts; foods that worked for years stop working. Best for: complete dietary overhaul under medical supervision; worst for: clinging to old eating habits.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The deep dietary restructuring window narrows. Lock in the new eating reality; the changes are permanent.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak constitutional-shift day. A long-tolerated food finally rejects you; a new eating pattern crystallizes. Accept the body\'s verdict.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Deep dietary restructuring rising. Begin researching the new approach; the old way is breaking.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden food-relationship shifts. Female cooking partners may change; restaurant relationships transform. Watch impulsive food allergies, sudden palette shifts.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Sudden food-relationship shifts settle. Integrate the new dietary configuration with cooking partners.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'A food-relationship shifts suddenly today. Receive the change with composure.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Unconventional food-relationship energy rising. Pay attention to sudden cravings or aversions.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS — natal house fixed by birth chart (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Jupiter aspect Jupiter in 8th house', description: 'Mentor-blessed dietary expansion. A wise nutritionist or Ayurvedic practitioner enters your eating life. Trust depth-counsel about food. Watch generosity at the table.' },
  { name: 'Jupiter aspect Jupiter in 8th house : Ends', description: 'Wise-eating window narrows. Lock the depth-counsel learnings into permanent dietary practice.' },
  { name: 'Jupiter aspect Jupiter in 8th house : Exact', description: 'A food-mentor offers transformative counsel today. Listen; act. Watch indulgence in the moment of insight.' },
  { name: 'Jupiter aspect Jupiter in 8th house : Starts', description: 'Wise-eating energy rising. Open to depth-nutritionist introductions, ancestral food wisdom.' },
  { name: 'Jupiter aspect Ketu in 6th house', description: 'Dietary detoxification expands gracefully. Body-cleansing, gut healing, debt-eating habits dissolve.' },
  { name: 'Jupiter aspect Ketu in 6th house : Ends', description: 'Cleansing window narrows. Solidify the streamlined daily-eating routine.' },
  { name: 'Jupiter aspect Ketu in 6th house : Exact', description: 'A long-running food sensitivity resolves today; chronic gut issue clears. Reduce, don\'t add.' },
  { name: 'Jupiter aspect Ketu in 6th house : Starts', description: 'Cleansing-eating energy rising. Plan the gentle elimination protocol.' },
  { name: 'Jupiter aspect Mars in 9th house', description: 'Disciplined-precise dharmic eating peaks. Best for: starting Ayurvedic protocol, foreign-cuisine immersion, sattvic eating commitment.' },
  { name: 'Jupiter aspect Mars in 9th house : Ends', description: 'Disciplined-eating window narrows. Lock the principled food rules into long-term practice.' },
  { name: 'Jupiter aspect Mars in 9th house : Exact', description: 'Peak day to commit to the disciplined diet. Sign up for the Ayurvedic course, accept the food-philosophy guide, formalize the eating commitment.' },
  { name: 'Jupiter aspect Mars in 9th house : Starts', description: 'Disciplined-eating energy rising. Research the principled protocol you\'ll commit to at peak.' },
  { name: 'Jupiter aspect Mercury in 8th house', description: 'Investigative food research blooms. Deep-dive into your gut microbiome, ancestral food sensitivities, depth-Ayurveda.' },
  { name: 'Jupiter aspect Mercury in 8th house : Ends', description: 'Food-investigation window narrows. Document the findings into permanent reference.' },
  { name: 'Jupiter aspect Mercury in 8th house : Exact', description: 'A food-investigation breakthrough today. The pattern in your symptoms becomes clear; the dietary answer arrives.' },
  { name: 'Jupiter aspect Mercury in 8th house : Starts', description: 'Food-investigation energy rising. Schedule the depth-research, the microbiome test, the Ayurvedic consultation.' },
  { name: 'Jupiter aspect Moon in 10th house', description: 'Public-meal warmth amplifies. Female-mentor recipes shared with team; client-meals carry both nourishment and goodwill.' },
  { name: 'Jupiter aspect Moon in 10th house : Ends', description: 'Warm-public-meal window narrows. Lock the partnerships built over food.' },
  { name: 'Jupiter aspect Moon in 10th house : Exact', description: 'A senior female figure shares a generous meal today. Show up warmly, eat moderately, leave with relationship deepened.' },
  { name: 'Jupiter aspect Moon in 10th house : Starts', description: 'Warm-public-meal energy rising. Plan the elegant-warm hosting for peak.' },
  { name: 'Jupiter aspect Rahu in 12th house', description: 'Foreign cuisine wisdom expands. Ancestral medicines, exotic herbs, foreign Ayurvedic herbs all valuable.' },
  { name: 'Jupiter aspect Rahu in 12th house : Ends', description: 'Foreign-cuisine window narrows. Stock the imported essentials, settle the foreign-food relationships.' },
  { name: 'Jupiter aspect Rahu in 12th house : Exact', description: 'A foreign-food breakthrough today: an ancestral remedy works, an exotic herb resolves an issue, a foreign nutrition framework aligns.' },
  { name: 'Jupiter aspect Rahu in 12th house : Starts', description: 'Foreign-cuisine energy rising. Open to imported herbal recommendations, foreign cookbook research.' },
  { name: 'Jupiter aspect Saturn in 1st house', description: 'Body discipline meets grace. The sober eating routine softens just enough to become sustainable.' },
  { name: 'Jupiter aspect Saturn in 1st house : Ends', description: 'Disciplined-grace eating window narrows. The routine you built is now reference; live it.' },
  { name: 'Jupiter aspect Saturn in 1st house : Exact', description: 'A formal commitment to long-term eating discipline crystallizes today (joining a wellness program, hiring a permanent nutritionist, formalizing the daily ritual).' },
  { name: 'Jupiter aspect Saturn in 1st house : Starts', description: 'Disciplined-grace energy rising. Research the long-form eating commitment.' },
  { name: 'Jupiter aspect Sun in 8th house', description: 'Body fire transformation through wise eating. Best for: medical-supervised fasting, depth-Ayurvedic protocols, surgical-precision dietary regeneration.' },
  { name: 'Jupiter aspect Sun in 8th house : Ends', description: 'Transformation-eating window narrows. The new dietary reality is yours; live it.' },
  { name: 'Jupiter aspect Sun in 8th house : Exact', description: 'Peak transformation-eating day. The cleansing protocol delivers; the regenerative dietary breakthrough crystallizes.' },
  { name: 'Jupiter aspect Sun in 8th house : Starts', description: 'Transformation-eating energy rising. Plan the medical-supervised cleanse for peak.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Peak warm-partner-eating window. Marriage-of-business-interest dining, exclusive client meals, romantic warm dinners all favored.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Warm-partner-meal window narrows. Lock the partnerships forged over food.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Sign the partnership over an elegant meal today. Host the gala, deliver the warm business dining.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Warm-partner-meal energy rising. Plan the elegant partnership dining for peak.' },
  { name: 'Ketu aspect Jupiter in 8th house', description: 'Mentor-counsel about food fades; depth-eating insights feel less compelling. Keep the routines that work; don\'t add new theories.' },
  { name: 'Ketu aspect Jupiter in 8th house : Ends', description: 'Detached-from-food-wisdom phase passes. Reconnect gently with the eating practices that fit your body.' },
  { name: 'Ketu aspect Jupiter in 8th house : Exact', description: 'Food advice from old mentors feels hollow today. Trust your body over external counsel.' },
  { name: 'Ketu aspect Jupiter in 8th house : Starts', description: 'Mentor-food-counsel detachment rising. Notice which food advice no longer serves.' },
  { name: 'Ketu aspect Ketu in 6th house', description: 'Daily routines simplify; chronic food sensitivities resolve quietly. Less is more.' },
  { name: 'Ketu aspect Ketu in 6th house : Ends', description: 'Service-eating simplification window narrows. Keep the streamlined patterns.' },
  { name: 'Ketu aspect Ketu in 6th house : Exact', description: 'A long-running food sensitivity self-resolves today; a daily routine simplifies. Accept the lightness.' },
  { name: 'Ketu aspect Ketu in 6th house : Starts', description: 'Service-eating simplification rising. Begin pruning unnecessary supplements, rituals.' },
  { name: 'Ketu aspect Mars in 9th house', description: 'Disciplined dharmic eating loses urgency. Strict protocols feel less compelling. Don\'t abandon entirely; just soften the rigidity.' },
  { name: 'Ketu aspect Mars in 9th house : Ends', description: 'Discipline-fatigue passes. Reconnect with principled eating in gentler form.' },
  { name: 'Ketu aspect Mars in 9th house : Exact', description: 'The strict diet feels exhausting today. Take a relaxation day; resume tomorrow.' },
  { name: 'Ketu aspect Mars in 9th house : Starts', description: 'Discipline-fatigue rising. Plan a gentle refresh of the dietary practice.' },
  { name: 'Ketu aspect Mercury in 8th house', description: 'Investigative food awareness quiets. Stop researching; let the body inform you directly.' },
  { name: 'Ketu aspect Mercury in 8th house : Ends', description: 'Investigation-fatigue passes. Resume gentle tracking when interest returns naturally.' },
  { name: 'Ketu aspect Mercury in 8th house : Exact', description: 'Stop reading nutrition articles today. Eat simply, intuitively.' },
  { name: 'Ketu aspect Mercury in 8th house : Starts', description: 'Investigation-fatigue rising. Pause the elaborate food tracking.' },
  { name: 'Ketu aspect Moon in 10th house', description: 'Public-meal interest drains. Decline non-essential work-eating; eat alone or simply.' },
  { name: 'Ketu aspect Moon in 10th house : Ends', description: 'Public-meal apathy fades. Selectively re-engage strategic meals.' },
  { name: 'Ketu aspect Moon in 10th house : Exact', description: 'Skip the work-meal today. Eat at your desk, in private, simply.' },
  { name: 'Ketu aspect Moon in 10th house : Starts', description: 'Public-meal disinterest rising. Decline incoming work-meal invitations.' },
  { name: 'Ketu aspect Rahu in 12th house', description: 'Foreign-food cravings dissolve quietly. Hidden eating habits surface for clarification.' },
  { name: 'Ketu aspect Rahu in 12th house : Ends', description: 'Foreign-food obsession fades. Settle into simpler eating.' },
  { name: 'Ketu aspect Rahu in 12th house : Exact', description: 'Foreign-cuisine cravings vanish today; a hidden food habit (secret snacking, late-night eating) surfaces. Be honest about it.' },
  { name: 'Ketu aspect Rahu in 12th house : Starts', description: 'Foreign-food obsession quieting. Notice which exotic foods you no longer crave.' },
  { name: 'Ketu aspect Saturn in 1st house', description: 'Body-discipline fatigues. The strict eating regimen feels suffocating today. Take a relaxation day. Don\'t panic-quit.' },
  { name: 'Ketu aspect Saturn in 1st house : Ends', description: 'Body-discipline fatigue passes. Return to the routine in gentler form.' },
  { name: 'Ketu aspect Saturn in 1st house : Exact', description: 'Don\'t enforce strict eating today. Body wants permission; give it. Resume tomorrow.' },
  { name: 'Ketu aspect Saturn in 1st house : Starts', description: 'Body-discipline fatigue rising. Plan a gentle relaxation in the routine.' },
  { name: 'Ketu aspect Sun in 8th house', description: 'Digestive fire dims temporarily. Eat very simply; skip the rich foods. Watch fatigue around eating.' },
  { name: 'Ketu aspect Sun in 8th house : Ends', description: 'Digestive-fire dimming passes. Slowly reintroduce variety.' },
  { name: 'Ketu aspect Sun in 8th house : Exact', description: 'Digestive fire at its lowest today. Light broth, simple rice, soft foods. Avoid heavy / spicy / fried entirely.' },
  { name: 'Ketu aspect Sun in 8th house : Starts', description: 'Digestive-fire dimming rising. Stock simple foods.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Partner-eating loses charge. Restaurant dates feel performative. Eat simply at home.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Partner-eating apathy fades. Resume the warm intimate dining gradually.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Date-night dining feels hollow today. Order in or eat solo.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Partner-eating disinterest rising. Adjust the social-dining calendar.' },
  { name: 'Mars aspect Jupiter in 8th house', description: 'Aggressive cleansing protocols favored. Mentor-supervised fasts, intense detox routines. Watch over-doing it.' },
  { name: 'Mars aspect Jupiter in 8th house : Ends', description: 'Cleansing-intensity window narrows. Reintroduce solid foods gradually.' },
  { name: 'Mars aspect Jupiter in 8th house : Exact', description: 'Peak cleansing fire today. Push through the supervised fast; trust the depth-counsel guiding it.' },
  { name: 'Mars aspect Jupiter in 8th house : Starts', description: 'Cleansing-intensity energy rising. Stock the protocol ingredients.' },
  { name: 'Mars aspect Ketu in 6th house', description: 'Aggressive elimination diet. Cut suspected food triggers cleanly. Watch overzealous restriction.' },
  { name: 'Mars aspect Ketu in 6th house : Ends', description: 'Elimination-fight window narrows. Note which foods stayed eliminated; reintroduce others gently.' },
  { name: 'Mars aspect Ketu in 6th house : Exact', description: 'Decisive elimination today. Cut the suspected food entirely; observe the body\'s response.' },
  { name: 'Mars aspect Ketu in 6th house : Starts', description: 'Elimination energy rising. Identify the suspect; prepare to cut it.' },
  { name: 'Mars aspect Mars in 9th house', description: 'Disciplined-precise eating peaks. Best for: military-grade portion control, weighed meals, exact macro tracking.' },
  { name: 'Mars aspect Mars in 9th house : Ends', description: 'Precision-eating window narrows. Lock in the macros that worked.' },
  { name: 'Mars aspect Mars in 9th house : Exact', description: 'Peak day for surgical precision: weigh every meal, time every fast, measure every portion.' },
  { name: 'Mars aspect Mars in 9th house : Starts', description: 'Precision-eating energy rising. Set up the food scale, the meal-prep containers.' },
  { name: 'Mars aspect Mercury in 8th house', description: 'Aggressive food-research. Pin down the gut culprit; identify the hidden trigger.' },
  { name: 'Mars aspect Mercury in 8th house : Ends', description: 'Investigation-aggression window narrows. Send the test results to the practitioner.' },
  { name: 'Mars aspect Mercury in 8th house : Exact', description: 'Peak forensic-eating day. Read every label, research every ingredient origin.' },
  { name: 'Mars aspect Mercury in 8th house : Starts', description: 'Aggressive-investigation energy rising. Order the lab tests, schedule the practitioner visit.' },
  { name: 'Mars aspect Moon in 10th house', description: 'Stress-eating at high-stakes work meals. Bring home cooked food; refuse the catered options.' },
  { name: 'Mars aspect Moon in 10th house : Ends', description: 'Stress-eating window narrows. Recover with simple meals.' },
  { name: 'Mars aspect Moon in 10th house : Exact', description: 'Peak stress-eating risk in work context today. Pack lunch; refuse the catering.' },
  { name: 'Mars aspect Moon in 10th house : Starts', description: 'Work-stress eating rising. Stock home-cooked meals for the upcoming pressure week.' },
  { name: 'Mars aspect Rahu in 12th house', description: 'Foreign / hidden food risks. Travel food poisoning more likely; restaurant hygiene matters more.' },
  { name: 'Mars aspect Rahu in 12th house : Ends', description: 'Travel-food risk window narrows. Reset gut with simple foods.' },
  { name: 'Mars aspect Rahu in 12th house : Exact', description: 'Avoid foreign / unfamiliar foods today. Eat what you know is clean.' },
  { name: 'Mars aspect Rahu in 12th house : Starts', description: 'Travel-food risk rising. Plan careful eating around upcoming trips.' },
  { name: 'Mars aspect Saturn in 1st house', description: 'Body fire surges into Saturn-disciplined frame. Intense eating discipline at peak.' },
  { name: 'Mars aspect Saturn in 1st house : Ends', description: 'Body-fire-discipline window narrows. Maintain the rhythm built.' },
  { name: 'Mars aspect Saturn in 1st house : Exact', description: 'Peak body-discipline fire today. Maximum precision in eating; minimum indulgence.' },
  { name: 'Mars aspect Saturn in 1st house : Starts', description: 'Body-fire-discipline rising. Plan the strict eating week ahead.' },
  { name: 'Mars aspect Sun in 8th house', description: 'Intense digestive transformation. Heartburn, ulcers, GI issues flare. Cool the inner Sun.' },
  { name: 'Mars aspect Sun in 8th house : Ends', description: 'Digestive-fire window narrows. Soothing foods, ghee, cooked vegetables.' },
  { name: 'Mars aspect Sun in 8th house : Exact', description: 'Peak heartburn / ulcer / gastritis risk today. Coconut water, milk with cardamom, sweet rice. Avoid spicy / oily / alcohol entirely.' },
  { name: 'Mars aspect Sun in 8th house : Starts', description: 'Digestive-fire intensity rising. Cool the system in advance.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Partner-eating tension. Couples fights over food choices; client meals go combative. Eat calmly.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Partner-eating tension window narrows. Restore the warm dining routine.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Worst day for partner-food fights. Defer dietary disagreements; eat what\'s easy.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Partner-eating friction rising. Avoid food-related arguments before peak.' },
  { name: 'Mercury aspect Jupiter in 8th house', description: 'Investigative-wise food research. Read the canonical Ayurvedic text, the depth-nutrition book.' },
  { name: 'Mercury aspect Jupiter in 8th house : Ends', description: 'Wise-research window narrows. Document the findings.' },
  { name: 'Mercury aspect Jupiter in 8th house : Exact', description: 'Peak day to write the comprehensive food-protocol document for yourself.' },
  { name: 'Mercury aspect Jupiter in 8th house : Starts', description: 'Wise-research energy rising. Schedule the depth-counsel reading.' },
  { name: 'Mercury aspect Ketu in 6th house', description: 'SOP for daily eating. Best for documenting what works, eliminating what doesn\'t.' },
  { name: 'Mercury aspect Ketu in 6th house : Ends', description: 'SOP-window narrows. Lock the routines into the kitchen wall.' },
  { name: 'Mercury aspect Ketu in 6th house : Exact', description: 'Write your daily eating SOP today. Simple, clear, sustainable.' },
  { name: 'Mercury aspect Ketu in 6th house : Starts', description: 'SOP energy rising. Outline the daily routine.' },
  { name: 'Mercury aspect Mars in 9th house', description: 'Disciplined recipe research. Foreign / Ayurvedic recipe documentation.' },
  { name: 'Mercury aspect Mars in 9th house : Ends', description: 'Recipe-precision window narrows. Lock the canonical recipes.' },
  { name: 'Mercury aspect Mars in 9th house : Exact', description: 'Peak day to write the precise canonical recipe for the family / future generations.' },
  { name: 'Mercury aspect Mars in 9th house : Starts', description: 'Recipe-precision energy rising. Outline the canonical recipe project.' },
  { name: 'Mercury aspect Mercury in 8th house', description: 'Forensic food clarity peaks. Pin down the trigger, the pattern, the answer.' },
  { name: 'Mercury aspect Mercury in 8th house : Ends', description: 'Forensic clarity window narrows. Lock the findings into permanent reference.' },
  { name: 'Mercury aspect Mercury in 8th house : Exact', description: 'The food-puzzle solves itself today. Write down the answer.' },
  { name: 'Mercury aspect Mercury in 8th house : Starts', description: 'Forensic clarity energy rising. Set up the analysis tools.' },
  { name: 'Mercury aspect Moon in 10th house', description: 'Public-meal coordination. Plan client-dinner menus with care.' },
  { name: 'Mercury aspect Moon in 10th house : Ends', description: 'Coordination window narrows. Send the menu approvals.' },
  { name: 'Mercury aspect Moon in 10th house : Exact', description: 'Finalize the public-meal menu today.' },
  { name: 'Mercury aspect Moon in 10th house : Starts', description: 'Public-meal coordination rising. Outline the menus.' },
  { name: 'Mercury aspect Rahu in 12th house', description: 'Foreign-cookbook research, hidden ancestral recipes documentation.' },
  { name: 'Mercury aspect Rahu in 12th house : Ends', description: 'Foreign-research window narrows. Archive findings.' },
  { name: 'Mercury aspect Rahu in 12th house : Exact', description: 'Peak day for ancestral / foreign cookbook research.' },
  { name: 'Mercury aspect Rahu in 12th house : Starts', description: 'Foreign-research energy rising. Find the right cookbooks.' },
  { name: 'Mercury aspect Saturn in 1st house', description: 'Personal-eating-rules clarity. Draft the structured plan.' },
  { name: 'Mercury aspect Saturn in 1st house : Ends', description: 'Plan-clarity window narrows. Print and post the rules.' },
  { name: 'Mercury aspect Saturn in 1st house : Exact', description: 'Write the formal personal eating constitution today.' },
  { name: 'Mercury aspect Saturn in 1st house : Starts', description: 'Eating-rules clarity rising. Outline the constitution.' },
  { name: 'Mercury aspect Sun in 8th house', description: 'Authority-driven food investigation. Father-figure doctor or Ayurveda teacher endorses your protocol.' },
  { name: 'Mercury aspect Sun in 8th house : Ends', description: 'Authority-research window narrows. Lock the endorsed protocol.' },
  { name: 'Mercury aspect Sun in 8th house : Exact', description: 'Peak day to consult the senior food authority. Write down their recommendations.' },
  { name: 'Mercury aspect Sun in 8th house : Starts', description: 'Authority-research energy rising. Schedule the senior consultation.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Partner-meal coordination. Plan family meals, romantic dinners, client menus together.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Coordination window narrows. Send the meal-plan to the partner.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Plan the next month\'s shared meals together today.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Partner-meal-planning rising. Outline the menus.' },
  { name: 'Moon aspect Jupiter in 8th house', description: 'Mentor-warm meals. Eat with the wise figure today.' },
  { name: 'Moon aspect Jupiter in 8th house : Ends', description: 'Warm-mentor-meal charge fades.' },
  { name: 'Moon aspect Jupiter in 8th house : Exact', description: 'Share a meal with a depth-counsel figure today; cooking in their kitchen heals.' },
  { name: 'Moon aspect Jupiter in 8th house : Starts', description: 'Mentor-meal warmth rising. Schedule the visit.' },
  { name: 'Moon aspect Ketu in 6th house', description: 'Daily eating feels uninspiring. Eat simply.' },
  { name: 'Moon aspect Ketu in 6th house : Ends', description: 'Service-meal apathy lifts.' },
  { name: 'Moon aspect Ketu in 6th house : Exact', description: 'Lunch feels mechanical today; honor it as nutrition, not pleasure.' },
  { name: 'Moon aspect Ketu in 6th house : Starts', description: 'Service-meal apathy rising.' },
  { name: 'Moon aspect Mars in 9th house', description: 'Father-figure / mentor recipe traditions emotionally resonant.' },
  { name: 'Moon aspect Mars in 9th house : Ends', description: 'Mentor-recipe charge fades.' },
  { name: 'Moon aspect Mars in 9th house : Exact', description: 'Cook the ancestral / mentor-taught recipe today; share it.' },
  { name: 'Moon aspect Mars in 9th house : Starts', description: 'Mentor-recipe energy rising. Source the right ingredients.' },
  { name: 'Moon aspect Mercury in 8th house', description: 'Investigative eating with empathic charge. Track food and mood together.' },
  { name: 'Moon aspect Mercury in 8th house : Ends', description: 'Tracking-empathy fades.' },
  { name: 'Moon aspect Mercury in 8th house : Exact', description: 'Note the precise food-mood link today; the pattern is briefly visible.' },
  { name: 'Moon aspect Mercury in 8th house : Starts', description: 'Tracking-empathy rising. Open the food-mood journal.' },
  { name: 'Moon aspect Moon in 10th house', description: 'Peak emotional-public meal. Female-mentor / female-boss meal land warmly.' },
  { name: 'Moon aspect Moon in 10th house : Ends', description: 'Public-meal warmth fades.' },
  { name: 'Moon aspect Moon in 10th house : Exact', description: 'The 12-hour window for the warm public-meal moment of the month.' },
  { name: 'Moon aspect Moon in 10th house : Starts', description: 'Warm-public-meal energy rising.' },
  { name: 'Moon aspect Rahu in 12th house', description: 'Foreign-food cravings tinged with emotion. Watch midnight-snacking from restless dreams.' },
  { name: 'Moon aspect Rahu in 12th house : Ends', description: 'Foreign-food-mood fades.' },
  { name: 'Moon aspect Rahu in 12th house : Exact', description: 'Foreign cuisine cravings peak today. Indulge mindfully or substitute with familiar comfort food.' },
  { name: 'Moon aspect Rahu in 12th house : Starts', description: 'Foreign-food cravings rising emotionally.' },
  { name: 'Moon aspect Saturn in 1st house', description: 'Body listens to mood; eat what the body actually wants today.' },
  { name: 'Moon aspect Saturn in 1st house : Ends', description: 'Body-mood-food fades.' },
  { name: 'Moon aspect Saturn in 1st house : Exact', description: 'Trust hunger, trust fullness today; intuitive eating wins.' },
  { name: 'Moon aspect Saturn in 1st house : Starts', description: 'Body-mood-food window opening. Soften meal schedule.' },
  { name: 'Moon aspect Sun in 8th house', description: 'Emotional-eating around father-figure dynamics. Watch shadow eating triggered by buried emotions.' },
  { name: 'Moon aspect Sun in 8th house : Ends', description: 'Emotional-eating-trigger fades.' },
  { name: 'Moon aspect Sun in 8th house : Exact', description: 'Heavy emotional-eating trigger today. Notice; substitute with movement, water, breath.' },
  { name: 'Moon aspect Sun in 8th house : Starts', description: 'Emotional-eating triggers rising. Pre-empt with awareness.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Peak partner-eating warmth. Cook with spouse, eat with clients warmly.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Partner-warmth fades.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Host the warm intimate dinner today.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Partner-warmth rising. Plan the dinner.' },
  { name: 'Rahu aspect Jupiter in 8th house', description: 'Foreign / unconventional dietary protocols spread. Try cautiously.' },
  { name: 'Rahu aspect Jupiter in 8th house : Ends', description: 'Trend-protocol window narrows. Keep what worked.' },
  { name: 'Rahu aspect Jupiter in 8th house : Exact', description: 'Peak temptation to try the trendy unconventional protocol. Resist if Vata-Saturn body says no.' },
  { name: 'Rahu aspect Jupiter in 8th house : Starts', description: 'Trend-protocol energy rising.' },
  { name: 'Rahu aspect Ketu in 6th house', description: 'Sudden food sensitivities surface. Best for thorough allergy testing.' },
  { name: 'Rahu aspect Ketu in 6th house : Ends', description: 'Sensitivity-surfacing window narrows. Adjust diet.' },
  { name: 'Rahu aspect Ketu in 6th house : Exact', description: 'A surprise food reaction today. Note it; eliminate the trigger.' },
  { name: 'Rahu aspect Ketu in 6th house : Starts', description: 'Food-reaction energy rising. Order allergy testing.' },
  { name: 'Rahu aspect Mars in 9th house', description: 'Unusual / controversial dietary philosophy attractive. Discriminate carefully.' },
  { name: 'Rahu aspect Mars in 9th house : Ends', description: 'Controversial-protocol pull fades.' },
  { name: 'Rahu aspect Mars in 9th house : Exact', description: 'Peak pull toward the unconventional dietary teacher. Verify before committing.' },
  { name: 'Rahu aspect Mars in 9th house : Starts', description: 'Controversial-protocol energy rising.' },
  { name: 'Rahu aspect Mercury in 8th house', description: 'Viral food-research trends spread. Read critically; apply selectively.' },
  { name: 'Rahu aspect Mercury in 8th house : Ends', description: 'Viral-food-info window narrows. Pin down what\'s yours.' },
  { name: 'Rahu aspect Mercury in 8th house : Exact', description: 'Peak day for viral nutrition info. Read deeply, sleep on it before changing diet.' },
  { name: 'Rahu aspect Mercury in 8th house : Starts', description: 'Viral-food-info energy rising.' },
  { name: 'Rahu aspect Moon in 10th house', description: 'Trendy work-eating events multiply. Choose carefully; your body responds slowly.' },
  { name: 'Rahu aspect Moon in 10th house : Ends', description: 'Work-trend-meal window narrows.' },
  { name: 'Rahu aspect Moon in 10th house : Exact', description: 'Peak trendy work-meal pressure. Politely decline the gimmick.' },
  { name: 'Rahu aspect Moon in 10th house : Starts', description: 'Trendy work-meal pressure rising.' },
  { name: 'Rahu aspect Rahu in 12th house', description: 'Foreign-cuisine cravings surge unusually. Hidden indulgences amplify.' },
  { name: 'Rahu aspect Rahu in 12th house : Ends', description: 'Foreign-craving inflation fades.' },
  { name: 'Rahu aspect Rahu in 12th house : Exact', description: 'Peak unusual food cravings today. Substitute with home-cooked simple foods.' },
  { name: 'Rahu aspect Rahu in 12th house : Starts', description: 'Foreign-craving inflation rising.' },
  { name: 'Rahu aspect Saturn in 1st house', description: 'Body-image-driven extreme dieting temptation. Resist fad diets.' },
  { name: 'Rahu aspect Saturn in 1st house : Ends', description: 'Extreme-diet temptation fades.' },
  { name: 'Rahu aspect Saturn in 1st house : Exact', description: 'Peak temptation toward extreme dieting today. Stick with steady Vata-friendly eating.' },
  { name: 'Rahu aspect Saturn in 1st house : Starts', description: 'Extreme-diet temptation rising.' },
  { name: 'Rahu aspect Sun in 8th house', description: 'Sudden digestive shifts; transformative cleansing protocols intense. Watch addiction-eating.' },
  { name: 'Rahu aspect Sun in 8th house : Ends', description: 'Cleansing-intensity window narrows.' },
  { name: 'Rahu aspect Sun in 8th house : Exact', description: 'Peak transformative-eating intensity. Honor the body\'s clear yes-or-no on each food.' },
  { name: 'Rahu aspect Sun in 8th house : Starts', description: 'Transformative-eating energy rising.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Foreign-cuisine partner dates, exotic restaurant adventures. Discriminate.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Exotic-restaurant window narrows.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Peak exotic-dining temptation today. If you go, eat carefully.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Exotic-restaurant energy rising. Research before committing.' },
  { name: 'Saturn aspect Jupiter in 8th house', description: 'Long-form structured eating with mentor wisdom. Hire the permanent nutritionist.' },
  { name: 'Saturn aspect Jupiter in 8th house : Ends', description: 'Structural-mentor-eating window narrows. Lock the relationship.' },
  { name: 'Saturn aspect Jupiter in 8th house : Exact', description: 'Sign the long-term wellness contract today.' },
  { name: 'Saturn aspect Jupiter in 8th house : Starts', description: 'Structural-mentor-eating energy rising.' },
  { name: 'Saturn aspect Ketu in 6th house', description: 'Long-running food sensitivities formally resolved. Document the diet for the long term.' },
  { name: 'Saturn aspect Ketu in 6th house : Ends', description: 'Resolution window narrows. Lock the avoidance list.' },
  { name: 'Saturn aspect Ketu in 6th house : Exact', description: 'The chronic food trigger is officially identified today; the elimination is permanent.' },
  { name: 'Saturn aspect Ketu in 6th house : Starts', description: 'Resolution energy rising.' },
  { name: 'Saturn aspect Mars in 9th house', description: 'Multi-year disciplined dharmic eating commitment.' },
  { name: 'Saturn aspect Mars in 9th house : Ends', description: 'Multi-year-commitment window narrows. Live the practice.' },
  { name: 'Saturn aspect Mars in 9th house : Exact', description: 'Commit formally to the multi-year dharmic eating practice today.' },
  { name: 'Saturn aspect Mars in 9th house : Starts', description: 'Multi-year-commitment energy rising. Research the right framework.' },
  { name: 'Saturn aspect Mercury in 8th house', description: 'Long-form documentation of personal food research. Write the canonical reference.' },
  { name: 'Saturn aspect Mercury in 8th house : Ends', description: 'Documentation window narrows.' },
  { name: 'Saturn aspect Mercury in 8th house : Exact', description: 'Finalize the multi-year personal food document today.' },
  { name: 'Saturn aspect Mercury in 8th house : Starts', description: 'Documentation energy rising. Outline the canonical reference.' },
  { name: 'Saturn aspect Moon in 10th house', description: 'Public-meal habits formalize. Female-mentor food recommendations crystallize.' },
  { name: 'Saturn aspect Moon in 10th house : Ends', description: 'Formalization window narrows.' },
  { name: 'Saturn aspect Moon in 10th house : Exact', description: 'Lock the public-meal etiquette today: how you eat in client / boss settings becomes structural.' },
  { name: 'Saturn aspect Moon in 10th house : Starts', description: 'Formalization energy rising.' },
  { name: 'Saturn aspect Rahu in 12th house', description: 'Long-form foreign-food relationship structures. Imported herbs become permanent kitchen staples.' },
  { name: 'Saturn aspect Rahu in 12th house : Ends', description: 'Structural-foreign window narrows.' },
  { name: 'Saturn aspect Rahu in 12th house : Exact', description: 'Settle the foreign-supplement subscription today; commit to the herb supplier long-term.' },
  { name: 'Saturn aspect Rahu in 12th house : Starts', description: 'Structural-foreign-food energy rising.' },
  { name: 'Saturn aspect Saturn in 1st house', description: 'Body discipline restructures at the deepest level. The constitution changes.' },
  { name: 'Saturn aspect Saturn in 1st house : Ends', description: 'Constitutional-restructuring window narrows. Live the new reality.' },
  { name: 'Saturn aspect Saturn in 1st house : Exact', description: 'Peak constitutional shift today. The diet that worked at 30 stops working at 40 — adapt now.' },
  { name: 'Saturn aspect Saturn in 1st house : Starts', description: 'Constitutional-restructuring energy rising.' },
  { name: 'Saturn aspect Sun in 8th house', description: 'Methodical digestive-fire restructuring. Long-form Ayurvedic protocol favored.' },
  { name: 'Saturn aspect Sun in 8th house : Ends', description: 'Restructuring window narrows.' },
  { name: 'Saturn aspect Sun in 8th house : Exact', description: 'The medical-supervised long-term protocol completes today.' },
  { name: 'Saturn aspect Sun in 8th house : Starts', description: 'Restructuring energy rising. Hire the long-term Ayurvedic doctor.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Multi-year shared eating habits with partner formalize.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Shared-eating-formalization narrows.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Commit to the long-term shared kitchen / shared meal-prep / shared diet today.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Shared-eating-formalization energy rising.' },
  { name: 'Sun aspect Jupiter in 8th house', description: 'Father-figure-mentor publicly endorses your dietary practice.' },
  { name: 'Sun aspect Jupiter in 8th house : Ends', description: 'Mentor-endorsement window narrows.' },
  { name: 'Sun aspect Jupiter in 8th house : Exact', description: 'A senior-figure approves your eating protocol today; the validation strengthens commitment.' },
  { name: 'Sun aspect Jupiter in 8th house : Starts', description: 'Mentor-endorsement energy rising.' },
  { name: 'Sun aspect Ketu in 6th house', description: 'Father-figure / boss support in operational eating dispute.' },
  { name: 'Sun aspect Ketu in 6th house : Ends', description: 'Operational-support window narrows.' },
  { name: 'Sun aspect Ketu in 6th house : Exact', description: 'A senior figure backs your dietary boundary today (e.g., dietary requirement honored at work events).' },
  { name: 'Sun aspect Ketu in 6th house : Starts', description: 'Operational-support energy rising.' },
  { name: 'Sun aspect Mars in 9th house', description: 'Father-figure mentor validates your principled eating.' },
  { name: 'Sun aspect Mars in 9th house : Ends', description: 'Validation window narrows.' },
  { name: 'Sun aspect Mars in 9th house : Exact', description: 'A father-figure mentor endorses the dharmic / principled diet today.' },
  { name: 'Sun aspect Mars in 9th house : Starts', description: 'Validation energy rising.' },
  { name: 'Sun aspect Mercury in 8th house', description: 'Authority-driven food investigation. Senior doctor / Ayurveda teacher endorses your protocol.' },
  { name: 'Sun aspect Mercury in 8th house : Ends', description: 'Authority-research window narrows.' },
  { name: 'Sun aspect Mercury in 8th house : Exact', description: 'Senior practitioner endorses your protocol today.' },
  { name: 'Sun aspect Mercury in 8th house : Starts', description: 'Authority-research energy rising.' },
  { name: 'Sun aspect Moon in 10th house', description: 'Father-figure boss endorses warm public meals. Female-mentor recipes shared with team.' },
  { name: 'Sun aspect Moon in 10th house : Ends', description: 'Endorsement window narrows.' },
  { name: 'Sun aspect Moon in 10th house : Exact', description: 'Peak warm public meal with senior endorsement today.' },
  { name: 'Sun aspect Moon in 10th house : Starts', description: 'Warm public-meal energy rising.' },
  { name: 'Sun aspect Rahu in 12th house', description: 'Father-figure-boss endorses foreign-cuisine investment.' },
  { name: 'Sun aspect Rahu in 12th house : Ends', description: 'Foreign-endorsement window narrows.' },
  { name: 'Sun aspect Rahu in 12th house : Exact', description: 'A senior figure endorses the imported herb / supplement protocol today.' },
  { name: 'Sun aspect Rahu in 12th house : Starts', description: 'Foreign-endorsement energy rising.' },
  { name: 'Sun aspect Saturn in 1st house', description: 'Body vitality publicly recognized. Personal-brand around physical discipline crystallizes.' },
  { name: 'Sun aspect Saturn in 1st house : Ends', description: 'Vitality-recognition window narrows.' },
  { name: 'Sun aspect Saturn in 1st house : Exact', description: 'Body-discipline visibly recognized today (gym milestone, weight goal, public health validation).' },
  { name: 'Sun aspect Saturn in 1st house : Starts', description: 'Vitality-recognition energy rising.' },
  { name: 'Sun aspect Sun in 8th house', description: 'Annual digestive-fire reset. Father-figure boss may exit; food-related authority shifts.' },
  { name: 'Sun aspect Sun in 8th house : Ends', description: 'Annual reset window narrows.' },
  { name: 'Sun aspect Sun in 8th house : Exact', description: 'Annual digestive-fire reset day. Best for: medical-supervised cleanse start, depth Ayurvedic protocol initiation.' },
  { name: 'Sun aspect Sun in 8th house : Starts', description: 'Annual reset energy rising. Plan the cleanse.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Father-figure-boss endorses warm partner-meal events.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Endorsement window narrows.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'A senior figure publicly hosts the partnership dinner today.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Warm partnership-meal endorsement energy rising.' },
  { name: 'Venus aspect Jupiter in 8th house', description: 'Aesthetic depth-eating with mentor presence. Beautifully plated cleansing meals.' },
  { name: 'Venus aspect Jupiter in 8th house : Ends', description: 'Aesthetic-depth window narrows.' },
  { name: 'Venus aspect Jupiter in 8th house : Exact', description: 'Mentor introduces the beautifully aesthetic protocol today.' },
  { name: 'Venus aspect Jupiter in 8th house : Starts', description: 'Aesthetic-depth energy rising.' },
  { name: 'Venus aspect Ketu in 6th house', description: 'Gracious daily eating routines. Beautify the simple plate.' },
  { name: 'Venus aspect Ketu in 6th house : Ends', description: 'Gracious-routine window narrows.' },
  { name: 'Venus aspect Ketu in 6th house : Exact', description: 'Set up the elegant minimalist eating ritual today.' },
  { name: 'Venus aspect Ketu in 6th house : Starts', description: 'Gracious-routine energy rising.' },
  { name: 'Venus aspect Mars in 9th house', description: 'Warm-precise dharmic eating. Beautifully presented Ayurvedic meals.' },
  { name: 'Venus aspect Mars in 9th house : Ends', description: 'Warm-precise window narrows.' },
  { name: 'Venus aspect Mars in 9th house : Exact', description: 'Cook the beautifully precise dharmic meal today; share the photograph.' },
  { name: 'Venus aspect Mars in 9th house : Starts', description: 'Warm-precise energy rising.' },
  { name: 'Venus aspect Mercury in 8th house', description: 'Empathic food research. Investigative writing about food with warmth.' },
  { name: 'Venus aspect Mercury in 8th house : Ends', description: 'Empathic-research window narrows.' },
  { name: 'Venus aspect Mercury in 8th house : Exact', description: 'Write the warm-toned food essay / blog post today.' },
  { name: 'Venus aspect Mercury in 8th house : Starts', description: 'Empathic-food-research energy rising.' },
  { name: 'Venus aspect Moon in 10th house', description: 'Peak warm-public-meal aesthetic. Female-mentor / female-client dining gracefully.' },
  { name: 'Venus aspect Moon in 10th house : Ends', description: 'Warm-public-meal window narrows.' },
  { name: 'Venus aspect Moon in 10th house : Exact', description: 'Host the elegant warm public meal today.' },
  { name: 'Venus aspect Moon in 10th house : Starts', description: 'Warm-public-meal energy rising.' },
  { name: 'Venus aspect Rahu in 12th house', description: 'Foreign romance over food. Exotic aesthetic cuisine.' },
  { name: 'Venus aspect Rahu in 12th house : Ends', description: 'Exotic-aesthetic window narrows.' },
  { name: 'Venus aspect Rahu in 12th house : Exact', description: 'The beautiful foreign meal today, the imported wine, the exotic dessert. Indulge mindfully.' },
  { name: 'Venus aspect Rahu in 12th house : Starts', description: 'Exotic-aesthetic energy rising.' },
  { name: 'Venus aspect Saturn in 1st house', description: 'Personal-eating aesthetic crystallizes. Beautiful plating becomes ritual.' },
  { name: 'Venus aspect Saturn in 1st house : Ends', description: 'Aesthetic-ritual window narrows.' },
  { name: 'Venus aspect Saturn in 1st house : Exact', description: 'The ritual of beautiful plating becomes habit today.' },
  { name: 'Venus aspect Saturn in 1st house : Starts', description: 'Aesthetic-ritual energy rising.' },
  { name: 'Venus aspect Sun in 8th house', description: 'Surgical eating with grace. The cleansing protocol made beautiful.' },
  { name: 'Venus aspect Sun in 8th house : Ends', description: 'Graceful-cleanse window narrows.' },
  { name: 'Venus aspect Sun in 8th house : Exact', description: 'The transformative meal made beautiful today.' },
  { name: 'Venus aspect Sun in 8th house : Starts', description: 'Graceful-cleanse energy rising.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Peak warm-partner-meal of the year. Marriage-of-business-interest dining peaks.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Annual partner-meal peak window narrows.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'The flagship warm-partner meal of the year today.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Annual partner-meal peak energy rising.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
