// db/seed_advice_virgo.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own — 11L in 11H)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga, yogakaraka)
//     Venus=7th (Pisces, exalted — Malavya Yoga, 2L+9L Dhana-Dharma)
//     Mars=8th (Aries, own)  Jupiter=4th (Sagittarius, own — Hamsa Yoga, 4L+7L)
//     Saturn=5th (Capricorn, own — 5L+6L)  Rahu=9th (Taurus)  Ketu=3rd (Scorpio)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose advice-specific interpretations, then run:
//
//   node db/seed_advice_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./advice');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'Lead with precision. Today the room is reading you for analytical sharpness, articulation quality, attention to detail. Body, voice, vocabulary all carry signal — lean clean, articulate, deliberate. Refresh the bio, polish the personal pitch, walk in as the principal-craftsman. Do: ship the technical clarification, lead the analyst meeting, deliver the precise note. Avoid: vague talk, sloppy execution, rushed deliverables. The shadow: perfectionism that delays the release; ship the 90% draft.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'Today money and partnership move together. The income channel is open through the partner / spouse / principal client. Do: have the warm money-conversation with partner, sign the JV memo, take the family-finance meeting with in-laws. Avoid: solo financial moves disconnected from the partnership context; the money this chart attracts comes through relationship.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'Today communication carries transformational weight. The message you send lands in someone\'s crisis chamber — be precise, warm, deliberate. Sibling-channel deals have surgical edge; brothers/sisters carry weight in restructuring chapters. Do: write the careful inheritance email, send the considered crisis-communication. Avoid: aggressive notes that detonate.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'Today the home-throne is the engine. The wisdom-source for this day is the family seat, the lineage, the mother-channel. Do: take the family-business meeting at home, host the elders, eat the heritage meal, make the property decision with lineage-consciousness. Avoid: trading the home-base advantage for the flashy capital; your power compounds at the family seat.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Today disciplined creative work pays. The long-arc project, the slow-burn romance, the structured creative collaboration all favor today. Do: commit to the multi-month protocol, write the long-form piece, take the patient teaching role with mentees. Avoid: rushing the rough draft to publication; this engine rewards the institutional cadence.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'Today daily-routine carried as discipline becomes the moat. The audit memo, the protocol, the spreadsheet, the methodology you build today is the structural defense against future chaos. Do: document the system, lock the recurring schedule, write the SOP. Avoid: turning every relationship into a compliance exercise; warmth must coexist with rigor.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Today partnership routes through home and family. The spouse decision, the anchor-client conversation, the principal-collaborator move all pick up dharma weight when held in lineage-context. Do: bring the partner home, take the in-law meeting seriously, host at the family seat. Avoid: confusing the family\'s preferred partner with your dharma-correct partner.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'Today the surgical-transformation engine is hot. Crisis-management, restructuring, equity-event, life-or-death advisory move under your hand cleanly. Do: walk into the burning room with discipline, close the inheritance / severance / M&A move, carry the system-stabilization mantle. Avoid: thrill-seeking that confuses adrenaline for dharma; the 8th rewards the surgeon, not the cowboy.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'Today dharma and partner converge. The teacher-track decision and the partner-track decision are the same decision. Do: take the foreign-pilgrimage planning conversation, pick the dharma-aligned anchor-client, marry the principle-aligned partner. Avoid: confusing partner-pleasure with dharma-truth.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'Today personal craftsmanship is the path to status. The slow, deliberate, principal-of-X moves compound. Do: refresh the bio, lead the technical pitch, accept the principal-track appointment, sign the founder declaration. Avoid: looking for shortcuts; this engine rewards the multi-decade-cadence player.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Today the wide-network gains channel runs warm. Reach out to alumni, community, peer-trust circle, the long-arc female-friend network. Do: send the warm note to the old colleague, accept the board-advisory call, take the cooperative-platform meeting. Avoid: emotional-reactivity in group politics; protect sleep on big network days.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'Today solitude is productive. Foreign-front work, behind-the-scenes mandates, retreat-strategy drafts, white papers all favor. The light is dimmed publicly, but quiet authority compounds. Do: write the next-quarter strategy alone, take the confidential meeting, carry the foreign mandate. Avoid: forcing visibility; today rewards the shadow-lane player.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, the confidential / foreign / behind-the-scenes mandate carries the day. Retreat, white paper, embassy posting, off-balance-sheet strategy.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, the wide-network gains channel pays. Alumni introductions, community-led wins, bonus-pool conversations, equity vesting events.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, the precision-yogakaraka pays. Lead with personal craftsmanship; the body, voice, and articulation are the channel of advancement.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, the home-and-lineage channel pays. Real-estate decisions, family-business inflection, mother-line introduction to the anchor opportunity.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, the surgical-crisis chapter opens. Restructuring, inheritance, severance, M&A — walk in disciplined, walk out with the system stabilized.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, slow creative discipline produces compounding output. Long-form publication, doctoral milestone, structured creative leadership.' },
  { name: 'Venus in 7th (Dispositor)', description: 'When this engine fires, the partnership engine pays. Anchor partner, spouse, principal collaborator carry the chapter. Move through the relational channel, not solo.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak personal-visibility window. Body radiates; the principal-craftsman framing lands. Reset the personal brand, take the public mantle, stake the founder declaration. Watch ego-friction with father-figures.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on income, voice, family-finance. Negotiate the salary, record the talk, pin the family-money decision. Throat-care matters; vocal-led work favored.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on writing and short-burst effort. Send the bold note, ship the document, push the campaign. Ketu zone — keep the message warm, not detached.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home-throne. Real-estate decisions, family-business inflections, mother-line conversations all favored. Father-figures press their mark on lineage decisions.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on disciplined-creative output. Best window for the long-form analysis, the curriculum, the doctoral milestone, the structured-creative product. Mentor-of-mentees roles light up.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on adversary-management. Hard HR conversations, compliance filings, lawsuits you have postponed all favor offensive action. Adversaries weaken.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on partnerships. Spouse and principal-client visibility peak. Sign the anchor partnership; demand JV terms; take the deal public.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in transformation chamber. Career moves take surgical edge. Inheritance, severance matters surface. Mars own-territory — sharp, disciplined execution rewarded.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma engine. International-stage talks, certifications, judicial proceedings, teacher-mentor moves. Rahu zone — unconventional teacher / foreign stage materializes.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility window. Best for launching the flagship initiative, demanding the title bump, leading the competitive pitch.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on gains and wide-network. Bonus-pool conversations, equity true-ups, board invitations, alumni-network introductions.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return through own sign in moksha. Annual peak for confidential mandates, foreign work, retreats, white papers, off-balance-sheet structuring.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of emotional charge on persona. Body wants warmth; channel into a precision-led relational move.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on income and voice. Soft-spoken negotiations land; read the room before pricing.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on communication. Bold message, brave outreach. Ketu zone — calibrate warmth back in.' },
  { name: 'Moon Transits the 4th House', description: 'Emotional pull to the home-throne. Mother-channel calls, real-estate read-outs, family-business pulse-check. Cook a real meal.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on disciplined-creative engine. Mind feels poetic but structured; capture the draft.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict-management. Adversary may push; respond from documentation, not reaction.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnership. Read partner / principal-client temperature before meetings. Warm tone wins.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on transformation zone. Defer high-risk decisions two days. Old fears around chaos surface.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma, teaching, foreign work. The pilgrimage thought, the international intro draft.' },
  { name: 'Moon Transits the 10th House', description: 'Monthly career-pulse peak. Public reception warm; senior-network read-outs favor you.' },
  { name: 'Moon Transits the 11th House', description: 'Monthly own-sign peak (Moon territory). Reach out to alumni, community, peer-trust circle. Gains channel runs warm.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; foreign and behind-the-scenes pull. Best for retreat planning, confidential drafting.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury return through own + exalted lagna. Peak self-articulation window of the year. Refresh bio, founder-story, personal pitch deck. Most powerful Mercury transit for this chart.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Renegotiate salary, write family-finance plan, record the talk, pin the pricing.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s natural turf for short-burst communication. Peak for content production, sales sequences, sibling-channel deals.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-throne articulation. Real-estate paperwork, family-business memo, mother-channel correspondence.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative-discipline analysis. Long-form research drafts, curriculum design, doctoral chapter completion.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp adversary-management. Audit memos, litigation briefs, HR documentation — surgical-precision wins.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, JV memos, contract negotiations land cleanly.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-zone articulation. Restructuring memos, succession plans, insurance filings.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-articulation. Course outlines, lecture decks, certification applications, international-publication submissions.' },
  { name: 'Mercury Transits the 10th House', description: 'Mercury through 10L\'s domain — peak career-articulation window. Promotion memos, board decks, public lectures.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Alumni-newsletter writing, community-platform posts, board-advisory memos.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp confidential-mandate articulation. White papers, off-balance-sheet memos, retreat-strategy drafts.' },
  { name: 'Venus Transits the 1st House', description: 'Personal-magnetism window. Body, voice, taste, presence radiate. Signed contracts feel warm; client meetings convert.' },
  { name: 'Venus Transits the 2nd House', description: 'Venus through own income/voice zone. Family-finance windfall windows, vocal performance favored.' },
  { name: 'Venus Transits the 3rd House', description: 'Charm on communication. The warm message lands. Ketu zone — keep the ask sharp.' },
  { name: 'Venus Transits the 4th House', description: 'Venus through home-throne. Real-estate beauty decisions, mother-channel warmth, family-business soft-power.' },
  { name: 'Venus Transits the 5th House', description: 'Charm on creative-discipline. Structured craft picks up graceful surface — academic paper that reads beautifully.' },
  { name: 'Venus Transits the 6th House', description: 'Charm in conflict zone. Mediation, diplomatic resolution, gracefully-handled HR fight.' },
  { name: 'Venus Transits the 7th House', description: 'Venus return through own exalted 7th. Monthly peak partnership window. Sign the anchor deal, marry, lock principal client.' },
  { name: 'Venus Transits the 8th House', description: 'Charm in transformation zone. Severance / inheritance / restructuring negotiated warmly.' },
  { name: 'Venus Transits the 9th House', description: 'Charm on dharma engine. Foreign-stage talks land warmly, ethical-investment intros, teacher-mentor warmth.' },
  { name: 'Venus Transits the 10th House', description: 'Charm on career visibility. Board-level diplomacy, principal-craftsman warm public moments.' },
  { name: 'Venus Transits the 11th House', description: 'Charm in wide-network. Bonus-pool warm conversations, alumni intros, community-product affection.' },
  { name: 'Venus Transits the 12th House', description: 'Charm in moksha zone. Foreign-warmth, confidential-collaboration, retreat-relationships.' },
  { name: 'Mars Transits the 1st House', description: 'Surge of personal force on the precision-instrument body. Bold push window — but watch burnout. Temper with rest.' },
  { name: 'Mars Transits the 2nd House', description: 'Force on income and voice. Aggressive pricing, vocal demands. Avoid sharp tones in commerce.' },
  { name: 'Mars Transits the 3rd House', description: 'Force on communication. Bold campaigns, sales pushes. Ketu-zone — bluntness can land cold.' },
  { name: 'Mars Transits the 4th House', description: 'Force on home-throne. Property disputes, family friction. Keep the temperature low at home.' },
  { name: 'Mars Transits the 5th House', description: 'Force on creative-discipline. Push to ship the long-form; competitive contest. Saturn-territory keeps it disciplined.' },
  { name: 'Mars Transits the 6th House', description: 'Force on adversary-management. Best window for offensive action — lawsuit, audit, firing, regulatory filing.' },
  { name: 'Mars Transits the 7th House', description: 'Force on partnership. Sharp negotiations — but watch friction with spouse / principal client.' },
  { name: 'Mars Transits the 8th House', description: 'Mars through own territory — surgical-execution window. Crisis you walk into resolves under your hand.' },
  { name: 'Mars Transits the 9th House', description: 'Force on dharma. Aggressive teaching, doctrinal disputes, certification battles. Rahu zone activated.' },
  { name: 'Mars Transits the 10th House', description: 'Force on career visibility. Aggressive promotion pushes, competitive pitches, principal-track demands.' },
  { name: 'Mars Transits the 11th House', description: 'Force on wide-network. Aggressive bonus negotiations, board-position pushes. Watch group friction.' },
  { name: 'Mars Transits the 12th House', description: 'Force in moksha zone. Foreign-front sharp moves, confidential mandate sharpness. Protect the body.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual wisdom-on-self window. Body, personal brand, public-craftsman pick up dharma weight. Best year for personal-credential moves.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom on income, voice, family-finance. Year-block to expand voice-led income, refine family-finance ethics.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on communication. Year-block to publish the book, formalize the writing practice. Ketu-zone — keep doctrine grounded.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter return through own + Hamsa-Yoga territory. Year-block for property purchase, family-business inflection, mother-line teaching. Most important Jupiter transit of the chart.' },
  { name: 'Jupiter Transits the 5th House', description: 'Wisdom on creative-discipline. Year-block for doctoral defense, curriculum institutionalization, mentor-of-mentees roles.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom in conflict-zone. Year-block where adversaries weaken, debts repay, regulatory clarity arrives.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom on partnership. Year-block for marriage, JV consolidation, anchor-client dharma-alignment.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom in transformation zone. Year-block for inheritance, equity events, succession planning.' },
  { name: 'Jupiter Transits the 9th House', description: 'Wisdom in dharma-territory. Year-block for foreign-stage credentialing, teacher-track elevation.' },
  { name: 'Jupiter Transits the 10th House', description: 'Wisdom on career visibility. Year-block for principal-of-something appointment, formal lineage transfer.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom in wide-network gains zone. Year-block for cooperative-platform leadership, alumni-network institutionalization.' },
  { name: 'Jupiter Transits the 12th House', description: 'Wisdom in moksha zone. Year-block for retreat-residencies, foreign-research mandates, white papers.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn on the precision-instrument body. ~2.5-year discipline-on-self chapter. Slow strip-down of inflated self-image; lean re-emergence.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn on income / voice / family-finance. Lean years; long-term wealth foundations laid. Voice deepens.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn on communication. Rigorous editing of public message. Ketu-zone — productive loneliness.' },
  { name: 'Saturn Transits the 4th House', description: 'Saturn on home-throne. Heavy chapter for property, mother\'s health — but the *real* foundations of the home are built here.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn return through own 5H — the disciplined-creative chapter peak. Multi-decade moat laid here.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn on adversary/health/debt. Long grind chapter — but adversaries deplete themselves under your patience.' },
  { name: 'Saturn Transits the 7th House', description: 'Saturn on partnership. Marriage / anchor-client tested for structural soundness. Exalted Venus 7H softens.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn on transformation zone. Heavy-but-gold chapter for restructuring, succession, inheritance.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn on dharma. Long-arc chapter for credentialing, judicial proceedings, doctrinal restructure.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on career-visibility — the structural-status chapter. ~2.5 years of slow, irreversible promotion to principal-track.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn on wide-network gains. Structural rebuild of alumni / community / board-advisory channels.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn on moksha-zone. Heavy chapter for foreign work, confidential mandates, retreat-residency.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu on persona. ~18-month chapter of unconventional self-presentation. Risk: identity-overreach. Reward: breakthrough visibility.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu on income/voice/family-finance. Speculative income windows, foreign-currency exposure, unconventional vocal-led ventures.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on communication. Foreign / disruptive content channels, viral writing, unconventional sibling-network deals.' },
  { name: 'Rahu Transits the 4th House', description: 'Rahu on home-throne. Foreign-property windows, unconventional family-business pivots.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu on creative-discipline. Speculative-creative windows, foreign-curriculum ventures, viral-research opportunities.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu on adversary-zone. Unconventional enemies, foreign litigation. Strong Rahu in 6 typically defeats adversaries.' },
  { name: 'Rahu Transits the 7th House', description: 'Rahu on partnership. Foreign-spouse / foreign-anchor-client window. Exalted Venus 7H absorbs Rahu well.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on transformation. Speculative-equity events, unconventional inheritance, foreign restructuring.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu return through 9H. ~18-month foreign-dharma chapter — unconventional teacher, foreign credentialing.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu on career-visibility. Sudden public-craftsman elevation through disruptive channels.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu on wide-network. Foreign-friend windfalls, viral community moves, unconventional board appointments.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu on moksha-zone. Foreign-retreat residencies, confidential disruptive mandates.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu on persona. Detachment from public visibility; identity-stripping chapter. Useful for sabbatical thinking.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu on income/voice. Detachment from family-money attachment; voice quieter.' },
  { name: 'Ketu Transits the 3rd House', description: 'Ketu return through own territory. Detachment from communication noise; sibling-channel disengagement.' },
  { name: 'Ketu Transits the 4th House', description: 'Ketu on home-throne. Detachment from family-business / mother-line attachment. Defer big purchases.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu on creative-discipline. Detachment from validation-seeking creative work. Pure-form output emerges.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu on adversary-zone. Detachment from old grievances; enemies you thought mattered evaporate.' },
  { name: 'Ketu Transits the 7th House', description: 'Ketu on partnership. Detachment from anchor-client / spouse warmth; defer big partnership signing.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu on transformation zone. Detachment from crisis-thrill; the inheritance arrives muted.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on dharma. Detachment from doctrinal certainty; old teacher-track may stop fitting.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu on career-visibility. Detachment from status-attachment; promotion arrives strangely unsatisfying.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu on wide-network gains. Detachment from group-validation; some friends drift.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu on moksha-zone. Detachment-on-detachment — deep retreat months.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar light on persona. Body warms; public visibility tightens. Take the founder photo, the principal-craftsman framing.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Solar approach to lagna. Polish the public framing.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Today the spotlight peaks. Make the founder declaration.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Light fades. Consolidate visibility gains.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar light on career-MC. Public-status visibility window.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Solar approach to MC. Prep the senior-track move.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Today public-status spotlight peaks. Pitch the principal role.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Light fades from MC. Lock the recognition.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Take the relationship-driven meeting.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep softer outreach.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Today persona runs warm. Send the warm pitch.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Warmth fades. Lock warm-channel relationships.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-status. Lead with relational warmth in senior meetings.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Approach. Warm up senior-track relationships.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Today public-status read runs warm.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Warmth fades. Lock warm-status relationships.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury on persona — articulation peak. Bio refresh, founder-story polish.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Approach. Draft the personal pitch deck.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Today precision-articulation peaks. Ship the founder-story.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mercury fades. Lock articulation polish.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on public-status — board decks, principal-craftsman submissions.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Approach. Draft the board deck.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Today senior-track articulation peaks. Submit the board deck.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Mercury fades from MC. Lock senior-track articulation.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Charm on persona. Body radiates; client meetings convert.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep warm-pitch sequence.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Today personal-charm peaks. Sign the warm contracts.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm fades. Lock warm-channel relationships.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Charm on public-status. Board-level diplomacy, principal-craftsman warmth.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Approach. Soften senior-track outreach.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Today senior-track charm peaks.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Charm fades from MC. Lock senior-track warmth.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Force on persona. Bold pushes favored — but watch burnout on precision-instrument body.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Approach. Gather force.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Today force on persona peaks. Make the bold demand. Body needs rest tonight.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Force fades. Lock bold-push gains.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Force on public-status. Aggressive promotion pushes, competitive senior-track demands.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Approach. Gather force for senior-track push.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Today public-status force peaks. Demand the title.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Force fades. Cool friction with current authority.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom on persona. Lineage-anchored personal-brand moves, dharma-aligned framing.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Approach. Polish dharma-aligned framing.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Today wisdom on persona peaks. Take the lineage photo.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Wisdom fades. Lock lineage-anchored gains.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Wisdom on public-status. Senior-track elevation through dharma-aligned channels.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Approach. Position senior move as dharma-aligned.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Today senior-track dharma-elevation peaks.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Wisdom fades from MC. Lock dharma-aligned status.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Discipline on persona. Strip-down of inflated self-image; lean re-emergence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Approach. Begin personal discipline cycle.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Today discipline-on-persona peaks. Make the lean, principled statement.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Discipline closing. Lock leaner framing.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Discipline on public-status. Slow, structural, irreversible promotion to senior track.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Approach. Begin structural senior positioning.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Today structural-status peak. Take the slow-but-permanent promotion.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Discipline closing. Structural senior track in place.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Rahu on persona. Unconventional / foreign / disruptive personal-brand moves. Risk: identity-overreach. Reward: breakthrough.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Approach. Unconventional persona-pivot gathering.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Today disruptive-persona peak. Make the unconventional move.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu fades. Decide which disruptive elements stay.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Rahu on public-status. Sudden, unconventional senior-track elevation.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Approach. Unconventional senior move gathering.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Today disruptive-status peak. Take the unconventional appointment.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu fades from MC. Lock disruptive gains.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Ketu on persona. Detachment from public visibility; sabbatical-thinking favored.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Approach. Pull toward solitude rising.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Today persona-detachment peaks. Best for solitary work.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Detachment fading. Re-emerge with what survived silence.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Ketu on public-status. Detachment from status-attachment.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Approach. Status-attachment unwinds.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Today status-detachment peaks. Recognition feels strangely empty — useful info.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Detachment fading. Next chapter starts on internal grounds.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural transformation in 5L+6L Saturn territory. Career-discipline architecture rebuilt from foundation.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Pressure builds on Saturn-territory. Document the structural architecture you want to preserve.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Today the generational rebuild peaks. Disciplined-creative framework re-cast at depth.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Pressure releases. New structural architecture in place.' },
  { name: 'Uranus conjunct Venus', description: 'Disruptive innovation on the partnership / income / dharma engine. Spouse, anchor-client, principal-teacher relationship undergoes sudden re-architecture.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruptive pressure builds on partnership.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Today the partnership rewiring peaks. Unconventional partner declaration lands.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption settling. New partnership architecture in place.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar return through 12th. Annual peak for confidential mandates, foreign work, retreats.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Solar return approaching. Prep year-block strategic drafts.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Solar return peak. Take new-year strategic drafts done alone.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Solar return closing. Shadow-lane strategy on record.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar light on wide-network gains. Bonus-pool conversations, alumni introductions warm up.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Approach. Network-spotlight gathering.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Today network-spotlight peaks. Take alumni call.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Spotlight fades. Lock network-recognition.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar light on yogakaraka. Annual peak for personal-craftsman visibility.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka spotlight gathering.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Today yogakaraka spotlight peaks. Make founder declaration.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Spotlight fades. Lock principal-craftsman appointment.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar light on partnership. Visibility through contracts; spouse / principal-client dynamics light up.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Approach. Partnership-spotlight gathering.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Today partnership-spotlight peaks. Sign anchor partnership.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Spotlight fades. Lock public partnership.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar light on surgical-transformation engine. Career decisions take surgical edge.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Approach. Transformation-spotlight gathering.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Today crisis-spotlight peaks. Lead the restructuring.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Spotlight fades. Lock transformation gains.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar light on home-throne / Hamsa. Real-estate decisions, family-business inflections.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne spotlight gathering.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-spotlight peaks. Make property purchase, family-business move.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Spotlight fades. Lock home-throne move.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar light on disciplined-creative engine. Best for launching long-form work.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Approach. Creative-discipline spotlight gathering.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H spotlight peaks. Ship long-form work.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Spotlight fades. Lock structured-creative output.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Solar light on foreign-dharma engine. International-stage talks, certifications.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma spotlight gathering.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H spotlight peaks. Take foreign-stage talk.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Spotlight fades. Lock foreign-dharma recognition.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Solar light on detached-communication engine. Brave solitary-research push gets quiet recognition.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research spotlight gathering.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H spotlight peaks. Publish solitary research.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Spotlight fades. Solitary-research output on record.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on moksha-solar engine. Inwardness, foreign-pull, confidential-relationship warmth.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane warmth gathering.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Today 12H emotional warmth peaks. Take the confidential warm-toned meeting.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Warmth fades. Shadow-lane bond consolidated.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon return — wide-network gains channel runs warm. Reach out to alumni, community.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Moon return approaching. Network-warmth rising.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Moon return peak. Take the warm alumni call.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Moon return closing. Warm network gains on record.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional charge on yogakaraka. Body wants warmth in principal-craftsman framing.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Approach. Personal-warmth rising.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Today personal-warmth peaks. Take the warm client meeting.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Warmth fades. Lock warm-channel relationships.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on partnership. Read partner / principal-client temperature.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Approach. Partnership-warmth rising.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Today partnership-warmth peaks. Take warm-toned anchor meeting.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Warmth fades. Lock warm-partner alliance.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on transformation zone. Defer high-risk decisions two days.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Approach. Crisis-emotion rising.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Today crisis-weight peaks. Defer signings.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Weight fades. Re-engage transformation work.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional charge on home-throne / Hamsa. Mother-channel warmth peaks.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Approach. Home-warmth rising.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Today home-warmth peaks. Cook the real meal.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Warmth fades. Home-bond consolidated.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional charge on disciplined-creative engine. Structured-creative work picks up emotional warmth.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Approach. Creative-warmth rising.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Today creative-warmth peaks. Add heart to rigorous output.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Warmth fades. Warm-rigorous work on record.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional charge on foreign-dharma engine. Pilgrimage thought, international-introduction draft.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma warmth rising.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H warmth peaks. Make foreign-teacher reach-out.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Warmth fades. Foreign-dharma bond on record.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Emotional charge on detached-communication engine. Solitary-research mood.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research warmth rising.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H warmth peaks. Write the brave message.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Warmth fades. Solitary-research warmth locked.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Articulation on moksha-solar engine. Confidential mandate documentation; white papers.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane writing picks up pace.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Today shadow-lane articulation peaks. Ship the white paper.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Articulation fades. Shadow-lane document locked.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Articulation on wide-network gains. Alumni newsletter, community-platform posts, board-advisory memos.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Approach. Network-articulation gathers.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Today network-articulation peaks. Send alumni newsletter.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Articulation fades. Network-message on record.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury return — most important communication aspect of the chart. Bio refresh, founder-story, principal-craftsman pitch.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Mercury return approaching. Prep personal-articulation refresh.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Mercury return peak. Ship the bio.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Mercury return closing. Yogakaraka articulation locked.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Articulation on partnership. Term sheets, JV memos, contract negotiations.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Approach. Partnership-articulation gathers.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Today partnership-articulation peaks. Ship the term sheet.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Articulation fades. Partnership documents on record.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Articulation on transformation. Restructuring memos, succession plans, insurance filings.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Approach. Transformation-articulation gathers.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Today crisis-articulation peaks. Ship the restructuring memo.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Articulation fades. Transformation document locked.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Articulation on home-throne / Hamsa. Real-estate paperwork, family-business memo.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne articulation gathers.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-articulation peaks. Ship the real-estate doc.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Articulation fades. Home-throne document on record.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Articulation on disciplined-creative engine. Long-form drafts, curriculum design, doctoral chapter completion.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-creative articulation gathers.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H articulation peaks. Ship doctoral chapter.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Articulation fades. Disciplined-creative document locked.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Articulation on foreign-dharma engine. Foreign-publication submissions, certification applications.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma articulation gathers.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H articulation peaks. Submit foreign-publication piece.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Articulation fades. Foreign-dharma submission on record.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Articulation on detached-communication engine. Solitary research writing, deep-research notes.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research writing gathers.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H articulation peaks. Ship the lineage-research piece.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Articulation fades. Solitary-research piece stands.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Charm on moksha-solar engine. Foreign-warmth, confidential-collaboration, retreat-relationships.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane warmth gathering.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Today Venus-on-12H-Sun peaks. Take warm confidential meeting.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Charm fades. Shadow-lane warmth locked.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Charm on wide-network gains. Bonus-pool warm conversations, alumni warm intros.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Approach. Network-charm gathering.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Today Venus-on-network peaks. Take warm board call.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Charm fades. Lock warm-network bonds.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Charm on yogakaraka. Personal-craftsman framing radiates.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka-charm gathering.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Today Venus-on-yogakaraka peaks. Sign warm contracts.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Charm fades. Lock warm-channel relationships.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus return — partnership engine peaks. Sign anchor deal, marry, lock principal client.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Venus return approaching. Prep partnership move.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Venus return peak. Lock structural partnership.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Venus return closing. Partnership on record.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Charm on surgical-transformation engine. Severance / inheritance / restructuring negotiated warmly.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Approach. Transformation-warmth gathering.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Today Venus-on-Mars-8H peaks. Negotiate the inheritance with grace.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Charm fades. Warm transformation on record.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Charm on home-throne / Hamsa. Real-estate beauty decisions, mother-channel warmth.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne charm gathering.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-charm peaks. Take warm property meeting.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Charm fades. Lock warm home-throne move.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Charm on disciplined-creative engine. Structured craft picks up graceful surface.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Approach. Creative-charm gathering.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Today Venus-on-Saturn-5H peaks. Rigorous-creative work picks up grace.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Charm fades. Graceful-rigorous output on record.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Charm on foreign-dharma engine. Foreign-stage talks land warmly.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma charm gathering.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Today Venus-on-Rahu-9H peaks. Take warm foreign-stage talk.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Charm fades. Warm foreign-dharma bond on record.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Charm on detached-communication engine. Warm message that does not need a reply.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research warmth gathering.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Today Venus-on-Ketu-3H peaks. Send warm note that does not need a reply.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Charm fades. Gentle-research bond on record.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Force on moksha-solar engine. Confidential / foreign mandates sharpen.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane work gathers force.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Today force-on-12H-Sun peaks. Push the confidential mandate.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Force fades. Shadow-lane gains lock in.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Force on wide-network gains. Aggressive bonus moves, board-position pushes. Watch group-friction.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Approach. Network-push gathers.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Today force-on-network peaks. Demand the bonus.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Force fades. Network gains locked.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Force on yogakaraka. Aggressive personal-craftsman moves — bold founder push.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Approach. Principal-craftsman gathers force.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Today force-on-yogakaraka peaks. Make bold founder demand.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Force fades. Lock pitch gains; rest.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Force on partnership. Sharp negotiations — but cool the temperature before signing.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Approach. Partnership friction gathers.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Today partnership-force peaks. Demand JV terms; cool relational temperature.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Force fades. Partnership consolidates.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars return — surgical-execution peak. Crisis you walk into resolves under your hand.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Mars return approaching. Transformation push gathers.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Mars return peak. Walk into the burning room; stabilize the system.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Mars return closing. Crisis-resolution on record.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Force on home-throne / Hamsa. Aggressive property push, family-business confrontation. Keep home temperature low.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne friction gathers.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Today force-on-Jupiter-4H peaks. Property / family negotiation reaches its sharp point.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Force fades. Home-throne consolidates.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Force on disciplined-creative engine. Push to ship long-form work; competitive contest.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Approach. Creative-discipline push gathers.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Today force-on-Saturn-5H peaks. Ship long-form work.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Force fades. Disciplined-creative gains lock in.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Force on foreign-dharma engine. Aggressive doctrinal disputes, foreign-stage assertions.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Approach. Dharma-fight gathers.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Today force-on-Rahu-9H peaks. Take doctrinal stand on foreign stage.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Force fades. Foreign-dharma stand on record.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Force on detached-communication engine. Sharp solitary writing; fierce research.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Approach. Fierce-solitary push gathers.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Today force-on-Ketu-3H peaks. Ship the fierce research.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Force fades. Solitary-research push consolidated.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom touches the moksha-solar engine. Confidential mandates take dharma-weight.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane work gathering dharma weight.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Today wisdom on 12th-Sun peaks. Lock the confidential / foreign mandate.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Wisdom fades. Document the dharma-weight gained.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on wide-network gains. Alumni-network institutionalization, ethical bonus structures.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Approach. Network-gains picks up dharma framing.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Today wisdom-on-network peaks. Anchor wide-network in ethical structure.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Wisdom fades. Lock dharma-aligned network architecture.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom touches the central yogakaraka engine. Personal-craftsman framing picks up doctrinal weight.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Approach. Principal-craftsman framing gathers lineage authority.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Today wisdom-on-yogakaraka peaks. Take principal-of-craft mantle.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Wisdom fades. Lineage-anchored role locked.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on exalted partnership / dharma / wealth engine. Marriage with dharma-alignment, JV with ethical framing.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Approach. Partnership picks up dharma weight.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Today wisdom-on-Venus-7H peaks. Lock dharma-aligned partnership.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Wisdom fades. Principled partnership consolidated.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on surgical-transformation engine. Inheritance, restructuring take dharma-weight.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Approach. Transformation gathers dharma framing.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Today wisdom-on-Mars-8H peaks. Lock dharma-aligned restructuring.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Wisdom fades. Principled crisis-resolution on record.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter return — most important transit-aspect of the chart. Hamsa-Yoga territory amplified. Year-block for property purchase, family-business inflection.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Jupiter return approaching. Prep the home-throne move.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Jupiter return peak. Make the property purchase, family-business move.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Jupiter return closing. Home-throne lineage move consolidated.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on disciplined-creative engine. Doctoral framework receives lineage-authority.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-creative work picks up lineage weight.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Today wisdom-on-Saturn-5H peaks. Lock institutional curriculum.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Wisdom fades. Disciplined-creative architecture institutionalized.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Wisdom on foreign-dharma engine. Unconventional teacher-track gains lineage authority.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma move gathers framing.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Today wisdom-on-Rahu-9H peaks. Take unconventional teacher-track move.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Wisdom fades. Foreign-dharma path on record.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on detached-communication engine. Solitary research, doctrinal writing without audience-pressure.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research framing gathers.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Today wisdom-on-Ketu-3H peaks. Publish lineage-rooted research.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Wisdom fades. Solitary-research output locked.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Discipline on moksha-solar engine. Long-arc confidential / foreign mandate.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane discipline cycle beginning.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Today Saturn-on-12H-Sun peaks. Lock long-arc confidential mandate.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Discipline phase closing. Shadow-lane structure in place.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Discipline on wide-network gains. Structural rebuild of channels.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Approach. Network-discipline cycle beginning.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Today Saturn-on-network peaks. Some friends fall away; deep ones lock in for life.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Discipline phase closing. Pruned network is structural.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Discipline on yogakaraka. Slow personal-craftsman re-architecture. Body weight, posture tighten.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka discipline cycle beginning.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Today Saturn-on-yogakaraka peaks. Make lean, principled statement.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Discipline phase closing. Leaner principal-craftsman in place.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Discipline on partnership. Marriage / anchor-client tested for structural soundness.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Approach. Partnership-discipline cycle beginning.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Today Saturn-on-Venus-7H peaks. Structural partnership decision lands.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Discipline phase closing. Sound partnership on record.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Discipline on surgical-transformation engine. Heavy-but-gold restructuring.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Approach. Transformation-discipline cycle beginning.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Today Saturn-on-Mars-8H peaks. Lock long-arc restructuring.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Discipline phase closing. Structural transformation in place.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Discipline on home-throne / Hamsa. Heavy chapter for property, mother\'s health.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne discipline cycle beginning.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Today Saturn-on-Jupiter-4H peaks. Structural home / family decision lands.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Discipline phase closing. Home-throne foundation structural.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn return — disciplined-creative chapter peak. Multi-decade moat laid here.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn return approaching. Disciplined-creative chapter gathering.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Saturn return peak. Lock institutional curriculum.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn return closing. Multi-decade creative moat in place.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Discipline on foreign-dharma engine. Slow foreign credentialing.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma discipline cycle beginning.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Today Saturn-on-Rahu-9H peaks. Lock foreign credential.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Discipline phase closing. Foreign-dharma structure in place.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Discipline on detached-communication engine. Long-form solitary research.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research discipline cycle beginning.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Today Saturn-on-Ketu-3H peaks. Lock long-form project.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Discipline phase closing. Lineage-research output on record.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Disruption on moksha-solar engine. Sudden foreign / confidential mandate; speculative shadow-lane work.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Approach. Disruptive shadow-lane move gathering.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Today Rahu-on-12H-Sun peaks. Take unconventional foreign mandate.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Disruption fading. Lock or release move.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Disruption on wide-network gains. Foreign-friend windfalls, viral-community moves.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Approach. Network-disruption gathering.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Today Rahu-on-network peaks. Ride viral wave.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Disruption fading. Decide which gains stay.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Disruption on yogakaraka. Unconventional / foreign personal-brand pivot.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Approach. Disruptive principal-craftsman move gathering.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Today Rahu-on-yogakaraka peaks. Make unconventional public-brand move.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Disruption fading. Lock breakthrough; drop overreach.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Disruption on partnership. Foreign-spouse / foreign-anchor-client window.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Approach. Disruptive partnership move gathering.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Today Rahu-on-Venus-7H peaks. Unconventional partner declaration lands.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Disruption fading. Unusual partnership consolidated.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Disruption on surgical-transformation engine. Speculative-equity events, unconventional inheritance.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Approach. Disruptive transformation gathering.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Today Rahu-on-Mars-8H peaks. Walk into high-velocity transformation; harness, do not chase.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Disruption fading. Transformation gains documented.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Disruption on home-throne / Hamsa. Foreign-property windows, unconventional family-business pivots.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne disruption gathering.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Today Rahu-on-Jupiter-4H peaks. Take foreign-property move.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Disruption fading. Unconventional move consolidated.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Disruption on disciplined-creative engine. Speculative-creative windows, foreign-curriculum ventures.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Approach. Creative-disruption gathering.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Today Rahu-on-Saturn-5H peaks. Take speculative venture; ground in discipline.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Disruption fading. Unconventional-creative output on record.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Rahu return — foreign-dharma engine peaks. Unconventional teacher, foreign credentialing, disruptive doctrine.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return approaching. Foreign-dharma chapter gathering.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Rahu return peak. Make foreign-teacher / unconventional-doctrine move.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return closing. Unconventional dharma path consolidated.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Nodal-axis activation on communication. Foreign / disruptive content channels.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Approach. Nodal-axis communication disruption gathering.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Today nodal-axis peak. Viral / foreign content move lands.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal pressure fading. Unconventional content gains documented.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on moksha-solar engine. Pure shadow-lane work, ego-free retreat mandates.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Approach. 12H solar light dims.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Today detachment-on-12H-Sun peaks. Best for monastery-as-client work.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Detachment fading. Shadow-lane work consolidates.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on wide-network gains. Some friends drift; alumni channel quiets. Prune the network.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Approach. Group-warmth fades.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Today network-detachment peaks. Trust the silence.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Detachment fading. Pruned network reveals real members.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on yogakaraka. Identity-stripping window — principal-craftsman essence remains; ego-frame thins.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Approach. Public-craftsman ego-frame loosens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Today yogakaraka-detachment peaks. Best for solitary craft.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Detachment fading. Leaner principal-craftsman re-emerges.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on partnership. Defer big partnership signing.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Approach. Partnership warmth dims.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Today partnership-detachment peaks. Defer signings.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Detachment fading. Partnership warmth returns.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on surgical-crisis engine. The inheritance / equity event arrives muted. Document.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Approach. Crisis-thrill loosens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Today crisis-detachment peaks. Transformation passes through quietly.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Detachment fading. Quiet transformation on record.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on home-throne / Hamsa engine. Family-business attachment loosens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne attachment loosens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-detachment peaks. Family-business decisions feel oddly indifferent.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Detachment fading. Home-throne re-engages quieter.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on disciplined-creative engine. Validation-seeking impulse fades; pure-form output emerges.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Approach. Validation-attachment loosens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Today creative-detachment peaks. Make the work nobody is asking for.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Detachment fading. Pure-form output stands alone.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Detachment on foreign-dharma engine. Doctrinal certainty loosens.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Approach. Doctrinal certainty wobbles.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Today doctrine-detachment peaks. Sabbatical from teacher-track ambition.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Detachment fading. Teacher-track returns on different terms.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Ketu return — communication-detachment peak. Sibling-channel goes quiet; marketing impulse fades.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Approach. Communication-attachment loosens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Ketu return peak. Drop the marketing.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu return closing. Re-engage on lighter terms.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
