// db/seed_relationship_aries.js
//
// Per-ascendant fill-in seed for the **relationship** category, scoped to a
// representative Aries ascendant native with:
//   Ascendant: Aries
//   Natal placements (sidereal Lahiri):
//     Sun=5th (Leo, own)  Moon=4th (Cancer, own)  Mercury=6th (Virgo, own+exalted)
//     Venus=12th (Pisces, exalted)  Mars=1st (Aries, own — Ruchaka Yoga)
//     Jupiter=9th (Sagittarius, own)  Saturn=10th (Capricorn, own — Sasa Yoga)
//     Rahu=5th (Leo, conjunct Sun)  Ketu=11th (Aquarius)
//
// All 530 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose relationship-specific interpretations, then run:
//
//   node db/seed_relationship_aries.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./relationship');

const ASCENDANT = 'Aries';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mars ruler of the 1st House in the 1st House', description: 'You walk into rooms as your own person. In love, that is both the gift and the friction: partners are drawn to the unmistakable self-direction, and then sometimes wear out under it. You need a counterpart who can hold their own ground without flinching, who does not require constant softening. Relationships fail when you try to shrink the warrior; they thrive when you channel that fire into protection rather than dominance.' },
  { name: 'Venus ruler of the 2nd House in the 12th House', description: 'Speech of love runs through quiet, devotional, foreign, or hidden channels. You don\'t flirt loudly; you express affection through service, retreat-time, written letters, distance-bridging gestures. The voice that says "I love you" prefers the bedroom to the dinner table. Long-distance phases work for you. The shadow: words of affection slip through your fingers if not pinned to a deliberate ritual — write, send, repeat.' },
  { name: 'Mercury ruler of the 3rd House in the 6th House', description: 'Communication with siblings, peers, and close friends is sharp, useful, and sometimes too clinical. You write what you cannot say; you fix what you cannot accept. With siblings you tend to be the troubleshooter. With friends, you become the one they call when there is a real problem — but make space for play too, or the bonds become purely transactional.' },
  { name: 'Moon ruler of the 4th House in the 4th House', description: 'Home is your emotional center of gravity. Mother is a quiet anchor across decades. The dwelling itself — the kitchen, the windows, the wall colors — feeds your nervous system more than it should, and starves it when neglected. Relationships compound when your home is in order. A home that nourishes you is the prerequisite, not the reward, of romantic stability.' },
  { name: 'Sun ruler of the 5th House in the 5th House', description: 'Romance runs warm, theatrical, generous, and pulled toward visibility. You like to be seen with the person you love; you choose partners who can hold the spotlight beside you. Children, mentees, and creative work are emotional anchors. The shadow: ego-pull toward partners who shine publicly more than they show up privately — verify the warmth backstage matches the warmth on stage.' },
  { name: 'Mercury ruler of the 6th House in the 6th House', description: 'In intimate-circle conflicts you are sharp, precise, and a touch clinical. You diagnose; you adjudicate; you draft the resolution. That serves you in workplace and family-system disputes — but in romance, the same precision can wound. Soften by 20% before delivering the truth. Love is not a service-ticket queue.' },
  { name: 'Venus ruler of the 7th House in the 12th House', description: 'Marriage and primary partnership lean foreign, devotional, hidden, or service-oriented. The spouse may come from abroad, from a hospitality or healing background, or arrive after a retreat. The partnership matures behind closed doors; private rituals carry it. Public-facing display of the relationship feels false. The shadow: the partner drifts inward or geographically distant when the relationship is forced into public visibility prematurely.' },
  { name: 'Mars ruler of the 8th House in the 1st House', description: 'Intensity and transformation live in your body. Sexuality is direct, vital, sometimes overwhelming for softer partners. You bring the same Mars-energy to intimacy as to work — and partners either match it or step back. The shadow: sudden eruptions over old wounds. Cultivate a regular release valve (intense exercise, ritual, deep talk) so the 8H Mars does not catch the relationship sideways.' },
  { name: 'Jupiter ruler of the 9th House in the 9th House', description: 'Romance is filtered through values, ethics, philosophy, and shared worldview. You commit to people whose principles you respect — and lose interest fast in those whose ethics blur. Foreign partners, teacher-student dynamics, age-gap relationships, and pilgrimage-style courtships all find their natural shape here. The shadow: principled rigidity that turns love into a doctrinal exam.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Public-facing relationships (career partners, public couples-image) carry heavy structural weight. The world reads you and your partner as a unit; reputation is shared. Long, slow, irreversible commitments are your nature — fast romances rarely survive. The shadow: marrying the role rather than the person; verify the relationship works at home, not just on the resume.' },
  { name: 'Saturn ruler of the 11th House in the 10th House', description: 'Friend networks compound through career and seniority more than through casual leisure. Your closest long-term friends tend to be older, more established, or formal. Romantic introductions arrive through professional rather than recreational channels. The shadow: the network you keep also gates who you can love — make space for friends outside the work circle.' },
  { name: 'Jupiter ruler of the 12th House in the 9th House', description: 'Bedroom-pleasures and hidden romance carry a devotional, philosophical undertone. You are drawn to retreats, meditation, foreign trips, and pilgrimages where intimacy and spiritual growth fuse. Some of your deepest love memories will live in places no one else knows about. The shadow: confusing devotional partnership with rescue-fantasy — keep clarity between sacred and saving.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (6)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 5th (Dispositor)', description: 'When this engine fires, romance announces itself loudly. New crushes, public couplings, theatrical declarations, children-related news, mentee-protégé dynamics. Verify that the Rahu-amplified shine of a new partner is anchored to actual character before publicly committing.' },
  { name: 'Moon in 4th (Dispositor)', description: 'When this engine fires, the home is the stage. Family approval matters; the kitchen-table version of your relationship is the truest one. Mother often weighs in with unsolicited but valuable instinct. Avoid pulling partners away from your home-base — they are meant to integrate, not replace.' },
  { name: 'Mercury in 6th (Dispositor)', description: 'When this engine fires, expect surgical clarity in family-system or peer-circle disputes. Old conflicts close; debts owed within the relationship rebalance; the difficult sibling-conversation finally happens. The shadow: deploying the same precision in romance and wounding the partner.' },
  { name: 'Jupiter in 9th (Dispositor)', description: 'When this engine fires, principled love and foreign-fortune bonds light up. Marriage proposals from abroad, ceremonial commitments, teacher-student bonds, ethics-driven courtships. Major life-decisions made together feel blessed when this dispositor activates.' },
  { name: 'Mars in 1st (Dispositor)', description: 'When this engine fires, you assert yourself in romance — sometimes too directly. Bold confessions, decisive moves, founder-style commitment-asks. Verify the intensity is what the partner can hold, not what you need to discharge.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, the long-arc commitment crystallizes. Marriage, formal cohabitation, joint long-term financial moves, legal partnership steps. The slow promise becomes the structural fact.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual visibility window for the persona. In love, your warmth is more openly extended; partners receive you without you having to over-explain. Best four-week stretch for a public relationship-step (announcement, photo, family introduction).' },
  { name: 'Sun Transits the 2nd House', description: 'Conversations about money, voice, and family-finance light up the partnership. The bills, the joint account, the family-money question — all surface for open discussion.' },
  { name: 'Sun Transits the 3rd House', description: 'Sibling and peer-circle dynamics light up. Best for the difficult brother/sister conversation, the peer-friendship reset, the courageous text you have been deferring.' },
  { name: 'Sun Transits the 4th House', description: 'Home-base spotlight. Mother-related developments; family approval; the dwelling itself becomes the conversation. Real-estate-and-relationship decisions intertwine.' },
  { name: 'Sun Transits the 5th House', description: 'Annual peak romance-visibility window. Best for the bold declaration, the public outing, the proposal, the announcement of pregnancy or new mentee. Verify spectacle is anchored in substance.' },
  { name: 'Sun Transits the 6th House', description: 'Workplace and service-context relationship dynamics surface. The work-spouse situation, the colleague-flirt, the work-friend conflict — all find clarity. Health-of-the-relationship audits favored.' },
  { name: 'Sun Transits the 7th House', description: 'Annual peak partnership-visibility window. Marriage, contracts, public-facing alliance moves. Watch ego friction with the spouse — the same light that illuminates also exposes.' },
  { name: 'Sun Transits the 8th House', description: 'Visibility on shared resources, sexuality, in-laws, and transformations. Inheritance, joint-taxation, deep intimacy conversations. Keep the surface respect intact while the deep work happens.' },
  { name: 'Sun Transits the 9th House', description: 'Visibility on values, ethics, foreign relationships. Best window for a wedding ceremony, a vow renewal, an ethics-driven commitment, a foreign-relationship clarification.' },
  { name: 'Sun Transits the 10th House', description: 'Visibility on the public face of the relationship. The world sees you as a unit; reputation moves accordingly. Best for the public announcement, the joint career-step, the formal status update.' },
  { name: 'Sun Transits the 11th House', description: 'Visibility on shared friendships, networks, gains. The friend-circle as a couple; the joint birthday; the network introductions. Watch for muted emotion despite social warmth.' },
  { name: 'Sun Transits the 12th House', description: 'Visibility dims; intimacy deepens behind closed doors. Best for retreats, foreign trips together, devotional joint practice, private rituals.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional charge on persona. Affection runs warmer; reach out to the partner with extra warmth. Watch impulsive declarations.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotion around money, voice, family-finance. Speak about resources when warm; defer when overcooked.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge with siblings and close peers. Send the warm message; make the gentle call.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly emotional-home peak. The kitchen-table conversation lands; mother-call favored; partner appreciates being invited into your inner sanctum.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on romance, children, creative play. Date nights, mentee-time, playful courtship. Watch the ambition undertow that can confuse passion with possession.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional intelligence in service-and-conflict zone. Soften any peer-circle correction; offer empathy in workplace-relationship dynamics.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on the partner. Read their mood before pushing terms; warm tone wins over sharp clarity today.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on intimacy, sexuality, shared resources. Sensitive 48-hour window; defer money-arguments two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward shared values, ethics, foreign-friend-of-relationship. Big-vision conversations about meaning.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on public-facing relationship reputation. The room reads you and the partner; couples-photo lands well.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth toward shared network with detachment undertone. Reach out to mutual friends, but expect cool reception emotionally.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional charge on private intimacy, retreat, foreign-friend, devotion. Sleep more together; private warmth compounds.' },
  { name: 'Mercury Transits the 1st House', description: 'Bold communication of self in love. Confess, declare, send the personal-narrative letter. Watch overly aggressive phrasing.' },
  { name: 'Mercury Transits the 2nd House', description: 'Patient communication around money, voice, family-finance with the partner. Excellent for joint-budget paperwork.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak peer/sibling communication window. Send the long-deferred message; revive the cooled friendship.' },
  { name: 'Mercury Transits the 4th House', description: 'Emotionally tuned home/family writing. Mother-letters, family-business communications, lease-with-partner paperwork.' },
  { name: 'Mercury Transits the 5th House', description: 'Bold romance-communication. Love letters, dating-app outreach, mentee-coaching, children-related correspondence. Verify the volume is calibrated.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp peer-and-workplace relationship communication. Settle the work-friend conflict; deliver the precise but warm correction.' },
  { name: 'Mercury Transits the 7th House', description: 'Diplomatic, balanced negotiation with the partner. Excellent for marriage paperwork, prenups, joint-resource documents.' },
  { name: 'Mercury Transits the 8th House', description: 'Investigative communication around sexuality, in-laws, shared resources. Tax docs, inheritance conversations, deep talks.' },
  { name: 'Mercury Transits the 9th House', description: 'Visionary writing about values, philosophy, foreign-friend correspondence. Wedding-vow drafts; ethics conversations.' },
  { name: 'Mercury Transits the 10th House', description: 'Disciplined, structural communication about the public face of the relationship. Joint announcements, status updates.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp-but-detached communication with shared network. Group-text leadership, friend-circle logistics.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential and devotional communication. Private letters, foreign-friend correspondence, intimate written rituals.' },
  { name: 'Venus Transits the 1st House', description: 'Personal warmth and charm peak. Flirtation lands; first impressions go well; the mirror feels kind. Excellent for date-nights you initiate.' },
  { name: 'Venus Transits the 2nd House', description: 'Soft window for joint-money, shared-voice, family-finance with the partner. Indulgence in food and beauty together.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful peer and sibling warmth. Reconnect with the cooled friend; reach the difficult sibling.' },
  { name: 'Venus Transits the 4th House', description: 'Beautiful home/mother/family-with-partner window. Sign the lease together, beautify the home, host the family.' },
  { name: 'Venus Transits the 5th House', description: 'Peak romance-aesthetic visibility. Date-nights, creative play with the partner, mentee/protégé warmth. Indulgent.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic warmth in workplace and peer-circle relationships. The difficult colleague becomes a receptive ally.' },
  { name: 'Venus Transits the 7th House', description: 'Annual peak partnership-warmth window. Sign the marriage paperwork, formalize the long-standing love, propose.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic intimacy. Inheritance, shared-resources, sexuality conversations soften. Excellent for fair-share negotiations.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful values, ethics, foreign-relationship window. Travel together, attend ceremonies, deepen ethics-conversation.' },
  { name: 'Venus Transits the 10th House', description: 'Softens the public face. Joint photos, couples-branding, public couple-events all favored.' },
  { name: 'Venus Transits the 11th House', description: 'Graceful but cool friend-network warmth. Group dinners, mutual-friend gatherings — pleasant but emotionally muted.' },
  { name: 'Venus Transits the 12th House', description: 'Annual peak window for private intimacy, foreign love, devotional partnership. Retreats together; bedroom-pleasure deepens.' },
  { name: 'Mars Transits the 1st House', description: 'High self-assertion in love. Bold confessions, founder-style commitment-asks. Watch domineering tone.' },
  { name: 'Mars Transits the 2nd House', description: 'Heat around joint money, voice, family-finance. Avoid joint-budget arguments today; defer if possible.' },
  { name: 'Mars Transits the 3rd House', description: 'Fierce peer/sibling energy. Bold messages, sibling confrontations, peer-circle decisive moves.' },
  { name: 'Mars Transits the 4th House', description: 'Heat in home/family. Decisive real-estate-with-partner action; watch family arguments.' },
  { name: 'Mars Transits the 5th House', description: 'Hot romance-and-creativity drive. Passionate phase; speculation in love possible; verify integrity before pursuing.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable conflict-resolution heat. Win the workplace dispute; settle the peer-debt fight.' },
  { name: 'Mars Transits the 7th House', description: 'Friction in primary partnership. Hard to negotiate cleanly; defer the contract-style relationship conversation a week.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical action on intimacy, in-laws, shared resources. Restructurings of shared finances; sexuality-conversation peaks.' },
  { name: 'Mars Transits the 9th House', description: 'Bold values-and-ethics action. Wedding-planning push, foreign-relationship decisive move, vow-renewal.' },
  { name: 'Mars Transits the 10th House', description: 'Strong public-face-of-relationship action window. Joint career step, public couple-move.' },
  { name: 'Mars Transits the 11th House', description: 'Assertive friend-network push with detachment. Group-decisions, mutual-friend conflicts decisively addressed.' },
  { name: 'Mars Transits the 12th House', description: 'Heated private/foreign/intimate zone. Bedroom-intensity peaks; back-channel power-plays. Sleep loss possible.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual self-expansion in love. Take the larger role in the partnership; declare the bigger commitment.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom-blessing on joint money, voice, family-finance. Long-term resource decisions blessed.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on peers, siblings, short-effort. Major peer-friend deepenings; sibling reconciliation; new closeness.' },
  { name: 'Jupiter Transits the 4th House', description: 'Peak home/family/real-estate-with-partner expansion year. Buy the home, deepen with mother, marry into family.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major romance-or-children-or-creativity year. Marriage proposals, pregnancy news, mentee placements, creative joint-projects.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom into work-and-peer-circle relationships. Difficult colleagues become teachers; friend-debt resolves.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom into primary partnership. Marriage, anchor JV with spouse-as-partner, prestige-couples-event.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into intimacy, in-laws, shared resources. Inheritance favorably resolves; sexuality-and-shared-life deepen.' },
  { name: 'Jupiter Transits the 9th House', description: 'Among the most blessed partnership windows. Wedding ceremonies, ethics-driven joint commitments, foreign-relationship deepening.' },
  { name: 'Jupiter Transits the 10th House', description: 'Peak public-face-of-relationship year. Joint prestige; couples-brand expansion.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom on shared friendships. Mutual-friend network expands; joint social capital grows.' },
  { name: 'Jupiter Transits the 12th House', description: 'Peak private-intimacy and devotional-partnership year. Foreign joint sabbatical; spiritual practice together.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on persona within the relationship. Slow down; simplify; build for permanence not display.' },
  { name: 'Saturn Transits the 2nd House', description: 'Discipline on joint money, voice, family-finance. Slow but real wage-and-resource growth in the partnership.' },
  { name: 'Saturn Transits the 3rd House', description: 'Discipline on peers and siblings. Long-arc rebuilding of strained friendships; sibling-relations restructuring.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy home/family weight; mother-related responsibility intensifies; the dwelling carries structural change.' },
  { name: 'Saturn Transits the 5th House', description: 'Romance/children/creativity tested. Long-arc relationship maturation; mentee-relationships restructure; speculation-in-love disciplined.' },
  { name: 'Saturn Transits the 6th House', description: 'Favorable for service/conflict mastery. Work-and-peer relationships professionalize; long-debts within friendships resolve.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of marriage/primary partnership. Long-arc commitment matures; the spouse ages alongside you.' },
  { name: 'Saturn Transits the 8th House', description: 'Major intimacy/in-laws/shared-resource restructuring. Inheritance chapters open and close. Hold steady.' },
  { name: 'Saturn Transits the 9th House', description: 'Discipline on values, ethics, foreign-relationships. Slow visa or international-couples processes; ethics tested.' },
  { name: 'Saturn Transits the 10th House', description: 'The 2.5-year window that seeds the long-term public-couple structure. Marriage, formal cohabitation, legal commitment.' },
  { name: 'Saturn Transits the 11th House', description: 'Disciplined shared-network. Friend-circle consolidates; mutual-friends formalize role. The network purges what is no longer dharmic.' },
  { name: 'Saturn Transits the 12th House', description: 'Discipline on private intimacy, foreign love, devotional bond. Long-distance phases formalize; retreats turn structural.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive self-reinvention in love. New persona within the relationship; new ambition together. Verify each leap.' },
  { name: 'Rahu Transits the 2nd House', description: 'Obsessive ambition around joint money, voice, family-finance. Beware get-rich-quick schemes that pull the partnership.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive peer/sibling chapter. Sudden reconnections with old friends; unconventional peer-bonds.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home/mother/relocation-with-partner chapter. Foreign relocation pull strong. Verify before moving.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month peak romance-ambition. Sudden affairs, dramatic new courtship, mentee obsession. Verify integrity.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat a relationship-rival, settle a long peer-debt, transform workplace-relationship dynamics.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive primary-partnership chapter. Foreign partner pull; controversial marriage moves. Verify carefully.' },
  { name: 'Rahu Transits the 8th House', description: 'Obsessive intimacy/in-laws/shared-resources chapter. Sudden inheritance; deep-sex obsession; in-laws turbulence.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign-fortune obsession in love. International courtship, controversial guru-of-the-couple, ethics-questioning.' },
  { name: 'Rahu Transits the 10th House', description: 'Obsessive public-face-of-relationship push. Sudden public couple-moves, foreign couple-relocation. Vet legitimacy.' },
  { name: 'Rahu Transits the 11th House', description: 'Obsessive shared-friend-network chapter. Mutual-friend turbulence; new clique formation. Stay clean.' },
  { name: 'Rahu Transits the 12th House', description: 'Obsessive private/foreign/intimate chapter. Foreign affair-pull, hidden-bond obsession, retreat-driven romance.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping in love. The old persona inside the relationship feels empty. Sit; do not over-rebuild.' },
  { name: 'Ketu Transits the 2nd House', description: 'Detachment from joint money/voice/family-finance dynamics. The wealth-with-partner question feels meaningless temporarily.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from peers/siblings. Old friendships fade; sibling-bonds cool naturally.' },
  { name: 'Ketu Transits the 4th House', description: 'Home-and-mother detachment within the relationship. Sell-property impulses; mother\'s independence; leave-the-city signals.' },
  { name: 'Ketu Transits the 5th House', description: 'Romance/children/creativity eclipse. Old romance feels hollow; mentee-pull fades; speculation-in-love loses charge.' },
  { name: 'Ketu Transits the 6th House', description: 'Service detachment within the friend-circle. Old peer-conflicts dissolve without victory; debts forgiven.' },
  { name: 'Ketu Transits the 7th House', description: 'Primary-partnership detachment. Old marriage chapter feels finished; spouse needs space.' },
  { name: 'Ketu Transits the 8th House', description: 'Intimacy/in-laws/shared-resources acceleration of endings. Old chapters end abruptly.' },
  { name: 'Ketu Transits the 9th House', description: 'Values/ethics/foreign-relationship detachment. Old ethical bonds feel outdated; foreign-friend ties cool.' },
  { name: 'Ketu Transits the 10th House', description: 'Public-couple eclipse. Old couples-image dissolves; reputation feels weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month deep purification of friendships. Friends drift; mutual-friend network reorganizes.' },
  { name: 'Ketu Transits the 12th House', description: 'Private/foreign/devotional dissolution. Old hidden bonds close; pleasure-spending evaporates.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Visibility radiates through persona. The partner sees you clearly today; warm declarations land.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens. Polish how you show up to the partner.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the bold step; declare the love.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes. Lock in any declarations.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Public-face-of-relationship visibility window. Joint announcements, couples-photos, formal status moves.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Public-couple window opens. Plan the joint announcement.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak public-couple day. Make the formal announcement.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Public-couple window closes. Lock in any joint commitments.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional warmth radiates. Affection runs warmer; partner receives you generously.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotional-self window opens. Prepare to be felt.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak emotional-self day. Warm presentations of self land.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Emotional-self window closes. The wave passes fast.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-couple reputation. Warm couples-news possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Emotional public-couple window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak emotional public-couple day. Warm joint moments land publicly.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Emotional public-couple window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-communication in love. Personal declarations, narrative refresh.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Mind-on-self window opens. Refresh the personal-story.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak self-communication day. Send the bold personal letter.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mind-on-self window closes. Lock in personal commitments.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp public-couple communication. Joint announcements, formal status memos.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Public-couple-communication window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Send the public update.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Window closes. Convert into commitment.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Personal charm peaks. Flirtation lands; presence is magnetic.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Charm-self window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm day. Make the warm ask.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm-self window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens public-couple face. Joint photos, couples-branding favored.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-couple window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak aesthetic-couple day.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-couple window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Bold self-action in love. Founder-style commitment-asks.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak action-self day. Take the bold relationship-step.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold public-couple action. Joint career step, public commitment move.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Public-couple-action window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the joint career step.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Window closes. Lock in joint position.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Self-expansion in love. Take the larger role in the partnership.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Self-expansion window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak self-expansion day. Accept the bigger relationship-role.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Self-expansion window closes. Lock in.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Public-couple expansion. Joint prestige; couples-brand expansion.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Public-couple-expansion window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak day. Accept the joint prestige.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on persona within the relationship. Simplify.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Structural-self window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak structural-self day. Reckoning is acute.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Window closes. What survived is permanent.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Public-couple tested for staying power. Foundation-laying.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Public-couple-discipline window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day. The promise delayed; foundation laid.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion in love. New persona within the partnership.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Reinvention-self window begins.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Window closes. Decide which experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic public-couple expansion. Sudden unconventional couple-moves.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Public-couple-reinvention window begins.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping inside the relationship. The old persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Stripping window opens. The pull to step away rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit with the dissolution.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Window closes. Move forward leaner.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Public-couple eclipse. Couples-image stalls; recognition feels hollow.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Public-couple-eclipse window begins.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. The couples-image dissolves quietly. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting your long-arc commitment engine. Marriage, formal partnership, public-couple status under multi-year transformation pressure.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins on the long-arc commitment. Old partnership frameworks dismantle.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak transformation day. The old partnership-form breaks; a new one is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'The partnership-transformation chapter completes. You emerge with a rebuilt commitment.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the foreign and devotional love-channel. Unexpected foreign-friend turn; surprise back-channel romance; abrupt shifts in the private-intimacy circuit.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruption window opens. Expect surprise foreign offers; back-channel love shifts.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak surprise day. The foreign love-news arrives; the back-channel pivots.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption window closes. Integrate; release what didn\'t hold.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 5th house', description: 'Birthday-window ego activation in romance/creativity zone. Best for the bold declaration, the public outing, the proposal.' },
  { name: 'Sun aspect Sun in 5th house : Starts', description: 'Annual romance window opens.' },
  { name: 'Sun aspect Sun in 5th house : Exact', description: 'Peak day. Declare, propose, take the platform.' },
  { name: 'Sun aspect Sun in 5th house : Ends', description: 'Window closes. Lock in commitments.' },
  { name: 'Sun aspect Moon in 4th house', description: 'Visibility through home, mother, family-with-partner. Mother-channel relationship news.' },
  { name: 'Sun aspect Moon in 4th house : Starts', description: 'Home-visibility window opens.' },
  { name: 'Sun aspect Moon in 4th house : Exact', description: 'Peak home-anchored day. Sign the lease, host mother.' },
  { name: 'Sun aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mercury in 6th house', description: 'Solar fire on peer/sibling/workplace-relationship clarity. Conflicts resolve.' },
  { name: 'Sun aspect Mercury in 6th house : Starts', description: 'Window opens. Plan the precise resolution.' },
  { name: 'Sun aspect Mercury in 6th house : Exact', description: 'Peak day. The hard peer/sibling conversation closes.' },
  { name: 'Sun aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Venus in 12th house', description: 'Solar light on private-intimacy, foreign-love, devotional bond. Retreat-driven warmth.' },
  { name: 'Sun aspect Venus in 12th house : Starts', description: 'Foreign-intimacy window opens.' },
  { name: 'Sun aspect Venus in 12th house : Exact', description: 'Peak day. Take the foreign call; book the retreat together.' },
  { name: 'Sun aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mars in 1st house', description: 'Solar fire on warrior identity in love. Bold declarations; founder-style asks.' },
  { name: 'Sun aspect Mars in 1st house : Starts', description: 'Founder-fire window opens.' },
  { name: 'Sun aspect Mars in 1st house : Exact', description: 'Peak day. Take the bold relationship-step.' },
  { name: 'Sun aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Jupiter in 9th house', description: 'Solar light on values/ethics/foreign-friend. Wedding/ceremony favorability; ethics-driven commitment.' },
  { name: 'Sun aspect Jupiter in 9th house : Starts', description: 'Window opens. Plan ceremony or vow.' },
  { name: 'Sun aspect Jupiter in 9th house : Exact', description: 'Peak day. The vow lands.' },
  { name: 'Sun aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on public-face-of-relationship. Joint career-step or formal commitment.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak day. Take the joint formal step.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Rahu in 5th house', description: 'Ambition-amplified ego in romance. Watch fame-chasing in love.' },
  { name: 'Sun aspect Rahu in 5th house : Starts', description: 'Window opens. Beware spectacle in romance.' },
  { name: 'Sun aspect Rahu in 5th house : Exact', description: 'Peak day. The bold leap in love presents — verify integrity.' },
  { name: 'Sun aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Ketu in 11th house', description: 'Solar light on detached friend-network. Mutual-friend news lands; feel without grasping.' },
  { name: 'Sun aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Ketu in 11th house : Exact', description: 'Peak day. Recognition lands flat.' },
  { name: 'Sun aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Sun in 5th house', description: 'Emotional charge on romance/children/creativity. Warm date-nights, mentee-warmth, playful courtship.' },
  { name: 'Moon aspect Sun in 5th house : Starts', description: 'Window opens. Soften the romance-tone.' },
  { name: 'Moon aspect Sun in 5th house : Exact', description: 'Peak day. Make the heart-led romantic move.' },
  { name: 'Moon aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Moon in 4th house', description: 'Monthly emotional-home peak. Family-with-partner warmth.' },
  { name: 'Moon aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Moon in 4th house : Exact', description: 'Peak day. Host mother; bring the partner home.' },
  { name: 'Moon aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mercury in 6th house', description: 'Empathetic peer/workplace-relationship work. Soft conflict-resolution.' },
  { name: 'Moon aspect Mercury in 6th house : Starts', description: 'Window opens. Soften the technical tone.' },
  { name: 'Moon aspect Mercury in 6th house : Exact', description: 'Peak day. Hold the warm reconciliation.' },
  { name: 'Moon aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Venus in 12th house', description: 'Emotional warmth on private intimacy, foreign-love, devotional bond.' },
  { name: 'Moon aspect Venus in 12th house : Starts', description: 'Window opens. Plan the retreat.' },
  { name: 'Moon aspect Venus in 12th house : Exact', description: 'Peak day. Take the foreign call; sit with devotion together.' },
  { name: 'Moon aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mars in 1st house', description: 'Emotional charge on warrior identity in love. Body and heart aligned.' },
  { name: 'Moon aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mars in 1st house : Exact', description: 'Peak day. Lead from heart and gut.' },
  { name: 'Moon aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Jupiter in 9th house', description: 'Emotional pull toward shared values, ethics, foreign-friend warmth.' },
  { name: 'Moon aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Jupiter in 9th house : Exact', description: 'Peak day. Deep values-conversation lands.' },
  { name: 'Moon aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on public-couple reputation. Sensitive 48-hour window.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day. Hold warm-but-firm couples-conversation.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Rahu in 5th house', description: 'Emotional charge on romance-ambition. Watch obsessive craving.' },
  { name: 'Moon aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Rahu in 5th house : Exact', description: 'Peak day. The fame-pull peaks.' },
  { name: 'Moon aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Ketu in 11th house', description: 'Emotional detachment from friend-network. Mutual-friends feel cool.' },
  { name: 'Moon aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Ketu in 11th house : Exact', description: 'Peak day. Cool friend-feeling peaks.' },
  { name: 'Moon aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Sun in 5th house', description: 'Sharp romance/creative communication. Love letters; bold dating-app messaging.' },
  { name: 'Mercury aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Sun in 5th house : Exact', description: 'Peak day. Send the bold romantic letter.' },
  { name: 'Mercury aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Moon in 4th house', description: 'Emotionally tuned home/family writing. Mother-letters, family-with-partner memos.' },
  { name: 'Mercury aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Moon in 4th house : Exact', description: 'Peak day. Send the lease, the mother-letter.' },
  { name: 'Mercury aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mercury in 6th house', description: 'Peak peer/sibling/workplace-relationship clarity window of any quarter.' },
  { name: 'Mercury aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mercury in 6th house : Exact', description: 'Peak day. Settle the long-pending peer or sibling conversation.' },
  { name: 'Mercury aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Venus in 12th house', description: 'Graceful private-intimacy and foreign-friend writing.' },
  { name: 'Mercury aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Venus in 12th house : Exact', description: 'Peak day. Send the foreign-love letter.' },
  { name: 'Mercury aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mars in 1st house', description: 'Punchy bold self-communication in love. Founder-narrative refresh.' },
  { name: 'Mercury aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mars in 1st house : Exact', description: 'Peak day. Send the bold personal-narrative letter.' },
  { name: 'Mercury aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Jupiter in 9th house', description: 'Visionary writing about values/ethics/foreign-relationship.' },
  { name: 'Mercury aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Jupiter in 9th house : Exact', description: 'Peak day. Draft the vow; send the ethics-letter.' },
  { name: 'Mercury aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Disciplined public-couple communication.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day. Send the joint formal announcement.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Rahu in 5th house', description: 'Bold romance-communication. Verify before sending.' },
  { name: 'Mercury aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Rahu in 5th house : Exact', description: 'Peak day. Viral romance-pitch lands.' },
  { name: 'Mercury aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Ketu in 11th house', description: 'Sharp-detached friend-network communication. Cool group-text leadership.' },
  { name: 'Mercury aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Ketu in 11th house : Exact', description: 'Peak day. Cold friend-network logistics close.' },
  { name: 'Mercury aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Sun in 5th house', description: 'Graceful romance-authority. Aesthetic date-nights, mentee-warmth, charm-driven courtship.' },
  { name: 'Venus aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Sun in 5th house : Exact', description: 'Peak day. Launch the beautiful date or proposal.' },
  { name: 'Venus aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Moon in 4th house', description: 'Beautiful home/mother/family-with-partner window.' },
  { name: 'Venus aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Moon in 4th house : Exact', description: 'Peak day. Sign, host, beautify.' },
  { name: 'Venus aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mercury in 6th house', description: 'Diplomatic peer/sibling/workplace warmth. Difficult colleagues become receptive.' },
  { name: 'Venus aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mercury in 6th house : Exact', description: 'Peak day. The hard peer-talk lands warmly.' },
  { name: 'Venus aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Venus in 12th house', description: 'Peak private-intimacy/foreign-love/devotional warmth. Hidden patrons of the heart surface.' },
  { name: 'Venus aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Venus in 12th house : Exact', description: 'Peak day. Foreign love-news lands; retreat-mandate clarifies.' },
  { name: 'Venus aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mars in 1st house', description: 'Mars-Venus warmth on persona. Charm-driven founder-style asks.' },
  { name: 'Venus aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mars in 1st house : Exact', description: 'Peak day. Make the warm bold ask.' },
  { name: 'Venus aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Jupiter in 9th house', description: 'Graceful foreign/dharma-of-love window. Diplomatic foreign-friend engagement.' },
  { name: 'Venus aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Jupiter in 9th house : Exact', description: 'Peak day. Sign the foreign-relationship deal warmly.' },
  { name: 'Venus aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Softens public-couple face. Couples-photos, brand campaigns favored.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Rahu in 5th house', description: 'Glamour-amplified romance window. Spotlight romance, fame-driven courtship. Verify substance.' },
  { name: 'Venus aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Rahu in 5th house : Exact', description: 'Peak day. Take the spotlight — anchor in dharma.' },
  { name: 'Venus aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Ketu in 11th house', description: 'Graceful but cool friend-network warmth. Bonus-of-the-network arrives muted.' },
  { name: 'Venus aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Ketu in 11th house : Exact', description: 'Peak day. Friend-warmth lands; feel without grasping.' },
  { name: 'Venus aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Sun in 5th house', description: 'Fiery romance-authority push. Bold courtship, passionate launches. Verify Rahu doesn\'t inflate.' },
  { name: 'Mars aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Sun in 5th house : Exact', description: 'Peak day. Launch hard; verify integrity.' },
  { name: 'Mars aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Moon in 4th house', description: 'Heated home-and-family-with-partner push. Decisive real-estate moves.' },
  { name: 'Mars aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Moon in 4th house : Exact', description: 'Peak day. Sign or close decisively; soften family communication.' },
  { name: 'Mars aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mercury in 6th house', description: 'Fiery peer/sibling/workplace conflict-push. Win the dispute, settle the friend-debt.' },
  { name: 'Mars aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mercury in 6th house : Exact', description: 'Peak day. Defeat the rival; close the case.' },
  { name: 'Mars aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Venus in 12th house', description: 'Heated private-intimacy/foreign-love zone. Bedroom-intensity peaks.' },
  { name: 'Mars aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Venus in 12th house : Exact', description: 'Peak day. Foreign or hidden battle peaks.' },
  { name: 'Mars aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mars in 1st house', description: 'Peak self-action window of any two-year cycle in love. Founder-style commitment-asks.' },
  { name: 'Mars aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mars in 1st house : Exact', description: 'Peak day. Take the founder-step; sign the bold paper.' },
  { name: 'Mars aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Jupiter in 9th house', description: 'Fiery values/ethics push. Wedding-planning aggression; ceremony-fight.' },
  { name: 'Mars aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Jupiter in 9th house : Exact', description: 'Peak day. Force the wedding-decision; settle the ethics-question.' },
  { name: 'Mars aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Fiery public-couple push. Bold joint career-step; demand the formal commitment.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day. Take the joint formal step.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Rahu in 5th house', description: 'Fiery romance-ambition with shadow. Bold affairs or passionate moves; verify twice.' },
  { name: 'Mars aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Rahu in 5th house : Exact', description: 'Peak day. Take the bold leap — anchor in dharma.' },
  { name: 'Mars aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Ketu in 11th house', description: 'Heated friend-network push with detachment. Group-decisions, mutual-friend conflicts decisive.' },
  { name: 'Mars aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Ketu in 11th house : Exact', description: 'Peak day. Win the network battle.' },
  { name: 'Mars aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Sun in 5th house', description: 'Peak wisdom on romance/children/creativity. Major commitment-launches; mentor-blessed marriage.' },
  { name: 'Jupiter aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Sun in 5th house : Exact', description: 'Peak day. Launch the principled relationship-step.' },
  { name: 'Jupiter aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Moon in 4th house', description: 'Wisdom-blessing on home/mother/family-with-partner. Buy-the-home-together.' },
  { name: 'Jupiter aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Moon in 4th house : Exact', description: 'Peak day. Sign the lease together; deepen with mother.' },
  { name: 'Jupiter aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mercury in 6th house', description: 'Wisdom on peer/workplace/sibling relationships. Difficult peers become teachers.' },
  { name: 'Jupiter aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mercury in 6th house : Exact', description: 'Peak day. Resolve the long sibling or peer issue.' },
  { name: 'Jupiter aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Venus in 12th house', description: 'Peak private-intimacy/foreign-love/devotional expansion. Foreign joint-sabbatical.' },
  { name: 'Jupiter aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Venus in 12th house : Exact', description: 'Peak day. Foreign-love news lands.' },
  { name: 'Jupiter aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mars in 1st house', description: 'Wisdom on warrior-identity in love. Take the larger relationship-role.' },
  { name: 'Jupiter aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mars in 1st house : Exact', description: 'Peak day. Accept the larger commitment.' },
  { name: 'Jupiter aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Jupiter in 9th house', description: 'Peak values/ethics/foreign-relationship window of any twelve-year cycle. Wedding/ceremony/vow ideal.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Exact', description: 'Peak day. Take the foreign-relationship step; the vow lands.' },
  { name: 'Jupiter aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on public-couple commitment. Marriage, formal-cohabitation, joint-prestige.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day. Take the formal commitment.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Rahu in 5th house', description: 'Wisdom on romance-ambition. The fame-of-love-pull gets a guru.' },
  { name: 'Jupiter aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Rahu in 5th house : Exact', description: 'Peak day. Principled romance-ambition crystallizes.' },
  { name: 'Jupiter aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Ketu in 11th house', description: 'Wisdom on detached friend-network. Joint network-prestige with detachment.' },
  { name: 'Jupiter aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Ketu in 11th house : Exact', description: 'Peak day. Major friend-event lands; honor without clinging.' },
  { name: 'Jupiter aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Sun in 5th house', description: 'Structural test of romance/children/creativity. Speculation in love tightens.' },
  { name: 'Saturn aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Sun in 5th house : Exact', description: 'Peak day. Romance-fame-pull is checked. Build for permanence.' },
  { name: 'Saturn aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Moon in 4th house', description: 'Heaviness on home/mother/family-with-partner. Mother-care intensifies.' },
  { name: 'Saturn aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Moon in 4th house : Exact', description: 'Peak day. Mother needs care; real-estate restructures.' },
  { name: 'Saturn aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mercury in 6th house', description: 'Favorable for service/peer-conflict mastery. Long-arc rebuilding of strained friendships.' },
  { name: 'Saturn aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mercury in 6th house : Exact', description: 'Peak day. The structural peer-resolution lands.' },
  { name: 'Saturn aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Venus in 12th house', description: 'Multi-year discipline on private-intimacy/foreign-love. Long-distance phases formalize.' },
  { name: 'Saturn aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Venus in 12th house : Exact', description: 'Peak day. Foreign-relationship formalizes.' },
  { name: 'Saturn aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mars in 1st house', description: 'Heavy structural test of warrior-identity in love. Slow rebuilding.' },
  { name: 'Saturn aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mars in 1st house : Exact', description: 'Peak day. The persona-in-love is tested.' },
  { name: 'Saturn aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Jupiter in 9th house', description: 'Discipline on values/ethics/foreign-relationship. Slow visa or ceremony-process.' },
  { name: 'Saturn aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Jupiter in 9th house : Exact', description: 'Peak day. The principle is tested.' },
  { name: 'Saturn aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Peak public-couple-restructure window of any thirty-year cycle. Marriage, formal cohabitation.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak day. Accept the multi-decade commitment chapter.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Rahu in 5th house', description: 'Discipline on romance-ambition. Speculative-love bubbles deflate.' },
  { name: 'Saturn aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Rahu in 5th house : Exact', description: 'Peak day. The fame-of-love bubble pops.' },
  { name: 'Saturn aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Ketu in 11th house', description: 'Disciplined friend-network. The network purges what is no longer dharmic.' },
  { name: 'Saturn aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Ketu in 11th house : Exact', description: 'Peak day. Structural friend-locks set.' },
  { name: 'Saturn aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Sun in 5th house', description: 'Peak romance-ambition window of any eighteen-year cycle. Verify dharma.' },
  { name: 'Rahu aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Sun in 5th house : Exact', description: 'Peak day. The bold love-leap presents — verify.' },
  { name: 'Rahu aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Moon in 4th house', description: 'Obsessive home/mother/relocation-with-partner chapter.' },
  { name: 'Rahu aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Moon in 4th house : Exact', description: 'Peak day. Foreign-relocation pull peaks.' },
  { name: 'Rahu aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mercury in 6th house', description: 'Favorable. Defeat a relationship-rival, settle long peer-debt.' },
  { name: 'Rahu aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mercury in 6th house : Exact', description: 'Peak day. Major peer or sibling adversary yields.' },
  { name: 'Rahu aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Venus in 12th house', description: 'Obsessive private-intimacy/foreign-love pull.' },
  { name: 'Rahu aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Venus in 12th house : Exact', description: 'Peak day. Foreign-love pull peaks.' },
  { name: 'Rahu aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mars in 1st house', description: 'Obsessive founder-identity push in love. New persona within partnership.' },
  { name: 'Rahu aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mars in 1st house : Exact', description: 'Peak day. Founder-leap in love presents — verify.' },
  { name: 'Rahu aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Jupiter in 9th house', description: 'Foreign-fortune obsession in love. International courtship.' },
  { name: 'Rahu aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Jupiter in 9th house : Exact', description: 'Peak day. Foreign-fortune leap presents.' },
  { name: 'Rahu aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Obsessive public-couple elevation push. Sudden status moves.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day. Bold public-couple-leap presents — verify.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Rahu in 5th house', description: 'Eighteen-year apex of romance-ambition cycle. Anchor in dharma.' },
  { name: 'Rahu aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Rahu in 5th house : Exact', description: 'Peak day. The romance-ambition cycle peaks.' },
  { name: 'Rahu aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Ketu in 11th house', description: 'Generational reckoning of friend-network. Mutual-friend turbulence.' },
  { name: 'Rahu aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Ketu in 11th house : Exact', description: 'Peak day. Friend-defining event lands; old network dissolves.' },
  { name: 'Rahu aspect Ketu in 11th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Sun in 5th house', description: 'Romance-authority eclipse. Old crush-ambition feels hollow.' },
  { name: 'Ketu aspect Sun in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Sun in 5th house : Exact', description: 'Peak day. Old romance dissolves; cleaner love remains.' },
  { name: 'Ketu aspect Sun in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Moon in 4th house', description: 'Home/mother/family-with-partner detachment.' },
  { name: 'Ketu aspect Moon in 4th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Moon in 4th house : Exact', description: 'Peak day. Simplification impulse peaks.' },
  { name: 'Ketu aspect Moon in 4th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mercury in 6th house', description: 'Peer/workplace-relationship detachment. Old conflicts dissolve quietly.' },
  { name: 'Ketu aspect Mercury in 6th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mercury in 6th house : Exact', description: 'Peak day. Old peer-enemies disengage on their own.' },
  { name: 'Ketu aspect Mercury in 6th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Venus in 12th house', description: 'Private-intimacy/foreign-love dissolution. Pilgrimage-pull strong.' },
  { name: 'Ketu aspect Venus in 12th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Venus in 12th house : Exact', description: 'Peak day. Old foreign-love channel closes.' },
  { name: 'Ketu aspect Venus in 12th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mars in 1st house', description: 'Founder-identity stripping in love. Old warrior-persona finished.' },
  { name: 'Ketu aspect Mars in 1st house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mars in 1st house : Exact', description: 'Peak day. Old persona dissolves.' },
  { name: 'Ketu aspect Mars in 1st house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Jupiter in 9th house', description: 'Values/ethics/foreign-friend detachment.' },
  { name: 'Ketu aspect Jupiter in 9th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Jupiter in 9th house : Exact', description: 'Peak day. Old principle dissolves.' },
  { name: 'Ketu aspect Jupiter in 9th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Public-couple eclipse. Old couples-image dissolves.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day. Old joint role dissolves.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Rahu in 5th house', description: 'Generational ambition vs. detachment reckoning in love.' },
  { name: 'Ketu aspect Rahu in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Rahu in 5th house : Exact', description: 'Peak day. Old romance-ambition ends; new seeds.' },
  { name: 'Ketu aspect Rahu in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Ketu in 11th house', description: 'Eighteen-year apex of friend-network detachment cycle.' },
  { name: 'Ketu aspect Ketu in 11th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Ketu in 11th house : Exact', description: 'Peak day. Old network completes its dissolve.' },
  { name: 'Ketu aspect Ketu in 11th house : Ends', description: 'Window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} relationship] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
