// db/seed_relationship_virgo.js
//
// Per-ascendant fill-in seed for the **relationship** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own — 11L in 11H)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga, yogakaraka)
//     Venus=7th (Pisces, exalted — Malavya Yoga, 2L+9L Dhana-Dharma)
//     Mars=8th (Aries, own)  Jupiter=4th (Sagittarius, own — Hamsa Yoga, 4L+7L)
//     Saturn=5th (Capricorn, own — 5L+6L)  Rahu=9th (Taurus)  Ketu=3rd (Scorpio)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose relationship-specific interpretations, then run:
//
//   node db/seed_relationship_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./relationship');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'You are read as the analytical, precise, articulate one in every relationship — and that is exactly the magnetic field. The right partner is drawn to your sharpness, your detail-care, your discriminating mind. Imperfection-spotting is your love language; learn to spend it on the world\'s problems together rather than the partner\'s small flaws. The body is a finely-tuned instrument; partners who respect routine, sleep, food-purity, and quiet thrive here. The shadow: the same precision that attracts can corrode if it slides into chronic critique. Be ruthless with the systems and gentle with the human.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'The spouse is also the family-money channel and the dharma teacher — three threads woven into one person. The right partnership funds the household, expands the wisdom, and stabilizes the voice. Marriage tends toward formal, traditional, ceremonially-anchored unions; the legal-and-relational structure carries weight. In-laws often become genuine financial allies. The shadow: a bad partnership detonates wealth and dharma simultaneously, so partner selection deserves more deliberation than any other life decision.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'Sibling dynamics carry transformational charge. Brothers and sisters are involved in some of your hardest, most-rebuilding chapters — inheritance disputes, health crises, restructuring of family roles. Communication style with siblings tends sharp, sometimes surgical. The shadow: small communication conflicts that escalate into 8th-house permanent fractures. Cool the message before it goes; siblings will outlive friends.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'The home is a teaching environment. Your mother (or mother-figure) is the original wisdom-source; her conversations shape your dharma. Family gatherings have a doctrinal, lineage-conscious quality. The partner you bring home will be evaluated by family elders for ethical fit, not just emotional fit. The shadow: parental dharma-projection — the family\'s preferred path may not be your dharma. Honor the lineage but choose the partner yourself.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Children, romance, and creative-collaborator relationships all run on a slow-burn, structured cadence. Romance feels like a long-term apprenticeship; love-at-first-sight is rare here. Children arrive late but stay loyal, often becoming structural-creative collaborators in middle life. The shadow: the inner-critic showing up in romance — the partner needs warmth, not the audit. Schedule discipline-free zones with children and lovers.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'Conflict-management lives in the same chamber as romance and children — meaning your relational disputes often have a structural / fairness / boundary-rules character. Daily-routine alignment with the partner matters more than peak-romance moments. Fights are usually about whose system gets followed. The shadow: turning the relationship into a compliance audit; in the 5th, warmth must outweigh fairness.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Spouse arrives through home, family, lineage, mother-channel introductions. The marriage itself often happens at the family seat or through an inherited tradition. The 7L in 4H means the marital home is the spiritual home — the place where your deepest peace lives. The shadow: confusing the family\'s preferred partner with your dharma-correct partner; check whether your love is yours or the lineage\'s.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'Crisis is a regular guest in the partnership. The spouse may go through a health, inheritance, or career-transformation chapter where you carry the weight; or you may, with the spouse carrying. The partnership is forged through these crises, not despite them. The shadow: thrill-seeking that confuses adrenaline for intimacy. The 8th here rewards the disciplined surgeon-spouse, not the cowboy-spouse.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'Your principal teacher tends to become your principal partner, or vice versa. Foreign-spouse, foreign-teacher, or foreign-met-on-pilgrimage partnership is a real structural possibility here. The dharma and the warmth converge. The shadow: confusing partner-pleasure with dharma-truth; check whether the principle requires this person, or whether the comfort does.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'The public-self / professional-identity is welded to who you are personally — meaning your partner will inevitably be drawn into the work. Best partnerships are with people who can hold the work-identity warmly, who do not need you to be off-duty to feel loved. The shadow: identity-collapse into the role, leaving the partner a spectator; protect the off-duty hours.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Friend-circles, alumni, communities, and peer-trust networks are the deepest sustained relational infrastructure. The Moon-own here makes long-arc female friendships especially load-bearing. The right partner integrates with this network warmly; the wrong one isolates you from it. The shadow: emotional dependency on group-mood; protect your sleep on big network weeks.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'Solitude, retreat, foreign-travel, and behind-the-scenes time are non-negotiable for your relational health. The right partner respects, even cherishes, your need for monastic solitude. Father-figure dynamics often play out abroad or behind closed doors. The shadow: the lonely 12H Sun can isolate inside the relationship — name the need for solitude rather than disappearing into it.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, the confidential / foreign / retreat relationship matters. The bond that lives off-stage carries the chapter.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, the wide-network warmth peaks. Alumni-friends, community bonds, peer-trust circles all carry weight.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, the analytical-precision identity attracts the right partner. The body, the bio, the way you articulate yourself in the room is the relational signal.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, the home-and-lineage channel anchors the relationship. Mother-line introduction, family-seat moment, in-law warmth all show up here.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, the relationship transforms through crisis. Inheritance, health, succession events welded into the partnership.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, structured romance and child-related decisions land. Slow-burn love consolidation, mentor-of-mentees relationships solidify.' },
  { name: 'Venus in 7th (Dispositor)', description: 'When this engine fires, the partnership pays out emotionally and financially. Anchor partner, spouse, principal collaborator carry the chapter. Most central relational engine for this chart.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak personal-magnetism window. The body radiates; the right partner sees you clearly. Best month for taking the relationship public, the founder-photo moment with partner, the principal-couple framing.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on family-finance and voice in the relationship. Money conversations with partner land warmly. Speak the financial truth gently.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on communication. Send the brave message, have the postponed conversation with the sibling, address the friction. Ketu zone — keep the message warm.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home-throne. Bring the partner home, host the family meal, take the in-law meeting. Hamsa territory — relational warmth radiates from the family seat.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on romance and children. Best window for the romantic gesture, the child-related decision, the creative-collaboration with partner. Saturn-territory — slow-burn romance peaks.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on conflict-management. Best window for the postponed clearing-the-air conversation, the boundary-setting, the daily-routine recalibration with partner.' },
  { name: 'Sun Transits the 7th House', description: 'Solar return-style activation of partnership. Annual peak relational visibility window. Marry, sign the JV, take the relationship public. Venus-7H territory — the warmth is structural here.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in the transformation chamber. Crisis-events in partnership land here — health, inheritance, succession. Walk slowly; the partnership is being forged.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma-alignment in the relationship. Pilgrimage with partner, foreign travel, teacher-tradition exploration together. Rahu zone — unconventional shared dharma surfaces.' },
  { name: 'Sun Transits the 10th House', description: 'Solar fire on the public-couple identity. Career-relationship intersections — partner attends the public event, the joint introduction, the public principal-couple moment.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on friend-circles and wide-network bonds. Alumni reunion warmth, community gathering with partner, peer-circle re-engagement. Moon-territory carries the warmth.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return through 12H. Annual peak for retreat-with-partner, foreign travel, off-grid relational windows. Light dimmed publicly but intimacy quietens beautifully.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of emotional charge on persona. The body wants warmth; the partner reads you tenderly. Take the warm-toned relational meeting.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on family-finance and voice. Soft-spoken money conversations land; speak the financial truth gently with partner.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on communication. The brave warm message lands; sibling-channel reaches out. Ketu zone — keep the message anchored.' },
  { name: 'Moon Transits the 4th House', description: 'Emotional pull to the home-throne. Mother-channel call, family gathering, partner-at-home warmth. Cook a real meal together.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on romance and children. The child wants the warm hour; the partner wants the playful moment; honor both.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict-management. The partner may push the trigger; respond from documentation, not reaction.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnership. Read the spouse / principal-client temperature before the meeting. Warm tone wins the day.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on transformation zone. Defer high-stakes relationship decisions two days. Old fears around chaos surface for processing.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward shared dharma. The pilgrimage thought, the foreign-trip-with-partner draft, the teacher-tradition exploration.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on the public-couple identity. Senior-relationship dynamics light up; the public moment with partner reads warm.' },
  { name: 'Moon Transits the 11th House', description: 'Moon-own peak for wide-network warmth. Alumni reach-outs, community-friend reconnections, peer-circle warmth. Take the warm group call.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; foreign and behind-the-scenes pull. Best for retreat planning, dream-led relational drafting, intimate solitude.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury through own + exalted lagna. Peak self-articulation in relationships. Refresh the way you describe yourself to partner; clarify the relational expectations cleanly.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation in the relationship. Have the postponed family-finance conversation; pin the joint pricing; record the shared values.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s home turf for short-burst communication. Peak window for sibling-channel deals, written outreach to partner, candid sales of your relational truth.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-throne articulation. The family-business memo, the in-law correspondence, the lineage-conscious documentation of relational decisions.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative articulation in romance and children. Love letter, child-curriculum design, structured-creative collaboration with partner.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp conflict-management articulation. Documentation of the dispute, written boundary-setting, surgical clearing-the-air memo.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, prenups, JV memos, contract negotiations — the relational paperwork lands cleanly.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-zone articulation. Inheritance documents, succession plans, will-related conversations with partner.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-articulation in the relationship. Foreign-travel-plan discussion with partner, doctrinal-alignment conversation, shared-teacher-exploration.' },
  { name: 'Mercury Transits the 10th House', description: 'Mercury through 10L\'s domain — peak public-couple articulation. Joint announcements, principal-couple framing, public-relationship documentation.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Group-chat updates, alumni-reunion organization, community-bond explicit documentation.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp confidential-relational articulation. Private letters, retreat-planning, off-grid relational drafts.' },
  { name: 'Venus Transits the 1st House', description: 'Personal-magnetism peak. Body, voice, taste, presence radiate. Partner sees you at your most attractive; client meetings convert with relational warmth.' },
  { name: 'Venus Transits the 2nd House', description: 'Venus on family-finance and voice. Joint-money decisions land warmly; verbal endearments come easily; family-money harmony peaks.' },
  { name: 'Venus Transits the 3rd House', description: 'Charm on communication. The warm message lands. Sibling-channel reconnections favored. Ketu zone — keep the warmth concrete.' },
  { name: 'Venus Transits the 4th House', description: 'Venus on the home-throne. Real-estate-with-partner decisions, mother-channel warmth, family-business soft-power moves.' },
  { name: 'Venus Transits the 5th House', description: 'Charm on romance and children. Best window for romantic gestures, child-celebration moments, creative-collaboration with partner.' },
  { name: 'Venus Transits the 6th House', description: 'Charm in conflict zone. The mediation, the diplomatic resolution, the gracefully-handled relational fight. Warmth disarms.' },
  { name: 'Venus Transits the 7th House', description: 'Venus return through own exalted 7th. Monthly peak partnership window. Sign the anchor relational contract, marry, lock the principal partner. Most important Venus transit of the year.' },
  { name: 'Venus Transits the 8th House', description: 'Charm in transformation zone. Severance / inheritance / health-crisis negotiated warmly with partner. Relational humanity in hard chapters.' },
  { name: 'Venus Transits the 9th House', description: 'Charm on dharma-alignment. Foreign-stage pilgrimage with partner, ethical-investment conversation, teacher-mentor warmth shared.' },
  { name: 'Venus Transits the 10th House', description: 'Charm on public-couple identity. Board-level couple events, principal-couple public moments, status-with-grace appearances.' },
  { name: 'Venus Transits the 11th House', description: 'Charm in wide-network zone. Alumni warmth, community-bond peaks, peer-circle relational gains.' },
  { name: 'Venus Transits the 12th House', description: 'Charm in moksha zone. Foreign-warmth, confidential intimacy, retreat-relationships, off-grid romantic windows.' },
  { name: 'Mars Transits the 1st House', description: 'Surge of force on persona. Sharp personal demands; bold relational pushes — but watch friction. The body burns hot; rest tonight.' },
  { name: 'Mars Transits the 2nd House', description: 'Force on family-finance and voice. Aggressive money conversations, sharp vocal demands. Avoid sharp tones in joint-finance discussions.' },
  { name: 'Mars Transits the 3rd House', description: 'Force on communication. Sibling friction risk; bold messaging. Ketu-zone — bluntness can land cold; check warmth.' },
  { name: 'Mars Transits the 4th House', description: 'Force on home-throne. Property-related disputes, family-business friction, in-law confrontation. Keep the temperature low at home.' },
  { name: 'Mars Transits the 5th House', description: 'Force on romance and children. Sharp playfulness or sharp friction with kids/partner; channel into creative-competitive games.' },
  { name: 'Mars Transits the 6th House', description: 'Force on conflict-management. Best window for offensive action — the boundary-setting confrontation, the lawsuit, the firing. Adversaries weaken.' },
  { name: 'Mars Transits the 7th House', description: 'Force on partnership. Sharp negotiations — but watch friction with spouse. Cool the temperature before signing or arguing.' },
  { name: 'Mars Transits the 8th House', description: 'Mars through own territory — surgical-execution window. Crisis events in partnership resolve under your hand. Walk slow, document.' },
  { name: 'Mars Transits the 9th House', description: 'Force on shared dharma. Aggressive doctrinal disputes with partner, sharp travel-plan negotiations, teacher-tradition disputes.' },
  { name: 'Mars Transits the 10th House', description: 'Force on public-couple identity. Joint career pushes, sharp principal-couple demands, competitive public appearances.' },
  { name: 'Mars Transits the 11th House', description: 'Force on wide-network. Aggressive group dynamics, sharp alumni-politics. Watch group friction with peers.' },
  { name: 'Mars Transits the 12th House', description: 'Force in moksha zone. Foreign-front aggressive moves with partner, confidential mandate sharpness. Protect intimacy from work-bleed.' },
  { name: 'Jupiter Transits the 1st House', description: 'Annual wisdom-on-self window. The body, the personal brand, the public self pick up dharma weight. Best year for personal-credential rebranding visible to partner.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Wisdom on family-finance and voice. Year-block to expand voice-led income, refine joint-finance ethics, take on dharma-aligned wealth structures with partner.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Wisdom on communication. Year-block to publish the relational truth, formalize the writing practice. Ketu-zone — keep the doctrine grounded.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter return through own + Hamsa-Yoga territory. Year-block for property purchase with partner, family-business inflection, mother-line teaching. Almost every major home decision compounds during this window.' },
  { name: 'Jupiter Transits the 5th House', description: 'Wisdom on romance and children. Year-block for child-related milestones, structured romantic consolidation, mentor-of-mentees relationships.' },
  { name: 'Jupiter Transits the 6th House', description: 'Wisdom in conflict-zone. Year-block where adversaries weaken, debts repay, regulatory clarity arrives. Health regimens institutionalize between partners.' },
  { name: 'Jupiter Transits the 7th House', description: 'Wisdom on partnership. Year-block for marriage, JV consolidation, anchor-client dharma-alignment, foreign-spouse / foreign-teacher partnerships.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom in transformation zone. Year-block for inheritance with partner, succession planning, longevity advisory together.' },
  { name: 'Jupiter Transits the 9th House', description: 'Wisdom in dharma-territory. Year-block for foreign-pilgrimage with partner, teacher-track elevation, doctrinal-alignment moves together.' },
  { name: 'Jupiter Transits the 10th House', description: 'Wisdom on public-couple identity. Year-block for the principal-couple appointment, joint lineage transfer, senior-track elevation together.' },
  { name: 'Jupiter Transits the 11th House', description: 'Wisdom in wide-network gains zone. Year-block for cooperative-platform leadership with partner, alumni-network institutionalization.' },
  { name: 'Jupiter Transits the 12th House', description: 'Wisdom in moksha zone. Year-block for retreat-residency with partner, foreign-research mandates together, white-paper publications.' },
  { name: 'Saturn Transits the 1st House', description: 'Saturn on persona. ~2.5-year discipline-on-self chapter. Body weight, posture, public framing tighten; partner sees the leaner you re-emerge.' },
  { name: 'Saturn Transits the 2nd House', description: 'Saturn on family-finance. Lean years on the joint balance sheet — structural rather than punitive. Voice deepens; money truths get said.' },
  { name: 'Saturn Transits the 3rd House', description: 'Saturn on communication. Rigorous editing of the relational message; sibling-channel relationships restructure. The loneliness during this period can be productive if held.' },
  { name: 'Saturn Transits the 4th House', description: 'Saturn on the home-throne. Heavy chapter for property, mother\'s health, family-business — but the *real* foundations of the home are built here.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn return through own 5H. ~2.5-year peak for structured romantic consolidation, child-related milestones requiring patience. Slow-burn romance reaches commitment-readiness.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn on adversary/health/debt. Long grind chapter — adversaries deplete themselves; health regimens become protocol-grade between partners.' },
  { name: 'Saturn Transits the 7th House', description: 'Saturn on partnership. Marriage / anchor-client tested for structural soundness. Weak partnerships fall away; sound ones harden into multi-decade ones. Exalted Venus 7H softens the lesson.' },
  { name: 'Saturn Transits the 8th House', description: 'Saturn on transformation zone. Heavy-but-gold chapter for inheritance / succession with partner. Walk slow; the surgical work pays.' },
  { name: 'Saturn Transits the 9th House', description: 'Saturn on dharma. Long-arc shared-doctrine chapter; foreign-teacher relationships tested for soundness. Weak teachers fall away.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on public-couple identity. ~2.5 years of slow elevation to the senior-couple track. Flashy-couple peers rotate; you remain.' },
  { name: 'Saturn Transits the 11th House', description: 'Saturn on wide-network. Structural rebuild of alumni / community / peer-circle channels. Some friends fall away; deep ones lock in for life.' },
  { name: 'Saturn Transits the 12th House', description: 'Saturn on moksha-zone. Heavy chapter for retreat-residency, foreign-mandate relationship, hospital/prison-related service. Body needs more sleep; honor it.' },
  { name: 'Rahu Transits the 1st House', description: 'Rahu on persona. ~18-month chapter of unconventional self-presentation in relationships. Risk: identity-overreach. Reward: breakthrough magnetism.' },
  { name: 'Rahu Transits the 2nd House', description: 'Rahu on family-finance. Speculative joint-income windows, foreign-currency exposure, unconventional vocal-led ventures with partner.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on communication. Foreign / disruptive content channels, viral writing about relational truth, unconventional sibling-network deals.' },
  { name: 'Rahu Transits the 4th House', description: 'Rahu on home-throne. Foreign-property windows with partner, unconventional family-business pivots, mother-line disruption.' },
  { name: 'Rahu Transits the 5th House', description: 'Rahu on romance and children. Speculative-romantic windows, foreign-curriculum ventures, viral creative collaboration with partner.' },
  { name: 'Rahu Transits the 6th House', description: 'Rahu on adversary-zone. Unconventional enemies, foreign litigation, viral conflict — Rahu in 6 typically defeats adversaries.' },
  { name: 'Rahu Transits the 7th House', description: 'Rahu on partnership. Foreign-spouse / foreign-anchor-client window, unconventional JV structures. Exalted Venus absorbs Rahu well.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on transformation. Speculative-equity events with partner, unconventional inheritance, foreign restructuring shared.' },
  { name: 'Rahu Transits the 9th House', description: 'Rahu return through 9H. ~18-month foreign-dharma chapter — unconventional teacher with partner, foreign credentialing together.' },
  { name: 'Rahu Transits the 10th House', description: 'Rahu on public-couple identity. Sudden public-couple elevation through disruptive channels — viral case study, foreign-stage breakthrough.' },
  { name: 'Rahu Transits the 11th House', description: 'Rahu on wide-network. Foreign-friend windfalls, viral community moves, unconventional board appointments shared.' },
  { name: 'Rahu Transits the 12th House', description: 'Rahu on moksha-zone. Foreign-retreat residencies with partner, confidential disruptive mandates, off-balance-sheet shared structures.' },
  { name: 'Ketu Transits the 1st House', description: 'Ketu on persona. Detachment from public visibility; identity-stripping chapter. The ego-self thins — useful for sabbatical thinking with partner.' },
  { name: 'Ketu Transits the 2nd House', description: 'Ketu on family-finance. Detachment from family-money attachment; voice quieter. Don\'t monetize the silence with partner.' },
  { name: 'Ketu Transits the 3rd House', description: 'Ketu return through own territory. Detachment from communication noise; sibling-channel disengagement. Best for solitary thinking; worst for relational marketing.' },
  { name: 'Ketu Transits the 4th House', description: 'Ketu on home-throne. Detachment from family-business attachment; property decisions feel oddly indifferent. Defer big purchases.' },
  { name: 'Ketu Transits the 5th House', description: 'Ketu on romance and children. Detachment from validation-romantic impulse. Saturn-territory + Ketu = unusually pure-form relational output.' },
  { name: 'Ketu Transits the 6th House', description: 'Ketu on adversary-zone. Detachment from old grievances with partner; the conflicts you thought mattered evaporate.' },
  { name: 'Ketu Transits the 7th House', description: 'Ketu on partnership. Detachment from anchor-client / spouse warmth; defer the big partnership signing. Exalted Venus usually softens.' },
  { name: 'Ketu Transits the 8th House', description: 'Ketu on transformation zone. Detachment from crisis-thrill; the inheritance / equity event arrives muted. Document carefully.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on dharma. Detachment from doctrinal certainty; the old shared teacher-track may stop fitting. Sabbatical from credentialing.' },
  { name: 'Ketu Transits the 10th House', description: 'Ketu on public-couple identity. Detachment from status-attachment; the public moment arrives muted but the private bond strengthens.' },
  { name: 'Ketu Transits the 11th House', description: 'Ketu on wide-network. Detachment from group-validation; some friends drift. Trust the silence.' },
  { name: 'Ketu Transits the 12th House', description: 'Ketu on moksha-zone. Detachment-on-detachment — deep retreat months with partner, foreign-solitude windows.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar light on persona — the partner reads you brighter, warmer. Best for taking the joint photo, the relationship-public moment.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Solar approach to lagna. Polish the relational presentation; the spotlight is rising.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Today the spotlight peaks. Make the joint declaration, take the public-couple mantle.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Light fades. Consolidate the relational visibility gains.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar light on the public-couple identity. Joint career-relationship moments, principal-couple appointments.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Solar approach to MC. Prep the senior-couple move.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Today the principal-couple spotlight peaks. Take the senior-platform appearance together.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Solar light fades from MC. Lock the senior-couple recognition.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Body wants warmth; partner reads you tenderly. Take the warm-toned relational meeting.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep softer outreach to partner.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Today the persona runs warm. Send the warm partner-pitch.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Warmth fades. Lock the warm-channel bonds.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-couple identity. Joint visibility benefits from warm tone.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Approach. Warm up senior-couple relationships.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Today public-couple read runs warm. Lead with relational warmth in senior meetings.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Warmth fades from MC. Lock the warm-status relationships.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury on persona — relational articulation peak. Refresh the way you describe yourself to partner; clarify expectations.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Approach. Draft the relational expectations.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Today precision-articulation peaks. Send the clarifying note to partner.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Mercury fades. Lock the articulation polish.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on public-couple identity. Joint announcements, principal-couple framing, relationship documentation.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Approach. Draft the joint announcement.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Today senior-couple articulation peaks. Submit the joint statement.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Mercury fades from MC. Lock the joint documentation.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Charm on persona. Partner sees you radiant; client meetings convert with relational warmth.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Approach. Prep the warm-relational outreach.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Today personal-charm peaks. Take the camera moments with partner.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Charm fades. Lock the warm-relational bonds.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Charm on public-couple identity. Joint board-level diplomacy, principal-couple warmth.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Approach. Soften senior-couple outreach.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Today senior-couple charm peaks. Take the joint board-level relational meeting.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Charm fades from MC. Lock the senior-couple alliance.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Force on persona. Bold relational pushes, demanding intimate moves favored — but watch friction.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Approach. Gather force for the bold relational ask.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Today force on persona peaks. Make the bold demand to partner. Body needs rest tonight.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Force fades. Lock the bold-push gains.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Force on public-couple identity. Joint career pushes, sharp principal-couple demands.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Approach. Gather force for the senior-couple push.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Today public-couple force peaks. Take the joint demanding stand.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Force fades. Cool the relational temperature.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom on persona. Lineage-anchored personal-brand moves visible to partner; dharma-aligned relational framing.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Approach. Polish the dharma-aligned relational framing.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Today wisdom on persona peaks. Take the lineage photo with partner.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Wisdom fades. Lock the lineage-anchored personal-relational gains.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Wisdom on public-couple identity. Senior-track elevation through dharma-aligned channels — the principled couple appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Approach. Position the senior-couple move as dharma-aligned.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Today senior-couple dharma-elevation peaks. Take the principled joint appointment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Wisdom fades from MC. Lock the dharma-aligned couple-status.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Discipline on persona. Strip-down of inflated self-image; partner sees the leaner you re-emerge.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Approach. Begin the personal discipline cycle visible in the relationship.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Today discipline-on-persona peaks. Make the lean, principled relational statement.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Discipline closing. Lock the leaner relational framing.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Discipline on public-couple identity. Slow, structural elevation to senior-couple track.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Approach. Begin the structural senior-couple positioning.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Today structural-couple peak. Take the slow-but-permanent joint promotion.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Discipline closing. The structural senior-couple track is in place.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Rahu on persona. Unconventional / foreign / disruptive personal-relational moves. Risk: identity-overreach. Reward: breakthrough.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Approach. The unconventional persona-pivot is gathering.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Today disruptive-persona peak. Make the unconventional relational move.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu fades. Decide which disruptive elements stay.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Rahu on public-couple identity. Sudden, unconventional senior-couple elevation — viral case study, foreign-stage breakthrough.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Approach. The unconventional senior-couple move is gathering.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Today disruptive-couple peak. Take the unconventional joint appointment.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu fades. Lock the disruptive couple-gains.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Ketu on persona. Detachment from public visibility; sabbatical-thinking favored. The ego-self thins.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Approach. The pull toward solitude rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Today persona-detachment peaks. Best for solitary intimacy; worst for self-promotion.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Detachment fading. Re-emerge with what survived the silence.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Ketu on public-couple identity. Detachment from couple-status-attachment; the public moment arrives muted.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Approach. Couple-status attachment unwinds.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Today couple-status detachment peaks. Useful information.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Detachment fading. The next couple-chapter starts on internal grounds.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural transformation in 5L+6L Saturn territory. Romance, child-related decisions, and creative-collaboration architecture rebuilt from the foundation.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Pressure builds on Saturn-territory. Begin documenting the structural relational architecture you want to preserve.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Today the generational rebuild peaks. The structured-relational framework is being re-cast at depth.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Pressure releases. The new structural architecture is in place.' },
  { name: 'Uranus conjunct Venus', description: 'Disruptive innovation on the partnership / income / dharma engine. Spouse, anchor-client, principal-teacher relationship undergoes sudden re-architecture. The unconventional partner becomes the right partner.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Disruptive pressure builds on partnership. The conventional model starts cracking.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Today the partnership rewiring peaks. The unconventional partner declaration lands.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption settling. The new partnership architecture is in place.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar return through 12th. Annual peak for retreat-with-partner, foreign work, intimate solitude.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Solar return approaching. Prep year-block strategic relational drafts.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Solar return peak. Take the new-year strategic drafts done together.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Solar return closing. Shadow-lane strategy on record.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar light on wide-network warmth. Alumni introductions, community gatherings, peer-circle relational moments.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Approach. Network-spotlight gathering.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Today network-spotlight peaks. Take the alumni call, the peer-bond meeting.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Spotlight fades. Lock the network-recognition.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar light on the yogakaraka. Annual peak for personal-craftsman visibility — the founder photo, the principal-of-X declaration with partner.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka spotlight gathering.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Today yogakaraka spotlight peaks. Make the founder declaration; take the principal-of-craft mantle.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Spotlight fades. Lock the principal-craftsman appointment.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar light on partnership. Visibility through contracts; spouse and principal-client dynamics light up.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Approach. Partnership-spotlight gathering.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Today partnership-spotlight peaks. Sign the anchor partnership; demand the JV terms.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Spotlight fades. Lock the public partnership.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar light on the surgical-transformation engine. Career-relationship intersections in crisis chapters.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Approach. Transformation-spotlight gathering.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Today crisis-spotlight peaks. Lead the restructuring; close the equity event with partner.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Spotlight fades. Lock the transformation gains.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar light on the home-throne / Hamsa. Real-estate decisions, family-business inflections, mother-line conversations all favored.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne spotlight gathering.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-spotlight peaks. Make the property purchase, the family-business move with partner.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Spotlight fades. Lock the home-throne move.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar light on the disciplined-creative / romance engine. Best for structured-romantic milestones, child-related decisions.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Approach. Romance-discipline spotlight gathering.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H spotlight peaks. Consolidate the structured romance; deliver the child-milestone.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Spotlight fades. Lock the structured-creative output.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Solar light on the foreign-dharma engine. International-stage talks, certifications, judicial proceedings together.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma spotlight gathering.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H spotlight peaks. Take the foreign-stage talk together.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Spotlight fades. Lock the foreign-dharma recognition.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Solar light on the detached-communication engine. Brave solitary-research push gets quiet recognition; sibling-channel reconnections.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research spotlight gathering.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H spotlight peaks. Publish the solitary research; the right people see it.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Spotlight fades. The solitary-research output stands on record.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on the moksha-solar engine. Inwardness, foreign-pull, confidential-relationship warmth.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane warmth gathers.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Today 12H emotional warmth peaks. Take the confidential warm-toned meeting with partner.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Warmth fades. Shadow-lane bond consolidated.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon return — wide-network warmth peaks. Alumni reach-outs, community reconnections, peer-circle warmth.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Moon return approaching. Network-warmth rising.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Moon return peak. Take the warm alumni call, community-leadership meeting.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Moon return closing. Warm network gains on record.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional charge on the yogakaraka. Body wants warmth in the relational framing; soft-toned partner meetings.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Approach. Personal-warmth rising.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Today personal-warmth peaks. Take the warm partner meeting.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Warmth fades. Lock the warm-channel bonds.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on partnership. Spouse / principal-client temperature read; warm tone wins the day.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Approach. Partnership-warmth rising.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Today partnership-warmth peaks. Take the warm-toned anchor meeting.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Warmth fades. Lock the warm-partner alliance.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on transformation zone. Defer high-stakes relationship decisions two days. Old fears around chaos surface.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Approach. Crisis-emotion rising.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Today crisis-weight peaks. Defer signings; let fear pass.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Weight fades. Re-engage the transformation work.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional charge on the home-throne / Hamsa. Mother-channel warmth peaks; family gatherings warm-pulse.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Approach. Home-warmth rising.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Today home-warmth peaks. Cook the meal with partner; take mother\'s call.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Warmth fades. The home-bond consolidated.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional charge on the disciplined-creative / romance engine. Structured romance picks up emotional warmth.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Approach. Romance-warmth rising.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Today romance-warmth peaks. Add heart to the structured bond.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Warmth fades. Warm-rigorous romance on record.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional charge on the foreign-dharma engine. Pilgrimage-with-partner thought, foreign-trip draft, unconventional-teacher warmth.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma warmth rising.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H warmth peaks. Make the foreign-teacher reach-out together.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Warmth fades. Foreign-dharma bond on record.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Emotional charge on the detached-communication engine. Solitary-research mood; the brave message that does not need a reply.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research warmth rising.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H warmth peaks. Write the brave message; do not need a reply.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Warmth fades. The solitary-research warmth locked.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Articulation on the moksha-solar engine. Confidential relational documentation; private letters; off-stage memos.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane writing picks up pace.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Today shadow-lane articulation peaks. Ship the confidential relational note.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Articulation fades. The private document is locked.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Articulation on the wide-network warmth. Alumni newsletter, community-platform posts, peer-circle explicit documentation.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Approach. Network-articulation gathers.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Today network-articulation peaks. Send the alumni note, the community update.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Articulation fades. The network-message on record.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury return — the most important relational-articulation aspect of the chart. Refresh the way you describe yourself to partner.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Mercury return approaching. Prep the personal-relational refresh.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Mercury return peak. Ship the relational-clarification note to partner.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Mercury return closing. The yogakaraka articulation is locked.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Articulation on partnership. Term sheets, prenups, JV memos, contract negotiations land cleanly.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Approach. Partnership-articulation gathers.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Today partnership-articulation peaks. Ship the term sheet, the JV memo.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Articulation fades. Partnership documents on record.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Articulation on transformation. Inheritance documents, succession plans, will-related conversations with partner.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Approach. Transformation-articulation gathers.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Today crisis-articulation peaks. Ship the succession plan, the will revision.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Articulation fades. The transformation document is locked.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Articulation on the home-throne / Hamsa. Real-estate paperwork, family-business memo, mother-channel correspondence.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne articulation gathers.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-articulation peaks. Ship the real-estate doc, the in-law memo.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Articulation fades. Home-throne document on record.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Articulation on the disciplined-creative / romance engine. Long-form joint research, child-curriculum design, structured-romance documentation.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-creative articulation gathers.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Today Saturn-5H articulation peaks. Ship the joint chapter, the child-curriculum module.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Articulation fades. The disciplined-creative document is locked.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Articulation on the foreign-dharma engine. Foreign-publication submissions with partner, doctrinal essays together.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma articulation gathers.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Today Rahu-9H articulation peaks. Submit the foreign piece together.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Articulation fades. The foreign-dharma submission on record.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Articulation on the detached-communication engine. Solitary research notes, lineage-content production, deep relational journaling.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research writing gathers.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'Today Ketu-3H articulation peaks. Ship the solitary piece.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Articulation fades. The solitary piece stands alone.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Charm on the moksha-solar engine. Foreign-warmth, confidential-collaboration, retreat-relationships with partner.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane warmth gathering.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Today Venus-on-12H-Sun peaks. Take the warm confidential meeting with partner.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Charm fades. Shadow-lane warmth locked.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Charm on the wide-network warmth. Alumni warm intros, community-product affection, peer-circle relational gains.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Approach. Network-charm gathering.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Today Venus-on-network peaks. Take the warm peer call.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Charm fades. Lock the warm-network bonds.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Charm on the yogakaraka. Personal-craftsman framing radiates; partner sees you radiant.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka-charm gathering.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Today Venus-on-yogakaraka peaks. Sign the warm contracts; lead with personal-craftsman grace.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Charm fades. Lock the warm-channel relationships.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus return — partnership engine peaks. Sign the anchor deal, marry, lock the principal client. Most important Venus aspect of the chart.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Venus return approaching. Prep the partnership move.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Venus return peak. Lock the structural partnership; warmth at annual peak.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Venus return closing. Partnership on record.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Charm on the surgical-transformation engine. Severance / inheritance / health-event negotiated warmly with partner.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Approach. Transformation-warmth gathering.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Today Venus-on-Mars-8H peaks. Negotiate the inheritance / restructuring with grace.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Charm fades. Warm transformation on record.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Charm on the home-throne / Hamsa. Real-estate beauty decisions, mother-channel warmth, family-business soft-power moves.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne charm gathering.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-charm peaks. Take the warm property meeting; soft family-business pivot.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Charm fades. Lock the warm home-throne move.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Charm on the disciplined-creative / romance engine. Structured romance picks up grace; child-related decisions warm.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Approach. Romance-charm gathering.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Today Venus-on-Saturn-5H peaks. The rigorous-romance picks up grace.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Charm fades. The graceful-rigorous romance on record.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Charm on the foreign-dharma engine. Foreign-stage talks land warmly with partner; ethical-investment intros.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma charm gathering.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Today Venus-on-Rahu-9H peaks. Take the warm foreign-stage talk together.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Charm fades. Warm foreign-dharma bond on record.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Charm on the detached-communication engine. Warm message that does not need a reply; gentle-sibling correspondence.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research warmth gathering.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'Today Venus-on-Ketu-3H peaks. Send the warm note that does not need a reply.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Charm fades. The gentle-research bond on record.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Force on the moksha-solar engine. Confidential / foreign mandates with partner sharpen; shadow-lane work pushes hard.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane work gathers force.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Today force-on-12H-Sun peaks. Push the confidential mandate hard.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Force fades. Shadow-lane gains lock in.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Force on the wide-network. Aggressive group dynamics, sharp peer politics. Watch group-friction.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Approach. Network-push gathers.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Today force-on-network peaks. Take the bold group stance.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Force fades. Network gains locked.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Force on the yogakaraka. Aggressive personal demands in the relationship; sharp principal-pitch. Body needs rest after.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Approach. Principal-craftsman gathers force.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Today force-on-yogakaraka peaks. Make the bold relational demand.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Force fades. Lock the bold-pitch gains; rest.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Force on partnership. Sharp negotiations — but watch friction with spouse. Cool the temperature before signing.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Approach. Partnership friction gathers.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Today partnership-force peaks. Demand the JV terms; cool the relational temperature.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Force fades. Partnership consolidates on the new terms.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars return — surgical-execution peak in the partnership. Health, inheritance, restructuring shared events resolve under your hand.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Mars return approaching. Transformation push gathers.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Mars return peak. Walk into the burning room with partner; stabilize the system.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Mars return closing. The crisis-resolution is on record.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Force on the home-throne / Hamsa. Aggressive property push, family-business confrontation, in-law negotiation. Keep home temperature low.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne friction gathers.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Today force-on-Jupiter-4H peaks. The property / family negotiation reaches its sharp point.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Force fades. Home-throne consolidates.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Force on the disciplined-creative / romance engine. Push to consolidate the relationship; competitive contest with partner.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Approach. Romance-discipline push gathers.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Today force-on-Saturn-5H peaks. Consolidate the structured romance; ship the long-form joint work.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Force fades. Disciplined-creative gains lock in.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Force on the foreign-dharma engine. Sharp doctrinal disputes with partner, foreign-stage assertions together.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Approach. Dharma-fight gathers.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Today force-on-Rahu-9H peaks. Take the doctrinal stand on the foreign stage.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Force fades. Foreign-dharma stand on record.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Force on the detached-communication engine. Sharp solitary writing; fierce sibling-channel confrontation.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Approach. Fierce-solitary push gathers.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Today force-on-Ketu-3H peaks. Ship the brave message; address the sibling friction.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Force fades. The solitary-research push consolidated.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom touches the moksha-solar engine in the relationship. Confidential / foreign-shared mandates take on dharma-weight; retreat-relationships pick up lineage value.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Approach. The shadow-lane relational work is gathering dharma weight.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Today wisdom on the 12th-Sun peaks. Lock the confidential / retreat relational chapter.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Wisdom fades. Document the dharma-weight gained.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on the wide-network warmth channel. Alumni-network institutionalization, community-led relational dharma.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Approach. The network-warmth channel picks up dharma framing.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Today wisdom-on-network peaks. Anchor wide-network bonds in ethical structure.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Wisdom fades. Lock the dharma-aligned network architecture.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom touches the central yogakaraka in the relational sphere. Personal-craftsman framing picks up doctrinal weight visible to partner.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Approach. The principal-craftsman framing gathers lineage authority.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Today wisdom-on-yogakaraka peaks. Take the principal-of-craft mantle with lineage backing.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Wisdom fades. The lineage-anchored role is locked in.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on the exalted partnership / dharma / wealth engine. Marriage with dharma-alignment, JV with ethical framing, anchor-client with teacher-quality.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Approach. Partnership picks up dharma weight.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Today wisdom-on-Venus-7H peaks. Lock the dharma-aligned partnership.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Wisdom fades. The principled partnership is consolidated.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on the surgical-transformation engine of the partnership. Inheritance, restructuring, equity events take on dharma-weight together.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Approach. The transformation chapter gathers dharma framing.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Today wisdom-on-Mars-8H peaks. Lock the dharma-aligned restructuring with partner.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Wisdom fades. The principled crisis-resolution is on record.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter return — most important transit-aspect of the chart. Hamsa-Yoga territory amplified. Year-block for property purchase with partner, family-business inflection, mother-line teaching.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Jupiter return approaching. Prep the home-throne move.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Jupiter return peak. Make the property purchase, the family-business move with partner.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Jupiter return closing. The home-throne lineage move is consolidated.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on the disciplined-creative engine in romance and children. Doctoral framework receives lineage-authority; structured romance gains teacher-quality.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Approach. Disciplined-creative work picks up lineage weight.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Today wisdom-on-Saturn-5H peaks. Lock the institutional curriculum or structured romance.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Wisdom fades. The disciplined-creative architecture is institutionalized.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Wisdom on the foreign-dharma engine. Unconventional teacher-track gains lineage authority; foreign credentialing materializes with partner.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma move gathers framing.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Today wisdom-on-Rahu-9H peaks. Take the unconventional teacher-track move together.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Wisdom fades. Foreign-dharma path is on record.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on the detached-communication engine. Solitary research, doctrinal writing without audience-pressure. Sibling-channel dharma surfaces.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research framing gathers.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'Today wisdom-on-Ketu-3H peaks. Publish the lineage-rooted research.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Wisdom fades. The solitary-research output is locked in.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Discipline on the moksha-solar engine. Long-arc confidential / foreign mandate with partner.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Approach. Shadow-lane discipline cycle beginning.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Today Saturn-on-12H-Sun peaks. Lock the long-arc confidential mandate.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Discipline phase closing. Shadow-lane structure in place.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Discipline on the wide-network warmth. Structural rebuild of alumni / community channels.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Approach. Network-discipline cycle beginning.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Today Saturn-on-network peaks. Some friends fall away; deep ones lock in for life.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Discipline phase closing. Pruned network is structural.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Discipline on the yogakaraka. Slow personal-craftsman re-architecture visible to partner. Body weight, posture tighten.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Approach. Yogakaraka discipline cycle beginning.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Today Saturn-on-yogakaraka peaks. Make the lean, principled relational statement.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Discipline phase closing. The leaner principal-craftsman in place.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Discipline on partnership. Marriage / anchor-client tested for structural soundness. Weak partnerships fall away; strong ones harden.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Approach. Partnership-discipline cycle beginning.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Today Saturn-on-Venus-7H peaks. The structural partnership decision lands.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Discipline phase closing. The structurally-sound partnership on record.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Discipline on the surgical-transformation engine. Heavy-but-gold restructuring with partner.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Approach. Transformation-discipline cycle beginning.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Today Saturn-on-Mars-8H peaks. Lock the long-arc restructuring move with partner.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Discipline phase closing. The structural transformation in place.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Discipline on the home-throne / Hamsa. Heavy chapter for property, mother\'s health — the *real* foundations of the home are built here.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne discipline cycle beginning.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Today Saturn-on-Jupiter-4H peaks. The structural home / family decision lands.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Discipline phase closing. Home-throne foundation structural.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn return — disciplined-creative chapter peak in romance and children. Slow-burn romance reaches commitment-readiness; child milestones consolidate.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn return approaching. Disciplined-creative chapter gathering.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Saturn return peak. Lock the structured-romance commitment.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn return closing. The multi-decade relational moat in place.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Discipline on the foreign-dharma engine. Slow, structural foreign credentialing with partner.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Approach. Foreign-dharma discipline cycle beginning.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Today Saturn-on-Rahu-9H peaks. Lock the foreign credential, doctrinal framework together.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Discipline phase closing. Foreign-dharma structure in place.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Discipline on the detached-communication engine. Long-form solitary research, lineage-content production with multi-year cadence.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Approach. Solitary-research discipline cycle beginning.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Today Saturn-on-Ketu-3H peaks. Lock the long-form solitary project.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Discipline phase closing. The lineage-research output on record.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Disruption on the moksha-solar engine. Sudden foreign / confidential mandate with partner; speculative shadow-lane work.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Approach. Disruptive shadow-lane move gathering.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Today Rahu-on-12H-Sun peaks. Take the unconventional foreign-retreat with partner.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Disruption fading. Lock or release the unconventional move.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Disruption on the wide-network warmth. Foreign-friend windfalls, viral community moves, unconventional alumni dynamics.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Approach. Network-disruption gathering.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Today Rahu-on-network peaks. Ride the viral wave; take the unconventional peer seat.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Disruption fading. Decide which gains stay.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Disruption on the yogakaraka. Unconventional / foreign personal-brand pivot visible to partner.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Approach. Disruptive principal-craftsman move gathering.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Today Rahu-on-yogakaraka peaks. Make the unconventional public-brand move.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Disruption fading. Lock the breakthrough; drop overreach.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Disruption on partnership. Foreign-spouse / foreign-anchor-client window. Exalted Venus 7H absorbs Rahu well — the unusual partner often turns out to be the right one.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Approach. Disruptive partnership move gathering.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Today Rahu-on-Venus-7H peaks. The unconventional partner declaration lands.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Disruption fading. The unusual partnership consolidated.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Disruption on the surgical-transformation engine. Speculative-equity events with partner, unconventional inheritance.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Approach. Disruptive transformation gathering.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Today Rahu-on-Mars-8H peaks. Walk into the high-velocity transformation; harness, do not chase.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Disruption fading. Transformation gains documented.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Disruption on the home-throne / Hamsa. Foreign-property windows, unconventional family-business pivots.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne disruption gathering.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Today Rahu-on-Jupiter-4H peaks. Take the foreign-property move with partner.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Disruption fading. The unconventional home-throne move consolidated.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Disruption on the disciplined-creative / romance engine. Speculative-romantic windows, foreign-curriculum ventures.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Approach. Romance-disruption gathering.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Today Rahu-on-Saturn-5H peaks. Take the unconventional romantic move; ground in disciplined craft.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Disruption fading. The unconventional-romance output on record.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Rahu return — foreign-dharma engine peaks. Unconventional teacher with partner, foreign credentialing together. The unconventional path is the path during this window.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return approaching. Foreign-dharma chapter gathering.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'Rahu return peak. Make the foreign-teacher / unconventional-doctrine move together.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'Rahu return closing. The unconventional dharma path consolidated.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Nodal-axis activation on communication. Foreign / disruptive content channels, viral writing about relational truth.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Approach. Nodal-axis communication disruption gathering.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Today nodal-axis peak. The viral / foreign content move lands.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal pressure fading. The unconventional content gains documented.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on the moksha-solar engine. The 12H Sun thins further — pure shadow-lane intimacy, ego-free retreat-relationship.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Approach. The 12H solar light dims.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Today detachment-on-12H-Sun peaks. Best for retreat-with-partner; ego-free intimacy.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Detachment fading. The shadow-lane bond consolidates.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on the wide-network warmth. Some friends drift; alumni channel quiets. Signal: prune the network.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Approach. Group-warmth fades.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Today network-detachment peaks. Trust the silence; some peers walk away.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Detachment fading. The pruned network reveals real members.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on the yogakaraka. Identity-stripping window in the relationship — the principal-craftsman essence remains; the ego-frame thins.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Approach. Public-craftsman ego-frame loosens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Today yogakaraka-detachment peaks. Best for solitary intimacy; worst for self-promotion.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Detachment fading. The leaner principal-craftsman re-emerges.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on partnership. Defer big partnership signing if possible. Warmth feels distant; trust the lull.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Approach. Partnership warmth dims.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Today partnership-detachment peaks. Defer signings; allow the relational lull.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Detachment fading. Partnership warmth returns.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on the surgical-crisis engine. Inheritance / health-event arrives muted. Document; do not chase adrenaline.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Approach. Crisis-thrill loosens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Today crisis-detachment peaks. Transformation passes through quietly.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Detachment fading. The quiet transformation is on record.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on the home-throne / Hamsa engine. Family-business attachment loosens; mother-line conversation goes quiet.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Approach. Home-throne attachment loosens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Today Hamsa-detachment peaks. Family-business decisions feel oddly indifferent.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Detachment fading. The home-throne re-engages quieter.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on the disciplined-creative engine. Validation-seeking romantic impulse fades; the relational work nobody asked for becomes the work that matters.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Approach. Validation-attachment loosens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Today creative-detachment peaks. Make the relational gesture nobody is asking for.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Detachment fading. The pure-form output stands alone.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Detachment on the foreign-dharma engine. Doctrinal certainty loosens; shared teacher-track may stop fitting.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Approach. Doctrinal certainty wobbles.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Today doctrine-detachment peaks. Useful sabbatical from teacher-track ambition together.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Detachment fading. The teacher-track returns on different terms.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Ketu return — communication-detachment peak. Sibling-channel goes quiet; relational-marketing impulse fades.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Approach. Communication-attachment loosens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Ketu return peak. Drop the relational marketing; the bond stands alone.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu return closing. Re-engage communication on lighter terms.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} relationship] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
