// db/seed_advice_taurus.js
//
// Per-ascendant fill-in seed for the **advice** category, scoped to a
// representative Taurus ascendant native with:
//   Ascendant: Taurus
//   Natal placements (sidereal Lahiri):
//     Sun=4th (Leo, own)  Moon=3rd (Cancer, own)  Mercury=5th (Virgo, own+exalted)
//     Venus=1st (Taurus, own — Malavya Yoga)  Mars=7th (Scorpio, own — Ruchaka Yoga)
//     Jupiter=11th (Pisces, own)  Saturn=10th (Aquarius, own — Sasa Yoga, yogakaraka)
//     Rahu=8th (Sagittarius)  Ketu=2nd (Gemini)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose advice-specific interpretations, then run:
//
//   node db/seed_advice_taurus.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./advice');

const ASCENDANT = 'Taurus';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Venus ruler of the 1st House in the 1st House', description: 'You are the magnet. Slow, deliberate, sensual presence is your operating system. Rushed days misfire; the body wants steady tempo, the room wants the considered move. Honor the comfort, but do not let it stagnate. Build daily rituals — body care, beauty, taste, simple repeated pleasures. The shadow: comfort-trap. The same magnetism that pulls people in can quietly become a couch you do not get up from.' },
  { name: 'Mercury ruler of the 2nd House in the 5th House', description: 'Speak less, write more. The voice carries weight when it has been preceded by considered language. Family-money topics are best handled as creative projects — the spreadsheet treated like the script — and the household responds to careful documentation more than to spontaneous appeal.' },
  { name: 'Moon ruler of the 3rd House in the 3rd House', description: 'Daily life rides on small bursts of courage in communication. The brave message you have been postponing is the one to send today. Sibling-channel and peer-channel rapport carry your week — invest in them. The shadow: emotional reactivity in the message. When the day is hot, sleep before sending the bold note.' },
  { name: 'Sun ruler of the 4th House in the 4th House', description: 'Home is the throne. Spend deliberate time there; the work-from-home setup is not a fallback, it is a structural advantage. Honor mother and family-of-origin patterns. The shadow: paternal projection coloring choices that should be yours alone — see the inherited expectation, then choose freely.' },
  { name: 'Mercury ruler of the 5th House in the 5th House', description: 'Mercury exalted on its creative-intellect throne. Trust the analytical reading of situations; the mind here is at peak diagnostic. Use writing, journaling, sharp planning — they will save you weeks. The shadow: over-mentalizing the moment that wants to be felt. Some hours stay non-verbal.' },
  { name: 'Venus ruler of the 6th House in the 1st House', description: 'Daily friction shows on the body. The fight does not stay in the air; it lodges in shoulders, sleep, skin. When the body signals, audit the recent days for the trigger. The shadow: charm used to dodge friction will compound the underlying issue. Resolve, do not deflect.' },
  { name: 'Mars ruler of the 7th House in the 7th House', description: 'Partner and counterparties are the engine — Ruchaka Mars on the 7H throne. The deal, the JV, the spouse, the principal-client carry the day\'s torque. Bring the partner into the decision early; do not move alone when collaboration is the structural truth. The shadow: combative reactivity that detonates the relationship — channel intensity into shared mission, not at each other.' },
  { name: 'Jupiter ruler of the 8th House in the 11th House', description: 'Sudden transformations route through the wide friend-network. Inheritance-conversations, joint-finance shifts, occult-research breakthroughs come from international and ethical-friend channels. Trust the network for the deep moves; isolate yourself and the transformation arrives harder.' },
  { name: 'Saturn ruler of the 9th House in the 10th House', description: 'Dharma and structure are fused. The principle-driven move is the strategic move. Long-arc, ethical, lawful work is what compounds; shortcut-seeking flattens. Honor the slow path; what survives is permanent.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Build for the long horizon. Slow promotions, structural authority, multi-decade roles — Sasa Yoga compounds across years, not quarters. Today is one brick in a 30-year wall; place it well and move on. The shadow: workaholism that erodes everything else. Cap the hours.' },
  { name: 'Jupiter ruler of the 11th House in the 11th House', description: 'Wide friend-circle is your ecosystem. Reach out to one international or long-arc friend each week; the network is the wealth-channel and the wisdom-channel both. The shadow: generosity that pays out faster than it earns. Pace the wisdom-flow through proper structures.' },
  { name: 'Mars ruler of the 12th House in the 7th House', description: 'Behind-the-scenes work feeds the public partnership. The confidential effort, the foreign mandate, the off-balance-sheet initiative — these mature into the visible deal. The shadow: hidden conflicts with the partner that drain liquidity invisibly. Name the friction early.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 4th (Dispositor)', description: 'When this engine fires, go home. Cook a meal, sit at the family-table, anchor in property. The home is the medicine.' },
  { name: 'Moon in 3rd (Dispositor)', description: 'When this engine fires, send the brave note. The communication you have been postponing is the right move today. Sibling-channel rapport carries.' },
  { name: 'Mercury in 5th (Dispositor)', description: 'When this engine fires, write before deciding. The journal, the spreadsheet, the analytical note clarifies the situation. The mind is exalted; trust it.' },
  { name: 'Venus in 1st (Dispositor)', description: 'When this engine fires, slow down. The day responds to deliberate presence — the considered word, the unhurried move, the elegant choice. Hurried days misfire.' },
  { name: 'Mars in 7th (Dispositor)', description: 'When this engine fires, bring the partner into the decision. The deal, the JV, the spouse — they hold the torque. Don\'t move alone.' },
  { name: 'Jupiter in 11th (Dispositor)', description: 'When this engine fires, reach out to the wide network. The international friend, the long-arc mentor, the cooperative-platform ally. The wisdom and the gain both route through them.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, build slowly. Today is one brick in a 30-year wall. Place it well and move on.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual self-visibility peak. Take the leadership move, the founder declaration, the public stage. Watch ego friction with father-figures.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar focus on voice and family-money. Negotiate, record, lock the salary. Mind throat care.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on communication. Send the bold note; push the campaign sequence.' },
  { name: 'Sun Transits the 4th House', description: 'Annual home-throne activation. Real-estate decisions, family-business inflection, work-from-home founder moves.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on creative-intellect. Launch the script, the course, the speculative analysis, the public lecture.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on adversary-management. Take the hard HR conversation, the regulatory filing, the long-postponed lawsuit.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on partnerships. Sign the JV, demand the terms, take the deal public.' },
  { name: 'Sun Transits the 8th House', description: 'Solar light in the transformation chamber. Restructuring, succession, equity-events surface. Verify each opaque move.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma. International stages, certifications, judicial processes, teacher-mentor moves.' },
  { name: 'Sun Transits the 10th House', description: 'Annual peak career-visibility. Launch the flagship; demand the title; lead the competitive pitch.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on wide-network. Bonus-pool conversations, board invitations, international-network introductions.' },
  { name: 'Sun Transits the 12th House', description: 'Behind-the-scenes mode. Confidential mandates, retreats, foreign correspondence favored.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional-self window. Show up warm; channel into a body-anchored move.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on voice and family-money. Soft-spoken negotiations land.' },
  { name: 'Moon Transits the 3rd House', description: 'Monthly courage-communication peak. Send the brave note; take the candid call.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-emotion peak. Cook a real meal; sit at the family table.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creativity. Capture the warm draft; do not over-edit.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on conflict. Respond from documentation, not reaction.' },
  { name: 'Moon Transits the 7th House', description: 'Monthly partnership-pulse peak. Read the temperature before the meeting.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on transformation. Defer high-risk decisions two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma. The mentor-call, the pilgrimage thought.' },
  { name: 'Moon Transits the 10th House', description: 'Monthly career-pulse peak. Public reception is warm.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth in network. Reach out to the long-arc friend.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness. Quiet-time, retreat planning, dream-led strategy.' },
  { name: 'Mercury Transits the 1st House', description: 'Sharp self-articulation. Refresh the bio, the founder-story.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Lock the family-finance plan.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s home turf. Peak window for content, sales sequences, sibling-channel deals.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-throne articulation. Real-estate paperwork, family-business memos.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury exalted. Peak creative-intellect month. Ship the script, publish the analysis.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp adversary-management. The audit memo, the litigation brief.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership articulation. Term sheets, JV memos.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-articulation. Document the opaque deal precisely.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma-articulation. Publish the paper, file the certification.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp career-public articulation. Press releases, all-hands updates.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. International newsletters, board memos.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp behind-the-scenes articulation. Confidential memos, retreat-strategy drafts.' },
  { name: 'Venus Transits the 1st House', description: 'Venus on Malavya throne — peak personal-magnetism month. Slow, deliberate, sensual moves land.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on voice and family-money. Soft-spoken negotiations soften the household.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on communication. Tone the message; charm carries the bold note further.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on home-throne. Aesthetic upgrades to the workspace, family-business diplomacy.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on creative-intellect. Performance, design, course aesthetics.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on adversary-management. Mediated settlements, charm-led HR.' },
  { name: 'Venus Transits the 7th House', description: 'Beauty on partnership. Anchor-deal warmth, JV diplomacy.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in transformation chamber. Equity-event diplomacy, restructuring with grace.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on dharma. International stages with grace, ethics-led design moves.' },
  { name: 'Venus Transits the 10th House', description: 'Peak public-aesthetic visibility. Brand campaigns, design-led PR.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on wide-network. Cooperative-platform diplomacy, international-friend warmth.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on behind-the-scenes. Confidential design work, retreat aesthetics.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on the body. Bold founder moves; watch impulsivity. Pair speed with discipline.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on voice. Aggressive negotiation; argue from documentation.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on communication. Bold sales sequences, fierce pitch-mode.' },
  { name: 'Mars Transits the 4th House', description: 'Mars on home-throne. Don\'t fight family in heat — wait two days.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on creative-intellect. Bold creative shipping, contested speculative bets.' },
  { name: 'Mars Transits the 6th House', description: 'Mars\'s strong terrain. Press the audit, push the lawsuit.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on its own throne (Ruchaka activation). Peak partnership-action year. Sign the JV; divorce the dead deal.' },
  { name: 'Mars Transits the 8th House', description: 'Mars in transformation. Surgical action; verify each fight.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on dharma. Bold teaching declarations, judicial filings.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on career-throne. Bold competitive pitches; demand title-bumps.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on wide-network. Bold international moves, contested platform pushes.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential combat. Behind-the-scenes warrior energy.' },
  { name: 'Jupiter Transits the 1st House', description: 'Major year for self-expansion. Public-mantle assumption; ambition declaration.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Major year for income and voice expansion. Salary jumps, family-money inflows.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Major year for communication-expansion. Publishing, broadcasting, sales-leadership.' },
  { name: 'Jupiter Transits the 4th House', description: 'Major year for home-throne expansion. Real-estate acquisition; family-business growth.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for creative-intellect expansion. Course-platform breakthrough.' },
  { name: 'Jupiter Transits the 6th House', description: 'Major year for adversary-victory. Long lawsuits resolve favorably.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major year for partnership-expansion. Spouse / principal-client inflection.' },
  { name: 'Jupiter Transits the 8th House', description: 'Major year for transformation-zone gains. Inheritance, equity-event windfalls.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major year for dharma-expansion. Foreign credentials, teaching breakthroughs.' },
  { name: 'Jupiter Transits the 10th House', description: 'Major year for public-career expansion. Chief-of-something offers.' },
  { name: 'Jupiter Transits the 11th House', description: 'Jupiter on its own throne. Peak wide-network gain year of the cycle.' },
  { name: 'Jupiter Transits the 12th House', description: 'Major year for behind-the-scenes expansion. Foreign work, retreats, pilgrimage.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on body and identity. What survives is permanent.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on income, voice, family-finance. Structure the savings ritual.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on communication. Long-arc content systems compound.' },
  { name: 'Saturn Transits the 4th House', description: 'Multi-year discipline on home-throne. Real-estate restructuring, mother\'s health.' },
  { name: 'Saturn Transits the 5th House', description: 'Multi-year discipline on creative-intellect. The 3-year script, the slow course.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain. Multi-year adversary-mastery. Patience and paperwork win.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partnership. Strong deals formalize; weak ones end.' },
  { name: 'Saturn Transits the 8th House', description: 'Multi-year reckoning in transformation chamber. Inheritance disputes, equity delays.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year dharma-discipline. Long credential paths, teaching-institution leadership.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on its own throne (Aquarius 10H — Sasa peak). The 2.5-year cycle that crystallizes the next 30-year structural authority.' },
  { name: 'Saturn Transits the 11th House', description: 'Multi-year discipline on wide-network gains. Cooperative platforms formalize.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on behind-the-scenes. Long retreat-chapter, foreign mandates.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive identity-reinvention. Verify each move.' },
  { name: 'Rahu Transits the 2nd House', description: 'Eighteen-month obsession on voice and family-money. Verify get-rich schemes.' },
  { name: 'Rahu Transits the 3rd House', description: 'Eighteen-month obsessive communication chapter. Verify integrity of viral content.' },
  { name: 'Rahu Transits the 4th House', description: 'Eighteen-month home-throne obsession. Verify each property title.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month obsessive creative chapter. Verify ethical bedrock.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Long-running enemies fall; chronic conflicts resolve unconventionally.' },
  { name: 'Rahu Transits the 7th House', description: 'Eighteen-month obsessive partnership chapter. Verify counterparty integrity.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on its strong terrain. Eighteen-month obsessive transformation chapter. Verify everything.' },
  { name: 'Rahu Transits the 9th House', description: 'Eighteen-month foreign-dharma obsession. International guru-pull.' },
  { name: 'Rahu Transits the 10th House', description: 'Eighteen-month career-reinvention obsession. Verify each pivot.' },
  { name: 'Rahu Transits the 11th House', description: 'Eighteen-month obsessive wide-network chapter. Verify integrity.' },
  { name: 'Rahu Transits the 12th House', description: 'Eighteen-month foreign-confidential obsession. Hidden mandates surface.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month identity-stripping. Sit; do not over-correct.' },
  { name: 'Ketu Transits the 2nd House', description: 'Eighteen-month detachment from voice, family-money. Cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Eighteen-month communication-detachment. Old loops feel finished.' },
  { name: 'Ketu Transits the 4th House', description: 'Eighteen-month home-throne detachment. Family-business attachment dissolves.' },
  { name: 'Ketu Transits the 5th House', description: 'Eighteen-month creative-detachment. Speculative cravings fall away.' },
  { name: 'Ketu Transits the 6th House', description: 'Eighteen-month adversary-detachment. Long enemies fade quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Eighteen-month partnership-detachment. Old deal feels finished.' },
  { name: 'Ketu Transits the 8th House', description: 'Eighteen-month transformation-acceleration. Old crises evaporate.' },
  { name: 'Ketu Transits the 9th House', description: 'Eighteen-month dharma-detachment. Old guru-attachments fade.' },
  { name: 'Ketu Transits the 10th House', description: 'Eighteen-month career-eclipse. Old role feels weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month wide-network detachment. Friend-circles drift.' },
  { name: 'Ketu Transits the 12th House', description: 'Eighteen-month behind-the-scenes detachment. Old retreats close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar fire on persona. Lead with quiet authority today.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Visibility window opens.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak visibility day. Take the public-mantle move.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Visibility window closes.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar fire on career-public. Senior-track move favored.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-visibility window opens.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the elevation, accept the prestige role.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-visibility window closes.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on persona. Show up warm.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Body-anchored warmth lands.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on public-status. Warm public reception.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the warm-toned senior meeting.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp self-articulation. Refresh personal materials.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Send the polished introduction.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp public articulation. Status memos, press releases.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Issue the formal status update.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Venus on its Malavya throne. Peak charm-day. The smile, the warm ask, the unhurried move work.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Malavya-window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak Malavya day. Show up where you want to be seen; magnetism is at peak.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Malavya-window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Beauty on public-status. Brand campaigns, design-led PR.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak day. Launch the campaign with grace.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Mars on the body. Bold action; pair speed with discipline.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the bold founder move.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Mars on public-status. Bold competitive pitches.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak day. Lead the charge, demand the title.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom-expansion of persona. Take the elevation; declare the larger ambition.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Accept the public-mantle.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Peak career-expansion. Take the prestige role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak day. Accept the chief-of-something role.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body and identity. Slow down, simplify.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Hold steady; the reckoning is acute.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Saturn on its own MC throne. Peak structural-career window.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day. The structural authority crystallizes.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion. Watch obsession.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the unconventional move — but check basics.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic public-status expansion. Verify each pivot.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-stripping. Old persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit with the dissolution; do not leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Public-status eclipse. Old role feels hollow.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. The role dissolves quietly. Don\'t cling.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning. Old hierarchies collapse; you emerge with rebuilt structural authority on the Aquarian-Saturn frontier.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning begins. Position for the long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak day. The old system breaks; the new is forced into being. Hold authority where others panic.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Transformation chapter completes. Permanent foundation set.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the Venus-on-lagna magnetism. Unexpected pivots in self-presentation.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak day. The unexpected pivot lands. Decide fast but with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Disruption window closes. Integrate.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 4th house', description: 'Solar fire on home-throne. Real-estate, family-business, mother-line conversations favored.' },
  { name: 'Sun aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Sun in 4th house : Exact', description: 'Peak day. Sign the property paper, host the family-business meeting.' },
  { name: 'Sun aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Moon in 3rd house', description: 'Visibility through brave communication. Send the bold note.' },
  { name: 'Sun aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Moon in 3rd house : Exact', description: 'Peak day. Push the campaign; take the candid call.' },
  { name: 'Sun aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mercury in 5th house', description: 'Solar fire on creative-intellect. Course launches, scripts, performances peak.' },
  { name: 'Sun aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mercury in 5th house : Exact', description: 'Peak day. Ship the script, launch the course.' },
  { name: 'Sun aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Venus in 1st house', description: 'Solar fire on personal-magnetism. Founder-as-product visibility peaks.' },
  { name: 'Sun aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Venus in 1st house : Exact', description: 'Peak day. Take the public-face move.' },
  { name: 'Sun aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Solar fire on partnership. Sign the JV, demand the terms.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Peak day. Take the deal public.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Jupiter in 11th house', description: 'Solar fire on wide-network. International introductions, board invitations.' },
  { name: 'Sun aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Jupiter in 11th house : Exact', description: 'Peak day. Accept the board seat, take the international intro.' },
  { name: 'Sun aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on Sasa-Yoga career engine. Public-mantle assumption.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak day. Take the chief role.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Rahu in 8th house', description: 'Solar fire in foreign-occult chamber. Verify each opaque move.' },
  { name: 'Sun aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Rahu in 8th house : Exact', description: 'Peak day. Document the opaque deal precisely.' },
  { name: 'Sun aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Ketu in 2nd house', description: 'Solar light on detached-voice zone. Old earning-paths feel finished.' },
  { name: 'Sun aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the channel that has been hollow.' },
  { name: 'Sun aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Sun in 4th house', description: 'Emotional charge on home-throne. Cook a meal, host the family.' },
  { name: 'Moon aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Sun in 4th house : Exact', description: 'Peak day. Family-table conversations heal.' },
  { name: 'Moon aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Moon in 3rd house', description: 'Emotional courage on communication. Brave message day.' },
  { name: 'Moon aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Moon in 3rd house : Exact', description: 'Peak day. Send the brave note.' },
  { name: 'Moon aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mercury in 5th house', description: 'Emotional charge on creative-intellect. Capture the warm draft.' },
  { name: 'Moon aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mercury in 5th house : Exact', description: 'Peak day. Don\'t over-edit the warmth out.' },
  { name: 'Moon aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Venus in 1st house', description: 'Emotional charge on personal-magnetism. Heart-led day.' },
  { name: 'Moon aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Venus in 1st house : Exact', description: 'Peak day. Show up warm; the body is feeling-led.' },
  { name: 'Moon aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge on partnership. Read partner\'s temperature.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Peak day. Lead with warmth in the partner-meeting.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Jupiter in 11th house', description: 'Emotional warmth on wide-network. Reach out to the long-arc friend.' },
  { name: 'Moon aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the warm board call.' },
  { name: 'Moon aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional weight on Sasa-engine. Take the warm-toned senior call.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day. Honor the long-arc structure with warmth.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Rahu in 8th house', description: 'Emotional charge on foreign-occult chamber. Defer opaque moves two days.' },
  { name: 'Moon aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Rahu in 8th house : Exact', description: 'Peak day. Let the emotion settle before deciding.' },
  { name: 'Moon aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Ketu in 2nd house', description: 'Emotional detachment from voice / family-money. Old paths feel hollow.' },
  { name: 'Moon aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Ketu in 2nd house : Exact', description: 'Peak day. Sit with the income-paths feeling weightless.' },
  { name: 'Moon aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Sun in 4th house', description: 'Sharp home-throne articulation. Real-estate paperwork, family-business memos.' },
  { name: 'Mercury aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Sun in 4th house : Exact', description: 'Peak day. Send the formal property memo.' },
  { name: 'Mercury aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Moon in 3rd house', description: 'Sharp courage-articulation. Bold sales sequences, brave journalism drafts.' },
  { name: 'Mercury aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Moon in 3rd house : Exact', description: 'Peak day. Send the bold sequence.' },
  { name: 'Mercury aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mercury in 5th house', description: 'Mercury\'s exalted return on the creative-intellect throne. Peak articulation day.' },
  { name: 'Mercury aspect Mercury in 5th house : Starts', description: 'Exalted-window opens.' },
  { name: 'Mercury aspect Mercury in 5th house : Exact', description: 'Peak day. Ship the masterpiece — the mind is at peak yearly setting.' },
  { name: 'Mercury aspect Mercury in 5th house : Ends', description: 'Exalted-window closes.' },
  { name: 'Mercury aspect Venus in 1st house', description: 'Sharp personal-brand articulation. Bio refresh, brand decks.' },
  { name: 'Mercury aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Venus in 1st house : Exact', description: 'Peak day. Publish the polished bio.' },
  { name: 'Mercury aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Sharp partnership articulation. Term sheets, JV memos.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Peak day. Send the term sheet.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Jupiter in 11th house', description: 'Sharp wide-network articulation. International newsletters.' },
  { name: 'Mercury aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Jupiter in 11th house : Exact', description: 'Peak day. Send the international update.' },
  { name: 'Mercury aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Sharp Sasa-Yoga articulation. Public-mantle press releases.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day. Issue the formal authority paper.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Rahu in 8th house', description: 'Sharp foreign-occult articulation. Document the opaque deal.' },
  { name: 'Mercury aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Rahu in 8th house : Exact', description: 'Peak day. The paperwork is your protection.' },
  { name: 'Mercury aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Ketu in 2nd house', description: 'Sharp voice-detachment articulation. Audit the earning paths.' },
  { name: 'Mercury aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Ketu in 2nd house : Exact', description: 'Peak day. Write the closure of the dead channel.' },
  { name: 'Mercury aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Sun in 4th house', description: 'Beauty on home-throne. Aesthetic upgrades to the workspace.' },
  { name: 'Venus aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Sun in 4th house : Exact', description: 'Peak day. Soften the property negotiation.' },
  { name: 'Venus aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Moon in 3rd house', description: 'Beauty on courage-communication. Tone the bold message.' },
  { name: 'Venus aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Moon in 3rd house : Exact', description: 'Peak day. Send the elegantly-worded brave note.' },
  { name: 'Venus aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mercury in 5th house', description: 'Beauty on creative-intellect. Performance-aesthetics, course-design grace.' },
  { name: 'Venus aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mercury in 5th house : Exact', description: 'Peak day. Polish the creative output.' },
  { name: 'Venus aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Venus in 1st house', description: 'Venus on its Malavya throne. Peak personal-magnetism day. Slow, deliberate, sensual presence is at peak.' },
  { name: 'Venus aspect Venus in 1st house : Starts', description: 'Malavya-window opens.' },
  { name: 'Venus aspect Venus in 1st house : Exact', description: 'Peak Malavya day. Show up where you want to be seen.' },
  { name: 'Venus aspect Venus in 1st house : Ends', description: 'Malavya-window closes.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Beauty on partnership. Anchor-deal warmth.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Peak day. Mediate the standoff with grace.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Jupiter in 11th house', description: 'Beauty on wide-network. Cooperative-platform diplomacy.' },
  { name: 'Venus aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Jupiter in 11th house : Exact', description: 'Peak day. Attend the elegant friend-event.' },
  { name: 'Venus aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Beauty on Sasa-Yoga career engine. Senior-network charm.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day. Take the elegant senior meeting.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Rahu in 8th house', description: 'Beauty in foreign-occult chamber. Verify under the gloss.' },
  { name: 'Venus aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Rahu in 8th house : Exact', description: 'Peak day. Take the elegant opaque meeting carefully.' },
  { name: 'Venus aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Ketu in 2nd house', description: 'Beauty on voice-detachment. Old earning-paths feel weightless.' },
  { name: 'Venus aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the hollow channel; do not over-justify.' },
  { name: 'Venus aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Sun in 4th house', description: 'Mars on home-throne. Don\'t fight family in heat.' },
  { name: 'Mars aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Sun in 4th house : Exact', description: 'Peak day. Defer family confrontation two days.' },
  { name: 'Mars aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Moon in 3rd house', description: 'Mars on courage-communication. Bold sales pushes.' },
  { name: 'Mars aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Moon in 3rd house : Exact', description: 'Peak day. Push the campaign; send the contested note.' },
  { name: 'Mars aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mercury in 5th house', description: 'Mars on creative-intellect. Bold creative shipping.' },
  { name: 'Mars aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mercury in 5th house : Exact', description: 'Peak day. Ship the bold script, place the contested bet.' },
  { name: 'Mars aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Venus in 1st house', description: 'Mars on personal-magnetism. Bold founder-of-self moves.' },
  { name: 'Mars aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Venus in 1st house : Exact', description: 'Peak day. Take the bold founder pivot.' },
  { name: 'Mars aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Mars on its own Ruchaka throne. Peak partnership-fire day. Sign the JV, divorce the dead deal.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Ruchaka-window opens.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Peak Ruchaka day. The deal is forced to clarity.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Ruchaka-window closes.' },
  { name: 'Mars aspect Jupiter in 11th house', description: 'Mars on wide-network. Bold international-circle moves.' },
  { name: 'Mars aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Jupiter in 11th house : Exact', description: 'Peak day. Push the international move.' },
  { name: 'Mars aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Mars on Sasa-Yoga career engine. Bold competitive pitches.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day. Demand the title-bump.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Rahu in 8th house', description: 'Mars in foreign-occult chamber. Surgical action with documentation.' },
  { name: 'Mars aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Rahu in 8th house : Exact', description: 'Peak day. Verify each fight before launching.' },
  { name: 'Mars aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Ketu in 2nd house', description: 'Mars on voice-detachment. Forcefully close the dead channel.' },
  { name: 'Mars aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Ketu in 2nd house : Exact', description: 'Peak day. Do not negotiate the closure.' },
  { name: 'Mars aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Sun in 4th house', description: 'Wisdom on home-throne. Real-estate gains, family-business expansion.' },
  { name: 'Jupiter aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Sun in 4th house : Exact', description: 'Peak day. Acquire the property; expand the family business.' },
  { name: 'Jupiter aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Moon in 3rd house', description: 'Wisdom on courage-communication. Publishing breakthroughs.' },
  { name: 'Jupiter aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Moon in 3rd house : Exact', description: 'Peak day. Publish the book; accept the broadcast.' },
  { name: 'Jupiter aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mercury in 5th house', description: 'Wisdom on creative-intellect. Course-platform breakthrough.' },
  { name: 'Jupiter aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mercury in 5th house : Exact', description: 'Peak day. Launch the course; accept the elevated role.' },
  { name: 'Jupiter aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Venus in 1st house', description: 'Wisdom on personal-magnetism. Public-face role expansion.' },
  { name: 'Jupiter aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Venus in 1st house : Exact', description: 'Peak day. Accept the public-face elevation.' },
  { name: 'Jupiter aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Wisdom on partnership. Anchor-deal expansion.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak day. Sign the elevated JV.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Jupiter in 11th house', description: 'Jupiter on its own throne (Pisces 11H). Peak wide-network gain day of the cycle.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Starts', description: 'Wide-network-gain window opens.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the international windfall.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Ends', description: 'Wide-network-gain window closes.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on Sasa-engine. Chief-of-something offers.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day. Accept the prestige seat.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Rahu in 8th house', description: 'Wisdom in foreign-occult chamber. Inheritance gains, equity-event windfalls.' },
  { name: 'Jupiter aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Rahu in 8th house : Exact', description: 'Peak day. Take the equity-event windfall.' },
  { name: 'Jupiter aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Ketu in 2nd house', description: 'Wisdom on voice-detachment. The lesson of the abandoned channel becomes the teaching artifact.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Exact', description: 'Peak day. Convert the abandoned earning channel into a teaching.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Sun in 4th house', description: 'Structural pressure on home-throne. Real-estate restructuring.' },
  { name: 'Saturn aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Sun in 4th house : Exact', description: 'Peak day. Take the slow real-estate decision.' },
  { name: 'Saturn aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Moon in 3rd house', description: 'Structural pressure on courage-communication. Long-arc content systems.' },
  { name: 'Saturn aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Moon in 3rd house : Exact', description: 'Peak day. Lock the multi-year content schedule.' },
  { name: 'Saturn aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mercury in 5th house', description: 'Structural pressure on creative-intellect. The 3-year project commitment.' },
  { name: 'Saturn aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mercury in 5th house : Exact', description: 'Peak day. Commit to the multi-year creative project.' },
  { name: 'Saturn aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Venus in 1st house', description: 'Structural pressure on personal-magnetism. Vanity-aesthetics fall away; durable presence sets in.' },
  { name: 'Saturn aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Venus in 1st house : Exact', description: 'Peak day. Eliminate vanity commitments; lock in durable structure.' },
  { name: 'Saturn aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Structural pressure on partnership. Weak deals end; strong ones formalize.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Peak day. Divorce the weak deal; formalize the strong JV.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Jupiter in 11th house', description: 'Structural pressure on wide-network. Cooperative platforms formalize.' },
  { name: 'Saturn aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Jupiter in 11th house : Exact', description: 'Peak day. Sign the cooperative-platform charter.' },
  { name: 'Saturn aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Saturn on its own Sasa throne. Peak structural-career day of the multi-decade cycle.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Sasa-Yoga peak window opens.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak Sasa day. Lock in title, contract, term — for the long horizon.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Sasa-Yoga peak window closes.' },
  { name: 'Saturn aspect Rahu in 8th house', description: 'Structural pressure in foreign-occult chamber. Patience pays.' },
  { name: 'Saturn aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Rahu in 8th house : Exact', description: 'Peak day. Hold the line on slow restructuring.' },
  { name: 'Saturn aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Ketu in 2nd house', description: 'Structural pressure on voice-detachment. Old channels formally close.' },
  { name: 'Saturn aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Ketu in 2nd house : Exact', description: 'Peak day. Sign the formal closure.' },
  { name: 'Saturn aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Sun in 4th house', description: 'Chaotic expansion on home-throne. Verify foreign-property paperwork.' },
  { name: 'Rahu aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Sun in 4th house : Exact', description: 'Peak day. Vet titles before signing.' },
  { name: 'Rahu aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Moon in 3rd house', description: 'Chaotic communication. Verify viral content twice.' },
  { name: 'Rahu aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Moon in 3rd house : Exact', description: 'Peak day. Push viral content carefully.' },
  { name: 'Rahu aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mercury in 5th house', description: 'Chaotic expansion on creative-intellect. Speculation-fevers; check ethical bedrock.' },
  { name: 'Rahu aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mercury in 5th house : Exact', description: 'Peak day. Take the speculative move with verification.' },
  { name: 'Rahu aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Venus in 1st house', description: 'Chaotic expansion on personal-magnetism. Sudden aesthetic-pivots.' },
  { name: 'Rahu aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Venus in 1st house : Exact', description: 'Peak day. Take the bold pivot — verify integrity.' },
  { name: 'Rahu aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic expansion on partnership. Verify counterparty integrity.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Peak day. Vet the controversial JV thoroughly.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Jupiter in 11th house', description: 'Chaotic expansion on wide-network. Verify ethical bedrock.' },
  { name: 'Rahu aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Jupiter in 11th house : Exact', description: 'Peak day. Take the viral-network move carefully.' },
  { name: 'Rahu aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Chaotic expansion on Sasa-Yoga career engine. Verify each pivot.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day. Vet the unconventional career move.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Rahu in 8th house', description: 'Rahu return on its strong terrain. Peak transformation-chaos day.' },
  { name: 'Rahu aspect Rahu in 8th house : Starts', description: 'Rahu-return window opens.' },
  { name: 'Rahu aspect Rahu in 8th house : Exact', description: 'Peak Rahu-return day. Take the equity-event with full documentation.' },
  { name: 'Rahu aspect Rahu in 8th house : Ends', description: 'Rahu-return window closes.' },
  { name: 'Rahu aspect Ketu in 2nd house', description: 'Axis-stress on voice-detachment. Sudden earning-path turbulence.' },
  { name: 'Rahu aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Ketu in 2nd house : Exact', description: 'Peak day. Defer voice-channel decisions; the axis is loud.' },
  { name: 'Rahu aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Sun in 4th house', description: 'Detachment on home-throne. Old plans feel weightless.' },
  { name: 'Ketu aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Sun in 4th house : Exact', description: 'Peak day. Sit with the home-throne weightlessness.' },
  { name: 'Ketu aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Moon in 3rd house', description: 'Detachment on courage-communication. Old loops feel finished.' },
  { name: 'Ketu aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Moon in 3rd house : Exact', description: 'Peak day. Release the dead message-loop.' },
  { name: 'Ketu aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mercury in 5th house', description: 'Detachment on creative-intellect. Speculative cravings fall away.' },
  { name: 'Ketu aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mercury in 5th house : Exact', description: 'Peak day. Release the dead creative-loop.' },
  { name: 'Ketu aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Venus in 1st house', description: 'Detachment on personal-magnetism. The magnetism quiets.' },
  { name: 'Ketu aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Venus in 1st house : Exact', description: 'Peak day. Sit with the magnetism feeling weightless; do not over-perform.' },
  { name: 'Ketu aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Detachment on partnership. Old deal feels finished.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Peak day. Release the dead deal.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Jupiter in 11th house', description: 'Detachment on wide-network. Old friend-circles drift.' },
  { name: 'Ketu aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Jupiter in 11th house : Exact', description: 'Peak day. Release the friend-circle that has run its course.' },
  { name: 'Ketu aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Detachment on Sasa-engine. The title that was the destination feels like a costume.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day. Sit with the role feeling hollow; the new role is forming silently.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Rahu in 8th house', description: 'Axis-detachment. Old crisis-loops dissolve.' },
  { name: 'Ketu aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Rahu in 8th house : Exact', description: 'Peak day. Release the crisis that has been the engine.' },
  { name: 'Ketu aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Ketu in 2nd house', description: 'Ketu return on voice-detachment. Old earning-channels formally close.' },
  { name: 'Ketu aspect Ketu in 2nd house : Starts', description: 'Ketu-return window opens.' },
  { name: 'Ketu aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the channel hollow for years.' },
  { name: 'Ketu aspect Ketu in 2nd house : Ends', description: 'Ketu-return window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} advice] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
