// db/seed_relationship_cancer.js
//
// Per-ascendant fill-in seed for the **relationship** category, scoped to a
// representative Cancer ascendant native with:
//   Ascendant: Cancer
//   Natal: Sun=3rd Moon=2nd Mercury=3rd Venus=4th(own) Mars=7th(exalted)
//          Jupiter=6th(own) Saturn=8th(own) Rahu=9th Ketu=3rd

const db = require('./relationship');

const ASCENDANT = 'Cancer';

const events = [
  // RULERS (12)
  { name: 'Moon ruler of the 1st House in the 2nd House', description: 'Relationships succeed when the partner can sit at your family table; they fail when family is held at arm\'s length. You attract people through your voice — the way you tell stories, the song you sing, the warmth in conversation. Sensitive to emotional weather; you read your partner\'s mood before they speak. Family wealth dynamics flow into romance, for better or worse.' },
  { name: 'Sun ruler of the 2nd House in the 3rd House', description: 'In partnership, money conversations are best held precisely, in writing, with data. The partner respects your editorial-minded approach to family finances. Father and elder-sibling figures shape your sense of "what relationship should look like" — sometimes more than you realize.' },
  { name: 'Mercury ruler of the 3rd House in the 3rd House', description: 'The partner who can match your text wit, edit your draft, parse your sequence — that\'s the long-term match. Younger siblings, peers, and same-stage friends are central to the relational ecosystem. Excellent for relationships that begin in a shared craft or work context.' },
  { name: 'Venus ruler of the 4th House in the 4th House', description: 'The relationship\'s strength is measured by how peaceful the home feels when both partners are in it. Mother and mother-figure dynamics shape your romantic template profoundly. You need beauty in the shared space; visual disorder erodes affection. Family business, real-estate, or hospitality work side-by-side with partner is favored.' },
  { name: 'Mars ruler of the 5th House in the 7th House', description: 'Children of relationships, mentees, creative collaborators all arrive through partnership channels. Speculative ventures with the partner are favored if they\'re disciplined. Romance flourishes in the structured-shared-project, not in the unstructured "let\'s see how it goes" mode.' },
  { name: 'Jupiter ruler of the 6th House in the 6th House', description: 'Hamsa-style means daily-service is the relationship\'s love language. You take care of partners through the schedule, the doctor appointment, the code of honor. Conflicts in relationships resolve when you fight on principle, not on emotion. The shadow: rescuing a partner is not loving them; learn the line.' },
  { name: 'Saturn ruler of the 7th House in the 8th House', description: 'Partnership karma routes through the transformation chamber. Marriage is structurally permanent but tested through extreme circumstances: long separations, family-of-origin reckonings, financial trials, mortality crises. What survives Saturn\'s 8H is forever. The right partner is older, slower, more established than you expect at first.' },
  { name: 'Saturn ruler of the 8th House in the 8th House', description: 'Vipareet on the in-laws/sex/shared-resources axis. In-laws may be challenging but ultimately become structural support. Sexuality deepens through structured commitment; casual is rarely satisfying for you long-term. Joint financial decisions with partner mature slowly and become permanent foundations.' },
  { name: 'Jupiter ruler of the 9th House in the 6th House', description: 'The partner\'s family teaches you something fundamental about principle. Long-distance or cross-cultural relationships favored when packaged as service-shared (working together for a cause, healing project, teaching mission).' },
  { name: 'Mars ruler of the 10th House in the 7th House', description: 'Career and partner fuse into one structuring force. The spouse is older or more established or simply more disciplined; they bring structural rigor. You attract the responsible, capable, hardworking partner — the one who shows up on time and signs the contract. Soft-romance fades fast; durable-action-romance lasts decades.' },
  { name: 'Venus ruler of the 11th House in the 4th House', description: 'Your closest friends become like family; they meet your mother. Gains from female friends and senior women are reliable. Friendships that start at home dinners outlast friendships that start at parties.' },
  { name: 'Mercury ruler of the 12th House in the 3rd House', description: 'Long-distance romance, written-letter intimacy, foreign-partner dynamics all favored. The shadow: careless words at intimate moments cost you. Pillow-talk is karmic — what\'s said in bed reverberates.' },

  // DISPOSITORS (5)
  { name: 'Mercury in 3rd (Dispositor)', description: 'The mind drives both your relational authority and your detachment habits. Partners must be able to handle your editorial mind without taking analytical observations as criticism. Fight with words — but choose them well; this Mercury cuts when wielded carelessly.' },
  { name: 'Sun in 3rd (Dispositor)', description: 'Methodical authority wired to emotional voice. In love, you express ego through what you ship, write, build for the partner; through small acts of methodical care more than grand gestures. Father-figure shapes the relationship template profoundly.' },
  { name: 'Venus in 4th (Dispositor)', description: 'Your natal Venus in own-sign 4H is the harmony engine self-disposing. The home is the relationship; the relationship is the home. Female partners, female friends, the mother archetype all run through your love life. Beauty is not luxury but emotional infrastructure.' },
  { name: 'Saturn in 8th (Dispositor)', description: 'The structural discipline supports the partnership engine. When this fires, the long-tested marriage proves itself; the in-law dynamic that took years to settle yields permanent stability.' },
  { name: 'Jupiter in 6th (Dispositor)', description: 'Service-with-wisdom anchors the foreign-dharma obsession. In relationships, you express love through care-taking the partner\'s health, schedule, principles. The shadow: rescuing isn\'t loving.' },

  // TRANSITS (108)
  { name: 'Sun Transits the 1st House', description: 'Your visibility rises but emotional fragility too. Push through awkwardness; show up in social settings even when you\'d rather hide. Watch ego friction with partner over "who gets the spotlight."' },
  { name: 'Sun Transits the 2nd House', description: 'Vocal/family-money season in relationships. Best for: family-finance conversations with partner, expressing what you value out loud, addressing family-of-origin dynamics directly.' },
  { name: 'Sun Transits the 3rd House', description: 'Peer/sibling/communication dynamics intensify. Write the difficult relationship letter; have the precise conversation; address peer-friend dynamics that affect the partnership.' },
  { name: 'Sun Transits the 4th House', description: 'Peak home-and-mother visibility. Excellent for: family gatherings, mother-attention, deepening home-partner rituals, real-estate-as-love decisions.' },
  { name: 'Sun Transits the 5th House', description: 'Sun in 5H Scorpio energizes romance, children, creative shared output, mentee-style relationships. Best for: planning kids, deepening creative collaboration, dating with intention.' },
  { name: 'Sun Transits the 6th House', description: 'Service-and-care peak. Show up for partner\'s health, daily admin, the boring doctor visits. Conflicts addressed on principle resolve favorably.' },
  { name: 'Sun Transits the 7th House', description: 'Annual peak for partnership visibility. Best window for: marriage, formal commitment, public coupling, major contract renegotiation with partner.' },
  { name: 'Sun Transits the 8th House', description: 'Sexuality, in-laws, joint-finance, mortality reckoning. Best for: addressing the long-pending shared-finance question; in-law conversations long deferred.' },
  { name: 'Sun Transits the 9th House', description: 'Dharma/foreign/long-distance relationship visibility. Best for: addressing cross-cultural dynamics, philosophical alignment, religious or value differences with partner.' },
  { name: 'Sun Transits the 10th House', description: 'Career-and-public-couple visibility. The partner appears in your career narrative; the relationship enters the public-status zone. Watch one partner\'s ambition eclipsing the other.' },
  { name: 'Sun Transits the 11th House', description: 'Friends, social network, group affiliations spotlight. Best for: introducing partner to wider circle, formalizing friendship-network alignment, hosting the senior peer event.' },
  { name: 'Sun Transits the 12th House', description: 'Private, behind-scenes, foreign-bedroom dynamics. Plan the retreat with partner; pull back from social visibility; address hidden resentments quietly.' },
  { name: 'Moon Transits the 1st House', description: 'Peak emotional warmth on your persona. The partner reads you generously; conversations land warmly.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on speech, family-money, voice. Talk warmly; the family-finance conversation lands.' },
  { name: 'Moon Transits the 3rd House', description: 'Emotional charge on writing, peer, sibling dynamics. Send the warm message; have the warm-toned call.' },
  { name: 'Moon Transits the 4th House', description: 'Peak home-emotional days. Cook the meal, light the candles, host the family dinner.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional intensity in romance, children, creative collaboration. Channel into shared creative push.' },
  { name: 'Moon Transits the 6th House', description: 'Service-empathy days. Show up for partner\'s daily struggles with warmth.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partnership zone. Read the partner\'s mood before pushing.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight in shared-resource/sexuality/in-law zone. Defer hard conversations 2 days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward big-vision-shared-future. Dream-talk OK; commit later.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on the public-couple image. Sensitive to how the relationship looks to others.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth toward friends, network. Reach out to the dear friend; accept the warm invitation.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional energy drains in social/public zone. Quiet days, private intimacy, behind-scenes care.' },
  { name: 'Mercury Transits the 1st House', description: 'Emotionally attuned communication of self in relationship. Best for: writing the personal-state letter, voicing the inner update warmly.' },
  { name: 'Mercury Transits the 2nd House', description: 'Passionate-vocal communication around speech, family-money, value. Best for: the family-finance discussion; the value-articulation talk.' },
  { name: 'Mercury Transits the 3rd House', description: 'Peak relationship-communication window. Send the difficult message; have the precise relationship discussion; address peer-friend dynamics.' },
  { name: 'Mercury Transits the 4th House', description: 'Diplomatic family/home/mother communication. Best for: real-estate paperwork as a couple, family-business calls, mother-letters.' },
  { name: 'Mercury Transits the 5th House', description: 'Investigative communication around romance, children, creative shared work. Due-diligence on romantic prospects.' },
  { name: 'Mercury Transits the 6th House', description: 'Service-communication peak in relationship. Best for: scheduling logistics, health-coordination, conflict-resolution-by-letter.' },
  { name: 'Mercury Transits the 7th House', description: 'Disciplined contractual communication with partner. Best for: drafting prenup-style understandings, formalizing relationship terms.' },
  { name: 'Mercury Transits the 8th House', description: 'Depth-writing on shared-resources, sexuality, in-laws. Forensic clarity on long-pending shared-finance issues.' },
  { name: 'Mercury Transits the 9th House', description: 'Debilitated, but Rahu amplifies. Best for: visionary letter-writing to long-distance partner. Worst for: precise contract language.' },
  { name: 'Mercury Transits the 10th House', description: 'Punchy public-couple communication. Best for: announcements, joint-public-statements, social media as a couple.' },
  { name: 'Mercury Transits the 11th House', description: 'Patient, well-structured outreach to friends/network as a couple. Wedding logistics, group-event planning.' },
  { name: 'Mercury Transits the 12th House', description: 'Confidential pillow-talk, foreign correspondence with partner, off-the-record relationship work. Watch leaks.' },
  { name: 'Venus Transits the 1st House', description: 'Exalted-style charm on your persona. Magnetism rises; the relationship feels easier.' },
  { name: 'Venus Transits the 2nd House', description: 'Luxurious vocal/family-money window. Speech turns warm; family-finance harmonizes.' },
  { name: 'Venus Transits the 3rd House', description: 'Graceful relationship-writing. The difficult email turns diplomatic; peer-friend dynamics warm.' },
  { name: 'Venus Transits the 4th House', description: 'Annual peak for home-as-love. Beautify the shared space; host gatherings; deepen with mother.' },
  { name: 'Venus Transits the 5th House', description: 'Peak romance/children/creative-pleasure days. Date nights, conception conversations, shared aesthetic work.' },
  { name: 'Venus Transits the 6th House', description: 'Diplomatic service excellence. Conflict resolution lands; the difficult dynamic softens.' },
  { name: 'Venus Transits the 7th House', description: 'Peak partnership-warmth window. Major commitment moves favored; engagement, marriage, formal coupling.' },
  { name: 'Venus Transits the 8th House', description: 'Diplomatic shared-finance/sexuality/in-law work. Best for: the gentle joint-finance conversation; warm in-law diplomacy.' },
  { name: 'Venus Transits the 9th House', description: 'Graceful long-distance/foreign/dharmic relationship dynamics. Travel as a couple favored.' },
  { name: 'Venus Transits the 10th House', description: 'Softer public-couple image. Best for: aesthetic moves as a couple, public-relations-of-the-relationship.' },
  { name: 'Venus Transits the 11th House', description: 'Friend/network warmth peaks. Hosting, group events, female-friend deepening, gainful introductions through circles.' },
  { name: 'Venus Transits the 12th House', description: 'Quiet pleasure with partner; foreign-luxury dynamics; hidden indulgences. Watch over-spending on travel/aesthetic.' },
  { name: 'Mars Transits the 1st House', description: 'Energy up but emotionally fragile. Push assertively but don\'t assume warm reception.' },
  { name: 'Mars Transits the 2nd House', description: 'Heated speech, family-money flares. Watch sharp words at the dinner table.' },
  { name: 'Mars Transits the 3rd House', description: 'Fierce communication window. Best for: shipping the difficult message; defending your relational position. Watch sharp emails.' },
  { name: 'Mars Transits the 4th House', description: 'Debilitated Mars meets exalted Venus. Family-home arguments flare; decisive home-action favored.' },
  { name: 'Mars Transits the 5th House', description: 'Drive in romance, children, creative play. Best for: pursuing the romance, defending the creative collaboration.' },
  { name: 'Mars Transits the 6th House', description: 'Favorable service-combat. Settle the long-pending logistical dispute; defend the schedule.' },
  { name: 'Mars Transits the 7th House', description: 'Peak partnership-action window. Major contract moves with partner favored. Watch domineering tone.' },
  { name: 'Mars Transits the 8th House', description: 'Surgical action in shared-resources/sexuality/in-law zone. Address long-deferred joint-finance issues.' },
  { name: 'Mars Transits the 9th House', description: 'Assertive long-distance/cross-cultural moves. Take the principled stand on the dharma-difference.' },
  { name: 'Mars Transits the 10th House', description: 'Bold public-couple assertion. The partnership steps into the public-status arena.' },
  { name: 'Mars Transits the 11th House', description: 'Heated friend/network dynamics. Aggressive event planning, peer-rivalry contests.' },
  { name: 'Mars Transits the 12th House', description: 'Hidden frictions stir. Avoid open warfare with partner over private matters.' },
  { name: 'Jupiter Transits the 1st House', description: 'Once-in-12-years personal-relational expansion. Mentors arrive who shape your relationship template; reputation as a partner grows.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Vocal/family-finance expansion. Family wealth grows; your speech-as-love-language deepens.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Flagship year for relationship-communication. Peer-friend leadership in your life expands.' },
  { name: 'Jupiter Transits the 4th House', description: 'Exalted-style home-love expansion. Buy the home together; deepen the family foundation.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for romance, children, shared creative output. Conception, creative collaborations, mentee-relationships flourish.' },
  { name: 'Jupiter Transits the 6th House', description: 'Service-with-wisdom relationship year. Health and admin care for partner deepens; chronic conflicts heal.' },
  { name: 'Jupiter Transits the 7th House', description: 'Debilitated Jupiter, but the natal Mars cushions. Major partnership moves favored; choose carefully.' },
  { name: 'Jupiter Transits the 8th House', description: 'Wisdom into shared-resources/sexuality/in-laws. Inheritance, in-law dynamics, joint finance favorably resolve.' },
  { name: 'Jupiter Transits the 9th House', description: 'Own-sign Jupiter on the dharma node. Major year for cross-cultural/long-distance relationships.' },
  { name: 'Jupiter Transits the 10th House', description: 'Public-couple expansion. Shared social standing rises; partner becomes more visible in your life narrative.' },
  { name: 'Jupiter Transits the 11th House', description: 'Friend/network expansion. Major social-circle growth; group-events that include partner shape long-term ties.' },
  { name: 'Jupiter Transits the 12th House', description: 'Private/foreign/sabbatical relationship dimension grows. Retreats with partner produce outsized resets.' },
  { name: 'Saturn Transits the 1st House', description: 'Sade Sati 2nd leg. Identity-as-partner under structural test. Slow down the relationship pace; build for permanence.' },
  { name: 'Saturn Transits the 2nd House', description: 'Sade Sati 3rd leg. Family-finance/voice/speech reckoning. The relationship\'s family-money architecture firms up.' },
  { name: 'Saturn Transits the 3rd House', description: 'Heavy communication chapter in relationships. The long-form letter, the years-deferred conversation.' },
  { name: 'Saturn Transits the 4th House', description: 'Home/mother/family-foundation under structural test. Buy carefully, hold patiently.' },
  { name: 'Saturn Transits the 5th House', description: 'Romance, children, creative collaboration demand seriousness. The casual relationship either gets serious or ends.' },
  { name: 'Saturn Transits the 6th House', description: 'Favorable. Long workplace/health/admin battles in relationship resolve through patience.' },
  { name: 'Saturn Transits the 7th House', description: 'Heavy partnership chapter. The marriage tested for staying power; what remains is permanent.' },
  { name: 'Saturn Transits the 8th House', description: 'Once-in-29-years deep transformation in shared-resources/sexuality/in-laws. The reckoning is total.' },
  { name: 'Saturn Transits the 9th House', description: 'Dharma/long-distance under structural pressure. The cross-cultural relationship demands compliance and patience.' },
  { name: 'Saturn Transits the 10th House', description: 'Public-couple chapter under heavy review. The relationship\'s public form earns slow recognition.' },
  { name: 'Saturn Transits the 11th House', description: 'Friend/network discipline. The friendship circle shrinks to the real ones.' },
  { name: 'Saturn Transits the 12th House', description: 'Sade Sati 1st leg. Withdrawal, isolation, foreign distance phases in relationship begin.' },
  { name: 'Rahu Transits the 1st House', description: 'Once-in-18-years identity-shock as a partner. Persona shifts; new ambition for relationship form emerges.' },
  { name: 'Rahu Transits the 2nd House', description: 'Chaotic family-finance/voice dynamics in relationship. Speculative shared-money moves; family-of-origin shifts.' },
  { name: 'Rahu Transits the 3rd House', description: 'Explosive relationship-communication. Viral moments, peer-friend reshuffles, written-relationship-content surges.' },
  { name: 'Rahu Transits the 4th House', description: 'Chaotic home/mother dynamics. Sudden moves, foreign-property-as-couple, mother-shifts.' },
  { name: 'Rahu Transits the 5th House', description: 'Speculative romance/children/creative chaos. Unconventional romantic forms, surprise pregnancies, controversial creative outputs.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat chronic relational rivals; expand into unconventional service-care roles for partner.' },
  { name: 'Rahu Transits the 7th House', description: 'Chaotic partnership dynamics. Foreign partner appears, surprise contract terms with spouse, unconventional spouse-energy. Vet rigorously.' },
  { name: 'Rahu Transits the 8th House', description: 'Sudden in-law/sex/inheritance events. Vipareet activation. Watch obsessive joint-finance research.' },
  { name: 'Rahu Transits the 9th House', description: 'Once-in-18-years foreign-dharma-romance peak. Cross-cultural obsession in relationships intensifies.' },
  { name: 'Rahu Transits the 10th House', description: 'Meteoric public-couple shifts. Sudden formal commitment, abrupt social-status change, relocation as a couple.' },
  { name: 'Rahu Transits the 11th House', description: 'Chaotic friend/network expansion. Unusual social affiliations, foreign-network ties, surprise gainful contacts.' },
  { name: 'Rahu Transits the 12th House', description: 'Foreign relocation, hidden-affair dynamics, sleep-disrupting visions about partner. Watch obsessive pull.' },
  { name: 'Ketu Transits the 1st House', description: 'Identity-as-partner stripping. Persona dissolves; old relational identity feels empty.' },
  { name: 'Ketu Transits the 2nd House', description: 'Emotional detachment from speech/family-money. Family-of-origin recalibrates downward in relevance.' },
  { name: 'Ketu Transits the 3rd House', description: 'Old peer/sibling/friendship ties dissolve. Solo deep work in relationship: write the long letter.' },
  { name: 'Ketu Transits the 4th House', description: 'Detachment from home/mother/real-estate. Selling shared property, downsizing, mother-independence — favored.' },
  { name: 'Ketu Transits the 5th House', description: 'Romance/children/creative collaboration feels hollow. Use for non-monetary relational study.' },
  { name: 'Ketu Transits the 6th House', description: 'Chronic relational enemies disengage; long debts close; service-burdens end.' },
  { name: 'Ketu Transits the 7th House', description: 'Partnership eclipse. Long contracts quietly end; spouse-business-partner dynamic recalibrates. Don\'t cling.' },
  { name: 'Ketu Transits the 8th House', description: 'Deep karmic transformation in shared-resources/sexuality/in-laws. Honor what wants to end.' },
  { name: 'Ketu Transits the 9th House', description: 'Eclipse on the dharma node. Long-distance/cross-cultural relationship recalibrates fundamentally.' },
  { name: 'Ketu Transits the 10th House', description: 'Public-couple visibility flickers. The relationship as social currency dissolves; what remains is internal.' },
  { name: 'Ketu Transits the 11th House', description: 'Friend/network burn-through. Transactional friendships disappear; the real ones remain.' },
  { name: 'Ketu Transits the 12th House', description: 'Quiet foreign/isolation chapter. Spiritual-relationship dimension deepens.' },

  // ANGLE ASPECTS (72)
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Partner attention, ego dynamics, father-figure-style relational cycles. Show up.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Plan your own visibility within the relationship; watch ego friction.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Take the spotlight in the relationship moment; be seen.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Release the ego-charge; let the partner share the stage again.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'The relationship becomes visible to your wider world.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Prepare the joint social-statement; the partner enters your status narrative.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'The relationship enters the public stage; show up together with intention.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Lock in joint-public commitments before momentum settles.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Peak emotional sensitivity in relationship. Read the room with full empathy.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Lead with warmth; the partner reads you generously.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Receive and offer warmth; the relational depth lands without effort.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Carry forward the deepened relational baseline.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'The relationship\'s public face is emotionally read.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Watch how your shared emotional state reads in the social field.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'The shared emotional state becomes visible; show up regulated.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'The steadier shared mood persists; protect it.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury sharpens self-articulation in relationship. Best for: explaining yourself clearly, the personal letter, the introspective talk.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Plan the difficult personal sharing; draft the letter.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Send the letter; have the introspective conversation.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Lock in the verbal commitments; finalize written agreements.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Mercury on the public-couple zenith. Joint statements, shared social-content, couple-communication on display.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Plan the announcement, the public statement together.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Publish, post, announce as a couple.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Lock in the shared public statements.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Magnetism rises; partner sees you with fresh affection.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'The relationship feels easier; lean into it.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Receive love freely; offer warmth without effort.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'The deepened mutual appreciation persists.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Diplomatic, beautiful joint visibility. Best for: shared social events, couple-aesthetics.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Plan the joint event, the photographed gathering.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Host the public couple event; the warmth lands publicly.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Lock in the shared social moves.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Debilitated; energy high but emotionally fragile in relationship.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Action-self window opens with debilitated edge. Push asks gently; avoid emotional escalation.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Take the firm stand with regulated tone.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Action-self window fades; release the heat.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Competitive/assertive joint moves. Watch combative tone in shared public statements.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Prepare the bold joint move.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Take the public-couple stand; defend the relationship publicly if needed.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Public-couple-action window cools. Settle the position; don\'t escalate.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Once-in-12-years personal-relational expansion. Mentors arrive; reputation as a partner grows.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Multi-month relational expansion begins. Plan the major personal-relational growth project.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Mentors notice your relational maturity; the partner sees the elevation.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Lock in the relational maturity gained.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Expansive social/public couple visibility, blessed by mentors.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Plan the major shared public commitment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Take the major shared public step — engagement, marriage, public commitment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Public-couple-expansion closes. Convert into formal binding commitments.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Body, persona, identity-as-partner under structural test. Slow down; build for permanence.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Long structural test of self-as-partner begins. Simplify; eliminate vanity dynamics.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'The reckoning is acute; hold steady; the work matters.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'The mature partner identity remains.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'The relationship\'s public form tested for staying power.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Prepare for slow recognition of the relationship.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'The structural reckoning of the relationship\'s public form.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Public-couple-Saturn closes. The structures built remain.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic identity expansion as partner. Foreign or unconventional self emerges.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Sudden ambition for relationship form surfaces.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Take the unconventional relational move with discipline.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Rahu-self closes. Decide which relational experiments to keep.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic visibility expansion. Sudden formal commitments, foreign-couple dynamics.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Unconventional offers re: relationship may surface.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Take the bold pivot in relationship form, but verify integrity.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Rahu-MC closes. Lock in the legitimate moves.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Identity-as-partner stripping. Old relational persona feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'The pull to step away from the old relational form rises.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Sit with the dissonance; don\'t leap.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Ketu-self closes. What dissolved was meant to.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Visibility eclipse. The relationship-as-social-currency dissolves.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Don\'t over-defend the public form.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'The shared public role dissolves quietly.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Public-couple-eclipse closes. The cleaner private bond underneath emerges.' },

  // OUTER SPECIALS (8)
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting your natal Saturn (Aquarius 8H). The shared-resources/in-law/sexuality structures undergo deep transformation. Joint financial frameworks rewrite; in-law roles shift; the marriage transforms beneath you.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural-relational reckoning begins. Old joint-finance/in-law/intimacy frameworks dismantle. Position for long transformation.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'The old jointly-held structure breaks; the new is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Structural-relational transformation completes. The marriage emerges with rebuilt shared foundation.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting your natal Venus (Libra 4H). Unexpected home/mother shifts; surprise affection-events; abrupt relational reset.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Expect surprise relational moves, abrupt home shifts.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'The unexpected gesture, the shock-encounter, the sudden home shift. Move with discipline.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Integrate the changes; release the unsustainable experiments.' },

  // ASPECTS (324) — 9 transit × 9 natal × 4 phases
  // — Jupiter aspects natal —
  { name: 'Jupiter aspect Sun in 3rd house', description: 'Expansive father-figure-style authority in relationship-communication. Best for: deepening with siblings, mentor-style relating, peer-friend integration.' },
  { name: 'Jupiter aspect Sun in 3rd house : Starts', description: 'Plan the family/peer/sibling deepening project.' },
  { name: 'Jupiter aspect Sun in 3rd house : Exact', description: 'Peak day for authoritative relational communication. The mentor-style move lands.' },
  { name: 'Jupiter aspect Sun in 3rd house : Ends', description: 'Lock in deepened peer/sibling commitments.' },
  { name: 'Jupiter aspect Moon in 2nd house', description: 'Vocal/family-money expansion in relationship. Speak warmly; family wealth grows; partner-as-family deepens.' },
  { name: 'Jupiter aspect Moon in 2nd house : Starts', description: 'Plan the family-wealth or partner-finance deepening.' },
  { name: 'Jupiter aspect Moon in 2nd house : Exact', description: 'The warm family-finance conversation lands; family wealth expands.' },
  { name: 'Jupiter aspect Moon in 2nd house : Ends', description: 'Lock in the family-finance commitments.' },
  { name: 'Jupiter aspect Mercury in 3rd house', description: 'Peak relational-communication wisdom. Letters that change the partnership trajectory.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Starts', description: 'Begin the major relational letter, the deep conversation.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Exact', description: 'Send the major relational letter; the alignment is exceptional.' },
  { name: 'Jupiter aspect Mercury in 3rd house : Ends', description: 'Lock in the relational commitments expressed in writing.' },
  { name: 'Jupiter aspect Venus in 4th house', description: 'Peak home-as-love expansion. Buy the home, deepen with mother, formalize the family foundation.' },
  { name: 'Jupiter aspect Venus in 4th house : Starts', description: 'Plan the major home/family/mother deepening.' },
  { name: 'Jupiter aspect Venus in 4th house : Exact', description: 'Sign the lease together, finalize the family foundation, deepen with mother.' },
  { name: 'Jupiter aspect Venus in 4th house : Ends', description: 'Lock in the family/home decisions.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Major partnership/marriage expansion window. Engagement, marriage, formal lifelong commitment.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Negotiate the engagement, the prenup, the major commitment.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak partnership/marriage day. Get engaged, marry, formalize the lifelong union. Exalted Mars + Jupiter = blessed permanence.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Lock in the binding lifelong terms.' },
  { name: 'Jupiter aspect Jupiter in 6th house', description: 'Service-with-wisdom relationship year. Deep care for partner\'s health/admin; chronic conflicts heal.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Starts', description: 'Take on the partner\'s long-pending health/admin issue.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Exact', description: 'The chronic relational dispute heals; the long-pending care-task closes.' },
  { name: 'Jupiter aspect Jupiter in 6th house : Ends', description: 'Document the resolutions; the deepened care baseline persists.' },
  { name: 'Jupiter aspect Saturn in 8th house', description: 'Wisdom into shared-resources/sexuality/in-law zone. Inheritance, joint-finance, in-law dynamics resolve favorably.' },
  { name: 'Jupiter aspect Saturn in 8th house : Starts', description: 'Begin the inheritance/joint-finance/in-law conversation.' },
  { name: 'Jupiter aspect Saturn in 8th house : Exact', description: 'Peak day for shared-finance/in-law clarity. Inheritance lands fairly; joint-finance harmonizes; in-law shifts settle.' },
  { name: 'Jupiter aspect Saturn in 8th house : Ends', description: 'Lock in the joint-finance/inheritance/in-law settlements.' },
  { name: 'Jupiter aspect Rahu in 9th house', description: 'Own-sign Jupiter on the dharma node. Peak window for cross-cultural/long-distance relationship moves.' },
  { name: 'Jupiter aspect Rahu in 9th house : Starts', description: 'Plan the cross-cultural deepening, the long-distance commitment.' },
  { name: 'Jupiter aspect Rahu in 9th house : Exact', description: 'Take the international relational call; sign the cross-border commitment.' },
  { name: 'Jupiter aspect Rahu in 9th house : Ends', description: 'Lock in the cross-cultural commitments.' },
  { name: 'Jupiter aspect Ketu in 3rd house', description: 'Wisdom on the detached-communication node. Solo relational-writing flourishes; the long love letter finds its voice.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Starts', description: 'Begin the long-form letter to partner.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Exact', description: 'The long letter, the contemplative relational output crystallizes.' },
  { name: 'Jupiter aspect Ketu in 3rd house : Ends', description: 'Send the letter; convert solitary work to public form.' },

  // — Ketu aspects natal —
  { name: 'Ketu aspect Sun in 3rd house', description: 'Relational authority through writing/effort feels hollow. Solo, contemplative output favored over ambition-style.' },
  { name: 'Ketu aspect Sun in 3rd house : Starts', description: 'Authority-eclipse begins on relational communication. Step back from ambition.' },
  { name: 'Ketu aspect Sun in 3rd house : Exact', description: 'The ego-driven relational message falls flat; the dharmic one lands.' },
  { name: 'Ketu aspect Sun in 3rd house : Ends', description: 'Authority-eclipse fades. The cleaner less-ego version of relating remains.' },
  { name: 'Ketu aspect Moon in 2nd house', description: 'Emotional detachment from speech/family-money/voice in relationship. Family-of-origin recalibrates downward.' },
  { name: 'Ketu aspect Moon in 2nd house : Starts', description: 'Voice/family detachment begins. Don\'t panic-renegotiate; observe.' },
  { name: 'Ketu aspect Moon in 2nd house : Exact', description: 'Speech feels distant; family-money feels disconnected. Sit with it.' },
  { name: 'Ketu aspect Moon in 2nd house : Ends', description: 'Voice/family detachment fades. The cleaner relational baseline embedded.' },
  { name: 'Ketu aspect Mercury in 3rd house', description: 'Paradoxical detached-precision in relational communication. Solo depth favored; collaborative chat misfires.' },
  { name: 'Ketu aspect Mercury in 3rd house : Starts', description: 'Pull back from team/peer/friend chatter.' },
  { name: 'Ketu aspect Mercury in 3rd house : Exact', description: 'The solo clarity lands; group-text misfires.' },
  { name: 'Ketu aspect Mercury in 3rd house : Ends', description: 'The solo work integrates back into team/peer flow.' },
  { name: 'Ketu aspect Venus in 4th house', description: 'Detachment from home, mother, real-estate, aesthetic comfort. Selling shared property, downsizing, mother-independence — all favored.' },
  { name: 'Ketu aspect Venus in 4th house : Starts', description: 'Consider what to release from the shared home.' },
  { name: 'Ketu aspect Venus in 4th house : Exact', description: 'The sell-property impulse, the downsize, the let-mother-be-mother — all valid signals.' },
  { name: 'Ketu aspect Venus in 4th house : Ends', description: 'Home-detachment fades. The leaner home-base persists.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Partnership eclipse on the central yogakaraka. The marriage/partnership recalibrates fundamentally.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Don\'t push contracts/commitments; observe what wants to dissolve.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Major partnership feels distant; long contracts may quietly end.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'The remaining partnership is the real one.' },
  { name: 'Ketu aspect Jupiter in 6th house', description: 'Service-detachment. Difficult relational dynamics lose hold; chronic enemies disengage; long care-debts close.' },
  { name: 'Ketu aspect Jupiter in 6th house : Starts', description: 'Service-detachment begins. Energy to serve difficult cases drops.' },
  { name: 'Ketu aspect Jupiter in 6th house : Exact', description: 'The chronic relational enemy disengages; the long care-debt closes.' },
  { name: 'Ketu aspect Jupiter in 6th house : Ends', description: 'Service-detachment closes. The leaner care-portfolio remains.' },
  { name: 'Ketu aspect Saturn in 8th house', description: 'Deep transformation-detachment in shared-resources/sexuality/in-laws. Don\'t resist; the surfacing is purifying.' },
  { name: 'Ketu aspect Saturn in 8th house : Starts', description: 'Transformation-detachment begins. Slow surfacing of hidden truths in shared-zone.' },
  { name: 'Ketu aspect Saturn in 8th house : Exact', description: 'The buried in-law truth surfaces; the long-pending settlement clarifies.' },
  { name: 'Ketu aspect Saturn in 8th house : Ends', description: 'Transformation-detachment closes. What surfaced has integrated.' },
  { name: 'Ketu aspect Rahu in 9th house', description: 'Axis activation. Foreign/dharma direction in relationship recalibrates.' },
  { name: 'Ketu aspect Rahu in 9th house : Starts', description: 'Nodal-axis window begins in relating. Foreign/dharma path in relationship under review.' },
  { name: 'Ketu aspect Rahu in 9th house : Exact', description: 'Peak axis day. The foreign/spiritual relational dynamic recalibrates sharply.' },
  { name: 'Ketu aspect Rahu in 9th house : Ends', description: 'Nodal-axis closes. Clearer relational dharma path emerges.' },
  { name: 'Ketu aspect Ketu in 3rd house', description: 'Once-in-18-years detachment-on-detachment. Old peer/friend/sibling ties dissolve; solo deepens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Starts', description: 'Ketu-return begins. The 18-year peer-friend chapter completes.' },
  { name: 'Ketu aspect Ketu in 3rd house : Exact', description: 'Old peer dynamics dissolve; new arc opens.' },
  { name: 'Ketu aspect Ketu in 3rd house : Ends', description: 'Ketu-return closes. New peer/sibling baseline.' },

  // — Mars aspects natal —
  { name: 'Mars aspect Sun in 3rd house', description: 'Fierce relational-communication drive. Defend the relationship in writing; argue with precision.' },
  { name: 'Mars aspect Sun in 3rd house : Starts', description: 'Prepare for high-energy relational exchanges.' },
  { name: 'Mars aspect Sun in 3rd house : Exact', description: 'Defend the relational position with calm fire. Watch temper.' },
  { name: 'Mars aspect Sun in 3rd house : Ends', description: 'Lock in the position; release heat.' },
  { name: 'Mars aspect Moon in 2nd house', description: 'Heated speech, family-money flares in relationship. Watch sharp words at the dinner table.' },
  { name: 'Mars aspect Moon in 2nd house : Starts', description: 'Voice/family heat rising. Bring data not emotion.' },
  { name: 'Mars aspect Moon in 2nd house : Exact', description: 'Address the family-money issue with calm fire.' },
  { name: 'Mars aspect Moon in 2nd house : Ends', description: 'Voice/family heat fades. Convert into written agreement.' },
  { name: 'Mars aspect Mercury in 3rd house', description: 'Sharp execution mind in relational comms. Best for: hard-won difficult conversations.' },
  { name: 'Mars aspect Mercury in 3rd house : Starts', description: 'Sharp-mind window opens in relating. Prepare the difficult conversation.' },
  { name: 'Mars aspect Mercury in 3rd house : Exact', description: 'Send the precise cutting note; have the hard conversation.' },
  { name: 'Mars aspect Mercury in 3rd house : Ends', description: 'Let go of the heated debate.' },
  { name: 'Mars aspect Venus in 4th house', description: 'Heated home/family/real-estate dynamics. Decisive moves favored; family arguments flare.' },
  { name: 'Mars aspect Venus in 4th house : Starts', description: 'Plan decisive home conversation.' },
  { name: 'Mars aspect Venus in 4th house : Exact', description: 'The home-action moment: sign, sell, move, confront.' },
  { name: 'Mars aspect Venus in 4th house : Ends', description: 'Home-heat closes. The decision is made.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Peak partnership-action window of any 2-year cycle. Major commitment, major decision, major contract with partner.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Mars-return on yogakaraka begins. Prepare the major partnership move.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Sign the major commitment, formalize the union.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Mars-return closes. Lock in lifelong commitments; next window 2 years out.' },
  { name: 'Mars aspect Jupiter in 6th house', description: 'Fierce service-care combat. Win the long-pending logistical/health battle for partner.' },
  { name: 'Mars aspect Jupiter in 6th house : Starts', description: 'Prepare to fight the relational logistic dispute on principle.' },
  { name: 'Mars aspect Jupiter in 6th house : Exact', description: 'Win the relational rivalry, settle the care-debt.' },
  { name: 'Mars aspect Jupiter in 6th house : Ends', description: 'Service-combat closes. Document the win.' },
  { name: 'Mars aspect Saturn in 8th house', description: 'Surgical action in shared-resources/sexuality/in-laws. Address the long-deferred joint-finance issue.' },
  { name: 'Mars aspect Saturn in 8th house : Starts', description: 'Prepare the surgical decision.' },
  { name: 'Mars aspect Saturn in 8th house : Exact', description: 'Take the joint-finance/in-law action; lead through the chaos.' },
  { name: 'Mars aspect Saturn in 8th house : Ends', description: 'Lock in the structural changes.' },
  { name: 'Mars aspect Rahu in 9th house', description: 'Assertive cross-cultural/long-distance moves. Take the principled stand on the dharma-difference.' },
  { name: 'Mars aspect Rahu in 9th house : Starts', description: 'Prepare the cross-cultural fight, the principle-stand.' },
  { name: 'Mars aspect Rahu in 9th house : Exact', description: 'Push the foreign/principled position in relationship.' },
  { name: 'Mars aspect Rahu in 9th house : Ends', description: 'Lock in principled wins.' },
  { name: 'Mars aspect Ketu in 3rd house', description: 'Sharp solo execution in relating; team/peer dynamics misfire. Solo letter, individual move.' },
  { name: 'Mars aspect Ketu in 3rd house : Starts', description: 'Solo-action window opens in relating. Step back from peer-friend coordination.' },
  { name: 'Mars aspect Ketu in 3rd house : Exact', description: 'Solo relational breakthrough lands; group-channel work falls flat.' },
  { name: 'Mars aspect Ketu in 3rd house : Ends', description: 'Bring solo back into peer rhythm.' },

  // — Mercury aspects natal —
  { name: 'Mercury aspect Sun in 3rd house', description: 'Annual return-style activation of editorial-authority cluster in relating. Best for: the well-structured relational presentation.' },
  { name: 'Mercury aspect Sun in 3rd house : Starts', description: 'Editorial-authority window opens in relating. Prepare the structured letter, the analytical relational memo.' },
  { name: 'Mercury aspect Sun in 3rd house : Exact', description: 'Send the structured relational document.' },
  { name: 'Mercury aspect Sun in 3rd house : Ends', description: 'Lock in the formal relational position.' },
  { name: 'Mercury aspect Moon in 2nd house', description: 'Articulate emotional speech around speech/family-money/voice in relating. The compensation-of-love conversation.' },
  { name: 'Mercury aspect Moon in 2nd house : Starts', description: 'Plan the family-finance discussion.' },
  { name: 'Mercury aspect Moon in 2nd house : Exact', description: 'Speak from the heart with precision in family-finance/voice.' },
  { name: 'Mercury aspect Moon in 2nd house : Ends', description: 'Voice-articulation closes. Convert spoken into written.' },
  { name: 'Mercury aspect Mercury in 3rd house', description: 'Annual peak for relational technical-writing, peer-leadership, hands-on relational execution.' },
  { name: 'Mercury aspect Mercury in 3rd house : Starts', description: 'Begin the major relational analytical/written project.' },
  { name: 'Mercury aspect Mercury in 3rd house : Exact', description: 'Ship the relational document; debug the relational logic.' },
  { name: 'Mercury aspect Mercury in 3rd house : Ends', description: 'Lock in the technical commitments in the relationship.' },
  { name: 'Mercury aspect Venus in 4th house', description: 'Diplomatic communication around home/family/real-estate. Best for: family-business negotiations, mother-correspondence.' },
  { name: 'Mercury aspect Venus in 4th house : Starts', description: 'Plan family/mother/real-estate calls.' },
  { name: 'Mercury aspect Venus in 4th house : Exact', description: 'Send the diplomatic family note.' },
  { name: 'Mercury aspect Venus in 4th house : Ends', description: 'Home-communication closes. Lock in family/real-estate paper trail.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Precise contractual communication with partner. Best for: drafting prenup-style understandings.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Prepare the relationship-terms draft.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Send the term-sheet to partner.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Contract-communication closes. Lock in binding written commitments.' },
  { name: 'Mercury aspect Jupiter in 6th house', description: 'Service-and-wisdom communication. Best for: scheduling logistics, health-coordination, conflict-resolution-letters with partner.' },
  { name: 'Mercury aspect Jupiter in 6th house : Starts', description: 'Service-communication window opens.' },
  { name: 'Mercury aspect Jupiter in 6th house : Exact', description: 'The wise written communication that resolves chronic dispute lands.' },
  { name: 'Mercury aspect Jupiter in 6th house : Ends', description: 'Service-communication closes. Document resolutions.' },
  { name: 'Mercury aspect Saturn in 8th house', description: 'Investigative depth-writing in shared-resources/sexuality/in-laws. Forensic clarity on long-pending issues.' },
  { name: 'Mercury aspect Saturn in 8th house : Starts', description: 'Begin the investigative analysis of joint finance/in-law dynamic.' },
  { name: 'Mercury aspect Saturn in 8th house : Exact', description: 'The forensic relational insight lands.' },
  { name: 'Mercury aspect Saturn in 8th house : Ends', description: 'Depth-writing closes. File the investigative work.' },
  { name: 'Mercury aspect Rahu in 9th house', description: 'Unconventional/foreign relational communication. Best for: international correspondence, philosophical position-letters.' },
  { name: 'Mercury aspect Rahu in 9th house : Starts', description: 'Begin the international relational letter.' },
  { name: 'Mercury aspect Rahu in 9th house : Exact', description: 'Send the cross-cultural note.' },
  { name: 'Mercury aspect Rahu in 9th house : Ends', description: 'Foreign-vision closes. Lock in cross-border commitments.' },
  { name: 'Mercury aspect Ketu in 3rd house', description: 'Paradoxical mind-on-detachment in relational cluster. Solo precision favored; group-text misfires.' },
  { name: 'Mercury aspect Ketu in 3rd house : Starts', description: 'Detached-precision window opens.' },
  { name: 'Mercury aspect Ketu in 3rd house : Exact', description: 'The solo letter lands; group-text misfires.' },
  { name: 'Mercury aspect Ketu in 3rd house : Ends', description: 'Detached-precision closes.' },

  // — Moon aspects natal —
  { name: 'Moon aspect Sun in 3rd house', description: 'Feelings drive relational communication. Best for warm-toned messages.' },
  { name: 'Moon aspect Sun in 3rd house : Starts', description: 'Feelings-on-authority window opens.' },
  { name: 'Moon aspect Sun in 3rd house : Exact', description: 'Send the emotionally honest letter.' },
  { name: 'Moon aspect Sun in 3rd house : Ends', description: 'Feelings-on-authority closes. Warmer baseline persists.' },
  { name: 'Moon aspect Moon in 2nd house', description: 'Annual emotional-vocal-family-finance peak. The voice is warm; family-money flows.' },
  { name: 'Moon aspect Moon in 2nd house : Starts', description: 'Voice-finance emotional window opens.' },
  { name: 'Moon aspect Moon in 2nd house : Exact', description: 'Speak warmly; address family-money with heart.' },
  { name: 'Moon aspect Moon in 2nd house : Ends', description: 'Vocal-financial baseline shifted.' },
  { name: 'Moon aspect Mercury in 3rd house', description: 'Warm-toned writing/peer-communication. Excellent for the message that needs to land softly.' },
  { name: 'Moon aspect Mercury in 3rd house : Starts', description: 'Warm-tone window opens.' },
  { name: 'Moon aspect Mercury in 3rd house : Exact', description: 'Send the warm message.' },
  { name: 'Moon aspect Mercury in 3rd house : Ends', description: 'Warm-tone closes.' },
  { name: 'Moon aspect Venus in 4th house', description: 'Peak home/family/mother emotional zone. Host gathering, mother-call, real-estate intuition.' },
  { name: 'Moon aspect Venus in 4th house : Starts', description: 'Home-emotional window opens.' },
  { name: 'Moon aspect Venus in 4th house : Exact', description: 'Host the family; deepen with mother.' },
  { name: 'Moon aspect Venus in 4th house : Ends', description: 'Home-emotional closes. Foundation deepened.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge on partnership. Read partner\'s mood before pushing.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Partnership-emotion window opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Soften the partner conversation.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Partnership-emotion closes.' },
  { name: 'Moon aspect Jupiter in 6th house', description: 'Emotional warmth in service zone. Care for partner with empathy.' },
  { name: 'Moon aspect Jupiter in 6th house : Starts', description: 'Service-empathy window opens.' },
  { name: 'Moon aspect Jupiter in 6th house : Exact', description: 'Resolve chronic care-conflict warmly.' },
  { name: 'Moon aspect Jupiter in 6th house : Ends', description: 'Service-empathy closes.' },
  { name: 'Moon aspect Saturn in 8th house', description: 'Emotional weight in shared-resources zone. Defer hard joint-finance decisions.' },
  { name: 'Moon aspect Saturn in 8th house : Starts', description: 'Shared-zone emotion window opens.' },
  { name: 'Moon aspect Saturn in 8th house : Exact', description: 'Sleep more; decide less in shared zone.' },
  { name: 'Moon aspect Saturn in 8th house : Ends', description: 'Shared-zone emotion closes.' },
  { name: 'Moon aspect Rahu in 9th house', description: 'Emotional pull toward foreign/dharma/long-distance dynamics. Big-vision dream-talk OK.' },
  { name: 'Moon aspect Rahu in 9th house : Starts', description: 'Foreign-vision emotional window opens.' },
  { name: 'Moon aspect Rahu in 9th house : Exact', description: 'International/dharma pull peaks.' },
  { name: 'Moon aspect Rahu in 9th house : Ends', description: 'Foreign-vision closes.' },
  { name: 'Moon aspect Ketu in 3rd house', description: 'Emotional detachment in cluster. Solo writing flourishes; group-chat feels hollow.' },
  { name: 'Moon aspect Ketu in 3rd house : Starts', description: 'Solo-emotion window opens.' },
  { name: 'Moon aspect Ketu in 3rd house : Exact', description: 'Solo deep-work emotional satisfaction.' },
  { name: 'Moon aspect Ketu in 3rd house : Ends', description: 'Solo-emotion closes.' },

  // — Saturn aspects natal —
  { name: 'Saturn aspect Sun in 3rd house', description: 'Structural test of relational-authority through writing/effort/peers. Slow recognition; demanding mentor.' },
  { name: 'Saturn aspect Sun in 3rd house : Starts', description: 'Authority-discipline window opens in relating.' },
  { name: 'Saturn aspect Sun in 3rd house : Exact', description: 'Hold steady; ship the disciplined relational output.' },
  { name: 'Saturn aspect Sun in 3rd house : Ends', description: 'Authority-discipline closes. Elevated authority is now baseline.' },
  { name: 'Saturn aspect Moon in 2nd house', description: 'Structural test of voice/family-finance in relating. Speak less, write more.' },
  { name: 'Saturn aspect Moon in 2nd house : Starts', description: 'Voice/family-finance discipline opens.' },
  { name: 'Saturn aspect Moon in 2nd house : Exact', description: 'Family-money reckoning is acute; patience compounds.' },
  { name: 'Saturn aspect Moon in 2nd house : Ends', description: 'Voice/family discipline closes. Steadier income remains.' },
  { name: 'Saturn aspect Mercury in 3rd house', description: 'Long-form relational-communication chapter. The years-in-the-making relational opus.' },
  { name: 'Saturn aspect Mercury in 3rd house : Starts', description: 'Structural-communication window opens.' },
  { name: 'Saturn aspect Mercury in 3rd house : Exact', description: 'Ship the long-form relational document.' },
  { name: 'Saturn aspect Mercury in 3rd house : Ends', description: 'Structural-communication closes. Opus complete.' },
  { name: 'Saturn aspect Venus in 4th house', description: 'Structural test of home/family/real-estate. Buy carefully; hold patiently.' },
  { name: 'Saturn aspect Venus in 4th house : Starts', description: 'Home-discipline window opens.' },
  { name: 'Saturn aspect Venus in 4th house : Exact', description: 'The home-foundation reckoning.' },
  { name: 'Saturn aspect Venus in 4th house : Ends', description: 'Home-discipline closes. Sound foundation remains.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Heavy partnership chapter. Marriage tested for staying power. What survives lasts decades.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Partnership-discipline window opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'The reckoning of which relational commitments are real.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Partnership-discipline closes. Durable bonds remain.' },
  { name: 'Saturn aspect Jupiter in 6th house', description: 'Favorable. Long care-disputes won through patience; chronic conflicts heal slowly.' },
  { name: 'Saturn aspect Jupiter in 6th house : Starts', description: 'Service-discipline window opens.' },
  { name: 'Saturn aspect Jupiter in 6th house : Exact', description: 'The years-old care-battle resolves.' },
  { name: 'Saturn aspect Jupiter in 6th house : Ends', description: 'Service-discipline closes.' },
  { name: 'Saturn aspect Saturn in 8th house', description: 'Once-in-29-years deep transformation in shared-resources/sexuality/in-laws. Reckoning is total.' },
  { name: 'Saturn aspect Saturn in 8th house : Starts', description: '29-year shared-zone chapter completes.' },
  { name: 'Saturn aspect Saturn in 8th house : Exact', description: 'Half-life reckoning of shared-resources/intimacy/in-laws.' },
  { name: 'Saturn aspect Saturn in 8th house : Ends', description: 'New 29-year arc.' },
  { name: 'Saturn aspect Rahu in 9th house', description: 'Pressure on foreign-dharma node in relating. Cross-cultural relationship demands compliance/patience.' },
  { name: 'Saturn aspect Rahu in 9th house : Starts', description: 'Foreign-discipline window opens.' },
  { name: 'Saturn aspect Rahu in 9th house : Exact', description: 'Dharma path reckoning in relating.' },
  { name: 'Saturn aspect Rahu in 9th house : Ends', description: 'Foreign-discipline closes.' },
  { name: 'Saturn aspect Ketu in 3rd house', description: 'Discipline-on-detachment in cluster. Solo deep work in relating compounds.' },
  { name: 'Saturn aspect Ketu in 3rd house : Starts', description: 'Solo-discipline window opens.' },
  { name: 'Saturn aspect Ketu in 3rd house : Exact', description: 'Solo opus reaches disciplined apex.' },
  { name: 'Saturn aspect Ketu in 3rd house : Ends', description: 'Solo-discipline closes.' },

  // — Sun aspects natal —
  { name: 'Sun aspect Sun in 3rd house', description: 'Annual peak for authoritative effort/writing/relating. Lead the difficult relational conversation; demand the recognition for the relational work shipped.' },
  { name: 'Sun aspect Sun in 3rd house : Starts', description: 'Solar-return window opens on cluster.' },
  { name: 'Sun aspect Sun in 3rd house : Exact', description: 'Ship; present; claim authorship in relating.' },
  { name: 'Sun aspect Sun in 3rd house : Ends', description: 'Solar-return closes. Lock in the relational position.' },
  { name: 'Sun aspect Moon in 2nd house', description: 'Authoritative voice/family-finance window. Step into family-money leadership; speak with full authority.' },
  { name: 'Sun aspect Moon in 2nd house : Starts', description: 'Authoritative-voice window opens.' },
  { name: 'Sun aspect Moon in 2nd house : Exact', description: 'Speak with authority; family-money leadership crystallizes.' },
  { name: 'Sun aspect Moon in 2nd house : Ends', description: 'Authoritative-voice closes.' },
  { name: 'Sun aspect Mercury in 3rd house', description: 'Annual visibility on the technical-writer mind in relating. Take authorship of the relational platform.' },
  { name: 'Sun aspect Mercury in 3rd house : Starts', description: 'Technical-authority window opens in relating.' },
  { name: 'Sun aspect Mercury in 3rd house : Exact', description: 'Take authorship of the relational form.' },
  { name: 'Sun aspect Mercury in 3rd house : Ends', description: 'Technical-authority closes.' },
  { name: 'Sun aspect Venus in 4th house', description: 'Annual visibility through home/family/aesthetic. Family-business leadership move; mother-attention.' },
  { name: 'Sun aspect Venus in 4th house : Starts', description: 'Home-authority window opens.' },
  { name: 'Sun aspect Venus in 4th house : Exact', description: 'Step into family-business leadership.' },
  { name: 'Sun aspect Venus in 4th house : Ends', description: 'Home-authority closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Annual peak for partnership-led authority. Major commitment, formal coupling with public visibility.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Partnership-authority window opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Sign the major commitment publicly.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Partnership-authority closes.' },
  { name: 'Sun aspect Jupiter in 6th house', description: 'Service-authority peak. Step into the difficult-care lead for partner.' },
  { name: 'Sun aspect Jupiter in 6th house : Starts', description: 'Service-authority window opens.' },
  { name: 'Sun aspect Jupiter in 6th house : Exact', description: 'Take the expert-care lead for the relationship.' },
  { name: 'Sun aspect Jupiter in 6th house : Ends', description: 'Service-authority closes.' },
  { name: 'Sun aspect Saturn in 8th house', description: 'Authoritative leadership through shared-resources/sexuality/in-laws. Visible through joint-finance leadership.' },
  { name: 'Sun aspect Saturn in 8th house : Starts', description: 'Shared-zone leadership window opens.' },
  { name: 'Sun aspect Saturn in 8th house : Exact', description: 'Lead through shared-resources crisis.' },
  { name: 'Sun aspect Saturn in 8th house : Ends', description: 'Shared-zone leadership closes.' },
  { name: 'Sun aspect Rahu in 9th house', description: 'Visibility through foreign/dharma channels in relating. Cross-cultural commitment moves.' },
  { name: 'Sun aspect Rahu in 9th house : Starts', description: 'Foreign-authority window opens.' },
  { name: 'Sun aspect Rahu in 9th house : Exact', description: 'Take the international relational stage.' },
  { name: 'Sun aspect Rahu in 9th house : Ends', description: 'Foreign-authority closes.' },
  { name: 'Sun aspect Ketu in 3rd house', description: 'Paradoxical authority-on-detachment. Solo authoritative relating shines; group-channel feels off.' },
  { name: 'Sun aspect Ketu in 3rd house : Starts', description: 'Solo-authority window opens in relating.' },
  { name: 'Sun aspect Ketu in 3rd house : Exact', description: 'Solo relational authority lands.' },
  { name: 'Sun aspect Ketu in 3rd house : Ends', description: 'Solo-authority closes.' },

  // — Venus aspects natal —
  { name: 'Venus aspect Sun in 3rd house', description: 'Graceful authoritative relational-communication. Charm the partner with the well-written letter.' },
  { name: 'Venus aspect Sun in 3rd house : Starts', description: 'Graceful-authority window opens.' },
  { name: 'Venus aspect Sun in 3rd house : Exact', description: 'Charm with substance.' },
  { name: 'Venus aspect Sun in 3rd house : Ends', description: 'Graceful-authority closes.' },
  { name: 'Venus aspect Moon in 2nd house', description: 'Luxurious income/voice/family-finance window. Speak warmly; family-money harmonizes.' },
  { name: 'Venus aspect Moon in 2nd house : Starts', description: 'Income-luxury window opens.' },
  { name: 'Venus aspect Moon in 2nd house : Exact', description: 'Warm authority; family-money flows.' },
  { name: 'Venus aspect Moon in 2nd house : Ends', description: 'Income-luxury closes.' },
  { name: 'Venus aspect Mercury in 3rd house', description: 'Graceful technical/peer-communication. Beautiful relational presentations.' },
  { name: 'Venus aspect Mercury in 3rd house : Starts', description: 'Graceful-mind window opens.' },
  { name: 'Venus aspect Mercury in 3rd house : Exact', description: 'The beautiful precision lands.' },
  { name: 'Venus aspect Mercury in 3rd house : Ends', description: 'Graceful-mind closes.' },
  { name: 'Venus aspect Venus in 4th house', description: 'Annual peak for home-as-love. Beautify; host; deepen with mother.' },
  { name: 'Venus aspect Venus in 4th house : Starts', description: 'Venus return opens.' },
  { name: 'Venus aspect Venus in 4th house : Exact', description: 'The home foundation crystallizes.' },
  { name: 'Venus aspect Venus in 4th house : Ends', description: 'Standard persists.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Partnership-of-warmth-and-rigor. Sign the commitment with both heart and structure.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Partnership-warmth window opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Sign the commitment; warmth and rigor unite.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Partnership-warmth closes.' },
  { name: 'Venus aspect Jupiter in 6th house', description: 'Diplomatic service excellence. Conflict-resolution lands; difficult dynamic softens.' },
  { name: 'Venus aspect Jupiter in 6th house : Starts', description: 'Service-diplomacy window opens.' },
  { name: 'Venus aspect Jupiter in 6th house : Exact', description: 'Resolve the conflict with grace.' },
  { name: 'Venus aspect Jupiter in 6th house : Ends', description: 'Service-diplomacy closes.' },
  { name: 'Venus aspect Saturn in 8th house', description: 'Diplomatic transformation of shared-resources. Negotiate fair joint-finance with grace.' },
  { name: 'Venus aspect Saturn in 8th house : Starts', description: 'Transformation-diplomacy window opens.' },
  { name: 'Venus aspect Saturn in 8th house : Exact', description: 'Negotiate the joint-finance/in-law shift with diplomacy.' },
  { name: 'Venus aspect Saturn in 8th house : Ends', description: 'Transformation-diplomacy closes.' },
  { name: 'Venus aspect Rahu in 9th house', description: 'Graceful foreign/long-distance engagement. International romance, cross-cultural diplomacy.' },
  { name: 'Venus aspect Rahu in 9th house : Starts', description: 'Foreign-diplomacy window opens.' },
  { name: 'Venus aspect Rahu in 9th house : Exact', description: 'Take the cross-cultural call with warmth.' },
  { name: 'Venus aspect Rahu in 9th house : Ends', description: 'Foreign-diplomacy closes.' },
  { name: 'Venus aspect Ketu in 3rd house', description: 'Graceful detachment in cluster. Solo aesthetic relational work flourishes.' },
  { name: 'Venus aspect Ketu in 3rd house : Starts', description: 'Solo-aesthetic window opens.' },
  { name: 'Venus aspect Ketu in 3rd house : Exact', description: 'The solo love letter crystallizes.' },
  { name: 'Venus aspect Ketu in 3rd house : Ends', description: 'Solo-aesthetic closes.' },

  // — Rahu aspects natal —
  { name: 'Rahu aspect Sun in 3rd house', description: 'Chaotic relational-authority. Viral relational moments, sudden friend-shifts. Watch over-claiming.' },
  { name: 'Rahu aspect Sun in 3rd house : Starts', description: 'Chaotic-authority window opens.' },
  { name: 'Rahu aspect Sun in 3rd house : Exact', description: 'Move with discipline; don\'t over-leverage relational visibility.' },
  { name: 'Rahu aspect Sun in 3rd house : Ends', description: 'Chaotic-authority closes.' },
  { name: 'Rahu aspect Moon in 2nd house', description: 'Chaotic family-finance/voice. Speculative shared-money moves; family-of-origin reshuffles.' },
  { name: 'Rahu aspect Moon in 2nd house : Starts', description: 'Chaotic-finance window opens.' },
  { name: 'Rahu aspect Moon in 2nd house : Exact', description: 'Don\'t leverage on sudden family-money.' },
  { name: 'Rahu aspect Moon in 2nd house : Ends', description: 'Chaotic-finance closes.' },
  { name: 'Rahu aspect Mercury in 3rd house', description: 'Explosive relational-communication breakthrough. Foreign-friend collaborations, unconventional letters.' },
  { name: 'Rahu aspect Mercury in 3rd house : Starts', description: 'Breakthrough-mind window opens.' },
  { name: 'Rahu aspect Mercury in 3rd house : Exact', description: 'Ship the boundary-breaking relational message.' },
  { name: 'Rahu aspect Mercury in 3rd house : Ends', description: 'Breakthrough-mind closes.' },
  { name: 'Rahu aspect Venus in 4th house', description: 'Chaotic home/family/real-estate. Sudden moves, foreign-property dynamics.' },
  { name: 'Rahu aspect Venus in 4th house : Starts', description: 'Home-chaos window opens.' },
  { name: 'Rahu aspect Venus in 4th house : Exact', description: 'Move with discipline through the home shift.' },
  { name: 'Rahu aspect Venus in 4th house : Ends', description: 'Home-chaos closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic partnership dynamics. Foreign partner appears, surprise commitment terms. Vet rigorously.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Chaotic-partnership window opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Verify before committing.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Chaotic-partnership closes.' },
  { name: 'Rahu aspect Jupiter in 6th house', description: 'Favorable. Defeat chronic relational rivals; expand into unconventional service-care roles.' },
  { name: 'Rahu aspect Jupiter in 6th house : Starts', description: 'Unconventional-service window opens.' },
  { name: 'Rahu aspect Jupiter in 6th house : Exact', description: 'Win unconventional care-victory.' },
  { name: 'Rahu aspect Jupiter in 6th house : Ends', description: 'Unconventional-service closes.' },
  { name: 'Rahu aspect Saturn in 8th house', description: 'Sudden in-law/sex/inheritance events. Vipareet activation.' },
  { name: 'Rahu aspect Saturn in 8th house : Starts', description: 'Sudden-transformation window opens.' },
  { name: 'Rahu aspect Saturn in 8th house : Exact', description: 'The sudden shared-zone event lands.' },
  { name: 'Rahu aspect Saturn in 8th house : Ends', description: 'Sudden-transformation closes.' },
  { name: 'Rahu aspect Rahu in 9th house', description: 'Once-in-18-years foreign-dharma-romance peak. Cross-cultural obsession in relating.' },
  { name: 'Rahu aspect Rahu in 9th house : Starts', description: 'Rahu return opens.' },
  { name: 'Rahu aspect Rahu in 9th house : Exact', description: 'New foreign-dharma obsession arrives.' },
  { name: 'Rahu aspect Rahu in 9th house : Ends', description: 'New 18-year arc.' },
  { name: 'Rahu aspect Ketu in 3rd house', description: 'Axis activation. Foreign-vision pulls against solo-detachment.' },
  { name: 'Rahu aspect Ketu in 3rd house : Starts', description: 'Nodal-axis window begins.' },
  { name: 'Rahu aspect Ketu in 3rd house : Exact', description: 'Clearer dharma direction in relating emerges.' },
  { name: 'Rahu aspect Ketu in 3rd house : Ends', description: 'Nodal-axis closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} relationship] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
