// db/seed_food_taurus.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to a
// representative Taurus ascendant native with:
//   Ascendant: Taurus
//   Natal placements (sidereal Lahiri):
//     Sun=4th (Leo, own)  Moon=3rd (Cancer, own)  Mercury=5th (Virgo, own+exalted)
//     Venus=1st (Taurus, own — Malavya Yoga)  Mars=7th (Scorpio, own — Ruchaka Yoga)
//     Jupiter=11th (Pisces, own)  Saturn=10th (Aquarius, own — Sasa Yoga, yogakaraka)
//     Rahu=8th (Sagittarius)  Ketu=2nd (Gemini)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose food-specific interpretations, then run:
//
//   node db/seed_food_taurus.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./food');

const ASCENDANT = 'Taurus';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Venus ruler of the 1st House in the 1st House', description: 'Your constitution is Kapha-rich. Body holds reserves easily; weight settles in the hips, chest, lower belly; skin glows when nourished and dulls when neglected. Sweet tooth runs deep; dairy and refined-grain pleasure can quietly thicken the body. The diet that suits you is warm, lightly spiced, slightly bitter and astringent: bitter greens, ginger, turmeric, black pepper, mustard, basmati rice, lentil dal, small amounts of ghee, cooked fruit. Avoid cold dairy, ice cream, heavy desserts, oily fried, late-night feasting. Move daily; the body holds without movement.' },
  { name: 'Mercury ruler of the 2nd House in the 5th House', description: 'Speech, family-finance, and food intersect in a creative-analytic key. You think clearly about food when you treat the diet as a curated project — meal plans, journals, recipe rotations. Earn through food-content, recipe-writing, food-photography, beverage-craft if it ever appeals. The shadow: over-thinking food into a performance — the body wants the simple bowl more than the styled plate.' },
  { name: 'Moon ruler of the 3rd House in the 3rd House', description: 'Emotion goes through small-burst eating. Stress shows up as snacking, courage shows up as appetite-clarity. Build a clean snack system; pre-prep simple bites; the urge will be honored without breaking the body. Sibling-channel meals (siblings, cousins, peer-friends) carry comfort-charge — eat with them often.' },
  { name: 'Sun ruler of the 4th House in the 4th House', description: 'Home-kitchen is the throne. Mother\'s recipes, traditional family dishes, the dining table you grew up at — all medicinal. The home cookpot beats every restaurant. Build a kitchen that feels royal: good cookware, ample light, ceremonial-quality plates. Best foods: warm cooked rice, ghee in moderation, dal, vegetables, seasonal traditional dishes. Eat the largest meal at midday at home.' },
  { name: 'Mercury ruler of the 5th House in the 5th House', description: 'Mercury exalted on the digestive-creative engine. The mind reads the body precisely when given the chance — keep a food journal for two weeks and the system will tell you exactly what irritates and what nourishes. Best foods: lightly cooked greens, basmati, lentils, fresh fruit, ginger, fennel, coriander. Avoid: heavy creams, refined sugar, fried, late-night.' },
  { name: 'Venus ruler of the 6th House in the 1st House', description: 'Daily friction with food shows on the body — the skin, the gut, the joints register every misstep. The body is a precise instrument of feedback. Use it: when the skin breaks out, when sleep gets disturbed, when joints stiffen, audit the last three days of eating and find the trigger. The shadow: comfort-eating that masks the conflict instead of resolving it.' },
  { name: 'Mars ruler of the 7th House in the 7th House', description: 'Partner-and-counterparty meals carry weight. Shared restaurant decisions, joint-cooking projects, partner\'s family-cuisine adoption all influence your body. The partner\'s food-mood often colors yours; the kitchen you share is the most influential nutrition factor of the long marriage. The shadow: outsourcing the food agenda to the partner — keep your own diet-plumb-line.' },
  { name: 'Jupiter ruler of the 8th House in the 11th House', description: 'Sudden food-shifts (allergies, intolerances, deep dietary epiphanies) arrive through the wide-network and friend-circle. The community-cleanse, the friend-led elimination diet, the international-cuisine immersion that resets the gut. Inheritance of food-traditions through extended family. The shadow: trend-diet pressure from the network — verify each protocol against your body\'s actual response.' },
  { name: 'Saturn ruler of the 9th House in the 10th House', description: 'Diet must align with dharma. Sattvic, traditional, ceremonial food works best long-arc. Saturn-Aquarian discipline favors a fixed, simple, repeatable food system — same meals at same times for years compound into excellent health.' },
  { name: 'Saturn ruler of the 10th House in the 10th House', description: 'Structural eating-rhythm is the long-game medicine. Build a fixed meal-schedule and the metabolism compounds. Joints, bones, knees need warm, oily, well-spiced food in middle age. Bone broth, sesame, ghee, ginger, turmeric — long-game nourishment. Avoid raw cold salads as the primary diet; favor soups, stews, well-cooked vegetables.' },
  { name: 'Jupiter ruler of the 11th House in the 11th House', description: 'Generous appetite. You can eat large portions of rich, traditional food and feel blessed by it — but the body remembers. Weight gain is gradual and structural rather than rapid. Group-meals, ceremonial-feasts, sattvic banquets favor you in moderation. Best practice: largest meal at midday; lighter dinner; no late food. Foreign-cuisine fascination compounds; international travel-eating is medicinal.' },
  { name: 'Mars ruler of the 12th House in the 7th House', description: 'Foreign or hidden food-exposures shape the gut. Travel-eating, retreat-meals, hospital diets, hotel breakfasts shift the system. The shadow: indulgent shared-eating during travel that thickens the body silently — schedule a clean-eating reset day weekly.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 4th (Dispositor)', description: 'When this engine fires, the home kitchen is the answer. Mother\'s recipes restore; family-table meals are medicinal; the cooking pot itself heals.' },
  { name: 'Moon in 3rd (Dispositor)', description: 'When this engine fires, snack-discipline matters. Pre-prep clean small bites; the small-burst hunger will arrive — meet it cleanly. Sibling-channel meals comfort.' },
  { name: 'Mercury in 5th (Dispositor)', description: 'When this engine fires, run a precision food-audit. Track three meals a day for two weeks; the body will tell you exactly what irritates. Eliminate the obvious — alcohol, refined sugar, fried, late-night — and reintroduce one at a time.' },
  { name: 'Venus in 1st (Dispositor)', description: 'When this engine fires, the body wants beauty in food — well-presented, fragrant, sensual eating. Slow meals, candlelit dinners, well-curated plates. The shadow: aesthetic-eating that focuses on form over the body\'s real signal.' },
  { name: 'Mars in 7th (Dispositor)', description: 'When this engine fires, partner-eating dynamics dominate. Shared cuisine choices, joint-restaurant patterns. Honor your own body-signal even in shared settings.' },
  { name: 'Jupiter in 11th (Dispositor)', description: 'When this engine fires, generous group-meals, ceremonial banquets, foreign-cuisine immersion all favored — in moderation. Beware over-eating in celebration.' },
  { name: 'Saturn in 10th (Dispositor)', description: 'When this engine fires, regularity is the medicine. Same meals at same times for two weeks; the system stabilizes. Warm cooked food, steady protein, oils and warming spices for joints.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Solar fire on the body. Heat rises slightly; appetite sharpens; warm cooked food favored. Avoid extra heating spices.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on speech, voice, intake. Vocal-care matters; honey, ghee, soothing teas. Avoid acid foods if voice is in use.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on the diet. Bold dietary changes possible; the willpower is up.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on the home kitchen. Cook at home; mother\'s recipes restore; the hearth is medicinal.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on the digestive-creative engine. Best window for masterclass-grade clean eating; performance-fuel diet.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on the daily eating-system. Best window for elimination-diet, clean-eating reset, parasite-cleanse, gut-audit.' },
  { name: 'Sun Transits the 7th House', description: 'Solar light on shared meals. Partner-related eating dynamics surface. Avoid alcohol-heavy social meals.' },
  { name: 'Sun Transits the 8th House', description: 'Solar fire in the transformation chamber. Sharp digestive resets; possible flare of old food-triggers — handle softly.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on philosophical eating. Sattvic diet calls; traditional fast; ceremonial food.' },
  { name: 'Sun Transits the 10th House', description: 'Solar fire on structural-eating habits. Lock in fixed meal-times; the schedule sets in.' },
  { name: 'Sun Transits the 11th House', description: 'Solar light on group-eating. Friend-network meals favored, but watch over-eating in celebration.' },
  { name: 'Sun Transits the 12th House', description: 'Solar light on retreat-eating. Foreign cuisine, hotel meals, hospital-style diets dominate.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day window of body-emotion fusion. Eat with extra warmth and self-care.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on speech and intake. Comfort-food cravings rise; choose warm and nourishing.' },
  { name: 'Moon Transits the 3rd House', description: 'Monthly snack-emotion peak. Pre-prep clean snacks.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly home-kitchen peak. Cook at home; mother\'s food restores.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative-eating. Avoid emotional eating before performances.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on digestive sensitivity. Eat clean; reduce triggers.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on shared meals. Read the partner\'s food-mood.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on the transformation-eating zone. Avoid heavy meals; defer rich food two days.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward sattvic, ceremonial, foreign food. Travel-eating favored.' },
  { name: 'Moon Transits the 10th House', description: 'Emotional charge on the eating schedule. Don\'t skip meals from busy-ness.' },
  { name: 'Moon Transits the 11th House', description: 'Emotional warmth toward group-eating. Attend the dinner mindfully.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional charge on retreat and foreign-cuisine. Soup, broth, soft foods.' },
  { name: 'Mercury Transits the 1st House', description: 'Sharp body-communication. Refresh the eating-plan; review the food-journal.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp food-and-voice articulation. Lock in family-finance-food plan; record the recipe-talk.' },
  { name: 'Mercury Transits the 3rd House', description: 'Mercury\'s home turf for snack-articulation. Plan the meal-prep system.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp home-kitchen articulation. Write the family-recipe document.' },
  { name: 'Mercury Transits the 5th House', description: 'Mercury exalted on the digestive-creative engine. Peak food-precision month. Audit the diet, write the protocol, ship the food-content.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp daily-eating articulation. Document the elimination-diet; track the gut-response precisely.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp shared-eating articulation. Communicate the food-rules to partner; align the kitchen.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation-eating articulation. Document the cleanse, the reaction, the trigger.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp philosophical-eating articulation. Write the dietary-principle document.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp structural-eating articulation. Publish the meal-schedule formally.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp group-eating articulation. Coordinate the cooperative-meal-plan with friends.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp retreat-eating articulation. Foreign-cuisine notes, retreat-meal-protocol.' },
  { name: 'Venus Transits the 1st House', description: 'Venus on the body. Body-aesthetic eating, well-presented meals, sensual dining. Sweet pleasure rises — moderate.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on speech and intake. Honey, dates, sweet fruits, soothing teas. Voice-care food.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on snacking. Curated bites, fresh-fruit boards, pleasure-rich small meals.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on the home kitchen. Aesthetic upgrades to cookware, dining table, plating.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on creative-eating. Performance-grade meals, child-friendly favorites, romantic dining.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on daily-eating. Charm the food-routine; pleasure-rich healing.' },
  { name: 'Venus Transits the 7th House', description: 'Beauty on shared meals. Partner-warmth at the table; romantic dinners.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in the transformation chamber. Cleansing-with-grace, aesthetic-fast, retreat-meal beauty.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on philosophical eating. Sattvic banquets, ceremonial-food, foreign-luxury cuisine.' },
  { name: 'Venus Transits the 10th House', description: 'Beauty on structural-eating. The elegant lunch, the curated business meal, the photographed dish.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on group-eating. Friend-banquets, cooperative-platform dining.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on retreat-eating. Foreign-luxury dining, hotel-breakfast aesthetics.' },
  { name: 'Mars Transits the 1st House', description: 'Body-fire peaks. Cool the system; cucumber, mint, coconut, fennel water. Avoid red meat, alcohol, chili.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on speech and intake. Tongue-burns possible; avoid hot food rapidly consumed.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on snacking. Aggressive snacking risk; pre-prep clean choices.' },
  { name: 'Mars Transits the 4th House', description: 'Mars in the home kitchen. Cooking-fire risk; care with hot pans, knives.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on creative-eating. Bold dietary experiments, intense fasting.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on the digestive engine — Mars\'s strong terrain. Best window for the strict elimination diet, the parasite-cleanse, the bold gut-protocol.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on its own throne (Scorpio 7H — Ruchaka activation). Peak transformation-eating window. Bold detoxes, sudden allergy-discoveries, aggressive cleanses, surgical eliminations all work.' },
  { name: 'Mars Transits the 8th House', description: 'Mars in the transformation chamber. Surgical food-resets, sudden allergy-flares, deep parasite-protocols.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on philosophical eating. Bold sattvic-fast, contested ceremonial food.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on structural-eating. Bold meal-rhythm enforcement; lock the discipline.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on group-eating. Contested social meals; lead the cleanse-with-friends.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential eating. Foreign-cuisine adventures, hospital-diet combat.' },
  { name: 'Jupiter Transits the 1st House', description: 'Body-expansion year. Weight-gain risk; portion control matters. The body wants more food than the metabolism can burn.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Speech-and-intake expansion. Voice projects, family-recipe-publication, food-content growth.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Snack-and-courage expansion. Clean-snack-content, bold dietary-bravery.' },
  { name: 'Jupiter Transits the 4th House', description: 'Home-kitchen expansion year. Family-recipe publication, traditional-food chapter, mother-line cuisine inflection.' },
  { name: 'Jupiter Transits the 5th House', description: 'Creative-eating expansion. Course on food, recipe-book, performance-grade meal protocols.' },
  { name: 'Jupiter Transits the 6th House', description: 'Adversary-victory in the diet. Long-running gut issues resolve; chronic food-allergy fades.' },
  { name: 'Jupiter Transits the 7th House', description: 'Shared-eating expansion. Partner-cuisine inflection; joint-kitchen growth.' },
  { name: 'Jupiter Transits the 8th House', description: 'Transformation-eating expansion. Inheritance of food-traditions; deep-protocol breakthroughs.' },
  { name: 'Jupiter Transits the 9th House', description: 'Philosophical-eating expansion year. Sattvic-diet platform, ceremonial-food chapter, foreign-cuisine immersion.' },
  { name: 'Jupiter Transits the 10th House', description: 'Structural-eating expansion year. Meal-rhythm consolidation, food-platform leadership.' },
  { name: 'Jupiter Transits the 11th House', description: 'Jupiter on its own throne. Peak group-eating gain year. Friend-banquets, cooperative-platform dining, international-cuisine networks all compound. Watch portion-discipline.' },
  { name: 'Jupiter Transits the 12th House', description: 'Foreign-eating expansion year. International travel-cuisine, retreat-meal chapter, hospital-diet wisdom.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year structural pressure on the body. Joints, bones, slow weight gain. Discipline diet now or pay later.' },
  { name: 'Saturn Transits the 2nd House', description: 'Discipline on speech, voice, food. Slow dental and throat care.' },
  { name: 'Saturn Transits the 3rd House', description: 'Discipline on small-effort eating. Build food-prep routines that last decades.' },
  { name: 'Saturn Transits the 4th House', description: 'Heavy home-kitchen weight; mother\'s health-and-food becomes a structural concern.' },
  { name: 'Saturn Transits the 5th House', description: 'Creative-metabolism discipline. Heart-care, bone-density work; long-arc fitness foundation.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain. Long-term gut-mastery year. Multi-year diet that compounds.' },
  { name: 'Saturn Transits the 7th House', description: 'Structural test of shared meals. Long-arc partner-nutrition habits formalize.' },
  { name: 'Saturn Transits the 8th House', description: 'Major dietary restructuring window. Old food-habits end; new structural patterns set.' },
  { name: 'Saturn Transits the 9th House', description: 'Discipline on sattvic/traditional eating. Slow ceremonial-fast practice.' },
  { name: 'Saturn Transits the 10th House', description: 'Saturn on its own throne (Aquarius 10H — Sasa). The 2.5-year window that seeds the next 30-year eating-pattern. Lock in the structure.' },
  { name: 'Saturn Transits the 11th House', description: 'Disciplined group-eating; the social-eating network purges what is unhealthy.' },
  { name: 'Saturn Transits the 12th House', description: 'Discipline on foreign and retreat-eating. Long-distance dietary patterns formalize.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive body-reinvention. New diet, new body-image. Verify each protocol.' },
  { name: 'Rahu Transits the 2nd House', description: 'Obsessive eating around voice, family-finance. Beware get-thin-quick schemes.' },
  { name: 'Rahu Transits the 3rd House', description: 'Obsessive food-research. Diet-fad-chasing; verify integrity.' },
  { name: 'Rahu Transits the 4th House', description: 'Obsessive home-cooking chapter. Foreign recipes, family-tradition reinvention.' },
  { name: 'Rahu Transits the 5th House', description: 'Obsessive performance-eating. Intense dieting; speculation around food businesses.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Defeat a long-running food sensitivity, win against a chronic gut issue.' },
  { name: 'Rahu Transits the 7th House', description: 'Obsessive partner-eating. Foreign cuisine pull; controversial joint-diet experiments.' },
  { name: 'Rahu Transits the 8th House', description: 'Rahu on its strong terrain. Obsessive transformation-eating. Sudden allergy-discoveries; deep food-medicine research; aggressive cleansing protocols.' },
  { name: 'Rahu Transits the 9th House', description: 'Foreign-fortune food obsession. International cuisine, controversial guru-of-the-diet.' },
  { name: 'Rahu Transits the 10th House', description: 'Obsessive structural-diet push. Sudden meal-plan changes; verify legitimacy.' },
  { name: 'Rahu Transits the 11th House', description: 'Obsessive group-eating chapter. Trend-diet pressure; stay clean.' },
  { name: 'Rahu Transits the 12th House', description: 'Obsessive foreign-cuisine pull. Hidden food-issues surface; pleasure-eating obsession.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month body-stripping window. Old eating-identity feels empty. Sit; do not over-protocol.' },
  { name: 'Ketu Transits the 2nd House', description: 'Detachment from food, voice, family-finance dynamics. Cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Detachment from food-research and small-burst eating. Solo simple meals favored.' },
  { name: 'Ketu Transits the 4th House', description: 'Home-kitchen detachment. Less attachment to family-recipes; simplification.' },
  { name: 'Ketu Transits the 5th House', description: 'Performance-metabolism eclipse. Old fame-diet feels hollow; fasting easier.' },
  { name: 'Ketu Transits the 6th House', description: 'Service-eating detachment. Old chronic gut-issues dissolve without intervention.' },
  { name: 'Ketu Transits the 7th House', description: 'Partner-eating detachment. Joint food-rituals dissolve.' },
  { name: 'Ketu Transits the 8th House', description: 'Transformation-eating acceleration. Old food-allergies fade; new ones may surface briefly.' },
  { name: 'Ketu Transits the 9th House', description: 'Sattvic-eating detachment. Old guru-diets feel finished; principle-without-attachment ripens.' },
  { name: 'Ketu Transits the 10th House', description: 'Structural-diet eclipse. Old meal-schedule feels weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month deep purification of group-eating motivations.' },
  { name: 'Ketu Transits the 12th House', description: 'Foreign-cuisine and retreat-diet dissolution. Pleasure-eating evaporates.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar fire on the body. Warm cooked food; avoid extra heating spices.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Heating window opens.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Cooling, hydrating foods.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Heating window closes.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Solar fire on eating-schedule. Lock fixed meal-times.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Schedule-discipline window opens.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak day. Maintain rhythm strictly.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Emotional charge on body. Eat with warmth and self-care.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Emotion-on-body window opens.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Comfort cravings rise; nourish warmly.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Emotional charge on schedule. Don\'t skip meals from busy-ness.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak day. Honor the meal-time.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Sharp body-communication. Refresh the eating-plan.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Send the dietitian inquiry; write the food journal.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Sharp schedule-communication. Lock the meal-plan formally.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Publish the meal schedule to household.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Body-aesthetic eating. Sweet pleasure rises — moderate.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Indulge with intention.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Softens public-eating. Brand-friendly food choices.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak day. Photograph the elegant meal.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Body-fire peaks. Cool the system; cucumber, mint, coconut.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Coconut water, mint, fennel.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Bold scheduling-discipline. Lock rigorous meal-plan.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak day. Execute the plan strictly.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Body expands. Weight-gain risk; portion control matters.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Larger appetite — control portions.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Wisdom on eating-schedule. Lock long-term plan.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the long-term diet decision.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Heavy structural pressure on body. Joints, bones, slow weight gain risk.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Discipline diet — bones, joints need warm oily food.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Saturn on its own MC throne. Peak structural-eating window. Lock the rigorous meal-plan for years.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day. The schedule sets in for the long horizon.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic body-experimentation. Diet-fad pull strong; verify each protocol.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Body-reinvention urge — verify integrity.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Chaotic schedule-shifts. Sudden meal-plan changes.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Verify the new schedule before locking.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Body-stripping. Old eating-identity feels empty.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit; do not over-protocol.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Schedule-eclipse. Old meal-rhythm feels weightless.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Window opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. The schedule dissolves; do not panic-rebuild.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting the long-arc eating engine. Old dietary frameworks dismantle. Multi-year food-platform transformation; the body emerges with rebuilt structural nutrition.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year dietary structural reckoning begins. Old food-frameworks dismantle.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak day. The old eating-system breaks; the new one is forced into being.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Dietary-transformation chapter completes. The new nutrition-foundation is permanent.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the Venus-on-lagna body-aesthetic. Unexpected dietary shifts, abrupt body-image pivots.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Sudden body-aesthetic-disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak day. The unexpected dietary pivot lands.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Body-aesthetic-disruption window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 4th house', description: 'Solar fire on home-kitchen. Cook at home; mother\'s recipes restore.' },
  { name: 'Sun aspect Sun in 4th house : Starts', description: 'Home-kitchen window opens.' },
  { name: 'Sun aspect Sun in 4th house : Exact', description: 'Peak day. Home-cooked feast.' },
  { name: 'Sun aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Moon in 3rd house', description: 'Solar fire on snack-emotion. Pre-prep clean small bites.' },
  { name: 'Sun aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Moon in 3rd house : Exact', description: 'Peak day. Honor the small-burst hunger cleanly.' },
  { name: 'Sun aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mercury in 5th house', description: 'Solar fire on creative-eating. Performance-fuel diet; clean grains, good fats, sharp protein.' },
  { name: 'Sun aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mercury in 5th house : Exact', description: 'Peak day. Performance-grade clean meals.' },
  { name: 'Sun aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Venus in 1st house', description: 'Solar fire on body-aesthetic. Warm cooked food; sweet pleasure rises — moderate.' },
  { name: 'Sun aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Venus in 1st house : Exact', description: 'Peak day. Sensual but disciplined eating.' },
  { name: 'Sun aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Mars in 7th house', description: 'Solar fire on shared meals. Partner-related eating dynamics surface.' },
  { name: 'Sun aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Mars in 7th house : Exact', description: 'Peak day. Avoid alcohol-heavy social meals.' },
  { name: 'Sun aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Jupiter in 11th house', description: 'Solar fire on group-eating. Friend-network meals favored, but moderate.' },
  { name: 'Sun aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Jupiter in 11th house : Exact', description: 'Peak day. Attend the friend-banquet mindfully.' },
  { name: 'Sun aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Saturn in 10th house', description: 'Solar fire on structural-eating. Lock fixed meal-times; the schedule sets in.' },
  { name: 'Sun aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Saturn in 10th house : Exact', description: 'Peak day. Maintain the rhythm strictly.' },
  { name: 'Sun aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Rahu in 8th house', description: 'Solar fire in transformation-eating chamber. Sharp digestive resets; possible flare of old triggers.' },
  { name: 'Sun aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Rahu in 8th house : Exact', description: 'Peak day. Handle old food-triggers softly.' },
  { name: 'Sun aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Sun aspect Ketu in 2nd house', description: 'Solar light on detached voice/family-money zone. Old earning-channel meals feel finished.' },
  { name: 'Sun aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Sun aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the food-spending pattern that has been hollow.' },
  { name: 'Sun aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Sun in 4th house', description: 'Emotional charge on home-kitchen. Cook at home; mother\'s food restores.' },
  { name: 'Moon aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Sun in 4th house : Exact', description: 'Peak day. Family-table meal.' },
  { name: 'Moon aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Moon in 3rd house', description: 'Emotional courage on snacking. Pre-prep clean snacks.' },
  { name: 'Moon aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Moon in 3rd house : Exact', description: 'Peak day. Honor the small-burst hunger.' },
  { name: 'Moon aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mercury in 5th house', description: 'Emotional charge on creative-eating. Avoid emotional eating before performance.' },
  { name: 'Moon aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mercury in 5th house : Exact', description: 'Peak day. Pre-meal: anchor with warm grain, not sugar.' },
  { name: 'Moon aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Venus in 1st house', description: 'Emotional charge on body-aesthetic. Sweet cravings rise; warm milk and dates beat ice cream.' },
  { name: 'Moon aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Venus in 1st house : Exact', description: 'Peak day. Indulge warmly, not coldly.' },
  { name: 'Moon aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Mars in 7th house', description: 'Emotional charge on shared meals. Read the partner\'s food-mood.' },
  { name: 'Moon aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Mars in 7th house : Exact', description: 'Peak day. Soften the joint-meal tone.' },
  { name: 'Moon aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Jupiter in 11th house', description: 'Emotional warmth toward group-eating. Friend-banquet pull.' },
  { name: 'Moon aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Jupiter in 11th house : Exact', description: 'Peak day. Attend mindfully; over-eating risk in celebration.' },
  { name: 'Moon aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Saturn in 10th house', description: 'Emotional charge on structural-eating. Don\'t skip meals from busy-ness.' },
  { name: 'Moon aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Saturn in 10th house : Exact', description: 'Peak day. Honor the meal-time even if work pulls.' },
  { name: 'Moon aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Rahu in 8th house', description: 'Emotional weight on transformation-eating. Defer rich food two days.' },
  { name: 'Moon aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Rahu in 8th house : Exact', description: 'Peak day. Soup, broth, soft foods.' },
  { name: 'Moon aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Moon aspect Ketu in 2nd house', description: 'Emotional detachment from voice/family-money food. Cravings dissolve.' },
  { name: 'Moon aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Moon aspect Ketu in 2nd house : Exact', description: 'Peak day. Eat simply; do not chase the old comfort-pattern.' },
  { name: 'Moon aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Sun in 4th house', description: 'Sharp home-kitchen articulation. Write the family-recipe document.' },
  { name: 'Mercury aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Sun in 4th house : Exact', description: 'Peak day. Document mother\'s recipes formally.' },
  { name: 'Mercury aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Moon in 3rd house', description: 'Sharp snack-articulation. Plan the meal-prep system.' },
  { name: 'Mercury aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Moon in 3rd house : Exact', description: 'Peak day. Pre-prep clean snacks for the week.' },
  { name: 'Mercury aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mercury in 5th house', description: 'Mercury exalted on the digestive-creative engine. Peak food-precision day. Audit the diet, write the protocol, ship the food-content.' },
  { name: 'Mercury aspect Mercury in 5th house : Starts', description: 'Exalted-precision window opens.' },
  { name: 'Mercury aspect Mercury in 5th house : Exact', description: 'Peak day. The mind reads the body precisely — write the food-journal protocol.' },
  { name: 'Mercury aspect Mercury in 5th house : Ends', description: 'Exalted-precision window closes.' },
  { name: 'Mercury aspect Venus in 1st house', description: 'Sharp body-aesthetic articulation. Document the body-baseline; track the photographs.' },
  { name: 'Mercury aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Venus in 1st house : Exact', description: 'Peak day. Photograph the body, log the measurements.' },
  { name: 'Mercury aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Mars in 7th house', description: 'Sharp shared-eating articulation. Communicate the food-rules to partner.' },
  { name: 'Mercury aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Mars in 7th house : Exact', description: 'Peak day. Send the joint-kitchen guidelines.' },
  { name: 'Mercury aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Jupiter in 11th house', description: 'Sharp group-eating articulation. Coordinate cooperative-meal-plan.' },
  { name: 'Mercury aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Jupiter in 11th house : Exact', description: 'Peak day. Send the friend-banquet meal-plan.' },
  { name: 'Mercury aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Saturn in 10th house', description: 'Sharp structural-eating articulation. Publish the meal-schedule formally.' },
  { name: 'Mercury aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Saturn in 10th house : Exact', description: 'Peak day. Lock the multi-year meal-rhythm in writing.' },
  { name: 'Mercury aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Rahu in 8th house', description: 'Sharp transformation-eating articulation. Document the cleanse, the reaction, the trigger.' },
  { name: 'Mercury aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Rahu in 8th house : Exact', description: 'Peak day. Track the elimination-diet response precisely.' },
  { name: 'Mercury aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Mercury aspect Ketu in 2nd house', description: 'Sharp voice-detachment articulation. Audit the food-spending channels.' },
  { name: 'Mercury aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Mercury aspect Ketu in 2nd house : Exact', description: 'Peak day. Cut the food-subscription that has been wasted.' },
  { name: 'Mercury aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Sun in 4th house', description: 'Beauty on home-kitchen. Aesthetic upgrades to cookware, table, plating.' },
  { name: 'Venus aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Sun in 4th house : Exact', description: 'Peak day. Curate the dining setting at home.' },
  { name: 'Venus aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Moon in 3rd house', description: 'Beauty on snacking. Curated bites, fresh-fruit boards.' },
  { name: 'Venus aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Moon in 3rd house : Exact', description: 'Peak day. Build pleasure-rich small meals.' },
  { name: 'Venus aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Mercury in 5th house', description: 'Beauty on creative-eating. Performance-grade meal-aesthetics.' },
  { name: 'Venus aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mercury in 5th house : Exact', description: 'Peak day. Photograph the meal; publish the food-content.' },
  { name: 'Venus aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Venus in 1st house', description: 'Venus on its Malavya throne. Peak body-aesthetic day. Sweet cravings peak — moderate. Sensual, well-presented eating.' },
  { name: 'Venus aspect Venus in 1st house : Starts', description: 'Malavya window opens.' },
  { name: 'Venus aspect Venus in 1st house : Exact', description: 'Peak Malavya day. Curate the pleasure-meal carefully.' },
  { name: 'Venus aspect Venus in 1st house : Ends', description: 'Malavya window closes.' },
  { name: 'Venus aspect Mars in 7th house', description: 'Beauty on shared meals. Romantic dinner; partner-warmth at the table.' },
  { name: 'Venus aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Mars in 7th house : Exact', description: 'Peak day. Take the partner to the elegant meal.' },
  { name: 'Venus aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Jupiter in 11th house', description: 'Beauty on group-eating. Friend-banquets, cooperative dining grace.' },
  { name: 'Venus aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Jupiter in 11th house : Exact', description: 'Peak day. Host the elegant friend-feast.' },
  { name: 'Venus aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Saturn in 10th house', description: 'Beauty on structural-eating. Elegant business-lunches, photographed dishes.' },
  { name: 'Venus aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Saturn in 10th house : Exact', description: 'Peak day. Take the elegant senior-stakeholder meal.' },
  { name: 'Venus aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Rahu in 8th house', description: 'Beauty in transformation-chamber. Aesthetic-cleanse, retreat-meal grace.' },
  { name: 'Venus aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Rahu in 8th house : Exact', description: 'Peak day. Take the elegant cleansing-protocol.' },
  { name: 'Venus aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Venus aspect Ketu in 2nd house', description: 'Beauty on voice-detachment. Old food-traditions feel weightless; simplicity is elegant.' },
  { name: 'Venus aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Venus aspect Ketu in 2nd house : Exact', description: 'Peak day. Eat one simple beautiful meal.' },
  { name: 'Venus aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Sun in 4th house', description: 'Mars in the home kitchen. Cooking-fire risk; care with hot pans, knives.' },
  { name: 'Mars aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Sun in 4th house : Exact', description: 'Peak day. Watch knife-injuries and burns.' },
  { name: 'Mars aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Moon in 3rd house', description: 'Mars on snacking. Aggressive snacking risk; pre-prep clean choices.' },
  { name: 'Mars aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Moon in 3rd house : Exact', description: 'Peak day. Honor the urge cleanly.' },
  { name: 'Mars aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mercury in 5th house', description: 'Mars on creative-eating. Bold dietary experiments, intense fasting windows.' },
  { name: 'Mars aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Mercury in 5th house : Exact', description: 'Peak day. Take the bold protocol.' },
  { name: 'Mars aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Venus in 1st house', description: 'Mars on body-aesthetic. Body-fire peaks. Cool the system.' },
  { name: 'Mars aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Venus in 1st house : Exact', description: 'Peak day. Cucumber, mint, coconut.' },
  { name: 'Mars aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Mars in 7th house', description: 'Mars on its own throne (Scorpio 7H). Peak transformation-eating day. Surgical detoxes, aggressive cleanses, sudden allergy-discoveries — Ruchaka activation favors decisive food-discipline.' },
  { name: 'Mars aspect Mars in 7th house : Starts', description: 'Ruchaka-window opens. Plan the bold protocol.' },
  { name: 'Mars aspect Mars in 7th house : Exact', description: 'Peak Ruchaka day. Take the surgical food-discipline move.' },
  { name: 'Mars aspect Mars in 7th house : Ends', description: 'Ruchaka-window closes.' },
  { name: 'Mars aspect Jupiter in 11th house', description: 'Mars on group-eating. Contested social meals; lead the cleanse-with-friends.' },
  { name: 'Mars aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Jupiter in 11th house : Exact', description: 'Peak day. Lead the friend-cleanse.' },
  { name: 'Mars aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Saturn in 10th house', description: 'Mars on structural-eating. Bold meal-rhythm enforcement; lock the discipline.' },
  { name: 'Mars aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Saturn in 10th house : Exact', description: 'Peak day. Force the rigorous schedule.' },
  { name: 'Mars aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Rahu in 8th house', description: 'Mars in transformation-chamber. Surgical food-resets; sudden allergy-flares.' },
  { name: 'Mars aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Rahu in 8th house : Exact', description: 'Peak day. Take the deep parasite-protocol.' },
  { name: 'Mars aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Mars aspect Ketu in 2nd house', description: 'Mars on voice-detachment. Sudden food-spending disputes; old food-channels detonate.' },
  { name: 'Mars aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Mars aspect Ketu in 2nd house : Exact', description: 'Peak day. Cut the food-subscription forcefully.' },
  { name: 'Mars aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Sun in 4th house', description: 'Wisdom on home-kitchen. Family-recipe-publication, traditional-food chapter.' },
  { name: 'Jupiter aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Sun in 4th house : Exact', description: 'Peak day. Document mother\'s cuisine for posterity.' },
  { name: 'Jupiter aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Moon in 3rd house', description: 'Wisdom on snack-and-courage. Clean-snack-content publishing.' },
  { name: 'Jupiter aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Moon in 3rd house : Exact', description: 'Peak day. Publish the bold-eating-discipline note.' },
  { name: 'Jupiter aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mercury in 5th house', description: 'Wisdom on creative-eating. Course on food, recipe-book, performance-meal protocols.' },
  { name: 'Jupiter aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mercury in 5th house : Exact', description: 'Peak day. Launch the food-course or recipe-platform.' },
  { name: 'Jupiter aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Venus in 1st house', description: 'Wisdom on body-aesthetic. Body-image expansion — moderate the indulgence.' },
  { name: 'Jupiter aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Venus in 1st house : Exact', description: 'Peak day. Eat luxuriously but disciplined.' },
  { name: 'Jupiter aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Mars in 7th house', description: 'Wisdom on shared-eating. Partner-cuisine inflection; joint-kitchen growth.' },
  { name: 'Jupiter aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Mars in 7th house : Exact', description: 'Peak day. Establish the joint-kitchen ethic.' },
  { name: 'Jupiter aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Jupiter in 11th house', description: 'Jupiter on its own throne (Pisces 11H). Peak group-eating year. Friend-banquets, ceremonial-feasts, foreign-cuisine networks all compound. Watch portion-discipline.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Starts', description: 'Group-eating expansion window opens.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Exact', description: 'Peak day. Host or attend the elegant friend-feast — moderate.' },
  { name: 'Jupiter aspect Jupiter in 11th house : Ends', description: 'Group-eating expansion window closes.' },
  { name: 'Jupiter aspect Saturn in 10th house', description: 'Wisdom on structural-eating. Meal-rhythm consolidation, food-platform leadership.' },
  { name: 'Jupiter aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Saturn in 10th house : Exact', description: 'Peak day. Lock the long-term diet decision.' },
  { name: 'Jupiter aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Rahu in 8th house', description: 'Wisdom in transformation-chamber. Inheritance of food-traditions; deep-protocol breakthroughs.' },
  { name: 'Jupiter aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Rahu in 8th house : Exact', description: 'Peak day. Adopt the family-tradition food-protocol.' },
  { name: 'Jupiter aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Jupiter aspect Ketu in 2nd house', description: 'Wisdom on voice-detachment. Old food-channels graduate; teach the lesson of the simple meal.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Exact', description: 'Peak day. Convert the abandoned food-pattern into a teaching artifact.' },
  { name: 'Jupiter aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Sun in 4th house', description: 'Discipline on home-kitchen. Mother\'s health-and-food becomes a structural concern.' },
  { name: 'Saturn aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Sun in 4th house : Exact', description: 'Peak day. Restructure the family-meal pattern.' },
  { name: 'Saturn aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Moon in 3rd house', description: 'Discipline on snacking. Build food-prep routines that last decades.' },
  { name: 'Saturn aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Moon in 3rd house : Exact', description: 'Peak day. Lock the meal-prep system.' },
  { name: 'Saturn aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mercury in 5th house', description: 'Discipline on creative-eating. Long-arc fitness foundation; bone-density work.' },
  { name: 'Saturn aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mercury in 5th house : Exact', description: 'Peak day. Lock the multi-year creative-eating protocol.' },
  { name: 'Saturn aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Venus in 1st house', description: 'Discipline on body-aesthetic. Slow weight-management; vanity-diet falls away; durable body-care sets in.' },
  { name: 'Saturn aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Venus in 1st house : Exact', description: 'Peak day. Lock the long-term body-care ritual.' },
  { name: 'Saturn aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Mars in 7th house', description: 'Structural test of shared meals. Long-arc partner-nutrition habits formalize.' },
  { name: 'Saturn aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Mars in 7th house : Exact', description: 'Peak day. Lock the joint-kitchen rhythm.' },
  { name: 'Saturn aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Jupiter in 11th house', description: 'Disciplined group-eating; the social-eating network purges what is unhealthy.' },
  { name: 'Saturn aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Jupiter in 11th house : Exact', description: 'Peak day. Formalize the friend-cleanse.' },
  { name: 'Saturn aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Saturn in 10th house', description: 'Saturn on its own Sasa throne. Peak structural-eating day of the multi-decade cycle. The 30-year meal-rhythm sets in permanently.' },
  { name: 'Saturn aspect Saturn in 10th house : Starts', description: 'Sasa-window opens.' },
  { name: 'Saturn aspect Saturn in 10th house : Exact', description: 'Peak Sasa day. Lock the lifetime meal-schedule.' },
  { name: 'Saturn aspect Saturn in 10th house : Ends', description: 'Sasa-window closes.' },
  { name: 'Saturn aspect Rahu in 8th house', description: 'Major dietary restructuring window. Old food-habits end; new structural patterns set.' },
  { name: 'Saturn aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Rahu in 8th house : Exact', description: 'Peak day. Lock the new transformative-eating structure.' },
  { name: 'Saturn aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Saturn aspect Ketu in 2nd house', description: 'Discipline on voice-detachment. Old food-spending channels formally close.' },
  { name: 'Saturn aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Saturn aspect Ketu in 2nd house : Exact', description: 'Peak day. Sign the closure of the dead food-pattern.' },
  { name: 'Saturn aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Sun in 4th house', description: 'Chaotic expansion on home-kitchen. Foreign recipes, family-tradition reinvention.' },
  { name: 'Rahu aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Sun in 4th house : Exact', description: 'Peak day. Try the foreign-cuisine experiment at home.' },
  { name: 'Rahu aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Moon in 3rd house', description: 'Chaotic snacking expansion. Diet-fad-chasing; verify integrity.' },
  { name: 'Rahu aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Moon in 3rd house : Exact', description: 'Peak day. Vet the new snack-trend before adopting.' },
  { name: 'Rahu aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mercury in 5th house', description: 'Chaotic creative-eating expansion. Speculative food-businesses, intense diet-platforms.' },
  { name: 'Rahu aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mercury in 5th house : Exact', description: 'Peak day. Take the diet-platform move with verification.' },
  { name: 'Rahu aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Venus in 1st house', description: 'Chaotic body-experimentation. Diet-fad pull strong; verify each protocol.' },
  { name: 'Rahu aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Venus in 1st house : Exact', description: 'Peak day. Body-reinvention urge — verify integrity.' },
  { name: 'Rahu aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Mars in 7th house', description: 'Chaotic shared-eating. Foreign cuisine pull with partner; controversial joint-diet experiments.' },
  { name: 'Rahu aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Mars in 7th house : Exact', description: 'Peak day. Vet the joint-cleanse before committing.' },
  { name: 'Rahu aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Jupiter in 11th house', description: 'Chaotic group-eating. Trend-diet pressure from network; stay clean.' },
  { name: 'Rahu aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Jupiter in 11th house : Exact', description: 'Peak day. Resist the friend-circle diet-fad.' },
  { name: 'Rahu aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Saturn in 10th house', description: 'Chaotic structural-diet shift. Sudden meal-plan changes; verify legitimacy.' },
  { name: 'Rahu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Saturn in 10th house : Exact', description: 'Peak day. Vet the unconventional meal-rhythm.' },
  { name: 'Rahu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Rahu aspect Rahu in 8th house', description: 'Rahu return on its strong terrain. Peak transformation-eating chaos. Sudden allergy-flares; deep food-medicine research.' },
  { name: 'Rahu aspect Rahu in 8th house : Starts', description: 'Rahu-return window opens.' },
  { name: 'Rahu aspect Rahu in 8th house : Exact', description: 'Peak Rahu-return day. Take the surgical food-protocol with documentation.' },
  { name: 'Rahu aspect Rahu in 8th house : Ends', description: 'Rahu-return window closes.' },
  { name: 'Rahu aspect Ketu in 2nd house', description: 'Axis-stress on voice-detachment. Sudden food-spending turbulence.' },
  { name: 'Rahu aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Rahu aspect Ketu in 2nd house : Exact', description: 'Peak day. Defer food-spending decisions; the axis is loud.' },
  { name: 'Rahu aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Sun in 4th house', description: 'Detachment on home-kitchen. Old family-recipes feel weightless; simplification.' },
  { name: 'Ketu aspect Sun in 4th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Sun in 4th house : Exact', description: 'Peak day. Eat one simple home-meal; do not chase tradition.' },
  { name: 'Ketu aspect Sun in 4th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Moon in 3rd house', description: 'Detachment from snacking. Old snack-loops feel finished.' },
  { name: 'Ketu aspect Moon in 3rd house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Moon in 3rd house : Exact', description: 'Peak day. Skip the habitual snack; the urge dissolves.' },
  { name: 'Ketu aspect Moon in 3rd house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mercury in 5th house', description: 'Detachment on creative-eating. Old performance-diet feels hollow; fasting easier.' },
  { name: 'Ketu aspect Mercury in 5th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mercury in 5th house : Exact', description: 'Peak day. Try the simple fast.' },
  { name: 'Ketu aspect Mercury in 5th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Venus in 1st house', description: 'Body-stripping. Old eating-identity feels empty; sweet cravings dissolve.' },
  { name: 'Ketu aspect Venus in 1st house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Venus in 1st house : Exact', description: 'Peak day. Sit with the body feeling weightless.' },
  { name: 'Ketu aspect Venus in 1st house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Mars in 7th house', description: 'Partner-eating detachment. Joint food-rituals dissolve.' },
  { name: 'Ketu aspect Mars in 7th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Mars in 7th house : Exact', description: 'Peak day. Eat alone if the joint-meal feels hollow.' },
  { name: 'Ketu aspect Mars in 7th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Jupiter in 11th house', description: 'Eighteen-month deep purification of group-eating motivations.' },
  { name: 'Ketu aspect Jupiter in 11th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Jupiter in 11th house : Exact', description: 'Peak day. Skip the friend-banquet; the network is cleansing.' },
  { name: 'Ketu aspect Jupiter in 11th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Saturn in 10th house', description: 'Structural-diet eclipse. Old meal-schedule feels weightless.' },
  { name: 'Ketu aspect Saturn in 10th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Saturn in 10th house : Exact', description: 'Peak day. Loosen the rigid meal-rhythm; do not panic-rebuild.' },
  { name: 'Ketu aspect Saturn in 10th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Rahu in 8th house', description: 'Transformation-eating acceleration. Old food-allergies fade; new ones may surface briefly.' },
  { name: 'Ketu aspect Rahu in 8th house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Rahu in 8th house : Exact', description: 'Peak day. The chronic food-issue dissolves; sit with the silence.' },
  { name: 'Ketu aspect Rahu in 8th house : Ends', description: 'Window closes.' },
  { name: 'Ketu aspect Ketu in 2nd house', description: 'Ketu return on voice-detachment. Old food-spending channels formally close.' },
  { name: 'Ketu aspect Ketu in 2nd house : Starts', description: 'Window opens.' },
  { name: 'Ketu aspect Ketu in 2nd house : Exact', description: 'Peak day. Release the food-channel that has been hollow for years.' },
  { name: 'Ketu aspect Ketu in 2nd house : Ends', description: 'Window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
