// db/seed_food_virgo.js
//
// Per-ascendant fill-in seed for the **food** category, scoped to a
// representative Virgo ascendant native with:
//   Ascendant: Virgo
//   Natal placements (sidereal Lahiri):
//     Sun=12th (Leo, own)  Moon=11th (Cancer, own)
//     Mercury=1st (Virgo, own+exalted — Bhadra Yoga)
//     Venus=7th (Pisces, exalted — Malavya Yoga)
//     Mars=8th (Aries, own — 8L-in-8 Vipareet)
//     Jupiter=4th (Sagittarius, own — Hamsa Yoga)
//     Saturn=5th (Capricorn, own)
//     Rahu=3rd (Scorpio)  Ketu=9th (Taurus)
//
// All 531 events below are the ones the kerykeion engine could emit for
// this user across any transitDate. Fill in the `description` strings as
// you compose food-specific interpretations, then run:
//
//   node db/seed_food_virgo.js
//
// Empty descriptions are skipped — partial fills are safe to run repeatedly.

const db = require('./food');

const ASCENDANT = 'Virgo';

const events = [
  // ────────────────────────────────────────────────────────────────────────
  // RULERS (12)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Mercury ruler of the 1st House in the 1st House', description: 'You eat with the analyst-mind: portions, ingredients, timing, cleanliness all matter to you instinctively. The body is Vata-Pitta dominant — wiry frame, sharp digestion when calm, susceptible to anxiety-driven indigestion. Best diet: warm, cooked, predictable, eaten in a quiet environment on a tight schedule. Avoid raw, cold, irregular eating. Cumin, ginger, fennel, ajwain settle the nervous-stomach. Skip kale-and-cold-salad culture; choose khichdi, soups, stewed vegetables. The shadow: over-analyzing the meal into a research project — at some point food is just nourishment, not data.' },
  { name: 'Venus ruler of the 2nd House in the 7th House', description: 'The mouth and the marriage-table are linked. Many of your richest meals will be shared with the partner; sweet, slow, candle-lit meals open the heart-channel where business deals also close. Pisces-Venus tilt favors refined, watery, sweet foods (fish, rice puddings, white-cheese-and-honey, soft fruits). The shadow: sugar-and-comfort tilt at the partner-table; the love-eats-too-much pattern. Pair sweetness with bitter greens to keep the liver happy.' },
  { name: 'Mars ruler of the 3rd House in the 8th House', description: 'Crisis-eating is a real pattern: when communication intensifies or surgical conversations land, appetite spikes or dies entirely. Mars-Aries-8H ignites the digestive Pitta — your stomach can over-acidify under stress. Cooling sour-sweet food (buttermilk, coconut water, sweet lassi, cucumber, sweet pomegranate) extinguishes the fire. Avoid alcohol during crisis chapters; it amplifies acidity. The shadow: skipping meals in the heat of communication-fire — set a meal alarm.' },
  { name: 'Jupiter ruler of the 4th House in the 4th House', description: 'Hamsa Yoga on the home-throne. The home kitchen is the medicine. Mother\'s recipes, family-business food, slow-cooked grandmother dishes are deeply nourishing. Sagittarian-Jupiter favors warming, sattvic, traditional cuisine — ghee, dal, rice, kichari, slow-cooked meats with whole-spice. Cooking *at home* is itself a healing ritual. Avoid restaurant-heavy weeks. The shadow: comfort-food expansion can quietly settle into Kapha layers — Jupiter in 4th expands the body too.' },
  { name: 'Saturn ruler of the 5th House in the 5th House', description: 'Saturn-on-creative-throne brings discipline to the eating schedule. Best practice: same time, same plate, same quantity — the body responds to ritual. Sweet-warm grains (rice, wheat-roti, oats) ground the Vata mind into the body. The 5H also rules child-feeding — you instinctively know what to feed children but may forget yourself. Cold, dry, raw food (Saturn-Vata-tilt) destabilizes; choose warm, oily, cooked. The shadow: rigidity that becomes a punishment — eating discipline should bring peace, not tension.' },
  { name: 'Saturn ruler of the 6th House in the 5th House', description: 'The chronic-illness chapter is metabolized in the kitchen. Long-arc dietary protocols (six-month Ayurvedic regimens, multi-year fasting schedules, sustained anti-inflammatory diets) are your medicine. Vipareet potential — turn the food problem into the food practice. The shadow: cultivating illness narratives to keep the protocol going; let some chapters of body be uncomplicated.' },
  { name: 'Jupiter ruler of the 7th House in the 4th House', description: 'Spouse and home-cooking merge. Many of your healthiest food chapters will be cooked by the partner or together. Sagittarian-Jupiter favors traditional, warming, sattvic cooking with the partner. Family-recipe transmission is sacred — learn from in-laws too. The shadow: dependency on the partner for nourishment that the body should also know to produce alone.' },
  { name: 'Mars ruler of the 8th House in the 8th House', description: 'Vipareet engine in the gut. Surgical interventions, surgical-style cleanses (panchakarma, controlled fasting under supervision), strong purgative protocols all suit you. Mars-own-sign in 8H wants intense — but the gut doesn\'t. Avoid extreme spice, alcohol, raw garlic in heat. The shadow: occult/extreme dietary protocols (raw-meat fevers, strict carnivore experiments, fasting cults) — Vipareet wants intensity, but Vata-Pitta breaks under it.' },
  { name: 'Venus ruler of the 9th House in the 7th House', description: 'Foreign cuisine, religious-ceremonial food, dharma-table meals nourish you deeply. Pisces-Venus favors fish (where dharma allows), white wines, soft cheese, sweet fruits, slow Mediterranean-style fare. Wedding food, festival food, ashram food all have an extra channel of nourishment for you. The shadow: over-romanticizing exotic-cuisine experiments; the body wants familiar warmth most of the time.' },
  { name: 'Mercury ruler of the 10th House in the 1st House', description: 'Career-anxiety lands in the stomach first. The deadline week, the pitch day, the audit weekend all show up as digestive turbulence before they show up in the calendar. Pre-meeting meals must be light, warm, cooked — never heavy or raw. Ginger tea before high-stakes presentations. The shadow: skipping meals in deadline mode — the body pays interest on the missed meal for three days.' },
  { name: 'Moon ruler of the 11th House in the 11th House', description: 'Friend-circle dinners, community feasts, women-led-network potlucks are deep-nourishment occasions. Moon-Cancer in 11H loves warm, milky, gentle foods — kheer, kichari, soft rice, sweet curd. Mass-audience comfort food (the kind grandma cooked for 30 cousins) feels like home. The shadow: emotional eating in public — the friend-circle table is a place where the food and the warmth blur.' },
  { name: 'Sun ruler of the 12th House in the 12th House', description: 'Retreat-style eating practice. Solo meals, monastery-style meals, ashram food all carry extra nourishment for you. Sun-in-Leo-12H favors warm, sattvic, simple food eaten in silence or near-silence. Pitru tarpan and ancestral-offering rituals before meals are quietly powerful. The shadow: the kingly appetite that wants too much when alone — portion the plate, then sit.' },

  // ────────────────────────────────────────────────────────────────────────
  // DISPOSITORS (7)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun in 12th (Dispositor)', description: 'When this engine fires, retreat-style eating heals. Solo dinners, ashram food, monastery-style portions. The shadow: solitude-eating that drifts into under-eating; weigh yourself monthly.' },
  { name: 'Moon in 11th (Dispositor)', description: 'When this engine fires, friend-circle warmth nourishes. Community feasts, mother-figure-cooked meals, women-led-network potlucks. The shadow: emotional eating in public chapters.' },
  { name: 'Mercury in 1st (Dispositor)', description: 'When this engine fires, the analyst-discipline lands. Best for tracking macros, refining the protocol, adjusting the herbal-formula precisely. The shadow: over-tracking that becomes an eating disorder.' },
  { name: 'Jupiter in 4th (Dispositor)', description: 'When this engine fires, home-cooked traditional food heals. Mother\'s recipes, slow-cooked meals, family-table sit-downs. The shadow: Jupiterian over-portioning — leftovers are not extra meals.' },
  { name: 'Mars in 8th (Dispositor)', description: 'When this engine fires, surgical-style cleansing pays. Panchakarma, supervised fasting, controlled purgatives. The shadow: extreme-cleanse fevers — choose qualified guidance.' },
  { name: 'Saturn in 5th (Dispositor)', description: 'When this engine fires, ritual-eating compounds. Same time, same plate, same quantity. Long-arc dietary protocols mature. The shadow: rigid-discipline eating that becomes its own anxiety.' },
  { name: 'Venus in 7th (Dispositor)', description: 'Malavya-table. When this engine fires, partner-shared meals nourish deepest. Candlelit dinners, sweet fish, slow Pisces-style cuisine. The shadow: sweet-tooth tilt at the partner-table — pair sweetness with bitter greens.' },

  // ────────────────────────────────────────────────────────────────────────
  // TRANSITS (108)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Transits the 1st House', description: 'Annual peak digestive-fire window. The body radiates warmth; sharp Pitta-digestion handles richer foods than usual. Best month for moderate spice and fuller portions.' },
  { name: 'Sun Transits the 2nd House', description: 'Solar light on voice and mouth. Throat-and-mouth health peaks; vocal projects favored. Eat warm soups for vocal clarity.' },
  { name: 'Sun Transits the 3rd House', description: 'Solar courage on short-burst eating. Quick-cook traditional dishes, speed-prepared protein-rich meals.' },
  { name: 'Sun Transits the 4th House', description: 'Solar fire on Hamsa home-throne. Home-cooking peak window. Learn the family recipe; cook with mother.' },
  { name: 'Sun Transits the 5th House', description: 'Solar fire on creative-discipline. Best window for launching the long-arc dietary protocol; the structured eating regimen.' },
  { name: 'Sun Transits the 6th House', description: 'Solar fire on health-and-conflict. Best month for medical check-ups, dietary corrections, parasite cleanses, gut-restoration protocols.' },
  { name: 'Sun Transits the 7th House', description: 'Solar fire on Malavya partner-table. Anniversary dinners, spouse-cooked meals, candle-lit warm cuisine.' },
  { name: 'Sun Transits the 8th House', description: 'Solar fire in Vipareet chamber. Best window for surgical-style cleansing under guidance; panchakarma; controlled fasting.' },
  { name: 'Sun Transits the 9th House', description: 'Solar light on dharma-detachment. Religious-festival food, ashram cuisine, foreign-spiritual fare.' },
  { name: 'Sun Transits the 10th House', description: 'Career-anxiety peak window — the stomach feels the visibility. Eat lightly, cook warm, drink ginger tea.' },
  { name: 'Sun Transits the 11th House', description: 'Solar fire on emotional-network. Friend-circle dinners, mother-figure-cooked meals, community feasts.' },
  { name: 'Sun Transits the 12th House', description: 'Solar return on retreat-throne. Annual peak for solo-eating practice, ashram cuisine, monastery-style portions, silent meals.' },
  { name: 'Moon Transits the 1st House', description: 'Two-day emotional charge. Body craves comfort food — choose warm Kapha-soothing classics, not cold or raw.' },
  { name: 'Moon Transits the 2nd House', description: 'Emotional charge on mouth-and-voice. Soft warm foods for the throat: porridge, soup, milky-rice.' },
  { name: 'Moon Transits the 3rd House', description: 'Two-day window of warm-eating. Cook with siblings; share warm dishes.' },
  { name: 'Moon Transits the 4th House', description: 'Monthly Hamsa home-throne emotional peak. Cook a real meal at home; the reset compounds.' },
  { name: 'Moon Transits the 5th House', description: 'Emotional charge on creative-eating. Try the recipe you have been postponing.' },
  { name: 'Moon Transits the 6th House', description: 'Emotional charge on health. Listen to the body — what does the gut want today? Adjust accordingly.' },
  { name: 'Moon Transits the 7th House', description: 'Emotional charge on partner-table. Cook with the spouse; share a slow meal.' },
  { name: 'Moon Transits the 8th House', description: 'Emotional weight on the gut. Defer heavy meals; choose simple kichari and soft fruits.' },
  { name: 'Moon Transits the 9th House', description: 'Emotional pull toward dharma-food. Festival cuisine, religious-ceremonial meals, foreign-spiritual fare.' },
  { name: 'Moon Transits the 10th House', description: 'Monthly career-stomach pulse. Eat lightly before public moves; ginger tea before pitches.' },
  { name: 'Moon Transits the 11th House', description: 'Moon\'s own-sign return on gain-throne. Peak monthly emotional-network warmth at the table. Friend-circle dinner; mother-figure visit.' },
  { name: 'Moon Transits the 12th House', description: 'Emotional inwardness; private-meal pull. Cook for yourself slowly; eat in silence.' },
  { name: 'Mercury Transits the 1st House', description: 'Mercury\'s Bhadra return. Peak monthly food-research window. Refine the protocol, adjust the herbal formula, recalibrate the schedule.' },
  { name: 'Mercury Transits the 2nd House', description: 'Sharp money-and-voice articulation. Negotiate the household food-budget; refine the grocery routine.' },
  { name: 'Mercury Transits the 3rd House', description: 'Sharp short-burst food-articulation. Quick-cook traditional dishes, food-blogging, recipe-writing.' },
  { name: 'Mercury Transits the 4th House', description: 'Sharp Hamsa home-throne articulation. Recipe-documentation, family-cookbook compilation, mother-channel cooking lessons.' },
  { name: 'Mercury Transits the 5th House', description: 'Sharp creative-discipline articulation. Long-arc dietary protocol writing, classical-cuisine research.' },
  { name: 'Mercury Transits the 6th House', description: 'Sharp health articulation. Lab-results review, nutrition consultation, allergen-tracking.' },
  { name: 'Mercury Transits the 7th House', description: 'Sharp partnership-eating articulation. Discuss the household food culture; align eating styles.' },
  { name: 'Mercury Transits the 8th House', description: 'Sharp transformation articulation. Detox-protocol writing, cleanse-program planning.' },
  { name: 'Mercury Transits the 9th House', description: 'Sharp dharma articulation. Festival-food planning, ashram-cuisine research, foreign-cooking exploration.' },
  { name: 'Mercury Transits the 10th House', description: 'Sharp career-public articulation. Pre-meeting eating ritual refinement; pitch-day food strategy.' },
  { name: 'Mercury Transits the 11th House', description: 'Sharp wide-network articulation. Friend-circle food-event planning, community-cookbook drafts.' },
  { name: 'Mercury Transits the 12th House', description: 'Sharp behind-the-scenes articulation. Confidential food-protocol design, retreat-meal planning.' },
  { name: 'Venus Transits the 1st House', description: 'Beauty on the body. The skin radiates; sweet-fragrant fruits, rosewater, honey-and-saffron drinks favored.' },
  { name: 'Venus Transits the 2nd House', description: 'Beauty on mouth and voice. Pomegranate, sweet citrus, soft cheese for vocal clarity.' },
  { name: 'Venus Transits the 3rd House', description: 'Beauty on quick-eating. Elegant short-format meals; tea-time rituals.' },
  { name: 'Venus Transits the 4th House', description: 'Beauty on Hamsa home-throne. Aesthetic upgrades to the kitchen; redesign the dining table; soft lighting at meals.' },
  { name: 'Venus Transits the 5th House', description: 'Beauty on creative-eating. Date-night dinners, child-related cake celebrations, refined dessert experiments.' },
  { name: 'Venus Transits the 6th House', description: 'Beauty on health. Soft-restorative foods; chamomile, rose tea, cooling cucumber-water.' },
  { name: 'Venus Transits the 7th House', description: 'Venus on Malavya throne. Peak partner-table month. Sweet-warm dinners, fish, white wines, soft cheese, candlelit fare.' },
  { name: 'Venus Transits the 8th House', description: 'Beauty in transformation chamber. Aesthetic-cleanse protocols; rose-petal-and-honey morning rituals.' },
  { name: 'Venus Transits the 9th House', description: 'Beauty on dharma-food. Festival-cuisine elegance, ashram-food refined, religious-ceremony grace.' },
  { name: 'Venus Transits the 10th House', description: 'Public-aesthetic visibility at the table. Brand-dinner moves, design-led plating, beauty-driven food-presentation.' },
  { name: 'Venus Transits the 11th House', description: 'Beauty on the wide-network table. Friend-circle gala dinners, women-led-network potlucks elegant.' },
  { name: 'Venus Transits the 12th House', description: 'Beauty on retreat-table. Solo elegant dinner, foreign-luxury back-channel meal, monastery-elevated cuisine.' },
  { name: 'Mars Transits the 1st House', description: 'Mars on body-mind. Acidity rises; cool the Pitta with sweet-cooling foods (cucumber, sweet lassi, coconut). Skip alcohol and heavy spice.' },
  { name: 'Mars Transits the 2nd House', description: 'Mars on mouth and money. Sharp sour-spicy foods amplify acidity; reach for sweet-soothing instead.' },
  { name: 'Mars Transits the 3rd House', description: 'Mars on quick-cooking. Bold protein-rich meals, contested ingredient experiments. Watch heat in the body.' },
  { name: 'Mars Transits the 4th House', description: 'Mars on Hamsa home-throne. Family-table friction; cook calmly. Don\'t debate at the dinner table in heat.' },
  { name: 'Mars Transits the 5th House', description: 'Mars on creative-discipline. Bold dietary experiments; contested protocol pivots. Verify with practitioner first.' },
  { name: 'Mars Transits the 6th House', description: 'Mars on health-throne — strong terrain. Best for parasite cleanses, gut-warfare, antimicrobial protocols.' },
  { name: 'Mars Transits the 7th House', description: 'Mars on Malavya partnership. Bold contested partner-eating dynamics. Don\'t fight food-philosophy at the table.' },
  { name: 'Mars Transits the 8th House', description: 'Mars on Vipareet throne. Surgical-style cleanse window — under guidance only.' },
  { name: 'Mars Transits the 9th House', description: 'Mars on dharma-detachment. Bold religious-fasting moves, contested ascetic experiments.' },
  { name: 'Mars Transits the 10th House', description: 'Mars on career-throne. Stress-acidity peaks; sweet-cooling foods are mandatory. Watch coffee intake.' },
  { name: 'Mars Transits the 11th House', description: 'Mars on gain-network. Contested friend-circle food dynamics; bold mother-figure-network meals.' },
  { name: 'Mars Transits the 12th House', description: 'Mars in confidential combat. Hidden food-frictions; address allergens; eliminate the silent irritant.' },
  { name: 'Jupiter Transits the 1st House', description: 'Major year for body-expansion. Discipline portion-control — Jupiter expands the body too. Sattvic cuisine compounds.' },
  { name: 'Jupiter Transits the 2nd House', description: 'Major year for mouth-and-voice expansion. Vocal-project breakthrough; family-recipe inheritance.' },
  { name: 'Jupiter Transits the 3rd House', description: 'Major year for short-format-eating expansion. Recipe-publishing, food-blogging, sibling-channel cuisine.' },
  { name: 'Jupiter Transits the 4th House', description: 'Jupiter on Hamsa home-throne. Peak home-cooking expansion year. Real-estate kitchen-upgrade; family-recipe inheritance.' },
  { name: 'Jupiter Transits the 5th House', description: 'Major year for creative-cuisine expansion. Course-publishing, classical-cuisine breakthrough, child-feeding wisdom.' },
  { name: 'Jupiter Transits the 6th House', description: 'Major year for health-victory. Long chronic-illness resolves; gut-restoration succeeds; protocol-mastery.' },
  { name: 'Jupiter Transits the 7th House', description: 'Major year for partner-table expansion. Spouse-food culture deepens; in-law cooking transmitted.' },
  { name: 'Jupiter Transits the 8th House', description: 'Major year for transformation-cuisine. Cleanse-protocol breakthrough; advanced Ayurvedic chapter; Vipareet gains.' },
  { name: 'Jupiter Transits the 9th House', description: 'Major year for dharma-food expansion. Foreign cuisine breakthrough, ashram-stays, festival-food chapters.' },
  { name: 'Jupiter Transits the 10th House', description: 'Major year for career-public expansion. The body-and-stomach must be disciplined to handle the visibility load.' },
  { name: 'Jupiter Transits the 11th House', description: 'Major year for emotional-network gains at the table. Community-feast leadership, women-led-network catering breakthroughs.' },
  { name: 'Jupiter Transits the 12th House', description: 'Major year for retreat-cuisine. Foreign ashram chapters, monastery-food breakthroughs, off-grid kitchen wisdom.' },
  { name: 'Saturn Transits the 1st House', description: 'Multi-year body-discipline. Vata-Saturn combo intensifies; warm, oily, cooked foods are mandatory. Skip raw-cold-dry.' },
  { name: 'Saturn Transits the 2nd House', description: 'Multi-year discipline on mouth and money. Dental health requires attention; family-food-budget restructures.' },
  { name: 'Saturn Transits the 3rd House', description: 'Multi-year discipline on quick-eating. Long-arc cooking systems formalize; food-routines compound.' },
  { name: 'Saturn Transits the 4th House', description: 'Multi-year discipline on Hamsa home-throne. Kitchen restructuring, family-recipe-archive project, mother\'s-cooking-decline navigation.' },
  { name: 'Saturn Transits the 5th House', description: 'Saturn on its own throne in 5H. Peak structural-discipline-eating chapter of the multi-decade cycle. The 10-year dietary protocol matures; classical-cuisine mastery sets in.' },
  { name: 'Saturn Transits the 6th House', description: 'Saturn\'s strong terrain. Multi-year health-discipline. Long chronic-illness protocols, structural gut-restoration, patient parasite work.' },
  { name: 'Saturn Transits the 7th House', description: 'Multi-year structural test of partner-table. Eating-style alignment with spouse; long disagreements resolve.' },
  { name: 'Saturn Transits the 8th House', description: 'Multi-year reckoning in the gut. Slow cleanse protocols, long-arc Ayurvedic chapters, structural body-restoration.' },
  { name: 'Saturn Transits the 9th House', description: 'Multi-year dharma-eating discipline. Long ascetic-eating chapters, foreign-cuisine mastery, ritual-fasting practice.' },
  { name: 'Saturn Transits the 10th House', description: 'Multi-year career-stress on body. Eat warm-cooked-on-schedule even on the busiest weeks.' },
  { name: 'Saturn Transits the 11th House', description: 'Multi-year discipline on community-table. Friend-circle food-events formalize; women-led-network catering structures.' },
  { name: 'Saturn Transits the 12th House', description: 'Multi-year discipline on solo-eating. Long retreat-cuisine chapters, monastery-portion practice, foreign-confidential meals.' },
  { name: 'Rahu Transits the 1st House', description: 'Eighteen-month obsessive body-reinvention. New diet fevers; verify each protocol with a practitioner.' },
  { name: 'Rahu Transits the 2nd House', description: 'Eighteen-month obsession on mouth-and-money. Sudden food-budget chaos; verify each new ingredient.' },
  { name: 'Rahu Transits the 3rd House', description: 'Rahu on its strong terrain (3H). Eighteen-month obsessive recipe-publishing, viral food-content, controversial cuisine experiments.' },
  { name: 'Rahu Transits the 4th House', description: 'Eighteen-month home-throne obsession. Foreign-cuisine pull, family-recipe-reinvention.' },
  { name: 'Rahu Transits the 5th House', description: 'Eighteen-month obsessive dietary chapter. Speculative-protocol fevers; viral diet-experiments.' },
  { name: 'Rahu Transits the 6th House', description: 'Favorable. Eighteen-month obsessive health-victory chapter. Chronic gut-issues fall.' },
  { name: 'Rahu Transits the 7th House', description: 'Eighteen-month obsessive partner-table chapter. Foreign-spouse cuisine, controversial food-culture clash.' },
  { name: 'Rahu Transits the 8th House', description: 'Eighteen-month obsessive transformation-chapter. Extreme cleanse-protocols, occult-Ayurvedic experiments.' },
  { name: 'Rahu Transits the 9th House', description: 'Eighteen-month foreign-dharma-food obsession. International ashram-stays, controversial fasting cults.' },
  { name: 'Rahu Transits the 10th House', description: 'Eighteen-month career-reinvention obsession. Stress-eating patterns may surface; verify each.' },
  { name: 'Rahu Transits the 11th House', description: 'Eighteen-month obsessive friend-circle-table chapter. Sudden viral-cooking fevers.' },
  { name: 'Rahu Transits the 12th House', description: 'Eighteen-month foreign-confidential food obsession. Hidden mandates, foreign-luxury back-channel cuisine.' },
  { name: 'Ketu Transits the 1st House', description: 'Eighteen-month appetite-stripping. Old eating identity dissolves; sit with the dissolution.' },
  { name: 'Ketu Transits the 2nd House', description: 'Eighteen-month detachment from old food-budget; cravings dissolve.' },
  { name: 'Ketu Transits the 3rd House', description: 'Eighteen-month detachment from quick-cooking habits.' },
  { name: 'Ketu Transits the 4th House', description: 'Eighteen-month home-cooking detachment. Old family-recipes feel finished.' },
  { name: 'Ketu Transits the 5th House', description: 'Eighteen-month creative-eating detachment. Old performance-cuisine loops feel hollow.' },
  { name: 'Ketu Transits the 6th House', description: 'Eighteen-month chronic-symptom detachment. Old gut-issues fade quietly.' },
  { name: 'Ketu Transits the 7th House', description: 'Eighteen-month partner-table detachment. Old shared-food-culture feels finished.' },
  { name: 'Ketu Transits the 8th House', description: 'Eighteen-month transformation-acceleration. Old cleanse-loops evaporate.' },
  { name: 'Ketu Transits the 9th House', description: 'Ketu on its own placement. Peak dharma-food detachment chapter. Old religious-eating attachments dissolve completely.' },
  { name: 'Ketu Transits the 10th House', description: 'Eighteen-month career-stress-eating eclipse. Old anxiety-food patterns feel weightless.' },
  { name: 'Ketu Transits the 11th House', description: 'Eighteen-month wide-network table detachment. Old friend-circle dinners drift.' },
  { name: 'Ketu Transits the 12th House', description: 'Eighteen-month retreat-table detachment. Old solo-meals close.' },

  // ────────────────────────────────────────────────────────────────────────
  // ANGLE ASPECTS (72)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun Aspecting Ascendant (ASC)', description: 'Solar fire on the body. Digestion sharpens; richer foods handled.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Starts', description: 'Body-fire window opens. Begin the slightly heavier protocol.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Exact', description: 'Peak body-fire day. Eat fuller, warmer; the system handles it.' },
  { name: 'Sun Aspecting Ascendant (ASC) : Ends', description: 'Body-fire window closes. Return to lighter eating.' },
  { name: 'Sun Aspecting Midheaven (MC)', description: 'Career-stress window. Eat lightly, warm, on schedule.' },
  { name: 'Sun Aspecting Midheaven (MC) : Starts', description: 'Career-stress window opens. Reduce coffee.' },
  { name: 'Sun Aspecting Midheaven (MC) : Exact', description: 'Peak day. Ginger tea before the pitch; light meal after.' },
  { name: 'Sun Aspecting Midheaven (MC) : Ends', description: 'Career-stress window closes. Return to normal protocol.' },
  { name: 'Moon Aspecting Ascendant (ASC)', description: 'Body-emotion window; comfort-food cravings rise.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Starts', description: 'Comfort-craving window opens. Stock soothing soups.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Choose warm-comfort food over sweet-comfort food.' },
  { name: 'Moon Aspecting Ascendant (ASC) : Ends', description: 'Comfort-craving window closes.' },
  { name: 'Moon Aspecting Midheaven (MC)', description: 'Career-stress emotion window. Eat slower; chew well.' },
  { name: 'Moon Aspecting Midheaven (MC) : Starts', description: 'Career-stress emotion window opens.' },
  { name: 'Moon Aspecting Midheaven (MC) : Exact', description: 'Peak day. Take the warm lunch break alone if possible.' },
  { name: 'Moon Aspecting Midheaven (MC) : Ends', description: 'Career-stress emotion window closes.' },
  { name: 'Mercury Aspecting Ascendant (ASC)', description: 'Mercury\'s Bhadra fire on body. Best for protocol refinement, herbal-formula adjustment.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Starts', description: 'Bhadra-protocol window opens.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Exact', description: 'Peak Bhadra day. Refine the schedule; commit to the new herbal-formula.' },
  { name: 'Mercury Aspecting Ascendant (ASC) : Ends', description: 'Bhadra-protocol window closes.' },
  { name: 'Mercury Aspecting Midheaven (MC)', description: 'Career-articulation window. Coordinate office-eating with a colleague.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Starts', description: 'Career-eating-articulation window opens.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Exact', description: 'Peak day. Plan the pitch-day eating ritual.' },
  { name: 'Mercury Aspecting Midheaven (MC) : Ends', description: 'Career-eating-articulation window closes.' },
  { name: 'Venus Aspecting Ascendant (ASC)', description: 'Beauty on body. Sweet-warm fruits, soft cheese, refined dessert.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Starts', description: 'Venus-body window opens.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Exact', description: 'Peak charm-body day. Eat the elegant warm meal.' },
  { name: 'Venus Aspecting Ascendant (ASC) : Ends', description: 'Venus-body window closes.' },
  { name: 'Venus Aspecting Midheaven (MC)', description: 'Aesthetic public-table window. Brand-dinner moves; design-led plating.' },
  { name: 'Venus Aspecting Midheaven (MC) : Starts', description: 'Aesthetic-table window opens.' },
  { name: 'Venus Aspecting Midheaven (MC) : Exact', description: 'Peak day. Host the elegant client lunch.' },
  { name: 'Venus Aspecting Midheaven (MC) : Ends', description: 'Aesthetic-table window closes.' },
  { name: 'Mars Aspecting Ascendant (ASC)', description: 'Mars on body. Acidity rises; cool with sweet-cucumber-coconut.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Starts', description: 'Mars-body window opens. Reduce spice.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Cool the Pitta with sweet lassi and coconut water.' },
  { name: 'Mars Aspecting Ascendant (ASC) : Ends', description: 'Mars-body window closes.' },
  { name: 'Mars Aspecting Midheaven (MC)', description: 'Stress-acidity peak. Eliminate coffee; switch to ginger or fennel tea.' },
  { name: 'Mars Aspecting Midheaven (MC) : Starts', description: 'Stress-acidity window opens.' },
  { name: 'Mars Aspecting Midheaven (MC) : Exact', description: 'Peak day. Coconut water and cucumber are mandatory.' },
  { name: 'Mars Aspecting Midheaven (MC) : Ends', description: 'Stress-acidity window closes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC)', description: 'Wisdom on body. Sattvic cuisine deepens; ghee-and-rice base nourishes.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Starts', description: 'Sattvic window opens.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Exact', description: 'Peak sattvic day. Cook the traditional grandmother dish.' },
  { name: 'Jupiter Aspecting Ascendant (ASC) : Ends', description: 'Sattvic window closes.' },
  { name: 'Jupiter Aspecting Midheaven (MC)', description: 'Public-elevation window. Body must handle the visibility — discipline portions.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Starts', description: 'Public-eating window opens.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Exact', description: 'Peak day. Eat lightly before the elevation moment.' },
  { name: 'Jupiter Aspecting Midheaven (MC) : Ends', description: 'Public-eating window closes.' },
  { name: 'Saturn Aspecting Ascendant (ASC)', description: 'Saturn on body. Vata pressure peaks; warm, oily, cooked is mandatory.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Starts', description: 'Saturn-body window opens. Skip raw-cold-dry.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Warm sesame-oil massage; warm kichari.' },
  { name: 'Saturn Aspecting Ascendant (ASC) : Ends', description: 'Saturn-body window closes.' },
  { name: 'Saturn Aspecting Midheaven (MC)', description: 'Career-pressure on body. The deadline-week eating discipline matters most now.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Starts', description: 'Career-pressure-body window opens.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Exact', description: 'Peak day. Stick to the protocol; do not skip the warm lunch.' },
  { name: 'Saturn Aspecting Midheaven (MC) : Ends', description: 'Career-pressure-body window closes.' },
  { name: 'Rahu Aspecting Ascendant (ASC)', description: 'Chaotic body-experimentation. Verify each new diet with a practitioner.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Starts', description: 'Body-chaos window opens.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Take the bold protocol — but verify integrity.' },
  { name: 'Rahu Aspecting Ascendant (ASC) : Ends', description: 'Body-chaos window closes.' },
  { name: 'Rahu Aspecting Midheaven (MC)', description: 'Career-chaos eating. Stress-eating obsessions may surface; verify each.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Starts', description: 'Career-chaos-eating window opens.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Don\'t order the controversial new ingredient under stress.' },
  { name: 'Rahu Aspecting Midheaven (MC) : Ends', description: 'Career-chaos-eating window closes.' },
  { name: 'Ketu Aspecting Ascendant (ASC)', description: 'Body-detachment. Old eating identity dissolves.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Starts', description: 'Body-detachment window opens.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Exact', description: 'Peak day. Sit with the appetite quieting; do not force.' },
  { name: 'Ketu Aspecting Ascendant (ASC) : Ends', description: 'Body-detachment window closes.' },
  { name: 'Ketu Aspecting Midheaven (MC)', description: 'Career-stress-eating eclipse. Old anxiety-food patterns feel weightless.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Starts', description: 'Career-stress-eating eclipse window opens.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Exact', description: 'Peak day. Release the old stress-snack ritual.' },
  { name: 'Ketu Aspecting Midheaven (MC) : Ends', description: 'Career-stress-eating eclipse window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // OUTER SPECIALS (8)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Pluto conjunct Saturn', description: 'Generational structural reckoning hitting the long-arc dietary discipline. Old protocols dissolve; the ten-year regimen rebuilds. You emerge with deepened body-wisdom.' },
  { name: 'Pluto conjunct Saturn : Starts', description: 'Multi-year structural reckoning on body-discipline begins.' },
  { name: 'Pluto conjunct Saturn : Exact', description: 'Peak structural-transformation day. Old eating frameworks dissolve.' },
  { name: 'Pluto conjunct Saturn : Ends', description: 'Body-transformation chapter completes.' },
  { name: 'Uranus conjunct Venus', description: 'Sudden disruption hitting the partner-table. Unexpected food-culture pivots, abrupt cuisine reinventions.' },
  { name: 'Uranus conjunct Venus : Starts', description: 'Partner-table disruption window opens.' },
  { name: 'Uranus conjunct Venus : Exact', description: 'Peak partner-table disruption day. The food-philosophy pivot is forced.' },
  { name: 'Uranus conjunct Venus : Ends', description: 'Partner-table disruption window closes.' },

  // ────────────────────────────────────────────────────────────────────────
  // ASPECTS (324)
  // ────────────────────────────────────────────────────────────────────────
  { name: 'Sun aspect Sun in 12th house', description: 'Solar light on retreat-table. Best for solo-eating practice, ashram cuisine, monastery-portion meals.' },
  { name: 'Sun aspect Sun in 12th house : Starts', description: 'Retreat-table window opens.' },
  { name: 'Sun aspect Sun in 12th house : Exact', description: 'Peak day. Eat alone, slowly, in silence.' },
  { name: 'Sun aspect Sun in 12th house : Ends', description: 'Retreat-table window closes.' },
  { name: 'Sun aspect Moon in 11th house', description: 'Solar fire on emotional-network table. Friend-circle dinners, mother-figure-cooked meals.' },
  { name: 'Sun aspect Moon in 11th house : Starts', description: 'Network-table window opens.' },
  { name: 'Sun aspect Moon in 11th house : Exact', description: 'Peak day. Host the friend-circle warm dinner.' },
  { name: 'Sun aspect Moon in 11th house : Ends', description: 'Network-table window closes.' },
  { name: 'Sun aspect Mercury in 1st house', description: 'Solar fire on Bhadra protocol. Best for refining eating-discipline; sharpening the herbal-formula.' },
  { name: 'Sun aspect Mercury in 1st house : Starts', description: 'Bhadra-protocol-fire window opens.' },
  { name: 'Sun aspect Mercury in 1st house : Exact', description: 'Peak day. Commit to the new protocol; the body responds to clear instruction.' },
  { name: 'Sun aspect Mercury in 1st house : Ends', description: 'Bhadra-protocol-fire window closes.' },
  { name: 'Sun aspect Venus in 7th house', description: 'Solar fire on Malavya partner-table. Anniversary dinner, candlelit warm cuisine, sweet-Pisces fare.' },
  { name: 'Sun aspect Venus in 7th house : Starts', description: 'Malavya-table-fire window opens.' },
  { name: 'Sun aspect Venus in 7th house : Exact', description: 'Peak Malavya-meal day. Host the partner-led celebratory meal.' },
  { name: 'Sun aspect Venus in 7th house : Ends', description: 'Malavya-table-fire window closes.' },
  { name: 'Sun aspect Mars in 8th house', description: 'Solar fire on Vipareet engine. Surgical-cleanse window — under guidance.' },
  { name: 'Sun aspect Mars in 8th house : Starts', description: 'Vipareet-cleanse window opens.' },
  { name: 'Sun aspect Mars in 8th house : Exact', description: 'Peak day. Take the structured cleanse with practitioner support.' },
  { name: 'Sun aspect Mars in 8th house : Ends', description: 'Vipareet-cleanse window closes.' },
  { name: 'Sun aspect Jupiter in 4th house', description: 'Solar fire on Hamsa home-throne. Home-cooking peak window; learn the family recipe.' },
  { name: 'Sun aspect Jupiter in 4th house : Starts', description: 'Hamsa-table-fire window opens.' },
  { name: 'Sun aspect Jupiter in 4th house : Exact', description: 'Peak Hamsa-meal day. Cook the multi-generational recipe.' },
  { name: 'Sun aspect Jupiter in 4th house : Ends', description: 'Hamsa-table-fire window closes.' },
  { name: 'Sun aspect Saturn in 5th house', description: 'Solar fire on creative-discipline-eating. Best for launching the long-arc protocol.' },
  { name: 'Sun aspect Saturn in 5th house : Starts', description: 'Creative-discipline-fire window opens.' },
  { name: 'Sun aspect Saturn in 5th house : Exact', description: 'Peak day. Begin the multi-month dietary regimen.' },
  { name: 'Sun aspect Saturn in 5th house : Ends', description: 'Creative-discipline-fire window closes.' },
  { name: 'Sun aspect Rahu in 3rd house', description: 'Solar fire on viral-cuisine zone. Verify each new ingredient before adopting.' },
  { name: 'Sun aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-fire window opens.' },
  { name: 'Sun aspect Rahu in 3rd house : Exact', description: 'Peak day. Take the bold cuisine-experiment with practitioner verification.' },
  { name: 'Sun aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-fire window closes.' },
  { name: 'Sun aspect Ketu in 9th house', description: 'Solar light on dharma-detachment. Old religious-fasting attachments dissolve.' },
  { name: 'Sun aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-fire window opens.' },
  { name: 'Sun aspect Ketu in 9th house : Exact', description: 'Peak day. Release the old fasting-cult or ritual-diet that has been hollow.' },
  { name: 'Sun aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-fire window closes.' },
  { name: 'Moon aspect Sun in 12th house', description: 'Emotional charge on retreat-table. Quiet meals heal.' },
  { name: 'Moon aspect Sun in 12th house : Starts', description: 'Retreat-emotion window opens.' },
  { name: 'Moon aspect Sun in 12th house : Exact', description: 'Peak day. Eat alone in silence; let the meal be sacred.' },
  { name: 'Moon aspect Sun in 12th house : Ends', description: 'Retreat-emotion window closes.' },
  { name: 'Moon aspect Moon in 11th house', description: 'Moon\'s own-sign return. Peak emotional-network warmth at the table.' },
  { name: 'Moon aspect Moon in 11th house : Starts', description: 'Network-emotion window opens.' },
  { name: 'Moon aspect Moon in 11th house : Exact', description: 'Peak day. Host or attend the friend-circle warm meal.' },
  { name: 'Moon aspect Moon in 11th house : Ends', description: 'Network-emotion window closes.' },
  { name: 'Moon aspect Mercury in 1st house', description: 'Emotional warmth on Bhadra protocol. Soft adjustments to the regimen.' },
  { name: 'Moon aspect Mercury in 1st house : Starts', description: 'Bhadra-emotion window opens.' },
  { name: 'Moon aspect Mercury in 1st house : Exact', description: 'Peak day. Take the warm consultation about your protocol.' },
  { name: 'Moon aspect Mercury in 1st house : Ends', description: 'Bhadra-emotion window closes.' },
  { name: 'Moon aspect Venus in 7th house', description: 'Emotional charge on Malavya partner-table. Cook with the spouse.' },
  { name: 'Moon aspect Venus in 7th house : Starts', description: 'Malavya-emotion window opens.' },
  { name: 'Moon aspect Venus in 7th house : Exact', description: 'Peak day. Cook a warm meal together; eat slowly.' },
  { name: 'Moon aspect Venus in 7th house : Ends', description: 'Malavya-emotion window closes.' },
  { name: 'Moon aspect Mars in 8th house', description: 'Emotional weight on the gut. Defer heavy meals; choose simple kichari.' },
  { name: 'Moon aspect Mars in 8th house : Starts', description: 'Gut-emotion window opens.' },
  { name: 'Moon aspect Mars in 8th house : Exact', description: 'Peak day. Eat soft, simple, soothing food only.' },
  { name: 'Moon aspect Mars in 8th house : Ends', description: 'Gut-emotion window closes.' },
  { name: 'Moon aspect Jupiter in 4th house', description: 'Emotional warmth on Hamsa home-throne. Mother-channel cooking.' },
  { name: 'Moon aspect Jupiter in 4th house : Starts', description: 'Hamsa-emotion window opens.' },
  { name: 'Moon aspect Jupiter in 4th house : Exact', description: 'Peak day. Cook the family recipe; visit mother.' },
  { name: 'Moon aspect Jupiter in 4th house : Ends', description: 'Hamsa-emotion window closes.' },
  { name: 'Moon aspect Saturn in 5th house', description: 'Emotional weight on dietary-discipline. The long protocol feels heavy; honor the slow body-arc.' },
  { name: 'Moon aspect Saturn in 5th house : Starts', description: 'Dietary-discipline-emotion window opens.' },
  { name: 'Moon aspect Saturn in 5th house : Exact', description: 'Peak day. Sit with the dietary heaviness; do not break the protocol from emotion.' },
  { name: 'Moon aspect Saturn in 5th house : Ends', description: 'Dietary-discipline-emotion window closes.' },
  { name: 'Moon aspect Rahu in 3rd house', description: 'Emotional swing on viral-cuisine. Cravings rise; verify before indulging.' },
  { name: 'Moon aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-emotion window opens.' },
  { name: 'Moon aspect Rahu in 3rd house : Exact', description: 'Peak day. Defer the bold food-experiment two days.' },
  { name: 'Moon aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-emotion window closes.' },
  { name: 'Moon aspect Ketu in 9th house', description: 'Emotional detachment from dharma-food. Old religious-eating attachments quietly dissolve.' },
  { name: 'Moon aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-emotion window opens.' },
  { name: 'Moon aspect Ketu in 9th house : Exact', description: 'Peak day. Release the old ritual-fast that has felt hollow.' },
  { name: 'Moon aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-emotion window closes.' },
  { name: 'Mercury aspect Sun in 12th house', description: 'Sharp articulation of retreat-table. Confidential food-protocols, retreat-meal planning.' },
  { name: 'Mercury aspect Sun in 12th house : Starts', description: 'Retreat-articulation window opens.' },
  { name: 'Mercury aspect Sun in 12th house : Exact', description: 'Peak day. Plan the silent-meal routine; design the retreat-week menu.' },
  { name: 'Mercury aspect Sun in 12th house : Ends', description: 'Retreat-articulation window closes.' },
  { name: 'Mercury aspect Moon in 11th house', description: 'Sharp articulation on emotional-network table. Friend-circle food-event planning.' },
  { name: 'Mercury aspect Moon in 11th house : Starts', description: 'Network-articulation window opens.' },
  { name: 'Mercury aspect Moon in 11th house : Exact', description: 'Peak day. Plan the warm community feast.' },
  { name: 'Mercury aspect Moon in 11th house : Ends', description: 'Network-articulation window closes.' },
  { name: 'Mercury aspect Mercury in 1st house', description: 'Mercury\'s Bhadra return. Peak food-research day. Refine the protocol; sharpen the herbal-formula.' },
  { name: 'Mercury aspect Mercury in 1st house : Starts', description: 'Bhadra-research peak window opens.' },
  { name: 'Mercury aspect Mercury in 1st house : Exact', description: 'Peak Bhadra day. Lock in the year\'s dietary-regimen design.' },
  { name: 'Mercury aspect Mercury in 1st house : Ends', description: 'Bhadra-research peak window closes.' },
  { name: 'Mercury aspect Venus in 7th house', description: 'Sharp Malavya partner-table articulation. Discuss the household food culture; align eating styles.' },
  { name: 'Mercury aspect Venus in 7th house : Starts', description: 'Partner-table-articulation window opens.' },
  { name: 'Mercury aspect Venus in 7th house : Exact', description: 'Peak day. Plan the household menu together for the next month.' },
  { name: 'Mercury aspect Venus in 7th house : Ends', description: 'Partner-table-articulation window closes.' },
  { name: 'Mercury aspect Mars in 8th house', description: 'Sharp Vipareet articulation. Cleanse-protocol writing, surgical-fasting planning.' },
  { name: 'Mercury aspect Mars in 8th house : Starts', description: 'Vipareet-articulation window opens.' },
  { name: 'Mercury aspect Mars in 8th house : Exact', description: 'Peak day. Plan the cleanse precisely; document each ingredient.' },
  { name: 'Mercury aspect Mars in 8th house : Ends', description: 'Vipareet-articulation window closes.' },
  { name: 'Mercury aspect Jupiter in 4th house', description: 'Sharp Hamsa home-throne articulation. Recipe-documentation, family-cookbook compilation.' },
  { name: 'Mercury aspect Jupiter in 4th house : Starts', description: 'Hamsa-articulation window opens.' },
  { name: 'Mercury aspect Jupiter in 4th house : Exact', description: 'Peak day. Document the family recipes; record mother\'s cooking lessons.' },
  { name: 'Mercury aspect Jupiter in 4th house : Ends', description: 'Hamsa-articulation window closes.' },
  { name: 'Mercury aspect Saturn in 5th house', description: 'Sharp creative-discipline articulation. Long-arc dietary protocol writing.' },
  { name: 'Mercury aspect Saturn in 5th house : Starts', description: 'Creative-discipline-articulation window opens.' },
  { name: 'Mercury aspect Saturn in 5th house : Exact', description: 'Peak day. Draft the multi-month regimen plan.' },
  { name: 'Mercury aspect Saturn in 5th house : Ends', description: 'Creative-discipline-articulation window closes.' },
  { name: 'Mercury aspect Rahu in 3rd house', description: 'Sharp viral-cuisine articulation. Recipe-publishing, food-blogging.' },
  { name: 'Mercury aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-articulation window opens.' },
  { name: 'Mercury aspect Rahu in 3rd house : Exact', description: 'Peak day. Publish the recipe — but verify the ingredient claims.' },
  { name: 'Mercury aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-articulation window closes.' },
  { name: 'Mercury aspect Ketu in 9th house', description: 'Sharp dharma-detachment articulation. Audit religious-food attachments; release.' },
  { name: 'Mercury aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-articulation window opens.' },
  { name: 'Mercury aspect Ketu in 9th house : Exact', description: 'Peak day. Write the closure note to the old ritual-diet.' },
  { name: 'Mercury aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-articulation window closes.' },
  { name: 'Venus aspect Sun in 12th house', description: 'Beauty on retreat-table. Solo elegant dinner; foreign-luxury back-channel meal.' },
  { name: 'Venus aspect Sun in 12th house : Starts', description: 'Retreat-table-beauty window opens.' },
  { name: 'Venus aspect Sun in 12th house : Exact', description: 'Peak day. Host the elegant private dinner alone.' },
  { name: 'Venus aspect Sun in 12th house : Ends', description: 'Retreat-table-beauty window closes.' },
  { name: 'Venus aspect Moon in 11th house', description: 'Beauty on emotional-network. Friend-circle gala dinners.' },
  { name: 'Venus aspect Moon in 11th house : Starts', description: 'Network-beauty window opens.' },
  { name: 'Venus aspect Moon in 11th house : Exact', description: 'Peak day. Host the elegant friend-circle warm dinner.' },
  { name: 'Venus aspect Moon in 11th house : Ends', description: 'Network-beauty window closes.' },
  { name: 'Venus aspect Mercury in 1st house', description: 'Beauty on Bhadra protocol. Refine the aesthetic of the meal; design the plating.' },
  { name: 'Venus aspect Mercury in 1st house : Starts', description: 'Bhadra-beauty window opens.' },
  { name: 'Venus aspect Mercury in 1st house : Exact', description: 'Peak day. Polish the protocol; design the elegant meal-presentation.' },
  { name: 'Venus aspect Mercury in 1st house : Ends', description: 'Bhadra-beauty window closes.' },
  { name: 'Venus aspect Venus in 7th house', description: 'Venus on Malavya throne. Peak partner-table grace day. Sweet-warm dinner; fish; soft cheese; candle-lit.' },
  { name: 'Venus aspect Venus in 7th house : Starts', description: 'Malavya peak window opens.' },
  { name: 'Venus aspect Venus in 7th house : Exact', description: 'Peak Malavya-meal day. Host the elegant warm partner-meal.' },
  { name: 'Venus aspect Venus in 7th house : Ends', description: 'Malavya peak window closes.' },
  { name: 'Venus aspect Mars in 8th house', description: 'Beauty in Vipareet chamber. Aesthetic-cleanse protocols; rose-and-honey morning rituals.' },
  { name: 'Venus aspect Mars in 8th house : Starts', description: 'Vipareet-beauty window opens.' },
  { name: 'Venus aspect Mars in 8th house : Exact', description: 'Peak day. Design the elegant cleanse; soften the surgical regimen.' },
  { name: 'Venus aspect Mars in 8th house : Ends', description: 'Vipareet-beauty window closes.' },
  { name: 'Venus aspect Jupiter in 4th house', description: 'Beauty on Hamsa home-throne. Kitchen redesign, dining table aesthetics, soft lighting at meals.' },
  { name: 'Venus aspect Jupiter in 4th house : Starts', description: 'Hamsa-beauty window opens.' },
  { name: 'Venus aspect Jupiter in 4th house : Exact', description: 'Peak day. Redesign the kitchen aesthetic; host the warm family meal.' },
  { name: 'Venus aspect Jupiter in 4th house : Ends', description: 'Hamsa-beauty window closes.' },
  { name: 'Venus aspect Saturn in 5th house', description: 'Beauty on creative-discipline-eating. Polished long-arc regimen, elegant classical-cuisine.' },
  { name: 'Venus aspect Saturn in 5th house : Starts', description: 'Creative-discipline-beauty window opens.' },
  { name: 'Venus aspect Saturn in 5th house : Exact', description: 'Peak day. Polish the regimen-presentation; refine the classical-cuisine practice.' },
  { name: 'Venus aspect Saturn in 5th house : Ends', description: 'Creative-discipline-beauty window closes.' },
  { name: 'Venus aspect Rahu in 3rd house', description: 'Beauty on viral-cuisine zone. Polished recipe-publishing, elegant food-blogging — verify integrity.' },
  { name: 'Venus aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-beauty window opens.' },
  { name: 'Venus aspect Rahu in 3rd house : Exact', description: 'Peak day. Polish the food-content; verify ingredient claims.' },
  { name: 'Venus aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-beauty window closes.' },
  { name: 'Venus aspect Ketu in 9th house', description: 'Beauty on dharma-food-detachment. Old festival-food aesthetic feels weightless.' },
  { name: 'Venus aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-beauty window opens.' },
  { name: 'Venus aspect Ketu in 9th house : Exact', description: 'Peak day. Release the old festival-food ritual that has been hollow.' },
  { name: 'Venus aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-beauty window closes.' },
  { name: 'Mars aspect Sun in 12th house', description: 'Mars on retreat-table. Solo-meal aggression; eat slower than usual.' },
  { name: 'Mars aspect Sun in 12th house : Starts', description: 'Retreat-fire window opens.' },
  { name: 'Mars aspect Sun in 12th house : Exact', description: 'Peak day. Slow the solo-meal; chew thoroughly.' },
  { name: 'Mars aspect Sun in 12th house : Ends', description: 'Retreat-fire window closes.' },
  { name: 'Mars aspect Moon in 11th house', description: 'Mars on community-table. Contested friend-circle food dynamics.' },
  { name: 'Mars aspect Moon in 11th house : Starts', description: 'Community-fire window opens.' },
  { name: 'Mars aspect Moon in 11th house : Exact', description: 'Peak day. Don\'t debate at the friend-circle dinner table.' },
  { name: 'Mars aspect Moon in 11th house : Ends', description: 'Community-fire window closes.' },
  { name: 'Mars aspect Mercury in 1st house', description: 'Mars on Bhadra protocol. Bold dietary experiments; verify with practitioner.' },
  { name: 'Mars aspect Mercury in 1st house : Starts', description: 'Bhadra-fire window opens.' },
  { name: 'Mars aspect Mercury in 1st house : Exact', description: 'Peak day. Take the bold protocol-pivot — under guidance only.' },
  { name: 'Mars aspect Mercury in 1st house : Ends', description: 'Bhadra-fire window closes.' },
  { name: 'Mars aspect Venus in 7th house', description: 'Mars on Malavya partner-table. Contested eating-style dynamics with spouse.' },
  { name: 'Mars aspect Venus in 7th house : Starts', description: 'Partner-table-fire window opens.' },
  { name: 'Mars aspect Venus in 7th house : Exact', description: 'Peak day. Don\'t fight food-philosophy at the table; defer the debate.' },
  { name: 'Mars aspect Venus in 7th house : Ends', description: 'Partner-table-fire window closes.' },
  { name: 'Mars aspect Mars in 8th house', description: 'Mars on its own Vipareet throne. Peak surgical-cleanse window — under qualified guidance only.' },
  { name: 'Mars aspect Mars in 8th house : Starts', description: 'Vipareet-cleanse peak window opens.' },
  { name: 'Mars aspect Mars in 8th house : Exact', description: 'Peak Vipareet day. Take the structured panchakarma; the body responds powerfully now.' },
  { name: 'Mars aspect Mars in 8th house : Ends', description: 'Vipareet-cleanse peak window closes.' },
  { name: 'Mars aspect Jupiter in 4th house', description: 'Mars on Hamsa home-throne. Family-table friction; cook calmly.' },
  { name: 'Mars aspect Jupiter in 4th house : Starts', description: 'Hamsa-fire window opens.' },
  { name: 'Mars aspect Jupiter in 4th house : Exact', description: 'Peak day. Defer the family debate; eat in peace.' },
  { name: 'Mars aspect Jupiter in 4th house : Ends', description: 'Hamsa-fire window closes.' },
  { name: 'Mars aspect Saturn in 5th house', description: 'Mars on creative-discipline-eating. Bold dietary experiments; contested protocol pivots.' },
  { name: 'Mars aspect Saturn in 5th house : Starts', description: 'Creative-discipline-fire window opens.' },
  { name: 'Mars aspect Saturn in 5th house : Exact', description: 'Peak day. Take the bold protocol-revision under practitioner guidance.' },
  { name: 'Mars aspect Saturn in 5th house : Ends', description: 'Creative-discipline-fire window closes.' },
  { name: 'Mars aspect Rahu in 3rd house', description: 'Mars on viral-cuisine zone. Bold contested ingredient-experiments.' },
  { name: 'Mars aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-fire window opens.' },
  { name: 'Mars aspect Rahu in 3rd house : Exact', description: 'Peak day. Vet the bold ingredient before adoption.' },
  { name: 'Mars aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-fire window closes.' },
  { name: 'Mars aspect Ketu in 9th house', description: 'Mars on dharma-detachment. Forceful release of religious-fasting attachments.' },
  { name: 'Mars aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-fire window opens.' },
  { name: 'Mars aspect Ketu in 9th house : Exact', description: 'Peak day. Forcefully close the old fasting-cult or ritual-diet.' },
  { name: 'Mars aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-fire window closes.' },
  { name: 'Jupiter aspect Sun in 12th house', description: 'Wisdom on retreat-table. Foreign-ashram cuisine, monastery-food breakthroughs.' },
  { name: 'Jupiter aspect Sun in 12th house : Starts', description: 'Retreat-expansion window opens.' },
  { name: 'Jupiter aspect Sun in 12th house : Exact', description: 'Peak day. Take the foreign-ashram-stay; let the monastery cuisine teach.' },
  { name: 'Jupiter aspect Sun in 12th house : Ends', description: 'Retreat-expansion window closes.' },
  { name: 'Jupiter aspect Moon in 11th house', description: 'Wisdom on emotional-network table. Community-feast leadership; women-led-network catering.' },
  { name: 'Jupiter aspect Moon in 11th house : Starts', description: 'Network-expansion window opens.' },
  { name: 'Jupiter aspect Moon in 11th house : Exact', description: 'Peak day. Lead the warm community feast; accept the catering invitation.' },
  { name: 'Jupiter aspect Moon in 11th house : Ends', description: 'Network-expansion window closes.' },
  { name: 'Jupiter aspect Mercury in 1st house', description: 'Wisdom on Bhadra protocol. Body-mastery elevation; advanced herbal-formula breakthrough.' },
  { name: 'Jupiter aspect Mercury in 1st house : Starts', description: 'Bhadra-expansion window opens.' },
  { name: 'Jupiter aspect Mercury in 1st house : Exact', description: 'Peak day. Accept the body-mastery elevation; integrate the advanced protocol.' },
  { name: 'Jupiter aspect Mercury in 1st house : Ends', description: 'Bhadra-expansion window closes.' },
  { name: 'Jupiter aspect Venus in 7th house', description: 'Wisdom on Malavya partner-table. In-law cooking transmission, spouse-food-culture deepening.' },
  { name: 'Jupiter aspect Venus in 7th house : Starts', description: 'Malavya-expansion window opens.' },
  { name: 'Jupiter aspect Venus in 7th house : Exact', description: 'Peak day. Learn the in-law family recipe; deepen partner-cuisine.' },
  { name: 'Jupiter aspect Venus in 7th house : Ends', description: 'Malavya-expansion window closes.' },
  { name: 'Jupiter aspect Mars in 8th house', description: 'Wisdom on Vipareet engine. Cleanse-protocol breakthrough; advanced Ayurvedic mastery.' },
  { name: 'Jupiter aspect Mars in 8th house : Starts', description: 'Vipareet-expansion window opens.' },
  { name: 'Jupiter aspect Mars in 8th house : Exact', description: 'Peak day. Take the advanced cleanse with master-practitioner guidance.' },
  { name: 'Jupiter aspect Mars in 8th house : Ends', description: 'Vipareet-expansion window closes.' },
  { name: 'Jupiter aspect Jupiter in 4th house', description: 'Jupiter on Hamsa throne. Peak home-cooking expansion day. Kitchen-upgrade; family-recipe-archive breakthrough.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Starts', description: 'Hamsa peak window opens.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Exact', description: 'Peak Hamsa day. Upgrade the kitchen; archive the family recipes.' },
  { name: 'Jupiter aspect Jupiter in 4th house : Ends', description: 'Hamsa peak window closes.' },
  { name: 'Jupiter aspect Saturn in 5th house', description: 'Wisdom on creative-discipline-eating. Long-arc protocol breakthrough; classical-cuisine mastery.' },
  { name: 'Jupiter aspect Saturn in 5th house : Starts', description: 'Creative-discipline-expansion window opens.' },
  { name: 'Jupiter aspect Saturn in 5th house : Exact', description: 'Peak day. Formalize the multi-year regimen; teach what you have mastered.' },
  { name: 'Jupiter aspect Saturn in 5th house : Ends', description: 'Creative-discipline-expansion window closes.' },
  { name: 'Jupiter aspect Rahu in 3rd house', description: 'Wisdom on viral-cuisine. Recipe-publishing breakthroughs; food-content platform elevation.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-expansion window opens.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Exact', description: 'Peak day. Take the food-content platform elevation; integrate ethical bedrock.' },
  { name: 'Jupiter aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-expansion window closes.' },
  { name: 'Jupiter aspect Ketu in 9th house', description: 'Wisdom on dharma-food-detachment. The released fasting-cult becomes its own teaching.' },
  { name: 'Jupiter aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-expansion window opens.' },
  { name: 'Jupiter aspect Ketu in 9th house : Exact', description: 'Peak day. Convert the released ritual-diet into your own balanced practice.' },
  { name: 'Jupiter aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-expansion window closes.' },
  { name: 'Saturn aspect Sun in 12th house', description: 'Structural pressure on retreat-table. Long monastery-food chapters; slow ascetic eating.' },
  { name: 'Saturn aspect Sun in 12th house : Starts', description: 'Retreat-discipline window opens.' },
  { name: 'Saturn aspect Sun in 12th house : Exact', description: 'Peak day. Commit to the long ascetic-meal practice.' },
  { name: 'Saturn aspect Sun in 12th house : Ends', description: 'Retreat-discipline window closes.' },
  { name: 'Saturn aspect Moon in 11th house', description: 'Structural pressure on community-table. Friend-circle food-events formalize.' },
  { name: 'Saturn aspect Moon in 11th house : Starts', description: 'Community-discipline window opens.' },
  { name: 'Saturn aspect Moon in 11th house : Exact', description: 'Peak day. Sign the long-arc community-cookbook charter.' },
  { name: 'Saturn aspect Moon in 11th house : Ends', description: 'Community-discipline window closes.' },
  { name: 'Saturn aspect Mercury in 1st house', description: 'Structural pressure on Bhadra protocol. Slow body-evolution; vanity-fitness goals fall away.' },
  { name: 'Saturn aspect Mercury in 1st house : Starts', description: 'Bhadra-discipline window opens.' },
  { name: 'Saturn aspect Mercury in 1st house : Exact', description: 'Peak day. Eliminate vanity-protocol goals; lock in the durable regimen.' },
  { name: 'Saturn aspect Mercury in 1st house : Ends', description: 'Bhadra-discipline window closes.' },
  { name: 'Saturn aspect Venus in 7th house', description: 'Structural pressure on Malavya partner-table. Eating-style alignment with spouse formalizes.' },
  { name: 'Saturn aspect Venus in 7th house : Starts', description: 'Partner-table-discipline window opens.' },
  { name: 'Saturn aspect Venus in 7th house : Exact', description: 'Peak day. Lock in the household food-culture for the long term.' },
  { name: 'Saturn aspect Venus in 7th house : Ends', description: 'Partner-table-discipline window closes.' },
  { name: 'Saturn aspect Mars in 8th house', description: 'Structural pressure on Vipareet engine. Slow cleanse protocols, long-arc Ayurvedic chapters.' },
  { name: 'Saturn aspect Mars in 8th house : Starts', description: 'Vipareet-discipline window opens.' },
  { name: 'Saturn aspect Mars in 8th house : Exact', description: 'Peak day. Hold the line on the slow body-restoration regimen.' },
  { name: 'Saturn aspect Mars in 8th house : Ends', description: 'Vipareet-discipline window closes.' },
  { name: 'Saturn aspect Jupiter in 4th house', description: 'Structural pressure on Hamsa home-throne. Kitchen restructuring, family-recipe-archive project.' },
  { name: 'Saturn aspect Jupiter in 4th house : Starts', description: 'Hamsa-discipline window opens.' },
  { name: 'Saturn aspect Jupiter in 4th house : Exact', description: 'Peak day. Restructure the kitchen; document the family recipes.' },
  { name: 'Saturn aspect Jupiter in 4th house : Ends', description: 'Hamsa-discipline window closes.' },
  { name: 'Saturn aspect Saturn in 5th house', description: 'Saturn on its own creative throne. Peak structural-discipline-eating day of the multi-decade cycle. The 10-year regimen matures fully.' },
  { name: 'Saturn aspect Saturn in 5th house : Starts', description: 'Saturn-discipline peak window opens.' },
  { name: 'Saturn aspect Saturn in 5th house : Exact', description: 'Peak day. Lock in the multi-decade regimen; teach what you have mastered.' },
  { name: 'Saturn aspect Saturn in 5th house : Ends', description: 'Saturn-discipline peak window closes.' },
  { name: 'Saturn aspect Rahu in 3rd house', description: 'Structural pressure on viral-cuisine zone. Long-arc food-content discipline; chaotic recipe-channel formalizes.' },
  { name: 'Saturn aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-discipline window opens.' },
  { name: 'Saturn aspect Rahu in 3rd house : Exact', description: 'Peak day. Lock in the multi-year recipe-publishing schedule.' },
  { name: 'Saturn aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-discipline window closes.' },
  { name: 'Saturn aspect Ketu in 9th house', description: 'Structural pressure on dharma-food detachment. Old festival-food rituals formally close.' },
  { name: 'Saturn aspect Ketu in 9th house : Starts', description: 'Dharma-detachment-discipline window opens.' },
  { name: 'Saturn aspect Ketu in 9th house : Exact', description: 'Peak day. Sign the formal closure of the dead ritual-diet.' },
  { name: 'Saturn aspect Ketu in 9th house : Ends', description: 'Dharma-detachment-discipline window closes.' },
  { name: 'Rahu aspect Sun in 12th house', description: 'Chaotic expansion on retreat-table. Foreign-ashram fevers, controversial monastery-cuisine.' },
  { name: 'Rahu aspect Sun in 12th house : Starts', description: 'Retreat-chaos window opens.' },
  { name: 'Rahu aspect Sun in 12th house : Exact', description: 'Peak day. Vet the foreign-ashram before traveling.' },
  { name: 'Rahu aspect Sun in 12th house : Ends', description: 'Retreat-chaos window closes.' },
  { name: 'Rahu aspect Moon in 11th house', description: 'Chaotic expansion on community-table. Sudden viral-feast pulls; controversial cooperative-platform meals.' },
  { name: 'Rahu aspect Moon in 11th house : Starts', description: 'Community-chaos window opens.' },
  { name: 'Rahu aspect Moon in 11th house : Exact', description: 'Peak day. Vet the controversial community-meal before attending.' },
  { name: 'Rahu aspect Moon in 11th house : Ends', description: 'Community-chaos window closes.' },
  { name: 'Rahu aspect Mercury in 1st house', description: 'Chaotic expansion on Bhadra protocol. Sudden body-experiment fevers; verify each.' },
  { name: 'Rahu aspect Mercury in 1st house : Starts', description: 'Bhadra-chaos window opens.' },
  { name: 'Rahu aspect Mercury in 1st house : Exact', description: 'Peak day. Take the bold body-experiment with practitioner guidance.' },
  { name: 'Rahu aspect Mercury in 1st house : Ends', description: 'Bhadra-chaos window closes.' },
  { name: 'Rahu aspect Venus in 7th house', description: 'Chaotic expansion on Malavya partner-table. Foreign-cuisine pulls; controversial spouse-food-culture clashes.' },
  { name: 'Rahu aspect Venus in 7th house : Starts', description: 'Partner-table-chaos window opens.' },
  { name: 'Rahu aspect Venus in 7th house : Exact', description: 'Peak day. Vet the controversial partner-cuisine experiment thoroughly.' },
  { name: 'Rahu aspect Venus in 7th house : Ends', description: 'Partner-table-chaos window closes.' },
  { name: 'Rahu aspect Mars in 8th house', description: 'Chaotic expansion on Vipareet engine. Extreme cleanse-protocols, occult-Ayurvedic experiments.' },
  { name: 'Rahu aspect Mars in 8th house : Starts', description: 'Vipareet-chaos window opens.' },
  { name: 'Rahu aspect Mars in 8th house : Exact', description: 'Peak day. Take the extreme cleanse only with qualified guidance.' },
  { name: 'Rahu aspect Mars in 8th house : Ends', description: 'Vipareet-chaos window closes.' },
  { name: 'Rahu aspect Jupiter in 4th house', description: 'Chaotic expansion on Hamsa home-throne. Foreign-cuisine fevers; family-recipe reinvention.' },
  { name: 'Rahu aspect Jupiter in 4th house : Starts', description: 'Hamsa-chaos window opens.' },
  { name: 'Rahu aspect Jupiter in 4th house : Exact', description: 'Peak day. Vet the foreign-cuisine experiment before integrating into family meals.' },
  { name: 'Rahu aspect Jupiter in 4th house : Ends', description: 'Hamsa-chaos window closes.' },
  { name: 'Rahu aspect Saturn in 5th house', description: 'Chaotic expansion on creative-discipline-eating. Speculative-protocol fevers.' },
  { name: 'Rahu aspect Saturn in 5th house : Starts', description: 'Creative-chaos window opens.' },
  { name: 'Rahu aspect Saturn in 5th house : Exact', description: 'Peak day. Take the speculative-protocol move with full practitioner verification.' },
  { name: 'Rahu aspect Saturn in 5th house : Ends', description: 'Creative-chaos window closes.' },
  { name: 'Rahu aspect Rahu in 3rd house', description: 'Rahu return on its own placement. Peak viral-cuisine day. Recipe-publishing opportunity at maximum amplitude — and risk.' },
  { name: 'Rahu aspect Rahu in 3rd house : Starts', description: 'Rahu-return cuisine window opens.' },
  { name: 'Rahu aspect Rahu in 3rd house : Exact', description: 'Peak Rahu-return day. Push the bold recipe — verify ingredient claims.' },
  { name: 'Rahu aspect Rahu in 3rd house : Ends', description: 'Rahu-return cuisine window closes.' },
  { name: 'Rahu aspect Ketu in 9th house', description: 'Rahu-Ketu axis return on dharma-food. Peak ritual-diet turbulence.' },
  { name: 'Rahu aspect Ketu in 9th house : Starts', description: 'Axis-chaos window opens.' },
  { name: 'Rahu aspect Ketu in 9th house : Exact', description: 'Peak day. Defer dharma-food decisions; the axis is too loud.' },
  { name: 'Rahu aspect Ketu in 9th house : Ends', description: 'Axis-chaos window closes.' },
  { name: 'Ketu aspect Sun in 12th house', description: 'Detachment on retreat-table. Old solo-meal cravings dissolve.' },
  { name: 'Ketu aspect Sun in 12th house : Starts', description: 'Retreat-detachment window opens.' },
  { name: 'Ketu aspect Sun in 12th house : Exact', description: 'Peak day. Sit with the solo-meal feeling weightless.' },
  { name: 'Ketu aspect Sun in 12th house : Ends', description: 'Retreat-detachment window closes.' },
  { name: 'Ketu aspect Moon in 11th house', description: 'Detachment on community-table. Old friend-circle dinners drift.' },
  { name: 'Ketu aspect Moon in 11th house : Starts', description: 'Community-detachment window opens.' },
  { name: 'Ketu aspect Moon in 11th house : Exact', description: 'Peak day. Release the old community-feast that has grown hollow.' },
  { name: 'Ketu aspect Moon in 11th house : Ends', description: 'Community-detachment window closes.' },
  { name: 'Ketu aspect Mercury in 1st house', description: 'Detachment on Bhadra protocol. Old eating-identity dissolves.' },
  { name: 'Ketu aspect Mercury in 1st house : Starts', description: 'Bhadra-detachment window opens.' },
  { name: 'Ketu aspect Mercury in 1st house : Exact', description: 'Peak day. Sit with the protocol feeling weightless; do not over-track.' },
  { name: 'Ketu aspect Mercury in 1st house : Ends', description: 'Bhadra-detachment window closes.' },
  { name: 'Ketu aspect Venus in 7th house', description: 'Detachment on Malavya partner-table. Old shared-cuisine feels finished.' },
  { name: 'Ketu aspect Venus in 7th house : Starts', description: 'Partner-table-detachment window opens.' },
  { name: 'Ketu aspect Venus in 7th house : Exact', description: 'Peak day. Sit with the partner-cuisine quieting.' },
  { name: 'Ketu aspect Venus in 7th house : Ends', description: 'Partner-table-detachment window closes.' },
  { name: 'Ketu aspect Mars in 8th house', description: 'Detachment on Vipareet engine. Old cleanse-loops evaporate.' },
  { name: 'Ketu aspect Mars in 8th house : Starts', description: 'Vipareet-detachment window opens.' },
  { name: 'Ketu aspect Mars in 8th house : Exact', description: 'Peak day. Release the dead cleanse-protocol; field is clearing.' },
  { name: 'Ketu aspect Mars in 8th house : Ends', description: 'Vipareet-detachment window closes.' },
  { name: 'Ketu aspect Jupiter in 4th house', description: 'Detachment on Hamsa home-throne. Old family-recipes feel finished.' },
  { name: 'Ketu aspect Jupiter in 4th house : Starts', description: 'Hamsa-detachment window opens.' },
  { name: 'Ketu aspect Jupiter in 4th house : Exact', description: 'Peak day. Sit with the family-recipe feeling weightless.' },
  { name: 'Ketu aspect Jupiter in 4th house : Ends', description: 'Hamsa-detachment window closes.' },
  { name: 'Ketu aspect Saturn in 5th house', description: 'Detachment on creative-discipline-eating. Old long-arc protocol feels finished.' },
  { name: 'Ketu aspect Saturn in 5th house : Starts', description: 'Creative-detachment window opens.' },
  { name: 'Ketu aspect Saturn in 5th house : Exact', description: 'Peak day. Release the dead regimen; the field clears.' },
  { name: 'Ketu aspect Saturn in 5th house : Ends', description: 'Creative-detachment window closes.' },
  { name: 'Ketu aspect Rahu in 3rd house', description: 'Ketu-Rahu axis stress on viral-cuisine. Old recipe-loops feel finished.' },
  { name: 'Ketu aspect Rahu in 3rd house : Starts', description: 'Viral-cuisine-axis-detachment window opens.' },
  { name: 'Ketu aspect Rahu in 3rd house : Exact', description: 'Peak day. Sit with the recipe-channel quieting.' },
  { name: 'Ketu aspect Rahu in 3rd house : Ends', description: 'Viral-cuisine-axis-detachment window closes.' },
  { name: 'Ketu aspect Ketu in 9th house', description: 'Ketu return on its own placement. Peak dharma-food detachment day. Old ritual-eating attachments dissolve completely.' },
  { name: 'Ketu aspect Ketu in 9th house : Starts', description: 'Ketu-return dharma-food window opens.' },
  { name: 'Ketu aspect Ketu in 9th house : Exact', description: 'Peak Ketu-return day. The ritual-fast attachment evaporates; the principle without ceremony crystallizes.' },
  { name: 'Ketu aspect Ketu in 9th house : Ends', description: 'Ketu-return dharma-food window closes.' },
];

const update = db.prepare(
  'UPDATE events SET description = ? WHERE ascendant = ? AND name = ?'
);

function run() {
  const tx = db.transaction(() => {
    let updated = 0, empty = 0, notFound = 0;
    for (const e of events) {
      if (!e.description) { empty++; continue; }
      const r = update.run(e.description, ASCENDANT, e.name);
      if (r.changes > 0) updated++;
      else notFound++;
    }
    return { updated, empty, notFound };
  });
  return tx();
}

if (require.main === module) {
  const { updated, empty, notFound } = run();
  console.log(
    `[${ASCENDANT} food] ${updated} updated · ${empty} still empty · ` +
    `${notFound} not in DB`,
  );
}

module.exports = { events, ASCENDANT };
